#!/bin/sh
# gen_family_md5pass_fixture.sh -- generate a deterministic fixture file for
#                                   the Phase 5a.6 MAKE_MD5PASS family
#                                   byte-exact validation harness.
#
# Sub-phase 5a.6 (2026-05-23). Family is UNSALTED: each fixture line is
# PASS:<plaintext>, no SALT lines. Same alphabetic + index-suffix +
# rejection-retry uniqueness discipline as gen_e347_fixture.sh.
#
# A single shared fixture drives all 7 GPU-eligible family JOB enums
# (e122/e159/e161/e163/e165/e167/e169) because the family is unsalted
# and the oracle adapts per-algo via oracle_compute_md5pass_family in
# mdxfind.c. So 1 fixture x 7 algos x 2 backends = 14 cells, not 7
# per-algo fixtures.
#
# $Revision: 1.1 $
# $Log: gen_family_md5pass_fixture.sh,v $
# Revision 1.1  2026/05/23 18:40:35  dlr
# *** empty log message ***
#
#
# Usage:
#   ./gen_family_md5pass_fixture.sh <n_pass> <output_file>
#       [pass_minlen] [pass_maxlen]
#
# Defaults: pass_minlen=4 pass_maxlen=20
#
# Examples:
#   ./gen_family_md5pass_fixture.sh 8       family_md5pass/family_smoke.txt
#   ./gen_family_md5pass_fixture.sh 1024    family_md5pass/family_medium.txt
#   ./gen_family_md5pass_fixture.sh 1048576 family_md5pass/family_large.txt
#   ./gen_family_md5pass_fixture.sh 128     family_md5pass/family_edge_minlen.txt 1 4
#   ./gen_family_md5pass_fixture.sh 128     family_md5pass/family_edge_maxlen.txt 56 128

set -e

if [ $# -lt 2 ] || [ $# -gt 4 ]; then
    echo "usage: $0 <n_pass> <output_file> [pass_min] [pass_max]" >&2
    exit 1
fi

N_PASS=$1
OUT=$2
PASS_MIN=${3:-4}
PASS_MAX=${4:-20}

# Deterministic seed 42 mirrors gen_e347_fixture.sh; reproducible byte-for-
# byte across hosts. Suffix-and-retry uniqueness identical to e347; dies
# loud if requested count exceeds the unique combinatorial space (e.g.
# n_pass=100 with pmax=1).
awk -v np="$N_PASS" \
    -v pmin="$PASS_MIN" -v pmax="$PASS_MAX" \
    'function gen_random_str(min_l, max_l, alphabet, alen,    L, s, j, c, span) {
        span = max_l - min_l + 1
        if (span < 1) span = 1
        L = min_l + int(rand() * span)
        if (L < min_l) L = min_l
        if (L > max_l) L = max_l
        s = ""
        for (j = 0; j < L; j++) {
            c = substr(alphabet, 1 + int(rand() * alen), 1)
            s = s c
        }
        return s
    }
    function emit_unique(side_tag, suffix_template, n_items, min_l, max_l,
                         alphabet, alen, seen, MAX_RETRY,    i, s, key, tries) {
        for (i = 0; i < n_items; i++) {
            tries = 0
            while (1) {
                s = gen_random_str(min_l, max_l, alphabet, alen)
                if (suffix_template == "_%d") {
                    key = s "_" i
                } else {
                    key = s
                }
                if (!(key in seen)) break
                tries++
                if (tries > MAX_RETRY) {
                    printf("FATAL: gen_family_md5pass_fixture.sh: cannot "  \
                           "generate unique %s after %d retries at index "  \
                           "%d (min=%d max=%d alphabet=%d) -- requested "   \
                           "count exceeds the unique combinatorial space\n",\
                           side_tag, MAX_RETRY, i, min_l, max_l, alen)      \
                          > "/dev/stderr"
                    exit 2
                }
            }
            seen[key] = 1
            printf("%s:%s\n", side_tag, key)
        }
    }
    BEGIN {
    srand(42)
    printf("# MAKE_MD5PASS family validation fixture, generated by\n")
    printf("# gen_family_md5pass_fixture.sh (sub-phase 5a.6 2026-05-23).\n")
    printf("# n_pass=%d (family is unsalted; no SALT lines)\n", np)
    printf("# pass_min=%d pass_max=%d\n", pmin, pmax)
    printf("# seed=42 deterministic; do not hand-edit.\n")
    printf("# Same fixture drives all 7 GPU-eligible family JOBs\n")
    printf("# (e122/e159/e161/e163/e165/e167/e169).\n")
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    alen = length(alphabet)

    pass_suffix = (pmax >= 6 && pmax - pmin >= 2) ? "_%d" : ""
    MAX_RETRY = 10 * alen + 100

    emit_unique("PASS", pass_suffix, np, pmin, pmax,
                alphabet, alen, pass_seen, MAX_RETRY)
}' > "$OUT"

echo "wrote fixture $OUT (n_pass=$N_PASS pass=$PASS_MIN..$PASS_MAX)" >&2
