#!/bin/bash
# $Revision: 1.6 $
# $Log: build_metallib.sh,v $
# Revision 1.6  2026/05/12 16:47:16  dlr
# Phase 2a plumbing: link gpujob_metal.o, remove Phase 1 stubs from gpu_metal.m, add metal_md5_rules.metal to build_metallib.sh family list. The new worker thread (gpu/gpujob_metal.m rev 1.1, 800 LOC mirror of gpujob_opencl.c subset) takes over the gpujob_init+gpujob_available+gpujob_shutdown symbol exports; Phase 1 stubs in gpu_metal.m at EOF deleted (would duplicate-symbol-link otherwise). Makefile adds gpu/gpujob_metal.o build rule and link prereq. build_metallib.sh per-family compile gets metal_md5_rules.metal added so the metallib link includes the rules walker. Validation on nutshack: Phase 1 regression clean (cell 1 still 500==500 byte-exact CPU/Metal); stderr now prints Metal GPU: 1 gpujob thread started [40 batch buffers]. Kernel-side rules-engine integration (GPU_TEMPLATE_HAS_RULES block in metal_template.metal + rules PSO in gpu_metal.m) is the next dispatch.
#
# Revision 1.5  2026/05/12 13:36:00  dlr
# Phase 1 Metal library builder fresh start (replaces retired Phase 0 design). Per-family TU compilation via xcrun metal (offline AIR); linked into gpu/mdxfind.metallib by xcrun metallib; embedded as byte array in gpu/mdxfind_metallib.h via xxd -i. Phase 1 has ONE family TU (md5: metal_common.metal + metal_md5_core.metal + metal_template.metal); loop structure stays per-family so Phase 2+ families plug in mechanically (Pattern 4: never merge two families into one TU). Build options -std=metal3.0 -O3 -Wall; family-specific -DHASH_WORDS=4 -DHASH_BLOCK_BYTES=64. Verified on dev1.local (Apple M1): produces 12.9 KB metallib.
#
#
# build_metallib.sh — Phase 1 Metal library builder. Mirrors the role
# of gpu_kernel_cache for OpenCL: produce a pre-compiled "metallib"
# blob that the host (gpu_metal.m, out-of-scope for Phase 1 dispatch)
# embeds via gpu/mdxfind_metallib.h.
#
# Phase 1 produces ONE family TU:
#
#   md5: metal_common.metal + metal_md5_core.metal + metal_template.metal
#
# Pattern 4 (memo §12): each family compiles separately. Phase 1 is
# one family; the loop structure stays per-family so Phase 2+ families
# (SHA1, SHA256, ...) plug in mechanically.
#
# Output:
#   gpu/mdxfind.metallib       — Metal AIR library blob.
#   gpu/mdxfind_metallib.h     — generated by `xxd -i` of the blob.
#
# Pipeline:
#   1. cat per-family TU sources into a single .metal file under /tmp.
#   2. xcrun metal -c /tmp/tu.metal -o /tmp/tu.air      (per family)
#   3. xcrun metallib /tmp/*.air -o gpu/mdxfind.metallib (link all)
#   4. xxd -i gpu/mdxfind.metallib > gpu/mdxfind_metallib.h
#
# Must run on a host with the Metal toolchain — dev1.local (Apple
# Silicon) is the primary build host. The local iMac (Radeon 580X)
# also has the Metal toolchain so this script runs locally too.
#
# Non-zero exit on any failure; intended to be wired into the
# top-level Makefile as a dep of gpu_metal.o.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Per-family TU descriptor: family_name=common_file,family_core_file,template_file
# Phase 1: just md5.
FAMILIES=(
    "md5=metal_common.metal,metal_md5_core.metal,metal_md5_rules.metal,metal_template.metal"
)

# Build options: -DHASH_WORDS=4 -DHASH_BLOCK_BYTES=64 are MD5-specific.
# Phase 2+ families pass family-specific defines.
COMMON_OPTS="-std=metal3.0 -O3 -Wall"

TMPDIR="$(mktemp -d /tmp/mdxfind_metallib.XXXXXX)"
trap 'rm -rf "$TMPDIR"' EXIT

AIR_FILES=()

for FAM_DESC in "${FAMILIES[@]}"; do
    FAM_NAME="${FAM_DESC%%=*}"
    FILE_LIST="${FAM_DESC#*=}"
    IFS=',' read -r -a FILES <<< "$FILE_LIST"

    echo "=== Family ${FAM_NAME}: ${FILES[@]} ==="

    # Concatenate sources for this family into a single TU.
    TU_SRC="$TMPDIR/${FAM_NAME}_tu.metal"
    : > "$TU_SRC"
    for F in "${FILES[@]}"; do
        if [ ! -f "$SCRIPT_DIR/$F" ]; then
            echo "FAIL: missing source $SCRIPT_DIR/$F" >&2
            exit 1
        fi
        echo "/* ==== from $F ==== */" >> "$TU_SRC"
        cat "$SCRIPT_DIR/$F" >> "$TU_SRC"
        echo "" >> "$TU_SRC"
    done

    # Family-specific defines.
    case "$FAM_NAME" in
        md5)
            FAM_OPTS="-DHASH_WORDS=4 -DHASH_BLOCK_BYTES=64"
            ;;
        *)
            FAM_OPTS=""
            ;;
    esac

    AIR_OUT="$TMPDIR/${FAM_NAME}.air"
    echo "  -> xcrun metal -c (offline AIR compile)"
    xcrun metal $COMMON_OPTS $FAM_OPTS -c "$TU_SRC" -o "$AIR_OUT" || {
        echo "FAIL: xcrun metal failed for family ${FAM_NAME}" >&2
        echo "TU source preserved at $TU_SRC for debugging" >&2
        trap - EXIT
        exit 1
    }
    AIR_FILES+=("$AIR_OUT")
done

# Link all family AIRs into one metallib.
echo "=== metallib link (${#AIR_FILES[@]} family AIRs) ==="
METALLIB_OUT="$SCRIPT_DIR/mdxfind.metallib"
xcrun metallib "${AIR_FILES[@]}" -o "$METALLIB_OUT" || {
    echo "FAIL: xcrun metallib link failed" >&2
    exit 1
}

ls -la "$METALLIB_OUT"

# Generate the embedded C header.
HEADER_OUT="$SCRIPT_DIR/mdxfind_metallib.h"
echo "=== Generating $HEADER_OUT (xxd -i) ==="
{
    echo "/* Auto-generated from mdxfind.metallib by build_metallib.sh -- do not edit */"
    echo ""
    # `xxd -i` emits `unsigned char NAME[] = { ... };` and `unsigned int NAME_len`.
    # We need stable identifiers, so feed the file via stdin with a known basename.
    cd "$SCRIPT_DIR"
    xxd -i -n "gpu_mdxfind_metallib" "mdxfind.metallib"
} > "$HEADER_OUT"

ls -la "$HEADER_OUT"
echo ""
echo "OK: ${#FAMILIES[@]} family/families built, metallib $(wc -c <"$METALLIB_OUT") bytes."
