/* Auto-generated from gpu_sql5_core.cl -- do not edit */
static const char gpu_sql5_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sql5_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sql5_core.cl — SQL5 (MySQL 4.1+ password) algorithm extension\n"
    " * functions for the generic dispatch template (Memo B Phase B5\n"
    " * sub-batch 6, Tier C).\n"
    " *\n"
    " * SQL5 is the MySQL 4.1+ password hash: SHA1(SHA1(password)). The mdxfind\n"
    " * implementation, however, has an unusual iter loop that distinguishes\n"
    " * SQL5 from a simple sha1(sha1(p)) primitive:\n"
    " *\n"
    " * CPU reference (mdxfind.c JOB_SQL5 at line 25301):\n"
    " *\n"
    " *   for (x = 1; x <= Maxiter; x++) {\n"
    " *     mysha1(cur, len, curin.h);          // FIRST sha1: inner = sha1(input)\n"
    " *     mysha1(curin.h, 20, md5buf.h);      // SECOND sha1: outer = sha1(inner)\n"
    " *     cur = prmd5UC(curin.h, mdbuf, 40);  // hex(UPPERCASE) of FIRST sha1\n"
    " *     len = 40;\n"
    " *     hashcnt++;\n"
    " *     checkhash(&md5buf, 40, x, job);     // probe outer == sha1(sha1(input))\n"
    " *   }\n"
    " *\n"
    " * Per-iter behavior:\n"
    " *   - At iter N, input = (N==1 ? rule-mutated buffer : UPPERCASE_HEX(40)\n"
    " *     of inner from iter N-1).\n"
    " *   - Compute inner_N = sha1(input_N). Compute outer_N = sha1(inner_N).\n"
    " *   - Probe outer_N against compact table (it's the value being looked up\n"
    " *     in MySQL's user table).\n"
    " *   - If iter < Maxiter, prepare input_{N+1} = UPPERCASE_HEX(inner_N).\n"
    " *\n"
    " * Per-algorithm state struct retains BOTH sha1 chains:\n"
    " *   - state_inner[5]: the first sha1's chain (carried across iters as\n"
    " *     the basis for the next iter's UPPERCASE-hex re-feed).\n"
    " *   - h[5]: the second sha1's chain (exposed to template_digest_compare;\n"
    " *     this is what gets matched + emitted).\n"
    " *\n"
    " * The template body's call sequence is:\n"
    " *   template_init(&st)\n"
    " *   template_finalize(&st, buf, len)   -> compute inner + outer, expose\n"
    " *                                         outer in h[]; keep inner in\n"
    " *                                         state_inner[] for iter step.\n"
    " *   for iter 1..Maxiter:\n"
    " *     digest_compare(&st)               -> probe h[]\n"
    " *     if iter < Maxiter:\n"
    " *       template_iterate(&st)           -> uppercase_hex(state_inner) ->\n"
    " *                                          sha1 -> new state_inner; then\n"
    " *                                          sha1(state_inner_BE_20) ->\n"
    " *                                          new h[].\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=5,HASH_BLOCK_BYTES=64\" — same\n"
    " * as SHA1 / SHA1RAW. Distinct cache entry by source-text hash.\n"
    " *\n"
    " * R1 mitigation: single private buffer pattern; no addrspace-cast\n"
    " * helpers. Pattern matches gpu_sha1_core.cl.\n"
    " *\n"
    " * R2: same compression footprint as SHA1 (W[80] schedule footprint\n"
    " * doubled across two sha1_block calls per finalize/iterate). Expected\n"
    " * priv_mem_size on gfx1201 ~ identical to SHA1 (W[80] is a private\n"
    " * scalar inside sha1_block; reused across calls).\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sql5_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 5\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];       /* outer sha1 (exposed) — used by digest_compare */\n"
    "    uint state_inner[5];      /* inner sha1 — basis for next iter's hex feed */\n"
    "} template_state;\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    /* h[] will be set by template_finalize after the outer sha1. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "    /* state_inner is initialized inside template_finalize before the\n"
    "     * inner sha1 absorb. */\n"
    "    st->state_inner[0] = 0x67452301u;\n"
    "    st->state_inner[1] = 0xEFCDAB89u;\n"
    "    st->state_inner[2] = 0x98BADCFEu;\n"
    "    st->state_inner[3] = 0x10325476u;\n"
    "    st->state_inner[4] = 0xC3D2E1F0u;\n"
    "}\n"
    "\n"
    "/* template_transform: stub for interface symmetry. Not used by the SQL5\n"
    " * finalize because we handle padding inside template_finalize directly. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b]     << 24)\n"
    "             | ((uint)block[b + 1] << 16)\n"
    "             | ((uint)block[b + 2] << 8)\n"
    "             |  (uint)block[b + 3];\n"
    "    }\n"
    "    sha1_block(&st->state_inner[0], M);\n"
    "}\n"
    "\n"
    "/* sql5_inner_finalize: classic SHA1 finalize on (data, len) using\n"
    " * st->state_inner as the chain. Mirrors gpu_sha1_core.cl's\n"
    " * template_finalize byte-for-byte but writes to state_inner. */\n"
    "static inline void sql5_inner_finalize(template_state *st,\n"
    "                                       const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Reset inner state to SHA1 IV before absorbing the input. */\n"
    "    st->state_inner[0] = 0x67452301u;\n"
    "    st->state_inner[1] = 0xEFCDAB89u;\n"
    "    st->state_inner[2] = 0x98BADCFEu;\n"
    "    st->state_inner[3] = 0x10325476u;\n"
    "    st->state_inner[4] = 0xC3D2E1F0u;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b]     << 24)\n"
    "                 | ((uint)data[b + 1] << 16)\n"
    "                 | ((uint)data[b + 2] << 8)\n"
    "                 |  (uint)data[b + 3];\n"
    "        }\n"
    "        sha1_block(&st->state_inner[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = 3 - (i & 3);\n"
    "        M[wi] |= ((uint)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = 3 - (rem & 3);\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->state_inner[0], M);\n"
    "    } else {\n"
    "        sha1_block(&st->state_inner[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->state_inner[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* sql5_outer_sha1: feed the 20-byte BE inner-sha1 digest into a fresh\n"
    " * sha1_block and store the result in st->h[]. Single block (20+1+8 = 29\n"
    " * < 56). Mirrors the SHA1RAW iter step exactly. */\n"
    "static inline void sql5_outer_sha1(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    M[0] = st->state_inner[0];\n"
    "    M[1] = st->state_inner[1];\n"
    "    M[2] = st->state_inner[2];\n"
    "    M[3] = st->state_inner[3];\n"
    "    M[4] = st->state_inner[4];\n"
    "    M[5] = 0x80000000u;        /* 0x80 BE at byte 20 */\n"
    "    for (int j = 6; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 0u;\n"
    "    M[15] = 20u * 8u;          /* 160 bits */\n"
    "    /* Reset h[] to SHA1 IV; absorb the prepared block. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "    sha1_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: SQL5 = inner sha1 (over input) + outer sha1 (over\n"
    " * inner). Both states are kept in template_state for the iter step. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    sql5_inner_finalize(st, data, len);\n"
    "    sql5_outer_sha1(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: SQL5 iter. Per CPU reference:\n"
    " *   prev_inner = state_inner (in BE uint32 words)\n"
    " *   uppercase_hex_chars[40] = HEX_UC(prev_inner)\n"
    " *   new_inner = sha1(uppercase_hex_chars[40])  -> updates state_inner\n"
    " *   new_outer = sha1(new_inner_BE_20)          -> updates h[]\n"
    " *\n"
    " * The 40 uppercase hex chars fit in M[0..9]. M[10] = 0x80000000 BE\n"
    " * (padding marker at byte 40), M[14] = 0, M[15] = 320 (40 * 8). Single\n"
    " * block (40 + 1 + 8 = 49 < 56). */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "\n"
    "    /* Build M[0..9] from state_inner[0..4] as 40 BE-encoded UPPERCASE\n"
    "     * hex chars. Each state word produces 8 hex chars (2 M-words BE\n"
    "     * encoded). Mirrors gpu_sha1_core.cl's iter except for character\n"
    "     * case: ('A' - 10) instead of ('a' - 10). */\n"
    "    for (int i = 0; i < 5; i++) {\n"
    "        uint s = st->state_inner[i];\n"
    "        uint b0 = (s >> 24) & 0xff;\n"
    "        uint b1 = (s >> 16) & 0xff;\n"
    "        uint b2 = (s >> 8)  & 0xff;\n"
    "        uint b3 = s & 0xff;\n"
    "        uint hi0 = (b0 >> 4) & 0xf, lo0 = b0 & 0xf;\n"
    "        uint hi1 = (b1 >> 4) & 0xf, lo1 = b1 & 0xf;\n"
    "        uint hi2 = (b2 >> 4) & 0xf, lo2 = b2 & 0xf;\n"
    "        uint hi3 = (b3 >> 4) & 0xf, lo3 = b3 & 0xf;\n"
    "        uint h0 = ((hi0 + ((hi0 < 10) ? '0' : ('A' - 10))) << 8)\n"
    "                |  (lo0 + ((lo0 < 10) ? '0' : ('A' - 10)));\n"
    "        uint h1 = ((hi1 + ((hi1 < 10) ? '0' : ('A' - 10))) << 8)\n"
    "                |  (lo1 + ((lo1 < 10) ? '0' : ('A' - 10)));\n"
    "        uint h2 = ((hi2 + ((hi2 < 10) ? '0' : ('A' - 10))) << 8)\n"
    "                |  (lo2 + ((lo2 < 10) ? '0' : ('A' - 10)));\n"
    "        uint h3 = ((hi3 + ((hi3 < 10) ? '0' : ('A' - 10))) << 8)\n"
    "                |  (lo3 + ((lo3 < 10) ? '0' : ('A' - 10)));\n"
    "        M[i * 2]     = (h0 << 16) | h1;\n"
    "        M[i * 2 + 1] = (h2 << 16) | h3;\n"
    "    }\n"
    "    M[10] = 0x80000000u;        /* 0x80 BE at byte 40 */\n"
    "    for (int j = 11; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 0u;\n"
    "    M[15] = 40u * 8u;           /* 40 hex chars = 320 bits */\n"
    "\n"
    "    /* Reset state_inner to SHA1 IV; absorb the prepared block to compute\n"
    "     * new_inner = sha1(uppercase_hex_40). */\n"
    "    st->state_inner[0] = 0x67452301u;\n"
    "    st->state_inner[1] = 0xEFCDAB89u;\n"
    "    st->state_inner[2] = 0x98BADCFEu;\n"
    "    st->state_inner[3] = 0x10325476u;\n"
    "    st->state_inner[4] = 0xC3D2E1F0u;\n"
    "    sha1_block(&st->state_inner[0], M);\n"
    "\n"
    "    /* Compute new_outer = sha1(new_inner_BE_20) into h[]. */\n"
    "    sql5_outer_sha1(st);\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    /* SHA1 state is BE; compact table is keyed on LE — bswap32 first 4. */\n"
    "    uint h0 = bswap32(st->h[0]);\n"
    "    uint h1 = bswap32(st->h[1]);\n"
    "    uint h2 = bswap32(st->h[2]);\n"
    "    uint h3 = bswap32(st->h[3]);\n"
    "    return probe_compact_idx(\n"
    "        h0, h1, h2, h3,\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h, \\\n"
    "                   (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                   (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
;
