/* Auto-generated from gpu_kernel_a_bruteforce.cl -- do not edit */
static const char gpu_kernel_a_bruteforce_str[] =
    "/*\n"
    " * $Revision: $\n"
    " * $Log: $\n"
    " *\n"
    " */\n"
    "/* gpu_kernel_a_bruteforce.cl -- Kernel A4 (brute-force) candidate producer.\n"
    " *\n"
    " * Production kernel A variant A4 per Phase 1a sub-phase 1a.4 spec\n"
    " *   project_kernel_a_a4_bruteforce_spec_2026-05-21.md.\n"
    " *\n"
    " * A4 closes the Phase 1a hand-written kernel-A family (A1 rules, A2 masks,\n"
    " * A3 rules+masks, A4 brute-force). Unlike A1/A2/A3, A4 consumes NO input\n"
    " * word stream -- the candidate IS the mask expansion. Per parent spec the\n"
    " * BF chunk descriptor (bf_mask_start, bf_offset_per_word, bf_num_masks)\n"
    " * arrives on OCLParams and the host pre-sizes num_words as the synthetic\n"
    " * lane count via the procjob short-circuit (mdxfind.c:10498-10501).\n"
    " *\n"
    " * Output flows through the same buffer-quadruple API as A1/A2/A3\n"
    " * (b_packed_buf, b_chunk_index, b_kernelA_state, b_params), making any\n"
    " * kernel B consumer that obeys the buffer-quadruple contract a valid\n"
    " * downstream consumer.\n"
    " *\n"
    " * Topology (per spec sec.3):\n"
    " *   global_size = num_words * bf_num_masks\n"
    " *   synthetic_word_idx   = gid / bf_num_masks\n"
    " *   mask_offset_in_chunk = gid % bf_num_masks\n"
    " *   absolute_mask_idx    = bf_mask_start\n"
    " *                        + synthetic_word_idx * bf_offset_per_word\n"
    " *                        + mask_offset_in_chunk\n"
    " *\n"
    " * D11.1.a (pure BF only): no rule axis; no prepend mask axis. The kernel\n"
    " * defends n_prepend == 0 as a BF invariant (BF fast-path eligibility gate\n"
    " * at mdxfind.c:49032 requires MaskPrependLen == 0).\n"
    " *\n"
    " * D11.2.a (charset wire encoding reuse): identical class-encoded charset\n"
    " * table as A2; the 4 persistent mask buffers (mask_pattern_prepend, mask_-\n"
    " * pattern_append, mask_charsets, mask_class_counts) are reused verbatim\n"
    " * from gpu_opencl_kernel_a_upload_mask_buffers. Zero new persistent\n"
    " * buffers. The mask_pattern_prepend slot is bound to a zeroed buffer at\n"
    " * host dispatch time for arg-symmetry with A2; the kernel never reads it.\n"
    " *\n"
    " * D11.3.a (absolute_mask_idx integer width): ulong (uint64). mdxfind\n"
    " * supports keyspaces > 2^32 (10-digit BF = 10^10), and bf_mask_start is\n"
    " * already ulong at offset 8 of OCLParams. uint32 throughout would\n"
    " * truncate; the ladder operates in ulong via the mask_expand_into_gpu\n"
    " * helper (signature matches A2).\n"
    " *\n"
    " * D11.4.a (combined OpenCL + Metal in sub-phase 1a.4): the Metal twin\n"
    " * (metal_kernel_a_bruteforce.metal) is produced by the cl2metal.py +\n"
    " * post_kernel_a_metal.py translator chain. The translator R1-R6 rules\n"
    " * are family-generic (A1/A2/A3 proven); A4 adds zero new R-rules. R1\n"
    " * (apply_rule rename) is a no-op for A4 since A4 has no rule walker.\n"
    " *\n"
    " * Mechanical lineage:\n"
    " *  - mask_expand_into_gpu and mask_pattern_total are VERBATIM COPIES of\n"
    " *    gpu_kernel_a_masks.cl rev 1.3 mask helpers. Spec R8 acknowledges\n"
    " *    the duplication; Phase 1b will hoist into a shared .cl.frag. Until\n"
    " *    then any change to the A2 mask helpers MUST BE MIRRORED HERE\n"
    " *    MANUALLY.\n"
    " *  - The kernel function cand_bruteforce_phase0 is structurally minimal:\n"
    " *    decode params, compute (synthetic_word_idx, mask_offset_in_chunk),\n"
    " *    materialize the append mask into a private uchar[MAX_MASK_POS_GPU]\n"
    " *    buffer, atomic-reserve a slot + byte offset, write [len][bytes].\n"
    " *\n"
    " * Authoritative buffer contract:\n"
    " *   project_two_kernel_candidate_buffer_contract.md\n"
    " * Phase 1a A4-variant spec:\n"
    " *   project_kernel_a_a4_bruteforce_spec_2026-05-21.md\n"
    " *\n"
    " * Contract per buffer (identical to A1/A2/A3):\n"
    " *   b_packed_buf        - [len][bytes][len][bytes]... post-mask candidates.\n"
    " *                         len byte stored as uchar; bytes follow uncompressed.\n"
    " *                         Written at slot's reserved byte offset.\n"
    " *                         Layout: [final_len][appbuf...] -- no input word\n"
    " *                         component since BF has no input stream.\n"
    " *   b_chunk_index       - uint32 per slot. b_chunk_index[slot] = byte offset\n"
    " *                         into b_packed_buf where this candidate's len byte\n"
    " *                         lives. Pure physical byte offsets only.\n"
    " *   b_kernelA_state     - small counter buffer (same layout as A1/A2/A3):\n"
    " *                           offset 0 : uint slot_counter   (atomic_inc)\n"
    " *                           offset 4 : uint byte_counter   (atomic_add for\n"
    " *                                                            variable-size\n"
    " *                                                            byte reservation)\n"
    " *                           offset 8 : uint overflow_flag  (set if either\n"
    " *                                                            counter exceeds\n"
    " *                                                            its capacity)\n"
    " *\n"
    " * Walker behavior:\n"
    " *   1. Decode payload -> params. Read num_words, bf_num_masks, app_len,\n"
    " *      pre_len, bf_mask_start, bf_offset, packed_size.\n"
    " *   2. Compute total = num_words * bf_num_masks; guard gid >= total.\n"
    " *   3. Decompose gid -> (synthetic_word_idx, mask_offset_in_chunk).\n"
    " *   4. Compute absolute_mask_idx in ulong per topology formula.\n"
    " *   5. Materialize appbuf via mask_expand_into_gpu(absolute_mask_idx,\n"
    " *      mask_pattern_append, app_len, ...).\n"
    " *   6. Defensive guard: pre_len == 0 (BF invariant per mdxfind.c:49032);\n"
    " *      final_len in [1, 255].\n"
    " *   7. Reserve slot + byte offset (identical atomic discipline to A2);\n"
    " *      write [final_len][appbuf bytes] into b_packed_buf; record byte\n"
    " *      offset in b_chunk_index[slot].\n"
    " *\n"
    " * Geometry: BF dispatch (NEW vs A2's word-major, A3's rule-major):\n"
    " *   global_size          = num_words * bf_num_masks\n"
    " *   synthetic_word_idx   = gid / bf_num_masks\n"
    " *   mask_offset_in_chunk = gid % bf_num_masks\n"
    " *\n"
    " * Reused primitives from gpu_common.cl: OCLParams struct only.\n"
    " *   - No md5_block / md5_buf / md5_to_hex_lc reference (kernel A pure).\n"
    " *   - No probe_compact_idx reference.\n"
    " *   - No EMIT_HIT_N reference.\n"
    " *\n"
    " * OCLParams fields consumed by A4:\n"
    " *   mask_start          = bf_mask_start (absolute mask cursor at chunk start)\n"
    " *   num_words           = synthetic lane count (per-chunk; pre-sized by host)\n"
    " *   num_masks           = bf_num_masks (per-iter mask range)\n"
    " *   n_prepend           = 0 (BF invariant; A4 reads as defensive guard)\n"
    " *   n_append            = MaskAppendLen (mask byte count per candidate)\n"
    " *   base_word_idx       = host-set (for future kernel B attribution)\n"
    " *   packed_size         = bytes available in b_packed_buf\n"
    " *   mask_offset_per_word = bf_offset_per_word (per-lane mask stride)\n"
    " *   inner_iter          = read but NOT used (A4 v1 ignores inner_iter > 1;\n"
    " *                          Phase 1a.4.x deferred)\n"
    " *\n"
    " * OCLParams fields NOT consumed by A4 (set by host but ignored):\n"
    " *   num_rules           (no rule axis)\n"
    " *   input_cursor_start  (A4 v1 single-shot per dispatch)\n"
    " *   rule_cursor_start   (no rule axis)\n"
    " */\n"
    "\n"
    "/* 2026-05-30 long-mask amendment: A4 absorbs the new descriptor wire\n"
    " * format via helper rename + 1-byte-END prebuf binding. The kernel-arg\n"
    " * signature is unchanged; the host now uploads a 320 B descriptor\n"
    " * stream into mask_pattern_append and a 1-byte END descriptor into\n"
    " * mask_pattern_prepend. params.n_prepend = 1 (just the END byte),\n"
    " * params.n_append = app descriptor byte length.\n"
    " *\n"
    " * BF invariant `pre_len == 0` translates post-amendment to \"prebuf walker\n"
    " * sees END at offset 0 and returns 0 expanded bytes\" -- the kernel just\n"
    " * skips the prebuf composition naturally without an explicit guard. */\n"
    "\n"
    "/* ==== A4_PROFILE_VARIANT scaffolding (2026-05-30, BF-engine decomposition) ===\n"
    " * Per architect spec project_kernel_a_a4_profile_variant_spec_2026-05-30.md\n"
    " * D2.a (V0..V5). When kernel is JIT-built with -DA4_PROFILE_VARIANT=N\n"
    " * (N in 1..5), per-lane body is progressively stubbed. V0 (macro undefined)\n"
    " * = byte-identical to production cand_bruteforce_phase0.\n"
    " *\n"
    " * Macro NAME differs from A1's PROFILE_VARIANT so A1 + A4 programs can\n"
    " * coexist in the same JIT context without cross-contamination if both\n"
    " * env vars are set (per spec §4 D1.a).\n"
    " *\n"
    " * Variant semantics (V0-V_N = component cost-share):\n"
    " *   V0 baseline -- full cand_bruteforce_phase0 (uint4 stores by default\n"
    " *      per 2026-05-30 A4 C5 default-on refactor; see V0 site below).\n"
    " *   V1 no atomic claim (per-lane gid*256 strided offset; per-byte write\n"
    " *      still happens). Measures atomic_add cost (CAVEAT: likely\n"
    " *      CONFOUNDED on NVIDIA/AGX/RDNA per spec §9 R1 + A1 #346/#354\n"
    " *      priors -- strided offset breaks SLC write coalescing).\n"
    " *   V2 no per-byte write (atomic claim still runs; per-byte loop +\n"
    " *      chunk_index store omitted). Measures C5 per-byte write cost\n"
    " *      share. Slot counter intentionally NOT incremented so host\n"
    " *      actual_slots stays 0.\n"
    " *   V3 stub charset walk (mask_expand_run_into_gpu returns minimal\n"
    " *      fixed length, fills outbuf with 'A' without consulting descriptor\n"
    " *      stream or charset table). EXPECTED A4 DOMINANT measurement;\n"
    " *      V0-V3 = charset-walk (C3) cost share.\n"
    " *   V4 decode-only (gid decompose + absolute_mask_idx ladder, then\n"
    " *      return BEFORE mask_expand_run_into_gpu). V4 - V5 = C2 decode +\n"
    " *      index-arithmetic cost share.\n"
    " *   V5 empty kernel (return immediately BEFORE param decode). Measures\n"
    " *      C1 dispatch overhead + WG scheduling baseline.\n"
    " *\n"
    " * Variants V1/V3/V4/V5: b_kernelA_state slot_counter and byte_counter\n"
    " * untouched (or restored to 0 implicitly). V2 atomic_add still fires\n"
    " * but slot_counter stays 0. Host sees actual_slots == 0 and the\n"
    " * harness-mode return path short-circuits. Crack-parity for V1..V5 is\n"
    " * INTENTIONALLY NOT preserved (timing-only stubs).\n"
    " *\n"
    " * 2026-05-30 A4 C5 DEFAULT-ON REFACTOR: the V6 cell that previously held\n"
    " * the env-gated KNOBG variant has been REMOVED. The V0 baseline now\n"
    " * unconditionally uses uint4 (16-byte) device stores -- the Knob-G-analog\n"
    " * shape that V6 was measuring is permanently the production path. Setting\n"
    " * A4_PROFILE_VARIANT=6 falls through to V0 (the active range is 0..5).\n"
    " *\n"
    " * Host gate (per spec §4 R5): activated ONLY when KERNEL_A_VARIANT=4\n"
    " * is also active, via gpu_opencl_kernel_a4_profile_variant() accessor. */\n"
    "\n"
    "/* Wire-format tags (must match mdxfind.c host packer). */\n"
    "#define GPU_MASK_DESC_TAG_LIT   0x00u\n"
    "#define GPU_MASK_DESC_TAG_VAR   0x01u\n"
    "#define GPU_MASK_DESC_TAG_END   0xFFu\n"
    "\n"
    "/* Per-side caps (must match mdxfind.c host defines). */\n"
    "#define GPU_MASK_VAR_CAP        16\n"
    "#define GPU_MASK_LIT_BYTES_CAP  224\n"
    "#define GPU_MASK_DESC_BYTES_CAP 320\n"
    "#define GPU_MASK_SIDE_EXPANDED_CAP (GPU_MASK_LIT_BYTES_CAP + GPU_MASK_VAR_CAP)\n"
    "\n"
    "/* Deprecated alias retained for grep compatibility. */\n"
    "#define MAX_MASK_POS_GPU       16\n"
    "#define MASK_LITERAL_SENTINEL  0xffu\n"
    "\n"
    "/* Bounds: final candidate length cap. The [len] uchar byte caps at 255\n"
    " * regardless. For BF the final candidate is purely the append mask\n"
    " * expansion so final_len == app_len <= MAX_MASK_POS_GPU (which is itself\n"
    " * <= 16 in practice). The 255 cap is structural -- we early-return rather\n"
    " * than corrupt the [len] slot under any pathological future scaling. */\n"
    "#define MASK_FINAL_LEN_LIMIT   255u\n"
    "\n"
    "/* Kernel-A state buffer offsets. Single source of truth for host wiring\n"
    " * to mirror via fixed-offset writes/reads. Identical to A1/A2/A3. */\n"
    "#define KERNELA_STATE_SLOT_COUNTER   0u\n"
    "#define KERNELA_STATE_BYTE_COUNTER   4u\n"
    "#define KERNELA_STATE_OVERFLOW_FLAG  8u\n"
    "#define KERNELA_STATE_BYTES         12u\n"
    "\n"
    "/* Charset table flat-array stride. MASK_MAX_CLASSES * 256 bytes total. */\n"
    "#define MASK_CHARSET_STRIDE          256u\n"
    "\n"
    "/* ==== Mask expander helper ============================================\n"
    " *\n"
    " * VERBATIM COPY from gpu_kernel_a_masks.cl rev 1.3 (Phase 1a sub-phase\n"
    " * 1a.2). Spec R8 TODO: hoist into a shared .cl.frag in Phase 1b. Until\n"
    " * then any change to A2's helper MUST be mirrored here manually.\n"
    " *\n"
    " * Literal port of mask_expand_into from mdxfind.c lines 7646-7660:\n"
    " *\n"
    " *   for (i = patlen - 1; i >= 0; i--) {\n"
    " *       if (pattern[i].classid == MASK_LITERAL)\n"
    " *           buf[i] = pattern[i].literal;\n"
    " *       else {\n"
    " *           buf[i] = mc->chars[index % mc->count];\n"
    " *           index /= mc->count;\n"
    " *       }\n"
    " *   }\n"
    " *\n"
    " * GPU adaptations:\n"
    " *  - pattern is a flat 2-byte-per-entry uchar buffer; classid at offset\n"
    " *    i*2, literal at offset i*2+1. MASK_LITERAL_SENTINEL (0xff) replaces\n"
    " *    the CPU's signed -1.\n"
    " *  - mask_charsets is the flat 16*256 byte table; mask_class_counts is\n"
    " *    the uint32-per-class count vector.\n"
    " *  - outbuf is thread-private (the apply path passes a stack array).\n"
    " *  - index is ulong to handle absolute mask indices up to 2^63; the\n"
    " *    division ladder operates on running ulong values.\n"
    " *\n"
    " * Static inline (kernel A1 convention; no noinline needed since this\n"
    " * helper has no hash compression). */\n"
    "/* 2026-05-30 amendment: walker rewritten for run-descriptor wire\n"
    " * format (Design Y). 2-pass: scan descriptor copying literals + recording\n"
    " * VAR positions; then expand VARs HIGH-TO-LOW to preserve CPU's\n"
    " * right-to-left consumption semantics. */\n"
    "static int mask_expand_run_into_gpu(\n"
    "    ulong idx,\n"
    "    __global const uchar *desc,\n"
    "    uint desc_bytes,\n"
    "    __global const uchar *mask_charsets,\n"
    "    __global const uint  *mask_class_counts,\n"
    "    uchar *outbuf)\n"
    "{\n"
    "#if defined(A4_PROFILE_VARIANT) && A4_PROFILE_VARIANT == 3\n"
    "    /* V3 stub: skip the EXPENSIVE part of the charset walk (the modulo\n"
    "     * + global-byte-load + idx/=cc ladder per VAR), but PRESERVE the\n"
    "     * output length contract so downstream host caps don't overflow.\n"
    "     *\n"
    "     * Compute the true expanded length cheaply (one pass scanning the\n"
    "     * descriptor stream summing LIT lens + counting VARs -- same shape\n"
    "     * as the V0 pass 1 walk, but WITHOUT the costly VAR pass 2). Then\n"
    "     * fill outbuf with fixed 'A' to that length. V0_us - V3_us\n"
    "     * approximates the VAR pass-2 cost share (C3b + C3c per spec §2);\n"
    "     * the LIT scan (C3a) is shared between V0 and V3, so V3 measures\n"
    "     * only the per-VAR charset-fetch + divide-ladder elimination.\n"
    "     *\n"
    "     * Per spec §2: V3 is the \"primary A4 expected dominant\" measurement.\n"
    "     * The aggregate (V0-V3) IS still expected to dominate on A4 because\n"
    "     * the per-VAR expansion (the actual stubbed work) is the dominant\n"
    "     * compute for the brute-force engine. */\n"
    "    (void)idx;\n"
    "    (void)mask_charsets;\n"
    "    (void)mask_class_counts;\n"
    "    int stub_len = 0;\n"
    "    {\n"
    "        uint p = 0;\n"
    "        while (p < desc_bytes) {\n"
    "            uchar tag = desc[p++];\n"
    "            if (tag == GPU_MASK_DESC_TAG_END) break;\n"
    "            if (tag == GPU_MASK_DESC_TAG_LIT) {\n"
    "                if (p + 2u > desc_bytes) break;\n"
    "                uint lit_len = (uint)desc[p] | ((uint)desc[p + 1u] << 8);\n"
    "                p += 2u;\n"
    "                if (p + lit_len > desc_bytes) break;\n"
    "                stub_len += (int)lit_len; p += lit_len;\n"
    "            } else if (tag == GPU_MASK_DESC_TAG_VAR) {\n"
    "                if (p + 1u > desc_bytes) break;\n"
    "                p++;\n"
    "                stub_len += 1;\n"
    "            } else break;\n"
    "        }\n"
    "    }\n"
    "    if (stub_len < 0) stub_len = 0;\n"
    "    if (stub_len > GPU_MASK_SIDE_EXPANDED_CAP) stub_len = GPU_MASK_SIDE_EXPANDED_CAP;\n"
    "    for (int i = 0; i < stub_len; i++) outbuf[i] = 'A';\n"
    "    return stub_len;\n"
    "#else\n"
    "    uchar var_classids[GPU_MASK_VAR_CAP];\n"
    "    uint  var_outpos[GPU_MASK_VAR_CAP];\n"
    "    int   n_vars  = 0;\n"
    "    int   out_len = 0;\n"
    "    uint  p       = 0;\n"
    "    while (p < desc_bytes) {\n"
    "        uchar tag = desc[p++];\n"
    "        if (tag == GPU_MASK_DESC_TAG_END) break;\n"
    "        if (tag == GPU_MASK_DESC_TAG_LIT) {\n"
    "            if (p + 2u > desc_bytes) break;\n"
    "            uint lit_len = (uint)desc[p] | ((uint)desc[p + 1u] << 8);\n"
    "            p += 2u;\n"
    "            if (p + lit_len > desc_bytes) break;\n"
    "            for (uint i = 0; i < lit_len; i++) outbuf[out_len + (int)i] = desc[p + i];\n"
    "            out_len += (int)lit_len; p += lit_len;\n"
    "        } else if (tag == GPU_MASK_DESC_TAG_VAR) {\n"
    "            if (p + 1u > desc_bytes) break;\n"
    "            uchar cid = desc[p++];\n"
    "            if (n_vars >= GPU_MASK_VAR_CAP) break;\n"
    "            var_classids[n_vars] = cid; var_outpos[n_vars] = (uint)out_len;\n"
    "            outbuf[out_len] = 0; out_len++; n_vars++;\n"
    "        } else break;\n"
    "    }\n"
    "    for (int i = n_vars - 1; i >= 0; i--) {\n"
    "        uint cid = (uint)var_classids[i];\n"
    "        uint cc  = mask_class_counts[cid]; if (cc == 0u) cc = 1u;\n"
    "        outbuf[var_outpos[i]] = mask_charsets[cid * MASK_CHARSET_STRIDE\n"
    "                                              + (uint)(idx % (ulong)cc)];\n"
    "        idx /= (ulong)cc;\n"
    "    }\n"
    "    return out_len;\n"
    "#endif  /* A4_PROFILE_VARIANT == 3 */\n"
    "}\n"
    "\n"
    "/* ==== Total-cardinality helper =========================================\n"
    " *\n"
    " * VERBATIM COPY from gpu_kernel_a_masks.cl rev 1.3 (Phase 1a sub-phase\n"
    " * 1a.2). Same hoist note as mask_expand_into_gpu applies.\n"
    " *\n"
    " * Compute the product of class sizes for a (pattern, patlen) pair.\n"
    " * Returns 1 when patlen == 0 (matches CPU mdxfind convention; MaskTotal\n"
    " * is 1 when the corresponding side is unused). Returns 1 also for any\n"
    " * literal-only pattern (literal positions contribute factor 1).\n"
    " *\n"
    " * NOTE: A4 does not actually CALL mask_pattern_total in the kernel body\n"
    " * (the host supplies bf_num_masks directly via OCLParams.num_masks, and\n"
    " * the absolute_mask_idx formula carries the stride explicitly). The\n"
    " * helper is kept here byte-identical to A2 for translator stability\n"
    " * (cl2metal.py overlay shape) and Phase 1b hoist consistency. */\n"
    "static inline ulong mask_pattern_total(\n"
    "    __global const uchar *pattern,\n"
    "    uint patlen,\n"
    "    __global const uint  *mask_class_counts)\n"
    "{\n"
    "    ulong total = 1ul;\n"
    "    for (uint i = 0; i < patlen; i++) {\n"
    "        uchar cid = pattern[i * 2];\n"
    "        if (cid != MASK_LITERAL_SENTINEL) {\n"
    "            total *= (ulong)mask_class_counts[(uint)cid];\n"
    "        }\n"
    "    }\n"
    "    return total;\n"
    "}\n"
    "\n"
    "/* ---- Kernel A4 (brute-force) production kernel -------------------\n"
    " *\n"
    " * Payload layout (per spec sec.6 \"Payload structure\"):\n"
    " *\n"
    " *   offset   0 : OCLParams params         (128 bytes)\n"
    " *   offset 128 : uint hit_count           (4 bytes; reserved for payload\n"
    " *                                            symmetry; unused by kernel A)\n"
    " *\n"
    " * Total payload size = 132 bytes. A4 does NOT carry word_offset[] /\n"
    " * packed_words[] tails because BF has no input word stream -- the\n"
    " * candidate IS the mask expansion. The mask_pattern_prepend arg is\n"
    " * host-bound to a zeroed buffer for arg-symmetry with A2.\n"
    " *\n"
    " * 8-arg signature: byte-identical to A2. mask_pattern_prepend slot\n"
    " * present but unread (kernel gates on pre_len == 0 via the BF invariant).\n"
    " *\n"
    " * params.base_word_idx is read by kernel B (host attribution); A4 does\n"
    " * not consume it directly. The host sets it before dispatch.\n"
    " *\n"
    " * params.packed_size is read as the b_packed_buf capacity. Overflow\n"
    " * detection: any candidate whose reservation would push byte_counter\n"
    " * past packed_size sets overflow_flag and returns without writing.\n"
    " *\n"
    " * Output buffer caps:\n"
    " *   b_packed_buf       capacity = params.packed_size bytes\n"
    " *   b_chunk_index      capacity = params.num_words * params.num_masks slots\n"
    " *                                  (worst case: every (lane, mask) emits\n"
    " *                                   one slot -- no rejection path in A4\n"
    " *                                   under the BF invariant).\n"
    " */\n"
    "\n"
    "__kernel\n"
    "void cand_bruteforce_phase0(\n"
    "    __global uchar         *payload,\n"
    "    __global const uchar   *mask_pattern_prepend,\n"
    "    __global const uchar   *mask_pattern_append,\n"
    "    __global const uchar   *mask_charsets,\n"
    "    __global const uint    *mask_class_counts,\n"
    "    __global uchar         *b_packed_buf,\n"
    "    __global uint          *b_chunk_index,\n"
    "    __global volatile uint *b_kernelA_state\n"
    "    )\n"
    "{\n"
    "#if defined(A4_PROFILE_VARIANT) && A4_PROFILE_VARIANT == 5\n"
    "    /* V5: empty kernel; return BEFORE any payload decode. Measures C1\n"
    "     * (dispatch overhead + WG scheduling + kernel launch latency). */\n"
    "    return;\n"
    "#endif\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words      = params.num_words;\n"
    "    uint bf_num_masks = params.num_masks;\n"
    "    uint app_dbytes   = params.n_append;              /* descriptor stream byte length */\n"
    "    /* n_prepend is now descriptor byte length (==1 for A4's END-only prebuf);\n"
    "     * A4 never composes prebuf, so we ignore it post-amendment. */\n"
    "    ulong bf_start    = params.mask_start;\n"
    "    uint bf_offset    = params.mask_offset_per_word;\n"
    "\n"
    "    uint total = n_words * bf_num_masks;\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint synthetic_word_idx   = gid / bf_num_masks;\n"
    "    uint mask_offset_in_chunk = gid % bf_num_masks;\n"
    "\n"
    "    ulong absolute_mask_idx = bf_start\n"
    "                            + (ulong)synthetic_word_idx * (ulong)bf_offset\n"
    "                            + (ulong)mask_offset_in_chunk;\n"
    "\n"
    "#if defined(A4_PROFILE_VARIANT) && A4_PROFILE_VARIANT == 4\n"
    "    /* V4: decode-only -- everything up through absolute_mask_idx is done\n"
    "     * (C2 component); NO mask_expand, NO atomic, NO write. Sentinel\n"
    "     * side-effect on unreachable bit pattern keeps absolute_mask_idx\n"
    "     * live (compiler must not dead-strip the ulong ladder). V4 - V5 =\n"
    "     * decode + index-arithmetic (C2) cost share; V3 - V4 = charset walk\n"
    "     * (C3) isolated. */\n"
    "    if (absolute_mask_idx == 0xffffffffffffffffUL) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 0u);\n"
    "    }\n"
    "    return;\n"
    "#endif\n"
    "\n"
    "    /* Per-thread expanded-mask scratch (240 B for new wire format). */\n"
    "    uchar appbuf[GPU_MASK_SIDE_EXPANDED_CAP];\n"
    "\n"
    "    int applen = mask_expand_run_into_gpu(absolute_mask_idx,\n"
    "                                          mask_pattern_append, app_dbytes,\n"
    "                                          mask_charsets, mask_class_counts,\n"
    "                                          appbuf);\n"
    "\n"
    "    /* Final candidate length: [appbuf] only -- no prebuf, no input word. */\n"
    "    uint final_len = (uint)applen;\n"
    "    if (final_len == 0u || final_len > MASK_FINAL_LEN_LIMIT) return;\n"
    "\n"
    "    /* --- Reserve a candidate slot ---------------------------------\n"
    "     * Identical atomic discipline to A1/A2/A3: byte reservation first,\n"
    "     * then capacity guard, then slot reservation. Overflow flag latched\n"
    "     * on either overflow. */\n"
    "    uint need_bytes = 1u + final_len;   /* [len][bytes] */\n"
    "\n"
    "#if defined(A4_PROFILE_VARIANT) && A4_PROFILE_VARIANT == 1\n"
    "    /* V1 (no atomic claim): substitute per-lane deterministic offsets\n"
    "     * for atomic_add slot + byte reservation. Per-byte write STILL\n"
    "     * HAPPENS so V0 - V1 attributes the atomic cost (CAVEAT: confounded\n"
    "     * per spec §9 R1 -- strided gid*256 offset breaks SLC write\n"
    "     * coalescing on NVIDIA/AGX/RDNA). slot_counter + byte_counter stay\n"
    "     * at zero (no atomic = no increment) so host sees actual_slots == 0\n"
    "     * and harness short-circuits.\n"
    "     *\n"
    "     * Capacity guards: per spec §3 V1 description -- the fake byte_off\n"
    "     * = gid * 256 stays within pre-allocated packed buffer for any gid\n"
    "     * covered by the host's chunk cap; defensively re-check. */\n"
    "    uint byte_off = gid * 256u;\n"
    "    uint slot     = gid;\n"
    "    if (byte_off + need_bytes > params.packed_size) return;\n"
    "    if (slot >= total) return;\n"
    "    b_packed_buf[byte_off] = (uchar)final_len;\n"
    "    {\n"
    "        uint p = byte_off + 1u;\n"
    "        for (int i = 0; i < applen; i++) b_packed_buf[p++] = appbuf[i];\n"
    "    }\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "#elif defined(A4_PROFILE_VARIANT) && A4_PROFILE_VARIANT == 2\n"
    "    /* V2 (no candidate write): atomic claim still runs (so V0 - V2\n"
    "     * attributes the per-byte write loop C5). Per-byte memcpy + index\n"
    "     * store are removed. slot_counter intentionally NOT incremented\n"
    "     * (host actual_slots stays 0 -> harness short-circuits). Use a\n"
    "     * private read-write of byte_counter to keep the atomic_add live\n"
    "     * so the compiler does not fold it. */\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes);\n"
    "    /* Keep byte_off live without producing a visible effect (or-with-0\n"
    "     * is a no-op functionally; prevents DCE of the atomic_add). */\n"
    "    if (byte_off == 0xffffffffu) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 0u);\n"
    "    }\n"
    "    /* Slot-counter NOT incremented. Per-byte write loop + chunk_index\n"
    "     * store omitted (the measured target). */\n"
    "#else\n"
    "    /* V0 (production baseline). 2026-05-30 A4 C5 default-on refactor:\n"
    "     * the uint4 (16-byte) device-store write path is now the ONLY write\n"
    "     * path -- the env-gated KNOBG_A4_VEC_WRITE preprocessor branch and\n"
    "     * the legacy per-byte loop have both been removed. Per the paired\n"
    "     * Phase 0 verdicts (project_a4_c5_phase0_opencl_ptx_verdict_-\n"
    "     * 2026-05-30 + project_a4_c5_phase0_metal_air_verdict_2026-05-30):\n"
    "     * explicit V_uint4 stores lower to 16-byte device stores on both\n"
    "     * Apple AGX (metal-llc) and NVIDIA Pascal/Maxwell (NVVM); the legacy\n"
    "     * V_char per-byte loop remained scalar (st.global.u8 / store i8).\n"
    "     * NVIDIA delivered -15% Pascal / -21% Maxwell wall on the production\n"
    "     * fixture; Apple AGX delivered null (load-side bound; see followup).\n"
    "     *\n"
    "     * Round need_bytes up to a 16-byte multiple. The atomic shape is a\n"
    "     * single atomic_add; only the value is rounded. Slot-start alignment\n"
    "     * proof: base ptr 16-aligned + each running sum adds a multiple of\n"
    "     * 16 -> every byte_off is 16-aligned. */\n"
    "    uint need_aligned = (need_bytes + 15u) & ~15u;\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_aligned);\n"
    "\n"
    "    /* Capacity guard: use the post-rounding byte count for the bound\n"
    "     * check (otherwise the tail uint4 stores could spill past packed). */\n"
    "    if (byte_off + need_aligned > params.packed_size) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    uint slot = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u], 1u);\n"
    "\n"
    "    /* Slot-index capacity: bounded by num_words * num_masks (uniform\n"
    "     * emit-rate; no rule rejection, no length-vary). */\n"
    "    if (slot >= total) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    /* --- Write [len][bytes] into packed buf via uint4 stores ----------\n"
    "     * Direct-from-appbuf uint4 stores (D5.a shape -- no stage[] copy).\n"
    "     * Build the [len|bytes] payload via shifted reads from the thread-\n"
    "     * private appbuf into 16-byte uint4 packets. need_aligned/16 stores;\n"
    "     * tail reads past applen are safe (appbuf is 240 B private), pad\n"
    "     * bytes in the dst tail are undefined but never inspected by the\n"
    "     * consumer (plen byte caps the read). emit_len cap for A4 is\n"
    "     * MaskAppendLen <= MAX_MASK_POS_GPU = 16; need_aligned in [16,32];\n"
    "     * nvec in [1,2]. */\n"
    "    {\n"
    "        __global uint4 *dst = (__global uint4 *)(b_packed_buf + byte_off);\n"
    "        uint hdr0 = (uint)final_len\n"
    "                  | ((uint)appbuf[0]  <<  8)\n"
    "                  | ((uint)appbuf[1]  << 16)\n"
    "                  | ((uint)appbuf[2]  << 24);\n"
    "        uint hdr1 = (uint)appbuf[3]\n"
    "                  | ((uint)appbuf[4]  <<  8)\n"
    "                  | ((uint)appbuf[5]  << 16)\n"
    "                  | ((uint)appbuf[6]  << 24);\n"
    "        uint hdr2 = (uint)appbuf[7]\n"
    "                  | ((uint)appbuf[8]  <<  8)\n"
    "                  | ((uint)appbuf[9]  << 16)\n"
    "                  | ((uint)appbuf[10] << 24);\n"
    "        uint hdr3 = (uint)appbuf[11]\n"
    "                  | ((uint)appbuf[12] <<  8)\n"
    "                  | ((uint)appbuf[13] << 16)\n"
    "                  | ((uint)appbuf[14] << 24);\n"
    "        dst[0] = (uint4)(hdr0, hdr1, hdr2, hdr3);\n"
    "        uint nvec = need_aligned / 16u;\n"
    "        for (uint v = 1u; v < nvec; v++) {\n"
    "            uint base = v * 16u - 1u;\n"
    "            uint w0 = (uint)appbuf[base + 0u]\n"
    "                    | ((uint)appbuf[base + 1u] <<  8)\n"
    "                    | ((uint)appbuf[base + 2u] << 16)\n"
    "                    | ((uint)appbuf[base + 3u] << 24);\n"
    "            uint w1 = (uint)appbuf[base + 4u]\n"
    "                    | ((uint)appbuf[base + 5u] <<  8)\n"
    "                    | ((uint)appbuf[base + 6u] << 16)\n"
    "                    | ((uint)appbuf[base + 7u] << 24);\n"
    "            uint w2 = (uint)appbuf[base + 8u]\n"
    "                    | ((uint)appbuf[base + 9u] <<  8)\n"
    "                    | ((uint)appbuf[base + 10u] << 16)\n"
    "                    | ((uint)appbuf[base + 11u] << 24);\n"
    "            uint w3 = (uint)appbuf[base + 12u]\n"
    "                    | ((uint)appbuf[base + 13u] <<  8)\n"
    "                    | ((uint)appbuf[base + 14u] << 16)\n"
    "                    | ((uint)appbuf[base + 15u] << 24);\n"
    "            dst[v] = (uint4)(w0, w1, w2, w3);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* --- Write per-slot byte offset -------------------------------\n"
    "     * Per contract S7.1, no parallel mask_idx sidecar. The composed\n"
    "     * plaintext IS the candidate at b_packed_buf[byte_off]; mask\n"
    "     * attribution can be re-derived from slot_idx if a future need\n"
    "     * arises (synthetic_word_idx and mask_offset_in_chunk are\n"
    "     * recoverable from slot via the absolute_mask_idx formula). */\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "#endif  /* A4_PROFILE_VARIANT 1 / 2 / V0 selection */\n"
    "\n"
    "    /* Per-spec invariant 1: caller (Phase 4 host) relies on in-order\n"
    "     * single-queue FIFO to ensure these writes are visible to kernel B\n"
    "     * before kernel B dispatches. No explicit fence; the queue boundary\n"
    "     * provides the cross-kernel global-memory visibility. */\n"
    "}\n"
;
