/* Auto-generated from gpu_md5raw_core.cl -- do not edit */
static const char gpu_md5raw_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_md5raw_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_md5raw_core.cl — MD5RAW algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 6, Tier A).\n"
    " *\n"
    " * MD5RAW differs from MD5 ONLY in template_iterate:\n"
    " *   - MD5    iter (gpu_md5_core.cl): re-hash 32-byte hex_lc encoding\n"
    " *     of the digest. Bytes are ASCII '0'..'9','a'..'f'.\n"
    " *   - MD5RAW iter (this file):     re-hash the 16-byte BINARY digest\n"
    " *     directly. No hex re-encoding.\n"
    " *\n"
    " * CPU reference (mdxfind.c JOB_MD5RAW at line 24237):\n"
    " *\n"
    " *   for (x = 1; x <= Maxiter; x++) {\n"
    " *     mymd5(cur, len, md5buf.h);\n"
    " *     cur = (char *)curin.h;\n"
    " *     len = 16;                     // BINARY 16 bytes\n"
    " *     memcpy(cur, md5buf.h, len);\n"
    " *     checkhash(md5buf, 32, x, job);\n"
    " *   }\n"
    " *\n"
    " * Block layout for the iter step (16-byte input, MD5 LE):\n"
    " *   M[0..3] = 16 LE digest bytes from state[0..3]\n"
    " *   M[4]    = 0x00000080u  (0x80 padding marker at byte 16, LE byte 0)\n"
    " *   M[5..13]= 0\n"
    " *   M[14]   = 16 * 8 = 128 (length in bits, LE low 32)\n"
    " *   M[15]   = 0\n"
    " *\n"
    " * 16 + 1 + 8 = 25 < 56 ⇒ single block.\n"
    " *\n"
    " * All other extension functions (template_state, template_init,\n"
    " * template_transform, template_finalize, template_digest_compare,\n"
    " * template_emit_hit) are byte-identical to gpu_md5_core.cl. Duplicated\n"
    " * inline rather than #include to keep the per-algo source unit\n"
    " * self-contained and the cache key clean (Memo B R3: defines_str +\n"
    " * source-text hash).\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=4,HASH_BLOCK_BYTES=64\" —\n"
    " * same as MD5. Distinct cache entry guaranteed by source-text hash\n"
    " * difference (only template_iterate differs; the rest is byte-identical).\n"
    " *\n"
    " * R1 mitigation: single private buffer pattern; no addrspace-cast\n"
    " * helpers. Same shape as gpu_md5_core.cl.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_md5raw_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* MD5 reads message words little-endian. */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: byte-identical to gpu_md5_core.cl. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    M[rem >> 2] |= (uint)0x80 << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    } else {\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: MD5RAW iter — re-feed the 16-byte BINARY digest\n"
    " * (not hex-encoded) into the compression. CPU reference at mdxfind.c\n"
    " * line 24237:\n"
    " *\n"
    " *   memcpy(cur, md5buf.h, 16);\n"
    " *   mymd5(cur, 16, md5buf.h);\n"
    " *\n"
    " * State after template_finalize: st->h[0..3] hold the 4 LE uint32 digest\n"
    " * words. They are exactly the LE-packed M[0..3] of an md5_block call\n"
    " * given the 16-byte digest as input (since md5 reads message words LE).\n"
    " *\n"
    " * Layout:\n"
    " *   M[0..3]  = st->h[0..3] (16 LE digest bytes; native md5 word order)\n"
    " *   M[4]     = 0x80u    (0x80 padding marker at byte 16, LE)\n"
    " *   M[5..13] = 0\n"
    " *   M[14]    = 16 * 8 = 128 (length in bits, LE)\n"
    " *   M[15]    = 0\n"
    " *\n"
    " * Single block (16 + 1 + 8 = 25 < 56). After absorption, h[] holds the\n"
    " * fresh digest in native MD5 LE form.\n"
    " */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    M[0] = st->h[0];\n"
    "    M[1] = st->h[1];\n"
    "    M[2] = st->h[2];\n"
    "    M[3] = st->h[3];\n"
    "    M[4] = 0x80u;\n"
    "    for (int j = 5; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 16u * 8u;\n"
    "    M[15] = 0u;\n"
    "    /* Reset state to MD5 IV; absorb the prepared block. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
