/* Auto-generated from gpu_ripemd320_core.cl -- do not edit */
static const char gpu_ripemd320_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_ripemd320_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_ripemd320_core.cl — RIPEMD-320 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 2).\n"
    " *\n"
    " * RIPEMD-320 is a parallel-pipeline extension of RIPEMD-160 that DOES\n"
    " * NOT merge the two lines at the end of compression. The result is a\n"
    " * 320-bit digest = 10 × uint32 LE state.\n"
    " *\n"
    " * Geometry / byte ordering:\n"
    " *   - 64-byte block, LE message-word layout (same as MD5 / RIPEMD-160)\n"
    " *   - 10 × uint32 state (5 from line A + 5 from line B; cross-swapped\n"
    " *     between rounds per RIPEMD-320 spec, accumulated into hash[0..9]\n"
    " *     at end of compression)\n"
    " *   - 64-bit LE length encoding in M[14..15]\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (10 for RIPEMD-320)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64)\n"
    " *   template_state     — 10 × uint32 chaining\n"
    " *   template_init      — install RIPEMD-320 IV\n"
    " *   template_transform — absorb one 64-byte block (LE word load,\n"
    " *                        rmd320_block from gpu_common.cl)\n"
    " *   template_finalize  — pad and finalize (LE, in-place M[16]; same\n"
    " *                        perf-fix lesson as MD5/SHA1/RMD160)\n"
    " *   template_iterate   — re-hash digest as 80-byte hex_lc input. Two\n"
    " *                        blocks: 80 hex chars + 1 (0x80) + 8 (length) =\n"
    " *                        89 bytes > 64 ⇒ FIRST block holds 64 hex\n"
    " *                        chars (state[0..7]), SECOND block holds the\n"
    " *                        remaining 16 hex chars (state[8..9]) + 0x80 +\n"
    " *                        length.\n"
    " *   template_digest_compare — probe leading 16 bytes (h[0..3]) directly,\n"
    " *                             NO bswap32 (LE state convention; same as\n"
    " *                             RMD160 / MD5)\n"
    " *   template_emit_hit       — EMIT_HIT_10 wrapper (NEW; added to\n"
    " *                             gpu_common.cl in this sub-batch).\n"
    " *\n"
    " * The dual-pipeline compression body lives in gpu_common.cl as\n"
    " * `rmd320_block` (added in this sub-batch; mirrors the body in\n"
    " * gpu_hmac_rmd320.cl which already implemented it for HMAC). The hash[]\n"
    " * accumulation pattern at end of compression:\n"
    " *\n"
    " *   hash[0] += A;  hash[1] += B;  hash[2] += C;  hash[3] += D;  hash[4] += EE;\n"
    " *   hash[5] += AA; hash[6] += BB; hash[7] += CC; hash[8] += DD; hash[9] += E;\n"
    " *\n"
    " * (cross-mixed E/EE in slots [4] and [9] is part of the spec — copied\n"
    " * directly from gpu_hmac_rmd320.cl rmd320_block.)\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_ripemd320_core_str, gpu_template_str ]\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final state[0..9] (after rmd320_block) is LITTLE-ENDIAN per uint32.\n"
    " *     Direct probe + direct emit; no bswap32.\n"
    " *   - apply_rule + buf in/out is identical to gpu_md5_rules.cl rev 1.28+.\n"
    " *\n"
    " * R1 mitigation: single-private-buffer pattern. R2 (register pressure):\n"
    " * rmd320_block carries 10 uint32 chaining + 10 uint32 working (A..E +\n"
    " * AA..EE) plus the 80-step expansion = comparable to but slightly more\n"
    " * than rmd160_block. Expected priv_mem_size on gfx1201 ~ similar to or\n"
    " * slightly above the RMD160 reading.\n"
    " *\n"
    " * PERF-FIX LESSON (carried from gpu_md5_core.cl rev 1.2): the in-place\n"
    " * M[16] pattern is preserved here — no intermediate uchar pad[] buffer.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key: \"HASH_WORDS=10,HASH_BLOCK_BYTES=64\". */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 10\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: RIPEMD-320 carries 10 uint32 chaining values. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install RIPEMD-320 IV.\n"
    " * Standard RIPEMD-320 initial hash values (RIPEMD-320 spec / mhash;\n"
    " * matches gpu_hmac_rmd320.cl line 228-229 init exactly). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "    st->h[5] = 0x76543210u;\n"
    "    st->h[6] = 0xFEDCBA98u;\n"
    "    st->h[7] = 0x89ABCDEFu;\n"
    "    st->h[8] = 0x01234567u;\n"
    "    st->h[9] = 0x3C2D1E0Fu;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one 64-byte block, LE message words. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    rmd320_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process tail, append 0x80 + 64-bit LE length-in-\n"
    " * bits, absorb. After return, st->h[0..9] holds the final RIPEMD-320\n"
    " * digest words in LITTLE-ENDIAN form. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        rmd320_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    M[rem >> 2] |= (uint)0x80u << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        M[15] = 0u;\n"
    "        rmd320_block(&st->h[0], M);\n"
    "    } else {\n"
    "        rmd320_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        M[15] = 0u;\n"
    "        rmd320_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the 320-bit digest as 80\n"
    " * lowercase hex chars and rehash. 80 + 1 (0x80) + 8 (length) = 89 bytes\n"
    " * > 64 ⇒ requires a SECOND padding block.\n"
    " *\n"
    " * Layout:\n"
    " *   block 1 (M[0..15], 64 bytes):\n"
    " *     M[0..15] = first 16 LE-packed hex pairs = 64 hex chars (state[0..7])\n"
    " *\n"
    " *   block 2 (M[0..15], 64 bytes):\n"
    " *     M[0..3]  = remaining 16 hex chars (state[8..9])\n"
    " *     M[4]     = 0x80 (LE byte at offset 80)\n"
    " *     M[5..13] = 0\n"
    " *     M[14]    = 80 * 8 = 640 (low 32 bits of bit count)\n"
    " *     M[15]    = 0\n"
    " *\n"
    " * Snapshot state[8..9] BEFORE the IV reset so block 2 can hex-encode\n"
    " * the original digest's last two words. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* Snapshot state[8..9] for block 2 before the IV reset. */\n"
    "    uint snap8 = st->h[8];\n"
    "    uint snap9 = st->h[9];\n"
    "\n"
    "    /* Block 1: hex-encode state[0..7] into M[0..15]. */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint s = st->h[i];\n"
    "        uint b0 = s & 0xff,        b1 = (s >> 8) & 0xff;\n"
    "        uint b2 = (s >> 16) & 0xff, b3 = (s >> 24) & 0xff;\n"
    "        M[i*2]     = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "        M[i*2 + 1] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "    }\n"
    "    /* Reinitialize state to RIPEMD-320 IV; absorb block 1. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "    st->h[5] = 0x76543210u;\n"
    "    st->h[6] = 0xFEDCBA98u;\n"
    "    st->h[7] = 0x89ABCDEFu;\n"
    "    st->h[8] = 0x01234567u;\n"
    "    st->h[9] = 0x3C2D1E0Fu;\n"
    "    rmd320_block(&st->h[0], M);\n"
    "\n"
    "    /* Block 2: hex-encode (snap8, snap9) into M[0..3]; 0x80 at M[4];\n"
    "     * bit length in M[14]. */\n"
    "    {\n"
    "        uint s8 = snap8, s9 = snap9;\n"
    "        uint b0 = s8 & 0xff,        b1 = (s8 >> 8) & 0xff;\n"
    "        uint b2 = (s8 >> 16) & 0xff, b3 = (s8 >> 24) & 0xff;\n"
    "        M[0] = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "        M[1] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "        b0 = s9 & 0xff;        b1 = (s9 >> 8) & 0xff;\n"
    "        b2 = (s9 >> 16) & 0xff; b3 = (s9 >> 24) & 0xff;\n"
    "        M[2] = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "        M[3] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "    }\n"
    "    M[4] = 0x80u;                   /* LE 0x80 at byte offset 80 */\n"
    "    for (int j = 5; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 80u * 8u;               /* 80 hex chars = 640 bits */\n"
    "    M[15] = 0u;\n"
    "    rmd320_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe leading 16 bytes (h[0..3]). LE state\n"
    " * convention; no bswap32 (same as MD5 / RIPEMD-160). */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: EMIT_HIT_10 wrapper (RIPEMD-320 = 10 uint32 LE\n"
    " * digest words). State words flow directly, no bswap32. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_10((hits), (hit_count), (max_hits), \\\n"
    "                (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_10_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
