/* Auto-generated from gpu_sha1_core.cl -- do not edit */
static const char gpu_sha1_core_str[] =
    "/*\n"
    " * $Revision: 1.3 $\n"
    " * $Log: gpu_sha1_core.cl,v $\n"
    " * Revision 1.3  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha1_core.cl — SHA1 algorithm extension functions for the generic\n"
    " * dispatch template (Memo B Phase B4 — first-algorithm fan-out).\n"
    " *\n"
    " * Mirrors gpu_md5_core.cl rev 1.2 structure exactly. The template body\n"
    " * (gpu_template.cl) is algorithm-agnostic; this file provides the\n"
    " * SHA1-specific extension functions:\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (5 for SHA1)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64 — same as MD5/SHA-256\n"
    " *                        Merkle-Damgård 64-byte block)\n"
    " *   template_state     — opaque per-lane state struct (5 uint32 chaining)\n"
    " *   template_init      — install SHA1 IV (5 standard values)\n"
    " *   template_transform — absorb one 64-byte block (SHA1 BIG-ENDIAN word load)\n"
    " *   template_finalize  — pad and finalize (in-place M[16] pattern; see\n"
    " *                        the perf-fix lesson at the head of gpu_md5_core.cl)\n"
    " *   template_iterate   — re-hash digest as 40-byte hex_lc (-i loop)\n"
    " *   template_digest_compare — probe compact table with leading 16 bytes\n"
    " *                             (h[0..3], LE-byteswapped to match the\n"
    " *                             host-side compact table key encoding)\n"
    " *   template_emit_hit       — EMIT_HIT_5 wrapper (5 LE digest words)\n"
    " *\n"
    " * KEY DIFFERENCES FROM gpu_md5_core.cl:\n"
    " *\n"
    " * 1. Endianness. SHA1 reads message words in BIG-ENDIAN (RFC 3174); MD5\n"
    " *    reads LITTLE-ENDIAN (RFC 1321). The template_finalize in-place M[]\n"
    " *    build below packs bytes BE, length-encodes the bit count BE in\n"
    " *    M[15], and leaves M[14] = 0 (high-order 32 bits of the 64-bit BE\n"
    " *    bit count). md5's was M[14] LE, M[15] = 0.\n"
    " *\n"
    " * 2. State width. SHA1 = 5 uint32; MD5 = 4. This file uses HASH_WORDS = 5\n"
    " *    (compile-time defined via -D from gpu_kernel_cache_build_program_ex's\n"
    " *    defines_str). The state struct is uint h[HASH_WORDS]; the template\n"
    " *    body and digest_compare helper read at most HASH_WORDS entries.\n"
    " *\n"
    " * 3. Compact table probe. The compact table is keyed on the leading 16\n"
    " *    BYTES of the digest, in the algorithm's NATIVE byte order. SHA1's\n"
    " *    state is stored big-endian internally (matches sha1_block's chaining\n"
    " *    output convention); to match the host-side compact_table_register\n"
    " *    keying (which reads bytes from the digest as little-endian uint32\n"
    " *    pairs), we byte-swap state[0..3] -> probe_h[0..3] LE before calling\n"
    " *    probe_compact_idx. This matches gpu_sha1_packed.cl's existing path.\n"
    " *\n"
    " * 4. Iter loop. SHA1 hex output is 40 lowercase hex chars (vs MD5's 32).\n"
    " *    template_iterate fills 10 uint M[10] with the hex bytes (BE word\n"
    " *    encoding to match SHA1's BE message word layout), pads, and\n"
    " *    re-runs sha1_block. The iter step matches gpu_sha1_packed.cl's\n"
    " *    sha1_to_hex_lc_p + state-reset + sha1_compress sequence.\n"
    " *\n"
    " * 5. EMIT_HIT_5 vs EMIT_HIT_4. 5-word emit; widx/sidx/iter triple\n"
    " *     prepend stays the same.\n"
    " *\n"
    " * Source order at compile time (mirrors MD5 build):\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha1_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides sha1_block(), bswap32, EMIT_HIT_5, and\n"
    " * probe_compact_idx. gpu_md5_rules_str provides apply_rule (the rules\n"
    " * walker is algorithm-agnostic — it only mutates a uchar buffer in\n"
    " * place). gpu_sha1_core_str (this file) provides the per-algorithm\n"
    " * hooks. gpu_template_str ties them into template_phase0.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final digest h[0..4] (after template_finalize) is BIG-ENDIAN —\n"
    " *     the same byte order sha1_block writes back into state[0..4].\n"
    " *     gpu_sha1_packed.cl matches this.\n"
    " *   - template_digest_compare byte-swaps the leading 4 words to LE\n"
    " *     before probing. This matches the host's compact_table key encoding\n"
    " *     and gpu_sha1_packed.cl's existing `for j: h[j] = bswap32(state[j])`\n"
    " *     pattern at line 88-92.\n"
    " *   - template_emit_hit writes the LE-byteswapped digest into the hits\n"
    " *     buffer (same as gpu_sha1_packed.cl), so the host hit-replay\n"
    " *     matches the legacy SHA1 packed kernel.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single private\n"
    " * buffer pattern. No __private uchar* helpers; no addrspace-cast\n"
    " * ternaries. apply_rule + buf are unchanged from MD5; the algorithm\n"
    " * core only operates on the post-rule buf and emits LE digest words.\n"
    " *\n"
    " * R2 (register pressure): SHA1's W[80] schedule is built on-stack inside\n"
    " * sha1_block (gpu_common.cl line 437) — 80 uint32 = 320 bytes private,\n"
    " * plus 5-word state, plus 5-word transient probe_h. Per-lane VGPR\n"
    " * footprint is comparable to MD5's M[16] schedule + 4-word state.\n"
    " * Expected priv_mem_size on gfx1201 ~ similar to MD5's reading.\n"
    " *\n"
    " * PERF-FIX LESSON (from gpu_md5_core.cl rev 1.2):\n"
    " *\n"
    " * template_finalize MUST build M[16] DIRECTLY from input bytes via\n"
    " * shifts/OR-merge — NOT via a private uchar pad[64] tail-block buffer\n"
    " * that is then read BACK out as message words. The byte-store /\n"
    " * byte-load round-trip cost was the 12.3% wall regression in B2's\n"
    " * first-cut MD5 template path. This file applies the same pattern for\n"
    " * SHA1: only difference is BE byte ordering of the M[] words and the\n"
    " * length encoding being BE in M[15] (low 32 bits of 64-bit count).\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. The template uses these as structural\n"
    " * compile-time constants; the kernel-cache key (gpu_kernel_cache R3\n"
    " * fix) hashes the defines_str (\"HASH_WORDS=5,HASH_BLOCK_BYTES=64\")\n"
    " * alongside the source set so distinct instantiations get distinct\n"
    " * cache entries even though source text would otherwise be identical. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 5\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: SHA1 carries 5 uint32 chaining values (vs MD5's\n"
    " * 4). The template only reads/writes the digest words via\n"
    " * template_finalize's output + template_digest_compare; it does not\n"
    " * introspect the struct. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install SHA1 IV into state.\n"
    " * Standard SHA1 initial hash values (RFC 3174 §6.1). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (64) byte block.\n"
    " * `block` points into the working buffer at the absorb position;\n"
    " * the caller must guarantee >=64 bytes are readable. SHA1 reads\n"
    " * message words BIG-ENDIAN.\n"
    " *\n"
    " * Public extension API; the hot-path template_finalize bypasses this\n"
    " * via an in-place M[16] pattern (see perf-fix lesson at file head).\n"
    " * Kept symmetric with gpu_md5_core.cl for cores that prefer the\n"
    " * function-style entry. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* SHA1 reads message words big-endian. */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b]     << 24)\n"
    "             | ((uint)block[b + 1] << 16)\n"
    "             | ((uint)block[b + 2] << 8)\n"
    "             |  (uint)block[b + 3];\n"
    "    }\n"
    "    sha1_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process the tail, append the 0x80 padding marker\n"
    " * + 64-bit BE length-in-bits, and absorb. Caller passes the full\n"
    " * buffer; we run complete blocks then build the final padded block(s)\n"
    " * here. After return, st->h[0..4] holds the final SHA1 digest words\n"
    " * in BIG-ENDIAN form (sha1_block's natural output).\n"
    " *\n"
    " * Mirrors gpu_md5_core.cl rev 1.2's in-place M[16] pattern: build the\n"
    " * message words DIRECTLY from input bytes via shifts/OR-merge. The\n"
    " * difference vs MD5 is byte ordering (BE for SHA1) and length encoding\n"
    " * (BE 64-bit count, low 32 bits in M[15]).\n"
    " *\n"
    " * PERF-FIX LESSON (carried forward from gpu_md5_core.cl rev 1.2):\n"
    " *\n"
    " * Do NOT route through template_transform() here. The previous MD5\n"
    " * version built a private uchar pad[64] tail block, populated it with\n"
    " * 64+rem byte stores, then handed it to template_transform which read\n"
    " * the same 64 bytes BACK out as BE uints into a fresh M[16]. That\n"
    " * round-trip (byte-stores -> byte-loads -> uint-pack) was the 12.3%\n"
    " * wall regression vs the legacy md5_buf path on ioblade (Memo B\n"
    " * Phase B2 perf-fix, 2026-05-04).\n"
    " *\n"
    " * For full blocks the function-call boundary plus rebuilt-M[] cost is\n"
    " * non-trivial too; for the final block the extra 64-byte zeroing +\n"
    " * byte-by-byte tail copy + 4-byte length store dominates because rem\n"
    " * is small for typical wordlist inputs. We build M[] in-place and\n"
    " * call sha1_block() once per block.\n"
    " *\n"
    " * R1 mitigation preserved: single private buffer (just the M[16]\n"
    " * uints + the input data pointer), no addrspace-cast helpers, no\n"
    " * __private uchar* helper that takes a private buffer pointer. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Process complete 64-byte blocks. Build M[] BIG-ENDIAN directly\n"
    "     * from bytes. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b]     << 24)\n"
    "                 | ((uint)data[b + 1] << 16)\n"
    "                 | ((uint)data[b + 2] << 8)\n"
    "                 |  (uint)data[b + 3];\n"
    "        }\n"
    "        sha1_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    /* Build final block(s): tail bytes + 0x80 marker + zeros + 64-bit\n"
    "     * BE length. Direct-into-M[] approach — no intermediate uchar\n"
    "     * pad[]. */\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Copy remaining tail bytes into M[] big-endian. Each byte's\n"
    "     * position within its 32-bit word is determined by 3-(byte_idx & 3)\n"
    "     * shift (BE: byte 0 is high octet of word). */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = 3 - (i & 3);\n"
    "        M[wi] |= ((uint)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker, BE byte position. */\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = 3 - (rem & 3);\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 56) {\n"
    "        /* Length fits in this block. SHA1 BE: M[14] = high 32 bits\n"
    "         * of bit count, M[15] = low 32 bits. For len < 2^29 bytes\n"
    "         * (always true for our wordlist inputs), high 32 bits = 0. */\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        sha1_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the digest as 40-byte\n"
    " * lowercase hex ASCII and rehash. Algorithm-specific because the\n"
    " * digest geometry differs (SHA1: 5 words, 40 chars).\n"
    " *\n"
    " * Mirrors gpu_sha1_packed.cl rev 1 lines 100-108 byte-for-byte:\n"
    " *   - 5 state words -> 10 BE-encoded hex M[] words (2 words per state\n"
    " *     word, 4 hex chars each — matches sha1_to_hex_lc_p)\n"
    " *   - M[10] = 0x80000000u   (BE 0x80 padding at byte offset 40)\n"
    " *   - M[11..14] = 0\n"
    " *   - M[15] = 40 * 8 = 320 (bit count)\n"
    " *   - state reset to SHA1 IV; sha1_block. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* Inlined sha1_to_hex_lc_p body — keeps gpu_sha1_core self-contained\n"
    "     * (gpu_sha1_packed.cl's hex_byte_be_p / sha1_to_hex_lc_p are not\n"
    "     * exported through gpu_common.cl). Per-byte BE hex encoding. */\n"
    "    for (int i = 0; i < 5; i++) {\n"
    "        uint s = st->h[i];\n"
    "        uint b0 = (s >> 24) & 0xff;\n"
    "        uint b1 = (s >> 16) & 0xff;\n"
    "        uint b2 = (s >> 8)  & 0xff;\n"
    "        uint b3 = s & 0xff;\n"
    "        /* hex_byte_be: produce two hex chars in a 16-bit BE pair. */\n"
    "        uint hi0 = (b0 >> 4) & 0xf, lo0 = b0 & 0xf;\n"
    "        uint hi1 = (b1 >> 4) & 0xf, lo1 = b1 & 0xf;\n"
    "        uint hi2 = (b2 >> 4) & 0xf, lo2 = b2 & 0xf;\n"
    "        uint hi3 = (b3 >> 4) & 0xf, lo3 = b3 & 0xf;\n"
    "        uint h0 = ((hi0 + ((hi0 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo0 + ((lo0 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h1 = ((hi1 + ((hi1 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo1 + ((lo1 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h2 = ((hi2 + ((hi2 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo2 + ((lo2 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h3 = ((hi3 + ((hi3 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo3 + ((lo3 < 10) ? '0' : ('a' - 10)));\n"
    "        M[i * 2]     = (h0 << 16) | h1;\n"
    "        M[i * 2 + 1] = (h2 << 16) | h3;\n"
    "    }\n"
    "    M[10] = 0x80000000u;\n"
    "    for (int j = 11; j < 15; j++) M[j] = 0u;\n"
    "    M[15] = 40u * 8u;        /* 40 hex chars = 320 bits */\n"
    "    /* Reinitialize state to SHA1 IV, then absorb the prepared M[]. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "    sha1_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the final\n"
    " * digest. On a hit, *out_idx is set to the matched target's hash_data\n"
    " * index (mirrors probe_compact_idx semantics). Return 1 on hit, 0 on\n"
    " * miss.\n"
    " *\n"
    " * SHA1 state is stored big-endian (sha1_block's natural form). The\n"
    " * compact table is keyed on the leading 16 BYTES of the digest in\n"
    " * little-endian uint32 form (same convention as MD5 — host-side\n"
    " * compact_table_register reads the digest bytes as 4 LE uint32 to\n"
    " * form the key). We byte-swap the leading 4 words to LE before\n"
    " * calling probe_compact_idx.\n"
    " *\n"
    " * Mirrors gpu_sha1_packed.cl line 88-92's `for j: h[j] = bswap32(state[j])`\n"
    " * pattern verbatim. The 5th state word (h[4]) is NOT used by the\n"
    " * compact-table probe — only by EMIT_HIT_5 below. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    uint h0 = bswap32(st->h[0]);\n"
    "    uint h1 = bswap32(st->h[1]);\n"
    "    uint h2 = bswap32(st->h[2]);\n"
    "    uint h3 = bswap32(st->h[3]);\n"
    "    return probe_compact_idx(\n"
    "        h0, h1, h2, h3,\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit into the global hits buffer. Wraps\n"
    " * EMIT_HIT_5 (SHA1 = 5 uint32 digest words). Hits buffer convention\n"
    " * matches gpu_sha1_packed.cl: 5 LE-byteswapped digest words after the\n"
    " * widx/sidx/iter triple.\n"
    " *\n"
    " * The macro builds a private uint h[5] of LE-byteswapped state, then\n"
    " * passes it to EMIT_HIT_5 (which expects an array, not 5 individual\n"
    " * args). Same wire format as gpu_sha1_packed.cl line 98 emit. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. See gpu_md5_core.cl for protocol\n"
    " * notes. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h, \\\n"
    "                   (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                   (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
;
