/* Auto-generated from gpu_sha1_packed.cl -- do not edit */
static const char gpu_sha1_packed_str[] =
    "/* gpu_sha1_packed.cl — Packed password SHA1 kernel for rule-generated candidates\n"
    " *\n"
    " * Same structure as gpu_md5_packed.cl but with SHA1:\n"
    " *   - Big-endian byte swap on M[] before compress\n"
    " *   - 5-word state, EMIT_HIT_5\n"
    " *   - Bit count at M[15] (BE)\n"
    " *\n"
    " * Primitives (bswap32, sha1_block, probe_compact, EMIT_HIT_5) from gpu_common.cl\n"
    " * hex_byte_be, sha1_to_hex_lc from gpu_sha1unsalted.cl (duplicated here)\n"
    " */\n"
    "\n"
    "#define sha1_compress sha1_block\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (lowercase, BE word packing) */\n"
    "uint hex_byte_be_p(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    return ((hi + ((hi < 10) ? '0' : ('a' - 10))) << 8)\n"
    "         |  (lo + ((lo < 10) ? '0' : ('a' - 10)));\n"
    "}\n"
    "\n"
    "void sha1_to_hex_lc_p(uint *state, uint *M) {\n"
    "    for (int i = 0; i < 5; i++) {\n"
    "        uint s = state[i];\n"
    "        uint b0 = (s >> 24) & 0xff, b1 = (s >> 16) & 0xff;\n"
    "        uint b2 = (s >> 8)  & 0xff, b3 = s & 0xff;\n"
    "        M[i*2]   = (hex_byte_be_p(b0) << 16) | hex_byte_be_p(b1);\n"
    "        M[i*2+1] = (hex_byte_be_p(b2) << 16) | hex_byte_be_p(b3);\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void sha1_packed_batch(\n"
    "    __global const uchar *packed_buf,\n"
    "    __global const uint *word_offset,\n"
    "    __global const uchar *unused_mask,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_start = params.reserved32[0];\n"
    "    uint word_idx = word_start + tid;\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint pos = word_offset[word_idx];\n"
    "    uint len = packed_buf[pos++];\n"
    "\n"
    "    /* Build M[16] in little-endian (same as MD5 unpack) */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint i = 0;\n"
    "    for (; i + 3 < len; i += 4) {\n"
    "        M[i >> 2] = (uint)packed_buf[pos + i]\n"
    "                  | ((uint)packed_buf[pos + i + 1] << 8)\n"
    "                  | ((uint)packed_buf[pos + i + 2] << 16)\n"
    "                  | ((uint)packed_buf[pos + i + 3] << 24);\n"
    "    }\n"
    "    uint tail = 0;\n"
    "    uint shift = 0;\n"
    "    for (; i < len; i++) {\n"
    "        tail |= (uint)packed_buf[pos + i] << shift;\n"
    "        shift += 8;\n"
    "    }\n"
    "    tail |= (uint)0x80 << shift;\n"
    "    M[i >> 2] = tail;\n"
    "    M[14] = len * 8;  /* temp: LE bitlen for swap */\n"
    "\n"
    "    /* Byte-swap to big-endian for SHA1 */\n"
    "    uint bitlen = M[14];\n"
    "    for (int j = 0; j < 16; j++) M[j] = bswap32(M[j]);\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;  /* BE 64-bit bit count in M[15] */\n"
    "\n"
    "    /* SHA1 compress */\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    /* Iteration loop */\n"
    "    uint max_iter = params.max_iter;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* Byte-swap state to LE for compact table probe */\n"
    "        uint h[5];\n"
    "        for (int j = 0; j < 5; j++) h[j] = bswap32(state[j]);\n"
    "\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe,\n"
    "                          params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes,\n"
    "                          overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_5(hits, hit_count, params.max_hits, word_idx, 0, iter, h)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            sha1_to_hex_lc_p(state, M);\n"
    "            M[10] = 0x80000000u;\n"
    "            for (int j = 11; j < 15; j++) M[j] = 0;\n"
    "            M[15] = 40 * 8;\n"
    "            state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "            state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "            sha1_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
