/* Auto-generated from gpu_md6256_core.cl -- do not edit */
static const char gpu_md6256_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_md6256_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_md6256_core.cl — MD6-256 (hashcat -m 17800, JOB_MD6256=29) algorithm\n"
    " * extension functions for the generic dispatch template (Memo B Phase B7.7b).\n"
    " *\n"
    " * STATUS: B7.7b — final M5 closure (renders gpu_md6256unsalted.cl retireable\n"
    " * after B7.8 mask cap widening). MD6 is the algorithmically-largest single-\n"
    " * compression unsalted algo on the unified template path: 89-ulong N input,\n"
    " * 1753-ulong A working array (= 14,024 bytes per work-item), 104 rounds × 16\n"
    " * words = 1,664 main-loop steps per compression.\n"
    " *\n"
    " * MD6-256 = md6_hash(d=256, data, len*8). For lengths fitting one leaf block\n"
    " * (b=64 ulong = 512 bytes; the slab path's maxpasslen=511 covers all in-scope\n"
    " * inputs), this is a SINGLE compression call followed by digest extraction\n"
    " * from C[12..15] (last 4 ulong = 32 bytes = 256 bits).\n"
    " *\n"
    " * CPU reference (mdxfind.c JOB_MD6256 at lines 25836-25855):\n"
    " *\n"
    " *   case JOB_MD6256: i = 256; goto MD6_start;\n"
    " *   ...\n"
    " *   MD6_start:\n"
    " *     for (x = 1; x <= Maxiter; x++) {\n"
    " *       md6_hash(i, (unsigned char *) cur, len * 8, curin.h);\n"
    " *       len = i / 4;                            // 64 hex chars for d=256\n"
    " *       cur = prmd5(curin.h, mdbuf, len);       // lowercase hex\n"
    " *       hashcnt++;\n"
    " *       checkhash(&curin, len, x, job);\n"
    " *     }\n"
    " *\n"
    " * Per-iter behavior:\n"
    " *   - At iter N, input = (N==1 ? rule-mutated buf : LOWERCASE_HEX(64) of\n"
    " *     prior iter's 32-byte digest).\n"
    " *   - Compute md6_256_N = md6_hash(input). Probe md6_256_N against compact\n"
    " *     table.\n"
    " *   - If iter < Maxiter, prepare input_{N+1} = LOWERCASE_HEX(md6_256_N).\n"
    " *\n"
    " * DESIGN: per-iter probe like SQL5 — template_finalize does the FIRST md6\n"
    " * compression; template_iterate does the hex-feedback then the next md6\n"
    " * compression. The kernel's outer iter loop in template_phase0 calls\n"
    " * template_digest_compare after every iter and template_iterate before the\n"
    " * next. This is the SQL5 pattern (gpu_sql5_core.cl) — distinct from the\n"
    " * SHA1DRU pattern (1M loop inside template_finalize, max_iter=1) because\n"
    " * MD6256 honors user `-i` semantics.\n"
    " *\n"
    " * Per-algorithm state struct holds the 32-byte md6_256 digest as 4 ulong\n"
    " * (BE words, LE-byte-emit). Probe converts to 8 uint LE for the compact\n"
    " * table compare.\n"
    " *\n"
    " * The compression scratch (1753-ulong working array A) lives on the\n"
    " * function-local stack in template_finalize / template_iterate — NOT in\n"
    " * template_state (which would balloon every algo's per-thread state).\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=8,HASH_BLOCK_BYTES=64,\n"
    " * BASE_ALGO=md6\". HASH_WORDS=8 (256-bit digest = 8 uint32). HASH_BLOCK_BYTES\n"
    " * is largely advisory for MD6 (the kernel processes the WHOLE input as one\n"
    " * 64-ulong = 512-byte leaf block); 64 chosen to align with default. Distinct\n"
    " * cache entry by source-text hash regardless.\n"
    " *\n"
    " * KNOWN ACCEPTED RISK (per architect §6 of project_b76plus_mask_iter_-\n"
    " * closure.md): the 1753-ulong A working array (14 KB) plus the standard\n"
    " * RULE_BUF_MAX (~40 KB) is expected to bust gfx1201's 43,024 B HARD GATE.\n"
    " * Architect predicted +800 to +1500 B over the SHA1DRU baseline of 41,328 B;\n"
    " * the actual cost may be substantially higher because of the 14 KB A[1753]\n"
    " * stack (the SHA1DRU baseline doesn't have it). User OPTION A directs\n"
    " * compile-only ship; integrated post-B7.9 validation will reveal whether\n"
    " * gfx1201 loses this kernel. Fall-back if so: leave gpu_md6256unsalted.cl\n"
    " * in tree as gfx1201-only kernel routed via slab path.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace): single private buffer pattern.\n"
    " * No __private uchar* helpers; no addrspace-cast ternaries. The A[] array\n"
    " * is a function-local automatic; OpenCL spec promises private addrspace\n"
    " * for stack locals (no special handling needed).\n"
    " *\n"
    " * VALIDATION ORACLE: existing slab kernel md6_256_unsalted_batch in\n"
    " * gpu_md6256unsalted.cl. The compression body of THIS file is a port of\n"
    " * that slab kernel's md6_compress_loop (lines 44-78 pre-B7.7b) plus the\n"
    " * N[89] packer (lines 99-110, 241-256 pre-B7.7b) into the template\n"
    " * extension API. Differences from the slab kernel:\n"
    " *   - reads pass from `data` (post-rule buf passed by template) rather\n"
    " *     than from a pre-packed N[89] block built by the host.\n"
    " *   - the iter feedback hex encoding of the digest happens in template_-\n"
    " *     iterate (vs. inline in the slab kernel's iter loop).\n"
    " *   - compact-table probe uses 8 LE uint32 (HASH_WORDS=8) — was hand-rolled\n"
    " *     EMIT_HIT_8 in the slab path; template path uses the standard\n"
    " *     probe_compact_idx + EMIT_HIT macros.\n"
    " *\n"
    " * Source order at compile time (mirrors other unsalted cores):\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_md6256_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 8\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* MD6 compression constants (mirrors gpu_md6256unsalted.cl). */\n"
    "__constant ulong MD6CORE_QC[15] = {\n"
    "    0x7311c2812425cfa0UL, 0x6432286434aac8e7UL, 0xb60450e9ef68b7c1UL,\n"
    "    0xe8fb23908d9f06f1UL, 0xdd2e76cba691e5bfUL, 0x0cd0d63b2c30bc41UL,\n"
    "    0x1f8ccf6823058f8aUL, 0x54e5ed5b88e3775dUL, 0x4ad12aae0a6d6031UL,\n"
    "    0x3e7f16bb88222e0dUL, 0x8af8671d3fb50c2cUL, 0x995ad1178bd25c31UL,\n"
    "    0xc878c1dd04c4b633UL, 0x3b72066c7a1552acUL, 0x0d6f3522631effcbUL\n"
    "};\n"
    "\n"
    "#define MD6CORE_n  89\n"
    "#define MD6CORE_c  16\n"
    "#define MD6CORE_r  104\n"
    "\n"
    "#define MD6CORE_t0  17\n"
    "#define MD6CORE_t1  18\n"
    "#define MD6CORE_t2  21\n"
    "#define MD6CORE_t3  31\n"
    "#define MD6CORE_t4  67\n"
    "#define MD6CORE_t5  89\n"
    "\n"
    "__constant ulong MD6CORE_S0    = 0x0123456789abcdefUL;\n"
    "__constant ulong MD6CORE_Smask = 0x7311c2812425cfa0UL;\n"
    "\n"
    "#define MD6CORE_STEP(rs, ls, step) \\\n"
    "    x  = S;                                         \\\n"
    "    x ^= A[i + step - MD6CORE_t5];                  \\\n"
    "    x ^= A[i + step - MD6CORE_t0];                  \\\n"
    "    x ^= (A[i + step - MD6CORE_t1] & A[i + step - MD6CORE_t2]); \\\n"
    "    x ^= (A[i + step - MD6CORE_t3] & A[i + step - MD6CORE_t4]); \\\n"
    "    x ^= (x >> rs);                                 \\\n"
    "    A[i + step] = x ^ (x << ls);\n"
    "\n"
    "/* MD6 main compression loop on a 1753-ulong working array A. The first 89\n"
    " * ulong (A[0..88]) hold N (the packed compression input); the remaining\n"
    " * r*c=1664 slots are filled by the loop. Output C[16] is at A[1737..1752];\n"
    " * the d=256-bit hash is the LAST 4 ulong of C, i.e. A[1749..1752]. */\n"
    "static inline void md6core_compress_loop(ulong *A) {\n"
    "    ulong x;\n"
    "    ulong S = MD6CORE_S0;\n"
    "    int i = MD6CORE_n;\n"
    "    for (int j = 0; j < MD6CORE_r * MD6CORE_c; j += MD6CORE_c) {\n"
    "        MD6CORE_STEP(10, 11,  0)\n"
    "        MD6CORE_STEP( 5, 24,  1)\n"
    "        MD6CORE_STEP(13,  9,  2)\n"
    "        MD6CORE_STEP(10, 16,  3)\n"
    "        MD6CORE_STEP(11, 15,  4)\n"
    "        MD6CORE_STEP(12,  9,  5)\n"
    "        MD6CORE_STEP( 2, 27,  6)\n"
    "        MD6CORE_STEP( 7, 15,  7)\n"
    "        MD6CORE_STEP(14,  6,  8)\n"
    "        MD6CORE_STEP(15,  2,  9)\n"
    "        MD6CORE_STEP( 7, 29, 10)\n"
    "        MD6CORE_STEP(13,  8, 11)\n"
    "        MD6CORE_STEP(11, 15, 12)\n"
    "        MD6CORE_STEP( 7,  5, 13)\n"
    "        MD6CORE_STEP( 6, 31, 14)\n"
    "        MD6CORE_STEP(12,  9, 15)\n"
    "        S = (S << 1) ^ (S >> 63) ^ (S & MD6CORE_Smask);\n"
    "        i += 16;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* md6core_pack_and_compress: build the N[89] packed input from `data`\n"
    " * bytes of length `len`, run one compression, store the 4-ulong digest\n"
    " * (BE within each ulong, MD6's natural state output) into st->h[] as\n"
    " * 8 uint32 (BE pair-wise — the bswap to LE happens at digest_compare /\n"
    " * emit time).\n"
    " *\n"
    " * Mirrors mdxfind.c:9361-9385 (host pack) + gpu_md6256unsalted.cl:99-185\n"
    " * (slab kernel pack + compress). The single-leaf single-compression path\n"
    " * is correct for any len <= 64*8 = 512 bytes (b=64 ulong leaf block). The\n"
    " * caller is responsible for clamping `len` to <= 512. */\n"
    "static inline void md6core_pack_and_compress(uint *digest_words,\n"
    "                                             const uchar *data, int len)\n"
    "{\n"
    "    /* Working array A[1753] = N[89] head + r*c=1664 trailing slots.\n"
    "     * 14,024 bytes on the kernel stack — same as slab kernel.\n"
    "     * KNOWN ACCEPTED RISK: gfx1201 priv_mem may bust HARD GATE (architect\n"
    "     * §6); compile-only ship per user OPTION A. */\n"
    "    ulong A[1753];\n"
    "\n"
    "    /* Clamp: leaf block holds b*w = 64 * 64 = 4096 bits = 512 bytes. */\n"
    "    if (len < 0)   len = 0;\n"
    "    if (len > 512) len = 512;\n"
    "\n"
    "    /* N[0..14] = Q (15 fixed constants). */\n"
    "    for (int i = 0; i < 15; i++) A[i] = MD6CORE_QC[i];\n"
    "    /* N[15..22] = K = 0 (8 ulong key, unused). */\n"
    "    for (int i = 15; i < 23; i++) A[i] = 0;\n"
    "    /* N[23] = U = nodeID(ell=1, i=0) = 1<<56. */\n"
    "    A[23] = (ulong)1 << 56;\n"
    "    /* N[24] = V = control_word(r=104, L=64, z=1, p=4096-len*8, keylen=0,\n"
    "     * d=256). Layout per md6_make_control_word at md6_compress.c:312:\n"
    "     *   r << 48, L << 40, z << 36, p << 20, keylen << 12, d. */\n"
    "    int p_bits = 64 * 64 - len * 8;\n"
    "    A[24] = ((ulong)104 << 48) | ((ulong)64 << 40) | ((ulong)1 << 36)\n"
    "          | ((ulong)p_bits << 20) | (ulong)256;\n"
    "\n"
    "    /* N[25..88] = B[64] data block — pack `data` bytes into LE ulong slots\n"
    "     * starting at byte offset 0 within B. The host's slab packer writes\n"
    "     * bytes via memcpy() into slot[200..200+len-1] which on a little-endian\n"
    "     * host translates to LE-packed ulong[]; the slab kernel then bswap64's\n"
    "     * to MD6's expected BE (per md6_reverse_little_endian at md6_mode.c:\n"
    "     * 822). We do the same here: build B as LE, then bswap64 in-place. */\n"
    "    for (int i = 25; i < 89; i++) A[i] = 0;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        int wi = 25 + (i >> 3);\n"
    "        int bi = (i & 7) << 3;\n"
    "        A[wi] |= (ulong)data[i] << bi;\n"
    "    }\n"
    "    /* Convert B from LE byte order to BE — MD6 absorbs words in BE. */\n"
    "    for (int i = 25; i < 89; i++) A[i] = bswap64(A[i]);\n"
    "\n"
    "    /* Run main compression loop: 104 rounds × 16 steps. */\n"
    "    md6core_compress_loop(A);\n"
    "\n"
    "    /* Extract C[12..15] = A[1749..1752] (last 4 ulong = 256-bit digest).\n"
    "     * MD6 output is BE ulong; we expand to 8 uint32 LE for compact-table\n"
    "     * probe consistency (matches slab kernel's bswap64-then-split-to-uint\n"
    "     * pattern at gpu_md6256unsalted.cl:198-202). */\n"
    "    ulong C0 = A[1749], C1 = A[1750], C2 = A[1751], C3 = A[1752];\n"
    "    ulong s0 = bswap64(C0); digest_words[0] = (uint)s0; digest_words[1] = (uint)(s0 >> 32);\n"
    "    ulong s1 = bswap64(C1); digest_words[2] = (uint)s1; digest_words[3] = (uint)(s1 >> 32);\n"
    "    ulong s2 = bswap64(C2); digest_words[4] = (uint)s2; digest_words[5] = (uint)(s2 >> 32);\n"
    "    ulong s3 = bswap64(C3); digest_words[6] = (uint)s3; digest_words[7] = (uint)(s3 >> 32);\n"
    "}\n"
    "\n"
    "/* Per-lane state struct: 32-byte MD6-256 digest exposed as 8 LE uint32.\n"
    " * The template only reads/writes via template_finalize's output +\n"
    " * template_digest_compare; it does not introspect the struct. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];   /* HASH_WORDS=8 (256-bit) */\n"
    "} template_state;\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    /* No persistent IV for MD6 (the IV is the Q/K/U/V prefix of N[],\n"
    "     * which md6core_pack_and_compress builds from scratch every call).\n"
    "     * Zero h[] for hygiene; template_finalize fully overwrites. */\n"
    "    for (int i = 0; i < HASH_WORDS; i++) st->h[i] = 0u;\n"
    "}\n"
    "\n"
    "/* template_transform: stub for interface symmetry. MD6's template_finalize\n"
    " * builds the 89-ulong N[] in-place — never routes through this. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    (void)st;\n"
    "    (void)block;\n"
    "}\n"
    "\n"
    "/* template_finalize: compute the FIRST iter's md6_256(data, len) and store\n"
    " * it in st->h[] as 8 LE uint32. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    md6core_pack_and_compress(&st->h[0], data, len);\n"
    "}\n"
    "\n"
    "/* template_iterate: per-iter step.\n"
    " *   prev_digest = st->h[0..7] (already LE)\n"
    " *   hexbuf[64] = LOWERCASE_HEX(prev_digest)\n"
    " *   new_digest = md6_256(hexbuf, 64)\n"
    " *   st->h[0..7] = new_digest (LE)\n"
    " *\n"
    " * Mirrors the CPU iter step at mdxfind.c:25849-25852 (md6_hash + prmd5).\n"
    " * The 64-byte hex buffer fits comfortably in a single MD6 leaf block (b=512\n"
    " * bytes). */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    /* Build 64-byte LOWERCASE-hex of the prior digest. h[i] is LE uint32:\n"
    "     * hex order is byte 0 first, byte 3 last (low byte → high byte).\n"
    "     * Mirrors prmd5() at mdxfind.c which encodes bytes in little-endian\n"
    "     * memory order from the MD-style state. */\n"
    "    __attribute__((aligned(16))) uchar hexbuf[64];\n"
    "    for (int w = 0; w < 8; w++) {\n"
    "        uint sv = st->h[w];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uint byte = (sv >> (b * 8)) & 0xffu;\n"
    "            uint hi = (byte >> 4) & 0xfu;\n"
    "            uint lo = byte & 0xfu;\n"
    "            hexbuf[w * 8 + b * 2]     = (uchar)(hi + ((hi < 10u) ? '0' : ('a' - 10)));\n"
    "            hexbuf[w * 8 + b * 2 + 1] = (uchar)(lo + ((lo < 10u) ? '0' : ('a' - 10)));\n"
    "        }\n"
    "    }\n"
    "    /* Run md6_256 over the 64-char hex buffer. */\n"
    "    md6core_pack_and_compress(&st->h[0], hexbuf, 64);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table. h[0..3] is LE; the\n"
    " * compact table is keyed on the first 4 LE uint32 — no swap needed. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. MD6256 = 8 LE uint32 digest words. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        EMIT_HIT_8((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), ((st)->h)) \\\n"
    "    } while (0)\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        EMIT_HIT_8_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), ((st)->h), \\\n"
    "                   (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                   (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
;
