/* Auto-generated from gpu_hmac_blake2s_core.cl -- do not edit */
static const char gpu_hmac_blake2s_core_str[] =
    "/*\n"
    " * $Revision: 1.3 $\n"
    " * $Log: gpu_hmac_blake2s_core.cl,v $\n"
    " * Revision 1.3  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_hmac_blake2s_core.cl — HMAC-BLAKE2S algorithm core for the unified\n"
    " * dispatch template. Path A (hand-written) sibling of the codegen-emitted\n"
    " * salted cores.\n"
    " *\n"
    " * Family I HMAC-BLAKE2S carrier (2026-05-08): JOB_HMAC_BLAKE2S (e828) shares\n"
    " * a salted-template kernel slot. There is NO production JOB_BLAKE2SSALTPASS\n"
    " * algorithm; mode-0 of this kernel is structurally unreachable. Single\n"
    " * algo_mode (5) — there is no KPASS sibling op for HMAC-BLAKE2S in mdxfind.\n"
    " *\n"
    " * Hand-written rather than codegen because the BLAKE2 family carries\n"
    " * counter+flag in the per-algo state struct (RFC 7693) and uses a 4-arg\n"
    " * b2s_compress(uint *h, const uchar *block, ulong counter, int last) primitive\n"
    " * unlike the SHA / RIPEMD families that codegen targets. The codegen tool's\n"
    " * fragment library targets MD-style \"absorb 64-byte block + length-pad-tail\"\n"
    " * shapes; BLAKE2's counter-driven finalization doesn't fit that mold without\n"
    " * a dedicated fragment family. Path A authoring mirrors the unsalted\n"
    " * gpu_blake2s256_core.cl and inserts the HMAC body inside template_finalize\n"
    " * gated on algo_mode == 5u.\n"
    " *\n"
    " * HMAC-BLAKE2S semantics (mirrors mdxfind.c JOB_HMAC_BLAKE2S at line 30341\n"
    " * + slab oracle gpu_hmac_blake2s.cl):\n"
    " *   key = $pass (the candidate word being tested)\n"
    " *   msg = $salt (the per-hash salt)\n"
    " *   if (klen > 64) K = BLAKE2S(pass)            ; 32 bytes, zero-padded to 64\n"
    " *   else            K = pass                    ; zero-padded to 64 bytes\n"
    " *   inner = BLAKE2S((K XOR ipad) || msg)        ; 32-byte digest\n"
    " *   outer = BLAKE2S((K XOR opad) || inner)      ; 32-byte digest = HMAC output\n"
    " *\n"
    " * Hit-replay: host calls checkhashsalt(curin, 64, salt_bytes, salt_len, 0, job)\n"
    " * (iter=0 sentinel suppresses xNN suffix; mirrors KPASS hit-replay arms in\n"
    " * Families G/H). Output label is \"HMAC-BLAKE2S\" (no -KPASS suffix because the\n"
    " * op is named JOB_HMAC_BLAKE2S, not JOB_HMAC_BLAKE2S_KPASS — the algorithm is\n"
    " * KPASS-shape but mdxfind never named a KSALT sibling for this op).\n"
    " *\n"
    " * BLAKE2S-256 geometry (carried over from gpu_blake2s256_core.cl):\n"
    " *   - 64-byte block, 8 x uint32 chaining state, LITTLE-ENDIAN\n"
    " *   - 10-round G-function compression (b2s_compress in gpu_common.cl)\n"
    " *   - parameter block init: IV[0] ^ 0x01010020\n"
    " *     (digest_length=32 << 0 | key_length=0 << 8 | fanout=1 << 16 |\n"
    " *      depth=1 << 24)\n"
    " *   - 32-byte digest = 8 uint32 LE\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (8 for BLAKE2S-256)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64)\n"
    " *   template_state     — h[8] digest + t[2] counter + f[2] flag\n"
    " *   template_init      — install IV ^ parameter_block; zero counter+flag\n"
    " *   template_transform — absorb one 64-byte block (NON-FINAL)\n"
    " *   template_finalize  — branches on algo_mode:\n"
    " *                          == 5u  : HMAC body (early return after writing\n"
    " *                                   the 32-byte HMAC digest into st->h[])\n"
    " *                          else   : plain BLAKE2S(data) main body (mirror of\n"
    " *                                   gpu_blake2s256_core.cl; structurally\n"
    " *                                   unreachable in production but kept for\n"
    " *                                   correctness if any future op routes here\n"
    " *                                   in mode 0)\n"
    " *   template_iterate        — re-hash 64-char hex of digest (single-block)\n"
    " *   template_digest_compare — probe leading 16 bytes (h[0..3]) LE-direct\n"
    " *   template_emit_hit       — EMIT_HIT_8 (8 uint32 LE = 32 bytes)\n"
    " *\n"
    " * Source order at compile time (via gpu_opencl_template_compile_hmac_blake2s):\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_hmac_blake2s_core_str,\n"
    " *     gpu_template_str ]\n"
    " *\n"
    " * Defines string for cache key:\n"
    " *   \"HASH_WORDS=8,HASH_BLOCK_BYTES=64,HAS_SALT=1,SALT_POSITION=PREPEND,\n"
    " *    BASE_ALGO=blake2s,HMAC_KPASS=1\"\n"
    " *\n"
    " * Cache-key disambiguation from BLAKE2S256 unsalted core\n"
    " * (gpu_blake2s256_core_str): HAS_SALT=1 + SALT_POSITION=PREPEND axes are\n"
    " * absent in the unsalted defines string. From every other salted-template\n"
    " * core (sha1saltpass, rmd160saltpass, etc.): BASE_ALGO=blake2s axis is\n"
    " * unique. From any potential future BLAKE2SSALTPASS unsalted-msg variant:\n"
    " * HMAC_KPASS=1 axis distinguishes (no other salted core uses HMAC_KPASS=1).\n"
    " *\n"
    " * Bytecast invariants (carried over):\n"
    " *   - Final st->h[0..7] is LITTLE-ENDIAN per uint32 — direct probe + emit,\n"
    " *     no bswap32.\n"
    " *   - Wire format: 8 LE uint32 words written via EMIT_HIT_8.\n"
    " *   - Probe key uses st->h[0..3] (leading 16 bytes LE).\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single-private-buffer\n"
    " * pattern. State struct is private; b2s_compress takes __private uchar*\n"
    " * (existing primitive in gpu_common.cl). HMAC body uses three 64-byte\n"
    " * private uchar buffers (key_block / ipad_block / opad_block) plus a small\n"
    " * inner-digest staging buffer — all __private, no addrspace casts.\n"
    " *\n"
    " * R2 (register pressure): HMAC body adds key_block[64] + ipad_block[64] +\n"
    " * opad_block[64] + scratch + temporary state[8] = ~256 B over the unsalted\n"
    " * BLAKE2S finalize. Comparable to other HMAC carrier kernels (Family G:\n"
    " * RMD160, Family H: RMD320). Expected priv_mem on gfx1201 within the\n"
    " * documented 41-43 KB band for B5 sub-batch siblings.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key (R3 fix): defines_str carries\n"
    " * HASH_WORDS=8, HASH_BLOCK_BYTES=64, BASE_ALGO=blake2s plus HAS_SALT=1\n"
    " * and HMAC_KPASS=1 — pairwise distinct from all other template cores. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 8\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct. Identical layout to gpu_blake2s256_core.cl's\n"
    " * template_state — same h/t/f triple. The shared template body\n"
    " * (gpu_template.cl) only reads st.h[]; t[] and f[] are touched only by\n"
    " * the per-algo init/transform/finalize/iterate functions below. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];   /* digest chaining state, LE-per-uint32 */\n"
    "    uint t[2];            /* byte counter (low, high) */\n"
    "    uint f[2];            /* finalization flag (0 = mid-stream,\n"
    "                             0xFFFFFFFFu = last block) */\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install BLAKE2S256 IV XOR'd with parameter block.\n"
    " * Identical to gpu_blake2s256_core.cl's template_init. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) st->h[i] = B2S_IV[i];\n"
    "    st->h[0] ^= 0x01010020u;   /* digest_length=32, key=0, fanout=1, depth=1 */\n"
    "    st->t[0] = 0u; st->t[1] = 0u;\n"
    "    st->f[0] = 0u; st->f[1] = 0u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one full 64-byte block as a NON-FINAL block.\n"
    " * Public extension API. The HMAC body in template_finalize bypasses this\n"
    " * and inlines b2s_compress directly to avoid the function-call boundary\n"
    " * cost (matches the unsalted sibling's perf-fix lesson). */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint t0 = st->t[0] + (uint)HASH_BLOCK_BYTES;\n"
    "    uint carry = (t0 < st->t[0]) ? 1u : 0u;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "    ulong counter = ((ulong)st->t[0]) | (((ulong)st->t[1]) << 32);\n"
    "    b2s_compress(&st->h[0], block, counter, 0);\n"
    "}\n"
    "\n"
    "/* hmac_blake2s_run: helper that runs a complete BLAKE2S(buf[0..len-1])\n"
    " * and writes the 8 LE uint32 digest words into out[0..7].\n"
    " *\n"
    " * Used by the HMAC body to compute three independent BLAKE2S hashes:\n"
    " *   1. K = BLAKE2S(pass) when klen > 64 (rarely taken at GPU dispatch\n"
    " *      sizes; password lengths beyond 64 bytes are uncommon in our\n"
    " *      wordlist + rule range)\n"
    " *   2. inner = BLAKE2S((K^ipad) || msg)\n"
    " *   3. outer = BLAKE2S((K^opad) || inner)\n"
    " *\n"
    " * Matches the slab oracle's blake2s_hash() helper at gpu_hmac_blake2s.cl\n"
    " * line 10 and the CPU's blake2s() call signature at mdxfind.c:30367. */\n"
    "static inline void hmac_blake2s_run(uint *out,\n"
    "                                    const uchar *data, int datalen)\n"
    "{\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;\n"
    "\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    int pos = 0;\n"
    "    int rem = datalen;\n"
    "    int doff = 0;\n"
    "    ulong counter = 0;\n"
    "\n"
    "    while (rem > 0) {\n"
    "        if (pos == HASH_BLOCK_BYTES) {\n"
    "            counter += HASH_BLOCK_BYTES;\n"
    "            b2s_compress(h, buf, counter, 0);\n"
    "            pos = 0;\n"
    "        }\n"
    "        int take = HASH_BLOCK_BYTES - pos;\n"
    "        if (take > rem) take = rem;\n"
    "        for (int i = 0; i < take; i++) buf[pos + i] = data[doff + i];\n"
    "        pos  += take;\n"
    "        doff += take;\n"
    "        rem  -= take;\n"
    "    }\n"
    "    counter += (ulong)pos;\n"
    "    for (int i = pos; i < HASH_BLOCK_BYTES; i++) buf[i] = 0;\n"
    "    b2s_compress(h, buf, counter, 1);\n"
    "\n"
    "    for (int i = 0; i < 8; i++) out[i] = h[i];\n"
    "}\n"
    "\n"
    "/* template_finalize: dual-mode entry.\n"
    " *\n"
    " * algo_mode == 5u (Family I HMAC-BLAKE2S production path):\n"
    " *   compute HMAC(key=data, msg=salt) and write 32-byte digest to st->h[].\n"
    " *\n"
    " *   The host passes:\n"
    " *     data  = the candidate password word (HMAC key)\n"
    " *     len   = password length\n"
    " *   The salt comes from the salt buffer bound at SETARG (args 17/18/19);\n"
    " *   the kernel reads it via the standard salted-template salt_buf /\n"
    " *   salt_off / salt_lens trio. SALT_POSITION=PREPEND in defines_str;\n"
    " *   HAS_SALT=1 unlocks the salt-axis arg block. The shared template body\n"
    " *   threads salt bytes into a per-algo finalize via #ifdef GPU_TEMPLATE_HAS_SALT\n"
    " *   wiring at the call site.\n"
    " *\n"
    " * algo_mode != 5u (defensive plain BLAKE2S(data) path):\n"
    " *   matches gpu_blake2s256_core.cl's template_finalize for the unsalted\n"
    " *   case. Structurally unreachable in production (mode-0 of this kernel\n"
    " *   is dead code per the carrier-kernel design) but kept for correctness\n"
    " *   parity with the unsalted sibling.\n"
    " *\n"
    " * Salt bytes for the HMAC msg come via the standard salted-template\n"
    " * trio uploaded by gpu_opencl_set_salts(): __global salt_buf (raw salt\n"
    " * bytes), __global salt_off (per-salt byte offset), __global salt_lens\n"
    " * (per-salt length). gpu_template.cl threads `salt_buf + salt_off[i]` and\n"
    " * `salt_lens[i]` into template_finalize per the GPU_TEMPLATE_HAS_SALT\n"
    " * call signature at line 387 (gpu_template.cl rev 1.6+). */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "                                     , __global const uchar *salt_bytes\n"
    "                                     , uint salt_len\n"
    "                                     , uint algo_mode\n"
    "#endif\n"
    "                                     )\n"
    "{\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    if (algo_mode == 5u) {\n"
    "        /* HMAC-BLAKE2S(key=data, msg=salt). Mirrors mdxfind.c:30341-30400\n"
    "         * and the slab oracle gpu_hmac_blake2s.cl lines 38-97. */\n"
    "\n"
    "        /* Step 1: build K (key block, 64 bytes). */\n"
    "        uchar K[HASH_BLOCK_BYTES];\n"
    "        if (len > HASH_BLOCK_BYTES) {\n"
    "            /* key longer than block — hash it down to 32 bytes, zero-pad. */\n"
    "            uint kh[8];\n"
    "            hmac_blake2s_run(kh, data, len);\n"
    "            /* Spill 8 LE uint32 into K[0..31] byte-image. */\n"
    "            for (int i = 0; i < 8; i++) {\n"
    "                uint w = kh[i];\n"
    "                K[i*4 + 0] = (uchar)(w        & 0xFFu);\n"
    "                K[i*4 + 1] = (uchar)((w >>  8) & 0xFFu);\n"
    "                K[i*4 + 2] = (uchar)((w >> 16) & 0xFFu);\n"
    "                K[i*4 + 3] = (uchar)((w >> 24) & 0xFFu);\n"
    "            }\n"
    "            for (int i = 32; i < HASH_BLOCK_BYTES; i++) K[i] = 0;\n"
    "        } else {\n"
    "            for (int i = 0; i < len; i++) K[i] = data[i];\n"
    "            for (int i = len; i < HASH_BLOCK_BYTES; i++) K[i] = 0;\n"
    "        }\n"
    "\n"
    "        /* Step 2: inner = BLAKE2S((K XOR ipad) || msg).\n"
    "         *\n"
    "         * Salt length cap: mdxfind's MAXLINE / salt-pack geometry caps salt\n"
    "         * length well under 256 bytes; the slab oracle's ibuf[192] bound\n"
    "         * (gpu_hmac_blake2s.cl:76) covers our actual workload. We allocate\n"
    "         * 64 + 256 bytes for headroom on the ipad-buffer concat — same shape\n"
    "         * as the slab oracle plus 64 B extra. The salt buffer's actual length\n"
    "         * (salt_len) is bounded by salt_lens (uint16_t max via SETARG arg 19),\n"
    "         * so a 256-byte cap is safe at the salted-template salt-pack layer.\n"
    "         *\n"
    "         * salt_bytes is __global; copy salt bytes into private staging\n"
    "         * before hashing (the slab oracle does the same — gpu_hmac_blake2s.cl\n"
    "         * line 78 copies into a private uchar buffer).\n"
    "         *\n"
    "         * R1 mitigation (AMD ROCm comgr addrspace fragility): no\n"
    "         * __private/__global addrspace mixing inside b2s_compress; the\n"
    "         * staged ibuf[] is private, matching every other HMAC body in the\n"
    "         * template family. */\n"
    "        uint inner[8];\n"
    "        {\n"
    "            uchar ibuf[64 + 256];\n"
    "            for (int i = 0; i < HASH_BLOCK_BYTES; i++) ibuf[i] = K[i] ^ 0x36u;\n"
    "            uint slen = salt_len;\n"
    "            if (slen > 256u) slen = 256u;\n"
    "            for (uint i = 0; i < slen; i++) ibuf[64 + i] = salt_bytes[i];\n"
    "            hmac_blake2s_run(inner, ibuf, 64 + (int)slen);\n"
    "        }\n"
    "\n"
    "        /* Step 3: outer = BLAKE2S((K XOR opad) || inner). 64 + 32 = 96 bytes,\n"
    "         * fits in two 64-byte blocks. */\n"
    "        uint outer[8];\n"
    "        {\n"
    "            uchar obuf[64 + 32];\n"
    "            for (int i = 0; i < HASH_BLOCK_BYTES; i++) obuf[i] = K[i] ^ 0x5Cu;\n"
    "            for (int i = 0; i < 8; i++) {\n"
    "                uint w = inner[i];\n"
    "                obuf[64 + i*4 + 0] = (uchar)(w        & 0xFFu);\n"
    "                obuf[64 + i*4 + 1] = (uchar)((w >>  8) & 0xFFu);\n"
    "                obuf[64 + i*4 + 2] = (uchar)((w >> 16) & 0xFFu);\n"
    "                obuf[64 + i*4 + 3] = (uchar)((w >> 24) & 0xFFu);\n"
    "            }\n"
    "            hmac_blake2s_run(outer, obuf, 96);\n"
    "        }\n"
    "\n"
    "        /* Install HMAC digest into st->h[] for probe + emit. LE-direct\n"
    "         * (matches BLAKE2S' native byte order). Counter+flag updates are\n"
    "         * irrelevant after this point (template_iterate reinitializes them\n"
    "         * on -i loops); leave them as set by template_init. */\n"
    "        for (int i = 0; i < 8; i++) st->h[i] = outer[i];\n"
    "        return;\n"
    "    }\n"
    "    /* Defensive fall-through to plain BLAKE2S(data) for non-HMAC algo_modes.\n"
    "     * Production never reaches this in mode 0 because the carrier kernel\n"
    "     * has no JOB_BLAKE2SSALTPASS dispatch path. The salt_bytes/salt_len\n"
    "     * args are unused in this path; OpenCL's __global pointer cannot be\n"
    "     * cast to (void) cleanly across all compilers, so we let the optimizer\n"
    "     * elide them. */\n"
    "#endif\n"
    "\n"
    "    /* Plain BLAKE2S(data) main body. Identical to gpu_blake2s256_core.cl's\n"
    "     * template_finalize. Reachable only as defensive fallback. */\n"
    "    int pos = 0;\n"
    "    while ((len - pos) > HASH_BLOCK_BYTES) {\n"
    "        uint t0 = st->t[0] + (uint)HASH_BLOCK_BYTES;\n"
    "        uint carry = (t0 < st->t[0]) ? 1u : 0u;\n"
    "        st->t[0] = t0;\n"
    "        st->t[1] += carry;\n"
    "        ulong counter = ((ulong)st->t[0]) | (((ulong)st->t[1]) << 32);\n"
    "        b2s_compress(&st->h[0], data + pos, counter, 0);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    for (int i = 0; i < rem; i++) buf[i] = data[pos + i];\n"
    "    for (int i = rem; i < HASH_BLOCK_BYTES; i++) buf[i] = 0;\n"
    "\n"
    "    uint t0 = st->t[0] + (uint)rem;\n"
    "    uint carry = (t0 < st->t[0]) ? 1u : 0u;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "    ulong counter = ((ulong)st->t[0]) | (((ulong)st->t[1]) << 32);\n"
    "\n"
    "    st->f[0] = 0xFFFFFFFFu;\n"
    "    b2s_compress(&st->h[0], buf, counter, 1);\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the 32-byte BLAKE2s256 digest\n"
    " * as 64 lowercase hex chars and rehash. Identical to gpu_blake2s256_core.cl's\n"
    " * template_iterate.\n"
    " *\n"
    " * For HMAC-BLAKE2S (e828) the host forces max_iter=1 (CPU semantics at\n"
    " * mdxfind.c:30391 do not iter; checkhashsalt is called with iter=0). So in\n"
    " * production this function runs zero times for Family I — kept for\n"
    " * structural parity with the unsalted sibling and future-proofing if any\n"
    " * future HMAC-BLAKE2S iter variant is added. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint snap[8];\n"
    "    for (int i = 0; i < 8; i++) snap[i] = st->h[i];\n"
    "\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint s = snap[i];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uchar by = (uchar)((s >> (b * 8)) & 0xFFu);\n"
    "            uchar hi = by >> 4, lo = by & 0xFu;\n"
    "            buf[i * 8 + b * 2 + 0] = (hi < 10) ? (uchar)('0' + hi) : (uchar)('a' + (hi - 10));\n"
    "            buf[i * 8 + b * 2 + 1] = (lo < 10) ? (uchar)('0' + lo) : (uchar)('a' + (lo - 10));\n"
    "        }\n"
    "    }\n"
    "\n"
    "    for (int i = 0; i < 8; i++) st->h[i] = B2S_IV[i];\n"
    "    st->h[0] ^= 0x01010020u;\n"
    "    st->t[0] = 64u; st->t[1] = 0u;\n"
    "    st->f[0] = 0xFFFFFFFFu; st->f[1] = 0u;\n"
    "\n"
    "    b2s_compress(&st->h[0], buf, 64UL, 1);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe leading 16 bytes (h[0..3]). LE-direct\n"
    " * (no bswap32). Identical to gpu_blake2s256_core.cl. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. Wraps EMIT_HIT_8 (32-byte digest =\n"
    " * 8 LE uint32 words; matches HMAC-BLAKE2S' 32-byte output, hexlen=64). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_8((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_8_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
