/* Auto-generated from gpu_sha512_core.cl -- do not edit */
static const char gpu_sha512_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sha512_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha512_core.cl — SHA512 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 1).\n"
    " *\n"
    " * Mirrors gpu_sha256_core.cl rev 1.2 structure. SHA512 is the FIRST\n"
    " * 64-bit-state algorithm in the family AND the FIRST with 128-bit length\n"
    " * encoding (vs MD5/SHA1/SHA256's 64-bit). Internal compression carries\n"
    " * 8 × uint64 chaining values; the final digest is exposed to the\n"
    " * template as 16 × uint32 LE-byteswapped (HASH_WORDS = 16) so the\n"
    " * template body's `digests_out[gid * HASH_WORDS + i] = st.h[i]` and\n"
    " * EMIT_HIT_16-style emit work without 64-bit indirection.\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (16 for SHA512)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (128 — first deviation\n"
    " *                        from MD5/SHA1/SHA256's 64-byte block)\n"
    " *   template_state     — opaque per-lane state struct: ulong state[8]\n"
    " *                        for compression + uint h[16] for digest emit\n"
    " *   template_init      — install SHA-512 H[0..7] init constants (uint64)\n"
    " *   template_transform — absorb one 128-byte block (BIG-ENDIAN ulong load)\n"
    " *   template_finalize  — pad and finalize (in-place ulong M[16] pattern;\n"
    " *                        128-bit length encoded in M[14..15])\n"
    " *   template_iterate   — re-hash digest as 128-byte hex_lc (-i loop;\n"
    " *                        128 hex chars + 0x80 + 16-byte length needs\n"
    " *                        a SECOND block — same two-block pattern as\n"
    " *                        SHA256 iter)\n"
    " *   template_digest_compare — bswap64 first 2 ulong of state, decompose\n"
    " *                             into 4 LE uint32 (probe key)\n"
    " *   template_emit_hit       — EMIT_HIT_16 wrapper (16 LE uint32 words\n"
    " *                             from 8 ulong BE state)\n"
    " *\n"
    " * KEY POINTS vs SHA256 core:\n"
    " *\n"
    " * 1. Block size 128 bytes (16 ulong) instead of 64 bytes (16 uint).\n"
    " *    template_finalize iterates `len - pos >= 128`.\n"
    " *\n"
    " * 2. Length encoding 128-bit (M[14] high 64, M[15] low 64). For our\n"
    " *    wordlist inputs len < 2^57 bytes always, so M[14] = 0 and\n"
    " *    M[15] = len * 8.\n"
    " *\n"
    " * 3. 80-round compression with K512[80] uint64 constants and 64-bit\n"
    " *    Sigma/sigma functions (rotr64). sha512_block (gpu_common.cl\n"
    " *    line 756) handles the inner loop.\n"
    " *\n"
    " * 4. State width: 8 × uint64 internally; emit-time decompose into\n"
    " *    16 × uint32 LE matches gpu_sha512_packed.cl convention exactly.\n"
    " *    h[0] = (uint)bswap64(state[0]); h[1] = (uint)(bswap64(state[0]) >> 32).\n"
    " *    Compact-table probe key uses h[0..3] (leading 16 bytes LE) —\n"
    " *    same convention as MD5/SHA1/SHA256.\n"
    " *\n"
    " * 5. Iter loop. SHA512 hex output is 128 lowercase hex chars (64 digest\n"
    " *    bytes × 2). 128 + 1 (0x80) + 16 (length) = 145 bytes — exceeds one\n"
    " *    HASH_BLOCK_BYTES (128) block. Two-block pattern: block 1 holds the\n"
    " *    128 hex bytes BE (M[0..15]); block 2 has 0x80 marker at byte 128\n"
    " *    (M[0] = 0x8000000000000000UL BE), zeros M[1..14], M[15] = 128 * 8\n"
    " *    = 1024 (bit count low 64; high 64 in M[14] = 0).\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha512_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides sha512_block(), bswap64, sha512_to_hex_lc,\n"
    " * EMIT_HIT_16{,_DEDUP_OR_OVERFLOW}, and probe_compact_idx.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final state[0..7] (after compression) is BIG-ENDIAN — sha512_block's\n"
    " *     natural output. gpu_sha512_packed.cl matches.\n"
    " *   - st->h[0..15] holds 16 × uint32 LE-byteswapped digest words —\n"
    " *     populated by template_finalize / template_iterate at the end of\n"
    " *     each compression. Template body reads h[] directly.\n"
    " *   - template_emit_hit writes 16 LE-byteswapped uint32 to the hits\n"
    " *     buffer. Wire format matches gpu_sha512_packed.cl line 81's emit.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single private\n"
    " * buffer pattern. No __private uchar* helpers; no addrspace-cast\n"
    " * ternaries. ulong M[16] is private scratch only.\n"
    " *\n"
    " * R2 (register pressure): SHA512's W[80] schedule (80 × 8 = 640 bytes\n"
    " * private scratch) is the largest in the family so far. Combined with\n"
    " * the 8-ulong state and 16-uint h[], expected priv_mem_size on gfx1201\n"
    " * MAY push past the 41,332-byte SHA224/SHA256 reading. Memo B §3 R2\n"
    " * flagged the SHA-512 family as the gfx1201 register-pressure risk;\n"
    " * production gate is the byte-exact CPU↔GPU smoke. Document the reading\n"
    " * but proceed unless the kernel fails to build or actively crashes.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key (R3 fix) hashes the defines_str\n"
    " * \"HASH_WORDS=16,HASH_BLOCK_BYTES=128\" alongside source text so this\n"
    " * instantiation gets a distinct cache entry from MD5/SHA1/SHA256/SHA224/\n"
    " * MD4. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 16\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 128\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct. SHA512 carries 8 × uint64 chaining INTERNALLY\n"
    " * (state[]). The template body needs uint32 access to the digest for\n"
    " * digests_out[] and EMIT_HIT_16 — provide that via h[16] populated at\n"
    " * the end of each compression (template_finalize / template_iterate).\n"
    " * h[0..15] mirrors state[0..7] in LE-byteswapped uint32 pairs:\n"
    " *   h[2i]   = (uint)bswap64(state[i])\n"
    " *   h[2i+1] = (uint)(bswap64(state[i]) >> 32)\n"
    " *\n"
    " * This matches gpu_sha512_packed.cl line 67-73's split convention exactly.\n"
    " *\n"
    " * 16-byte alignment helps AMD spill geometry (cl_ulong required 8-byte;\n"
    " * declaring aligned(16) lets the compiler vectorize the M[] load). */\n"
    "typedef struct {\n"
    "    ulong state[8];   /* internal compression state, BIG-ENDIAN */\n"
    "    uint  h[HASH_WORDS]; /* exposed digest words, LE-byteswapped uint32 */\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install SHA512 IV into state.\n"
    " * Standard SHA-512 initial hash values (FIPS 180-4 §5.3.5). h[] is left\n"
    " * untouched; it is populated only after template_finalize / iterate\n"
    " * compress at least one block. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->state[0] = 0x6a09e667f3bcc908UL;\n"
    "    st->state[1] = 0xbb67ae8584caa73bUL;\n"
    "    st->state[2] = 0x3c6ef372fe94f82bUL;\n"
    "    st->state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "    st->state[4] = 0x510e527fade682d1UL;\n"
    "    st->state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "    st->state[6] = 0x1f83d9abfb41bd6bUL;\n"
    "    st->state[7] = 0x5be0cd19137e2179UL;\n"
    "}\n"
    "\n"
    "/* Internal helper: decompose state[8] (BE ulong) into h[16] (LE uint32).\n"
    " * Mirrors gpu_sha512_packed.cl line 67-73 exactly. */\n"
    "static inline void template_state_to_h(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = bswap64(st->state[i]);\n"
    "        st->h[i*2]   = (uint)s;\n"
    "        st->h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (128) byte block.\n"
    " * SHA512 reads message words BIG-ENDIAN, 64-bit (8 bytes per word).\n"
    " *\n"
    " * Public extension API; the hot-path template_finalize bypasses this\n"
    " * via an in-place ulong M[16] pattern (perf-fix lesson, see file head). */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    ulong M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 8;\n"
    "        M[j] = ((ulong)block[b]     << 56)\n"
    "             | ((ulong)block[b + 1] << 48)\n"
    "             | ((ulong)block[b + 2] << 40)\n"
    "             | ((ulong)block[b + 3] << 32)\n"
    "             | ((ulong)block[b + 4] << 24)\n"
    "             | ((ulong)block[b + 5] << 16)\n"
    "             | ((ulong)block[b + 6] << 8)\n"
    "             |  (ulong)block[b + 7];\n"
    "    }\n"
    "    sha512_block(&st->state[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process the tail, append the 0x80 padding marker\n"
    " * + 128-bit BE length-in-bits, and absorb. Caller passes the full\n"
    " * buffer; we run complete 128-byte blocks then build the final padded\n"
    " * block(s) here. After return, st->state[0..7] holds the final SHA512\n"
    " * digest words BE; st->h[0..15] holds the same in LE uint32 pairs.\n"
    " *\n"
    " * Mirrors gpu_sha256_core.cl rev 1.2's in-place M[16] pattern, scaled\n"
    " * to ulong + 128-byte blocks + 128-bit length. SHA512 length encoding:\n"
    " * M[14] = high 64 bits of bit count; M[15] = low 64 bits. For our\n"
    " * wordlist inputs len < 2^57 bytes (always), high 64 bits = 0. The\n"
    " * 0x80 marker straddles the 112-byte (= 56*2) boundary check: if\n"
    " * rem < 112, length fits in this block; else need an extra block.\n"
    " *\n"
    " * R1 mitigation preserved: single private buffer (just ulong M[16]\n"
    " * + the input data pointer). */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    ulong M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Process complete 128-byte blocks, BE ulong load. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 8;\n"
    "            M[j] = ((ulong)data[b]     << 56)\n"
    "                 | ((ulong)data[b + 1] << 48)\n"
    "                 | ((ulong)data[b + 2] << 40)\n"
    "                 | ((ulong)data[b + 3] << 32)\n"
    "                 | ((ulong)data[b + 4] << 24)\n"
    "                 | ((ulong)data[b + 5] << 16)\n"
    "                 | ((ulong)data[b + 6] << 8)\n"
    "                 |  (ulong)data[b + 7];\n"
    "        }\n"
    "        sha512_block(&st->state[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..127 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "\n"
    "    /* Copy remaining tail bytes BIG-ENDIAN. Each byte's position within\n"
    "     * its 64-bit word is determined by 7-(byte_idx & 7) shift. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 3;\n"
    "        int bi = 7 - (i & 7);\n"
    "        M[wi] |= ((ulong)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker, BE byte position. */\n"
    "    {\n"
    "        int wi = rem >> 3;\n"
    "        int bi = 7 - (rem & 7);\n"
    "        M[wi] |= ((ulong)0x80UL) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 112) {\n"
    "        /* Length fits in this block. M[14] = high 64 bits = 0;\n"
    "         * M[15] = low 64 bits = len * 8. */\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        sha512_block(&st->state[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    }\n"
    "\n"
    "    /* Decompose final state into h[16] LE uint32 for digest emit. */\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the digest as 128-byte\n"
    " * lowercase hex ASCII and rehash. SHA512's hex output is 128 chars,\n"
    " * which exactly fills one HASH_BLOCK_BYTES (128) block — but the\n"
    " * 0x80 marker + 16-byte length need a SECOND block.\n"
    " *\n"
    " * Mirrors gpu_sha512_packed.cl rev 1 lines 84-93 byte-for-byte:\n"
    " *   - sha512_to_hex_lc(state, M) : 8 ulong BE state -> 16 ulong BE\n"
    " *     hex M[] (each ulong holds 8 hex chars BE)\n"
    " *   - state reset to SHA512 IV; sha512_block(state, M)\n"
    " *   - second block: M[0] = 0x8000000000000000UL BE (0x80 at byte 128),\n"
    " *     M[1..14] = 0, M[15] = 128*8 = 1024\n"
    " *   - sha512_block(state, M) again\n"
    " *   - decompose state -> h[16]. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    ulong M[16];\n"
    "    /* sha512_to_hex_lc (gpu_common.cl line 780) writes 16 ulong BE\n"
    "     * hex words into M[] from state[]. */\n"
    "    sha512_to_hex_lc(&st->state[0], M);\n"
    "    /* Reset state to SHA512 IV; absorb the prepared hex block. */\n"
    "    st->state[0] = 0x6a09e667f3bcc908UL;\n"
    "    st->state[1] = 0xbb67ae8584caa73bUL;\n"
    "    st->state[2] = 0x3c6ef372fe94f82bUL;\n"
    "    st->state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "    st->state[4] = 0x510e527fade682d1UL;\n"
    "    st->state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "    st->state[6] = 0x1f83d9abfb41bd6bUL;\n"
    "    st->state[7] = 0x5be0cd19137e2179UL;\n"
    "    sha512_block(&st->state[0], M);\n"
    "\n"
    "    /* Second block: pad + length only. */\n"
    "    M[0] = 0x8000000000000000UL;     /* 0x80 BE at byte position 128 */\n"
    "    for (int j = 1; j < 15; j++) M[j] = 0UL;\n"
    "    M[14] = 0UL;\n"
    "    M[15] = 128UL * 8UL;             /* 128 hex chars = 1024 bits */\n"
    "    sha512_block(&st->state[0], M);\n"
    "\n"
    "    /* Decompose updated state into h[16]. */\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the leading\n"
    " * 16 bytes of the final digest. h[0..3] already holds the 4 LE uint32\n"
    " * leading words (populated by template_state_to_h via finalize/iterate).\n"
    " *\n"
    " * Mirrors gpu_sha512_packed.cl line 75-80 exactly: probe_compact[_idx]\n"
    " * called with h[0], h[1], h[2], h[3]. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. Wraps EMIT_HIT_16 (SHA512 = 16 uint32\n"
    " * digest words, populated LE-byteswapped in st->h by finalize/iterate).\n"
    " * Wire format matches gpu_sha512_packed.cl emit. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_16((hits), (hit_count), (max_hits), \\\n"
    "                (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. See gpu_md5_core.cl for protocol\n"
    " * notes. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_16_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
