/* Auto-generated from gpu_sha512_packed.cl -- do not edit */
static const char gpu_sha512_packed_str[] =
    "/* gpu_sha512_packed.cl — Packed password SHA512 kernel\n"
    " *\n"
    " * 128-byte block, max password 111 bytes.\n"
    " * ulong M[16], big-endian, 8-word state split to 16 uint32 for compact table.\n"
    " *\n"
    " * Primitives (bswap64, sha512_block, sha512_to_hex_lc, probe_compact,\n"
    " *             EMIT_HIT_16) from gpu_common.cl\n"
    " */\n"
    "\n"
    "__kernel void sha512_packed_batch(\n"
    "    __global const uchar *packed_buf,\n"
    "    __global const uint *word_offset,\n"
    "    __global const uchar *unused_mask,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_start = params.reserved32[0];\n"
    "    uint word_idx = word_start + tid;\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint pos = word_offset[word_idx];\n"
    "    uint len = packed_buf[pos++];\n"
    "\n"
    "    /* Build M[16] as ulong in little-endian first */\n"
    "    ulong M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    /* Pack bytes into ulong LE */\n"
    "    for (uint b = 0; b < len; b++) {\n"
    "        uint wi = b >> 3;\n"
    "        uint bi = (b & 7) << 3;\n"
    "        M[wi] |= (ulong)packed_buf[pos + b] << bi;\n"
    "    }\n"
    "    /* 0x80 padding */\n"
    "    { uint wi = len >> 3;\n"
    "      uint bi = (len & 7) << 3;\n"
    "      M[wi] |= (ulong)0x80 << bi;\n"
    "    }\n"
    "    /* Store bitlen in M[15] low 32 bits (LE) before swap */\n"
    "    M[15] = (ulong)(len * 8);\n"
    "\n"
    "    /* Byte-swap to big-endian */\n"
    "    uint bitlen = (uint)(len * 8);\n"
    "    for (int i = 0; i < 16; i++) M[i] = bswap64(M[i]);\n"
    "    M[14] = 0;\n"
    "    M[15] = (ulong)bitlen;\n"
    "\n"
    "    /* SHA512 compress */\n"
    "    ulong state[8] = {\n"
    "        0x6a09e667f3bcc908UL, 0xbb67ae8584caa73bUL,\n"
    "        0x3c6ef372fe94f82bUL, 0xa54ff53a5f1d36f1UL,\n"
    "        0x510e527fade682d1UL, 0x9b05688c2b3e6c1fUL,\n"
    "        0x1f83d9abfb41bd6bUL, 0x5be0cd19137e2179UL\n"
    "    };\n"
    "    sha512_block(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* Split 8 × uint64 BE state into 16 × uint32 LE for compact table */\n"
    "        uint h[16];\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            ulong s = bswap64(state[i]);\n"
    "            h[i*2]   = (uint)s;\n"
    "            h[i*2+1] = (uint)(s >> 32);\n"
    "        }\n"
    "\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe,\n"
    "                          params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes,\n"
    "                          overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_16(hits, hit_count, params.max_hits, word_idx, 0, iter, h)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            sha512_to_hex_lc(state, M);\n"
    "            state[0] = 0x6a09e667f3bcc908UL; state[1] = 0xbb67ae8584caa73bUL;\n"
    "            state[2] = 0x3c6ef372fe94f82bUL; state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "            state[4] = 0x510e527fade682d1UL; state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "            state[6] = 0x1f83d9abfb41bd6bUL; state[7] = 0x5be0cd19137e2179UL;\n"
    "            sha512_block(state, M);\n"
    "            M[0] = 0x8000000000000000UL;\n"
    "            for (int i = 1; i < 15; i++) M[i] = 0;\n"
    "            M[15] = 128 * 8;\n"
    "            sha512_block(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
