/* Auto-generated from gpu_ripemd160_core.cl -- do not edit */
static const char gpu_ripemd160_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_ripemd160_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_ripemd160_core.cl — RIPEMD-160 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 2).\n"
    " *\n"
    " * RIPEMD-160 is structurally between MD5 and SHA1:\n"
    " *   - LITTLE-ENDIAN message-word layout (like MD5; UNLIKE the SHA family)\n"
    " *   - 5 × uint32 state (like SHA1)\n"
    " *   - 64-byte block, 64-bit LE length encoding (like MD5)\n"
    " *   - 80-round dual-pipeline compression (left line + right line combined\n"
    " *     into a single 5-word state at the end)\n"
    " *\n"
    " * Mirrors gpu_sha1_core.cl rev 1.2 in dispatch shape (HASH_WORDS=5,\n"
    " * EMIT_HIT_5{,_DEDUP_OR_OVERFLOW}) and gpu_md5_core.cl rev 1.3 in byte\n"
    " * ordering (LE in template_finalize / template_iterate). The combination\n"
    " * gives us the 80-round dual-pipeline character of RIPEMD-160 over the\n"
    " * familiar MD-style 64-byte block.\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (5 for RIPEMD-160)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64)\n"
    " *   template_state     — 5 × uint32 chaining\n"
    " *   template_init      — install RIPEMD-160 IV\n"
    " *   template_transform — absorb one 64-byte block (LE word load,\n"
    " *                        rmd160_block from gpu_common.cl)\n"
    " *   template_finalize  — pad and finalize (LE pattern, in-place M[16];\n"
    " *                        same perf-fix lesson as MD5 / SHA1)\n"
    " *   template_iterate   — re-hash digest as 40-byte hex_lc (LE packing,\n"
    " *                        mirrors gpu_rmd160unsalted.cl iter loop)\n"
    " *   template_digest_compare — probe leading 16 bytes (h[0..3]) directly,\n"
    " *                             NO bswap32 (RIPEMD output is LE per uint32,\n"
    " *                             same convention as MD5 — the host-side\n"
    " *                             compact_table_register reads LE uint32 pairs;\n"
    " *                             matches gpu_rmd160unsalted.cl's\n"
    " *                             probe_compact(state[0..3]) call)\n"
    " *   template_emit_hit       — EMIT_HIT_5 wrapper, NO bswap32 (LE state\n"
    " *                             matches MD5 convention; see compare note)\n"
    " *\n"
    " * KEY DIFFERENCE FROM gpu_sha1_core.cl:\n"
    " *\n"
    " *   SHA-1 stores state words BIG-ENDIAN (sha1_block's natural output);\n"
    " *   the SHA-1 template byte-swaps state[0..3] to LE before probing the\n"
    " *   compact table and writes LE-byteswapped state into the hits buffer.\n"
    " *\n"
    " *   RIPEMD-160 stores state words LITTLE-ENDIAN (rmd160_block's natural\n"
    " *   output — confirmed by gpu_rmd160unsalted.cl line 113 which calls\n"
    " *   probe_compact(state[0], state[1], state[2], state[3], ...) without\n"
    " *   any bswap32). The compact-table probe and hit emit pass state words\n"
    " *   directly to the macros — same convention as MD5 / MD4.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_ripemd160_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides rmd160_block(), the RMD_F1..RMD_F5 + L1..L5 +\n"
    " * R1..R5 macros, EMIT_HIT_5{,_DEDUP_OR_OVERFLOW}, and probe_compact_idx.\n"
    " * gpu_md5_rules_str provides apply_rule (algorithm-agnostic). This file\n"
    " * provides the per-algorithm hooks. gpu_template_str ties them together.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final state[0..4] (after rmd160_block) is LITTLE-ENDIAN per uint32.\n"
    " *     Direct probe + direct emit; no bswap32.\n"
    " *   - apply_rule + buf in/out is identical to gpu_md5_rules.cl rev 1.28+.\n"
    " *   - template_finalize() builds M[16] DIRECTLY from input bytes via\n"
    " *     in-place LE shifts/OR-merge. Same perf-fix lesson as MD5/SHA1.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single-private-\n"
    " * buffer pattern preserved.\n"
    " *\n"
    " * R2 (register pressure): rmd160_block keeps two parallel 5-word lines\n"
    " * (A,B,C,D,E + a1,b1,c1,d1,e1) plus the 80 message-word references\n"
    " * (constant indices into M[16]). The dual-pipeline carries more live\n"
    " * state than MD5's single line; comparable to SHA1's W[80] schedule\n"
    " * but with smaller working storage (160 bits state vs SHA1's 160 bits\n"
    " * + 80-word schedule). Expected priv_mem_size on gfx1201 ~ comparable\n"
    " * to MD5/SHA1 readings (within +/-200 bytes).\n"
    " *\n"
    " * PERF-FIX LESSON (carried from gpu_md5_core.cl rev 1.2):\n"
    " *\n"
    " * template_finalize MUST build M[16] DIRECTLY from input bytes — not\n"
    " * via a private uchar pad[64] buffer that is then read back as message\n"
    " * words. The byte-store / byte-load round-trip cost was the 12.3% wall\n"
    " * regression in B2's first-cut MD5 template path. RIPEMD-160 follows\n"
    " * the same in-place pattern (LE byte ordering, LE 64-bit length in\n"
    " * M[14]).\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key (R3 fix) hashes the defines_str\n"
    " * \"HASH_WORDS=5,HASH_BLOCK_BYTES=64\" alongside source text. Same\n"
    " * defines as SHA1; distinct source text guarantees distinct cache\n"
    " * entry per gpu_kernel_cache.c rev 1.5+. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 5\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: RIPEMD-160 carries 5 uint32 chaining values. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install RIPEMD-160 IV.\n"
    " * Standard RIPEMD-160 initial hash values (RIPEMD-160 spec §1; same\n"
    " * leading 4 words as MD5/SHA1 plus a fifth 0xC3D2E1F0). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (64) byte block.\n"
    " * `block` points into the working buffer at the absorb position;\n"
    " * the caller must guarantee >=64 bytes are readable. RIPEMD-160 reads\n"
    " * message words LITTLE-ENDIAN (like MD5).\n"
    " *\n"
    " * Public extension API; the hot-path template_finalize bypasses this\n"
    " * via an in-place M[16] pattern. Kept symmetric with the rest of the\n"
    " * core family for consumers preferring the function-style entry. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* RIPEMD-160 reads message words little-endian (same as MD5). */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    rmd160_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process the tail, append 0x80 padding marker +\n"
    " * 64-bit LE length-in-bits, and absorb. Caller passes the full buffer;\n"
    " * we run complete blocks then build the final padded block(s) here.\n"
    " * After return, st->h[0..4] holds the final RIPEMD-160 digest words\n"
    " * in LITTLE-ENDIAN form (rmd160_block's natural output).\n"
    " *\n"
    " * Mirrors gpu_md5_core.cl rev 1.2's in-place M[16] pattern (same LE\n"
    " * byte ordering and 64-bit LE length encoding). The 5th state word is\n"
    " * carried by rmd160_block transparently — the finalize logic is\n"
    " * structurally identical to MD5's; only the compression call differs. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Process complete 64-byte blocks. Build M[] LITTLE-ENDIAN\n"
    "     * directly from bytes (no intermediate pad[]). */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        rmd160_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    /* Build final block(s): tail bytes + 0x80 marker + zeros + 64-bit\n"
    "     * LE length. Direct-into-M[] approach. */\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Copy remaining tail bytes into M[] little-endian. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker (LE byte position). */\n"
    "    M[rem >> 2] |= (uint)0x80u << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        /* Length fits in this block. RIPEMD-160 LE: M[14] = low 32\n"
    "         * bits of bit count, M[15] = high 32 bits. For len < 2^29 bytes\n"
    "         * (always true for our wordlist inputs), high 32 bits = 0. */\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        M[15] = 0u;\n"
    "        rmd160_block(&st->h[0], M);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        rmd160_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        M[15] = 0u;\n"
    "        rmd160_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode digest as 40-byte lowercase\n"
    " * hex ASCII and rehash. RIPEMD-160 hex output is 40 chars (5 words ×\n"
    " * 8 chars = 40 hex chars) — same width as SHA1 — but the byte ordering\n"
    " * is LE.\n"
    " *\n"
    " * Mirrors gpu_rmd160unsalted.cl lines 119-133 byte-for-byte:\n"
    " *   - 5 LE state words → 10 LE-encoded hex M[] words (2 words per\n"
    " *     state word, 4 hex chars each)\n"
    " *   - M[10] = 0x80 (LE 0x80 padding at byte offset 40)\n"
    " *   - M[11..13] = 0\n"
    " *   - M[14] = 40 * 8 = 320 (low 32 bits of bit count)\n"
    " *   - M[15] = 0\n"
    " *   - state reset to RIPEMD-160 IV; rmd160_block. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* Hex-encode 5 LE state words into M[0..9] (40 hex chars, LE\n"
    "     * packing). hex_byte_lc helper from gpu_common.cl produces a 16-bit\n"
    "     * LE pair (low byte = low hex digit, high byte = high hex digit;\n"
    "     * because we store the result into M[] LE this corresponds to the\n"
    "     * correct ASCII byte order in the message stream). */\n"
    "    for (int i = 0; i < 5; i++) {\n"
    "        uint s = st->h[i];\n"
    "        uint b0 = s & 0xff,        b1 = (s >> 8) & 0xff;\n"
    "        uint b2 = (s >> 16) & 0xff, b3 = (s >> 24) & 0xff;\n"
    "        M[i*2]     = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "        M[i*2 + 1] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "    }\n"
    "    M[10] = 0x80u;                   /* LE 0x80 at byte offset 40 */\n"
    "    for (int j = 11; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 40u * 8u;                /* 40 hex chars = 320 bits */\n"
    "    M[15] = 0u;\n"
    "    /* Reinitialize state to RIPEMD-160 IV; absorb the prepared M[]. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "    rmd160_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the final\n"
    " * digest. RIPEMD-160 state is stored LITTLE-ENDIAN (rmd160_block's\n"
    " * natural form — confirmed by gpu_rmd160unsalted.cl line 113 calling\n"
    " * probe_compact(state[0..3]) without any byte-swap). The compact table\n"
    " * is keyed on the leading 16 BYTES of the digest in little-endian\n"
    " * uint32 form (host-side compact_table_register reads digest bytes as\n"
    " * 4 LE uint32). State words flow directly into the probe — same\n"
    " * convention as MD5 / MD4.\n"
    " *\n"
    " * The 5th state word (h[4]) is NOT used by the compact-table probe —\n"
    " * only by EMIT_HIT_5 below. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit into the global hits buffer. Wraps\n"
    " * EMIT_HIT_5 (RIPEMD-160 = 5 uint32 digest words). Hits buffer\n"
    " * convention matches gpu_rmd160unsalted.cl: state words go directly,\n"
    " * no bswap32 (LE state matches the LE hits-buffer convention used by\n"
    " * the host hit-replay path for LE-native algorithms). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_5((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. The template body uses this entry;\n"
    " * hashes_shown bit is rolled back on overflow per gpu_common.cl §B3\n"
    " * protocol. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_5_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
