/* Auto-generated from gpu_kernel_a_masks.cl -- do not edit */
static const char gpu_kernel_a_masks_str[] =
    "/*\n"
    " * $Revision: $\n"
    " * $Log: $\n"
    " *\n"
    " */\n"
    "/* gpu_kernel_a_masks.cl -- Kernel A2 (masks-only) candidate producer.\n"
    " *\n"
    " * Production kernel A variant A2 per Phase 1a sub-phase 1a.2 spec\n"
    " *   project_kernel_a_a2_masks_spec_2026-05-20.md\n"
    " * with 2026-05-30 long-mask amendment (D1.b Design Y wire format)\n"
    " *   project_kernel_a_a2_a3_long_mask_amendment_2026-05-30.md.\n"
    " *\n"
    " * Produces packed candidates from input words x mask combinations via\n"
    " * the buffer-quadruple API (b_packed_buf, b_chunk_index, b_kernelA_state,\n"
    " * b_params). Output is consumable by any kernel B that obeys the\n"
    " * buffer-quadruple contract; in this codebase the existing kernel B\n"
    " * salt-axis dispatcher (gpu_opencl_kernelb_dispatch_proto) is the\n"
    " * primary consumer.\n"
    " *\n"
    " * Topology (per parent spec a2 sec.10.2 decision):\n"
    " *   mask-major outer, word-parallel inner.\n"
    " *   global_size = n_words * n_masks\n"
    " *   word_idx    = gid % n_words\n"
    " *   mask_idx    = gid / n_words\n"
    " *\n"
    " * Wire format (2026-05-30 D1.b Design Y -- interleaved run-descriptor):\n"
    " *\n"
    " *   GPU_MASK_DESC_TAG_LIT (0x00) lit_len:u16 (little-endian) bytes[lit_len]\n"
    " *   GPU_MASK_DESC_TAG_VAR (0x01) classid:u8     (one placeholder)\n"
    " *   GPU_MASK_DESC_TAG_END (0xFF) terminator\n"
    " *\n"
    " * Per-side caps:\n"
    " *   GPU_MASK_VAR_CAP       = 16   placeholder positions\n"
    " *   GPU_MASK_LIT_BYTES_CAP = 224  literal bytes\n"
    " *   GPU_MASK_DESC_BYTES_CAP= 320  descriptor stream byte cap\n"
    " *\n"
    " * The walker (mask_expand_run_into_gpu) is a unified 2-pass design that\n"
    " * handles ALL CPU-parsable mask shapes (literal-only, var-only,\n"
    " * interleaved). Per amendment D4.a there is NO short-mask fast path;\n"
    " * the same walker covers pre-amendment workloads (?d?d, ?l, etc.) and\n"
    " * post-amendment long-lit workloads byte-identically.\n"
    " *\n"
    " * Pass 1: scan descriptor, copy literal runs verbatim, mark each VAR\n"
    " *         position with a (classid, outpos) entry in a per-thread table.\n"
    " * Pass 2: walk the VAR table HIGH-TO-LOW and consume idx %= cc / idx /= cc\n"
    " *         in order to preserve CPU's mask_expand_into semantics\n"
    " *         (mdxfind.c:7840-7848).\n"
    " *\n"
    " * Mechanical lineage: this kernel ports the CPU mask_expand_into helper\n"
    " * from mdxfind.c lines 7836-7849 directly into per-thread private state.\n"
    " * The descriptor walker handles the new wire format; the CPU oracle\n"
    " * still operates on the MaskPos[] layout.\n"
    " *\n"
    " * Authoritative buffer contract:\n"
    " *   project_two_kernel_candidate_buffer_contract.md\n"
    " *\n"
    " * Contract per buffer (identical to A1):\n"
    " *   b_packed_buf        - [len][bytes][len][bytes]... post-mask candidates.\n"
    " *   b_chunk_index       - uint32 per slot. b_chunk_index[slot] = byte\n"
    " *                         offset where this candidate's len byte lives.\n"
    " *   b_kernelA_state     - small counter buffer (same layout as A1):\n"
    " *                           offset 0 : uint slot_counter\n"
    " *                           offset 4 : uint byte_counter\n"
    " *                           offset 8 : uint overflow_flag\n"
    " *\n"
    " * OCLParams fields consumed by A2:\n"
    " *   num_words           = batch word count\n"
    " *   num_masks           = MaskTotal = MaskPrependTotal * MaskAppendTotal\n"
    " *   n_prepend           = descriptor stream BYTE LENGTH for prepend side\n"
    " *                         (post-amendment semantic; was position-count\n"
    " *                         pre-amendment)\n"
    " *   n_append            = descriptor stream BYTE LENGTH for append side\n"
    " *   base_word_idx       = source word index (for kernel B attribution)\n"
    " *   packed_size         = bytes available in b_packed_buf\n"
    " */\n"
    "\n"
    "/* Wire-format tags (must match mdxfind.c host packer). */\n"
    "#define GPU_MASK_DESC_TAG_LIT   0x00u\n"
    "#define GPU_MASK_DESC_TAG_VAR   0x01u\n"
    "#define GPU_MASK_DESC_TAG_END   0xFFu\n"
    "\n"
    "/* Per-side caps (must match mdxfind.c host defines). */\n"
    "#define GPU_MASK_VAR_CAP        16\n"
    "#define GPU_MASK_LIT_BYTES_CAP  224\n"
    "#define GPU_MASK_DESC_BYTES_CAP 320\n"
    "\n"
    "/* Per-thread expanded-mask scratch capacity. lit_bytes + var positions. */\n"
    "#define GPU_MASK_SIDE_EXPANDED_CAP (GPU_MASK_LIT_BYTES_CAP + GPU_MASK_VAR_CAP)\n"
    "\n"
    "/* Final candidate length cap (uchar len byte). */\n"
    "#define MASK_FINAL_LEN_LIMIT   255u\n"
    "\n"
    "/* Kernel-A state buffer offsets. */\n"
    "#define KERNELA_STATE_SLOT_COUNTER   0u\n"
    "#define KERNELA_STATE_BYTE_COUNTER   4u\n"
    "#define KERNELA_STATE_OVERFLOW_FLAG  8u\n"
    "#define KERNELA_STATE_BYTES         12u\n"
    "\n"
    "/* Charset table flat-array stride. MASK_MAX_CLASSES * 256 bytes total. */\n"
    "#define MASK_CHARSET_STRIDE          256u\n"
    "\n"
    "/* ==== Mask expander helper (post-amendment 2026-05-30) ===============\n"
    " *\n"
    " * Walks a run-descriptor stream and produces the expanded mask bytes\n"
    " * into the thread-private outbuf. Returns total expanded length.\n"
    " *\n"
    " * Per the D4.a single-unified-walker decision, both pre-amendment short\n"
    " * masks and post-amendment long-lit masks take this path.\n"
    " *\n"
    " * Per amendment §5 the walker uses a 2-pass design to preserve the CPU\n"
    " * mask_expand_into semantics (right-to-left variable consumption order\n"
    " * via decreasing-i loop at mdxfind.c:7840). Pass 1 lays out the\n"
    " * descriptor; Pass 2 walks variables high-to-low to consume idx.\n"
    " *\n"
    " * All lanes in a workgroup read the SAME descriptor (mask is workgroup-\n"
    " * invariant). Branch dispatch is warp-coherent; divergence is zero. */\n"
    "static int mask_expand_run_into_gpu(\n"
    "    ulong idx,\n"
    "    __global const uchar *desc,\n"
    "    uint desc_bytes,                          /* upper bound for safety */\n"
    "    __global const uchar *mask_charsets,\n"
    "    __global const uint  *mask_class_counts,\n"
    "    uchar *outbuf)\n"
    "{\n"
    "    /* Pass 1: scan descriptor, copy literals, record var positions. */\n"
    "    uchar var_classids[GPU_MASK_VAR_CAP];\n"
    "    uint  var_outpos[GPU_MASK_VAR_CAP];\n"
    "    int   n_vars  = 0;\n"
    "    int   out_len = 0;\n"
    "    uint  p       = 0;\n"
    "\n"
    "    while (p < desc_bytes) {\n"
    "        uchar tag = desc[p++];\n"
    "        if (tag == GPU_MASK_DESC_TAG_END) break;\n"
    "        if (tag == GPU_MASK_DESC_TAG_LIT) {\n"
    "            if (p + 2u > desc_bytes) break;\n"
    "            uint lit_len = (uint)desc[p] | ((uint)desc[p + 1u] << 8);\n"
    "            p += 2u;\n"
    "            if (p + lit_len > desc_bytes) break;\n"
    "            /* Bounded copy. lit_len <= GPU_MASK_LIT_BYTES_CAP per\n"
    "             * gpu_pack_mask_descriptor()'s caller invariant. */\n"
    "            for (uint i = 0; i < lit_len; i++) {\n"
    "                outbuf[out_len + (int)i] = desc[p + i];\n"
    "            }\n"
    "            out_len += (int)lit_len;\n"
    "            p += lit_len;\n"
    "        } else if (tag == GPU_MASK_DESC_TAG_VAR) {\n"
    "            if (p + 1u > desc_bytes) break;\n"
    "            uchar cid = desc[p++];\n"
    "            if (n_vars >= GPU_MASK_VAR_CAP) break;  /* defensive */\n"
    "            var_classids[n_vars] = cid;\n"
    "            var_outpos[n_vars]   = (uint)out_len;\n"
    "            outbuf[out_len] = 0;\n"
    "            out_len += 1;\n"
    "            n_vars  += 1;\n"
    "        } else {\n"
    "            /* Unknown tag: bail. Host invariant guarantees this never\n"
    "             * happens; we silently truncate to whatever was decoded. */\n"
    "            break;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Pass 2: expand variables HIGH-TO-LOW to preserve CPU's\n"
    "     * mdxfind.c:7836-7849 left-to-right pattern indexing under reverse\n"
    "     * iteration (the CPU's i = patlen-1; i--; loop). */\n"
    "    for (int i = n_vars - 1; i >= 0; i--) {\n"
    "        uint  cid = (uint)var_classids[i];\n"
    "        uint  cc  = mask_class_counts[cid];\n"
    "        if (cc == 0u) cc = 1u;\n"
    "        outbuf[var_outpos[i]] = mask_charsets[cid * MASK_CHARSET_STRIDE\n"
    "                                              + (uint)(idx % (ulong)cc)];\n"
    "        idx /= (ulong)cc;\n"
    "    }\n"
    "\n"
    "    return out_len;\n"
    "}\n"
    "\n"
    "/* ==== Per-side cardinality helper ====================================\n"
    " *\n"
    " * Compute the product of class sizes (placeholder positions) in a\n"
    " * descriptor stream. Returns 1 when stream has zero VAR runs (matches\n"
    " * CPU convention; MaskTotal is 1 when the corresponding side is unused\n"
    " * or literal-only). */\n"
    "static ulong mask_pattern_total_run(\n"
    "    __global const uchar *desc,\n"
    "    uint desc_bytes,\n"
    "    __global const uint  *mask_class_counts)\n"
    "{\n"
    "    ulong total = 1ul;\n"
    "    uint  p     = 0;\n"
    "    while (p < desc_bytes) {\n"
    "        uchar tag = desc[p++];\n"
    "        if (tag == GPU_MASK_DESC_TAG_END) break;\n"
    "        if (tag == GPU_MASK_DESC_TAG_LIT) {\n"
    "            if (p + 2u > desc_bytes) break;\n"
    "            uint lit_len = (uint)desc[p] | ((uint)desc[p + 1u] << 8);\n"
    "            p += 2u + lit_len;\n"
    "        } else if (tag == GPU_MASK_DESC_TAG_VAR) {\n"
    "            if (p + 1u > desc_bytes) break;\n"
    "            uchar cid = desc[p++];\n"
    "            uint cc = mask_class_counts[(uint)cid];\n"
    "            if (cc > 0u) total *= (ulong)cc;\n"
    "        } else {\n"
    "            break;\n"
    "        }\n"
    "    }\n"
    "    return total;\n"
    "}\n"
    "\n"
    "/* ---- Kernel A2 (masks-only) production kernel --------------------\n"
    " *\n"
    " * Payload layout identical to A1 / md5_rules_phase0:\n"
    " *\n"
    " *   offset   0 : OCLParams params\n"
    " *   offset 128 : uint hit_count\n"
    " *   offset 132 : uint word_offset[num_words]\n"
    " *   offset 132 + 4*num_words : uchar packed_words[]\n"
    " *\n"
    " * Output buffer caps:\n"
    " *   b_packed_buf       capacity = params.packed_size bytes\n"
    " *   b_chunk_index      capacity = params.num_words * params.num_masks slots\n"
    " *\n"
    " * 8-arg signature is BYTE-IDENTICAL to pre-amendment. Only the semantic\n"
    " * of mask_pattern_prepend / mask_pattern_append changes: they are now\n"
    " * run-descriptor streams sized GPU_MASK_DESC_BYTES_CAP (320 B) each.\n"
    " * params.n_prepend / params.n_append carry the descriptor stream BYTE\n"
    " * LENGTH (used as an upper-bound safety guard inside the walker loop).\n"
    " */\n"
    "__kernel\n"
    "void cand_masks_phase0(\n"
    "    __global uchar         *payload,\n"
    "    __global const uchar   *mask_pattern_prepend,\n"
    "    __global const uchar   *mask_pattern_append,\n"
    "    __global const uchar   *mask_charsets,\n"
    "    __global const uint    *mask_class_counts,\n"
    "    __global uchar         *b_packed_buf,\n"
    "    __global uint          *b_chunk_index,\n"
    "    __global volatile uint *b_kernelA_state\n"
    "    )\n"
    "{\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words      = params.num_words;\n"
    "    uint n_masks      = params.num_masks;\n"
    "    uint prep_dbytes  = params.n_prepend;   /* descriptor stream byte length */\n"
    "    uint app_dbytes   = params.n_append;    /* descriptor stream byte length */\n"
    "    uint total        = n_words * n_masks;\n"
    "\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint mask_idx = gid / n_words;\n"
    "\n"
    "    /* Compute append-side cardinality from the descriptor stream.\n"
    "     * Uniform across the workgroup (all lanes read the same descriptor),\n"
    "     * so warp-coherent. */\n"
    "    ulong append_total = mask_pattern_total_run(mask_pattern_append,\n"
    "                                                app_dbytes,\n"
    "                                                mask_class_counts);\n"
    "\n"
    "    /* mdxfind procjob convention (mdxfind.c:12348-12349):\n"
    "     *   append_idx  = idx % MaskAppendTotal\n"
    "     *   prepend_idx = idx / MaskAppendTotal\n"
    "     *\n"
    "     * append_total is guaranteed >= 1 by mask_pattern_total_run's empty\n"
    "     * stream semantics; the guard below mirrors pre-amendment defensive\n"
    "     * code. */\n"
    "    ulong append_idx;\n"
    "    ulong prepend_idx;\n"
    "    if (append_total > 0ul) {\n"
    "        append_idx  = (ulong)mask_idx % append_total;\n"
    "        prepend_idx = (ulong)mask_idx / append_total;\n"
    "    } else {\n"
    "        append_idx  = 0ul;\n"
    "        prepend_idx = (ulong)mask_idx;\n"
    "    }\n"
    "\n"
    "    /* Per-thread expanded-mask scratch. 240 B each side; 480 B per WI;\n"
    "     * 30 KB per WG at WG=64. Fits Pascal 65 KB and Apple M1 32 KB\n"
    "     * threadgroup limits. */\n"
    "    uchar prebuf[GPU_MASK_SIDE_EXPANDED_CAP];\n"
    "    uchar appbuf[GPU_MASK_SIDE_EXPANDED_CAP];\n"
    "\n"
    "    int prelen = mask_expand_run_into_gpu(prepend_idx,\n"
    "                                          mask_pattern_prepend, prep_dbytes,\n"
    "                                          mask_charsets, mask_class_counts,\n"
    "                                          prebuf);\n"
    "    int applen = mask_expand_run_into_gpu(append_idx,\n"
    "                                          mask_pattern_append,  app_dbytes,\n"
    "                                          mask_charsets, mask_class_counts,\n"
    "                                          appbuf);\n"
    "\n"
    "    /* Decode input word from payload (same layout as A1). */\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    uint wlen = (uint)words[wpos++];\n"
    "\n"
    "    /* Final candidate length: [prebuf][word][appbuf]. */\n"
    "    uint final_len = (uint)prelen + wlen + (uint)applen;\n"
    "    if (final_len > MASK_FINAL_LEN_LIMIT) return;\n"
    "\n"
    "    /* Reserve slot + byte offset (A1's atomic discipline). */\n"
    "    uint need_bytes = 1u + final_len;\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes);\n"
    "\n"
    "    if (byte_off + need_bytes > params.packed_size) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    uint slot = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u], 1u);\n"
    "\n"
    "    if (slot >= total) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    /* Write [len][bytes] into packed buf. */\n"
    "    b_packed_buf[byte_off] = (uchar)final_len;\n"
    "    uint p = byte_off + 1u;\n"
    "    for (int i = 0; i < prelen; i++) b_packed_buf[p++] = prebuf[i];\n"
    "    for (uint i = 0; i < wlen;   i++) b_packed_buf[p++] = words[wpos + i];\n"
    "    for (int i = 0; i < applen; i++) b_packed_buf[p++] = appbuf[i];\n"
    "\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "}\n"
;
