/* Auto-generated from gpu_kernel_a_masks.cl -- do not edit */
static const char gpu_kernel_a_masks_str[] =
    "/*\n"
    " * $Revision: $\n"
    " * $Log: $\n"
    " *\n"
    " */\n"
    "/* gpu_kernel_a_masks.cl -- Kernel A2 (masks-only) candidate producer.\n"
    " *\n"
    " * Production kernel A variant A2 per Phase 1a sub-phase 1a.2 spec\n"
    " *   project_kernel_a_a2_masks_spec_2026-05-20.md.\n"
    " *\n"
    " * Produces packed candidates from input words x mask combinations via\n"
    " * the buffer-quadruple API (b_packed_buf, b_chunk_index, b_kernelA_state,\n"
    " * b_params). Output is consumable by any kernel B that obeys the\n"
    " * buffer-quadruple contract; in this codebase the existing kernel B\n"
    " * salt-axis dispatcher (gpu_opencl_kernelb_dispatch_proto) is the\n"
    " * primary consumer.\n"
    " *\n"
    " * Topology (per parent spec a2 sec.10.2 decision):\n"
    " *   mask-major outer, word-parallel inner.\n"
    " *   global_size = n_words * n_masks\n"
    " *   word_idx    = gid % n_words\n"
    " *   mask_idx    = gid / n_words\n"
    " *\n"
    " * Mechanical lineage: this kernel does NOT port from gpu_template.cl's\n"
    " * mask-as-salt-axis path (which slices a single mask combination across\n"
    " * a workgroup); rather, it ports the CPU mask_expand_into helper from\n"
    " * mdxfind.c lines 7646-7660 directly into per-thread private state. Each\n"
    " * lane independently materializes one (word, prepend_mask, append_mask)\n"
    " * triple into the packed buffer with a per-slot byte offset.\n"
    " *\n"
    " * Authoritative buffer contract:\n"
    " *   project_two_kernel_candidate_buffer_contract.md\n"
    " * Phase 1a A2-variant spec:\n"
    " *   project_kernel_a_a2_masks_spec_2026-05-20.md\n"
    " *\n"
    " * Contract per buffer (identical to A1):\n"
    " *   b_packed_buf        - [len][bytes][len][bytes]... post-mask candidates.\n"
    " *                         len byte stored as uchar; bytes follow uncompressed.\n"
    " *                         Written at slot's reserved byte offset.\n"
    " *   b_chunk_index       - uint32 per slot. b_chunk_index[slot] = byte offset\n"
    " *                         into b_packed_buf where this candidate's len byte\n"
    " *                         lives. Pure physical byte offsets only.\n"
    " *   b_kernelA_state     - small counter buffer (same layout as A1):\n"
    " *                           offset 0 : uint slot_counter   (atomic_inc)\n"
    " *                           offset 4 : uint byte_counter   (atomic_add for\n"
    " *                                                            variable-size\n"
    " *                                                            byte reservation)\n"
    " *                           offset 8 : uint overflow_flag  (set if either\n"
    " *                                                            counter exceeds\n"
    " *                                                            its capacity)\n"
    " *\n"
    " * Mask pattern wire encoding (D9.2.a -- 0xff sentinel):\n"
    " *   Each MaskPos is encoded as 2 bytes:\n"
    " *     byte 0: classid (0..7 builtin, 8..15 custom, 0xff = MASK_LITERAL)\n"
    " *     byte 1: literal character (only meaningful when classid == 0xff)\n"
    " *   mask_pattern_prepend, mask_pattern_append each carry MAX_MASK_POS_GPU\n"
    " *   entries (32 bytes total per side); only the first n_prepend / n_append\n"
    " *   are read.\n"
    " *\n"
    " *   The host upload path encodes mdxfind's MaskPos.classid (signed int, -1\n"
    " *   for MASK_LITERAL) as 0xff at upload time. The kernel never sees the\n"
    " *   CPU's signed -1 sentinel; comparison is unsigned uchar == 0xff.\n"
    " *\n"
    " * Charset table layout:\n"
    " *   mask_charsets:     MASK_MAX_CLASSES (=16) x 256 bytes flat. Class N's\n"
    " *                      characters live at mask_charsets[N*256 + i], i in\n"
    " *                      [0, mask_class_counts[N]).\n"
    " *   mask_class_counts: uint32 per class. Caps at 256 (e.g. ?b = 256, ?a = 95).\n"
    " *\n"
    " * Walker behavior:\n"
    " *   1. Decode payload -> params, word_offset, words (same layout as A1).\n"
    " *   2. Decompose gid -> (word_idx, mask_idx) mask-major.\n"
    " *   3. Compute prepend_total / append_total from the patterns (cheap loop;\n"
    " *      patlen <= 16).\n"
    " *   4. Split mask_idx -> (prepend_idx, append_idx) via mod/div by\n"
    " *      append_total; the convention matches mdxfind.c procjob lines\n"
    " *      12111-12162.\n"
    " *   5. mask_expand_into_gpu(prepend_idx, prepend_pattern, ...) -> prebuf[]\n"
    " *      mask_expand_into_gpu(append_idx,  append_pattern,  ...) -> appbuf[]\n"
    " *   6. Compose final candidate as [prebuf][word][appbuf]; clamp len to 255.\n"
    " *   7. Reserve slot + byte offset (identical atomic discipline to A1);\n"
    " *      write [len][bytes] into b_packed_buf, byte offset into b_chunk_index.\n"
    " *\n"
    " * Geometry: mask-major dispatch (NEW vs A1's rule-major):\n"
    " *   global_size = n_words * n_masks\n"
    " *   word_idx    = gid % n_words\n"
    " *   mask_idx    = gid / n_words\n"
    " *\n"
    " * Reused primitives from gpu_common.cl: OCLParams struct only.\n"
    " *   - No md5_block / md5_buf / md5_to_hex_lc reference (kernel A pure).\n"
    " *   - No probe_compact_idx reference.\n"
    " *   - No EMIT_HIT_N reference.\n"
    " *\n"
    " * OCLParams fields consumed by A2:\n"
    " *   num_words           = batch word count\n"
    " *   num_masks           = MaskTotal = MaskPrependTotal * MaskAppendTotal\n"
    " *   n_prepend           = MaskPrependLen   (active prepend positions)\n"
    " *   n_append            = MaskAppendLen    (active append positions)\n"
    " *   base_word_idx       = source word index (for kernel B attribution)\n"
    " *   packed_size         = bytes available in b_packed_buf\n"
    " *\n"
    " * OCLParams fields NOT consumed by A2 (set by host but ignored):\n"
    " *   num_rules           (rules-axis; A2 has no rule fan-out)\n"
    " *   input_cursor_start  (B3 cursor; A2 v1 has no cursor restart -- chunking\n"
    " *                        comes 1a.2.x)\n"
    " *   rule_cursor_start   (B3 cursor)\n"
    " */\n"
    "\n"
    "/* Mask wire encoding sentinel: classid byte == 0xff means MASK_LITERAL.\n"
    " * Host upload path translates mdxfind's signed -1 to this unsigned sentinel.\n"
    " * Picked from the [0..255] uchar space's high gap (max real classid = 15\n"
    " * = MASK_CUSTOM_0+7); 0xff leaves room to grow up to 254 future classes.\n"
    " * Decision D9.2.a in the spec. */\n"
    "#define MASK_LITERAL_SENTINEL  0xffu\n"
    "\n"
    "/* Hard cap on mask positions per side. Mirrors mdxfind.c MAX_MASK_POS=16.\n"
    " * Per-thread private buffer size; kept identical so the wire format stays\n"
    " * 1:1 with the CPU pattern layout. */\n"
    "#define MAX_MASK_POS_GPU       16\n"
    "\n"
    "/* Bounds: final candidate length cap. Matches A1's RULE_BUF_LIMIT for\n"
    " * the [len] uchar byte; 255 is the hard cap regardless because the\n"
    " * length byte is uchar. With MAX_MASK_POS_GPU=16 on both sides plus an\n"
    " * input word up to RULE_BUF_LIMIT, well above 255 is structurally\n"
    " * possible -- we clamp via early-return below. */\n"
    "#define MASK_FINAL_LEN_LIMIT   255u\n"
    "\n"
    "/* Kernel-A state buffer offsets. Single source of truth for host wiring\n"
    " * to mirror via fixed-offset writes/reads. Identical to A1. */\n"
    "#define KERNELA_STATE_SLOT_COUNTER   0u\n"
    "#define KERNELA_STATE_BYTE_COUNTER   4u\n"
    "#define KERNELA_STATE_OVERFLOW_FLAG  8u\n"
    "#define KERNELA_STATE_BYTES         12u\n"
    "\n"
    "/* Charset table flat-array stride. MASK_MAX_CLASSES * 256 bytes total. */\n"
    "#define MASK_CHARSET_STRIDE          256u\n"
    "\n"
    "/* ==== Mask expander helper ============================================\n"
    " *\n"
    " * Literal port of mask_expand_into from mdxfind.c lines 7646-7660:\n"
    " *\n"
    " *   for (i = patlen - 1; i >= 0; i--) {\n"
    " *       if (pattern[i].classid == MASK_LITERAL)\n"
    " *           buf[i] = pattern[i].literal;\n"
    " *       else {\n"
    " *           buf[i] = mc->chars[index % mc->count];\n"
    " *           index /= mc->count;\n"
    " *       }\n"
    " *   }\n"
    " *\n"
    " * GPU adaptations:\n"
    " *  - pattern is a flat 2-byte-per-entry uchar buffer; classid at offset\n"
    " *    i*2, literal at offset i*2+1. MASK_LITERAL_SENTINEL (0xff) replaces\n"
    " *    the CPU's signed -1.\n"
    " *  - mask_charsets is the flat 16*256 byte table; mask_class_counts is\n"
    " *    the uint32-per-class count vector.\n"
    " *  - outbuf is thread-private (the apply path passes a stack array).\n"
    " *  - index is ulong to handle MaskTotal up to 2^31 (per spec R5 cap);\n"
    " *    the division ladder operates on running ulong values.\n"
    " *\n"
    " * Static inline (kernel A1 convention; no noinline needed since this\n"
    " * helper has no hash compression). */\n"
    "static inline void mask_expand_into_gpu(\n"
    "    ulong index,\n"
    "    __global const uchar *pattern,\n"
    "    uint patlen,\n"
    "    __global const uchar *mask_charsets,\n"
    "    __global const uint  *mask_class_counts,\n"
    "    uchar *outbuf)\n"
    "{\n"
    "    for (int i = (int)patlen - 1; i >= 0; i--) {\n"
    "        uchar cid = pattern[i * 2];\n"
    "        if (cid == MASK_LITERAL_SENTINEL) {\n"
    "            outbuf[i] = pattern[i * 2 + 1];\n"
    "        } else {\n"
    "            uint cc = mask_class_counts[(uint)cid];\n"
    "            outbuf[i] = mask_charsets[(uint)cid * MASK_CHARSET_STRIDE\n"
    "                                      + (uint)(index % (ulong)cc)];\n"
    "            index /= (ulong)cc;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ==== Total-cardinality helper =========================================\n"
    " *\n"
    " * Compute the product of class sizes for a (pattern, patlen) pair.\n"
    " * Returns 1 when patlen == 0 (matches CPU mdxfind convention; MaskTotal\n"
    " * is 1 when the corresponding side is unused). Returns 1 also for any\n"
    " * literal-only pattern (literal positions contribute factor 1).\n"
    " *\n"
    " * Kept inline since per-thread invocation cost is trivial (patlen <= 16\n"
    " * yields <= 16 global-memory reads per side per lane; values are cached\n"
    " * by the GPU L1 across the workgroup since all lanes read identical\n"
    " * pattern + counts arrays). */\n"
    "static inline ulong mask_pattern_total(\n"
    "    __global const uchar *pattern,\n"
    "    uint patlen,\n"
    "    __global const uint  *mask_class_counts)\n"
    "{\n"
    "    ulong total = 1ul;\n"
    "    for (uint i = 0; i < patlen; i++) {\n"
    "        uchar cid = pattern[i * 2];\n"
    "        if (cid != MASK_LITERAL_SENTINEL) {\n"
    "            total *= (ulong)mask_class_counts[(uint)cid];\n"
    "        }\n"
    "    }\n"
    "    return total;\n"
    "}\n"
    "\n"
    "/* ---- Kernel A2 (masks-only) production kernel --------------------\n"
    " *\n"
    " * Payload layout identical to A1 / md5_rules_phase0 (Memo B B1 coalesced):\n"
    " *\n"
    " *   offset   0 : OCLParams params\n"
    " *   offset 128 : uint hit_count            (unused by kernel A; reserved\n"
    " *                                            for payload symmetry)\n"
    " *   offset 132 : uint word_offset[num_words]\n"
    " *   offset 132 + 4*num_words : uchar packed_words[]\n"
    " *\n"
    " * params.base_word_idx is read by kernel B (host attribution); A2 does\n"
    " * not consume it directly. The host sets it before dispatch.\n"
    " *\n"
    " * params.packed_size is read as the b_packed_buf capacity. Overflow\n"
    " * detection: any candidate whose reservation would push byte_counter\n"
    " * past packed_size sets overflow_flag and returns without writing.\n"
    " *\n"
    " * Output buffer caps:\n"
    " *   b_packed_buf       capacity = params.packed_size bytes\n"
    " *   b_chunk_index      capacity = params.num_words * params.num_masks slots\n"
    " *                                  (worst case: every (word, mask) emits\n"
    " *                                   one slot -- no rejection path in A2).\n"
    " */\n"
    "\n"
    "__kernel\n"
    "void cand_masks_phase0(\n"
    "    __global uchar         *payload,\n"
    "    __global const uchar   *mask_pattern_prepend,\n"
    "    __global const uchar   *mask_pattern_append,\n"
    "    __global const uchar   *mask_charsets,\n"
    "    __global const uint    *mask_class_counts,\n"
    "    __global uchar         *b_packed_buf,\n"
    "    __global uint          *b_chunk_index,\n"
    "    __global volatile uint *b_kernelA_state\n"
    "    )\n"
    "{\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_masks = params.num_masks;\n"
    "    uint pre_len = params.n_prepend;\n"
    "    uint app_len = params.n_append;\n"
    "    uint total   = n_words * n_masks;\n"
    "\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint mask_idx = gid / n_words;\n"
    "\n"
    "    /* Compute per-side cardinalities. Cheap; both pattern arrays + the\n"
    "     * counts vector are uniform across the workgroup (cache-friendly).\n"
    "     * Values are well under 2^32 in practical use (per-side cap = 16\n"
    "     * positions * max 256 chars; full ?b?b?b?b?b = 1.1T which the spec\n"
    "     * R5 ASSERT keeps host-side). */\n"
    "    ulong append_total  = mask_pattern_total(mask_pattern_append,  app_len,\n"
    "                                             mask_class_counts);\n"
    "\n"
    "    /* mdxfind procjob convention (mdxfind.c:12111-12162):\n"
    "     *   append_idx  = idx % MaskAppendTotal\n"
    "     *   prepend_idx = idx / MaskAppendTotal\n"
    "     *\n"
    "     * Note: prepend_total is intentionally NOT computed. gid was already\n"
    "     * bounded by total = n_words * n_masks, and n_masks = MaskTotal =\n"
    "     * MaskPrependTotal * MaskAppendTotal, so any well-formed mask_idx\n"
    "     * decomposition is in-range. The host's R5-ASSERT (MaskTotal < 2^31)\n"
    "     * keeps the keyspace within ulong/uint dispatch limits. */\n"
    "    ulong append_idx  = (ulong)mask_idx % append_total;\n"
    "    ulong prepend_idx;\n"
    "    if (append_total > 0ul) {\n"
    "        prepend_idx = (ulong)mask_idx / append_total;\n"
    "    } else {\n"
    "        /* Defensive: empty append side reduces to prepend-only iteration.\n"
    "         * Host normally guarantees append_total >= 1 (mask_pattern_total\n"
    "         * returns 1 for patlen=0), but guard against pathological zero. */\n"
    "        prepend_idx = (ulong)mask_idx;\n"
    "    }\n"
    "\n"
    "    /* Per-thread private mask scratch. MAX_MASK_POS_GPU bytes each side. */\n"
    "    uchar prebuf[MAX_MASK_POS_GPU];\n"
    "    uchar appbuf[MAX_MASK_POS_GPU];\n"
    "\n"
    "    mask_expand_into_gpu(prepend_idx, mask_pattern_prepend, pre_len,\n"
    "                         mask_charsets, mask_class_counts, prebuf);\n"
    "    mask_expand_into_gpu(append_idx,  mask_pattern_append,  app_len,\n"
    "                         mask_charsets, mask_class_counts, appbuf);\n"
    "\n"
    "    /* Deterministic sub-buffer pointers from params.num_words (identical\n"
    "     * to A1). The compiler hoists since they depend only on params\n"
    "     * (uniform across the dispatch). */\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    uint wlen = (uint)words[wpos++];\n"
    "\n"
    "    /* Final candidate length: [prebuf][word][appbuf]. Clamp via early\n"
    "     * return if it would overflow the uchar [len] slot. Per-spec v1\n"
    "     * the host should size word inputs so this never triggers; defensive\n"
    "     * guard keeps us safe under future scaling. */\n"
    "    uint final_len = pre_len + wlen + app_len;\n"
    "    if (final_len > MASK_FINAL_LEN_LIMIT) return;\n"
    "\n"
    "    /* --- Reserve a candidate slot ---------------------------------\n"
    "     * Identical atomic discipline to A1: byte reservation first, then\n"
    "     * capacity guard, then slot reservation. Overflow flag latched on\n"
    "     * either overflow. */\n"
    "    uint need_bytes = 1u + final_len;   /* [len][bytes] */\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes);\n"
    "\n"
    "    if (byte_off + need_bytes > params.packed_size) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    uint slot = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u], 1u);\n"
    "\n"
    "    /* Slot-index capacity: bounded by num_words * num_masks. */\n"
    "    if (slot >= total) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    /* --- Write [len][bytes] into packed buf -----------------------\n"
    "     * Layout: [final_len][prebuf...][word...][appbuf...] */\n"
    "    b_packed_buf[byte_off] = (uchar)final_len;\n"
    "    uint p = byte_off + 1u;\n"
    "    for (uint i = 0; i < pre_len; i++) b_packed_buf[p++] = prebuf[i];\n"
    "    for (uint i = 0; i < wlen;    i++) b_packed_buf[p++] = words[wpos + i];\n"
    "    for (uint i = 0; i < app_len; i++) b_packed_buf[p++] = appbuf[i];\n"
    "\n"
    "    /* --- Write per-slot byte offset -------------------------------\n"
    "     * Per contract S7.1, no parallel mask_idx sidecar. The composed\n"
    "     * plaintext IS the candidate at b_packed_buf[byte_off]; mask\n"
    "     * attribution can be re-derived from slot_idx if a future need\n"
    "     * arises. */\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "\n"
    "    /* Per-spec invariant 1: caller (Phase 4 host) relies on in-order\n"
    "     * single-queue FIFO to ensure these writes are visible to kernel B\n"
    "     * before kernel B dispatches. No explicit fence; the queue boundary\n"
    "     * provides the cross-kernel global-memory visibility. */\n"
    "}\n"
;
