/* Auto-generated from gpu_md5iter.cl -- do not edit */
static const char gpu_md5iter_str[] =
    "/* ---- Hex conversion for MD5 iteration ---- */\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (lowercase) */\n"
    "uint hex_byte_lc(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    uint hc = hi + ((hi < 10) ? '0' : ('a' - 10));\n"
    "    uint lc = lo + ((lo < 10) ? '0' : ('a' - 10));\n"
    "    return hc | (lc << 8);\n"
    "}\n"
    "\n"
    "/* Convert one byte to 2 packed hex chars (uppercase) */\n"
    "uint hex_byte_uc(uint b) {\n"
    "    uint hi = (b >> 4) & 0xf;\n"
    "    uint lo = b & 0xf;\n"
    "    uint hc = hi + ((hi < 10) ? '0' : ('A' - 10));\n"
    "    uint lc = lo + ((lo < 10) ? '0' : ('A' - 10));\n"
    "    return hc | (lc << 8);\n"
    "}\n"
    "\n"
    "/* Convert 4 MD5 uint32s to 8 M[] words of hex text (lowercase) */\n"
    "void md5_to_hex_lc(uint hx, uint hy, uint hz, uint hw, uint *M) {\n"
    "    uint v[4]; v[0]=hx; v[1]=hy; v[2]=hz; v[3]=hw;\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint b0 = v[i] & 0xff, b1 = (v[i]>>8) & 0xff;\n"
    "        uint b2 = (v[i]>>16) & 0xff, b3 = (v[i]>>24) & 0xff;\n"
    "        M[i*2]   = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "        M[i*2+1] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Convert 4 MD5 uint32s to 8 M[] words of hex text (uppercase) */\n"
    "void md5_to_hex_uc(uint hx, uint hy, uint hz, uint hw, uint *M) {\n"
    "    uint v[4]; v[0]=hx; v[1]=hy; v[2]=hz; v[3]=hw;\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        uint b0 = v[i] & 0xff, b1 = (v[i]>>8) & 0xff;\n"
    "        uint b2 = (v[i]>>16) & 0xff, b3 = (v[i]>>24) & 0xff;\n"
    "        M[i*2]   = hex_byte_uc(b0) | (hex_byte_uc(b1) << 16);\n"
    "        M[i*2+1] = hex_byte_uc(b2) | (hex_byte_uc(b3) << 16);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Bare MD5 iteration kernel (e1 lowercase, e2 uppercase) ----\n"
    " *\n"
    " * Input: hex(MD5(password)) pre-packed by CPU into M[] words.\n"
    " * GPU iterates: MD5(hex) -> check -> hex(result) -> MD5(hex) -> ...\n"
    " * One work item per word (no salt dimension).\n"
    " * Hit stride is always 7 (includes iteration number).\n"
    " */\n"
    "__kernel void md5_iter_lc(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts_unused, __global const uint *salt_off_unused,\n"
    "    __global const ushort *salt_len_unused,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + tid * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "\n"
    "    /* MD5 padding for 32-byte input -- constant across all iterations */\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "    M[8] = 0x80;\n"
    "    M[14] = 32 * 8;\n"
    "\n"
    "    for (uint iter = 1; iter <= params.max_iter; iter++) {\n"
    "        uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = tid; hits[base+1] = 0;\n"
    "                hits[base+2] = iter + 1; /* +1: GPU iter 1 = mdxfind iter 2 */\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (iter < params.max_iter) {\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            /* M[8..15] unchanged: padding for 32-byte input */\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "__kernel void md5_iter_uc(\n"
    "    __global const uchar *hexhashes, __global const ushort *hexlens,\n"
    "    __global const uchar *salts_unused, __global const uint *salt_off_unused,\n"
    "    __global const ushort *salt_len_unused,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    if (tid >= params.num_words) return;\n"
    "\n"
    "    uint M[16];\n"
    "    __global const uint *mwords = (__global const uint *)(hexhashes + tid * 256);\n"
    "    for (int i = 0; i < 8; i++) M[i] = mwords[i];\n"
    "\n"
    "    for (int i = 8; i < 16; i++) M[i] = 0;\n"
    "    M[8] = 0x80;\n"
    "    M[14] = 32 * 8;\n"
    "\n"
    "    for (uint iter = 1; iter <= params.max_iter; iter++) {\n"
    "        uint hx = 0x67452301, hy = 0xEFCDAB89, hz = 0x98BADCFE, hw = 0x10325476;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            uint slot = atomic_add(hit_count, 1u);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * 7;\n"
    "                hits[base] = tid; hits[base+1] = 0;\n"
    "                hits[base+2] = iter + 1; /* +1: GPU iter 1 = mdxfind iter 2 */\n"
    "                hits[base+3] = hx; hits[base+4] = hy;\n"
    "                hits[base+5] = hz; hits[base+6] = hw;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (iter < params.max_iter) {\n"
    "            md5_to_hex_uc(hx, hy, hz, hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
