/* Auto-generated from gpu_blake2b512_core.cl -- do not edit */
static const char gpu_blake2b512_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_blake2b512_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_blake2b512_core.cl — BLAKE2B-512 algorithm extension functions for\n"
    " * the generic dispatch template (Memo B Phase B5 sub-batch 3).\n"
    " *\n"
    " * BLAKE2B-512 is BLAKE2b with digest_length=64 (full 512-bit output, all\n"
    " * 8 ulong of chaining state). The compression function is identical to\n"
    " * BLAKE2B-256; only the parameter-block init and output-length (=> the\n"
    " * iter hex re-encoding length and EMIT_HIT macro choice) differ.\n"
    " *\n"
    " * Geometry / byte ordering:\n"
    " *   - 128-byte block, 8 × uint64 chaining state, LITTLE-ENDIAN\n"
    " *   - 12-round G-function compression (b2b_compress in gpu_common.cl)\n"
    " *   - parameter block init: IV[0] ^ 0x01010040\n"
    " *     (digest_length=64 << 0 | key_length=0 << 8 | fanout=1 << 16 |\n"
    " *      depth=1 << 24 — high 32 bits zero)\n"
    " *   - 64-byte output = 8 ulong = 16 uint32 LE (full digest, no truncation)\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (16 for BLAKE2B-512)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (128)\n"
    " *   template_state     — h_ulong[8] internal + t[2] + f[2] + h[16] exposed\n"
    " *   template_init      — install IV ^ parameter_block (digest_length=64)\n"
    " *   template_transform — absorb one 128-byte block (NON-FINAL)\n"
    " *   template_finalize  — process complete blocks, zero tail, run final\n"
    " *                        compression with last==1; populate h[16] = all\n"
    " *                        8 ulong as 16 uint32 LE\n"
    " *   template_iterate   — re-hash digest as 128-byte hex_lc input (64-byte\n"
    " *                        binary -> 128 lc hex chars). Per BLAKE2 strict-\n"
    " *                        greater rule: 128 hex chars exactly == HASH_-\n"
    " *                        BLOCK_BYTES, so the WHOLE hex string IS the final\n"
    " *                        block (zero complete-block iterations); single\n"
    " *                        compression with last=1, counter=128.\n"
    " *   template_digest_compare — probe leading 16 bytes (h[0..3]); LE state.\n"
    " *   template_emit_hit       — EMIT_HIT_16 wrapper (16 uint32 LE = full\n"
    " *                             64-byte BLAKE2B-512 output)\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_blake2b512_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides B2B_IV[8], B2B_SIGMA[12][16], b2b_compress(),\n"
    " * EMIT_HIT_16{,_DEDUP_OR_OVERFLOW}, and probe_compact_idx.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - h_ulong[0..7] is LE per ulong; mdxfind.c blake2b_hash() at line 2446\n"
    " *     uses memcpy(out, h, outlen) directly — direct ulong byte image.\n"
    " *   - Decomposition to st->h[0..15] uint32 LE pairs follows the same\n"
    " *     pattern as BLAKE2B-256 but spans all 8 ulong → 16 uint32:\n"
    " *       st->h[2i]   = (uint)h_ulong[i]\n"
    " *       st->h[2i+1] = (uint)(h_ulong[i] >> 32)    for i = 0..7\n"
    " *   - Wire format matches gpu_sha512_packed.cl convention exactly: 16 LE\n"
    " *     uint32 words (state ulong split into low/high uint32 halves). The\n"
    " *     hit-replay path in gpujob_opencl.c reads the same 64-byte binary\n"
    " *     digest regardless of which 16-uint32 algorithm produced it.\n"
    " *\n"
    " * R1 mitigation: single-private-buffer pattern. R2 (register pressure):\n"
    " * BLAKE2b uses 8 ulong state + 16 ulong v[] + 16 ulong m[] = ~80 ulong-\n"
    " * equivalent. Compared to SHA512's W[80] schedule (640 bytes private\n"
    " * scratch), BLAKE2b's 16 m[] + 16 v[] is 256 bytes — substantially less.\n"
    " * Expected priv_mem_size on gfx1201 may be LOWER than SHA-512's\n"
    " * 42,520 B baseline. Per-phase clGetKernelWorkGroupInfo probe.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key (R3 fix): defines_str\n"
    " * \"HASH_WORDS=16,HASH_BLOCK_BYTES=128\" — same width/block as SHA-512 but\n"
    " * distinct source text (b2b_compress vs sha512_block; different state\n"
    " * struct), so cache key is unique per gpu_kernel_cache.c rev 1.5+. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 16\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 128\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    ulong h_ulong[8];     /* internal chaining state, LE per ulong */\n"
    "    ulong t[2];           /* 128-bit byte counter */\n"
    "    ulong f[2];           /* finalization flag pair */\n"
    "    uint  h[HASH_WORDS];  /* exposed digest words, 16 uint32 LE */\n"
    "} template_state;\n"
    "\n"
    "/* Decompose all 8 ulong of internal state into 16 LE uint32 for the\n"
    " * exposed h[]. Same convention as gpu_sha512_core.cl template_state_to_h\n"
    " * but WITHOUT bswap64 — BLAKE2b state is naturally LE per ulong (the\n"
    " * memcpy(out, h, outlen) byte image gives the canonical hash output). */\n"
    "static inline void template_state_to_h_b512(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong v = st->h_ulong[i];\n"
    "        st->h[i * 2]     = (uint)v;\n"
    "        st->h[i * 2 + 1] = (uint)(v >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_init: install BLAKE2B-512 IV XOR'd with parameter block.\n"
    " * Param block low ulong = 0x01010040 (digest_length=64). Matches mdxfind.c\n"
    " * blake2b_hash (line 2431) `0x01010000 ^ outlen` exactly when outlen=64\n"
    " * (0x01010000 ^ 0x40 = 0x01010040). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) st->h_ulong[i] = B2B_IV[i];\n"
    "    st->h_ulong[0] ^= 0x01010040UL;   /* digest_length=64, key=0, fanout=1, depth=1 */\n"
    "    st->t[0] = 0UL; st->t[1] = 0UL;\n"
    "    st->f[0] = 0UL; st->f[1] = 0UL;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one full 128-byte block as NON-FINAL. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    ulong t0 = st->t[0] + (ulong)HASH_BLOCK_BYTES;\n"
    "    ulong carry = (t0 < st->t[0]) ? 1UL : 0UL;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "    b2b_compress(&st->h_ulong[0], block, st->t[0], st->t[1], 0);\n"
    "}\n"
    "\n"
    "/* template_finalize: process all input start-to-end, advance counter,\n"
    " * zero-pad final block, run final compression with last=1.\n"
    " *\n"
    " * Same shape as gpu_blake2b256_core.cl but populates the FULL 16-uint32\n"
    " * exposed digest via template_state_to_h_b512 (8 ulong → 16 uint32 LE).\n"
    " * Matches mdxfind.c JOB_BLAKE2B512 (line 30722-30730) and the host\n"
    " * blake2b_hash(out, 64, ...) byte image. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    int pos = 0;\n"
    "    while ((len - pos) > HASH_BLOCK_BYTES) {\n"
    "        ulong t0 = st->t[0] + (ulong)HASH_BLOCK_BYTES;\n"
    "        ulong carry = (t0 < st->t[0]) ? 1UL : 0UL;\n"
    "        st->t[0] = t0;\n"
    "        st->t[1] += carry;\n"
    "        b2b_compress(&st->h_ulong[0], data + pos, st->t[0], st->t[1], 0);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    for (int i = 0; i < rem; i++) buf[i] = data[pos + i];\n"
    "    for (int i = rem; i < HASH_BLOCK_BYTES; i++) buf[i] = 0;\n"
    "\n"
    "    ulong t0 = st->t[0] + (ulong)rem;\n"
    "    ulong carry = (t0 < st->t[0]) ? 1UL : 0UL;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "\n"
    "    st->f[0] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    b2b_compress(&st->h_ulong[0], buf, st->t[0], st->t[1], 1);\n"
    "\n"
    "    template_state_to_h_b512(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: re-hash 64-byte digest as 128-byte hex_lc and BLAKE2B-512\n"
    " * the hex string. Mirrors mdxfind.c JOB_BLAKE2B512 (line 30722-30729):\n"
    " * blake2b_hash(curin.h, 64, ...); len = 128; prmd5(curin.h, mdbuf, 128)\n"
    " * writes 128 lowercase hex chars; next iter blake2b's those 128 bytes.\n"
    " *\n"
    " * 128 hex chars exactly equals HASH_BLOCK_BYTES (128). Per the strict-\n"
    " * greater \"while ((len - pos) > HASH_BLOCK_BYTES)\" rule in finalize, the\n"
    " * 128-byte hex string is the FINAL block directly — single compression\n"
    " * with last=1, counter=128, no preceding complete-block iterations. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint snap[HASH_WORDS];\n"
    "    for (int i = 0; i < HASH_WORDS; i++) snap[i] = st->h[i];\n"
    "\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    /* Hex-encode 16 LE uint32 -> 128 lowercase hex chars. */\n"
    "    for (int i = 0; i < 16; i++) {\n"
    "        uint s = snap[i];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uchar by = (uchar)((s >> (b * 8)) & 0xFFu);\n"
    "            uchar hi = by >> 4, lo = by & 0xFu;\n"
    "            buf[i * 8 + b * 2 + 0] = (hi < 10) ? (uchar)('0' + hi) : (uchar)('a' + (hi - 10));\n"
    "            buf[i * 8 + b * 2 + 1] = (lo < 10) ? (uchar)('0' + lo) : (uchar)('a' + (lo - 10));\n"
    "        }\n"
    "    }\n"
    "    /* No zero-padding needed: 128 hex chars exactly fill the 128-byte block. */\n"
    "\n"
    "    /* Reset state for the new compression. */\n"
    "    for (int i = 0; i < 8; i++) st->h_ulong[i] = B2B_IV[i];\n"
    "    st->h_ulong[0] ^= 0x01010040UL;\n"
    "    st->t[0] = 128UL; st->t[1] = 0UL;\n"
    "    st->f[0] = 0xFFFFFFFFFFFFFFFFUL; st->f[1] = 0UL;\n"
    "\n"
    "    b2b_compress(&st->h_ulong[0], buf, 128UL, 0UL, 1);\n"
    "\n"
    "    template_state_to_h_b512(st);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe leading 16 bytes (h[0..3]). LE state\n"
    " * convention; no bswap32. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: EMIT_HIT_16 wrapper (BLAKE2B-512 = 16 uint32 LE). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_16((hits), (hit_count), (max_hits), \\\n"
    "                (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_16_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
