/* Auto-generated from gpu_md5_rules.cl -- do not edit */
static const char gpu_md5_rules_str[] =
    "/*\n"
    " * $Revision: 1.30 $\n"
    " * $Log: gpu_md5_rules.cl,v $\n"
    " * Revision 1.30  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_md5_rules.cl — Phase 0+ GPU rule expansion + multi-block MD5 kernel\n"
    " *\n"
    " * UNIFIED WALKER (rev 1.17+):\n"
    " *   Single-buffer in-place per-op semantics. apply_rule(prog, buf, len)\n"
    " *   replaces the previous apply_rule_op() function-call walker + ping-pong\n"
    " *   buffer model. All three kernels (md5_rules_phase0,\n"
    " *   md5_rules_phase0_test, md5_rules_phase0_validate) share the SAME walker.\n"
    " *\n"
    " *   Bytecode contract:\n"
    " *     - Opcodes are high-bit (0xc1..0xfd contiguous + 0xfe/0xff variable).\n"
    " *     - Mapping is fixed by ruleproc.c rev 1.25+ packrules() emit-sites.\n"
    " *     - applyrule() in ruleproc.c is the byte-exact CPU reference.\n"
    " *\n"
    " *   Buffer model:\n"
    " *     - Single private uchar buf[512] (NOT 64, NOT 128, NOT 256).\n"
    " *     - Length stored in private int len.\n"
    " *     - In-place modification: ops mutate buf in place.\n"
    " *     - Length grows past current `len` for append/insert/prepend ops\n"
    " *       (write into uninitialized tail; bound check `len + N <= 127`).\n"
    " *     - Length shrinks for `]`, `D`, `[`, `'`, `O`, `x`, `@` (decrement\n"
    " *       len, optionally compact).\n"
    " *\n"
    " *   Dispatch:\n"
    " *     - switch (op) on contiguous 0xc1..0xfd values + 0xff/0xfe special.\n"
    " *     - 0xff (multi-$) and 0xfe (multi-^) handled OUTSIDE the main switch\n"
    " *       (variable-length argument bytes).\n"
    " *\n"
    " *   Geometry (rule-major):\n"
    " *     global_size = n_words * n_rules\n"
    " *     gid -> (word_idx, rule_idx) by rule-major decomposition:\n"
    " *       word_idx = gid % n_words\n"
    " *       rule_idx = gid / n_words\n"
    " *     => consecutive lanes within a warp share rule_idx, varying word_idx.\n"
    " *\n"
    " *   Per work-item:\n"
    " *     1. Stage input word into buf[0..wlen-1].\n"
    " *     2. apply_rule(rule_program + rpos, buf, wlen) -> new_len.\n"
    " *     3. (production) skip MD5+probe if buf == input (no-op detection).\n"
    " *     4. (production) Multi-block MD5 of buf[0..new_len). probe_compact;\n"
    " *        emit hit if found.\n"
    " *     (test kernel) emit MD5 digest per (word, rule).\n"
    " *     (validate kernel) emit fixed-size record [retlen][outlen][bytes].\n"
    " *\n"
    " * Primitives reused from gpu_common.cl: md5_block, md5_to_hex_lc,\n"
    " * probe_compact_idx, EMIT_HIT_4, OCLParams.\n"
    " */\n"
    "\n"
    "/* ==== Opcode definitions (must match ruleproc.c RULE_OP_* exactly) ==== */\n"
    "#define RULE_OP_INSERT      0xfd\n"
    "#define RULE_OP_OVERWRITE   0xfc\n"
    "#define RULE_OP_TOGGLE_AT   0xfb\n"
    "#define RULE_OP_INC         0xfa\n"
    "#define RULE_OP_DEC         0xf9\n"
    "#define RULE_OP_TRUNC       0xf8\n"
    "#define RULE_OP_DROP_LAST   0xf7\n"
    "#define RULE_OP_SUB         0xf6\n"
    "#define RULE_OP_LOWER       0xf5\n"
    "#define RULE_OP_UPPER       0xf4\n"
    "#define RULE_OP_CAP         0xf3\n"
    "#define RULE_OP_CAP_INV     0xf2\n"
    "#define RULE_OP_REVERSE     0xf1\n"
    "#define RULE_OP_TOGGLE      0xf0\n"
    "#define RULE_OP_TITLE_SP    0xef\n"
    "#define RULE_OP_TITLE_SEP   0xee\n"
    "#define RULE_OP_DUP         0xed\n"
    "#define RULE_OP_REFLECT     0xec\n"
    "#define RULE_OP_DUP_EACH    0xeb\n"
    "#define RULE_OP_ROT_L       0xea\n"
    "#define RULE_OP_ROT_R       0xe9\n"
    "#define RULE_OP_SWAP_FRONT  0xe8\n"
    "#define RULE_OP_SWAP_BACK   0xe7\n"
    "#define RULE_OP_DROP_FIRST  0xe6\n"
    "#define RULE_OP_APPEND      0xe5\n"
    "#define RULE_OP_PREPEND     0xe4\n"
    "#define RULE_OP_DEL_AT      0xe3\n"
    "#define RULE_OP_BIT_SHL     0xe2\n"
    "#define RULE_OP_BIT_SHR     0xe1\n"
    "#define RULE_OP_REPL_NEXT   0xe0\n"
    "#define RULE_OP_REPL_PREV   0xdf\n"
    "#define RULE_OP_PURGE       0xde\n"
    "#define RULE_OP_DUP_LAST    0xdd\n"
    "#define RULE_OP_DUP_FIRST   0xdc\n"
    "#define RULE_OP_REPEAT      0xdb\n"
    "#define RULE_OP_DUP_PREFIX  0xda\n"
    "#define RULE_OP_DUP_SUFFIX  0xd9\n"
    "#define RULE_OP_SWAP_AT     0xd8\n"
    "#define RULE_OP_EXTRACT     0xd7\n"
    "#define RULE_OP_OMIT        0xd6\n"
    "#define RULE_OP_TOGGLE_SEP  0xd5\n"
    "#define RULE_OP_NOOP        0xd4\n"
    "#define RULE_OP_NOOP_SP     0xd3\n"
    "#define RULE_OP_NOOP_TAB    0xd2\n"
    "#define RULE_OP_MEM_STORE   0xd1\n"
    "#define RULE_OP_MEM_APP     0xd0\n"
    "#define RULE_OP_MEM_PRE     0xcf\n"
    "#define RULE_OP_MEM_REJ     0xce\n"
    "#define RULE_OP_MEM_INSERT  0xcd\n"
    "#define RULE_OP_REJ_LEN_NE  0xcc\n"
    "#define RULE_OP_REJ_LEN_GE  0xcb\n"
    "#define RULE_OP_REJ_LEN_LE  0xca\n"
    "#define RULE_OP_REJ_HAS     0xc9\n"
    "#define RULE_OP_REJ_NHAS    0xc8\n"
    "#define RULE_OP_REJ_FIRST   0xc7\n"
    "#define RULE_OP_REJ_LAST    0xc6\n"
    "#define RULE_OP_S_SPECIAL   0xc5\n"
    "#define RULE_OP_HASH_EXIT   0xc4\n"
    "#define RULE_OP_HEX_UPPER   0xc3\n"
    "#define RULE_OP_HEX_LOWER   0xc2\n"
    "#define RULE_OP_DIV_INSERT  0xc1\n"
    "\n"
    "#define RULE_BUF_MAX   40960                      /* was 512 — bumped 2026-05-02 to match\n"
    "                                                   * CPU's MAXLINE=40*1024 in mdxfind.h:63.\n"
    "                                                   * Tracks ruleproc.c's MAXLINE clamp so any\n"
    "                                                   * CPU-producible rule output fits in the\n"
    "                                                   * GPU walker without divergent clamping. */\n"
    "#define RULE_BUF_LIMIT (RULE_BUF_MAX - 1)         /* now 40959 */\n"
    "\n"
    "/* ==== Branchless case-flip helper ====================================\n"
    " *\n"
    " * case_flip_mask(c) returns 0x20 if `c` is alphabetic (A-Z or a-z),\n"
    " * else 0. Uses the unsigned-subtract trick: `(c | 0x20) - 'a' < 26u`.\n"
    " * The OR lifts uppercase into lowercase territory (or leaves lowercase\n"
    " * unchanged); the unsigned compare is true only for 'a'..'z'.\n"
    " *\n"
    " * Robust across the entire 0x00..0xff input space (verified against\n"
    " * predicate-landmine sweep in mdx-team-state #72): no false positives\n"
    " * on '@' (0x40), '[' (0x5b), '`' (0x60), '{' (0x7b), DEL (0x7f), or\n"
    " * any control / high-bit byte.\n"
    " *\n"
    " * Compiles to predicated mov on jump-table backends:\n"
    " *   NVIDIA  -> selp.b32\n"
    " *   AMD     -> v_cndmask_b32\n"
    " *   ARM/Mali-> CSEL\n"
    " * All single-cycle.\n"
    " *\n"
    " * NOTE: OpenCL select(a,b,c) on scalar uchar uses MSB-of-c as the\n"
    " * boolean predicate (NOT C-style nonzero). The unsigned compare here\n"
    " * yields 0 or 1 (MSB always 0), so select() would always pick `a`.\n"
    " * Use the explicit ternary form instead — the compiler emits the\n"
    " * correct predicated move on every backend.\n"
    " */\n"
    "static inline uchar case_flip_mask(uchar c) {\n"
    "    /* Promote to uchar for the unsigned 8-bit subtract: OpenCL promotes\n"
    "     * uchar to int in expressions, so a naive `(c|0x20) - 'a'` becomes\n"
    "     * signed and `-49 < 26u` is TRUE, misclassifying digits. Cast the\n"
    "     * subtraction result back to uchar so the unsigned wrap kicks in,\n"
    "     * then compare to 26. */\n"
    "    uchar v = (uchar)((c | (uchar)0x20) - (uchar)'a');\n"
    "    return (uchar)((v < (uchar)26) ? 0x20 : 0);\n"
    "}\n"
    "\n"
    "/* ==== Unified single-buffer in-place rule walker =====================\n"
    " *\n"
    " * apply_rule:\n"
    " *   - prog: __global pointer to NUL-terminated bytecode (offset already\n"
    " *           applied by caller; first byte is the first opcode).\n"
    " *   - buf:  private uchar[RULE_BUF_MAX] register array, pre-staged with\n"
    " *           the input word in buf[0..len-1].\n"
    " *   - len:  initial length of the staged input.\n"
    " * Returns: post-rule length (>= 0) on success, -1 if a rejection op fires.\n"
    " *          The buffer is modified in place.\n"
    " *\n"
    " * Rejection semantics (rev 1.22): rejection ops `_ < > ! / ( )` mirror\n"
    " * applyrule's `_retval = -1` early-exit. When fired, apply_rule returns\n"
    " * -1 and callers must skip MD5+probe (production), emit zero digests\n"
    " * (test kernels), or emit `retlen=-1, outlen=0, no bytes` (validate).\n"
    " *\n"
    " * Note for the `_` op: it tests length-not-equal against the ORIGINAL\n"
    " * input length (the `len` parameter at function entry), NOT the running\n"
    " * clen. We capture orig_len at entry to match applyrule byte-exact.\n"
    " */\n"
    "static int apply_rule(__global const uchar *prog, uchar *buf, int len)\n"
    "{\n"
    "    int k = 0;\n"
    "    int orig_len = len;     /* preserved for the `_ N` length-equal test */\n"
    "\n"
    "    for (int n = 0; n < 256; n++) {\n"
    "        uchar op = prog[k];\n"
    "        if (op == 0) break;\n"
    "\n"
    "        /* Main switch — contiguous high-bit opcodes 0xc1..0xff.\n"
    "         * 0xff/0xfe are variable-length (op + N + N data bytes); the rest\n"
    "         * are fixed-size. Folded into the switch so the compiler can emit a\n"
    "         * single jump table over the contiguous range, saving ~0.4 cyc/iter\n"
    "         * on average across HashMob.100k frequency mix vs the prior hoist\n"
    "         * (which added 2 compares/branch on every fixed-size opcode).\n"
    "         * Listed by frequency rank then by opcode value for readability. */\n"
    "        switch (op) {\n"
    "\n"
    "            /* ---- Variable-length affix ops (0xff / 0xfe) ---- */\n"
    "            case 0xff: {\n"
    "                /* Multi-char append: 2 + N bytes, N data bytes follow N-byte.\n"
    "                 * Wave F: cap-once-then-copy. Compute the actual usable\n"
    "                 * count once instead of branching on every byte. */\n"
    "                int N = (int)prog[k + 1];\n"
    "                int n_copy = N;\n"
    "                if (len + n_copy > RULE_BUF_LIMIT) n_copy = RULE_BUF_LIMIT - len;\n"
    "                if (n_copy < 0) n_copy = 0;\n"
    "                for (int j = 0; j < n_copy; j++) {\n"
    "                    buf[len + j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += n_copy;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "            case 0xfe: {\n"
    "                /* Multi-char prepend: shift right by N, then write N data\n"
    "                 * bytes at buf[0..N-1]. */\n"
    "                int N = (int)prog[k + 1];\n"
    "                int new_pre = N;\n"
    "                if (len + new_pre > RULE_BUF_LIMIT) new_pre = RULE_BUF_LIMIT - len;\n"
    "                if (new_pre < 0) new_pre = 0;\n"
    "                /* Shift right (work backward to avoid overwrite). */\n"
    "                for (int j = len - 1; j >= 0; j--) {\n"
    "                    int dst = j + new_pre;\n"
    "                    if (dst <= RULE_BUF_LIMIT) buf[dst] = buf[j];\n"
    "                }\n"
    "                for (int j = 0; j < new_pre; j++) {\n"
    "                    buf[j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += new_pre;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Top-frequency: insert / overwrite / toggle ---- */\n"
    "            case RULE_OP_INSERT: {\n"
    "                /* iNX: insert byte arg2 at position arg1-1.\n"
    "                 * applyrule semantics: only fires when (clen > pos). */\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                if (pos >= 0 && pos < len && len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > pos; j--) buf[j] = buf[j - 1];\n"
    "                    buf[pos] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OVERWRITE: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                if (pos >= 0 && pos < len) buf[pos] = ch;\n"
    "                if (pos == 0 && len == 0) { buf[0] = ch; len++; }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_AT: {\n"
    "                /* Branchless: case_flip_mask returns 0 for non-alphabetic\n"
    "                 * bytes, so XOR with 0 is identity — the inner alphabetic\n"
    "                 * test collapses into the helper. Bounds check on `pos`\n"
    "                 * stays — required to match applyrule semantics. */\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    buf[pos] ^= case_flip_mask(buf[pos]);\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position arithmetic (Wave E branchless) ----\n"
    "             *\n"
    "             * Pattern: clamp `pos` into a safe slot, mask the increment\n"
    "             * by the validity flag, unconditionally write. When `valid`\n"
    "             * is 0 we write `buf[0] + 0` — a no-op idempotent self-write.\n"
    "             * On NVIDIA / AMD this compiles to one selp/v_cndmask + one\n"
    "             * predicated add, eliminating the divergent branch. */\n"
    "            case RULE_OP_INC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] + (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DEC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] - (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Length-shrink (Wave E) ----\n"
    "             * NOTE: the original `if (pos < len) len = pos;` matches\n"
    "             * applyrule. Branchless version preserved as a ternary —\n"
    "             * equivalent code shape, no behavioral change. */\n"
    "            case RULE_OP_TRUNC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                len = (pos < len) ? pos : len;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DROP_LAST: {\n"
    "                len -= (len > 0);\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Substitute ---- */\n"
    "            case RULE_OP_SUB: {\n"
    "                /* Wave D SIMD: vector compare against c1, blend c2 into\n"
    "                 * matched lanes, vstore. Length-preserving — past-len\n"
    "                 * writes invisible per detector + md5_buf semantics. */\n"
    "                uchar c1 = prog[k + 1], c2 = prog[k + 2];\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                uchar16 v_c1 = (uchar16)c1;\n"
    "                uchar16 v_c2 = (uchar16)c2;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 eq = (v == v_c1);\n"
    "                    /* Blend: where eq is true (-1 = 0xFF), pick v_c2,\n"
    "                     * else v. (v ^ ((v ^ v_c2) & eq_mask)). */\n"
    "                    uchar16 eq_mask = as_uchar16(eq);\n"
    "                    uchar16 result = v ^ ((v ^ v_c2) & eq_mask);\n"
    "                    vstore16(result, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    if (buf[j] == c1) buf[j] = c2;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-string case ops ---- *\n"
    "             *\n"
    "             * SIMD strategy (Wave C, mdx-team-state #75):\n"
    "             *   Vector vload16/vstore16 over `(len & ~15)` bytes plus a\n"
    "             *   scalar tail for `len & 15` bytes. Bytes past `len` are\n"
    "             *   read+written but ignored downstream — the no-op detector\n"
    "             *   at line 813-819 reads buf[0..wlen-1] only, and md5_buf\n"
    "             *   reads buf[0..len-1] only. Length-preserving ops do not\n"
    "             *   change `len`, so writes past `len` are invisible.\n"
    "             *\n"
    "             *   Predicate: same shape as case_flip_mask but vectorized.\n"
    "             *     v_or = v | 0x20             (lift A-Z into a-z range)\n"
    "             *     v_d  = (uchar)(v_or - 'a')  (0..25 for letters)\n"
    "             *     m    = (v_d < 26) ? 0x20 : 0   per-lane\n"
    "             *   For `l`: only flip when v originally was upper-case.\n"
    "             *     m_l = m & ~(v & 0x20)   (mask&0x20 already 0 for upper,\n"
    "             *                              so equivalent to `m if v>='A'&&v<='Z'`)\n"
    "             *     simpler: `mask = ((v >= 'A') & (v <= 'Z')) & 0x20`.\n"
    "             */\n"
    "            case RULE_OP_LOWER: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_upper = (v >= (uchar16)'A') & (v <= (uchar16)'Z');\n"
    "                    uchar16 mask = as_uchar16(is_upper) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_UPPER: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_lower = (v >= (uchar16)'a') & (v <= (uchar16)'z');\n"
    "                    uchar16 mask = as_uchar16(is_lower) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP: {\n"
    "                /* Capitalize: lowercase all (vector), then upper-case\n"
    "                 * the first lowercase letter (scalar pass — variable\n"
    "                 * exit, intrinsically scalar). Matches ruleproc.c SSE. */\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_upper = (v >= (uchar16)'A') & (v <= (uchar16)'Z');\n"
    "                    uchar16 mask = as_uchar16(is_upper) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                /* Pass 2: scalar find-first-lower. */\n"
    "                for (int q = 0; q < len; q++) {\n"
    "                    uchar c = buf[q];\n"
    "                    if (c >= 'a' && c <= 'z') {\n"
    "                        buf[q] = c ^ (uchar)0x20;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP_INV: {\n"
    "                /* Anti-capitalize: uppercase all (vector), then lower-case\n"
    "                 * the first uppercase letter (scalar pass). */\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_lower = (v >= (uchar16)'a') & (v <= (uchar16)'z');\n"
    "                    uchar16 mask = as_uchar16(is_lower) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                /* Pass 2: scalar find-first-upper. */\n"
    "                for (int q = 0; q < len; q++) {\n"
    "                    uchar c = buf[q];\n"
    "                    if (c >= 'A' && c <= 'Z') {\n"
    "                        buf[q] = c ^ (uchar)0x20;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REVERSE: {\n"
    "                int i = 0, j = len - 1;\n"
    "                while (i < j) {\n"
    "                    uchar t = buf[i];\n"
    "                    buf[i] = buf[j];\n"
    "                    buf[j] = t;\n"
    "                    i++;\n"
    "                    j--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    /* Vectorized case_flip_mask: alphabetic detection\n"
    "                     * via unsigned 8-bit subtract + compare. */\n"
    "                    uchar16 v_or = v | (uchar16)0x20;\n"
    "                    uchar16 v_d  = v_or - (uchar16)'a';\n"
    "                    char16 is_alpha = (v_d < (uchar16)26);\n"
    "                    uchar16 mask = as_uchar16(is_alpha) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                        buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Title-case ---- */\n"
    "            case RULE_OP_TITLE_SP: {\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == ' ') { z = 0; }\n"
    "                    else if (z == 0 && c >= 'a' && c <= 'z') { z = 1; buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else if (c >= 'A' && c <= 'Z') { buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_SEP: {\n"
    "                uchar delim = prog[k + 1];\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == delim) { z = 0; }\n"
    "                    else if (z == 0 && c >= 'a' && c <= 'z') { z = 1; buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else if (c >= 'A' && c <= 'Z') { buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-buffer length-grow ops ---- */\n"
    "            case RULE_OP_DUP: {\n"
    "                /* Wave F: vector copy buf[0..tlen-1] -> buf[len..len+tlen-1].\n"
    "                 * Source/dest don't overlap (offset == tlen). Scalar tail\n"
    "                 * keeps writes within tlen — must NOT overshoot into the\n"
    "                 * uninitialized region past 2*tlen since this is a length-\n"
    "                 * grow op (output buf[0..2*tlen-1] is read downstream). */\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    int j = 0;\n"
    "                    int vbound = tlen & ~15;\n"
    "                    for (; j < vbound; j += 16) {\n"
    "                        uchar16 v = vload16(0, buf + j);\n"
    "                        vstore16(v, 0, buf + len + j);\n"
    "                    }\n"
    "                    for (; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REFLECT: {\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = 0; j < tlen; j++)\n"
    "                        buf[len + tlen - 1 - j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_EACH: {\n"
    "                /* \"abc\" -> \"aabbcc\"; length doubles. Work from the end so\n"
    "                 * we don't overwrite source bytes still being read. */\n"
    "                int tlen = len;\n"
    "                if (tlen * 2 <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = tlen - 1; j >= 0; j--) {\n"
    "                        uchar c = buf[j];\n"
    "                        buf[j * 2]     = c;\n"
    "                        buf[j * 2 + 1] = c;\n"
    "                    }\n"
    "                    len = tlen * 2;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Rotation / swap ---- */\n"
    "            case RULE_OP_ROT_L: {\n"
    "                /* Rotate left by 1: \"abcd\"->\"bcda\".\n"
    "                 * applyrule: while (*rule == '{' && y < clen) coalesces\n"
    "                 * consecutive {{; the new bytecode emits each as a separate\n"
    "                 * RULE_OP_ROT_L so we step once per opcode. Functionally\n"
    "                 * equivalent (chained single-step rotation == multi-step). */\n"
    "                if (len > 0) {\n"
    "                    uchar first = buf[0];\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    buf[len - 1] = first;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_ROT_R: {\n"
    "                if (len > 0) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = last;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_FRONT: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[0]; buf[0] = buf[1]; buf[1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_BACK: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[len - 2];\n"
    "                    buf[len - 2] = buf[len - 1];\n"
    "                    buf[len - 1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Drop first / append / prepend ---- */\n"
    "            case RULE_OP_DROP_FIRST: {\n"
    "                if (len > 0) {\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_APPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) buf[len++] = ch;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_PREPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            case RULE_OP_DEL_AT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    for (int j = pos; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position bit shifts / nearest-neighbor copy ---- */\n"
    "            case RULE_OP_BIT_SHL: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] << 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_BIT_SHR: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] >> 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_NEXT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    buf[pos] = (pos + 1 < len) ? buf[pos + 1] : (uchar)0;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_PREV: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos > 0 && pos < len) buf[pos] = buf[pos - 1];\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Purge ---- */\n"
    "            case RULE_OP_PURGE: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                int w = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] != ch) buf[w++] = buf[j];\n"
    "                }\n"
    "                len = w;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Last/first-char duplicators ---- */\n"
    "            case RULE_OP_DUP_LAST: {\n"
    "                /* Wave F: broadcast vstore for the fill loop. */\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    int j = 0;\n"
    "                    int vbound = n2 & ~15;\n"
    "                    uchar16 v_last = (uchar16)last;\n"
    "                    for (; j < vbound; j += 16) {\n"
    "                        vstore16(v_last, 0, buf + len + j);\n"
    "                    }\n"
    "                    for (; j < n2; j++) buf[len + j] = last;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_FIRST: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar first = buf[0];\n"
    "                    /* Shift right by n2. */\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j + n2] = buf[j];\n"
    "                    /* applyrule's loop is `for (x = clen - 1; x > 0; x--)\n"
    "                     *    cpass[x + y] = cpass[x];` then `for (x = 1; x <= y; x++)\n"
    "                     *    cpass[x] = cpass[0];` — buf[0] is preserved (it is\n"
    "                     * the source we copy from), buf[1..n2] are filled with\n"
    "                     * first. So buf[0] keeps its original value. */\n"
    "                    for (int j = 1; j <= n2; j++) buf[j] = first;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPEAT: {\n"
    "                /* p N: append N copies of the input to itself (input\n"
    "                 * total = (N+1)*len; applyrule reads \"y = *rule++ - 1;\"\n"
    "                 * then loops y times. In our bytecode the arg is also\n"
    "                 * positiontranslate-encoded so n2 = arg-1, and the loop\n"
    "                 * runs n2 times. */\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                int tlen = len;\n"
    "                if (tlen > 0 && n2 > 0) {\n"
    "                    for (int copy = 0; copy < n2; copy++) {\n"
    "                        if (len + tlen > RULE_BUF_LIMIT) break;\n"
    "                        for (int j = 0; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                        len += tlen;\n"
    "                    }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_PREFIX: {\n"
    "                /* y N: duplicate first N chars at the start.\n"
    "                 * applyrule: memmove(cpass + n, cpass, clen); for (x = 0;\n"
    "                 * x < n; x++) cpass[x] = cpass[x + n] is implicit in the\n"
    "                 * pre-move state (the leading n bytes equal the original\n"
    "                 * leading n bytes after the right-shift). Actually applyrule\n"
    "                 * uses memmove only; the prepended bytes are buf[0..n-1]\n"
    "                 * which are now the first n bytes of the original input. */\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    /* memmove(cpass + n, cpass, clen) — shift right by n. */\n"
    "                    for (int j = len - 1; j >= 0; j--) buf[j + n2] = buf[j];\n"
    "                    /* The first n bytes of the buffer are now whatever was\n"
    "                     * shifted out — we want them to be the original first n\n"
    "                     * bytes. After the shift, buf[n..n+n-1] equals the\n"
    "                     * original buf[0..n-1]; we just need to copy those down. */\n"
    "                    for (int j = 0; j < n2; j++) buf[j] = buf[j + n2];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_SUFFIX: {\n"
    "                /* Y N: duplicate last N chars at the end. */\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    /* memmove(cpass + clen, cpass + (clen - n), n) */\n"
    "                    for (int j = 0; j < n2; j++) buf[len + j] = buf[len - n2 + j];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Position-paired ops ---- */\n"
    "            case RULE_OP_SWAP_AT: {\n"
    "                int posA = (int)prog[k + 1] - 1;\n"
    "                int posB = (int)prog[k + 2] - 1;\n"
    "                if (posA >= 0 && posA < len && posB >= 0 && posB < len) {\n"
    "                    uchar t = buf[posA]; buf[posA] = buf[posB]; buf[posB] = t;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_EXTRACT: {\n"
    "                /* xAB: out = in[A..A+B-1] capped at len-A.\n"
    "                 * applyrule: for (x = 0; x < z && ((y + x) < clen); x++)\n"
    "                 *   cpass[x] = cpass[y + x]; clen = x; */\n"
    "                int start = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (start > 0 && start < len && count > 0) {\n"
    "                    int actual = 0;\n"
    "                    while (actual < count && (start + actual) < len) {\n"
    "                        buf[actual] = buf[start + actual];\n"
    "                        actual++;\n"
    "                    }\n"
    "                    len = actual;\n"
    "                } else if (start == 0 && start < len && count > 0) {\n"
    "                    /* start=0 case: src and dst overlap at index 0; the\n"
    "                     * applyrule shape `cpass[x] = cpass[y + x]` with y=0\n"
    "                     * is buf[x]=buf[x] — no change beyond the truncation. */\n"
    "                    int actual = 0;\n"
    "                    while (actual < count && actual < len) {\n"
    "                        actual++;\n"
    "                    }\n"
    "                    len = actual;\n"
    "                } else if (start >= len || start < 0) {\n"
    "                    /* applyrule: if (clen > y) - false branch, no change. */\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OMIT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (pos >= 0 && pos < len && count > 0 && pos + count <= len) {\n"
    "                    /* applyrule: for (x = y; x < clen && (x + z) < clen; x++)\n"
    "                     *   cpass[x] = cpass[x + z]; clen = x;\n"
    "                     * The loop terminates when x + z == clen, so x = clen - z,\n"
    "                     * matching len - count. */\n"
    "                    for (int j = pos; j + count < len; j++) buf[j] = buf[j + count];\n"
    "                    len -= count;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_SEP: {\n"
    "                int upos = (int)prog[k + 1] - 1;\n"
    "                uchar sep = prog[k + 2];\n"
    "                int toggle_next = 0;\n"
    "                int occurrence = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == sep) {\n"
    "                        if (occurrence == upos) toggle_next = 1;\n"
    "                        else occurrence++;\n"
    "                        continue;\n"
    "                    }\n"
    "                    if (toggle_next) {\n"
    "                        if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                            buf[j] = c ^ case_flip_mask(c);\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- No-ops ---- */\n"
    "            case RULE_OP_NOOP:\n"
    "            case RULE_OP_NOOP_SP:\n"
    "            case RULE_OP_NOOP_TAB:\n"
    "                k += 1;\n"
    "                break;\n"
    "\n"
    "            /* ---- Special ops (still silent no-ops) ------------------- */\n"
    "            case RULE_OP_S_SPECIAL:  k += 1; break;\n"
    "            case RULE_OP_HASH_EXIT:  k += 1; break;\n"
    "            case RULE_OP_DIV_INSERT: k += 3; break;  /* op + count + char */\n"
    "\n"
    "            /* ---- Rejection ops (rev 1.22) ----------------------------\n"
    "             * Match applyrule byte-exact (ruleproc.c:1410-1456). On\n"
    "             * rejection we return -1 immediately; the caller is\n"
    "             * responsible for skipping MD5+probe / writing zero digests\n"
    "             * / emitting the validate sentinel record. The argument\n"
    "             * encoding is `arg - 1` per packrules positiontranslate. */\n"
    "            case RULE_OP_REJ_LEN_NE: {\n"
    "                /* `_ N`: reject if orig_len != (arg - 1). applyrule\n"
    "                 * tests the original input length, NOT the running clen. */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (y != orig_len) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_GE: {\n"
    "                /* `< N`: reject if clen < (arg - 1). Macro name is\n"
    "                 * misleading — applyrule rejects on LESS-THAN, not GE. */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len < y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_LE: {\n"
    "                /* `> N`: reject if clen > (arg - 1). Macro name is\n"
    "                 * misleading — applyrule rejects on GREATER-THAN. */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len > y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_HAS: {\n"
    "                /* `! X`: reject if buf contains X. */\n"
    "                uchar c = prog[k + 1];\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) return -1;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_NHAS: {\n"
    "                /* `/ X`: reject if buf does NOT contain X. */\n"
    "                uchar c = prog[k + 1];\n"
    "                int found = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) { found = 1; break; }\n"
    "                }\n"
    "                if (!found) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_FIRST: {\n"
    "                /* `( X`: reject if (clen > 0 && buf[0] != X). Empty buf\n"
    "                 * is accepted (matches applyrule clen-guard). */\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[0] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LAST: {\n"
    "                /* `) X`: reject if (clen > 0 && buf[clen-1] != X). Empty\n"
    "                 * buf is accepted (matches applyrule clen-guard). */\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[len - 1] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* H/h hex emit: cases split into independent bodies (rev 1.27,\n"
    "             * 2026-05-04). The unified version at rev 1.25 used a ternary-\n"
    "             * selected `const uchar *d` pointing at one of two private-memory\n"
    "             * tables; AMD's ROCm comgr LLVM 21.1.8 bitcode linker rejected the\n"
    "             * resulting addrspace(5) ↔ generic pointer aliasing with\n"
    "             * \"Invalid record\" / \"Linking bitcode failed\" (gfx1201 RX 9070).\n"
    "             * NVIDIA PTX path was unaffected (no IR-level link). Bisect on\n"
    "             * ioblade pinned the regression to r25 vs r24. Splitting the\n"
    "             * cases removes the pointer alias — each branch references its\n"
    "             * own private-memory table directly, no addrspace cast. */\n"
    "            case RULE_OP_HEX_UPPER: {\n"
    "                const uchar uhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','A','B','C','D','E','F'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = uhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = uhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_HEX_LOWER: {\n"
    "                const uchar lhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','a','b','c','d','e','f'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = lhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = lhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            default:\n"
    "                /* Unknown opcode — bail to avoid runaway walk. */\n"
    "                return len;\n"
    "        }\n"
    "    }\n"
    "    return len;\n"
    "}\n"
    "\n"
    "/* ---- Multi-block MD5 of a private byte buffer --------------------- */\n"
    "\n"
    "/* MD5 over (data, len) where data is private memory. Up to 5 blocks\n"
    " * (256 B + 9 padding bytes -> ceil((256+9)/64) = 5).\n"
    " *\n"
    " * Builds each 64-byte block from the byte stream, dispatches to\n"
    " * md5_block(&hx,&hy,&hz,&hw, M). The final block(s) include the 0x80\n"
    " * padding marker and the 64-bit little-endian length-in-bits at\n"
    " * M[14]/M[15]. If len%64 >= 56 the length doesn't fit in the final\n"
    " * data block and we emit one extra padding-only block.\n"
    " */\n"
    "static void md5_buf(const uchar *data, int len,\n"
    "                    uint *hx, uint *hy, uint *hz, uint *hw)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    *hx = 0x67452301u;\n"
    "    *hy = 0xEFCDAB89u;\n"
    "    *hz = 0x98BADCFEu;\n"
    "    *hw = 0x10325476u;\n"
    "\n"
    "    /* Process complete 64-byte blocks. */\n"
    "    while (len - pos >= 64) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(hx, hy, hz, hw, M);\n"
    "        pos += 64;\n"
    "    }\n"
    "\n"
    "    /* Build final block(s): tail bytes + 0x80 marker + zeros + length. */\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Copy remaining tail bytes into M[] little-endian. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker. */\n"
    "    M[rem >> 2] |= (uint)0x80 << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        /* Length fits in this block. */\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_block(hx, hy, hz, hw, M);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        md5_block(hx, hy, hz, hw, M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_block(hx, hy, hz, hw, M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- Production kernel --------------------------------------------\n"
    " *\n"
    " * Memo B B1 (2026-05-03): coalesced dispatch payload.\n"
    " *\n"
    " * The four per-dispatch host->GPU writes (b_packed_buf + b_chunk_index\n"
    " * + b_params + b_hit_count) are now ONE write into b_dispatch_payload\n"
    " * with the layout:\n"
    " *\n"
    " *   offset   0 : OCLParams params           (sizeof(OCLParams) == 128)\n"
    " *   offset 128 : uint hit_count             (4 bytes; kernel atomic_inc)\n"
    " *   offset 132 : uint word_offset[num_words] (deterministic from params.num_words)\n"
    " *   offset 132 + 4*num_words : uchar packed_words[]  (variable; up to 4 MiB)\n"
    " *\n"
    " * Offsets are deterministic (computable from params.num_words alone),\n"
    " * so no extra fields are stored. params.num_words is the only knob.\n"
    " *\n"
    " * Per project_gpu_pcie_baseline_20260427.md, this saves the per-call\n"
    " * SUBMIT->START tax (4 x 2.3 ms = ~9.2 ms on PCIe 3.0; ~190 us on PCIe\n"
    " * 4.0) by collapsing 4 small/medium writes into 1 medium write. The\n"
    " * pinning win from malloc_pinned host source is preserved (the staging\n"
    " * buffer the host packs into is still malloc_pinned'd; see\n"
    " * gpu_opencl_dispatch_md5_rules in gpu_opencl.c).\n"
    " *\n"
    " * The test/validate kernels (md5_rules_phase0_test*, *_validate) keep\n"
    " * the multi-arg signature -- they're diagnostic / harness paths, not\n"
    " * on the production hot loop. */\n"
    "\n"
    "__kernel\n"
    "void md5_rules_phase0(\n"
    "    __global uchar        *payload,         /* coalesced: params + hit_count + word_offset + packed */\n"
    "    __global const uchar  *rule_program,    /* compiled rule bytecode (NUL-term) */\n"
    "    __global const uint   *rule_offset,     /* byte offsets per rule */\n"
    "    __global const uint   *compact_fp,\n"
    "    __global const uint   *compact_idx,\n"
    "    __global const uchar  *hash_data_buf,\n"
    "    __global const ulong  *hash_data_off,\n"
    "    __global const ushort *unused_hash_data_len,\n"
    "    __global uint         *hits,\n"
    "    __global const ulong  *overflow_keys,\n"
    "    __global const uchar  *overflow_hashes,\n"
    "    __global const uint   *overflow_offsets,\n"
    "    __global const ushort *unused_overflow_lengths,\n"
    "    __global volatile uint *hashes_shown\n"
    "    )\n"
    "{\n"
    "    /* Decode payload header. params struct sits at offset 0; copy to\n"
    "     * private memory so subsequent field accesses stay in registers. */\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    /* B3 cursor check (Memo B §2 two-cursor protocol).\n"
    "     *\n"
    "     * On a re-issue dispatch following a hit-buffer overflow, the host\n"
    "     * sets input_cursor_start + rule_cursor_start to the (word, rule)\n"
    "     * coordinate of the first overflowing lane from the prior dispatch.\n"
    "     * Lanes whose (rule, word) lex-precedes the cursor early-return so\n"
    "     * we don't re-emit the hits already returned in the prior dispatch.\n"
    "     *\n"
    "     * Lex order: (rule_idx, word_idx). A lane is \"before the cursor\" iff:\n"
    "     *   rule_idx < rule_cursor_start, OR\n"
    "     *   (rule_idx == rule_cursor_start AND word_idx < input_cursor_start)\n"
    "     *\n"
    "     * Default behavior: cursor=0 => no lanes skip, identical to pre-B3. */\n"
    "    if (params.input_cursor_start > 0u || params.rule_cursor_start > 0u) {\n"
    "        if (rule_idx < params.rule_cursor_start) return;\n"
    "        if (rule_idx == params.rule_cursor_start &&\n"
    "            word_idx < params.input_cursor_start) return;\n"
    "    }\n"
    "\n"
    "    /* Deterministic sub-buffer pointers from params.num_words.\n"
    "     *   hit_count  @ offset 128\n"
    "     *   word_offset @ offset 132\n"
    "     *   packed_words @ offset 132 + 4*n_words\n"
    "     * The compiler hoists these out of the per-lane work since they\n"
    "     * depend only on params (uniform across the dispatch). */\n"
    "    __global volatile uint *hit_count = (__global volatile uint *)(payload + 128);\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "\n"
    "    /* B3: pointers to overflow_first_set (offset 100) and\n"
    "     * overflow_first_word (offset 104). Used by the overflow-aware\n"
    "     * EMIT_HIT_4_OR_OVERFLOW macro to record the first lane that\n"
    "     * overflowed the hit buffer. The kernel writes overflow_first_word\n"
    "     * as the lane gid (uint32, monotonic in (rule_idx, word_idx) lex\n"
    "     * order); host re-derives word/rule via gid %/n_words and gid /\n"
    "     * n_words. */\n"
    "    __global volatile uint *ovr_set =\n"
    "        (__global volatile uint *)(payload + 100);\n"
    "    __global volatile uint *ovr_gid =\n"
    "        (__global volatile uint *)(payload + 104);\n"
    "\n"
    "    /* Single private buffer, 16-byte aligned for any future vectorized\n"
    "     * op fast-paths (current walker is scalar in-place). */\n"
    "    __attribute__((aligned(16))) uchar buf[RULE_BUF_MAX];\n"
    "\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    int wlen = (int)words[wpos++];\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "    for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "    uint rpos = rule_offset[rule_idx];\n"
    "    /* Fast detect: if first byte is NUL, this is the synthetic no-rule\n"
    "     * pass (k == 0 at entry). apply_rule returns wlen unmodified. We\n"
    "     * MUST run MD5+probe for the synthetic pass — it IS the no-rule pass. */\n"
    "    int is_no_rule = (rule_program[rpos] == 0);\n"
    "    int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "\n"
    "    /* Rejection sentinel: rule fired `_ < > ! / ( )` and rejected this\n"
    "     * (word, rule) pair. Skip MD5+probe entirely. */\n"
    "    if (new_len < 0) return;\n"
    "\n"
    "    /* No-op detection: if at least one op was processed AND the post-rule\n"
    "     * buffer matches the original input bit-for-bit, the synthetic \":\"\n"
    "     * no-rule pass already covered this candidate — skip MD5+probe.\n"
    "     *\n"
    "     * Compare buf[0..new_len-1] to words[wpos..wpos+wlen-1]. */\n"
    "    if (!is_no_rule && new_len == wlen) {\n"
    "        int changed = 0;\n"
    "        for (int i = 0; i < wlen; i++) {\n"
    "            if (buf[i] != words[wpos + i]) { changed = 1; break; }\n"
    "        }\n"
    "        if (!changed) return;\n"
    "    }\n"
    "\n"
    "    /* --- Multi-block MD5 of buf[0..new_len). --------------------- */\n"
    "    uint hx, hy, hz, hw;\n"
    "    md5_buf(buf, new_len, &hx, &hy, &hz, &hw);\n"
    "\n"
    "    /* --- Iterated probe (mirrors gpu_md5_packed.cl). ------------- */\n"
    "    uint max_iter = params.max_iter;\n"
    "    if (max_iter < 1) max_iter = 1;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint matched_idx = 0u;\n"
    "        if (probe_compact_idx(hx, hy, hz, hw,\n"
    "                              compact_fp, compact_idx,\n"
    "                              params.compact_mask, params.max_probe,\n"
    "                              params.hash_data_count,\n"
    "                              hash_data_buf, hash_data_off,\n"
    "                              overflow_keys, overflow_hashes,\n"
    "                              overflow_offsets, params.overflow_count,\n"
    "                              &matched_idx)) {\n"
    "            uint mask = 1u << (iter & 31);\n"
    "            /* B3 overflow-aware dedup-aware emit (Memo B §2). On overflow,\n"
    "             * lane CAS-min's its gid into ovr_gid, signals ovr_set, AND\n"
    "             * rolls back the hashes_shown bit it just set so the re-issue\n"
    "             * lane can re-emit. Without the rollback, the dedup bit stays\n"
    "             * set across dispatches and silently drops the crack. */\n"
    "            EMIT_HIT_4_DEDUP_OR_OVERFLOW(hits, hit_count, params.max_hits,\n"
    "                       word_idx, rule_idx, iter, hx, hy, hz, hw,\n"
    "                       hashes_shown, matched_idx, mask,\n"
    "                       ovr_set, ovr_gid, gid);\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            uint M[16];\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80u;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "            M[14] = 32u * 8u;\n"
    "            M[15] = 0u;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u;\n"
    "            hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- TEST kernel: emits MD5 digest per (word, rule) -------------- */\n"
    "\n"
    "__kernel\n"
    "void md5_rules_phase0_test(\n"
    "    __global const uchar  *words,\n"
    "    __global const uint   *word_offset,\n"
    "    __global const uchar  *rule_program,\n"
    "    __global const uint   *rule_offset,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global uint         *digests_out)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    __attribute__((aligned(16))) uchar buf[RULE_BUF_MAX];\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    int wlen = (int)words[wpos++];\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "    for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "    uint rpos = rule_offset[rule_idx];\n"
    "    int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "\n"
    "    /* Rejection sentinel: write all-zero digest. The host test harness\n"
    "     * treats four-zeros as the rejection marker for this kernel. */\n"
    "    if (new_len < 0) {\n"
    "        digests_out[gid * 4 + 0] = 0u;\n"
    "        digests_out[gid * 4 + 1] = 0u;\n"
    "        digests_out[gid * 4 + 2] = 0u;\n"
    "        digests_out[gid * 4 + 3] = 0u;\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    uint hx, hy, hz, hw;\n"
    "    md5_buf(buf, new_len, &hx, &hy, &hz, &hw);\n"
    "\n"
    "    digests_out[gid * 4 + 0] = hx;\n"
    "    digests_out[gid * 4 + 1] = hy;\n"
    "    digests_out[gid * 4 + 2] = hz;\n"
    "    digests_out[gid * 4 + 3] = hw;\n"
    "}\n"
    "\n"
    "/* ---- VALIDATE kernel: emits per-(word,rule) post-rule buffer state -- */\n"
    "\n"
    "/* Validator wire format (rev 1.23, 2026-05-02 field widening):\n"
    " *   slot[0..1] = retlen as int16 little-endian (sign-preserving;\n"
    " *                values: -1 reject, -2 auto-skip, -3 fatal, >=0 length)\n"
    " *   slot[2..3] = outlen as uint16 little-endian\n"
    " *   slot[4..3+RULE_BUF_MAX] = post-rule buffer bytes\n"
    " * Record size = 4 + RULE_BUF_MAX. With RULE_BUF_MAX=40960 → 40964-byte slots.\n"
    " * Host-side mirror constants in gpu_opencl.h MUST match. */\n"
    "#define MD5_RULES_VALIDATE_MAX_BUF   RULE_BUF_MAX\n"
    "#define MD5_RULES_VALIDATE_RECORD_SZ (4 + MD5_RULES_VALIDATE_MAX_BUF)\n"
    "\n"
    "__kernel\n"
    "void md5_rules_phase0_validate(\n"
    "    __global const uchar  *words,\n"
    "    __global const uint   *word_offset,\n"
    "    __global const uchar  *rule_program,\n"
    "    __global const uint   *rule_offset,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global uchar        *records_out)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    __attribute__((aligned(16))) uchar buf[RULE_BUF_MAX];\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    int wlen = (int)words[wpos++];\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "    for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "    uint rpos = rule_offset[rule_idx];\n"
    "    int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "\n"
    "    /* Rejection sentinel: retlen=-1, outlen=0, no bytes. The host parser\n"
    "     * (gpu_opencl.c rev 1.72+) reads retlen as int16 LE and outlen as\n"
    "     * uint16 LE; the R2 reconciliation rule from #65 maps CPU retlen ∈\n"
    "     * {-1, -3} to effective_output=\"\" so the byte-exact diff lines up.\n"
    "     *\n"
    "     * Field widening rev 1.23 (2026-05-02): retlen / outlen widened from\n"
    "     * 8-bit to 16-bit LE so outputs > 255 bytes are recorded unclamped.\n"
    "     * The prior `if (retlen > 255) retlen = 255` clamp is removed; int16\n"
    "     * range -32768..32767 covers all RULE_BUF_LIMIT values up to 40959. */\n"
    "    int retlen = new_len;\n"
    "    int outlen = (retlen >= 0) ? retlen : 0;\n"
    "\n"
    "    uint slot = word_idx * n_rules + rule_idx;\n"
    "    uint base = slot * (uint)MD5_RULES_VALIDATE_RECORD_SZ;\n"
    "\n"
    "    /* retlen as int16 LE (sign-preserving via two-byte split of int16 cast). */\n"
    "    short retlen16 = (short)retlen;\n"
    "    records_out[base + 0] = (uchar)((uint)retlen16 & 0xffu);\n"
    "    records_out[base + 1] = (uchar)(((uint)retlen16 >> 8) & 0xffu);\n"
    "    /* outlen as uint16 LE. */\n"
    "    ushort outlen16 = (ushort)outlen;\n"
    "    records_out[base + 2] = (uchar)((uint)outlen16 & 0xffu);\n"
    "    records_out[base + 3] = (uchar)(((uint)outlen16 >> 8) & 0xffu);\n"
    "    for (int i = 0; i < outlen && i < MD5_RULES_VALIDATE_MAX_BUF; i++) {\n"
    "        records_out[base + 4 + (uint)i] = buf[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ---- TEST kernel (iter variant): emits per-iteration digests --------\n"
    " *\n"
    " * md5_rules_phase0_test_iter — sibling test kernel that exercises the\n"
    " * production md5_rules_phase0 iteration loop. Same (word, rule) input\n"
    " * geometry as md5_rules_phase0_test, but writes ONE digest PER iteration\n"
    " * level into digests_out[(gid * max_iter + (iter-1)) * 4 .. +3]. */\n"
    "__kernel\n"
    "void md5_rules_phase0_test_iter(\n"
    "    __global const uchar  *words,\n"
    "    __global const uint   *word_offset,\n"
    "    __global const uchar  *rule_program,\n"
    "    __global const uint   *rule_offset,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global uint         *digests_out)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    __attribute__((aligned(16))) uchar buf[RULE_BUF_MAX];\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    int wlen = (int)words[wpos++];\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "    for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "    uint rpos = rule_offset[rule_idx];\n"
    "    int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "\n"
    "    /* Rejection sentinel: zero all per-iteration slots. Same convention\n"
    "     * as the non-iter test kernel — host harness treats four-zeros per\n"
    "     * iteration level as the rejection marker. */\n"
    "    uint max_iter_r = params.max_iter;\n"
    "    if (max_iter_r < 1) max_iter_r = 1;\n"
    "    if (new_len < 0) {\n"
    "        for (uint iter = 1; iter <= max_iter_r; iter++) {\n"
    "            uint base = (gid * max_iter_r + (iter - 1u)) * 4u;\n"
    "            digests_out[base + 0] = 0u;\n"
    "            digests_out[base + 1] = 0u;\n"
    "            digests_out[base + 2] = 0u;\n"
    "            digests_out[base + 3] = 0u;\n"
    "        }\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    uint hx, hy, hz, hw;\n"
    "    md5_buf(buf, new_len, &hx, &hy, &hz, &hw);\n"
    "\n"
    "    uint max_iter = max_iter_r;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint base = (gid * max_iter + (iter - 1u)) * 4u;\n"
    "        digests_out[base + 0] = hx;\n"
    "        digests_out[base + 1] = hy;\n"
    "        digests_out[base + 2] = hz;\n"
    "        digests_out[base + 3] = hw;\n"
    "        if (iter < max_iter) {\n"
    "            uint M[16];\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80u;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "            M[14] = 32u * 8u;\n"
    "            M[15] = 0u;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u;\n"
    "            hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
