/* Auto-generated from gpu_sha384raw_core.cl -- do not edit */
static const char gpu_sha384raw_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sha384raw_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha384raw_core.cl — SHA384RAW algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 5a, Tier 1).\n"
    " *\n"
    " * SHA384RAW differs from SHA384 ONLY in template_iterate:\n"
    " *   - SHA384  iter (gpu_sha384_core.cl): re-hash 96-byte hex_lc encoding\n"
    " *     of the digest. Bytes are ASCII '0'..'9','a'..'f'.\n"
    " *   - SHA384RAW iter (this file):     re-hash the 48-byte BINARY digest\n"
    " *     directly. No hex re-encoding.\n"
    " *\n"
    " * CPU reference (mdxfind.c rev 1.394+ JOB_SHA384RAW at line 27744):\n"
    " *\n"
    " *   for (x = 1; x <= Maxiter; x++) {\n"
    " *     sph_sha384(...);                  // hash cur[0..len)\n"
    " *     sph_sha384_close(..., md5buf.h);\n"
    " *     cur = (char *)curin.h;\n"
    " *     len = 48;                         // BINARY 48 bytes\n"
    " *     memcpy(cur, md5buf.h, len);\n"
    " *     checkhash(&curin, 96, x, job);    // hexlen=96 is for compact-table probe\n"
    " *   }\n"
    " *\n"
    " * Key invariant: at iter N, the input is the 48-byte BIG-ENDIAN binary\n"
    " * digest from iter N-1 (the standard SHA-384 output byte order). Each\n"
    " * compression block consumes 128 bytes; 48 + 1 (0x80 marker) + 16\n"
    " * (length) = 65 bytes ≤ 128. So a single block suffices for the iter\n"
    " * step.\n"
    " *\n"
    " * Block layout for the iter step:\n"
    " *   M[0..5] = 48 BE digest bytes from state[0..5] (each ulong holds 8\n"
    " *             bytes BE — same byte order as the digest output from\n"
    " *             template_finalize).\n"
    " *   M[6] = 0x8000000000000000UL  (0x80 at byte 48 in BE position)\n"
    " *   M[7..13] = 0\n"
    " *   M[14] = 0          (high 64 bits of bit count)\n"
    " *   M[15] = 48 * 8 = 384 (low 64 bits)\n"
    " *\n"
    " * All other extension functions (template_state, template_init,\n"
    " * template_transform, template_finalize, template_digest_compare,\n"
    " * template_emit_hit) are byte-identical to gpu_sha384_core.cl. We\n"
    " * duplicate the body inline rather than #include to keep the per-algo\n"
    " * source unit self-contained and the cache key clean (Memo B R3:\n"
    " * defines_str + source-text hash).\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=12,HASH_BLOCK_BYTES=128\" —\n"
    " * same as SHA384. Distinct cache entry guaranteed by source-text hash\n"
    " * difference (only template_iterate differs; the rest is byte-identical).\n"
    " *\n"
    " * R1 mitigation: single private buffer pattern; no addrspace-cast\n"
    " * helpers. Same shape as gpu_sha384_core.cl.\n"
    " *\n"
    " * R2 (register pressure): same compression footprint as SHA512 / SHA384\n"
    " * (W[80] schedule). priv_mem_size on gfx1201 expected ~ 42.5 KB (within\n"
    " * the 64-VGPR / 256-byte hard ceiling, comparable to SHA512).\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha384raw_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 12\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 128\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    ulong state[8];   /* internal compression state, BIG-ENDIAN */\n"
    "    uint  h[HASH_WORDS]; /* exposed digest words, LE-byteswapped uint32 (12 only) */\n"
    "} template_state;\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->state[0] = 0xcbbb9d5dc1059ed8UL;\n"
    "    st->state[1] = 0x629a292a367cd507UL;\n"
    "    st->state[2] = 0x9159015a3070dd17UL;\n"
    "    st->state[3] = 0x152fecd8f70e5939UL;\n"
    "    st->state[4] = 0x67332667ffc00b31UL;\n"
    "    st->state[5] = 0x8eb44a8768581511UL;\n"
    "    st->state[6] = 0xdb0c2e0d64f98fa7UL;\n"
    "    st->state[7] = 0x47b5481dbefa4fa4UL;\n"
    "}\n"
    "\n"
    "static inline void template_state_to_h(template_state *st) {\n"
    "    for (int i = 0; i < 6; i++) {\n"
    "        ulong s = bswap64(st->state[i]);\n"
    "        st->h[i*2]   = (uint)s;\n"
    "        st->h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    ulong M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 8;\n"
    "        M[j] = ((ulong)block[b]     << 56)\n"
    "             | ((ulong)block[b + 1] << 48)\n"
    "             | ((ulong)block[b + 2] << 40)\n"
    "             | ((ulong)block[b + 3] << 32)\n"
    "             | ((ulong)block[b + 4] << 24)\n"
    "             | ((ulong)block[b + 5] << 16)\n"
    "             | ((ulong)block[b + 6] << 8)\n"
    "             |  (ulong)block[b + 7];\n"
    "    }\n"
    "    sha512_block(&st->state[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: byte-identical to gpu_sha384_core.cl. SHA384\n"
    " * compression + 128-bit length + 12-uint32 truncation. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    ulong M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 8;\n"
    "            M[j] = ((ulong)data[b]     << 56)\n"
    "                 | ((ulong)data[b + 1] << 48)\n"
    "                 | ((ulong)data[b + 2] << 40)\n"
    "                 | ((ulong)data[b + 3] << 32)\n"
    "                 | ((ulong)data[b + 4] << 24)\n"
    "                 | ((ulong)data[b + 5] << 16)\n"
    "                 | ((ulong)data[b + 6] << 8)\n"
    "                 |  (ulong)data[b + 7];\n"
    "        }\n"
    "        sha512_block(&st->state[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..127 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 3;\n"
    "        int bi = 7 - (i & 7);\n"
    "        M[wi] |= ((ulong)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 3;\n"
    "        int bi = 7 - (rem & 7);\n"
    "        M[wi] |= ((ulong)0x80UL) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 112) {\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    } else {\n"
    "        sha512_block(&st->state[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    }\n"
    "\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: SHA384RAW iter — re-feed the 48-byte BINARY digest\n"
    " * (not hex-encoded) into the compression. CPU reference at mdxfind.c\n"
    " * line 27744:\n"
    " *\n"
    " *   memcpy(cur, md5buf.h, 48);\n"
    " *   sph_sha384(cur, 48);\n"
    " *\n"
    " * State after template_finalize: state[0..5] hold the BE-packed digest\n"
    " * (state[i] = digest bytes [i*8..i*8+7] in BE = state[i] when interpreted\n"
    " * as a BE uint64). state[6..7] have the trailing internal chain values\n"
    " * but are NOT part of the digest output.\n"
    " *\n"
    " * For the iter step, we treat the first 48 bytes of the BIG-ENDIAN\n"
    " * digest as the new input. M[0..5] = state[0..5] directly (since BE byte\n"
    " * order matches sha512's M-load convention). M[6] is the 0x80 marker;\n"
    " * M[14..15] is the bit count.\n"
    " *\n"
    " * Layout:\n"
    " *   M[0..5]  = state[0..5] (48 BE digest bytes; state ulongs are already\n"
    " *              in the BE byte order that sha512_block expects)\n"
    " *   M[6]     = 0x8000000000000000UL  (0x80 padding marker at byte 48)\n"
    " *   M[7..13] = 0\n"
    " *   M[14]    = 0          (high 64 bits of bit count)\n"
    " *   M[15]    = 48 * 8 = 384 (low 64 bits)\n"
    " *\n"
    " * Single block (48 + 1 + 16 = 65 ≤ 128). After absorption, decompose\n"
    " * state[0..5] into h[0..11].\n"
    " */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    ulong M[16];\n"
    "    /* Copy the BE-packed digest directly into M[0..5]. state[i] is\n"
    "     * already the BE uint64 of digest bytes [i*8..i*8+7] — matches the\n"
    "     * sha512_block M-load convention exactly. */\n"
    "    M[0] = st->state[0];\n"
    "    M[1] = st->state[1];\n"
    "    M[2] = st->state[2];\n"
    "    M[3] = st->state[3];\n"
    "    M[4] = st->state[4];\n"
    "    M[5] = st->state[5];\n"
    "    M[6] = 0x8000000000000000UL;   /* 0x80 BE at byte 48 */\n"
    "    M[7] = 0UL;\n"
    "    for (int j = 8; j < 14; j++) M[j] = 0UL;\n"
    "    M[14] = 0UL;\n"
    "    M[15] = 48UL * 8UL;            /* 48 binary bytes = 384 bits */\n"
    "\n"
    "    /* Reset state to SHA384 IV; absorb the prepared block. */\n"
    "    st->state[0] = 0xcbbb9d5dc1059ed8UL;\n"
    "    st->state[1] = 0x629a292a367cd507UL;\n"
    "    st->state[2] = 0x9159015a3070dd17UL;\n"
    "    st->state[3] = 0x152fecd8f70e5939UL;\n"
    "    st->state[4] = 0x67332667ffc00b31UL;\n"
    "    st->state[5] = 0x8eb44a8768581511UL;\n"
    "    st->state[6] = 0xdb0c2e0d64f98fa7UL;\n"
    "    st->state[7] = 0x47b5481dbefa4fa4UL;\n"
    "    sha512_block(&st->state[0], M);\n"
    "\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_12((hits), (hit_count), (max_hits), \\\n"
    "                (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_12_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
