/* Auto-generated from gpu_blake2b256_core.cl -- do not edit */
static const char gpu_blake2b256_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_blake2b256_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_blake2b256_core.cl — BLAKE2B-256 algorithm extension functions for\n"
    " * the generic dispatch template (Memo B Phase B5 sub-batch 3).\n"
    " *\n"
    " * BLAKE2B-256 is BLAKE2b with digest_length=32 (256 bits). The compression\n"
    " * function is identical to BLAKE2B-512; only the parameter-block init and\n"
    " * output truncation differ.\n"
    " *\n"
    " * Geometry / byte ordering:\n"
    " *   - 128-byte block (vs BLAKE2S-256's 64-byte)\n"
    " *   - 8 × uint64 chaining state, LITTLE-ENDIAN\n"
    " *   - 12-round G-function compression (b2b_compress in gpu_common.cl)\n"
    " *   - parameter block init: IV[0] ^ 0x01010020\n"
    " *     (digest_length=32 << 0 | key_length=0 << 8 | fanout=1 << 16 |\n"
    " *      depth=1 << 24 — high 32 bits zero)\n"
    " *   - 32-byte output = first 4 ulong = 8 uint32 LE (truncated from full\n"
    " *     64-byte 8-ulong digest)\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (8 for BLAKE2B-256)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (128)\n"
    " *   template_state     — h[8] ulong digest + t[2] ulong counter + f[2]\n"
    " *                        ulong flag, plus exposed h_uint[HASH_WORDS] for\n"
    " *                        template body's digests_out and EMIT_HIT_8\n"
    " *\n"
    " * The state struct INTERNALLY carries 8 ulong h_ulong[8] (BLAKE2b chaining)\n"
    " * but the template body needs uint32 access via .h[]. This mirrors\n"
    " * gpu_sha512_core.cl rev 1.1 exactly: the per-uint64 state is decomposed\n"
    " * into a uint h[HASH_WORDS] array at the end of finalize/iterate so the\n"
    " * template body and EMIT_HIT macros work without 64-bit indirection.\n"
    " *\n"
    " *   template_init      — install IV ^ parameter_block (h_ulong); zero\n"
    " *                        counter+flag\n"
    " *   template_transform — absorb one 128-byte block (NON-FINAL)\n"
    " *   template_finalize  — process complete blocks, zero tail, run final\n"
    " *                        compression with last==1; populate h[8] = first\n"
    " *                        4 ulong as 8 uint32 LE\n"
    " *   template_iterate   — re-hash digest as 64-byte hex_lc input (32-byte\n"
    " *                        binary -> 64 lc hex chars). 64 < 128 so the hex\n"
    " *                        string fits in one BLAKE2b block; single\n"
    " *                        compression with last=1, counter=64\n"
    " *   template_digest_compare — probe leading 16 bytes (h[0..3]) directly;\n"
    " *                             LE state convention.\n"
    " *   template_emit_hit       — EMIT_HIT_8 wrapper (8 uint32 LE; first 4\n"
    " *                             ulong of BLAKE2B output decomposed)\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_blake2b256_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides B2B_IV[8], B2B_SIGMA[12][16], b2b_compress(),\n"
    " * EMIT_HIT_8{,_DEDUP_OR_OVERFLOW}, and probe_compact_idx.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Internal h_ulong[0..7] is LE per ulong; output bytes laid out\n"
    " *     little-endian (matches mdxfind.c blake2b_hash() at line 2446 which\n"
    " *     uses memcpy(out, h, outlen) — direct ulong byte image).\n"
    " *   - Decomposition to st->h[0..7] uint32 LE pairs:\n"
    " *       st->h[2i]   = (uint)h_ulong[i]\n"
    " *       st->h[2i+1] = (uint)(h_ulong[i] >> 32)\n"
    " *     This is the LE byte image of each ulong split into two uint32\n"
    " *     numerical halves. Probe key st->h[0..3] therefore corresponds to\n"
    " *     the leading 16 hash bytes — same convention as BLAKE2s256, MD5,\n"
    " *     and the host compact-table format.\n"
    " *   - Wire format matches gpu_blake2s256unsalted.cl emit (8 uint32 LE)\n"
    " *     so the hit-replay path in gpujob_opencl.c reads the same 32-byte\n"
    " *     binary digest regardless of which algorithm produced it.\n"
    " *\n"
    " * R1 mitigation: single-private-buffer pattern. b2b_compress takes\n"
    " * __private uchar* + __private ulong* (existing primitives in gpu_common.cl).\n"
    " *\n"
    " * R2 (register pressure): BLAKE2B's 8 ulong chaining + 16 ulong v[] +\n"
    " * 16 ulong m[] in b2b_compress = ~80 64-bit registers ~= 160 32-bit\n"
    " * registers. May approach the gfx1201 VGPR ceiling. Memo §3 R2 flagged\n"
    " * SHA-512 family as the boundary case (~50 VGPR); BLAKE2b is similar.\n"
    " * Per-phase clGetKernelWorkGroupInfo(CL_KERNEL_PRIVATE_MEM_SIZE) probe\n"
    " * provides the actual reading; SHA-512's 42,520 B on gfx1201 is the\n"
    " * comparison baseline.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 8\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 128\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct. h_ulong[] is the 8-ulong BLAKE2b chaining state\n"
    " * used internally by b2b_compress; h[] is the LE-uint32-decomposed view\n"
    " * exposed to the template body and EMIT_HIT macros.\n"
    " *\n"
    " * Counter t[] and flag f[] are kept as ulong pairs to mirror RFC 7693\n"
    " * BLAKE2b's spec layout (BLAKE2b uses 128-bit counter / flag pair; for\n"
    " * our wordlist inputs t[1] always = 0). */\n"
    "typedef struct {\n"
    "    ulong h_ulong[8];     /* internal chaining state, LE per ulong */\n"
    "    ulong t[2];           /* 128-bit byte counter (low, high) */\n"
    "    ulong f[2];           /* finalization flag pair */\n"
    "    uint  h[HASH_WORDS];  /* exposed digest words (template body reads h[]) */\n"
    "} template_state;\n"
    "\n"
    "/* Internal helper: decompose first 4 ulong of internal state into 8 LE\n"
    " * uint32 for the exposed h[] (truncated to digest_length=32 bytes). */\n"
    "static inline void template_state_to_h_b256(template_state *st) {\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        ulong v = st->h_ulong[i];\n"
    "        st->h[i * 2]     = (uint)v;\n"
    "        st->h[i * 2 + 1] = (uint)(v >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_init: install BLAKE2B-256 IV XOR'd with parameter block.\n"
    " *\n"
    " * Parameter block layout (RFC 7693 §2.5, BLAKE2b version):\n"
    " *   bytes 0:    digest_length = 32\n"
    " *   byte 1:     key_length = 0\n"
    " *   byte 2:     fanout = 1\n"
    " *   byte 3:     depth = 1\n"
    " *   bytes 4..7: leaf_length = 0\n"
    " *   bytes 8..15: node_offset = 0  (BLAKE2b widens to 64-bit here)\n"
    " *   byte 16:    node_depth = 0\n"
    " *   byte 17:    inner_length = 0\n"
    " *   bytes 18..31: reserved = 0\n"
    " *   bytes 32..47: salt = 0\n"
    " *   bytes 48..63: personalization = 0\n"
    " *\n"
    " * Param block as 8 ulong LE: P[0] = 0x0000000001010020 (digest=32, key=0,\n"
    " * fanout=1, depth=1, leaf=0); P[1..7] = 0. So h_ulong[0] = IV[0] ^\n"
    " * 0x01010020; h_ulong[1..7] = IV[1..7]. Matches mdxfind.c blake2b_hash\n"
    " * (line 2431) parameter-block formula `0x01010000 ^ outlen` exactly when\n"
    " * outlen=32 (0x01010000 ^ 0x20 = 0x01010020). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) st->h_ulong[i] = B2B_IV[i];\n"
    "    st->h_ulong[0] ^= 0x01010020UL;   /* digest_length=32, key=0, fanout=1, depth=1 */\n"
    "    st->t[0] = 0UL; st->t[1] = 0UL;\n"
    "    st->f[0] = 0UL; st->f[1] = 0UL;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one full 128-byte block as NON-FINAL.\n"
    " * Public extension API; template_finalize hot path bypasses for perf. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    /* Advance 128-bit counter by full block size. */\n"
    "    ulong t0 = st->t[0] + (ulong)HASH_BLOCK_BYTES;\n"
    "    ulong carry = (t0 < st->t[0]) ? 1UL : 0UL;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "    b2b_compress(&st->h_ulong[0], block, st->t[0], st->t[1], 0);\n"
    "}\n"
    "\n"
    "/* template_finalize: process all input start-to-end, advance counter,\n"
    " * zero-pad final block, run final compression with last=1.\n"
    " *\n"
    " * Same shape as gpu_blake2s256_core.cl template_finalize but with 128-byte\n"
    " * blocks and ulong counter. The \"len > HASH_BLOCK_BYTES strictly greater\"\n"
    " * loop preserves the BLAKE2 invariant: the final block runs with last=1\n"
    " * even when len is an exact multiple of 128.\n"
    " *\n"
    " * After return, h_ulong[0..7] holds the final BLAKE2B-256 chaining state;\n"
    " * the first 4 ulong contain the 32-byte output. h[0..7] (8 uint32 LE) is\n"
    " * populated by template_state_to_h_b256 for emit. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    int pos = 0;\n"
    "    while ((len - pos) > HASH_BLOCK_BYTES) {\n"
    "        ulong t0 = st->t[0] + (ulong)HASH_BLOCK_BYTES;\n"
    "        ulong carry = (t0 < st->t[0]) ? 1UL : 0UL;\n"
    "        st->t[0] = t0;\n"
    "        st->t[1] += carry;\n"
    "        b2b_compress(&st->h_ulong[0], data + pos, st->t[0], st->t[1], 0);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    for (int i = 0; i < rem; i++) buf[i] = data[pos + i];\n"
    "    for (int i = rem; i < HASH_BLOCK_BYTES; i++) buf[i] = 0;\n"
    "\n"
    "    ulong t0 = st->t[0] + (ulong)rem;\n"
    "    ulong carry = (t0 < st->t[0]) ? 1UL : 0UL;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "\n"
    "    st->f[0] = 0xFFFFFFFFFFFFFFFFUL;\n"
    "    b2b_compress(&st->h_ulong[0], buf, st->t[0], st->t[1], 1);\n"
    "\n"
    "    /* Decompose first 4 ulong → 8 uint32 LE for template body / emit. */\n"
    "    template_state_to_h_b256(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: re-hash 32-byte digest as 64-byte hex_lc and BLAKE2B-256\n"
    " * the hex string. Mirrors mdxfind.c JOB_BLAKE2B256 (line 30821-30828):\n"
    " * blake2b_hash(curin.h, 32, ...); len = 64; prmd5(curin.h, mdbuf, 64)\n"
    " * writes 64 lowercase hex chars; next iter blake2b's those 64 bytes.\n"
    " *\n"
    " * 64 hex chars < HASH_BLOCK_BYTES (128), so the hex string fits one\n"
    " * partial 128-byte block with 64 zero-padding bytes. Single compression\n"
    " * with last=1, counter=64.\n"
    " *\n"
    " * Snapshot the 8 LE uint32 from h[] BEFORE the IV reset. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint snap[HASH_WORDS];\n"
    "    for (int i = 0; i < HASH_WORDS; i++) snap[i] = st->h[i];\n"
    "\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    /* Hex-encode 8 LE uint32 -> 64 lowercase hex chars (matches prmd5\n"
    "     * byte order: byte 0 of each uint32 is hex'd first). */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint s = snap[i];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uchar by = (uchar)((s >> (b * 8)) & 0xFFu);\n"
    "            uchar hi = by >> 4, lo = by & 0xFu;\n"
    "            buf[i * 8 + b * 2 + 0] = (hi < 10) ? (uchar)('0' + hi) : (uchar)('a' + (hi - 10));\n"
    "            buf[i * 8 + b * 2 + 1] = (lo < 10) ? (uchar)('0' + lo) : (uchar)('a' + (lo - 10));\n"
    "        }\n"
    "    }\n"
    "    /* Zero the rest of the 128-byte block (64..127). */\n"
    "    for (int i = 64; i < HASH_BLOCK_BYTES; i++) buf[i] = 0;\n"
    "\n"
    "    /* Reset state for the new compression. */\n"
    "    for (int i = 0; i < 8; i++) st->h_ulong[i] = B2B_IV[i];\n"
    "    st->h_ulong[0] ^= 0x01010020UL;\n"
    "    st->t[0] = 64UL; st->t[1] = 0UL;\n"
    "    st->f[0] = 0xFFFFFFFFFFFFFFFFUL; st->f[1] = 0UL;\n"
    "\n"
    "    b2b_compress(&st->h_ulong[0], buf, 64UL, 0UL, 1);\n"
    "\n"
    "    template_state_to_h_b256(st);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe leading 16 bytes (h[0..3]). LE state\n"
    " * convention; no bswap32. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: EMIT_HIT_8 wrapper (BLAKE2B-256 truncated digest =\n"
    " * 8 uint32 LE words, populated by template_state_to_h_b256). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_8((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_8_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
