/* Auto-generated from gpu_md5_bf.cl -- do not edit */
static const char gpu_md5_bf_str[] =
    "/* gpu_md5_bf.cl — MD5 brute-force fast-path algorithm core for the\n"
    " * generic dispatch template (Phase 1.9 Tranche A2).\n"
    " *\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_md5_bf.cl,v $\n"
    " * Revision 1.2  2026/05/11 04:07:40  dlr\n"
    " * BF Phase 1.9 A2 (kernel optimization in gpu_md5_bf.cl): (1) Inline md5_block as static inline md5_compress_inline with VALUE-PASSED M[0..15] message words as scalar args (not pointer). Eliminates the pointer aliasing constraint that prevented register-residency in the noinline+pointer-param signature at gpu_common.cl:540 (which was the smoking gun per A0 — 41 KB private mem on every platform). State pointers (&st->h[0..3]) retained because gpu_template.cl owns template_state allocation; inliner sees through them. (2) Round-constant pre-add hoist: 64 local scalars s00..s63 = M_j + K_i precomputed upfront; the 64 BF_FF/GG/HH/II step macros consume the precomputed sums. Slow path (gpu_md5_core.cl + gpu_common.cl noinline md5_block) UNTOUCHED — A2 is gpu_md5_bf.cl-only. LOC: 254 -> 472. Validated on fpga 1080: V1.9.A2.1 correctness 3/3 cracks byte-exact; V1.9.A2.2 kernel-only rate 0.984 GH/s mean of 3 runs (vs slow-path 0.651 GH/s = +51%) — 1.6% UNDER 1.0 GH/s ship gate, but user-blessed ship-and-proceed-to-A3 2026-05-10. V1.9.A2.4 env override MDXFIND_GPU_FAST_DISABLE=1 still forces slow path correctly. Architects 1.5-2.5 GH/s projection assumed amortization across many candidates per WI; mdxfind runs 1 candidate per WI so pre-hoist only saves ~60 ADDs per WI on a path that already runs 64 MD5 steps. A3 (host mask pre-explode) restructures to N-candidates-per-WI which should amortize the pre-hoist properly.\n"
    " *\n"
    " * Revision 1.2  2026/05/11 04:00:00  dlr\n"
    " * Tranche A2: inline md5_block (value-passed M[16]) + round-constant\n"
    " * pre-add hoist. Removes the noinline pointer-param boundary from\n"
    " * gpu_common.cl:540 for the BF-fast path. State + message words kept\n"
    " * in registers across the round chain; (M_j + K_round) sums hoisted\n"
    " * outside the round body so the round step is a single F/G/H/I plus\n"
    " * rotate+add. Slow path (gpu_md5_core.cl) unchanged.\n"
    " *\n"
    " * Revision 1.1  2026/05/11 03:45:43  dlr\n"
    " * Initial revision — A1 skeleton (verbatim of gpu_md5_core.cl 1.2).\n"
    " *\n"
    " * Phase 1.9 architecture: side-by-side fast path for the hottest BF case\n"
    " * (unsalted JOB_MD5, no-rules, append-mask npre==0 / napp in [1,8]).\n"
    " * Selected at gpu_template_resolve_kernel time when bf_fast_eligible is\n"
    " * set on the dispatch; everything else continues to use gpu_md5_core.cl\n"
    " * (the slow generic path). See project_bf_phase19_kernel_parity.md.\n"
    " *\n"
    " * TRANCHE A2 SCOPE (this revision):\n"
    " *\n"
    " *  (A2.1) Inline MD5 compressor. A new `md5_compress_inline` function\n"
    " *         is defined locally in this file with `static inline` and a\n"
    " *         signature that takes M[0..15] BY VALUE (16 uint args) instead\n"
    " *         of via a __private uint* parameter. The four call sites that\n"
    " *         previously invoked `md5_block(&h0, &h1, &h2, &h3, M)` now\n"
    " *         pass the message words directly: `md5_compress_inline(&h0,\n"
    " *         &h1, &h2, &h3, M[0], M[1], ..., M[15])`. The state pointers\n"
    " *         remain because they reference st->h[0..3]; the inliner sees\n"
    " *         through them at the call site since `template_state st` is\n"
    " *         a stack-local with no escapes. The gpu_common.cl `md5_block`\n"
    " *         is left intact (still used by other cores via the slow path).\n"
    " *\n"
    " *         Rationale: the gpu_common.cl `md5_block` declaration is\n"
    " *         `__attribute__((noinline)) void md5_block(uint *h0..h3, uint\n"
    " *         *M)` (gpu_common.cl:540). Three pathologies in one site:\n"
    " *           1. `noinline` forbids the compiler from inlining.\n"
    " *           2. Pointer params force state to round-trip through\n"
    " *              __private memory across the call boundary.\n"
    " *           3. `__private uint *M` often spills to local under Pascal\n"
    " *              register pressure.\n"
    " *         A0 measured 41,040 B priv_mem on every platform — that is\n"
    " *         the smoking gun. Value-passing M[] + inline gives the\n"
    " *         compiler unambiguous license to keep state + M in registers.\n"
    " *\n"
    " *  (A2.2) Round-constant pre-add hoist. Each MD5 step has the shape\n"
    " *         `a = b + rotate(a + F(b,c,d) + M_j + K_i, s)`. The two\n"
    " *         operands `M_j + K_i` are independent of (a,b,c,d) and can\n"
    " *         be summed once before the round body. The compiler is free\n"
    " *         to do this anyway when M is a constant; but when M was\n"
    " *         pointer-aliased and noinline prevented inlining, the\n"
    " *         compiler could not prove the values constant. With (A2.1)\n"
    " *         already inlining the function and passing M by value, we\n"
    " *         get this fold for free at -O3 — but we make it explicit\n"
    " *         here for: (a) clarity, (b) better PTX/AMDIL scheduling\n"
    " *         (independent adds become a tree the scheduler can issue\n"
    " *         in parallel), and (c) future tranches A3-A4 where the\n"
    " *         60 pre-adds for an entire candidate batch could be\n"
    " *         hoisted outside an inner per-candidate loop.\n"
    " *\n"
    " *         Implementation: the function body precomputes 64 local\n"
    " *         scalars `s0..s63` = `M_j + K_i` upfront (one per MD5 round\n"
    " *         step, in round order), then the 64 STEP invocations use\n"
    " *         the precomputed scalars. The K_i values are inlined as\n"
    " *         literals at each step (compiler folds at constant prop).\n"
    " *\n"
    " *  NOT IN A2: host-side mask pre-explosion (A3), bitselect / vendor\n"
    " *  intrinsics (A4). These are separate tranches.\n"
    " *\n"
    " * Mali compatibility: NOT a constraint per user decision 2026-05-10.\n"
    " * (Mali support is being retired in a separate task.)\n"
    " *\n"
    " * Source-order at compile time (gpu_opencl_template_md5_bf_compile):\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_md5_bf_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_md5_rules_str provides apply_rule() for the rules walker; this\n"
    " * file provides the per-algorithm hooks; gpu_template_str ties them\n"
    " * into the template_phase0 kernel (same kernel name as the slow path —\n"
    " * the algorithm core is selected at source-array compose time, not at\n"
    " * runtime; the cache key disambiguates via defines_str \"BF_FAST_MD5=1\"\n"
    " * plus the source-text hash).\n"
    " *\n"
    " * Bytecast invariants (carry over from gpu_md5_core.cl 1.2):\n"
    " *   - apply_rule + buf in/out is identical to gpu_md5_rules.cl rev 1.28+.\n"
    " *   - md5 padding + multi-block logic is identical to md5_buf in\n"
    " *     gpu_md5_rules.cl (we do not call md5_buf directly to keep this\n"
    " *     file self-contained for future algorithm forks; the bytewise\n"
    " *     equivalence is the byte-exact gate).\n"
    " *   - template_finalize() builds the M[16] message words directly\n"
    " *     from the input bytes (mirrors md5_buf) and calls the inline\n"
    " *     compressor once per block. It does NOT route through\n"
    " *     template_transform() — that wrapper exists for the public API\n"
    " *     but is bypassed in the hot path because the byte-buffer\n"
    " *     round-trip cost would dominate.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): the template\n"
    " * passes a `__private uchar *buf` and `__private template_state *st`.\n"
    " * No addrspace-cast ternary pointers, no helper that takes a generic\n"
    " * pointer to private state. Pattern matches the safe single-private-\n"
    " * buffer model from gpu_md5_rules.cl r28.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. The template uses these as structural\n"
    " * compile-time constants; the kernel-cache key (gpu_kernel_cache R3\n"
    " * fix) hashes the defines_str (\"HASH_WORDS=4,HASH_BLOCK_BYTES=64,\n"
    " * BF_FAST_MD5=1\") alongside the source set so distinct instantiations\n"
    " * get distinct cache entries even though source text would otherwise\n"
    " * be identical. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: MD5 carries 4 uint32 chaining values.\n"
    " * SHA1 will carry 5; SHA256 8; SHA384/SHA512 8 ulong. The template\n"
    " * only reads/writes the digest words via template_finalize's output\n"
    " * + template_digest_compare; it does not introspect the struct. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* ============================================================== */\n"
    "/* A2: local inline MD5 compressor with value-passed M[16] and\n"
    " * pre-hoisted (M_j + K_i) round-constant sums.\n"
    " *\n"
    " * The macros mirror gpu_common.cl FF/GG/HH/II semantically. Their\n"
    " * signatures take a SINGLE precomputed scalar `mk = M_j + K_i`\n"
    " * instead of separate (m, k) operands. Functionally identical:\n"
    " *   a += F(b,c,d) + M_j + K_i; a = b + rotate(a, s)\n"
    " * is the same as\n"
    " *   a += F(b,c,d) + mk;        a = b + rotate(a, s)\n"
    " * for `mk = M_j + K_i` (addition is associative on uint32). */\n"
    "#define BF_FF(a,b,c,d,mk,s) { a += ((b&c)|(~b&d)) + (mk); a = b + rotate(a,(uint)(s)); }\n"
    "#define BF_GG(a,b,c,d,mk,s) { a += ((d&b)|(~d&c)) + (mk); a = b + rotate(a,(uint)(s)); }\n"
    "#define BF_HH(a,b,c,d,mk,s) { a += (b^c^d) + (mk);        a = b + rotate(a,(uint)(s)); }\n"
    "#define BF_II(a,b,c,d,mk,s) { a += (c^(~d|b)) + (mk);     a = b + rotate(a,(uint)(s)); }\n"
    "\n"
    "/* Single inline compressor used by every call site in this file.\n"
    " * All 16 message words are value-passed; the compiler is free to\n"
    " * keep them in registers across the round chain. The 60 round-\n"
    " * constant pre-adds are computed once upfront; the remaining\n"
    " * dependency chain is F/G/H/I -> rotate -> add (3 ops per step). */\n"
    "static inline void md5_compress_inline(\n"
    "    uint *h0, uint *h1, uint *h2, uint *h3,\n"
    "    uint M0,  uint M1,  uint M2,  uint M3,\n"
    "    uint M4,  uint M5,  uint M6,  uint M7,\n"
    "    uint M8,  uint M9,  uint M10, uint M11,\n"
    "    uint M12, uint M13, uint M14, uint M15)\n"
    "{\n"
    "    /* State copy into scalars — compiler keeps these in registers. */\n"
    "    uint a = *h0, b = *h1, c = *h2, d = *h3;\n"
    "\n"
    "    /* Round 1 (FF): 16 steps, message index = step index. */\n"
    "    uint s00 = M0  + 0xd76aa478u;\n"
    "    uint s01 = M1  + 0xe8c7b756u;\n"
    "    uint s02 = M2  + 0x242070dbu;\n"
    "    uint s03 = M3  + 0xc1bdceeeu;\n"
    "    uint s04 = M4  + 0xf57c0fafu;\n"
    "    uint s05 = M5  + 0x4787c62au;\n"
    "    uint s06 = M6  + 0xa8304613u;\n"
    "    uint s07 = M7  + 0xfd469501u;\n"
    "    uint s08 = M8  + 0x698098d8u;\n"
    "    uint s09 = M9  + 0x8b44f7afu;\n"
    "    uint s10 = M10 + 0xffff5bb1u;\n"
    "    uint s11 = M11 + 0x895cd7beu;\n"
    "    uint s12 = M12 + 0x6b901122u;\n"
    "    uint s13 = M13 + 0xfd987193u;\n"
    "    uint s14 = M14 + 0xa679438eu;\n"
    "    uint s15 = M15 + 0x49b40821u;\n"
    "\n"
    "    /* Round 2 (GG): message index permutation = (1+5k) mod 16. */\n"
    "    uint s16 = M1  + 0xf61e2562u;\n"
    "    uint s17 = M6  + 0xc040b340u;\n"
    "    uint s18 = M11 + 0x265e5a51u;\n"
    "    uint s19 = M0  + 0xe9b6c7aau;\n"
    "    uint s20 = M5  + 0xd62f105du;\n"
    "    uint s21 = M10 + 0x02441453u;\n"
    "    uint s22 = M15 + 0xd8a1e681u;\n"
    "    uint s23 = M4  + 0xe7d3fbc8u;\n"
    "    uint s24 = M9  + 0x21e1cde6u;\n"
    "    uint s25 = M14 + 0xc33707d6u;\n"
    "    uint s26 = M3  + 0xf4d50d87u;\n"
    "    uint s27 = M8  + 0x455a14edu;\n"
    "    uint s28 = M13 + 0xa9e3e905u;\n"
    "    uint s29 = M2  + 0xfcefa3f8u;\n"
    "    uint s30 = M7  + 0x676f02d9u;\n"
    "    uint s31 = M12 + 0x8d2a4c8au;\n"
    "\n"
    "    /* Round 3 (HH): message index permutation = (5+3k) mod 16. */\n"
    "    uint s32 = M5  + 0xfffa3942u;\n"
    "    uint s33 = M8  + 0x8771f681u;\n"
    "    uint s34 = M11 + 0x6d9d6122u;\n"
    "    uint s35 = M14 + 0xfde5380cu;\n"
    "    uint s36 = M1  + 0xa4beea44u;\n"
    "    uint s37 = M4  + 0x4bdecfa9u;\n"
    "    uint s38 = M7  + 0xf6bb4b60u;\n"
    "    uint s39 = M10 + 0xbebfbc70u;\n"
    "    uint s40 = M13 + 0x289b7ec6u;\n"
    "    uint s41 = M0  + 0xeaa127fau;\n"
    "    uint s42 = M3  + 0xd4ef3085u;\n"
    "    uint s43 = M6  + 0x04881d05u;\n"
    "    uint s44 = M9  + 0xd9d4d039u;\n"
    "    uint s45 = M12 + 0xe6db99e5u;\n"
    "    uint s46 = M15 + 0x1fa27cf8u;\n"
    "    uint s47 = M2  + 0xc4ac5665u;\n"
    "\n"
    "    /* Round 4 (II): message index permutation = 7k mod 16. */\n"
    "    uint s48 = M0  + 0xf4292244u;\n"
    "    uint s49 = M7  + 0x432aff97u;\n"
    "    uint s50 = M14 + 0xab9423a7u;\n"
    "    uint s51 = M5  + 0xfc93a039u;\n"
    "    uint s52 = M12 + 0x655b59c3u;\n"
    "    uint s53 = M3  + 0x8f0ccc92u;\n"
    "    uint s54 = M10 + 0xffeff47du;\n"
    "    uint s55 = M1  + 0x85845dd1u;\n"
    "    uint s56 = M8  + 0x6fa87e4fu;\n"
    "    uint s57 = M15 + 0xfe2ce6e0u;\n"
    "    uint s58 = M6  + 0xa3014314u;\n"
    "    uint s59 = M13 + 0x4e0811a1u;\n"
    "    uint s60 = M4  + 0xf7537e82u;\n"
    "    uint s61 = M11 + 0xbd3af235u;\n"
    "    uint s62 = M2  + 0x2ad7d2bbu;\n"
    "    uint s63 = M9  + 0xeb86d391u;\n"
    "\n"
    "    /* Round 1 — F(b,c,d) = (b&c)|(~b&d). Rotations: 7,12,17,22. */\n"
    "    BF_FF(a,b,c,d, s00, 7);   BF_FF(d,a,b,c, s01,12);\n"
    "    BF_FF(c,d,a,b, s02,17);   BF_FF(b,c,d,a, s03,22);\n"
    "    BF_FF(a,b,c,d, s04, 7);   BF_FF(d,a,b,c, s05,12);\n"
    "    BF_FF(c,d,a,b, s06,17);   BF_FF(b,c,d,a, s07,22);\n"
    "    BF_FF(a,b,c,d, s08, 7);   BF_FF(d,a,b,c, s09,12);\n"
    "    BF_FF(c,d,a,b, s10,17);   BF_FF(b,c,d,a, s11,22);\n"
    "    BF_FF(a,b,c,d, s12, 7);   BF_FF(d,a,b,c, s13,12);\n"
    "    BF_FF(c,d,a,b, s14,17);   BF_FF(b,c,d,a, s15,22);\n"
    "\n"
    "    /* Round 2 — G(b,c,d) = (d&b)|(~d&c). Rotations: 5,9,14,20. */\n"
    "    BF_GG(a,b,c,d, s16, 5);   BF_GG(d,a,b,c, s17, 9);\n"
    "    BF_GG(c,d,a,b, s18,14);   BF_GG(b,c,d,a, s19,20);\n"
    "    BF_GG(a,b,c,d, s20, 5);   BF_GG(d,a,b,c, s21, 9);\n"
    "    BF_GG(c,d,a,b, s22,14);   BF_GG(b,c,d,a, s23,20);\n"
    "    BF_GG(a,b,c,d, s24, 5);   BF_GG(d,a,b,c, s25, 9);\n"
    "    BF_GG(c,d,a,b, s26,14);   BF_GG(b,c,d,a, s27,20);\n"
    "    BF_GG(a,b,c,d, s28, 5);   BF_GG(d,a,b,c, s29, 9);\n"
    "    BF_GG(c,d,a,b, s30,14);   BF_GG(b,c,d,a, s31,20);\n"
    "\n"
    "    /* Round 3 — H(b,c,d) = b^c^d. Rotations: 4,11,16,23. */\n"
    "    BF_HH(a,b,c,d, s32, 4);   BF_HH(d,a,b,c, s33,11);\n"
    "    BF_HH(c,d,a,b, s34,16);   BF_HH(b,c,d,a, s35,23);\n"
    "    BF_HH(a,b,c,d, s36, 4);   BF_HH(d,a,b,c, s37,11);\n"
    "    BF_HH(c,d,a,b, s38,16);   BF_HH(b,c,d,a, s39,23);\n"
    "    BF_HH(a,b,c,d, s40, 4);   BF_HH(d,a,b,c, s41,11);\n"
    "    BF_HH(c,d,a,b, s42,16);   BF_HH(b,c,d,a, s43,23);\n"
    "    BF_HH(a,b,c,d, s44, 4);   BF_HH(d,a,b,c, s45,11);\n"
    "    BF_HH(c,d,a,b, s46,16);   BF_HH(b,c,d,a, s47,23);\n"
    "\n"
    "    /* Round 4 — I(b,c,d) = c ^ (~d | b). Rotations: 6,10,15,21. */\n"
    "    BF_II(a,b,c,d, s48, 6);   BF_II(d,a,b,c, s49,10);\n"
    "    BF_II(c,d,a,b, s50,15);   BF_II(b,c,d,a, s51,21);\n"
    "    BF_II(a,b,c,d, s52, 6);   BF_II(d,a,b,c, s53,10);\n"
    "    BF_II(c,d,a,b, s54,15);   BF_II(b,c,d,a, s55,21);\n"
    "    BF_II(a,b,c,d, s56, 6);   BF_II(d,a,b,c, s57,10);\n"
    "    BF_II(c,d,a,b, s58,15);   BF_II(b,c,d,a, s59,21);\n"
    "    BF_II(a,b,c,d, s60, 6);   BF_II(d,a,b,c, s61,10);\n"
    "    BF_II(c,d,a,b, s62,15);   BF_II(b,c,d,a, s63,21);\n"
    "\n"
    "    /* Add into chaining state. */\n"
    "    *h0 += a; *h1 += b; *h2 += c; *h3 += d;\n"
    "}\n"
    "\n"
    "/* template_init: install algorithm IV into state. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (64) byte block.\n"
    " * `block` points into the working buffer at the absorb position;\n"
    " * the caller must guarantee >=64 bytes are readable. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* MD5 reads message words little-endian. */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md5_compress_inline(&st->h[0], &st->h[1], &st->h[2], &st->h[3],\n"
    "                        M[0],  M[1],  M[2],  M[3],\n"
    "                        M[4],  M[5],  M[6],  M[7],\n"
    "                        M[8],  M[9],  M[10], M[11],\n"
    "                        M[12], M[13], M[14], M[15]);\n"
    "}\n"
    "\n"
    "/* template_finalize: process the tail, append the 0x80 padding marker\n"
    " * + length-in-bits, and absorb. Caller passes the full buffer; we run\n"
    " * complete blocks then build the final padded block(s) here. After\n"
    " * return, st->h[0..HASH_WORDS-1] holds the final digest words.\n"
    " *\n"
    " * A2 (this rev): each call to md5_block has been replaced by\n"
    " * md5_compress_inline(...) with the 16 message words passed BY VALUE.\n"
    " * Byte-exact behavior with A1 (verified via the BF correctness gate\n"
    " * V1.9.A2.1). The compiler is now free to keep state + M in registers\n"
    " * across the round chain instead of round-tripping through __private\n"
    " * memory at the noinline call boundary that the prior gpu_common.cl\n"
    " * md5_block imposed. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Process complete 64-byte blocks. Build M[] directly from\n"
    "     * bytes (no intermediate pad[]). Identical to md5_buf's main loop. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_compress_inline(&st->h[0], &st->h[1], &st->h[2], &st->h[3],\n"
    "                            M[0],  M[1],  M[2],  M[3],\n"
    "                            M[4],  M[5],  M[6],  M[7],\n"
    "                            M[8],  M[9],  M[10], M[11],\n"
    "                            M[12], M[13], M[14], M[15]);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    /* Build final block(s): tail bytes + 0x80 marker + zeros + length.\n"
    "     * Same direct-into-M[] approach as md5_buf — no intermediate uchar\n"
    "     * pad[]. */\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Copy remaining tail bytes into M[] little-endian. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker. */\n"
    "    M[rem >> 2] |= (uint)0x80 << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        /* Length fits in this block. */\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_compress_inline(&st->h[0], &st->h[1], &st->h[2], &st->h[3],\n"
    "                            M[0],  M[1],  M[2],  M[3],\n"
    "                            M[4],  M[5],  M[6],  M[7],\n"
    "                            M[8],  M[9],  M[10], M[11],\n"
    "                            M[12], M[13], M[14], M[15]);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        md5_compress_inline(&st->h[0], &st->h[1], &st->h[2], &st->h[3],\n"
    "                            M[0],  M[1],  M[2],  M[3],\n"
    "                            M[4],  M[5],  M[6],  M[7],\n"
    "                            M[8],  M[9],  M[10], M[11],\n"
    "                            M[12], M[13], M[14], M[15]);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_compress_inline(&st->h[0], &st->h[1], &st->h[2], &st->h[3],\n"
    "                            M[0],  M[1],  M[2],  M[3],\n"
    "                            M[4],  M[5],  M[6],  M[7],\n"
    "                            M[8],  M[9],  M[10], M[11],\n"
    "                            M[12], M[13], M[14], M[15]);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the digest as 32-byte\n"
    " * hex ASCII and rehash. Algorithm-specific because the\n"
    " * digest geometry differs. Mirrors gpu_md5_rules.cl rev 1.28's iter\n"
    " * loop exactly so byte-exact.\n"
    " *\n"
    " * B7.7a (2026-05-07): MD5UC variant via algo_mode. The CPU iter loop\n"
    " * (mdxfind.c MDstart) selects prmd5UC vs prmd5 based on\n"
    " * job->op == JOB_MD5UC at every iter step, so the inter-iter hex\n"
    " * encoding is uppercase for JOB_MD5UC. Iter=1 is byte-exact between\n"
    " * MD5 and MD5UC (the UC path only fires inter-iter). The\n"
    " * GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE define (set ONLY in this core\n"
    " * and gpu_md5_core.cl) extends the signature to accept algo_mode;\n"
    " * gpu_template.cl uses an #ifdef at the call site to invoke the\n"
    " * right shape. Other cores' template_iterate stay at the legacy\n"
    " * `(st)` signature.\n"
    " *\n"
    " * algo_mode == 0: lowercase hex (JOB_MD5 — default).\n"
    " * algo_mode == 1: uppercase hex (JOB_MD5UC). */\n"
    "#define GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE 1\n"
    "static inline void template_iterate(template_state *st, uint algo_mode)\n"
    "{\n"
    "    uint M[16];\n"
    "    if (algo_mode == 1u) {\n"
    "        md5_to_hex_uc(st->h[0], st->h[1], st->h[2], st->h[3], M);\n"
    "    } else {\n"
    "        md5_to_hex_lc(st->h[0], st->h[1], st->h[2], st->h[3], M);\n"
    "    }\n"
    "    M[8] = 0x80u;\n"
    "    for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 32u * 8u;     /* 32 hex chars = 256 bits */\n"
    "    M[15] = 0u;\n"
    "    /* Reinitialize state to IV, then absorb the prepared M[]. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    md5_compress_inline(&st->h[0], &st->h[1], &st->h[2], &st->h[3],\n"
    "                        M[0],  M[1],  M[2],  M[3],\n"
    "                        M[4],  M[5],  M[6],  M[7],\n"
    "                        M[8],  M[9],  M[10], M[11],\n"
    "                        M[12], M[13], M[14], M[15]);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the final\n"
    " * digest. On a hit, *out_idx is set to the matched target's hash_data\n"
    " * index (mirrors probe_compact_idx semantics). Return 1 on hit, 0 on\n"
    " * miss. Identical to gpu_md5_core.cl's probe wrapper. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit into the global hits buffer. Wraps\n"
    " * EMIT_HIT_4 (MD5 = 4 uint32 digest words). The template body invokes\n"
    " * this through the algorithm core so HASH_WORDS-specific EMIT_HIT_N\n"
    " * macros stay encapsulated. Input order matches md5_rules_phase0's\n"
    " * EMIT_HIT_4 call site. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. Wraps EMIT_HIT_4_DEDUP_OR_OVERFLOW\n"
    " * to keep the hashes_shown[] dedup bit consistent across overflow\n"
    " * re-issues (see gpu_common.cl §B3 protocol notes). The macro takes\n"
    " * the dedup state (hashes_shown ptr, matched_idx, dedup_mask) PLUS\n"
    " * the overflow channel (ovr_set, ovr_gid, lane_gid). The kernel must\n"
    " * NOT pre-set the dedup bit; the macro does that atomically. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
