/* Auto-generated from gpu_sha384_core.cl -- do not edit */
static const char gpu_sha384_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sha384_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha384_core.cl — SHA384 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 1).\n"
    " *\n"
    " * SHA384 uses the SAME compression function as SHA512 — only the IV\n"
    " * and the output truncation differ:\n"
    " *   - IV: 8 distinct ulong constants (FIPS 180-4 §5.3.4)\n"
    " *   - Output: first 6 of 8 state words (384 bits = 6 × 64 = 12 × 32)\n"
    " *\n"
    " * Mirrors gpu_sha224_core.cl rev 1.2 (the analogous SHA256→SHA224\n"
    " * truncation pattern), scaled to 64-bit state and 128-byte blocks.\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (12 for SHA384;\n"
    " *                        truncates 6 ulong = 12 uint32)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (128, same as SHA512)\n"
    " *   template_state     — 8 × ulong INTERNAL chaining + 12 × uint exposed\n"
    " *                        digest. The 8th & 7th internal ulong (state[6],\n"
    " *                        state[7]) participate in compression but are\n"
    " *                        DROPPED from h[]: only state[0..5] decompose\n"
    " *                        into h[0..11].\n"
    " *   template_init      — install SHA384 IV (8 distinct ulong values)\n"
    " *   template_transform — same as SHA512 (BIG-ENDIAN ulong block load)\n"
    " *   template_finalize  — same compression loop as SHA512; 128-bit length\n"
    " *                        encoding; only state[0..5] decompose into h[]\n"
    " *   template_iterate   — re-hash digest as 96-byte hex_lc (-i loop;\n"
    " *                        96 hex chars + 0x80 + 16 length = 113 bytes\n"
    " *                        > 128? NO — 113 ≤ 128: single-block iter,\n"
    " *                        with 0x80 at byte 96, length at M[14..15])\n"
    " *\n"
    " *   ACTUALLY: 96 + 1 + 16 = 113. 113 < 128 ⇒ FITS IN ONE BLOCK.\n"
    " *   But 96 hex bytes occupy M[0..11] (12 ulong = 96 bytes); M[12..13]\n"
    " *   are zero-pad; M[14..15] are length. The 0x80 marker lands at\n"
    " *   byte 96, which is M[12] high octet ⇒ M[12] = 0x8000000000000000UL.\n"
    " *   So actually layout is:\n"
    " *     M[0..11] = 96 hex bytes packed BE\n"
    " *     M[12] = 0x8000000000000000UL (0x80 at byte 96)\n"
    " *     M[13] = 0\n"
    " *     M[14] = 0 (high 64 bits of length)\n"
    " *     M[15] = 96 * 8 = 768 (low 64 bits)\n"
    " *   Single block. Different from SHA512's two-block iter.\n"
    " *\n"
    " *   template_digest_compare — probe leading 16 bytes (h[0..3], LE uint32\n"
    " *                             pairs from state[0..1])\n"
    " *   template_emit_hit       — EMIT_HIT_12 wrapper (12 LE uint32 from\n"
    " *                             state[0..5])\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha384_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides sha512_block(), bswap64, EMIT_HIT_12{,_DEDUP_OR_OVERFLOW},\n"
    " * and probe_compact_idx. We do NOT use sha512_to_hex_lc directly because\n"
    " * SHA384's hex iter writes only 96 bytes (12 ulong) — sha512_to_hex_lc\n"
    " * writes 16 ulong (128 bytes); an inline 12-word version is provided.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final state[0..7] (after compression) is BIG-ENDIAN. h[] holds\n"
    " *     LE-byteswapped uint32 pairs from state[0..5] only. state[6..7]\n"
    " *     are not exposed to the template body but participate in chaining.\n"
    " *   - template_emit_hit writes 12 LE uint32 to the hits buffer.\n"
    " *\n"
    " * R1 mitigation: single private buffer pattern. R2: same compression\n"
    " * footprint as SHA512 (W[80] schedule, 80 × 8 = 640 bytes scratch),\n"
    " * minus 4 uint32 (h[12..15] not allocated). Expected priv_mem_size on\n"
    " * gfx1201 ~ same as SHA512.\n"
    " *\n"
    " * Why a separate file (vs sharing sha512_block via #include): the SHA384\n"
    " * core only needs a different IV and a smaller h[] decomposition.\n"
    " * Inlining the entire compression body would duplicate ~80 lines vs\n"
    " * keeping the sha512_block primitive in gpu_common.cl and just changing\n"
    " * IV + output. The factoring sha512_block-as-shared-primitive is the\n"
    " * cleaner option; this file consumes it directly.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key (R3 fix) hashes the defines_str\n"
    " * \"HASH_WORDS=12,HASH_BLOCK_BYTES=128\" alongside source text so SHA384\n"
    " * gets a distinct cache entry from SHA512 (HASH_WORDS=16). Same source\n"
    " * text + different defines is the same setup as SHA224/SHA256. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 12\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 128\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct. SHA384 carries 8 × uint64 chaining INTERNALLY\n"
    " * (state[]) — same as SHA512's compression. Output truncates to 6 ulong\n"
    " * = 12 uint32 in h[]. The 7th & 8th ulong (state[6], state[7]) are\n"
    " * NEVER exposed; they exist only to feed sha512_block correctly. */\n"
    "typedef struct {\n"
    "    ulong state[8];   /* internal compression state, BIG-ENDIAN */\n"
    "    uint  h[HASH_WORDS]; /* exposed digest words, LE-byteswapped uint32 (12 only) */\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install SHA384 IV.\n"
    " * Standard SHA-384 initial hash values (FIPS 180-4 §5.3.4). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->state[0] = 0xcbbb9d5dc1059ed8UL;\n"
    "    st->state[1] = 0x629a292a367cd507UL;\n"
    "    st->state[2] = 0x9159015a3070dd17UL;\n"
    "    st->state[3] = 0x152fecd8f70e5939UL;\n"
    "    st->state[4] = 0x67332667ffc00b31UL;\n"
    "    st->state[5] = 0x8eb44a8768581511UL;\n"
    "    st->state[6] = 0xdb0c2e0d64f98fa7UL;\n"
    "    st->state[7] = 0x47b5481dbefa4fa4UL;\n"
    "}\n"
    "\n"
    "/* Internal helper: decompose state[0..5] (BE ulong) into h[0..11]\n"
    " * (LE uint32 pairs). state[6..7] dropped per SHA384 truncation. */\n"
    "static inline void template_state_to_h(template_state *st) {\n"
    "    for (int i = 0; i < 6; i++) {\n"
    "        ulong s = bswap64(st->state[i]);\n"
    "        st->h[i*2]   = (uint)s;\n"
    "        st->h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (128) byte block.\n"
    " * Same compression as SHA512. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    ulong M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 8;\n"
    "        M[j] = ((ulong)block[b]     << 56)\n"
    "             | ((ulong)block[b + 1] << 48)\n"
    "             | ((ulong)block[b + 2] << 40)\n"
    "             | ((ulong)block[b + 3] << 32)\n"
    "             | ((ulong)block[b + 4] << 24)\n"
    "             | ((ulong)block[b + 5] << 16)\n"
    "             | ((ulong)block[b + 6] << 8)\n"
    "             |  (ulong)block[b + 7];\n"
    "    }\n"
    "    sha512_block(&st->state[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: identical to SHA512 finalize for compression and\n"
    " * 128-bit length encoding; only the post-compression state-to-h\n"
    " * decomposition differs (truncates to 12 uint32 instead of 16). */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    ulong M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 8;\n"
    "            M[j] = ((ulong)data[b]     << 56)\n"
    "                 | ((ulong)data[b + 1] << 48)\n"
    "                 | ((ulong)data[b + 2] << 40)\n"
    "                 | ((ulong)data[b + 3] << 32)\n"
    "                 | ((ulong)data[b + 4] << 24)\n"
    "                 | ((ulong)data[b + 5] << 16)\n"
    "                 | ((ulong)data[b + 6] << 8)\n"
    "                 |  (ulong)data[b + 7];\n"
    "        }\n"
    "        sha512_block(&st->state[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..127 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 3;\n"
    "        int bi = 7 - (i & 7);\n"
    "        M[wi] |= ((ulong)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 3;\n"
    "        int bi = 7 - (rem & 7);\n"
    "        M[wi] |= ((ulong)0x80UL) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 112) {\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    } else {\n"
    "        sha512_block(&st->state[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    }\n"
    "\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. SHA384 hex output is 96 lowercase\n"
    " * hex chars (48 digest bytes × 2). 96 + 1 (0x80) + 16 (length) = 113\n"
    " * bytes — fits in one HASH_BLOCK_BYTES (128) block.\n"
    " *\n"
    " * Layout:\n"
    " *   M[0..11] = 96 hex bytes packed BE into 12 ulong words (each ulong\n"
    " *              holds 8 hex chars BE)\n"
    " *   M[12]    = 0x8000000000000000UL  (0x80 marker at byte 96)\n"
    " *   M[13]    = 0\n"
    " *   M[14]    = 0 (high 64 bits of bit count)\n"
    " *   M[15]    = 96 * 8 = 768 (low 64 bits of bit count)\n"
    " *\n"
    " * Inlined per-byte hex encoder over state[0..5] only (12 words instead\n"
    " * of sha512_to_hex_lc's 16). */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    ulong M[16];\n"
    "    /* Encode 6 state words → 12 hex ulong words. Same byte-by-byte\n"
    "     * pattern as sha512_to_hex_lc (gpu_common.cl line 780) but limited\n"
    "     * to 6 input words. */\n"
    "    for (int i = 0; i < 6; i++) {\n"
    "        ulong s = st->state[i];\n"
    "        uint b0 = (uint)((s >> 56) & 0xff), b1 = (uint)((s >> 48) & 0xff);\n"
    "        uint b2 = (uint)((s >> 40) & 0xff), b3 = (uint)((s >> 32) & 0xff);\n"
    "        uint b4 = (uint)((s >> 24) & 0xff), b5 = (uint)((s >> 16) & 0xff);\n"
    "        uint b6 = (uint)((s >> 8)  & 0xff), b7 = (uint)(s & 0xff);\n"
    "        M[i*2]   = (hex_byte_be64(b0) << 48) | (hex_byte_be64(b1) << 32)\n"
    "                  | (hex_byte_be64(b2) << 16) | hex_byte_be64(b3);\n"
    "        M[i*2+1] = (hex_byte_be64(b4) << 48) | (hex_byte_be64(b5) << 32)\n"
    "                  | (hex_byte_be64(b6) << 16) | hex_byte_be64(b7);\n"
    "    }\n"
    "    M[12] = 0x8000000000000000UL;   /* 0x80 BE at byte position 96 */\n"
    "    M[13] = 0UL;\n"
    "    M[14] = 0UL;                    /* high 64 bits of bit count */\n"
    "    M[15] = 96UL * 8UL;             /* 96 hex chars = 768 bits */\n"
    "\n"
    "    /* Reset state to SHA384 IV; absorb the hex block. */\n"
    "    st->state[0] = 0xcbbb9d5dc1059ed8UL;\n"
    "    st->state[1] = 0x629a292a367cd507UL;\n"
    "    st->state[2] = 0x9159015a3070dd17UL;\n"
    "    st->state[3] = 0x152fecd8f70e5939UL;\n"
    "    st->state[4] = 0x67332667ffc00b31UL;\n"
    "    st->state[5] = 0x8eb44a8768581511UL;\n"
    "    st->state[6] = 0xdb0c2e0d64f98fa7UL;\n"
    "    st->state[7] = 0x47b5481dbefa4fa4UL;\n"
    "    sha512_block(&st->state[0], M);\n"
    "\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe leading 16 bytes (h[0..3]). Same\n"
    " * convention as SHA512 — h[] is already LE-decomposed. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: EMIT_HIT_12 (SHA384 = 12 uint32 = 6 ulong LE\n"
    " * decomposed). state[6..7] dropped per SHA384 truncation. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_12((hits), (hit_count), (max_hits), \\\n"
    "                (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_12_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
