/* Auto-generated from gpu_md5crypt_core.cl -- do not edit */
static const char gpu_md5crypt_core_str[] =
    "/* gpu_md5crypt_core.cl -- MD5CRYPT (e511) algorithm extension functions\n"
    " * for the generic dispatch template (Memo B Phase Unix-crypt 1\n"
    " * MD5CRYPT Path A hand-written sibling of the unsalted-template family).\n"
    " *\n"
    " * $Revision: 1.1 $\n"
    " * $Log: gpu_md5crypt_core.cl,v $\n"
    " * Revision 1.1  2026/05/08 13:55:39  dlr\n"
    " * Initial\n"
    " *\n"
    " *\n"
    " * STATUS: MD5CRYPT fan-out 2026-05-08 -- second iterated-crypt salted\n"
    " * algorithm after PHPBB3 on the unified template path. Single algo_mode\n"
    " * (0); no KPASS/KSALT siblings -- JOB_MD5CRYPT (e511) is a single-mode\n"
    " * algorithm with a FIXED 1000-iteration count (vs PHPBB3's salt-carried\n"
    " * variable count). First Phase 1 of the Unix-crypt ladder\n"
    " * (MD5CRYPT -> SHA256CRYPT -> SHA512CRYPT -> SHA512CRYPTMD5).\n"
    " *\n"
    " * MD5CRYPT / BSD $1$ md5crypt semantics (mirrors mdxfind.c JOB_MD5CRYPT\n"
    " * at lines 13017-13117 + slab oracle gpu_md5crypt.cl):\n"
    " *\n"
    " *   salt buffer (4..12 bytes total): \"$1$<salt>$\" -- variable-length\n"
    " *   raw_salt = salt_bytes[3..3+saltlen-1] where saltlen <= 8\n"
    " *\n"
    " *   STEP 1: digest_b = MD5(pass || raw_salt || pass)\n"
    " *   STEP 2: digest_a = MD5(pass || \"$1$\" || raw_salt\n"
    " *                          || digest_b chunked-by-16 for plen bytes\n"
    " *                          || bit_byte: pass[0] if (len bit) else 0,\n"
    " *                                       repeating until len reaches 0)\n"
    " *   STEP 3: 1000 iterations\n"
    " *           for x in 0..999:\n"
    " *             buf = (x&1) ? pass : prev_state[16]\n"
    " *             if (x % 3) buf ||= raw_salt\n"
    " *             if (x % 7) buf ||= pass\n"
    " *             buf ||= (x&1) ? prev_state[16] : pass\n"
    " *             state = MD5(buf)\n"
    " *\n"
    " *   probe state once at the end (matches CPU semantics at mdxfind.c:13071\n"
    " *   which calls hybrid_check(curin.h, 16, ...) AFTER the for-loop).\n"
    " *\n"
    " * DESIGN: iter loop INSIDE template_finalize, max_iter=1.\n"
    " * --------------------------------------------------------\n"
    " * Mirrors PHPBB3 + SHA1DRU pattern (B6.11 precedent):\n"
    " *   - iteration count is INTERNAL to the algorithm (FIXED 1000 here,\n"
    " *     vs salt-carried in PHPBB3), NOT user-controlled via -i;\n"
    " *   - only the FINAL state is probed (CPU semantics);\n"
    " *   - host forces params.max_iter = 1 at the rules-engine pack site\n"
    " *     so the kernel's outer iter loop runs exactly once and never\n"
    " *     calls template_iterate (which is a stub).\n"
    " *\n"
    " * Salt-axis carrier: this kernel routes through the salted-template\n"
    " * scaffolding (GPU_TEMPLATE_HAS_SALT=1, SALT_POSITION=PREPEND in\n"
    " * defines_str). The salt buffer carries the FULL \"$1$<salt>$\" prefix\n"
    " * (mdxfind.c:40635 stores prefixlen bytes via store_typesalt(JOB_-\n"
    " * MD5CRYPT, line, prefixlen)). gpu_pack_salts is called with\n"
    " * use_hashsalt=0, so salt_buf+salt_off[i] points at the raw \"$1$<salt>$\"\n"
    " * prefix and salt_lens[i] is variable (5..12 bytes).\n"
    " *\n"
    " * Inside the kernel:\n"
    " *   - salt_bytes[0..2]  -> \"$1$\" prefix (used in step 2 verbatim)\n"
    " *   - salt_bytes[3..]   -> raw salt (terminated by '$' or end of buffer)\n"
    " *\n"
    " * Validation oracle: gpu_md5crypt.cl md5crypt_batch (slab kernel; this\n"
    " * file is a port of that body into the template extension API).\n"
    " * Differences:\n"
    " *   - reads pass from `data` (post-rule buf passed by template; PRIVATE\n"
    " *     uchar *) rather than from a packed wordbuf indexed by tid (slab's\n"
    " *     `__global const uchar *pass`);\n"
    " *   - reads salt from `salt_bytes` (the global salt buffer threaded by\n"
    " *     gpu_template.cl under GPU_TEMPLATE_HAS_SALT) rather than from\n"
    " *     the slab's own salts/salt_offsets/salt_lens trio.\n"
    " *\n"
    " * The slab oracle uses uchar buf[256] + md5_oneshot helper for variable-\n"
    " * length inputs that span multiple MD5 blocks. We mirror that approach\n"
    " * here -- the worst-case input is len + saltlen + len = 39 + 8 + 39 = 86\n"
    " * bytes for step 1, and similar for step 2/iter steps, so multi-block\n"
    " * MD5 absorption is required (a single MD5 block holds 55 message bytes\n"
    " * before length-encoding kicks in).\n"
    " *\n"
    " * Hit replay: host calls hybrid_check(curin.h, 16, ...) and reconstructs\n"
    " * \"$1$<salt>$<22-char-phpitoa64>\" via md5crypt_b64encode (existing\n"
    " * helper at gpujob_opencl.c). Mirrors the slab arm at\n"
    " * gpujob_opencl.c:1723 byte-for-byte.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single private\n"
    " * buffer pattern. uchar buf[128] working buffer + 4-uint chaining state\n"
    " * are private; salt_bytes is __global (read byte-by-byte into buf via\n"
    " * inline byte loops -- no addrspace casts).\n"
    " *\n"
    " * R2 (register pressure): one uchar buf[128] + 4-uint state + a small\n"
    " * iter counter. Comparable to PHPBB3 plus the longer working buffer\n"
    " * (PHPBB3's two-block-cap kernel doesn't need a uchar buffer). Expected\n"
    " * priv_mem on Pascal in the 41-44 KB band shared by other unified-\n"
    " * template dispatches.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_md5crypt_core_str,\n"
    " *     gpu_template_str ]\n"
    " *\n"
    " * Cache key (R3): defines_str =\n"
    " *   \"HASH_WORDS=4,HASH_BLOCK_BYTES=64,HAS_SALT=1,SALT_POSITION=PREPEND,\n"
    " *    BASE_ALGO=md5crypt\"\n"
    " *\n"
    " * Cache-key disambiguation:\n"
    " *   - From MD5SALT family (HASH_WORDS=4 + HAS_SALT=1 + BASE_ALGO=md5)\n"
    " *     by BASE_ALGO=md5crypt axis.\n"
    " *   - From PHPBB3 (HASH_WORDS=4 + HAS_SALT=1 + BASE_ALGO=phpbb3)\n"
    " *     by BASE_ALGO=md5crypt axis.\n"
    " *   - From every other salted/unsalted template via the unique\n"
    " *     BASE_ALGO=md5crypt token.\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: MD5 carries 4 uint32 chaining values (LE). */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install MD5 IV into state. Same IV as gpu_md5_core.cl. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: stub for interface symmetry. MD5CRYPT's\n"
    " * template_finalize manages multi-block absorption inline -- never\n"
    " * routes through this. Provided for completeness (matches PHPBB3\n"
    " * pattern). */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b])\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* md5crypt_oneshot: compute MD5(buf[0..buflen-1]) and write 4-uint LE\n"
    " * digest to out[0..3]. Handles variable-length input up to 119 bytes\n"
    " * (max two-block absorb plus length encoding; padding consumes 1 byte\n"
    " * marker plus 8 bytes length, leaving 55 + 64 = 119 bytes max).\n"
    " *\n"
    " * Mirrors slab gpu_md5crypt.cl:md5_oneshot byte-for-byte (uchar pad[]\n"
    " * staging + LE M[] pack + md5_block per absorbed block).\n"
    " *\n"
    " * Worst-case input lengths in MD5CRYPT:\n"
    " *   step 1 (pass+salt+pass):       39 + 8 + 39 = 86 bytes (2 blocks)\n"
    " *   step 2 (pass+\"$1$\"+salt+...): 39 + 3 + 8 + 39 + ~32 (bit bytes) = ~121 cap\n"
    " *                                  But bit_bytes = log2(plen)+1 so for\n"
    " *                                  plen <= 39 that's at most 6 extra bytes.\n"
    " *                                  Actual worst-case: 39+3+8+\n"
    " *                                  ceil(39/16)*16 + 6 = 39+3+8+48+6 = 104.\n"
    " *   step 3 iter (pass+salt+pass+pass): 39+8+39+39 = 125 bytes (3 blocks?)\n"
    " *                                  Actually: max iteration buf is pass+salt+\n"
    " *                                  pass+digest_or_pass = 39+8+39+39 = 125,\n"
    " *                                  OR digest+salt+pass+digest = 16+8+39+16 = 79.\n"
    " *\n"
    " * For a 3-block input the absorb requires absorbing two 64-byte blocks\n"
    " * before the final padded block. Max input we handle: 191 bytes\n"
    " * (3 absorbs, padding fits in 64-1-8 = 55 of the third block).\n"
    " *\n"
    " * Defensive: cap buflen at 191 on entry (kernel must not pass longer).\n"
    " */\n"
    "static inline void md5crypt_oneshot(const uchar *buf, int buflen, uint *out)\n"
    "{\n"
    "    uint M[16];\n"
    "    out[0] = 0x67452301u;\n"
    "    out[1] = 0xEFCDAB89u;\n"
    "    out[2] = 0x98BADCFEu;\n"
    "    out[3] = 0x10325476u;\n"
    "\n"
    "    if (buflen > 191) buflen = 191;\n"
    "\n"
    "    int pos = 0;\n"
    "    /* Process complete 64-byte blocks. */\n"
    "    while (pos + 64 <= buflen) {\n"
    "        for (int i = 0; i < 16; i++) {\n"
    "            int b = pos + i * 4;\n"
    "            M[i] = ((uint)buf[b])\n"
    "                 | ((uint)buf[b + 1] << 8)\n"
    "                 | ((uint)buf[b + 2] << 16)\n"
    "                 | ((uint)buf[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(&out[0], &out[1], &out[2], &out[3], M);\n"
    "        pos += 64;\n"
    "    }\n"
    "\n"
    "    /* Final block(s): build a uchar pad[128] tail with the remaining\n"
    "     * bytes + 0x80 marker + zeros + length. May span 1 or 2 blocks\n"
    "     * depending on rem. */\n"
    "    uchar pad[128];\n"
    "    for (int i = 0; i < 128; i++) pad[i] = 0;\n"
    "    int rem = buflen - pos;\n"
    "    for (int i = 0; i < rem; i++) pad[i] = buf[pos + i];\n"
    "    pad[rem] = 0x80u;\n"
    "\n"
    "    int blocks = (rem < 56) ? 1 : 2;\n"
    "    int lenoff = (blocks == 1) ? 56 : 120;\n"
    "    /* Length in bits (4-byte LE; high 4 bytes stay zero -- buflen <=\n"
    "     * 191 fits in 32 bits). */\n"
    "    pad[lenoff]     = (uchar)((buflen * 8) & 0xff);\n"
    "    pad[lenoff + 1] = (uchar)(((buflen * 8) >> 8) & 0xff);\n"
    "    pad[lenoff + 2] = (uchar)(((buflen * 8) >> 16) & 0xff);\n"
    "    pad[lenoff + 3] = (uchar)(((buflen * 8) >> 24) & 0xff);\n"
    "\n"
    "    for (int b = 0; b < blocks; b++) {\n"
    "        for (int i = 0; i < 16; i++) {\n"
    "            int x = b * 64 + i * 4;\n"
    "            M[i] = ((uint)pad[x])\n"
    "                 | ((uint)pad[x + 1] << 8)\n"
    "                 | ((uint)pad[x + 2] << 16)\n"
    "                 | ((uint)pad[x + 3] << 24);\n"
    "        }\n"
    "        md5_block(&out[0], &out[1], &out[2], &out[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_finalize: full MD5CRYPT chain (3 steps + 1000-iter loop).\n"
    " *\n"
    " * Step 1: digest_b = MD5(pass || raw_salt || pass)\n"
    " * Step 2: digest_a = MD5(pass || \"$1$\" || raw_salt\n"
    " *                        || digest_b-chunked-by-16-for-plen-bytes\n"
    " *                        || bit-loop-bytes)\n"
    " * Step 3: 1000 iterations of variable-shape MD5(buf) per CPU at\n"
    " *         mdxfind.c:13057-13066.\n"
    " *\n"
    " * Final state in st->h[0..3] (4 LE uint32 = 16 binary bytes), probed\n"
    " * by template_digest_compare.\n"
    " *\n"
    " * Password length cap: matches CPU's handling -- typical mdxfind\n"
    " * passwords are <= 39 bytes by default (see gpu_maxlen_val derivation).\n"
    " * Defensive cap below clamps plen to 39 so the working buffer never\n"
    " * exceeds the md5crypt_oneshot 191-byte cap.\n"
    " *\n"
    " * algo_mode: MD5CRYPT has only one mode. The arg is unused; kept for\n"
    " * interface symmetry with the salted-template signature. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "                                     , __global const uchar *salt_bytes\n"
    "                                     , uint salt_len\n"
    "                                     , uint algo_mode\n"
    "#endif\n"
    "                                     )\n"
    "{\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    (void)algo_mode;\n"
    "\n"
    "    /* Defensive: clamp plen at 39 (mdxfind default max) so buffer\n"
    "     * lengths stay within md5crypt_oneshot's 191-byte cap. */\n"
    "    int plen = len;\n"
    "    if (plen > 39) plen = 39;\n"
    "\n"
    "    /* Extract raw salt: salt_bytes points at \"$1$<salt>$\"; raw salt\n"
    "     * starts at byte 3, ends at next '$' or salt_len. Cap at 8.\n"
    "     * Mirrors slab gpu_md5crypt.cl:64-67 and CPU mdxfind.c:13039-13042. */\n"
    "    int saltlen = 0;\n"
    "    if (salt_len >= 4) {\n"
    "        int max_scan = (int)salt_len - 3;\n"
    "        if (max_scan > 8) max_scan = 8;\n"
    "        for (int i = 0; i < max_scan; i++) {\n"
    "            uchar c = salt_bytes[3 + i];\n"
    "            if (c == 0 || c == '$') break;\n"
    "            saltlen++;\n"
    "        }\n"
    "    }\n"
    "    if (saltlen > 8) saltlen = 8;\n"
    "\n"
    "    /* Working buffer: max input 125 bytes (step 3 iter worst case);\n"
    "     * round to 192 to leave headroom for the md5crypt_oneshot cap. */\n"
    "    uchar buf[192];\n"
    "\n"
    "    /* === STEP 1: digest_b = MD5(pass || raw_salt || pass) === */\n"
    "    int blen = 0;\n"
    "    for (int i = 0; i < plen; i++)    buf[blen++] = data[i];\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_bytes[3 + i];\n"
    "    for (int i = 0; i < plen; i++)    buf[blen++] = data[i];\n"
    "\n"
    "    uint digest[4];\n"
    "    md5crypt_oneshot(buf, blen, digest);\n"
    "\n"
    "    /* digest_b: 16 binary bytes of step-1 digest in LE byte order. */\n"
    "    uchar digest_b[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        digest_b[i * 4]     = (uchar)(digest[i] & 0xffu);\n"
    "        digest_b[i * 4 + 1] = (uchar)((digest[i] >> 8) & 0xffu);\n"
    "        digest_b[i * 4 + 2] = (uchar)((digest[i] >> 16) & 0xffu);\n"
    "        digest_b[i * 4 + 3] = (uchar)((digest[i] >> 24) & 0xffu);\n"
    "    }\n"
    "\n"
    "    /* === STEP 2: digest_a = MD5(pass || \"$1$\" || raw_salt\n"
    "     *                            || digest_b-chunked-by-16-for-plen-bytes\n"
    "     *                            || bit-loop-bytes) === */\n"
    "    blen = 0;\n"
    "    for (int i = 0; i < plen; i++) buf[blen++] = data[i];\n"
    "    buf[blen++] = '$';\n"
    "    buf[blen++] = '1';\n"
    "    buf[blen++] = '$';\n"
    "    for (int i = 0; i < saltlen; i++) buf[blen++] = salt_bytes[3 + i];\n"
    "    /* Append digest_b in 16-byte chunks until plen bytes have been\n"
    "     * appended. Mirrors CPU mdxfind.c:13050-13053 + slab :92-96. */\n"
    "    for (int x = plen; x > 0; x -= 16) {\n"
    "        int n = (x > 16) ? 16 : x;\n"
    "        for (int i = 0; i < n; i++) buf[blen++] = digest_b[i];\n"
    "    }\n"
    "    /* Bit-dependent bytes: for each 1 bit in plen (from LSB), append\n"
    "     * NUL; for each 0 bit, append pass[0]. Mirrors CPU mdxfind.c:13054-\n"
    "     * 13055 + slab :98-99. plen <= 39 means at most 6 iterations. */\n"
    "    for (int x = plen; x != 0; x >>= 1) {\n"
    "        buf[blen++] = (x & 1) ? (uchar)0u : (uchar)data[0];\n"
    "    }\n"
    "    md5crypt_oneshot(buf, blen, digest);\n"
    "\n"
    "    /* dig: 16 binary bytes of step-2 digest in LE byte order. Updated\n"
    "     * each iter in the 1000-iter loop. */\n"
    "    uchar dig[16];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        dig[i * 4]     = (uchar)(digest[i] & 0xffu);\n"
    "        dig[i * 4 + 1] = (uchar)((digest[i] >> 8) & 0xffu);\n"
    "        dig[i * 4 + 2] = (uchar)((digest[i] >> 16) & 0xffu);\n"
    "        dig[i * 4 + 3] = (uchar)((digest[i] >> 24) & 0xffu);\n"
    "    }\n"
    "\n"
    "    /* === STEP 3: 1000 iterations === */\n"
    "    for (int x = 0; x < 1000; x++) {\n"
    "        blen = 0;\n"
    "        if (x & 1) {\n"
    "            for (int i = 0; i < plen; i++) buf[blen++] = data[i];\n"
    "        } else {\n"
    "            for (int i = 0; i < 16; i++)   buf[blen++] = dig[i];\n"
    "        }\n"
    "        if (x % 3) {\n"
    "            for (int i = 0; i < saltlen; i++) buf[blen++] = salt_bytes[3 + i];\n"
    "        }\n"
    "        if (x % 7) {\n"
    "            for (int i = 0; i < plen; i++) buf[blen++] = data[i];\n"
    "        }\n"
    "        if (x & 1) {\n"
    "            for (int i = 0; i < 16; i++)   buf[blen++] = dig[i];\n"
    "        } else {\n"
    "            for (int i = 0; i < plen; i++) buf[blen++] = data[i];\n"
    "        }\n"
    "        md5crypt_oneshot(buf, blen, digest);\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            dig[i * 4]     = (uchar)(digest[i] & 0xffu);\n"
    "            dig[i * 4 + 1] = (uchar)((digest[i] >> 8) & 0xffu);\n"
    "            dig[i * 4 + 2] = (uchar)((digest[i] >> 16) & 0xffu);\n"
    "            dig[i * 4 + 3] = (uchar)((digest[i] >> 24) & 0xffu);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Install final state into template_state for digest compare + emit. */\n"
    "    st->h[0] = digest[0];\n"
    "    st->h[1] = digest[1];\n"
    "    st->h[2] = digest[2];\n"
    "    st->h[3] = digest[3];\n"
    "    return;\n"
    "#else\n"
    "    /* Defensive fall-through for the !HAS_SALT instantiation. MD5CRYPT\n"
    "     * is always a salted op (the algorithm requires the salt for steps\n"
    "     * 1+2+3); a no-salt build would have nothing to do. Compute MD5(data)\n"
    "     * so the extension interface stays well-formed. */\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "    while ((len - pos) >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b])\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "    int rem = len - pos;\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = (i & 3) * 8;\n"
    "        M[wi] |= ((uint)data[pos + i]) << bi;\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = (rem & 3) * 8;\n"
    "        M[wi] |= ((uint)0x80u) << bi;\n"
    "    }\n"
    "    if (rem < 56) {\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    } else {\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    }\n"
    "#endif\n"
    "}\n"
    "\n"
    "/* template_iterate: STUB. With max_iter = 1 (host-set for MD5CRYPT), the\n"
    " * outer iter loop in template_phase0 runs exactly once and never calls\n"
    " * template_iterate. Mirrors PHPBB3 / SHA1DRU pattern. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    (void)st;\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the 4 MD5 LE\n"
    " * digest words. Identical to gpu_md5_core.cl's template_digest_compare\n"
    " * (MD5CRYPT's final state is in MD5 native LE byte order). */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. MD5CRYPT = 4 LE uint32 digest words\n"
    " * (same wire format as MD5; host's hit-replay arm reconstructs the\n"
    " * \"$1$<salt>$<22>\" string via md5crypt_b64encode). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
