/* Auto-generated from gpu_md5_core.cl -- do not edit */
static const char gpu_md5_core_str[] =
    "/*\n"
    " * $Revision: 1.5 $\n"
    " * $Log: gpu_md5_core.cl,v $\n"
    " * Revision 1.5  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_md5_core.cl — MD5 algorithm extension functions for the generic\n"
    " * dispatch template (Memo B Phase B2).\n"
    " *\n"
    " * This file defines the per-algorithm pieces that the generic template\n"
    " * (gpu_template.cl) calls into:\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (4 for MD5)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64 for MD5)\n"
    " *   template_state     — opaque per-lane state struct\n"
    " *   template_init      — initialize state to algorithm IV\n"
    " *   template_transform — absorb one HASH_BLOCK_BYTES block\n"
    " *   template_finalize  — pad and finalize a buffer; produces final state\n"
    " *   template_digest_compare — probe the compact table from final state and\n"
    " *                             return 1+matched_idx on hit, 0 on miss\n"
    " *   template_iterate   — re-hash the digest as 32-byte hex_lc (-i loop)\n"
    " *\n"
    " * Reuses primitives from gpu_common.cl: md5_block, md5_to_hex_lc,\n"
    " * probe_compact_idx. The kernel proper lives in gpu_template.cl; the\n"
    " * source order at compile time is:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_md5_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_md5_rules_str provides apply_rule() for the rules walker; this\n"
    " * file provides the per-algorithm hooks; gpu_template_str ties them\n"
    " * into the template_phase0 kernel.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - apply_rule + buf in/out is identical to gpu_md5_rules.cl rev 1.28+.\n"
    " *   - md5 padding + multi-block logic is identical to md5_buf in\n"
    " *     gpu_md5_rules.cl (we do not call md5_buf directly to keep this\n"
    " *     file self-contained for future algorithm forks; the bytewise\n"
    " *     equivalence is the byte-exact gate).\n"
    " *   - template_finalize() builds the M[16] message words directly\n"
    " *     from the input bytes (mirrors md5_buf) and calls md5_block()\n"
    " *     once per block. It does NOT route through template_transform()\n"
    " *     — that wrapper exists for the public API but is bypassed in\n"
    " *     the hot path because the byte-buffer round-trip cost it would\n"
    " *     introduce was 12.3% of wall time on Memo B B2's first-cut\n"
    " *     template path. See the comment on template_finalize for detail.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): the template\n"
    " * passes a `__private uchar *buf` and `__private template_state *st`.\n"
    " * No addrspace-cast ternary pointers, no helper that takes a generic\n"
    " * pointer to private state. Pattern matches the safe single-private-\n"
    " * buffer model from gpu_md5_rules.cl r28.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. The template uses these as structural\n"
    " * compile-time constants; the kernel-cache key (gpu_kernel_cache R3\n"
    " * fix) hashes the defines_str (\"HASH_WORDS=4,HASH_BLOCK_BYTES=64\")\n"
    " * alongside the source set so distinct instantiations get distinct\n"
    " * cache entries even though source text would otherwise be identical. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: MD5 carries 4 uint32 chaining values.\n"
    " * SHA1 will carry 5; SHA256 8; SHA384/SHA512 8 ulong. The template\n"
    " * only reads/writes the digest words via template_finalize's output\n"
    " * + template_digest_compare; it does not introspect the struct. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install algorithm IV into state. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (64) byte block.\n"
    " * `block` points into the working buffer at the absorb position;\n"
    " * the caller must guarantee >=64 bytes are readable. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* MD5 reads message words little-endian. */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process the tail, append the 0x80 padding marker\n"
    " * + length-in-bits, and absorb. Caller passes the full buffer; we run\n"
    " * complete blocks then build the final padded block(s) here. After\n"
    " * return, st->h[0..HASH_WORDS-1] holds the final digest words.\n"
    " *\n"
    " * Mirrors md5_buf() in gpu_md5_rules.cl byte-for-byte. We do NOT\n"
    " * route through template_transform() here — instead we build uint\n"
    " * M[16] directly via in-place OR-merge of the input bytes, exactly\n"
    " * as md5_buf does, and call md5_block() once per block.\n"
    " *\n"
    " * Why not use template_transform: the previous version built a\n"
    " * private uchar pad[64] tail block, populated it with 64+rem byte\n"
    " * stores, then handed it to template_transform which read the same\n"
    " * 64 bytes BACK out as little-endian uints into a fresh M[16].\n"
    " * That round-trip (byte-stores -> byte-loads -> uint-pack) was the\n"
    " * 12.3% wall regression vs the legacy md5_buf path on ioblade\n"
    " * (Memo B Phase B2 perf-fix, 2026-05-04). For full blocks the\n"
    " * function-call boundary plus rebuilt-M[] cost is non-trivial too;\n"
    " * for the final block the extra 64-byte zeroing + byte-by-byte\n"
    " * tail copy + 4-byte length store dominates because rem is small\n"
    " * for typical wordlist inputs.\n"
    " *\n"
    " * template_transform() remains exposed as the public extension API\n"
    " * (a future algorithm core might prefer the function-style entry).\n"
    " * For MD5 we ignore it in the hot path. SHA1/SHA256 cores in B4\n"
    " * SHOULD follow this same in-place pattern in their finalize.\n"
    " *\n"
    " * R1 mitigation preserved: single private buffer (just the M[16]\n"
    " * uints + the input data pointer), no addrspace-cast helpers, no\n"
    " * __private uchar* helper that takes a private buffer pointer. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Process complete 64-byte blocks. Build M[] directly from\n"
    "     * bytes (no intermediate pad[]). Identical to md5_buf's main loop. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    /* Build final block(s): tail bytes + 0x80 marker + zeros + length.\n"
    "     * Same direct-into-M[] approach as md5_buf — no intermediate uchar\n"
    "     * pad[]. */\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Copy remaining tail bytes into M[] little-endian. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker. */\n"
    "    M[rem >> 2] |= (uint)0x80 << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        /* Length fits in this block. */\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the digest as 32-byte\n"
    " * hex ASCII and rehash. Algorithm-specific because the\n"
    " * digest geometry differs (MD5: 4 words, 32 chars; SHA1: 5 words,\n"
    " * 40 chars; SHA256: 8 words, 64 chars). For MD5 we mirror\n"
    " * gpu_md5_rules.cl rev 1.28's iter loop exactly so byte-exact.\n"
    " *\n"
    " * B7.7a (2026-05-07): MD5UC variant via algo_mode. The CPU iter loop\n"
    " * (mdxfind.c:25386 MDstart) selects prmd5UC vs prmd5 based on\n"
    " * job->op == JOB_MD5UC at every iter step, so the inter-iter hex\n"
    " * encoding is uppercase for JOB_MD5UC. Iter=1 is byte-exact between\n"
    " * MD5 and MD5UC (the UC path only fires inter-iter). The\n"
    " * GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE define (set ONLY in this core)\n"
    " * extends the signature to accept algo_mode; gpu_template.cl uses an\n"
    " * #ifdef at the call site to invoke the right shape. Other cores'\n"
    " * template_iterate stay at the legacy `(st)` signature.\n"
    " *\n"
    " * algo_mode == 0: lowercase hex (JOB_MD5 — default).\n"
    " * algo_mode == 1: uppercase hex (JOB_MD5UC). */\n"
    "#define GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE 1\n"
    "static inline void template_iterate(template_state *st, uint algo_mode)\n"
    "{\n"
    "    uint M[16];\n"
    "    if (algo_mode == 1u) {\n"
    "        md5_to_hex_uc(st->h[0], st->h[1], st->h[2], st->h[3], M);\n"
    "    } else {\n"
    "        md5_to_hex_lc(st->h[0], st->h[1], st->h[2], st->h[3], M);\n"
    "    }\n"
    "    M[8] = 0x80u;\n"
    "    for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 32u * 8u;     /* 32 hex chars = 256 bits */\n"
    "    M[15] = 0u;\n"
    "    /* Reinitialize state to IV, then absorb the prepared M[]. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the final\n"
    " * digest. On a hit, *out_idx is set to the matched target's hash_data\n"
    " * index (mirrors probe_compact_idx semantics). Return 1 on hit, 0 on\n"
    " * miss.\n"
    " *\n"
    " * Wrapper around probe_compact_idx — the template body calls this to\n"
    " * stay algorithm-agnostic about which words of the digest form the\n"
    " * (hx, hy, hz, hw) probe key. For MD5 it's the first 4 uint words.\n"
    " * SHA1 will have a 5-word variant; SHA256 will pull (h[0]..h[3]) for\n"
    " * the same 16-byte probe geometry (compact table is keyed on the\n"
    " * leading 16 bytes regardless of algorithm digest length). */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit into the global hits buffer. Wraps\n"
    " * EMIT_HIT_4 (MD5 = 4 uint32 digest words). The template body invokes\n"
    " * this through the algorithm core so HASH_WORDS-specific EMIT_HIT_N\n"
    " * macros stay encapsulated. Input order matches md5_rules_phase0's\n"
    " * EMIT_HIT_4 call site. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. Wraps EMIT_HIT_4_DEDUP_OR_OVERFLOW\n"
    " * to keep the hashes_shown[] dedup bit consistent across overflow\n"
    " * re-issues (see gpu_common.cl §B3 protocol notes). The macro takes\n"
    " * the dedup state (hashes_shown ptr, matched_idx, dedup_mask) PLUS\n"
    " * the overflow channel (ovr_set, ovr_gid, lane_gid). The kernel must\n"
    " * NOT pre-set the dedup bit; the macro does that atomically. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
