/* Auto-generated from gpu_sha224_core.cl -- do not edit */
static const char gpu_sha224_core_str[] =
    "/*\n"
    " * $Revision: 1.3 $\n"
    " * $Log: gpu_sha224_core.cl,v $\n"
    " * Revision 1.3  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha224_core.cl — SHA224 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B4 fan-out).\n"
    " *\n"
    " * Mirrors gpu_sha256_core.cl rev 1.1 structure. SHA224 uses the same\n"
    " * compression function as SHA256 — only the IV and the output truncation\n"
    " * differ:\n"
    " *   - IV: 8 distinct constants (FIPS 180-4 §5.3.4)\n"
    " *   - Output: first 7 of 8 state words (224 bits = 7 × 32)\n"
    " *\n"
    " * KEY DIFFERENCE FROM SHA256: HASH_WORDS = 7 (digest output size in\n"
    " * 32-bit words), but the INTERNAL state struct still holds 8 words —\n"
    " * the SHA256 compression function (sha256_block) reads and writes all\n"
    " * 8 chaining values regardless of which output truncation is requested.\n"
    " *\n"
    " * To handle this asymmetry without breaking the template's\n"
    " * `digests_out[gid * HASH_WORDS + i] = st.h[i]` loop (gpu_template.cl\n"
    " * template_phase0_test), the state struct is sized as a literal `uint\n"
    " * h[8]` rather than `uint h[HASH_WORDS]`. The template body only\n"
    " * iterates `i < HASH_WORDS` so it correctly writes 7 words per lane;\n"
    " * the 8th word is internal-only and never crosses the kernel boundary.\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (7 for SHA224)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64 — same as SHA256)\n"
    " *   template_state     — opaque per-lane state struct (8 uint32 chaining;\n"
    " *                        9th-and-beyond never accessed)\n"
    " *   template_init      — install SHA224 IV (8 standard values)\n"
    " *   template_transform — absorb one 64-byte block (BIG-ENDIAN word load)\n"
    " *   template_finalize  — pad and finalize (in-place M[16] pattern)\n"
    " *   template_iterate   — re-hash digest as 56-byte hex_lc (-i loop)\n"
    " *   template_digest_compare — probe compact table with leading 16 bytes\n"
    " *                             (h[0..3], LE-byteswapped)\n"
    " *   template_emit_hit       — EMIT_HIT_7 wrapper (7 LE digest words)\n"
    " *\n"
    " * KEY POINTS:\n"
    " *\n"
    " * 1. State width vs digest width. State struct = 8 uint32 (literal);\n"
    " *    digest output = 7 uint32 words (HASH_WORDS = 7). The 8th word\n"
    " *    (st->h[7]) is the SHA256 'h' chaining value — it participates in\n"
    " *    every compression step but is dropped from the final digest.\n"
    " *\n"
    " * 2. Iter loop. SHA224 hex output is 56 lowercase hex chars. The pad\n"
    " *    fits in the first block: M[14] = 0 = high bits, M[15] = 56 * 8 =\n"
    " *    448 (bit count). 56 < 64 so single-block pad-and-length. That's\n"
    " *    different from SHA256 (which fills exactly one block and needs a\n"
    " *    second pad-only block).\n"
    " *\n"
    " * 3. Compact table probe. Same leading-16-byte LE convention as the\n"
    " *    other algos: bswap32 the leading 4 state words. Works for SHA224\n"
    " *    because the truncation happens at output time, not at chaining.\n"
    " *\n"
    " * 4. EMIT_HIT_7: 7-word emit wrapper (gpu_common.cl line 71). The 8th\n"
    " *    state word st->h[7] is intentionally NOT emitted to match SHA224's\n"
    " *    output format.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha224_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides sha256_block(), bswap32, EMIT_HIT_7, and\n"
    " * probe_compact_idx. gpu_md5_rules_str provides apply_rule.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final digest h[0..6] (after template_finalize) is BIG-ENDIAN —\n"
    " *     same as SHA256 / SHA1 (the compression function's natural form).\n"
    " *   - template_digest_compare byte-swaps the leading 4 words to LE\n"
    " *     before probing.\n"
    " *   - template_emit_hit writes 7 LE-byteswapped digest words.\n"
    " *   - Existing legacy SHA224 path (gpu_sha256_packed.cl already covers\n"
    " *     SHA224 per the file header comment) uses the same wire format.\n"
    " *\n"
    " * R1 mitigation: single private buffer pattern. No __private uchar*\n"
    " * helpers; no addrspace-cast ternaries.\n"
    " *\n"
    " * R2 (register pressure): SHA224 is structurally identical to SHA256\n"
    " * for the compression function — same W[64] schedule, same round\n"
    " * constants. Expected priv_mem_size matches SHA256.\n"
    " *\n"
    " * PERF-FIX LESSON (from gpu_md5_core.cl rev 1.2): template_finalize\n"
    " * builds M[16] DIRECTLY from input bytes via shifts/OR-merge, not via\n"
    " * a uchar pad[64] tail-block round-trip. Same pattern as SHA1/SHA256.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. The kernel-cache key (R3 fix) hashes the\n"
    " * defines_str (\"HASH_WORDS=7,HASH_BLOCK_BYTES=64\") so this instantiation\n"
    " * receives a distinct cache entry from SHA256's (HASH_WORDS=8). */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 7\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: SHA224 carries 8 uint32 chaining values\n"
    " * INTERNALLY (same compression function as SHA256). The struct is\n"
    " * literally sized at 8 — NOT HASH_WORDS — because the compression\n"
    " * function reads/writes 8 words per call. Output truncation (HASH_WORDS\n"
    " * = 7) is enforced at digest-out / digest_compare / emit_hit time by\n"
    " * iterating to 7, not by shrinking the struct.\n"
    " *\n"
    " * This is the only algorithm in the B4 fan-out that has this width\n"
    " * asymmetry; B5/B6 SHA384 (state 8 ulong, output 6 ulong) will follow\n"
    " * the same convention. */\n"
    "typedef struct {\n"
    "    uint h[8];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install SHA224 IV into state.\n"
    " * Standard SHA224 initial hash values (FIPS 180-4 §5.3.2). 8 values —\n"
    " * the compression function uses all 8 as the chaining IV. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0xc1059ed8u;\n"
    "    st->h[1] = 0x367cd507u;\n"
    "    st->h[2] = 0x3070dd17u;\n"
    "    st->h[3] = 0xf70e5939u;\n"
    "    st->h[4] = 0xffc00b31u;\n"
    "    st->h[5] = 0x68581511u;\n"
    "    st->h[6] = 0x64f98fa7u;\n"
    "    st->h[7] = 0xbefa4fa4u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (64) byte block.\n"
    " * SHA224 reads message words BIG-ENDIAN (same as SHA256). */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b]     << 24)\n"
    "             | ((uint)block[b + 1] << 16)\n"
    "             | ((uint)block[b + 2] << 8)\n"
    "             |  (uint)block[b + 3];\n"
    "    }\n"
    "    sha256_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: identical to SHA256's — same compression, same\n"
    " * BE message-word load, same 64-bit BE length encoding. The output\n"
    " * truncation (7 words instead of 8) happens at digest-out time, not\n"
    " * here. After return, st->h[0..7] holds 8 SHA256-style chaining words\n"
    " * in BIG-ENDIAN; the template body emits only the leading 7. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b]     << 24)\n"
    "                 | ((uint)data[b + 1] << 16)\n"
    "                 | ((uint)data[b + 2] << 8)\n"
    "                 |  (uint)data[b + 3];\n"
    "        }\n"
    "        sha256_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Tail bytes BIG-ENDIAN. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = 3 - (i & 3);\n"
    "        M[wi] |= ((uint)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker. */\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = 3 - (rem & 3);\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha256_block(&st->h[0], M);\n"
    "    } else {\n"
    "        sha256_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha256_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. SHA224 hex output is 56 lowercase\n"
    " * hex chars (28 digest bytes × 2). 56 < 64 so the pad fits in the\n"
    " * SAME block — single-block iter (vs SHA256 which needs two).\n"
    " *\n"
    " * Layout:\n"
    " *   M[0..13] = 56 hex bytes packed BE into 14 uint32 words (each word\n"
    " *              holds 4 hex chars BE)\n"
    " *   M[14] = high 32 bits of bit count = 0\n"
    " *   M[15] = low 32 bits of bit count = 56 * 8 = 448\n"
    " *   But we also need the 0x80 pad byte right after the hex. 56 hex\n"
    " *   chars fill M[0..13] exactly (14 * 4 = 56), so 0x80 lands in M[14]\n"
    " *   at the high octet — UNLESS we'd overrun. Wait: 14 uint32 = 56\n"
    " *   bytes. 0x80 must go at byte 56, which is M[14] high octet.\n"
    " *   Then the length must go in M[14..15]. That's a conflict.\n"
    " *\n"
    " * Resolution: 56 + 1 (for 0x80) + 8 (length) = 65 bytes. Exceeds 64,\n"
    " * so we DO need a second block.\n"
    " *\n"
    " * Block 1: M[0..13] = 56 hex bytes BE; M[14] = 0x80000000u (BE 0x80\n"
    " * at byte position 56); M[15] = 0.\n"
    " * Block 2: M[0..13] = 0; M[14] = 0; M[15] = 56 * 8 = 448. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* Inlined hex encoder — per-byte BE hex. 7 state words → 14 hex\n"
    "     * uint32 words (M[0..13]). Note: we ENCODE only the FIRST 7 state\n"
    "     * words (HASH_WORDS) since SHA224's output is 28 bytes / 56 hex. */\n"
    "    for (int i = 0; i < 7; i++) {\n"
    "        uint s = st->h[i];\n"
    "        uint b0 = (s >> 24) & 0xff;\n"
    "        uint b1 = (s >> 16) & 0xff;\n"
    "        uint b2 = (s >> 8)  & 0xff;\n"
    "        uint b3 = s & 0xff;\n"
    "        uint hi0 = (b0 >> 4) & 0xf, lo0 = b0 & 0xf;\n"
    "        uint hi1 = (b1 >> 4) & 0xf, lo1 = b1 & 0xf;\n"
    "        uint hi2 = (b2 >> 4) & 0xf, lo2 = b2 & 0xf;\n"
    "        uint hi3 = (b3 >> 4) & 0xf, lo3 = b3 & 0xf;\n"
    "        uint h0 = ((hi0 + ((hi0 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo0 + ((lo0 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h1 = ((hi1 + ((hi1 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo1 + ((lo1 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h2 = ((hi2 + ((hi2 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo2 + ((lo2 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h3 = ((hi3 + ((hi3 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo3 + ((lo3 < 10) ? '0' : ('a' - 10)));\n"
    "        M[i * 2]     = (h0 << 16) | h1;\n"
    "        M[i * 2 + 1] = (h2 << 16) | h3;\n"
    "    }\n"
    "    M[14] = 0x80000000u;   /* 0x80 BE at byte position 56 */\n"
    "    M[15] = 0u;\n"
    "    /* Reset state to SHA224 IV; absorb first hex block. */\n"
    "    st->h[0] = 0xc1059ed8u; st->h[1] = 0x367cd507u;\n"
    "    st->h[2] = 0x3070dd17u; st->h[3] = 0xf70e5939u;\n"
    "    st->h[4] = 0xffc00b31u; st->h[5] = 0x68581511u;\n"
    "    st->h[6] = 0x64f98fa7u; st->h[7] = 0xbefa4fa4u;\n"
    "    sha256_block(&st->h[0], M);\n"
    "\n"
    "    /* Second block: pad + length only. */\n"
    "    for (int j = 0; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 0u;\n"
    "    M[15] = 56u * 8u;       /* 56 hex chars = 448 bits */\n"
    "    sha256_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the final\n"
    " * digest. Same leading-16-byte LE convention as SHA256: bswap32 the\n"
    " * leading 4 state words before probe_compact_idx. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    uint h0 = bswap32(st->h[0]);\n"
    "    uint h1 = bswap32(st->h[1]);\n"
    "    uint h2 = bswap32(st->h[2]);\n"
    "    uint h3 = bswap32(st->h[3]);\n"
    "    return probe_compact_idx(\n"
    "        h0, h1, h2, h3,\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit into the global hits buffer. Wraps\n"
    " * EMIT_HIT_7 (SHA224 = 7 uint32 digest words; the 8th internal word\n"
    " * st->h[7] is intentionally dropped). Hits buffer convention matches\n"
    " * gpu_sha256_packed.cl SHA224 path. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[7]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        _h[5] = bswap32((st)->h[5]); \\\n"
    "        _h[6] = bswap32((st)->h[6]); \\\n"
    "        EMIT_HIT_7((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. See gpu_md5_core.cl for protocol\n"
    " * notes. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[7]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        _h[5] = bswap32((st)->h[5]); \\\n"
    "        _h[6] = bswap32((st)->h[6]); \\\n"
    "        EMIT_HIT_7_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h, \\\n"
    "                   (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                   (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
;
