/* Auto-generated from gpu_sha1dru_core.cl -- do not edit */
static const char gpu_sha1dru_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sha1dru_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha1dru_core.cl — SHA1DRU (Drupal SHA1, hashcat -m 7900) algorithm\n"
    " * extension functions for the generic dispatch template (Memo B Phase B6.11).\n"
    " *\n"
    " * STATUS: B6.11 — first 1M-iteration algorithm on the unified template path.\n"
    " *\n"
    " * SHA1DRU = SHA1(pass), then 1,000,000 iterations of SHA1(hex_lc(state) || pass).\n"
    " *\n"
    " * CPU reference (mdxfind.c JOB_SHA1DRU at lines 14261-14285):\n"
    " *\n"
    " *   mysha1((char *)cur, len, curin.h);             // initial = SHA1(pass)\n"
    " *   memmove(linebuf + 40, cur, len);\n"
    " *   for (x = 1; x < 1000001; x++) {\n"
    " *     prmd5(curin.h, linebuf, 40);                 // hex_lc(state) -> linebuf[0..39]\n"
    " *     linebuf[40] = cur[0];                        // defensive overwrite of pass[0]\n"
    " *     mysha1((char *)linebuf, len + 40, curin.h);  // SHA1(hex(state) || pass)\n"
    " *   }\n"
    " *   checkhash(&curin, 40, 1, job);                 // ONE probe at end\n"
    " *\n"
    " * Key semantic property: ONLY the FINAL state (after all 1M iterations) is\n"
    " * probed. Unlike SQL5 (which probes every iter), SHA1DRU's iter loop is an\n"
    " * implementation detail of the algorithm — not user-controlled via -i.\n"
    " *\n"
    " * DESIGN: 1M-loop INSIDE template_finalize, max_iter = 1.\n"
    " * ----------------------------------------------------------\n"
    " * The host sets params.max_iter = 1 (Maxiter is the user's -i, default 1\n"
    " * for SHA1DRU; the algorithm does NOT honor -i — its 1M is hardcoded).\n"
    " *\n"
    " * The kernel's outer iter loop in template_phase0 runs ONCE:\n"
    " *\n"
    " *   for (uint iter = 1; iter <= 1; iter++) {\n"
    " *     digest_compare(&st);   // probe FINAL state from finalize\n"
    " *     // iter == max_iter, so template_iterate is NOT called\n"
    " *   }\n"
    " *\n"
    " * Therefore:\n"
    " *   - template_finalize: does the FULL chain (SHA1(pass) + 1M inner iters)\n"
    " *   - template_iterate:  STUB (never called given max_iter=1)\n"
    " *\n"
    " * This avoids 1M wasted probes against the compact table — only the\n"
    " * final state is probed, matching CPU semantics exactly.\n"
    " *\n"
    " * Why this differs from SQL5:\n"
    " *   SQL5 probes every iter (its CPU `checkhash(..., x, job)` inside the\n"
    " *   for-loop emits at every iter level). SHA1DRU's `checkhash` is OUTSIDE\n"
    " *   the loop — only the final state matters. SQL5's pattern (1M probes)\n"
    " *   would be both incorrect and 100,000x more expensive.\n"
    " *\n"
    " * Why finalize and not iterate:\n"
    " *   With max_iter = 1, the kernel's iter loop body runs once and never\n"
    " *   calls template_iterate (the `if (iter < max_iter)` guard prevents it).\n"
    " *   Putting the work in iterate would require max_iter = 2, which would\n"
    " *   then waste a probe on the initial SHA1(pass) state at iter=1.\n"
    " *\n"
    " * Source order at compile time (mirrors SHA1 build):\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha1dru_core_str, gpu_template_str ]\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=5,HASH_BLOCK_BYTES=64,BASE_ALGO=sha1,\n"
    " * ITER_COUNT=1000000\" — same HASH_WORDS/HASH_BLOCK_BYTES as SHA1 / SHA1RAW /\n"
    " * SQL5; the ITER_COUNT token distinguishes the cache entry. Distinct cache\n"
    " * entry by source-text hash regardless (the 1M-loop body in finalize differs).\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace): single private buffer pattern.\n"
    " * No __private uchar* helpers; no addrspace-cast ternaries.\n"
    " *\n"
    " * R2 (register pressure): the 1M-iter body uses one M[16] scratch + the 5-word\n"
    " * state + a small private staging area for hex(state)||pass (capped to\n"
    " * RULE_BUF_LIMIT). Expected priv_mem on gfx1201 ~ comparable to or slightly\n"
    " * above SHA1 (extra hexbuf staging ~80 bytes). HARD GATE 43,024 B; SHA1\n"
    " * unsalted reading was ~41 KB so ample headroom expected.\n"
    " *\n"
    " * VALIDATION ORACLE: the existing slab kernel sha1dru_batch in gpu_sha1.cl\n"
    " * (lines 26-132 pre-B6.11). The CORE OF THIS FILE is a port of that slab\n"
    " * kernel's body (lines 80-120 of gpu_sha1.cl pre-B6.11) into the template\n"
    " * extension API. Differences from the slab kernel:\n"
    " *   - reads pass from `data` (post-rule buf passed by template) rather\n"
    " *     than from a packed wordbuf.\n"
    " *   - state stays in BE uint32 throughout; bswap to LE happens only at\n"
    " *     digest_compare / emit time (matches gpu_sha1_core.cl's convention).\n"
    " *   - the CPU's \"linebuf[40] = cur[0]\" defensive overwrite is unnecessary\n"
    " *     here because we build hex(state)||pass into a fresh staging buffer\n"
    " *     where bytes [40..40+plen) are written from `data` (the pass) every\n"
    " *     iter — no stale overwrite to defend against.\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 5\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "#ifndef ITER_COUNT\n"
    "#define ITER_COUNT 1000000\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: SHA1 carries 5 uint32 chaining values. The template\n"
    " * only reads/writes these via template_finalize's output + template_digest_-\n"
    " * compare; it does not introspect the struct. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install SHA1 IV into state. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "}\n"
    "\n"
    "/* template_transform: stub for interface symmetry. SHA1DRU's template_finalize\n"
    " * builds M[] in-place per block — never routes through this. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b]     << 24)\n"
    "             | ((uint)block[b + 1] << 16)\n"
    "             | ((uint)block[b + 2] << 8)\n"
    "             |  (uint)block[b + 3];\n"
    "    }\n"
    "    sha1_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* sha1dru_init_finalize: classic SHA1 finalize over (data, len) using\n"
    " * st->h as the chain (BE state). Mirrors gpu_sha1_core.cl's template_finalize\n"
    " * byte-for-byte. Used to compute the INITIAL SHA1(pass). */\n"
    "static inline void sha1dru_init_finalize(template_state *st,\n"
    "                                         const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Reset state to SHA1 IV. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b]     << 24)\n"
    "                 | ((uint)data[b + 1] << 16)\n"
    "                 | ((uint)data[b + 2] << 8)\n"
    "                 |  (uint)data[b + 3];\n"
    "        }\n"
    "        sha1_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = 3 - (i & 3);\n"
    "        M[wi] |= ((uint)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = 3 - (rem & 3);\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    } else {\n"
    "        sha1_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* SHA1DRU_MAX_PLEN: per-iter staging buffer size cap for hex(40) + pass.\n"
    " *\n"
    " * Sized at 256 bytes to comfortably hold hex(40) + plen up to ~215 bytes\n"
    " * (well above typical wordlist passwords). This matches the slab kernel's\n"
    " * 256-byte hexhash slot in gpujob.h:156 (`hexhash[GPUBATCH_MAX][256]`).\n"
    " * Passwords longer than 215 bytes would truncate at the SHA1DRU iter input\n"
    " * — same behavior as the slab path (which capped hexhash at 256 too).\n"
    " *\n"
    " * R2 (gfx1201 priv_mem): a per-iter alloc of RULE_BUF_LIMIT (~40 KB) blew\n"
    " * out the spill region (B6.11 first build measured 82,080 B per work-item\n"
    " * on gfx1201). 256 bytes here keeps us comfortably under the 43,024 B\n"
    " * HARD GATE — expected reading ~41 KB (in line with SHA1 unsalted's\n"
    " * ~41 KB baseline). */\n"
    "#define SHA1DRU_MAX_PLEN  216\n"
    "#define SHA1DRU_HEXBUF    (40 + SHA1DRU_MAX_PLEN)\n"
    "\n"
    "/* sha1dru_iter_step: one iteration of the SHA1DRU inner loop:\n"
    " *   build hex_lc(state) into bytes 0..39 of a staging buffer;\n"
    " *   copy `pass` into bytes 40..40+plen-1 (capped at SHA1DRU_MAX_PLEN);\n"
    " *   total = 40 + min(plen, SHA1DRU_MAX_PLEN);\n"
    " *   reset state to SHA1 IV; absorb the staged buffer.\n"
    " *\n"
    " * Hex encoding is BIG-ENDIAN per state word, lowercase ('0'..'9','a'..'f').\n"
    " * Mirrors the CPU's prmd5 (lowercase hex) over the 20-byte BE state.\n"
    " *\n"
    " * Block layout:\n"
    " *   - For plen <= 14: total <= 54 bytes — single block (40 + plen + 1 + 8 <= 64\n"
    " *     when plen <= 14). The 0x80 marker at byte (40+plen), length BE in M[15].\n"
    " *   - For plen >= 15: total >= 55 bytes — needs two blocks (one full block\n"
    " *     of 64 bytes, then padding+length in second block).\n"
    " *   - For plen >= 24: 40 + plen >= 64 — block 1 full, second block holds\n"
    " *     remaining tail + 0x80 + zeros + length.\n"
    " *   - For plen >= 88 (total >= 128): 2 full blocks + final pad block.\n"
    " *   - For plen >= 152 (total >= 192): 3 full blocks + final pad block.\n"
    " *\n"
    " * The hexbuf staging area lives on the kernel stack (private memory). */\n"
    "static inline void sha1dru_iter_step(template_state *st,\n"
    "                                     const uchar *pass, int plen)\n"
    "{\n"
    "    __attribute__((aligned(16))) uchar hexbuf[SHA1DRU_HEXBUF];\n"
    "\n"
    "    /* Encode 20 bytes of state[0..4] as 40 lowercase hex chars in hexbuf[0..39]. */\n"
    "    for (int w = 0; w < 5; w++) {\n"
    "        uint sv = st->h[w];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uint byte = (sv >> ((3 - b) * 8)) & 0xff;\n"
    "            uint hi = (byte >> 4) & 0xf;\n"
    "            uint lo = byte & 0xf;\n"
    "            hexbuf[w * 8 + b * 2]     = (uchar)(hi + ((hi < 10u) ? '0' : ('a' - 10)));\n"
    "            hexbuf[w * 8 + b * 2 + 1] = (uchar)(lo + ((lo < 10u) ? '0' : ('a' - 10)));\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Append pass at offset 40, capped at SHA1DRU_MAX_PLEN. */\n"
    "    int eff_plen = (plen < SHA1DRU_MAX_PLEN) ? plen : SHA1DRU_MAX_PLEN;\n"
    "    for (int i = 0; i < eff_plen; i++) {\n"
    "        hexbuf[40 + i] = pass[i];\n"
    "    }\n"
    "    int total = 40 + eff_plen;\n"
    "\n"
    "    /* Reset state to SHA1 IV. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "\n"
    "    /* SHA1(hexbuf, total) — same finalize structure as sha1dru_init_finalize\n"
    "     * but inlined to avoid a second function call across 1M iters. */\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "    while (total - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)hexbuf[b]     << 24)\n"
    "                 | ((uint)hexbuf[b + 1] << 16)\n"
    "                 | ((uint)hexbuf[b + 2] << 8)\n"
    "                 |  (uint)hexbuf[b + 3];\n"
    "        }\n"
    "        sha1_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = total - pos;\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = 3 - (i & 3);\n"
    "        M[wi] |= ((uint)hexbuf[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = 3 - (rem & 3);\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)total * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    } else {\n"
    "        sha1_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)total * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_finalize: the FULL SHA1DRU chain — initial SHA1(pass) followed\n"
    " * by ITER_COUNT (1,000,000) iterations of SHA1(hex_lc(state) || pass).\n"
    " *\n"
    " * After return, st->h[0..4] holds the final SHA1 digest (BIG-ENDIAN — sha1_block's\n"
    " * natural output). template_digest_compare bswap32's to LE before probing. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    /* Step 1: initial SHA1(pass). */\n"
    "    sha1dru_init_finalize(st, data, len);\n"
    "\n"
    "    /* Step 2: 1,000,000 iterations of SHA1(hex_lc(state) || pass). */\n"
    "    for (uint iter = 0; iter < (uint)ITER_COUNT; iter++) {\n"
    "        sha1dru_iter_step(st, data, len);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: STUB. With max_iter = 1 (host-set for SHA1DRU), the\n"
    " * outer iter loop in template_phase0 runs exactly once and never calls\n"
    " * template_iterate. Kept for interface symmetry with the rest of the\n"
    " * unsalted-template family — if a future variant of SHA1DRU honored -i\n"
    " * (e.g., HASH_DRUPALx2 = run two 1M-cycle SHA1DRUs back-to-back), this\n"
    " * is where the per-iter step would live. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    /* No-op — see file header comment. */\n"
    "    (void)st;\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table. SHA1DRU's final digest\n"
    " * is BIG-ENDIAN; compact table is keyed LE — bswap32 first 4 words. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    uint h0 = bswap32(st->h[0]);\n"
    "    uint h1 = bswap32(st->h[1]);\n"
    "    uint h2 = bswap32(st->h[2]);\n"
    "    uint h3 = bswap32(st->h[3]);\n"
    "    return probe_compact_idx(\n"
    "        h0, h1, h2, h3,\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. SHA1 = 5 LE-byteswapped uint32 digest words. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h, \\\n"
    "                   (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                   (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
;
