/* Auto-generated from gpu_md5_rules32.cl -- do not edit */
static const char gpu_md5_rules32_str[] =
    "/*\n"
    " * $Revisio" "n: $\n"
    " * $Lo" "g: $\n"
    " *\n"
    " */\n"
    "/* gpu_md5_rules32.cl -- MD5 kernels driving the UTF-32 rule walker.\n"
    " *\n"
    " * Compiled AFTER gpu_common.cl, gpu_md5_rules.cl and gpu_u32_walker.cl, and\n"
    " * it depends on all three:\n"
    " *   gpu_common.cl      OCLParams, probe_compact_idx, EMIT_HIT_*, rule_class_match\n"
    " *   gpu_md5_rules.cl   md5_buf(), the RULE_OP_* opcode names, apply_rule()\n"
    " *                      (the BYTE walker -- still needed, see below)\n"
    " *   gpu_u32_walker.cl  u32_decode / u32_encode / apply_rule32 and the tables\n"
    " *\n"
    " * WHY THE BYTE WALKER IS STILL NEEDED.  pick_engine() (mdxfind.c) routes a\n"
    " * class-W word crossed with a BYTE-ONLY rule to the BYTE engine, and BYTE-ONLY\n"
    " * rules are real: 31 of HashMob.100k.rule, 1 of HashMob.10k.rule -- rules whose\n"
    " * own TEXT is not valid UTF-8, so the UTF-32 compiler refuses them.  A device\n"
    " * carrying only the UTF-32 walker would silently drop those pairs.  Both\n"
    " * walkers live here and the engine is chosen per (word, rule).\n"
    " *\n"
    " * ---- THE WIRE FORMAT, and why it needs no new kernel argument -------------\n"
    " *\n"
    " * OCLParams is FULL: 128 bytes, every offset named, and word_offset sits at a\n"
    " * hard-coded payload offset of 132 in 13 sites across 9 kernel files.  So\n"
    " * nothing new goes in it.  Instead:\n"
    " *\n"
    " *   rule_program  [ byte bytecode per rule, NUL-terminated ]\n"
    " *                 [ pad to a 4-byte boundary ]\n"
    " *                 [ uint32 packrule32 streams, RULE32_END-terminated ]\n"
    " *\n"
    " *   rule_offset[rule_idx]              byte offset of the BYTE stream.\n"
    " *                                      *** UNTAGGED AND UNCHANGED. ***\n"
    " *   rule_offset[n_rules + rule_idx]    bit 31 = a UTF-32 form exists\n"
    " *                                      bit 30 = Rule_byteok\n"
    " *                                      bits 0-29 = 4-aligned byte offset of\n"
    " *                                        the UTF-32 stream (meaningless when\n"
    " *                                        bit 31 is clear)\n"
    " *\n"
    " * BOTH capability bits live in the SECOND half, and the first half is left\n"
    " * exactly as md5_rules_phase0 already reads it.  That is not tidiness: the\n"
    " * production byte kernel masks NOTHING when it does\n"
    " * `uint rpos = rule_offset[rule_idx];`, so a tag bit in the first half would\n"
    " * send it to a wild offset.  Keeping the first half pristine means T0 (the\n"
    " * byte-only baseline) and the byte launch of T3 need no change to\n"
    " * gpu_md5_rules.cl at all -- which is what makes the comparison a comparison\n"
    " * rather than two different programs.\n"
    " *\n"
    " *   word_offset[word_idx]              byte offset into the packed words,\n"
    " *                                      bits 30-31 = per-word class:\n"
    " *                                        0 = A  ASCII / empty  (decodable)\n"
    " *                                        1 = W  HI|UTF8        (decodable)\n"
    " *                                        2 = I  HI alone       (NOT decodable)\n"
    " *\n"
    " * Both fields have room: the rules-path packed buffer is\n"
    " * GPU_RULES_MAX_WORDS_PER_BATCH * 256 = 2^22 and the rule program is well\n"
    " * under 2^30 at every real rule-file size (HashMob.100k packs to ~500 KB).\n"
    " * The host asserts prog_len <= 2^30 before it sets a tag bit.\n"
    " *\n"
    " * Carrying the class in word_offset rather than in a parallel array is what\n"
    " * makes the LANE PARTITION variants free: the kernels and both host hit\n"
    " * replays address a word ONLY through word_offset, so permuting that array\n"
    " * permutes the lanes with no change to the packed bytes and no mapping table.\n"
    " *\n"
    " * ---- THE KERNELS ---------------------------------------------------------\n"
    " *\n"
    " *   md5_rules_phase0          (in gpu_md5_rules.cl)  the BYTE walker\n"
    " *   md5_rules32_phase0        UTF-32 walker for every lane\n"
    " *   md5_rules_mixed_phase0    per-lane engine choice -- the PRODUCTION kernel\n"
    " *                             for `-8`; same 14 shared arguments and same\n"
    " *                             coalesced payload as md5_rules_phase0 plus one\n"
    " *                             of its own (the case tables), so the host swaps\n"
    " *                             the handle and changes nothing else\n"
    " *   md5_rules_mixed_validate  emits post-rule UTF-8 BYTES per (word, rule);\n"
    " *                             the oracle-diff instrument, not a hot path\n"
    " *\n"
    " * A per-batch class PARTITION and a C2 decode PRE-PASS were both built,\n"
    " * measured and removed; see the notes at the partition site in gpu_opencl.c\n"
    " * and above md5_rules_mixed_phase0 here.\n"
    " */\n"
    "\n"
    "/* The wire-format constants (U32_R_*, U32_OFF_MASK, U32_TAG_SHIFT,\n"
    " * U32_OUT_BYTES) and u32_run_pair() moved into gpu_u32_walker.inc, so BOTH\n"
    " * backends share one copy.  They belong there rather than here because\n"
    " * u32_run_pair's signature is already expressible in the address-space macros\n"
    " * the walker uses -- `U32_GLOBAL const uchar *prog` and `U32_BUF uchar *buf`\n"
    " * are exactly what OpenCL's private-buf and Metal's device-buf spellings need\n"
    " * -- so writing it twice would have been a choice, not a necessity. */\n"
    "\n"
    "/* The C2 PRE-PASS kernel that decoded every word once into a uint32 buffer is\n"
    " * DELETED, not disabled.\n"
    " *\n"
    " * MEASURED before removing it: the in-lane decode is 8.5-10.2% of a UTF-32\n"
    " * pair's cost (the walk is the other ~90%), so a pre-pass had a ~10% ceiling --\n"
    " * and it paid for that with a 4x wider per-lane staging read, an extra\n"
    " * dispatch against the $Lo" "g 1549 budget, and a global buffer of\n"
    " * n_words * U32_BUF_ELEMS * 4 = 16384 * 2048 * 4 = 128 MB per batch.\n"
    " *\n"
    " * Also worth stating because it is the part that is easy to get wrong: INSIDE\n"
    " * A LANE the two options are the same thing.  The geometry is one lane per\n"
    " * (word, rule), so a lane decodes exactly one word either way; \"decode once\n"
    " * per word\" only ever existed as a separate pass over global memory.  And the\n"
    " * ENCODE is per-lane in both variants -- the output differs per rule -- so it\n"
    " * is the half a pre-pass structurally cannot amortise.\n"
    " *\n"
    " * Deleted rather than left behind a knob: it was env-selectable, and\n"
    " * MDXFIND_CACHE is the only environment input mdxfind takes.  Dead kernel\n"
    " * source also costs JIT time and constant budget in every build.\n"
    " */\n"
    "\n"
    "/* ==== T1 / T2 production kernel: per-lane engine choice ===============\n"
    " *\n"
    " * Signature is IDENTICAL to md5_rules_phase0 in gpu_md5_rules.cl -- same 14\n"
    " * arguments, same coalesced payload, same offsets 128 / 132 / 132+4*n_words.\n"
    " * That is deliberate: the host dispatch path can swap the cl_kernel handle\n"
    " * and change nothing else, which is the only way the T0/T1/T2 comparison is\n"
    " * measuring the kernel rather than the plumbing.\n"
    " */\n"
    "__kernel\n"
    "void md5_rules_mixed_phase0(\n"
    "    __global uchar        *payload,\n"
    "    __global const uchar  *rule_program,\n"
    "    __global const uint   *rule_offset,\n"
    "    __global const uint   *compact_fp,\n"
    "    __global const uint   *compact_idx,\n"
    "    __global const uchar  *hash_data_buf,\n"
    "    __global const ulong  *hash_data_off,\n"
    "    __global const ushort *unused_hash_data_len,\n"
    "    __global uint         *hits,\n"
    "    __global const ulong  *overflow_keys,\n"
    "    __global const uchar  *overflow_hashes,\n"
    "    __global const uint   *overflow_offsets,\n"
    "    __global const ushort *unused_overflow_lengths,\n"
    "    __global volatile uint *hashes_shown,\n"
    "    /* The two 1:1 case tables, CONCATENATED: up at [0 .. U32_CASE_N-1], lo\n"
    "     * above it.  A __global argument rather than __constant because 26,048\n"
    "     * bytes of constant data put this program 13 KB past NVIDIA's 64 KB bank\n"
    "     * -- ptxas refused the build outright.  See gpu_u32_walker.inc. */\n"
    "    __global const uint   *case_tab\n"
    "    )\n"
    "{\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    /* B3 two-cursor re-issue protocol, byte-for-byte as md5_rules_phase0 does\n"
    "     * it: on a dispatch following a hit-buffer overflow, lanes that lex-precede\n"
    "     * the cursor early-return so the hits already returned are not re-emitted. */\n"
    "    if (params.input_cursor_start > 0u || params.rule_cursor_start > 0u) {\n"
    "        if (rule_idx < params.rule_cursor_start) return;\n"
    "        if (rule_idx == params.rule_cursor_start &&\n"
    "            word_idx < params.input_cursor_start) return;\n"
    "    }\n"
    "\n"
    "    __global volatile uint *hit_count = (__global volatile uint *)(payload + 128);\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "    __global volatile uint *ovr_set = (__global volatile uint *)(payload + 100);\n"
    "    __global volatile uint *ovr_gid = (__global volatile uint *)(payload + 104);\n"
    "\n"
    "    __attribute__((aligned(16))) uchar bytebuf[RULE_BUF_MAX];\n"
    "    __attribute__((aligned(16))) uint  u32buf[U32_BUF_ELEMS];\n"
    "    __attribute__((aligned(16))) uint  u32mem[U32_BUF_ELEMS];\n"
    "    __attribute__((aligned(16))) uchar cand[U32_OUT_BYTES];\n"
    "\n"
    "    uint raw   = word_offset[word_idx];\n"
    "    uint wpos  = raw & U32_OFF_MASK;\n"
    "    uint wcls  = raw >> U32_TAG_SHIFT;\n"
    "    int  wlen  = (int)words[wpos] | ((int)words[wpos + 1] << 8);\n"
    "    wpos += 2;\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "\n"
    "    uint byte_roff = rule_offset[rule_idx];\n"
    "    uint u32_roff  = rule_offset[n_rules + rule_idx];\n"
    "\n"
    "    /* The synthetic no-rule pass: an EMPTY byte program.  It must still run\n"
    "     * MD5+probe -- it IS the no-rule pass, which mdxfind treats as\n"
    "     * foundational.  It is detected on the byte stream because the synthetic\n"
    "     * entry has no UTF-32 form by construction. */\n"
    "    int is_no_rule = (rule_program[byte_roff] == 0);\n"
    "\n"
    "    int engine = 0;\n"
    "    int clen = u32_run_pair(words, wpos, wlen, rule_program,\n"
    "                            byte_roff, u32_roff, wcls,\n"
    "                            bytebuf, u32buf, u32mem,\n"
    "                            cand, U32_OUT_BYTES, case_tab, &engine);\n"
    "    if (clen < 0) return;\n"
    "\n"
    "    /* No-op detection.  The byte kernel compares its walker buffer to the\n"
    "     * input bytes; here the comparison is against the ENCODED output, which is\n"
    "     * the same test the CPU bridge makes when it returns -2 for an unchanged\n"
    "     * candidate.  Comparing CODEPOINTS instead would miss the case where the\n"
    "     * rule changed the codepoint sequence but not its UTF-8 serialisation --\n"
    "     * which cannot happen for valid input, but the byte comparison is free and\n"
    "     * does not depend on that being true. */\n"
    "    if (!is_no_rule && clen == wlen) {\n"
    "        int changed = 0;\n"
    "        for (int i = 0; i < wlen; i++) {\n"
    "            if (cand[i] != words[wpos + i]) { changed = 1; break; }\n"
    "        }\n"
    "        if (!changed) return;\n"
    "    }\n"
    "\n"
    "    uint hx, hy, hz, hw;\n"
    "    md5_buf(cand, clen, &hx, &hy, &hz, &hw);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    if (max_iter < 1) max_iter = 1;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint matched_idx = 0u;\n"
    "        if (probe_compact_idx(hx, hy, hz, hw,\n"
    "                              compact_fp, compact_idx,\n"
    "                              params.compact_mask, params.max_probe,\n"
    "                              params.hash_data_count,\n"
    "                              hash_data_buf, hash_data_off,\n"
    "                              overflow_keys, overflow_hashes,\n"
    "                              overflow_offsets, params.overflow_count,\n"
    "                              &matched_idx)) {\n"
    "            uint mask = 1u << (iter & 31);\n"
    "            /* Same B3 overflow-aware, dedup-aware emit as md5_rules_phase0.\n"
    "             * The dedup-bit ROLLBACK on overflow is load-bearing: without it\n"
    "             * the bit stays set across dispatches and the re-issue lane\n"
    "             * silently drops the crack. */\n"
    "            EMIT_HIT_4_DEDUP_OR_OVERFLOW(hits, hit_count, params.max_hits,\n"
    "                       word_idx, rule_idx, iter, hx, hy, hz, hw,\n"
    "                       hashes_shown, matched_idx, mask,\n"
    "                       ovr_set, ovr_gid, gid);\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* md5_to_hex_lc writes the 32 hex chars packed into M[0..7], so\n"
    "             * the re-hash is assembled here rather than through md5_buf. */\n"
    "            uint M[16];\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80u;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "            M[14] = 32u * 8u;\n"
    "            M[15] = 0u;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u;\n"
    "            hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "    (void)hashes_shown;\n"
    "    (void)unused_hash_data_len;\n"
    "    (void)unused_overflow_lengths;\n"
    "}\n"
    "\n"
    "/* ==== pure UTF-32 production kernel ===================================\n"
    " *\n"
    " * Every lane takes the UTF-32 arm.  This is the SECOND LAUNCH of the\n"
    " * two-dispatch variant (T3): the host partitions word_offset[] by class, then\n"
    " * launches the existing byte kernel over the class-A|I lane range and this one\n"
    " * over the class-W range.  Its register allocation is the UTF-32 walker's\n"
    " * alone, where md5_rules_mixed_phase0's is the union of both walkers even for\n"
    " * lanes that take the byte path -- which is exactly the effect T3 exists to\n"
    " * measure.\n"
    " *\n"
    " * It reads lane indices through params.input_cursor_start as a lane BASE, so\n"
    " * the host does not have to re-pack the batch: the two launches cover disjoint\n"
    " * lane ranges of the same payload.\n"
    " */\n"
    "__kernel\n"
    "void md5_rules32_phase0(\n"
    "    __global uchar        *payload,\n"
    "    __global const uchar  *rule_program,\n"
    "    __global const uint   *rule_offset,\n"
    "    __global const uint   *compact_fp,\n"
    "    __global const uint   *compact_idx,\n"
    "    __global const uchar  *hash_data_buf,\n"
    "    __global const ulong  *hash_data_off,\n"
    "    __global const ushort *unused_hash_data_len,\n"
    "    __global uint         *hits,\n"
    "    __global const ulong  *overflow_keys,\n"
    "    __global const uchar  *overflow_hashes,\n"
    "    __global const uint   *overflow_offsets,\n"
    "    __global const ushort *unused_overflow_lengths,\n"
    "    __global volatile uint *hashes_shown,\n"
    "    /* The two 1:1 case tables, CONCATENATED: up at [0 .. U32_CASE_N-1], lo\n"
    "     * above it.  A __global argument rather than __constant because 26,048\n"
    "     * bytes of constant data put this program 13 KB past NVIDIA's 64 KB bank\n"
    "     * -- ptxas refused the build outright.  See gpu_u32_walker.inc. */\n"
    "    __global const uint   *case_tab\n"
    "    )\n"
    "{\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "\n"
    "    uint gid = get_global_id(0) + params.base_word_idx;   /* lane base for T3 */\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    __global volatile uint *hit_count = (__global volatile uint *)(payload + 128);\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "    __global volatile uint *ovr_set = (__global volatile uint *)(payload + 100);\n"
    "    __global volatile uint *ovr_gid = (__global volatile uint *)(payload + 104);\n"
    "\n"
    "    __attribute__((aligned(16))) uint  u32buf[U32_BUF_ELEMS];\n"
    "    __attribute__((aligned(16))) uint  u32mem[U32_BUF_ELEMS];\n"
    "    __attribute__((aligned(16))) uchar cand[U32_OUT_BYTES];\n"
    "\n"
    "    uint raw  = word_offset[word_idx];\n"
    "    uint wpos = raw & U32_OFF_MASK;\n"
    "    int  wlen = (int)words[wpos] | ((int)words[wpos + 1] << 8);\n"
    "    wpos += 2;\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "\n"
    "    uint u32_roff = rule_offset[n_rules + rule_idx];\n"
    "    if (!(u32_roff & U32_R_HASFORM)) return;  /* host must not route this lane */\n"
    "\n"
    "    int n = u32_decode(words + wpos, wlen, u32buf, U32_BUF_ELEMS);\n"
    "    if (n < 0) return;\n"
    "    n = apply_rule32((__global const uint *)(rule_program + (u32_roff & U32_R_OFFMASK)),\n"
    "                     u32buf, u32mem, n, case_tab);\n"
    "    if (n < 0) return;\n"
    "    int clen = u32_encode(u32buf, n, cand, U32_OUT_BYTES);\n"
    "    if (clen < 0) return;\n"
    "\n"
    "    if (clen == wlen) {\n"
    "        int changed = 0;\n"
    "        for (int i = 0; i < wlen; i++)\n"
    "            if (cand[i] != words[wpos + i]) { changed = 1; break; }\n"
    "        if (!changed) return;\n"
    "    }\n"
    "\n"
    "    uint hx, hy, hz, hw;\n"
    "    md5_buf(cand, clen, &hx, &hy, &hz, &hw);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    if (max_iter < 1) max_iter = 1;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint matched_idx = 0u;\n"
    "        if (probe_compact_idx(hx, hy, hz, hw,\n"
    "                              compact_fp, compact_idx,\n"
    "                              params.compact_mask, params.max_probe,\n"
    "                              params.hash_data_count,\n"
    "                              hash_data_buf, hash_data_off,\n"
    "                              overflow_keys, overflow_hashes,\n"
    "                              overflow_offsets, params.overflow_count,\n"
    "                              &matched_idx)) {\n"
    "            uint mask = 1u << (iter & 31);\n"
    "            /* Same B3 overflow-aware, dedup-aware emit as md5_rules_phase0.\n"
    "             * The dedup-bit ROLLBACK on overflow is load-bearing: without it\n"
    "             * the bit stays set across dispatches and the re-issue lane\n"
    "             * silently drops the crack. */\n"
    "            EMIT_HIT_4_DEDUP_OR_OVERFLOW(hits, hit_count, params.max_hits,\n"
    "                       word_idx, rule_idx, iter, hx, hy, hz, hw,\n"
    "                       hashes_shown, matched_idx, mask,\n"
    "                       ovr_set, ovr_gid, gid);\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* md5_to_hex_lc writes the 32 hex chars packed into M[0..7], so\n"
    "             * the re-hash is assembled here rather than through md5_buf. */\n"
    "            uint M[16];\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80u;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "            M[14] = 32u * 8u;\n"
    "            M[15] = 0u;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u;\n"
    "            hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "    (void)hashes_shown;\n"
    "    (void)unused_hash_data_len;\n"
    "    (void)unused_overflow_lengths;\n"
    "}\n"
    "\n"
    "/* ==== VALIDATE kernels: the oracle-diff instruments ===================\n"
    " *\n"
    " * Wire format is md5_rules_phase0_validate's exactly, so one host parser\n"
    " * reads both:\n"
    " *   slot[0..1]  retlen, int16 LE (sign-preserving)\n"
    " *   slot[2..3]  outlen, uint16 LE\n"
    " *   slot[4..]   the candidate bytes\n"
    " *\n"
    " * These emit IDENTITY output -- a candidate equal to its input is written out\n"
    " * like any other.  That is on purpose and it is the recorded trap: procrule\n"
    " * suppresses identity output while hashcat's hcrule emits it, and a per-rule\n"
    " * TARGET test passes spuriously for identity-output rules because the implicit\n"
    " * no-rule pass already satisfies the target.  Comparing full candidate streams\n"
    " * avoids both.\n"
    " */\n"
    "#define MD5_RULES32_VALIDATE_MAX_BUF   U32_OUT_BYTES\n"
    "#define MD5_RULES32_VALIDATE_RECORD_SZ (4 + MD5_RULES32_VALIDATE_MAX_BUF)\n"
    "\n"
    "__kernel\n"
    "void md5_rules_mixed_validate(\n"
    "    __global const uchar  *words,\n"
    "    __global const uint   *word_offset,\n"
    "    __global const uchar  *rule_program,\n"
    "    __global const uint   *rule_offset,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global uchar        *records_out,\n"
    "    __global const uint   *case_tab)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    __attribute__((aligned(16))) uchar bytebuf[RULE_BUF_MAX];\n"
    "    __attribute__((aligned(16))) uint  u32buf[U32_BUF_ELEMS];\n"
    "    __attribute__((aligned(16))) uint  u32mem[U32_BUF_ELEMS];\n"
    "    __attribute__((aligned(16))) uchar cand[U32_OUT_BYTES];\n"
    "\n"
    "    uint raw  = word_offset[word_idx];\n"
    "    uint wpos = raw & U32_OFF_MASK;\n"
    "    uint wcls = raw >> U32_TAG_SHIFT;\n"
    "    int  wlen = (int)words[wpos] | ((int)words[wpos + 1] << 8);\n"
    "    wpos += 2;\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "\n"
    "    int engine = 0;\n"
    "    int clen = u32_run_pair(words, wpos, wlen, rule_program,\n"
    "                            rule_offset[rule_idx], rule_offset[n_rules + rule_idx],\n"
    "                            wcls, bytebuf, u32buf, u32mem,\n"
    "                            cand, U32_OUT_BYTES, case_tab, &engine);\n"
    "\n"
    "    int retlen = clen;\n"
    "    int outlen = (retlen >= 0) ? retlen : 0;\n"
    "\n"
    "    uint slot = word_idx * n_rules + rule_idx;\n"
    "    uint base = slot * (uint)MD5_RULES32_VALIDATE_RECORD_SZ;\n"
    "\n"
    "    short retlen16 = (short)retlen;\n"
    "    records_out[base + 0] = (uchar)((uint)retlen16 & 0xffu);\n"
    "    records_out[base + 1] = (uchar)(((uint)retlen16 >> 8) & 0xffu);\n"
    "    ushort outlen16 = (ushort)outlen;\n"
    "    records_out[base + 2] = (uchar)((uint)outlen16 & 0xffu);\n"
    "    records_out[base + 3] = (uchar)(((uint)outlen16 >> 8) & 0xffu);\n"
    "    for (int i = 0; i < outlen && i < MD5_RULES32_VALIDATE_MAX_BUF; i++)\n"
    "        records_out[base + 4 + (uint)i] = cand[i];\n"
    "}\n"
;
