/* Auto-generated from gpu_blake2s256_core.cl -- do not edit */
static const char gpu_blake2s256_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_blake2s256_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_blake2s256_core.cl — BLAKE2S-256 algorithm extension functions for\n"
    " * the generic dispatch template (Memo B Phase B5 sub-batch 3).\n"
    " *\n"
    " * BLAKE2 is structurally distinct from MD-style hashes:\n"
    " *\n"
    " *   1. State carries digest h[8] PLUS a byte-counter t[2] PLUS a\n"
    " *      finalization flag f[2]. Per Memo B brief §B5 sub-batch 3, we keep\n"
    " *      counter+flag INSIDE the per-algo state struct rather than extend\n"
    " *      template_transform's signature (which would force changes across\n"
    " *      all 9 existing cores). The shared template body never reads the\n"
    " *      counter/flag fields — only template_init / _finalize / _iterate\n"
    " *      manipulate them, and those are per-algo.\n"
    " *\n"
    " *   2. NO 0x80 / length-encoding-in-tail padding: BLAKE2 zeros the tail\n"
    " *      of the final block and signals end-of-input via the f[0] flag and\n"
    " *      the byte counter. Final block runs compression with last==1.\n"
    " *\n"
    " *   3. Single-block fast path: any password <= 55 bytes (the slab\n"
    " *      kernel's typical max) is one compression with last==1, counter ==\n"
    " *      total_len. The template_finalize streams arbitrary-length input\n"
    " *      through BLAKE2s blocks generically — same correctness, no\n"
    " *      single-block special case.\n"
    " *\n"
    " * BLAKE2S-256 geometry:\n"
    " *   - 64-byte block, 8 × uint32 chaining state, LITTLE-ENDIAN\n"
    " *   - 10-round G-function compression (b2s_compress in gpu_common.cl)\n"
    " *   - parameter block init: IV[0] ^ 0x01010020\n"
    " *     (digest_length=32 << 0 | key_length=0 << 8 | fanout=1 << 16 |\n"
    " *      depth=1 << 24)\n"
    " *   - 32-byte digest = 8 uint32 LE\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (8 for BLAKE2S-256)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64)\n"
    " *   template_state     — h[8] digest + t[2] counter + f[2] flag\n"
    " *   template_init      — install IV ^ parameter_block; zero counter+flag\n"
    " *   template_transform — absorb one 64-byte block (NON-FINAL; advances\n"
    " *                        counter, runs compression with last==0)\n"
    " *   template_finalize  — process complete blocks, zero tail, run final\n"
    " *                        compression with last==1\n"
    " *   template_iterate   — re-hash digest as 64-byte hex_lc input. The hex\n"
    " *                        string of the 32-byte BLAKE2s256 digest is 64\n"
    " *                        chars, fitting one 64-byte block exactly. Counter\n"
    " *                        = 64; last=1.\n"
    " *   template_digest_compare — probe leading 16 bytes (h[0..3]) directly\n"
    " *                             (LE state, no bswap32; same as MD5 / RMD).\n"
    " *   template_emit_hit       — EMIT_HIT_8 wrapper (BLAKE2S-256 = 8 uint32\n"
    " *                             LE digest words; matches gpu_blake2s256-\n"
    " *                             unsalted.cl line 122 emit format exactly).\n"
    " *\n"
    " * Source order at compile time:\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_blake2s256_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides B2S_IV[8], B2S_SIGMA[10][16], b2s_compress(),\n"
    " * EMIT_HIT_8{,_DEDUP_OR_OVERFLOW}, and probe_compact_idx.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final st->h[0..7] (after template_finalize/iterate) is LITTLE-ENDIAN\n"
    " *     per uint32 — direct probe + direct emit, no bswap32.\n"
    " *   - Wire format matches gpu_blake2s256unsalted.cl emit: 8 LE uint32\n"
    " *     words written via EMIT_HIT_8.\n"
    " *   - Probe key uses st->h[0..3] (leading 16 bytes LE), same convention\n"
    " *     as MD5/MD4/RIPEMD-160/RIPEMD-320.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single-private-buffer\n"
    " * pattern. State struct is private; b2s_compress takes __private uchar*\n"
    " * (existing primitive in gpu_common.cl rev 1.12, no addrspace-cast).\n"
    " *\n"
    " * R2 (register pressure): BLAKE2s carries 8 uint32 chaining + 16 uint32\n"
    " * working state in b2s_compress = comparable to RIPEMD-320 (which also\n"
    " * has 10 chaining + 10 working). Expected priv_mem_size on gfx1201\n"
    " * within the 41-43 KB band already documented for B5 sub-batch 1+2 algos.\n"
    " *\n"
    " * Iteration policy: BLAKE2 iterated mdxfind output is the 32-byte binary\n"
    " * digest re-encoded as 64 lowercase hex chars then re-hashed; matches\n"
    " * mdxfind.c's JOB_BLAKE2S256 case (line 30799) where len=64 between\n"
    " * iterations and prmd5() writes lowercase hex.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key (R3 fix): defines_str\n"
    " * \"HASH_WORDS=8,HASH_BLOCK_BYTES=64\" — same width as SHA256 but distinct\n"
    " * source text (different block compress + state struct), so cache key is\n"
    " * unique. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 8\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct. Fields beyond h[] are BLAKE2-specific:\n"
    " *   t[0..1] : 64-bit byte counter split into low/high uint32 pair (matches\n"
    " *             RFC 7693 BLAKE2s \"t\" parameter; for our wordlist inputs t[1]\n"
    " *             is always 0, but we keep it for spec compliance + reuse).\n"
    " *   f[0..1] : finalization flag pair. Only f[0] is set by single-pass\n"
    " *             flows (no last-node-of-tree semantics); kept as a pair to\n"
    " *             mirror RFC 7693's data layout for documentation consistency.\n"
    " *\n"
    " * The shared template body (gpu_template.cl) only reads st.h[]; it never\n"
    " * touches t[] or f[]. So the new fields cost zero in the shared path.\n"
    " *\n"
    " * 16-byte alignment helps AMD spill geometry (uint32 requires 4-byte;\n"
    " * declaring aligned(16) lets the compiler vectorize the M[16] internal\n"
    " * load inside b2s_compress). */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];   /* digest chaining state, LE-per-uint32 */\n"
    "    uint t[2];            /* byte counter (low, high) — t[1] unused for\n"
    "                             our input sizes but kept for spec parity */\n"
    "    uint f[2];            /* finalization flag (0 = mid-stream, 0xFFFFFFFFu\n"
    "                             = last block); f[1] unused (last-tree-node) */\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install BLAKE2s256 IV XOR'd with parameter block.\n"
    " *\n"
    " * Parameter block (RFC 7693 §2.5):\n"
    " *   bytes 0:    digest_length = 32 (BLAKE2S-256)\n"
    " *   byte 1:     key_length = 0 (no key)\n"
    " *   byte 2:     fanout = 1 (sequential)\n"
    " *   byte 3:     depth = 1 (sequential)\n"
    " *   bytes 4..7: leaf_length = 0\n"
    " *   bytes 8..13: node_offset = 0\n"
    " *   byte 14:    node_depth = 0\n"
    " *   byte 15:    inner_length = 0\n"
    " *   bytes 16..23: salt = 0 (no salt)\n"
    " *   bytes 24..31: personalization = 0\n"
    " *\n"
    " * Param block as 8 uint32 LE: P[0] = 0x01010020 (depth<<24 | fanout<<16 |\n"
    " * keylen<<8 | digestlen), P[1..7] = 0. So h[0] = IV[0] ^ 0x01010020;\n"
    " * h[1..7] = IV[1..7]. Matches mdxfind.c blake2s() (line 2334-2336) and\n"
    " * gpu_blake2s256unsalted.cl (line 105-106) exactly. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) st->h[i] = B2S_IV[i];\n"
    "    st->h[0] ^= 0x01010020u;   /* digest_length=32, key=0, fanout=1, depth=1 */\n"
    "    st->t[0] = 0u; st->t[1] = 0u;\n"
    "    st->f[0] = 0u; st->f[1] = 0u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one full 64-byte block as a NON-FINAL block.\n"
    " *\n"
    " * Public extension API. BLAKE2's per-block contract differs from MD-style:\n"
    " * the host kernel (template) calls template_transform only for COMPLETE\n"
    " * non-final blocks. The hot path inside template_finalize bypasses this\n"
    " * via a direct b2s_compress call to avoid the function-call boundary\n"
    " * cost (same perf-fix lesson as MD5/SHA cores).\n"
    " *\n"
    " * For BLAKE2 the \"partial-fill held over\" semantic that mdxfind.c uses\n"
    " * (blake2s() at line 2336-2351) doesn't apply here because template_-\n"
    " * finalize streams the whole input start-to-end in one call. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    /* Advance byte counter by full block size. */\n"
    "    uint t0 = st->t[0] + (uint)HASH_BLOCK_BYTES;\n"
    "    uint carry = (t0 < st->t[0]) ? 1u : 0u;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "    /* counter as ulong: lo | hi<<32 — LE on the OpenCL device side. */\n"
    "    ulong counter = ((ulong)st->t[0]) | (((ulong)st->t[1]) << 32);\n"
    "    b2s_compress(&st->h[0], block, counter, 0);\n"
    "}\n"
    "\n"
    "/* template_finalize: process all input start-to-end, advance counter,\n"
    " * zero-pad final block, run final compression with last=1.\n"
    " *\n"
    " * Mirrors mdxfind.c blake2s() (line 2329-2362) and the BLAKE2s spec.\n"
    " * For len in {0..55} bytes (our typical wordlist + rule range): single\n"
    " * compression with counter=len, last=1, tail bytes zero — matches\n"
    " * gpu_blake2s256unsalted.cl line 109-112 exactly.\n"
    " *\n"
    " * For longer inputs (len >= 64), processes complete 64-byte blocks first\n"
    " * (last=0, counter=cumulative bytes after the block), then the tail\n"
    " * (last=1).\n"
    " *\n"
    " * Edge case: len exactly == HASH_BLOCK_BYTES (== 64). Per RFC 7693 the\n"
    " * 64th byte cannot be processed in the last block of a NON-FINAL flow\n"
    " * (because then the final compression has zero new bytes, which is only\n"
    " * valid if the input is empty). The BLAKE2 spec resolves this by:\n"
    " *   - process exactly HASH_BLOCK_BYTES-1 bytes? No — the actual spec is:\n"
    " *     \"If 0 < dd <= HASH_BLOCK_BYTES, do final compression with the\n"
    " *      remaining dd bytes as a partial block padded with zeros.\"\n"
    " *   - In practice, when (len > 0 && len % 64 == 0), the last 64 bytes are\n"
    " *     the FINAL block (last=1), counter=len. The earlier complete blocks\n"
    " *     run as last=0. So for len==64 with content: ZERO complete-block\n"
    " *     iterations; the 64-byte input becomes the final block directly.\n"
    " *\n"
    " * Implementation: while (len - pos > HASH_BLOCK_BYTES) — strictly greater,\n"
    " * not >=. This leaves the last 1..64 bytes for the final compression.\n"
    " *\n"
    " * R1 mitigation preserved: only private uchar buffer + private state +\n"
    " * b2s_compress (existing __private uchar* primitive). */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    int pos = 0;\n"
    "    /* Process all complete blocks EXCEPT the last (which becomes the\n"
    "     * final block even if exactly HASH_BLOCK_BYTES bytes). Strictly\n"
    "     * greater preserves the \"len bytes go through with last=1 at the\n"
    "     * end\" invariant. */\n"
    "    while ((len - pos) > HASH_BLOCK_BYTES) {\n"
    "        uint t0 = st->t[0] + (uint)HASH_BLOCK_BYTES;\n"
    "        uint carry = (t0 < st->t[0]) ? 1u : 0u;\n"
    "        st->t[0] = t0;\n"
    "        st->t[1] += carry;\n"
    "        ulong counter = ((ulong)st->t[0]) | (((ulong)st->t[1]) << 32);\n"
    "        b2s_compress(&st->h[0], data + pos, counter, 0);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    /* Final block: copy remainder into a 64-byte zero-padded buffer.\n"
    "     * rem in [0..64]; rem==0 only for empty-input edge case. */\n"
    "    int rem = len - pos;\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    for (int i = 0; i < rem; i++) buf[i] = data[pos + i];\n"
    "    for (int i = rem; i < HASH_BLOCK_BYTES; i++) buf[i] = 0;\n"
    "\n"
    "    /* Advance counter by remaining (rem) bytes. */\n"
    "    uint t0 = st->t[0] + (uint)rem;\n"
    "    uint carry = (t0 < st->t[0]) ? 1u : 0u;\n"
    "    st->t[0] = t0;\n"
    "    st->t[1] += carry;\n"
    "    ulong counter = ((ulong)st->t[0]) | (((ulong)st->t[1]) << 32);\n"
    "\n"
    "    /* Final compression with last=1. */\n"
    "    st->f[0] = 0xFFFFFFFFu;\n"
    "    b2s_compress(&st->h[0], buf, counter, 1);\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the 32-byte BLAKE2s256 digest\n"
    " * as 64 lowercase hex chars and rehash. Matches mdxfind.c JOB_BLAKE2S256\n"
    " * (line 30799-30806): blake2s(curin.h, 32, ...); len = 64; prmd5(...)\n"
    " * writes 64 lc-hex chars; next iter blake2s those 64 bytes.\n"
    " *\n"
    " * 64 hex chars fit one HASH_BLOCK_BYTES (64) block exactly. Single\n"
    " * compression with last=1, counter=64.\n"
    " *\n"
    " * Snapshot the 8 LE state words BEFORE the IV reset so we can hex-encode\n"
    " * them into the next-iter input block. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint snap[8];\n"
    "    for (int i = 0; i < 8; i++) snap[i] = st->h[i];\n"
    "\n"
    "    uchar buf[HASH_BLOCK_BYTES];\n"
    "    /* Hex-encode 8 LE uint32 -> 64 lowercase hex chars. Byte order\n"
    "     * matches prmd5(): the LE byte image of each uint32 is hex'd byte-\n"
    "     * by-byte (b0, b1, b2, b3 → \"xxxx xxxx\") so the hex string equals\n"
    "     * mdxfind's prmd5 output. */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint s = snap[i];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uchar by = (uchar)((s >> (b * 8)) & 0xFFu);\n"
    "            uchar hi = by >> 4, lo = by & 0xFu;\n"
    "            buf[i * 8 + b * 2 + 0] = (hi < 10) ? (uchar)('0' + hi) : (uchar)('a' + (hi - 10));\n"
    "            buf[i * 8 + b * 2 + 1] = (lo < 10) ? (uchar)('0' + lo) : (uchar)('a' + (lo - 10));\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Reset state to BLAKE2s256 init (IV ^ parameter block); reset counter\n"
    "     * and flag for the new compression. */\n"
    "    for (int i = 0; i < 8; i++) st->h[i] = B2S_IV[i];\n"
    "    st->h[0] ^= 0x01010020u;\n"
    "    st->t[0] = 64u; st->t[1] = 0u;\n"
    "    st->f[0] = 0xFFFFFFFFu; st->f[1] = 0u;\n"
    "\n"
    "    b2s_compress(&st->h[0], buf, 64UL, 1);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe leading 16 bytes (h[0..3]). LE state\n"
    " * convention; no bswap32 (same as MD5 / RIPEMD-160 / RIPEMD-320 / matches\n"
    " * gpu_blake2s256unsalted.cl probe at line 118). */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. Wraps EMIT_HIT_8 (BLAKE2S-256 = 8 uint32\n"
    " * LE digest words; matches gpu_blake2s256unsalted.cl line 122 emit). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_8((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_8_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
