/* Auto-generated from gpu_kernel_a_rules.cl -- do not edit */
static const char gpu_kernel_a_rules_str[] =
    "/*\n"
    " * $Revisio" "n: $\n"
    " * $Lo" "g: $\n"
    " *\n"
    " */\n"
    "/* gpu_kernel_a_rules.cl -- Kernel A1 (rules-only) candidate producer.\n"
    " *\n"
    " * Production kernel A variant A1 per Phase 1a spec\n"
    " *   project_kernel_a_variants_phase1a_spec_2026-05-20.md.\n"
    " *\n"
    " * Produces packed candidates from input words x rule set via the\n"
    " * buffer-quadruple API (b_packed_buf, b_chunk_index, b_kernelA_state,\n"
    " * b_params). Output is consumable by any kernel B that obeys the\n"
    " * buffer-quadruple contract; in this codebase the existing kernel B\n"
    " * salt-axis dispatcher (gpu_opencl_kernelb_dispatch_proto) is the\n"
    " * primary consumer.\n"
    " *\n"
    " * Mechanical lineage: split from gpu_md5_rules.cl's md5_rules_phase0\n"
    " * production kernel. Identical apply_rule walker, identical opcode\n"
    " * contract, identical (word, rule) geometry, identical B3 cursor\n"
    " * semantics, identical no-op / rejection skip optimizations. The\n"
    " * MD5 + probe + EMIT_HIT tail is replaced by a write of [len][bytes]\n"
    " * into a packed candidate buffer with per-slot byte offset.\n"
    " *\n"
    " * Authoritative buffer contract:\n"
    " *   project_two_kernel_candidate_buffer_contract.md\n"
    " * Phase 1a A-variant spec:\n"
    " *   project_kernel_a_variants_phase1a_spec_2026-05-20.md\n"
    " *\n"
    " * Contract per buffer:\n"
    " *   b_packed_buf        - [len][bytes][len][bytes]... post-rule candidates.\n"
    " *                         len byte stored as uchar; bytes follow uncompressed.\n"
    " *                         Written at slot's reserved byte offset.\n"
    " *   b_chunk_index       - uint32 per slot. b_chunk_index[slot] = byte offset\n"
    " *                         into b_packed_buf where this candidate's len byte\n"
    " *                         lives. Pure physical byte offsets only.\n"
    " *   b_kernelA_state     - small counter buffer:\n"
    " *                           offset 0 : uint slot_counter   (atomic_inc)\n"
    " *                           offset 4 : uint byte_counter   (atomic_add for\n"
    " *                                                            variable-size\n"
    " *                                                            byte reservation)\n"
    " *                           offset 8 : uint overflow_flag  (set if either\n"
    " *                                                            counter exceeds\n"
    " *                                                            its capacity;\n"
    " *                                                            host re-issues\n"
    " *                                                            with larger\n"
    " *                                                            buffer or\n"
    " *                                                            smaller chunk)\n"
    " *\n"
    " * Walker behavior (mirrors md5_rules_phase0):\n"
    " *   1. Decode payload -> params, hit_count region (unused here but the same\n"
    " *      payload layout per the brief), word_offset, words.\n"
    " *   2. Decompose gid -> (word_idx, rule_idx) rule-major: same as the prod\n"
    " *      kernel.\n"
    " *   3. B3 cursor early-return for chunked overflow restart.\n"
    " *   4. Stage input word into private buf[].\n"
    " *   5. apply_rule(rule_program + rpos, buf, wlen) -> new_len.\n"
    " *   6. Rejection (new_len < 0): no slot reserved, no buffer write.\n"
    " *   7. No-op detection (!is_no_rule && new_len == wlen && buf == words):\n"
    " *      synthetic no-rule pass already covered this candidate; no slot.\n"
    " *      Foundational mdxfind behavior (feedback_no_rule_pass.md).\n"
    " *   8. Otherwise: reserve a slot, write [new_len][buf bytes] into\n"
    " *      b_packed_buf at the reserved byte offset, write byte offset into\n"
    " *      b_chunk_index[slot].\n"
    " *\n"
    " * Kernel B contract (consumer side, separate kernel):\n"
    " *   uint slot      = gid;\n"
    " *   uint wpos      = b_chunk_index[slot];\n"
    " *   if (wpos >= params.packed_size) return;  -- bounds guard per contract S5.2\n"
    " *   uint plen      = b_packed_buf[wpos];\n"
    " *   uchar *cand    = b_packed_buf + wpos + 1;\n"
    " *   uint widx      = params.base_word_idx + slot;\n"
    " *   -- kernel B then hashes cand[0..plen-1] and probes; EMIT_HIT_4 with\n"
    " *      widx + iter + digest. Per contract S7.1, no rule_idx sidecar is\n"
    " *      propagated; the plaintext IS the candidate and the host reads it\n"
    " *      from b_packed_buf[b_chunk_index[slot]].\n"
    " *\n"
    " * Geometry: same rule-major dispatch as md5_rules_phase0:\n"
    " *   global_size = n_words * n_rules\n"
    " *   word_idx    = gid % n_words\n"
    " *   rule_idx    = gid / n_words\n"
    " *\n"
    " * Reused primitives from gpu_common.cl: OCLParams struct only.\n"
    " *   - No md5_block / md5_buf / md5_to_hex_lc reference (kernel A pure).\n"
    " *   - No probe_compact_idx reference.\n"
    " *   - No EMIT_HIT_N reference.\n"
    " *\n"
    " * Salt-axis logic: not applicable. Salts are kernel B's concern. The\n"
    " * rules walker section of md5_rules_phase0 has no salt-axis fan-out\n"
    " * (verified by reading lines 1064-1153 of gpu_md5_rules.cl rev 1.30);\n"
    " * salts feed into the trailing MD5+probe block which kernel A omits.\n"
    " *\n"
    " * ====================================================================\n"
    " * KNOB G (2026-05-29) -- coalesced uint4 (16-byte) candidate writes.\n"
    " * --------------------------------------------------------------------\n"
    " * Build-gated by -DKNOBG_VEC_WRITE=1, which the host sets.  It used to be\n"
    " * reachable with MDXFIND_EXPERIMENT_RULES_CODEGEN_VEC_WRITE=1 plus a parent\n"
    " * flag; both env vars were removed 2026-09-16.  When the macro is\n"
    " * defined, the per-byte write loop that emits [len][bytes] into\n"
    " * b_packed_buf is replaced by uint4 (16-byte) stores from a private\n"
    " * 16-aligned staging buffer. Each slot's atomic byte-claim is rounded\n"
    " * UP to a multiple of 16 (need_aligned = (need_bytes + 15) & ~15), so\n"
    " * every slot starts on a 16-byte boundary and consumes a 16-byte\n"
    " * multiple of bytes. Pad bytes inside each slot's padded tail are\n"
    " * undefined; the consumer reads only [len] bytes (plen) and never\n"
    " * accesses padding -- bit-perfect equivalence with the legacy path.\n"
    " *\n"
    " * Invariant (proof by induction): the candidate buffer base is\n"
    " * 16-byte aligned by OpenCL guarantee; first byte_off=0 (16-aligned);\n"
    " * every subsequent claim adds a multiple of 16 -> every byte_off is a\n"
    " * multiple of 16. Aligned uint4 stores into the slot region are legal.\n"
    " *\n"
    " * Capacity: cap_packed sizing (host: cap_slots * 256) is unchanged.\n"
    " * 256 is the max need_aligned (need_bytes max = 256 = 1+255). Knob G\n"
    " * shifts ACTUAL bytes consumed per slot from emit_len+1 to\n"
    " * 16*ceil((emit_len+1)/16) ~ +3.8 B/slot on rockyou-1m mean (still\n"
    " * well under the cap; bounded halve-K retry handles the impossible-\n"
    " * by-construction overflow case unchanged).\n"
    " *\n"
    " * Authoritative spec: project_rules_codegen_knob_g_spec_2026-05-29.md.\n"
    " * ====================================================================\n"
    " */\n"
    "\n"
    "/* ---- The private byte walker, and when it is NOT compiled ------------\n"
    " *\n"
    " * Kernel A carries its own copy of the opcode table, case_flip_mask() and\n"
    " * apply_rule().  Under `-8` the host puts gpu_md5_rules.cl in this program\n"
    " * instead -- the UTF-32 walker's byte arm calls apply_rule(), and the walker\n"
    " * must be defined between apply_rule and the kernel, which one source file\n"
    " * cannot express -- so both copies would be in the same translation unit and\n"
    " * the second would be a redefinition.\n"
    " *\n"
    " * Guarding this copy out rather than the shared one is deliberate: the shared\n"
    " * one is what the UTF-32 walker was written against.  The substitution is\n"
    " * byte-exact -- the three OpenCL copies of this span (gpu_md5_rules.cl,\n"
    " * gpu_kernel_a_rules.cl, gpu_kernel_a_rules_masks.cl) are code-identical after\n"
    " * comments are stripped; they differ only in kernel-A's own KERNELA_STATE_* /\n"
    " * GPU_MASK_* constants, which sit OUTSIDE the guarded regions, and in the\n"
    " * PROFILE_VARIANT==3 timing stub, which is a diagnostic build that does not\n"
    " * combine with `-8`.\n"
    " * -------------------------------------------------------------------- */\n"
    "#ifndef GPU_U32_WALKER_PRESENT\n"
    "/* ==== Opcode definitions (must match ruleproc.c RULE_OP_* exactly) ==== */\n"
    "#define RULE_OP_INSERT      0xfd\n"
    "#define RULE_OP_OVERWRITE   0xfc\n"
    "#define RULE_OP_TOGGLE_AT   0xfb\n"
    "#define RULE_OP_INC         0xfa\n"
    "#define RULE_OP_DEC         0xf9\n"
    "#define RULE_OP_TRUNC       0xf8\n"
    "#define RULE_OP_DROP_LAST   0xf7\n"
    "#define RULE_OP_SUB         0xf6\n"
    "#define RULE_OP_LOWER       0xf5\n"
    "#define RULE_OP_UPPER       0xf4\n"
    "#define RULE_OP_CAP         0xf3\n"
    "#define RULE_OP_CAP_INV     0xf2\n"
    "#define RULE_OP_REVERSE     0xf1\n"
    "#define RULE_OP_TOGGLE      0xf0\n"
    "#define RULE_OP_TITLE_SP    0xef\n"
    "#define RULE_OP_TITLE_SEP   0xee\n"
    "#define RULE_OP_DUP         0xed\n"
    "#define RULE_OP_REFLECT     0xec\n"
    "#define RULE_OP_DUP_EACH    0xeb\n"
    "#define RULE_OP_ROT_L       0xea\n"
    "#define RULE_OP_ROT_R       0xe9\n"
    "#define RULE_OP_SWAP_FRONT  0xe8\n"
    "#define RULE_OP_SWAP_BACK   0xe7\n"
    "#define RULE_OP_DROP_FIRST  0xe6\n"
    "#define RULE_OP_APPEND      0xe5\n"
    "#define RULE_OP_PREPEND     0xe4\n"
    "#define RULE_OP_DEL_AT      0xe3\n"
    "#define RULE_OP_BIT_SHL     0xe2\n"
    "#define RULE_OP_BIT_SHR     0xe1\n"
    "#define RULE_OP_REPL_NEXT   0xe0\n"
    "#define RULE_OP_REPL_PREV   0xdf\n"
    "#define RULE_OP_PURGE       0xde\n"
    "#define RULE_OP_DUP_LAST    0xdd\n"
    "#define RULE_OP_DUP_FIRST   0xdc\n"
    "#define RULE_OP_REPEAT      0xdb\n"
    "#define RULE_OP_DUP_PREFIX  0xda\n"
    "#define RULE_OP_DUP_SUFFIX  0xd9\n"
    "#define RULE_OP_SWAP_AT     0xd8\n"
    "#define RULE_OP_EXTRACT     0xd7\n"
    "#define RULE_OP_OMIT        0xd6\n"
    "#define RULE_OP_TOGGLE_SEP  0xd5\n"
    "#define RULE_OP_NOOP        0xd4\n"
    "#define RULE_OP_NOOP_SP     0xd3\n"
    "#define RULE_OP_NOOP_TAB    0xd2\n"
    "#define RULE_OP_MEM_STORE   0xd1\n"
    "#define RULE_OP_MEM_APP     0xd0\n"
    "#define RULE_OP_MEM_PRE     0xcf\n"
    "#define RULE_OP_MEM_REJ     0xce\n"
    "#define RULE_OP_MEM_INSERT  0xcd\n"
    "#define RULE_OP_REJ_LEN_NE  0xcc\n"
    "#define RULE_OP_REJ_LEN_GE  0xcb\n"
    "#define RULE_OP_REJ_LEN_LE  0xca\n"
    "#define RULE_OP_REJ_HAS     0xc9\n"
    "#define RULE_OP_REJ_NHAS    0xc8\n"
    "#define RULE_OP_REJ_FIRST   0xc7\n"
    "#define RULE_OP_REJ_LAST    0xc6\n"
    "#define RULE_OP_S_SPECIAL   0xc5\n"
    "#define RULE_OP_HASH_EXIT   0xc4\n"
    "#define RULE_OP_HEX_UPPER   0xc3\n"
    "#define RULE_OP_HEX_LOWER   0xc2\n"
    "#define RULE_OP_DIV_INSERT  0xc1\n"
    "#define RULE_OP_CHR_ADD     0xc0\n"
    "\n"
    "/* Rule-walker scratch in ELEMENTS; host injects -D RULE_BUF_MAX from\n"
    " * GPU_RULES_WALKER_BUF_ELEMS (gpujob.h).  Fallback only.  LIMIT is MAX-15\n"
    " * (NUL + n+1 slack), and exceeding it is defined behaviour: the rule stops\n"
    " * and what it produced becomes the candidate.  See gpu_md5_rules.cl. */\n"
    "#ifndef RULE_BUF_MAX\n"
    "#define RULE_BUF_MAX   2048\n"
    "#endif\n"
    "#ifndef RULE_BUF_LIMIT\n"
    "#define RULE_BUF_LIMIT (RULE_BUF_MAX - 15)\n"
    "#endif\n"
    "#endif  /* !GPU_U32_WALKER_PRESENT -- see the note above region A */\n"
    "\n"
    "/* Candidate-buffer width.  MUST sit OUTSIDE the region-A guard: under `-8` that\n"
    " * guard is false, and a KA_BUF_BYTES defined inside it is simply absent -- which\n"
    " * is how this shipped for one build, with the kernel-A program failing to\n"
    " * compile on `use of undeclared identifier KA_BUF_BYTES` and every e347 and\n"
    " * MAKE_MD5PASS crack lost.  U32_OUT_BYTES (8192) under `-8` because the UTF-32\n"
    " * arm encodes up to U32_BUF_LIMIT codepoints at 4 bytes each; RULE_BUF_MAX\n"
    " * (2048) otherwise, which is what the byte walker bounds itself to.  Sizing it\n"
    " * at 2048 under `-8` would make u32_encode return NOROOM -- the pair silently\n"
    " * dropped -- exactly where the byte arm would instead have produced a long\n"
    " * candidate and let the [len] clamp below truncate it. */\n"
    "#ifdef GPU_U32_WALKER_PRESENT\n"
    "#define KA_BUF_BYTES  U32_OUT_BYTES\n"
    "#else\n"
    "#define KA_BUF_BYTES  RULE_BUF_MAX\n"
    "#endif\n"
    "\n"
    "/* Kernel-A state buffer offsets. Single source of truth for host wiring\n"
    " * (Phase 4) to mirror via fixed-offset writes/reads. */\n"
    "#define KERNELA_STATE_SLOT_COUNTER   0u\n"
    "#define KERNELA_STATE_BYTE_COUNTER   4u\n"
    "#define KERNELA_STATE_OVERFLOW_FLAG  8u\n"
    "#define KERNELA_STATE_BYTES         12u\n"
    "\n"
    "/* ==== Branchless case-flip helper ====================================\n"
    " *\n"
    " * case_flip_mask(c) returns 0x20 if `c` is alphabetic (A-Z or a-z),\n"
    " * else 0. Verbatim from gpu_md5_rules.cl rev 1.30.\n"
    " */\n"
    "#ifndef GPU_U32_WALKER_PRESENT\n"
    "static inline uchar case_flip_mask(uchar c) {\n"
    "    uchar v = (uchar)((c | (uchar)0x20) - (uchar)'a');\n"
    "    return (uchar)((v < (uchar)26) ? 0x20 : 0);\n"
    "}\n"
    "\n"
    "/* ==== Unified single-buffer in-place rule walker =====================\n"
    " *\n"
    " * Verbatim copy of apply_rule from gpu_md5_rules.cl rev 1.30 (lines\n"
    " * 179-954). The walker is identical bytecode contract, identical\n"
    " * rejection semantics, identical bounds discipline. Future post-prototype\n"
    " * refactor may hoist this into a shared header consumed by both kernels.\n"
    " * For Phase 2 mechanical-split scope, verbatim duplication is correct.\n"
    " */\n"
    "static int apply_rule(__global const uchar *prog, uchar *buf, int len)\n"
    "{\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 3\n"
    "    /* V3 (PROFILE_VARIANT=3): stub apply_rule — return input length\n"
    "     * unchanged; suppress the huge opcode switch entirely. The walker\n"
    "     * still runs (word read into buf), the atomic claim still happens,\n"
    "     * the per-byte write still happens; only the apply_rule body is\n"
    "     * stubbed. Used to isolate the cost of the rule-walker switch.\n"
    "     * Compile-time: this `if`-true block is the entire function body. */\n"
    "    return len;\n"
    "#else\n"
    "    int k = 0;\n"
    "    /* ---- memory family: M 4 6 Q X (GPU-enabled 2026-09-11) ------------\n"
    "     * Per-call scratch, matching ruleproc.c exactly: applyrule() sets\n"
    "     * memlen = 0 at the top of EVERY call, so memory state never crosses a\n"
    "     * (word, rule) boundary.  That is what makes these ops portable to a\n"
    "     * walker where each work-item is independent -- there is no cross-rule\n"
    "     * state to reproduce.\n"
    "     *\n"
    "     * A second RULE_BUF_MAX buffer used to be unaffordable: at 40960 bytes it\n"
    "     * doubled per-thread private memory and FATAL'd CL_OUT_OF_HOST_MEMORY on\n"
    "     * an RTX 3080 (mdxfind.c rev 1.24 attempt, reverted).  At 2048 it is 4 KB\n"
    "     * per thread for both buffers together, a tenth of what one buffer cost\n"
    "     * before, which is why the operator reopened this. */\n"
    "    uchar mem[RULE_BUF_MAX];\n"
    "    int   memlen = 0;\n"
    "    int orig_len = len;\n"
    "\n"
    "    for (int n = 0; n < 256; n++) {\n"
    "        uchar op = prog[k];\n"
    "        if (op == 0) break;\n"
    "\n"
    "        switch (op) {\n"
    "\n"
    "            /* ---- Variable-length affix ops (0xff / 0xfe) ---- */\n"
    "            case 0xff: {\n"
    "                int N = (int)prog[k + 1];\n"
    "                int n_copy = N;\n"
    "                if (len + n_copy > RULE_BUF_LIMIT) n_copy = RULE_BUF_LIMIT - len;\n"
    "                if (n_copy < 0) n_copy = 0;\n"
    "                for (int j = 0; j < n_copy; j++) {\n"
    "                    buf[len + j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += n_copy;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "            case 0xfe: {\n"
    "                int N = (int)prog[k + 1];\n"
    "                int new_pre = N;\n"
    "                if (len + new_pre > RULE_BUF_LIMIT) new_pre = RULE_BUF_LIMIT - len;\n"
    "                if (new_pre < 0) new_pre = 0;\n"
    "                for (int j = len - 1; j >= 0; j--) {\n"
    "                    int dst = j + new_pre;\n"
    "                    if (dst <= RULE_BUF_LIMIT) buf[dst] = buf[j];\n"
    "                }\n"
    "                for (int j = 0; j < new_pre; j++) {\n"
    "                    buf[j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += new_pre;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Insert / overwrite / toggle ---- */\n"
    "            case RULE_OP_INSERT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                /* pos <= len: inserting at position == length is an APPEND,\n"
    "                 * which john and hashcat 6.2.5 both do. */\n"
    "                if (pos >= 0 && pos <= len && len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > pos; j--) buf[j] = buf[j - 1];\n"
    "                    buf[pos] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OVERWRITE: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                if (pos >= 0 && pos < len) buf[pos] = ch;\n"
    "                if (pos == 0 && len == 0) { buf[0] = ch; len++; }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_AT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    buf[pos] ^= case_flip_mask(buf[pos]);\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position arithmetic (branchless) ---- */\n"
    "            /* hashcat `BNX`: add the byte value of X to the byte at\n"
    "             * position N, wrapping.  No-op out of range, matching\n"
    "             * hashcat's mangle_chr_add() and ruleproc.c.  Branchless,\n"
    "             * in the style of RULE_OP_INC below. */\n"
    "            case RULE_OP_CHR_ADD: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar add = prog[k + 2];\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] + (valid ? add : (uchar)0));\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_INC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] + (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DEC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] - (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Length-shrink ---- */\n"
    "            case RULE_OP_TRUNC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                len = (pos < len) ? pos : len;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DROP_LAST: {\n"
    "                len -= (len > 0);\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Substitute ---- */\n"
    "            case RULE_OP_SUB: {\n"
    "                uchar c1 = prog[k + 1], c2 = prog[k + 2];\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                uchar16 v_c1 = (uchar16)c1;\n"
    "                uchar16 v_c2 = (uchar16)c2;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 eq = (v == v_c1);\n"
    "                    uchar16 eq_mask = as_uchar16(eq);\n"
    "                    uchar16 result = v ^ ((v ^ v_c2) & eq_mask);\n"
    "                    vstore16(result, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    if (buf[j] == c1) buf[j] = c2;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-string case ops ---- */\n"
    "            case RULE_OP_LOWER: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_upper = (v >= (uchar16)'A') & (v <= (uchar16)'Z');\n"
    "                    uchar16 mask = as_uchar16(is_upper) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_UPPER: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_lower = (v >= (uchar16)'a') & (v <= (uchar16)'z');\n"
    "                    uchar16 mask = as_uchar16(is_lower) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_upper = (v >= (uchar16)'A') & (v <= (uchar16)'Z');\n"
    "                    uchar16 mask = as_uchar16(is_upper) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                /* john and hashcat both act on POSITION 0, not on the\n"
    "                 * first alphabetic character: `c` on \"!bang\" gives \"!bang\"\n"
    "                 * in both, where the find-first form gave \"!Bang\".  Mirrors\n"
    "                 * ruleproc.c. */\n"
    "                if (len > 0) {\n"
    "                    uchar c = buf[0];\n"
    "                    if (c >= 'a' && c <= 'z') buf[0] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP_INV: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_lower = (v >= (uchar16)'a') & (v <= (uchar16)'z');\n"
    "                    uchar16 mask = as_uchar16(is_lower) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                /* john and hashcat both act on POSITION 0, not on the\n"
    "                 * first alphabetic character: `c` on \"!bang\" gives \"!bang\"\n"
    "                 * in both, where the find-first form gave \"!Bang\".  Mirrors\n"
    "                 * ruleproc.c. */\n"
    "                if (len > 0) {\n"
    "                    uchar c = buf[0];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[0] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REVERSE: {\n"
    "                int i = 0, j = len - 1;\n"
    "                while (i < j) {\n"
    "                    uchar t = buf[i];\n"
    "                    buf[i] = buf[j];\n"
    "                    buf[j] = t;\n"
    "                    i++;\n"
    "                    j--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    uchar16 v_or = v | (uchar16)0x20;\n"
    "                    uchar16 v_d  = v_or - (uchar16)'a';\n"
    "                    char16 is_alpha = (v_d < (uchar16)26);\n"
    "                    uchar16 mask = as_uchar16(is_alpha) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                        buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Title-case ---- */\n"
    "            case RULE_OP_TITLE_SP: {\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    /* An already-uppercase letter at a word start IS the\n"
    "                     * capital: keep it and mark the word started.  The old\n"
    "                     * form left z at 0 so the NEXT lowercase letter was\n"
    "                     * capitalised -- Hello1 became hEllo1. */\n"
    "                    /* Word start is POSITIONAL: the first character after a\n"
    "                     * separator, or position 0, whether or not it is a letter.\n"
    "                     * The old form only consumed the word start when it SAW a\n"
    "                     * letter, so \"!bang\" gave \"!Bang\" where john and hashcat\n"
    "                     * both give \"!bang\".  Mirrors ruleproc.c. */\n"
    "                    if (c == ' ') { z = 0; continue; }\n"
    "                    if (z == 0) { z = 1; if (c >= 'a' && c <= 'z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else { if (c >= 'A' && c <= 'Z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_SEP: {\n"
    "                uchar delim = prog[k + 1];\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    /* Word start is POSITIONAL: the first character after a\n"
    "                     * separator, or position 0, whether or not it is a letter.\n"
    "                     * The old form only consumed the word start when it SAW a\n"
    "                     * letter, so \"!bang\" gave \"!Bang\" where john and hashcat\n"
    "                     * both give \"!bang\".  Mirrors ruleproc.c. */\n"
    "                    if (c == delim) { z = 0; continue; }\n"
    "                    if (z == 0) { z = 1; if (c >= 'a' && c <= 'z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else { if (c >= 'A' && c <= 'Z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-buffer length-grow ops ---- */\n"
    "            case RULE_OP_DUP: {\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    int j = 0;\n"
    "                    int vbound = tlen & ~15;\n"
    "                    for (; j < vbound; j += 16) {\n"
    "                        uchar16 v = vload16(0, buf + j);\n"
    "                        vstore16(v, 0, buf + len + j);\n"
    "                    }\n"
    "                    for (; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REFLECT: {\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = 0; j < tlen; j++)\n"
    "                        buf[len + tlen - 1 - j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_EACH: {\n"
    "                int tlen = len;\n"
    "                if (tlen * 2 <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = tlen - 1; j >= 0; j--) {\n"
    "                        uchar c = buf[j];\n"
    "                        buf[j * 2]     = c;\n"
    "                        buf[j * 2 + 1] = c;\n"
    "                    }\n"
    "                    len = tlen * 2;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Rotation / swap ---- */\n"
    "            case RULE_OP_ROT_L: {\n"
    "                if (len > 0) {\n"
    "                    uchar first = buf[0];\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    buf[len - 1] = first;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_ROT_R: {\n"
    "                if (len > 0) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = last;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_FRONT: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[0]; buf[0] = buf[1]; buf[1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_BACK: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[len - 2];\n"
    "                    buf[len - 2] = buf[len - 1];\n"
    "                    buf[len - 1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Drop first / append / prepend ---- */\n"
    "            case RULE_OP_DROP_FIRST: {\n"
    "                if (len > 0) {\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_APPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) buf[len++] = ch;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_PREPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            case RULE_OP_DEL_AT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    for (int j = pos; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position bit shifts / nearest-neighbor copy ---- */\n"
    "            case RULE_OP_BIT_SHL: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] << 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_BIT_SHR: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] >> 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_NEXT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    /* NO-OP when pos+1 is out of range, matching hashcat and\n"
    "                     * ruleproc.c: `hashcat --stdout` on abcdefghij gives\n"
    "                     * abcdefghjj for `.8` and abcdefghij unchanged for `.9`.\n"
    "                     * This wrote (uchar)0 instead, embedding a NUL in the\n"
    "                     * candidate -- a third answer again, different from both\n"
    "                     * the CPU engine's one-past-the-end read and hashcat's\n"
    "                     * no-op, so CPU and GPU hit sets could disagree on any\n"
    "                     * rule using `.` at the last position. */\n"
    "                    if (pos + 1 < len) buf[pos] = buf[pos + 1];\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_PREV: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos > 0 && pos < len) buf[pos] = buf[pos - 1];\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Purge ---- */\n"
    "            case RULE_OP_PURGE: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                int w = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] != ch) buf[w++] = buf[j];\n"
    "                }\n"
    "                len = w;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Last/first-char duplicators ---- */\n"
    "            case RULE_OP_DUP_LAST: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    int j = 0;\n"
    "                    int vbound = n2 & ~15;\n"
    "                    uchar16 v_last = (uchar16)last;\n"
    "                    for (; j < vbound; j += 16) {\n"
    "                        vstore16(v_last, 0, buf + len + j);\n"
    "                    }\n"
    "                    for (; j < n2; j++) buf[len + j] = last;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_FIRST: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar first = buf[0];\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j + n2] = buf[j];\n"
    "                    for (int j = 1; j <= n2; j++) buf[j] = first;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPEAT: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                int tlen = len;\n"
    "                if (tlen > 0 && n2 > 0) {\n"
    "                    for (int copy = 0; copy < n2; copy++) {\n"
    "                        if (len + tlen > RULE_BUF_LIMIT) break;\n"
    "                        for (int j = 0; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                        len += tlen;\n"
    "                    }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_PREFIX: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    for (int j = len - 1; j >= 0; j--) buf[j + n2] = buf[j];\n"
    "                    for (int j = 0; j < n2; j++) buf[j] = buf[j + n2];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_SUFFIX: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    for (int j = 0; j < n2; j++) buf[len + j] = buf[len - n2 + j];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Position-paired ops ---- */\n"
    "            case RULE_OP_SWAP_AT: {\n"
    "                int posA = (int)prog[k + 1] - 1;\n"
    "                int posB = (int)prog[k + 2] - 1;\n"
    "                if (posA >= 0 && posA < len && posB >= 0 && posB < len) {\n"
    "                    uchar t = buf[posA]; buf[posA] = buf[posB]; buf[posB] = t;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- character classes (0x80-0x89) and =NX / %NX ----------\n"
    "             * Mirrors ruleproc.c's class arms exactly.  The 480-byte\n"
    "             * membership table and rule_class_match() live in the COMMON\n"
    "             * source, in the constant address space -- deliberately not a\n"
    "             * function-local array, which is what put the retired memory-op\n"
    "             * attempt over the per-thread private-memory budget.\n"
    "             *\n"
    "             * Promoting these off the CPU-only list is the point: every\n"
    "             * character-class rule used to force a mixed GPU/CPU partition,\n"
    "             * and a partitioned run has to union two result sets.\n"
    "             */\n"
    "            case RULE_OP_SUB_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                uchar y  = prog[k + 2];\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) buf[j] = y;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_PURGE_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                int d = 0;\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (!rule_class_match(cb, buf[j])) buf[d++] = buf[j];\n"
    "                len = d;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_CLASS: {\n"
    "                /* john's e?C: positional word start, separator untouched. */\n"
    "                uchar cb = prog[k + 1];\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (rule_class_match(cb, c)) { z = 0; continue; }\n"
    "                    if (z == 0) {\n"
    "                        z = 1;\n"
    "                        if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                    } else {\n"
    "                        if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                    }\n"
    "                }\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_CLASS_HC: {\n"
    "                /* hashcat's ~e?C is a DIFFERENT algorithm from john's e?C\n"
    "                 * above: it lowercases every position, uppercases position 0\n"
    "                 * and every position whose PREDECESSOR was in the class, and\n"
    "                 * case-normalises the separator itself.  The class test reads\n"
    "                 * the pre-modification byte. */\n"
    "                uchar cb = prog[k + 1];\n"
    "                int up = 1;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    int this_up = up;\n"
    "                    up = rule_class_match(cb, c) ? 1 : 0;\n"
    "                    if (c >= 'A' && c <= 'Z') { c ^= (uchar)0x20; buf[j] = c; }\n"
    "                    if (this_up && c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_HAS_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_NHAS_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                int found = 0;\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) { found = 1; break; }\n"
    "                if (!found) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_FIRST_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                if (len > 0 && !rule_class_match(cb, buf[0])) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LAST_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                if (len > 0 && !rule_class_match(cb, buf[len - 1])) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_AT_CLASS: {\n"
    "                int   y  = (int)prog[k + 1] - 1;\n"
    "                uchar cb = prog[k + 2];\n"
    "                if (y >= len || !rule_class_match(cb, buf[y])) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_CNT_CLASS: {\n"
    "                int   y  = (int)prog[k + 1] - 1;\n"
    "                uchar cb = prog[k + 2];\n"
    "                int cnt = 0;\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) cnt++;\n"
    "                if (cnt < y) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_AT_CHR: {\n"
    "                /* `=NX` reject unless the character at position N is X. */\n"
    "                int   y = (int)prog[k + 1] - 1;\n"
    "                uchar c = prog[k + 2];\n"
    "                if (y >= len || buf[y] != c) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_CNT_CHR: {\n"
    "                /* `%NX` reject unless X occurs at least N times. */\n"
    "                int   y = (int)prog[k + 1] - 1;\n"
    "                uchar c = prog[k + 2];\n"
    "                int cnt = 0;\n"
    "                for (int j = 0; j < len; j++) if (buf[j] == c) cnt++;\n"
    "                if (cnt < y) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "\n"
    "            /* ---- memory family, mirroring ruleproc.c's SLOW path ---------\n"
    "             * The CPU fast path escapes to slowrule on overflow; the slow\n"
    "             * path CLAMPS (y = MAXLINE - clen) rather than skipping, and that\n"
    "             * is the behaviour with a real limit, so it is what we mirror at\n"
    "             * RULE_BUF_LIMIT.  `6` prepends by memmove-right-then-copy\n"
    "             * because a GPU buffer has no headroom before index 0, where the\n"
    "             * CPU walks cpass backwards into its 512-byte slack. */\n"
    "            case RULE_OP_MEM_STORE: {          /* M -- store candidate */\n"
    "                for (int j = 0; j < len; j++) mem[j] = buf[j];\n"
    "                memlen = len;\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_APP: {            /* 4 -- append memory */\n"
    "                int y = memlen;\n"
    "                if (len + y > RULE_BUF_LIMIT) y = RULE_BUF_LIMIT - len;\n"
    "                if (y < 0) y = 0;\n"
    "                if (y > 0) {\n"
    "                    for (int j = 0; j < y; j++) buf[len + j] = mem[j];\n"
    "                    len += y;\n"
    "                }\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_PRE: {            /* 6 -- prepend memory */\n"
    "                int y = memlen;\n"
    "                if (len + y > RULE_BUF_LIMIT) y = RULE_BUF_LIMIT - len;\n"
    "                if (y < 0) y = 0;\n"
    "                if (y > 0) {\n"
    "                    for (int j = len - 1; j >= 0; j--) buf[j + y] = buf[j];\n"
    "                    for (int j = 0; j < y; j++) buf[j] = mem[j];\n"
    "                    len += y;\n"
    "                }\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_REJ: {            /* Q -- reject if == memory */\n"
    "                if (memlen == len) {\n"
    "                    int same = 1;\n"
    "                    for (int j = 0; j < len; j++) {\n"
    "                        if (buf[j] != mem[j]) { same = 0; break; }\n"
    "                    }\n"
    "                    if (same) return -1;\n"
    "                }\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_INSERT: {         /* X N M I */\n"
    "                /* Insert M chars of memory from OFFSET N at position I.\n"
    "                 * Out-of-range REJECTS, following hashcat's\n"
    "                 * mangle_insert_multi -- operator ruling 2026-09-11, and\n"
    "                 * identical to the CPU arm. */\n"
    "                int y    = (int)prog[k + 1] - 1;   /* offset within memory */\n"
    "                int tlen = (int)prog[k + 2] - 1;   /* count              */\n"
    "                int z    = (int)prog[k + 3] - 1;   /* insert position    */\n"
    "                if (memlen < 1 || tlen < 1 || z > len ||\n"
    "                    y > memlen || (y + tlen) > memlen) return -1;\n"
    "                if (len + tlen > RULE_BUF_LIMIT) tlen = RULE_BUF_LIMIT - len;\n"
    "                if (tlen > 0) {\n"
    "                    for (int j = len; j >= z; j--) buf[j + tlen] = buf[j];\n"
    "                    for (int j = 0; j < tlen; j++) buf[z + j] = mem[y + j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 4; break;\n"
    "            }\n"
    "            case RULE_OP_EXTRACT: {\n"
    "                /* xAB: extract B characters from position A.  Mirrors\n"
    "                 * ruleproc.c, which follows HASHCAT here (operator ruling\n"
    "                 * 2026-09-11, superseding an earlier ruling for john).\n"
    "                 * hashcat's mangle_extract() no-ops on BOTH out-of-range\n"
    "                 * conditions and never extracts a partial run:\n"
    "                 *     if (upos >= arr_len)         return arr_len;\n"
    "                 *     if ((upos + ulen) > arr_len) return arr_len;\n"
    "                 * On \"abc\": x22 and x23 are \"abc\" here and \"c\" in john;\n"
    "                 * x90 is \"abc\" here and a reject in john.  A zero count\n"
    "                 * with an in-range start yields an EMPTY candidate, which\n"
    "                 * is kept -- john's empty-word rejection was also ruled to\n"
    "                 * hashcat.  start==0 self-copies, as on the CPU. */\n"
    "                int start = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (start >= 0 && start < len && (start + count) <= len) {\n"
    "                    for (int q = 0; q < count; q++) {\n"
    "                        buf[q] = buf[start + q];\n"
    "                    }\n"
    "                    len = count;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OMIT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (pos >= 0 && pos < len && count > 0 && pos + count <= len) {\n"
    "                    for (int j = pos; j + count < len; j++) buf[j] = buf[j + count];\n"
    "                    len -= count;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_SEP: {\n"
    "                int upos = (int)prog[k + 1] - 1;\n"
    "                uchar sep = prog[k + 2];\n"
    "                int toggle_next = 0;\n"
    "                int occurrence = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == sep) {\n"
    "                        if (occurrence == upos) toggle_next = 1;\n"
    "                        else occurrence++;\n"
    "                        continue;\n"
    "                    }\n"
    "                    if (toggle_next) {\n"
    "                        if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                            buf[j] = c ^ case_flip_mask(c);\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- No-ops ---- */\n"
    "            case RULE_OP_NOOP:\n"
    "            case RULE_OP_NOOP_SP:\n"
    "            case RULE_OP_NOOP_TAB:\n"
    "                k += 1;\n"
    "                break;\n"
    "\n"
    "            /* ---- Special ops (silent no-ops) ---- */\n"
    "            case RULE_OP_S_SPECIAL:  k += 1; break;\n"
    "            case RULE_OP_HASH_EXIT:  k += 1; break;\n"
    "            case RULE_OP_DIV_INSERT: k += 3; break;\n"
    "\n"
    "            /* ---- Rejection ops ---- */\n"
    "            case RULE_OP_REJ_LEN_NE: {\n"
    "                /* CURRENT length, not the original word's. */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (y != len) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_GE: {\n"
    "                /* john: \"<N reject unless less than N chars\" -- reject when\n"
    "                 * len >= N.  This was the complement, matching ruleproc.c's\n"
    "                 * old behaviour; both fixed together so CPU and GPU agree. */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len >= y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_LE: {\n"
    "                /* john: \">N reject unless greater than N chars\". */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len <= y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_HAS: {\n"
    "                uchar c = prog[k + 1];\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) return -1;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_NHAS: {\n"
    "                uchar c = prog[k + 1];\n"
    "                int found = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) { found = 1; break; }\n"
    "                }\n"
    "                if (!found) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_FIRST: {\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[0] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LAST: {\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[len - 1] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* H/h hex emit: split cases (ROCm comgr addrspace fix per\n"
    "             * gpu_md5_rules.cl rev 1.27). */\n"
    "            case RULE_OP_HEX_UPPER: {\n"
    "                const uchar uhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','A','B','C','D','E','F'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = uhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = uhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_HEX_LOWER: {\n"
    "                const uchar lhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','a','b','c','d','e','f'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = lhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = lhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            default:\n"
    "                return len;\n"
    "        }\n"
    "    }\n"
    "    return len;\n"
    "#endif  /* PROFILE_VARIANT == 3 stub guard */\n"
    "}\n"
    "#endif  /* !GPU_U32_WALKER_PRESENT -- see the note above region A */\n"
    "\n"
    "/* ---- Kernel A1 (rules-only) production kernel --------------------\n"
    " *\n"
    " * Payload layout is identical to md5_rules_phase0 (Memo B B1\n"
    " * coalesced layout):\n"
    " *\n"
    " *   offset   0 : OCLParams params\n"
    " *   offset 128 : uint hit_count            (unused by kernel A; reserved\n"
    " *                                            for payload symmetry with\n"
    " *                                            md5_rules_phase0)\n"
    " *   offset 132 : uint word_offset[num_words]\n"
    " *   offset 132 + 4*num_words : uchar packed_words[]\n"
    " *\n"
    " * params.base_word_idx is read for hit-attribution propagation. Phase 1\n"
    " * rev 1.23 of gpu_common.cl renamed reserved32[0] -> base_word_idx with\n"
    " * this exact semantic. Kernel A does NOT write base_word_idx; the host\n"
    " * sets it before dispatch.\n"
    " *\n"
    " * params.packed_size is read as the kernel-A output buffer capacity (bytes\n"
    " * available in b_packed_buf). Overflow detection: any candidate that would\n"
    " * push byte_counter past packed_size sets overflow_flag and returns\n"
    " * without writing.\n"
    " *\n"
    " * Output buffer caps (capacity guards):\n"
    " *   b_packed_buf       capacity = params.packed_size bytes\n"
    " *   b_chunk_index      capacity = params.num_words * params.num_rules slots\n"
    " *                                  (worst case: every (word, rule) emits\n"
    " *                                   a slot, which is the rejection-free /\n"
    " *                                   no-op-free upper bound).\n"
    " *\n"
    " * On overflow the kernel signals via overflow_flag (state offset 8); host\n"
    " * retries with a smaller chunk or larger buffer. Mirrors the rules-engine\n"
    " * B3 cursor pattern.\n"
    " */\n"
    "\n"
    "__kernel\n"
    "void cand_rules_phase0(\n"
    "    __global uchar         *payload,\n"
    "    __global const uchar   *rule_program,\n"
    "    __global const uint    *rule_offset,\n"
    "    __global uchar         *b_packed_buf,\n"
    "    __global uint          *b_chunk_index,\n"
    "    __global volatile uint *b_kernelA_state\n"
    "    /* UTF-32 path: the two 1:1 case tables, CONCATENATED.  Appended LAST so\n"
    "     * every existing argument index is unchanged.  __global rather than\n"
    "     * __constant because 26,048 bytes in the constant bank put the program\n"
    "     * past NVIDIA's 64 KB limit and ptxas refused the build. */\n"
    "#ifdef GPU_U32_WALKER_PRESENT\n"
    "    , __global const uint  *case_tab\n"
    "#endif\n"
    "    )\n"
    "{\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    /* RULE-AXIS CHUNKING (Option A, 2026-05-29): params.num_rules carries the\n"
    "     * per-chunk rule COUNT (rule_count) and params.rule_cursor_start carries\n"
    "     * the per-chunk rule BASE (rule_start) into rule_offset[]. The host loops\n"
    "     * disjoint rule sub-ranges [rule_start, rule_start+rule_count) so the\n"
    "     * candidate buffer for one dispatch is bounded to n_words*rule_count*256\n"
    "     * <= cap. When the whole ruleset fits one chunk (e347 / small rule count)\n"
    "     * the host sets rule_start=0 and rule_count=n_rules, making this decode\n"
    "     * BYTE-IDENTICAL to the pre-chunking geometry (rule_idx = gid / n_words).\n"
    "     * The legacy B3 overflow-cursor early-return is REMOVED from this A1 path:\n"
    "     * with chunking the per-chunk buffer cannot overflow by construction\n"
    "     * (host caps K), and overloading rule_cursor_start with two meanings\n"
    "     * (chunk base vs overflow-restart cursor) would corrupt the chunk decode.\n"
    "     * Overflow is now handled host-side by a bounded halve-K retry. */\n"
    "    uint rule_start = params.rule_cursor_start;  /* chunk base into rule_offset[] */\n"
    "    uint n_rules    = params.num_rules;           /* this chunk's rule_count */\n"
    "    uint total      = n_words * n_rules;\n"
    "\n"
    "    uint gid = get_global_id(0);\n"
    "\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    /* ==== PROFILE_VARIANT scaffolding (2026-05-29, perf decomposition) =====\n"
    "     * When the kernel is JIT-built with -DPROFILE_VARIANT=N (N in 1..5), the\n"
    "     * per-lane kernel body is progressively stubbed to attribute kernel_a_us\n"
    "     * to its components. V0 (default; macro undefined) = byte-identical to\n"
    "     * the production path. ALL variants leave b_kernelA_state untouched\n"
    "     * (slot_counter = 0, byte_counter = 0) so the host sees actual_slots=0\n"
    "     * and skips kernel B; kernel_a_us is captured by the existing CL\n"
    "     * profiling event before kernel B runs (host site\n"
    "     * gpu_opencl.c:13059 `if (actual_slots == 0) ... continue` already exists).\n"
    "     * Crack-parity is INTENTIONALLY NOT preserved for V1..V5; results are\n"
    "     * throwaway, this is timing-only profiling infrastructure.\n"
    "     *\n"
    "     *   V1 = no atomic claim (per-lane deterministic offset gid*256 instead\n"
    "     *        of atomic_add; per-byte write still happens; apply_rule still\n"
    "     *        runs). Measures: atomic_add cost share.\n"
    "     *   V2 = no candidate write (atomic_add still happens but per-byte\n"
    "     *        write loop is no-op'd; index store skipped). Measures: per-byte\n"
    "     *        write loop cost share (BUT note V2 lets atomic still fire so\n"
    "     *        slot_counter would advance; we force it back to 0 below via\n"
    "     *        an end-of-kernel reset by lane 0 to keep host-side\n"
    "     *        actual_slots=0 invariant).\n"
    "     *   V3 = stub apply_rule (returns wlen unchanged; rule walker walks\n"
    "     *        but switch body is gone). Measures: apply_rule switch cost.\n"
    "     *   V4 = walker only — read word into buf, then return. NO apply_rule,\n"
    "     *        NO atomic, NO write. Measures: word-read + apply_rule + write\n"
    "     *        in aggregate (delta from V5).\n"
    "     *   V5 = empty kernel — return immediately. Measures: dispatch overhead\n"
    "     *        + chunk-loop overhead + kernel launch latency.\n"
    "     *\n"
    "     * V5 must short-circuit BEFORE the word-read; place gate here. */\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 5\n"
    "    return;\n"
    "#endif\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = rule_start + (gid / n_words);  /* GLOBAL rule index */\n"
    "\n"
    "    /* Deterministic sub-buffer pointers from params.num_words (identical\n"
    "     * to md5_rules_phase0). The compiler hoists since they depend only on\n"
    "     * params (uniform across the dispatch). hit_count + ovr_set + ovr_gid\n"
    "     * regions exist for payload symmetry; kernel A does not read or write\n"
    "     * them. */\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "\n"
    "    /* Private buffer (16-byte aligned, matches md5_rules_phase0).\n"
    "     * KA_BUF_BYTES, not RULE_BUF_MAX -- see the note at its definition. */\n"
    "    __attribute__((aligned(16))) uchar buf[KA_BUF_BYTES];\n"
    "\n"
    "    /* Per-lane emit state. Populated for in-range lanes only. */\n"
    "    int should_emit = 0;\n"
    "    uint emit_len = 0u;\n"
    "    uint need_bytes = 0u;\n"
    "    uint wpos = 0u;\n"
    "\n"
    "    /* Walk the rule. */\n"
    "    {\n"
    "#ifdef GPU_U32_WALKER_PRESENT\n"
    "        /* Bits 30-31 carry the per-word CLASS under `-8`\n"
    "         * (gpu_u32_tag_word_offsets), so the offset MUST be masked.  The byte\n"
    "         * arm below does not, because in byte mode the host never writes the\n"
    "         * tag; failing to mask when it does cost a\n"
    "         * `md5_rules ovr-state read err=-5` on the legacy kernel.\n"
    "         *\n"
    "         * No staging loop here: u32_run_pair reads the word out of `words`\n"
    "         * itself, on both of its arms. */\n"
    "        uint raw_woff = word_offset[word_idx];\n"
    "        wpos = raw_woff & U32_OFF_MASK;\n"
    "        uint wcls = raw_woff >> U32_TAG_SHIFT;\n"
    "        int wlen = (int)words[wpos] | ((int)words[wpos + 1] << 8);\n"
    "        wpos += 2;   /* 2-byte little-endian length: see gpujob.h */\n"
    "        if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "#else\n"
    "        wpos = word_offset[word_idx];\n"
    "        int wlen = (int)words[wpos] | ((int)words[wpos + 1] << 8);\n"
    "        wpos += 2;   /* 2-byte little-endian length: see gpujob.h */\n"
    "        if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "        for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "#endif\n"
    "\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 4\n"
    "        /* V4 (walker only): stop here. word_read into buf is done; skip\n"
    "         * apply_rule, atomic claim, per-byte write, index store. The\n"
    "         * compiler must not dead-strip the buf write — `buf` is private\n"
    "         * stack; force a fence by reading it back into a sink. */\n"
    "        if (buf[0] == 0xffu) {\n"
    "            /* unreachable on real data (wlen>0 by construction); inserted\n"
    "             * to keep the buf write in the live range so the compiler does\n"
    "             * not strip the read into buf. */\n"
    "            atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 0u);\n"
    "        }\n"
    "        return;\n"
    "#endif\n"
    "\n"
    "        uint rpos = rule_offset[rule_idx];\n"
    "        int is_no_rule = (rule_program[rpos] == 0);\n"
    "#ifdef GPU_U32_WALKER_PRESENT\n"
    "        /* UTF-32 path (`-8`).  The second half of rule_offset holds the UTF-32\n"
    "         * stream offset plus the two capability bits, based at\n"
    "         * params.num_masks -- which is 0 on every byte-mode kernel-A dispatch\n"
    "         * and is set by the host to the FIRST-HALF ENTRY COUNT when `-8` is\n"
    "         * active.  Basing it on that count rather than on this chunk's\n"
    "         * params.num_rules is required: num_rules is the per-chunk rule COUNT\n"
    "         * under rule-axis chunking, so a second or later chunk would index the\n"
    "         * wrong half.\n"
    "         *\n"
    "         * `buf` is passed as both bytebuf and out; the aliasing is safe by\n"
    "         * inspection of u32_run_pair (its byte arm's closing copy becomes\n"
    "         * self-assignment, its UTF-32 arm never touches bytebuf). */\n"
    "        uint u32_rpos = rule_offset[params.num_masks + rule_idx];\n"
    "        __attribute__((aligned(16))) uint u32buf[U32_BUF_ELEMS];\n"
    "        __attribute__((aligned(16))) uint u32mem[U32_BUF_ELEMS];\n"
    "        int engine = 0;\n"
    "        int new_len = u32_run_pair(words, wpos, wlen, rule_program,\n"
    "                                   rpos, u32_rpos, wcls,\n"
    "                                   buf, u32buf, u32mem,\n"
    "                                   buf, KA_BUF_BYTES, case_tab, &engine);\n"
    "#else\n"
    "        int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "#endif\n"
    "\n"
    "        if (new_len >= 0) {\n"
    "            /* No-op detection: synthetic \":\" no-rule pass already covered\n"
    "             * this candidate; skip slot emission. Foundational mdxfind\n"
    "             * behavior (feedback_no_rule_pass.md). Matches md5_rules_phase0\n"
    "             * exactly. */\n"
    "            int suppress_noop = 0;\n"
    "            if (!is_no_rule && new_len == wlen) {\n"
    "                int changed = 0;\n"
    "                for (int i = 0; i < wlen; i++) {\n"
    "                    if (buf[i] != words[wpos + i]) { changed = 1; break; }\n"
    "                }\n"
    "                if (!changed) suppress_noop = 1;\n"
    "            }\n"
    "            if (!suppress_noop) {\n"
    "                /* Clamp new_len to fit in the [len] byte. RULE_BUF_LIMIT <\n"
    "                 * 65536 so caller-side capacity ensures it; defensive guard\n"
    "                 * for the uchar length-byte slot. */\n"
    "                uint elen = (uint)new_len;\n"
    "                if (elen > 255u) elen = 255u;\n"
    "                emit_len = elen;\n"
    "                need_bytes = 1u + elen;   /* [len][bytes] */\n"
    "                should_emit = 1;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Per-lane global atomic_add slot/byte reservation. */\n"
    "    if (!should_emit) return;\n"
    "\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 1\n"
    "    /* V1 (no atomic claim): substitute deterministic per-lane offsets for\n"
    "     * the atomic_add slot/byte reservation. Per-byte write still happens\n"
    "     * (so V0 - V1 attributes the atomic_add cost). slot_counter +\n"
    "     * byte_counter stay at zero, so host sees actual_slots=0 and skips\n"
    "     * kernel B. The fake byte_off (gid * 256) keeps writes within the\n"
    "     * pre-allocated packed buffer for any gid covered by the host's K-cap\n"
    "     * (worst-case K*num_words slots, 256 B/slot = cap). */\n"
    "    uint byte_off = gid * 256u;\n"
    "    uint slot     = gid;\n"
    "    if (byte_off + need_bytes > params.packed_size) return;\n"
    "    if (slot >= total) return;\n"
    "    b_packed_buf[byte_off] = (uchar)emit_len;\n"
    "    for (uint i = 0; i < emit_len; i++) {\n"
    "        b_packed_buf[byte_off + 1u + i] = buf[i];\n"
    "    }\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "#elif defined(PROFILE_VARIANT) && PROFILE_VARIANT == 2\n"
    "    /* V2 (no candidate write): atomic claim still runs (so V0 - V2\n"
    "     * attributes the per-byte write loop). Per-byte memcpy + index store\n"
    "     * are removed. We INTENTIONALLY do not write slot_counter — we use a\n"
    "     * private read-write of the byte_counter to keep the atomic_add live\n"
    "     * (compiler must not fold; the result `byte_off` is unused). To prevent\n"
    "     * the host from running kernel B with non-zero actual_slots, we leave\n"
    "     * slot_counter alone (it stays 0). */\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes);\n"
    "    /* Keep byte_off live so the compiler doesn't drop the atomic; cheap\n"
    "     * side-effect via overflow flag (ored with 0 = no-op functionally). */\n"
    "    if (byte_off == 0xffffffffu) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 0u);\n"
    "    }\n"
    "    /* Slot-counter NOT incremented (intentional — host actual_slots=0 ->\n"
    "     * kernel B skipped). Per-byte write loop omitted (the measured target). */\n"
    "#elif defined(PROFILE_VARIANT) && PROFILE_VARIANT == 6\n"
    "    /* V6 (Knob G micro-benchmark; D4 in knob_g_spec): V0 baseline with\n"
    "     * the Knob G vectorized write loop FORCED ON, regardless of\n"
    "     * KNOBG_VEC_WRITE. Used to measure V0-vs-V6 kernel_a_us delta in\n"
    "     * the same harness that motivated Knob G -- closes the prediction-\n"
    "     * verification loop. Slot/byte claim semantics + crack output are\n"
    "     * IDENTICAL to V0 with KNOBG_VEC_WRITE=1; the only reason V6\n"
    "     * exists separately is so the operator can toggle just this leg\n"
    "     * of the cost share independently of Knob G.  Both were selected by\n"
    "     * env vars until 2026-09-16; nothing selects them now. */\n"
    "    {\n"
    "        uint need_aligned = (need_bytes + 15u) & ~15u;\n"
    "        uint byte_off = atomic_add(\n"
    "            &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "            need_aligned);\n"
    "        if (byte_off + need_aligned > params.packed_size) {\n"
    "            atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "            return;\n"
    "        }\n"
    "        uint slot = atomic_add(\n"
    "            &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u], 1u);\n"
    "        if (slot >= total) {\n"
    "            atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "            return;\n"
    "        }\n"
    "        __private uchar __attribute__((aligned(16))) stage[256];\n"
    "        stage[0] = (uchar)emit_len;\n"
    "        for (uint i = 0; i < emit_len; i++) stage[1u + i] = buf[i];\n"
    "        uint nvec = need_aligned / 16u;\n"
    "        __global uint4 *dst = (__global uint4 *)(b_packed_buf + byte_off);\n"
    "        __private uint4 *src = (__private uint4 *)stage;\n"
    "        for (uint v = 0; v < nvec; v++) dst[v] = src[v];\n"
    "        b_chunk_index[slot] = byte_off;\n"
    "    }\n"
    "#else\n"
    "    /* V0 (production baseline) — legacy path. KNOB G gated. */\n"
    "#ifdef KNOBG_VEC_WRITE\n"
    "    /* KNOB G ON: round need_bytes up to a 16-byte multiple. The atomic\n"
    "     * shape is unchanged (single atomic_add); only the value is rounded.\n"
    "     * Slot-start alignment proof: base ptr 16-aligned + each running sum\n"
    "     * adds a multiple of 16 -> every byte_off is 16-aligned. */\n"
    "    uint need_aligned = (need_bytes + 15u) & ~15u;\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_aligned);\n"
    "\n"
    "    /* Capacity guard: use the post-rounding byte count for the bound\n"
    "     * check (otherwise the tail uint4 stores could spill past packed). */\n"
    "    if (byte_off + need_aligned > params.packed_size) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "#else\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes);\n"
    "\n"
    "    /* Capacity guard: did this lane's reservation push past packed_size?\n"
    "     * If so, flag overflow and return WITHOUT incrementing slot_counter\n"
    "     * (so the slot count reflects only successfully-emitted candidates). */\n"
    "    if (byte_off + need_bytes > params.packed_size) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "#endif\n"
    "\n"
    "    uint slot = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u], 1u);\n"
    "\n"
    "    /* Slot-index capacity: bounded by num_words * num_rules (host alloc\n"
    "     * size). If for some reason slot >= total (overflow paradox: lanes\n"
    "     * past 'total' early-returned at the top), flag and skip. */\n"
    "    if (slot >= total) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    /* --- Write [len][bytes] into packed buf ----------------------- */\n"
    "#ifdef KNOBG_VEC_WRITE\n"
    "    /* KNOB G ON: stage [len][bytes] into a private 16-aligned buffer,\n"
    "     * then issue need_aligned/16 uint4 stores. emit_len in [0,255] ->\n"
    "     * need_aligned in [16,256] -> nvec in [1,16]. Pad bytes in\n"
    "     * stage[1+emit_len .. need_aligned) are undefined; consumer reads\n"
    "     * only plen bytes after the [len] header (see §3 spec). */\n"
    "    {\n"
    "        __private uchar __attribute__((aligned(16))) stage[256];\n"
    "        stage[0] = (uchar)emit_len;\n"
    "        for (uint i = 0; i < emit_len; i++) stage[1u + i] = buf[i];\n"
    "        uint nvec = need_aligned / 16u;\n"
    "        __global uint4 *dst = (__global uint4 *)(b_packed_buf + byte_off);\n"
    "        __private uint4 *src = (__private uint4 *)stage;\n"
    "        for (uint v = 0; v < nvec; v++) dst[v] = src[v];\n"
    "    }\n"
    "#else\n"
    "    b_packed_buf[byte_off] = (uchar)emit_len;\n"
    "    for (uint i = 0; i < emit_len; i++) {\n"
    "        b_packed_buf[byte_off + 1u + i] = buf[i];\n"
    "    }\n"
    "#endif\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "#endif  /* PROFILE_VARIANT 1/2/6/V0 selection */\n"
    "    /* Per-spec invariant 1: caller (Phase 4 host) relies on in-order\n"
    "     * single-queue FIFO to ensure these writes are visible to kernel B\n"
    "     * before kernel B dispatches. No explicit fence; the queue boundary\n"
    "     * provides the cross-kernel global-memory visibility. */\n"
    "}\n"
;
