/* Auto-generated from gpu_keccak256_core.cl -- do not edit */
static const char gpu_keccak256_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_keccak256_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_keccak256_core.cl - Keccak-256 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 4, 2026-05-03).\n"
    " *\n"
    " * Sponge construction with rate=136 bytes (= 17 ulong), output=32 bytes,\n"
    " * domain suffix=0x01 (plain Keccak; SHA3 uses 0x06). HASH_WORDS=8 = 8 uint32\n"
    " * LE per slab-kernel convention; HASH_BLOCK_BYTES=136 = rate (the unit of\n"
    " * data the kernel absorbs per Keccak-f[1600] call).\n"
    " *\n"
    " * Geometry / byte ordering:\n"
    " *   - 1600-bit state (5x5 = 25 ulong), naturally LITTLE-ENDIAN per ulong\n"
    " *   - 24-round Keccak-f[1600] permutation (keccakf1600 in gpu_common.cl)\n"
    " *   - Padding: append suffix (0x01 / 0x06) at offset (len % rate), then 0x80\n"
    " *     at offset (rate-1), then absorb final block.\n"
    " *   - Output: first HASH_WORDS uint32 of state, decomposed as\n"
    " *       h[2i]   = (uint)sp[i]\n"
    " *       h[2i+1] = (uint)(sp[i] >> 32)\n"
    " *     Same byte image as mdxfind.c sph_keccak256_close + memcpy(curin.h, ..., 32).\n"
    " *\n"
    " * Source order at compile time (from gpu_opencl.c\n"
    " * gpu_opencl_template_compile_keccak256):\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_keccak256_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides keccakf1600() + KECCAK_RC[24] + KECCAK_ROTC[25]\n"
    " * (rev 1.14+) plus EMIT_HIT_8 + probe_compact_idx.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - sp[0..24] is LE per ulong; the first 4 ulong (32 bytes) hold the\n"
    " *     digest. mdxfind.c JOB_KECCAK256 (line 28791) copies 32 bytes from\n"
    " *     sph_keccak256_close - these are the LE byte image of sp[0..3].\n"
    " *   - Hit-replay (gpujob_opencl.c) reads gpu_hash_words(JOB_KECCAK256)*4 = 32\n"
    " *     bytes from hits[]; gpu_hash_words(JOB_KECCAK256) returns 8 (already in\n"
    " *     gpujob_opencl.c rev 1.85). No host-side change needed for this op.\n"
    " *\n"
    " * R1 mitigation: single-private-buffer pattern. R2 (register pressure):\n"
    " * Keccak's 25-ulong state (200 bytes) plus 25-ulong B[] scratch in keccakf\n"
    " * is dominant; expected priv_mem_size on gfx1201 around 41-43 KB\n"
    " * (compare against SHA-512 baseline 42,520 B).\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. Cache key: defines_str\n"
    " * \"HASH_WORDS=8,HASH_BLOCK_BYTES=136\" - distinct source text from BLAKE2B-256\n"
    " * (also HASH_WORDS=8, but HASH_BLOCK_BYTES=128) so cache key is unique. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 8\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 136\n"
    "#endif\n"
    "\n"
    "/* Per-algo constants for Keccak-256. */\n"
    "#define KECCAK_RATE       136\n"
    "#define KECCAK_RATE_WORDS  17   /* 136/8 */\n"
    "#define KECCAK_OUT_BYTES   32\n"
    "#define KECCAK_DOMAIN_PAD  0x01\n"
    "\n"
    "typedef struct {\n"
    "    ulong sp[25];          /* sponge state, LE per ulong */\n"
    "    uint  h[HASH_WORDS];   /* exposed digest words, 8 uint32 LE */\n"
    "} template_state;\n"
    "\n"
    "/* Decompose state to exposed digest. KECCAK_OUT_BYTES / 4 = HASH_WORDS uint32. */\n"
    "static inline void template_state_to_h_keccak256(template_state *st) {\n"
    "    for (int i = 0; i < HASH_WORDS / 2; i++) {\n"
    "        ulong v = st->sp[i];\n"
    "        st->h[i * 2]     = (uint)v;\n"
    "        st->h[i * 2 + 1] = (uint)(v >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Absorb the final (possibly partial) block plus padding.\n"
    " * data points to the partial-block slice (0..rem-1 bytes, where rem == len % rate).\n"
    " * Caller has already absorbed all complete rate-aligned blocks. */\n"
    "static inline void keccak256_absorb_pad(ulong *sp, const uchar *data, int rem) {\n"
    "    /* Build the final block in private memory: copy partial bytes, zero the\n"
    "     * rest, then OR in suffix at offset rem and 0x80 at offset rate-1.\n"
    "     * Note: positions rem and rate-1 may collide when rem == rate-1; in that\n"
    "     * case the byte ends up suffix | 0x80 (per Keccak/SHA3 spec). */\n"
    "    uchar block[KECCAK_RATE];\n"
    "    for (int i = 0; i < rem; i++) block[i] = data[i];\n"
    "    for (int i = rem; i < KECCAK_RATE; i++) block[i] = 0;\n"
    "    block[rem]            ^= (uchar)KECCAK_DOMAIN_PAD;\n"
    "    block[KECCAK_RATE - 1] ^= (uchar)0x80;\n"
    "    /* XOR block into state as LE ulong words. */\n"
    "    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {\n"
    "        ulong w = 0;\n"
    "        int b = i * 8;\n"
    "        w |= (ulong)block[b];\n"
    "        w |= (ulong)block[b + 1] << 8;\n"
    "        w |= (ulong)block[b + 2] << 16;\n"
    "        w |= (ulong)block[b + 3] << 24;\n"
    "        w |= (ulong)block[b + 4] << 32;\n"
    "        w |= (ulong)block[b + 5] << 40;\n"
    "        w |= (ulong)block[b + 6] << 48;\n"
    "        w |= (ulong)block[b + 7] << 56;\n"
    "        sp[i] ^= w;\n"
    "    }\n"
    "    keccakf1600(sp);\n"
    "}\n"
    "\n"
    "/* Absorb one complete rate-byte block (no padding). */\n"
    "static inline void keccak256_absorb_full(ulong *sp, const uchar *data) {\n"
    "    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {\n"
    "        ulong w = 0;\n"
    "        int b = i * 8;\n"
    "        w |= (ulong)data[b];\n"
    "        w |= (ulong)data[b + 1] << 8;\n"
    "        w |= (ulong)data[b + 2] << 16;\n"
    "        w |= (ulong)data[b + 3] << 24;\n"
    "        w |= (ulong)data[b + 4] << 32;\n"
    "        w |= (ulong)data[b + 5] << 40;\n"
    "        w |= (ulong)data[b + 6] << 48;\n"
    "        w |= (ulong)data[b + 7] << 56;\n"
    "        sp[i] ^= w;\n"
    "    }\n"
    "    keccakf1600(sp);\n"
    "}\n"
    "\n"
    "/* template_init: zero the 25-ulong sponge state. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    for (int i = 0; i < 25; i++) st->sp[i] = 0UL;\n"
    "}\n"
    "\n"
    "/* template_transform: NOT USED on the sponge path - the template only calls\n"
    " * template_init / template_finalize / template_iterate. Provided as a stub\n"
    " * for interface symmetry with MD-style cores (call-site coverage check). */\n"
    "static inline void template_transform(template_state *st, const uchar *block) {\n"
    "    keccak256_absorb_full(&st->sp[0], block);\n"
    "}\n"
    "\n"
    "/* template_finalize: process all rate-aligned chunks via absorb-and-permute,\n"
    " * then pad the final partial block with the algorithm's domain suffix and\n"
    " * absorb. Extract h[] = first HASH_WORDS uint32 LE of state. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    int pos = 0;\n"
    "    while ((len - pos) >= KECCAK_RATE) {\n"
    "        keccak256_absorb_full(&st->sp[0], data + pos);\n"
    "        pos += KECCAK_RATE;\n"
    "    }\n"
    "    int rem = len - pos;\n"
    "    keccak256_absorb_pad(&st->sp[0], data + pos, rem);\n"
    "    template_state_to_h_keccak256(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: re-hash digest as 2*KECCAK_OUT_BYTES lowercase hex chars.\n"
    " * For Keccak-256 / SHA3-256: 64 hex chars; less than rate=136 so single\n"
    " * partial-block absorb suffices. To keep the helper general (e.g. shared\n"
    " * with longer-output variants where 2*out > rate), we run the same\n"
    " * complete-block absorb loop then pad-and-absorb the remainder. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint snap[HASH_WORDS];\n"
    "    for (int i = 0; i < HASH_WORDS; i++) snap[i] = st->h[i];\n"
    "\n"
    "    /* hex_lc encode HASH_WORDS uint32 LE -> 2*KECCAK_OUT_BYTES chars. */\n"
    "    int hex_chars = 2 * KECCAK_OUT_BYTES;\n"
    "    uchar hex[2 * KECCAK_OUT_BYTES];\n"
    "    for (int i = 0; i < HASH_WORDS; i++) {\n"
    "        uint s = snap[i];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uchar by = (uchar)((s >> (b * 8)) & 0xFFu);\n"
    "            uchar hi = by >> 4, lo = by & 0xFu;\n"
    "            hex[i * 8 + b * 2 + 0] = (hi < 10) ? (uchar)('0' + hi) : (uchar)('a' + (hi - 10));\n"
    "            hex[i * 8 + b * 2 + 1] = (lo < 10) ? (uchar)('0' + lo) : (uchar)('a' + (lo - 10));\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Re-init sponge and absorb hex_chars with padding. */\n"
    "    for (int i = 0; i < 25; i++) st->sp[i] = 0UL;\n"
    "    int pos = 0;\n"
    "    while ((hex_chars - pos) >= KECCAK_RATE) {\n"
    "        keccak256_absorb_full(&st->sp[0], hex + pos);\n"
    "        pos += KECCAK_RATE;\n"
    "    }\n"
    "    int rem = hex_chars - pos;\n"
    "    keccak256_absorb_pad(&st->sp[0], hex + pos, rem);\n"
    "    template_state_to_h_keccak256(st);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe leading 16 bytes (h[0..3]). LE state. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: EMIT_HIT_8 wrapper (Keccak-256 = 8 uint32 LE). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_8((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_8_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
