/* Auto-generated from gpu_sha3_224_core.cl -- do not edit */
static const char gpu_sha3_224_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sha3_224_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha3_224_core.cl - SHA3-224 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 4, 2026-05-03).\n"
    " *\n"
    " * Sponge construction with rate=144 bytes (= 18 ulong), output=28 bytes,\n"
    " * domain suffix=0x06 (NIST FIPS 202 SHA3 family). Distinct from plain\n"
    " * Keccak-224 ONLY in the suffix byte; same rate, same output, same state\n"
    " * decomposition. HASH_WORDS=7, HASH_BLOCK_BYTES=144 = rate.\n"
    " *\n"
    " * Source order: [ gpu_common_str, gpu_md5_rules_str, gpu_sha3_224_core_str,\n"
    " *   gpu_template_str ]. gpu_common_str provides keccakf1600() (rev 1.14+).\n"
    " *\n"
    " * Bytecast invariant: sp[0..3] LE byte image (low 28 bytes) == rhash_sha3\n"
    " * output (mdxfind.c JOB_SHA3_224 line 28754; 28 bytes via rhash_sha3_final).\n"
    " * gpu_hash_words(JOB_SHA3_224) returns 7.\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 7\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 144\n"
    "#endif\n"
    "\n"
    "#define KECCAK_RATE       144\n"
    "#define KECCAK_RATE_WORDS  18\n"
    "#define KECCAK_OUT_BYTES   28\n"
    "#define KECCAK_DOMAIN_PAD  0x06\n"
    "\n"
    "typedef struct {\n"
    "    ulong sp[25];\n"
    "    uint  h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "static inline void template_state_to_h_sha3_224(template_state *st) {\n"
    "    for (int i = 0; i < 3; i++) {\n"
    "        ulong v = st->sp[i];\n"
    "        st->h[i * 2]     = (uint)v;\n"
    "        st->h[i * 2 + 1] = (uint)(v >> 32);\n"
    "    }\n"
    "    st->h[6] = (uint)st->sp[3];\n"
    "}\n"
    "\n"
    "static inline void sha3_224_absorb_pad(ulong *sp, const uchar *data, int rem) {\n"
    "    uchar block[KECCAK_RATE];\n"
    "    for (int i = 0; i < rem; i++) block[i] = data[i];\n"
    "    for (int i = rem; i < KECCAK_RATE; i++) block[i] = 0;\n"
    "    block[rem]            ^= (uchar)KECCAK_DOMAIN_PAD;\n"
    "    block[KECCAK_RATE - 1] ^= (uchar)0x80;\n"
    "    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {\n"
    "        ulong w = 0;\n"
    "        int b = i * 8;\n"
    "        w |= (ulong)block[b];\n"
    "        w |= (ulong)block[b + 1] << 8;\n"
    "        w |= (ulong)block[b + 2] << 16;\n"
    "        w |= (ulong)block[b + 3] << 24;\n"
    "        w |= (ulong)block[b + 4] << 32;\n"
    "        w |= (ulong)block[b + 5] << 40;\n"
    "        w |= (ulong)block[b + 6] << 48;\n"
    "        w |= (ulong)block[b + 7] << 56;\n"
    "        sp[i] ^= w;\n"
    "    }\n"
    "    keccakf1600(sp);\n"
    "}\n"
    "\n"
    "static inline void sha3_224_absorb_full(ulong *sp, const uchar *data) {\n"
    "    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {\n"
    "        ulong w = 0;\n"
    "        int b = i * 8;\n"
    "        w |= (ulong)data[b];\n"
    "        w |= (ulong)data[b + 1] << 8;\n"
    "        w |= (ulong)data[b + 2] << 16;\n"
    "        w |= (ulong)data[b + 3] << 24;\n"
    "        w |= (ulong)data[b + 4] << 32;\n"
    "        w |= (ulong)data[b + 5] << 40;\n"
    "        w |= (ulong)data[b + 6] << 48;\n"
    "        w |= (ulong)data[b + 7] << 56;\n"
    "        sp[i] ^= w;\n"
    "    }\n"
    "    keccakf1600(sp);\n"
    "}\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    for (int i = 0; i < 25; i++) st->sp[i] = 0UL;\n"
    "}\n"
    "\n"
    "static inline void template_transform(template_state *st, const uchar *block) {\n"
    "    sha3_224_absorb_full(&st->sp[0], block);\n"
    "}\n"
    "\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    int pos = 0;\n"
    "    while ((len - pos) >= KECCAK_RATE) {\n"
    "        sha3_224_absorb_full(&st->sp[0], data + pos);\n"
    "        pos += KECCAK_RATE;\n"
    "    }\n"
    "    int rem = len - pos;\n"
    "    sha3_224_absorb_pad(&st->sp[0], data + pos, rem);\n"
    "    template_state_to_h_sha3_224(st);\n"
    "}\n"
    "\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint snap[HASH_WORDS];\n"
    "    for (int i = 0; i < HASH_WORDS; i++) snap[i] = st->h[i];\n"
    "\n"
    "    int hex_chars = 2 * KECCAK_OUT_BYTES;\n"
    "    uchar hex[2 * KECCAK_OUT_BYTES];\n"
    "    for (int i = 0; i < HASH_WORDS; i++) {\n"
    "        uint s = snap[i];\n"
    "        for (int b = 0; b < 4; b++) {\n"
    "            uchar by = (uchar)((s >> (b * 8)) & 0xFFu);\n"
    "            uchar hi = by >> 4, lo = by & 0xFu;\n"
    "            hex[i * 8 + b * 2 + 0] = (hi < 10) ? (uchar)('0' + hi) : (uchar)('a' + (hi - 10));\n"
    "            hex[i * 8 + b * 2 + 1] = (lo < 10) ? (uchar)('0' + lo) : (uchar)('a' + (lo - 10));\n"
    "        }\n"
    "    }\n"
    "\n"
    "    for (int i = 0; i < 25; i++) st->sp[i] = 0UL;\n"
    "    int pos = 0;\n"
    "    while ((hex_chars - pos) >= KECCAK_RATE) {\n"
    "        sha3_224_absorb_full(&st->sp[0], hex + pos);\n"
    "        pos += KECCAK_RATE;\n"
    "    }\n"
    "    int rem = hex_chars - pos;\n"
    "    sha3_224_absorb_pad(&st->sp[0], hex + pos, rem);\n"
    "    template_state_to_h_sha3_224(st);\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_7((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_7_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
