/* Auto-generated from gpu_template.cl -- do not edit */
static const char gpu_template_str[] =
    "/*\n"
    " * $Revision: 1.16 $\n"
    " * $Log: gpu_template.cl,v $\n"
    " * Revision 1.16  2026/05/11 14:16:27  dlr\n"
    " * Phase 1.8 kernel-side REVERT (gpu_template.cl): remove the runtime-bounded `for (uint iter_idx = 0u; iter_idx < inner_iter; iter_idx++)` wrap at line ~439 (and matching close at ~701). Caused 2.19× Pascal kernel regression (NVCC register pressure spike on inner_iter=1 codegen path; whole-kernel register allocator forced worst-case allocation). Confirmed via task #239 mdx-debug spike on JOB_MD5 BF (Phase 1.5 1.18 GH/s → Phase 1.8 0.54 GH/s on fpga 1080). User observed e31 regression which traced to same root cause — every algo using gpu_template.cl (incl JOB_MD5SALT) inherited the wrap. Phase 1.8c body-duplication attempt (Phase 0 defer) confirmed whole-kernel reg-alloc scoping was the issue. Also removed iter_idx variable, `if (iter_idx > 0u) { ... }` save/restore block, and Phase 1.8 mask_idx_abs += iter_idx*mask_size shift (now mask_idx_abs = mask_idx_abs_base directly). Combined_ridx unsalted encoding reverted to Phase 1.7 form `rule_idx * mask_size + mask_idx_local`. Phase 1.5 ulong widening of mask_idx_abs PRESERVED (correctness for >4G keyspaces). LOC delta -35 (769 → 734). Salted combined_ridx unchanged (host servo guards salted with inner_iter=1). Validated on fpga 1080: V1 raw MD5 BF 1.021 GH/s (restored Phase 1.7 baseline); V2 e31 MD5SALT 4-digit 3/3 cracks 0.03s; V3 non-BF wordlist 3/3; V4 10-digit BF (>4G keyspace) 3/3 cracks at 1.897 GH/s — Phase 1.5 widening preserved.\n"
    " *\n"
    " * Revision 1.15  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_template.cl — generic dispatch-template kernel skeleton (Memo B\n"
    " * Phase B2).\n"
    " *\n"
    " * STATUS: B2 — STRUCTURAL PREREQUISITE, default OFF, MD5-only.\n"
    " *\n"
    " * The template body provides the SHARED infrastructure that every\n"
    " * algorithm template-instantiated under Memo B Phase B4-B7 will use:\n"
    " *\n"
    " *   - payload decode (B1 coalesced wire format from\n"
    " *     project_memo_b_dispatch_template.md §1)\n"
    " *   - geometry (gid -> (word_idx, rule_idx))\n"
    " *   - rule walker (apply_rule from gpu_md5_rules.cl, shared verbatim)\n"
    " *   - rejection + no-op detection (preserves feedback_no_rule_pass.md)\n"
    " *   - iterated probe loop (drives template_digest_compare in a\n"
    " *     loop with template_iterate steps)\n"
    " *   - cursor skeleton (read but unused in B2; B3 wires real restart\n"
    " *     logic per Memo B §2)\n"
    " *   - overflow back-pressure (today's \"warn at 90%, drop\" semantics\n"
    " *     only -- full grow/split/drain is B3)\n"
    " *\n"
    " * The template invokes per-algorithm extension functions defined in\n"
    " * gpu_<algo>_core.cl (this build: gpu_md5_core.cl):\n"
    " *\n"
    " *   template_state              -- algorithm-defined state struct\n"
    " *   template_init               -- algorithm-defined IV install\n"
    " *   template_transform          -- per-block compress\n"
    " *   template_finalize           -- pad + finalize\n"
    " *   template_iterate            -- -i loop step (hex_lc + rehash)\n"
    " *   template_digest_compare     -- probe wrapper\n"
    " *   template_emit_hit           -- HASH_WORDS-aware EMIT_HIT_N wrapper\n"
    " *   HASH_BLOCK_BYTES, HASH_WORDS -- compile-time geometry\n"
    " *\n"
    " * Build sources passed to clCreateProgramWithSource (in this order):\n"
    " *\n"
    " *   gpu_common_str        -- md5_block, EMIT_HIT_*, OCLParams,\n"
    " *                            probe_compact_idx, hex helpers\n"
    " *   gpu_md5_rules_str     -- apply_rule (shared rules walker)\n"
    " *   gpu_md5_core_str      -- algorithm geometry + 4 extension fns\n"
    " *   gpu_template_str      -- this file (template_phase0 kernel)\n"
    " *\n"
    " * Cache key (R3 mitigation): gpu_kernel_cache_build_program is now\n"
    " * passed defines_str = \"HASH_WORDS=4,HASH_BLOCK_BYTES=64\" so distinct\n"
    " * algorithm tuples receive distinct cache keys even though the\n"
    " * gpu_template.cl source text is identical.\n"
    " *\n"
    " * Side-by-side with gpu_md5_rules.cl rev 1.28+: B2 ships this kernel\n"
    " * alongside md5_rules_phase0; the production path remains the latter\n"
    " * unless MDXFIND_GPU_TEMPLATE=md5 is set in the environment. Default\n"
    " * off keeps R2 (register pressure on AMD gfx1201) from blocking\n"
    " * merge -- B5 flips the default once enough algorithms are wired\n"
    " * through the template that the side-by-side kernels become carrying\n"
    " * cost.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): the template\n"
    " * keeps the single-private-buffer pattern from gpu_md5_rules.cl r28.\n"
    " * No __private uchar* helper functions; no addrspace-cast ternary\n"
    " * pointers. Inline modifications only.\n"
    " *\n"
    " * Kernel signature MUST MATCH md5_rules_phase0 (gpu_md5_rules.cl) so\n"
    " * gpu_opencl_dispatch_md5_rules can swap kernels by changing only the\n"
    " * cl_kernel handle. 14 args, payload first.\n"
    " */\n"
    "\n"
    "/* Phase 6 BCRYPT (2026-05-08): the BCRYPT carrier needs a workgroup-shared\n"
    " * __local buffer (Eksblowfish S-boxes, 4 KB per lane × BCRYPT_WG_SIZE=8\n"
    " * lanes = 32 KB per WG) — slab gpu_bcrypt.cl precedent. OpenCL 1.2 §6.5.3\n"
    " * forbids `__local` declarations inside non-kernel functions, so we\n"
    " * declare it INSIDE template_phase0 (kernel-function scope) and pass it\n"
    " * as a __local pointer + per-lane lid into template_finalize. The 8-arg\n"
    " * salted template_finalize signature is gated on\n"
    " * GPU_TEMPLATE_HAS_LOCAL_BUFFER (set only by gpu_opencl_template_compile_-\n"
    " * bcrypt's build_opts -D list). All other algorithms (60+) compile\n"
    " * with the macro UNDEFINED — the preprocessor strips the ifdef block\n"
    " * entirely so their build output is byte-identical to pre-Phase 6.\n"
    " *\n"
    " * The reqd_work_group_size attribute pins WG=BCRYPT_WG_SIZE (8) at\n"
    " * kernel-decl time — required because the __local buffer is sized\n"
    " * relative to the WG, and the dispatch-side `local = BCRYPT_WG_SIZE`\n"
    " * override (gpu_opencl.c) must match. Mirror of slab gpu_bcrypt.cl\n"
    " * line 427. */\n"
    "\n"
    "/* B1+lane-batch MD5SALT pre-salt hoist scaffold (2026-05-09 experiment):\n"
    " * introduces an optional dispatch shape gated behind GPU_TEMPLATE_HAS_PRE_SALT.\n"
    " * Purpose: lift the password-only portion of a salted hash (e.g. the\n"
    " * inner MD5(password) of MD5SALT's MD5(MD5(password) || salt)) OUT of the\n"
    " * per-(word,rule,mask,salt) inner loop and into a per-(word,rule,mask,\n"
    " * salt_chunk) pre-pass, where salt_chunk groups SALT_BATCH consecutive\n"
    " * salts. The salt axis is replaced with a salt_chunk axis of size\n"
    " * ceil(num_salts_per_page / SALT_BATCH); each lane processes SALT_BATCH\n"
    " * salts serially after computing inner+hex once. Tunable via\n"
    " * SALT_BATCH compile-time macro (default 16; pass via -DSALT_BATCH=N).\n"
    " *\n"
    " * Mutual exclusion: GPU_TEMPLATE_HAS_PRE_SALT is mutually exclusive with\n"
    " * GPU_TEMPLATE_HAS_LOCAL_BUFFER. It REQUIRES GPU_TEMPLATE_HAS_SALT.\n"
    " *\n"
    " * Hook signatures (defined by the algorithm core, e.g. gpu_md5salt_core.cl):\n"
    " *\n"
    " *   typedef struct { uint M[16]; uint inner_len; } template_pre_salt_state;\n"
    " *\n"
    " *   void template_pre_salt(uchar *buf, int new_len, uint algo_mode,\n"
    " *                          template_pre_salt_state *pre_state);\n"
    " *       For algo_modes that benefit from inner-MD5+hex hoisting (mode 0),\n"
    " *       computes the password-only digest and stores hex-encoded result in\n"
    " *       pre_state->M with pre_state->inner_len == 32 (or whatever inner\n"
    " *       layout the algorithm uses). For algo_modes that don't benefit\n"
    " *       (modes 1-6), sets pre_state->inner_len = 0xFFFFFFFFu (sentinel)\n"
    " *       so template_finalize_post falls through to the legacy path.\n"
    " *\n"
    " *   void template_finalize_post(template_state *st,\n"
    " *                               const template_pre_salt_state *pre_state,\n"
    " *                               const uchar *buf, int new_len,\n"
    " *                               __global const uchar *salt, uint slen,\n"
    " *                               uint algo_mode);\n"
    " *       For non-sentinel pre_state: completes outer-MD5(hex32 || salt).\n"
    " *       For sentinel pre_state: calls into legacy template_finalize().\n"
    " *\n"
    " * Per-dispatch wall-clock target 250-500 ms with num_salts_per_page +\n"
    " * SALT_BATCH sized so the inner serial loop dominates without any single\n"
    " * kernel exceeding 500 ms. The host (gpu_opencl.c) computes\n"
    " * chunks_per_page = (num_salts_per_page + SALT_BATCH - 1) / SALT_BATCH\n"
    " * for the NDRange salt axis; the kernel performs the same calc to bound\n"
    " * the inner loop.\n"
    " *\n"
    " * Scaffold-only: when GPU_TEMPLATE_HAS_PRE_SALT is undefined (every\n"
    " * algo today), the preprocessor strips every HAS_PRE_SALT-gated block —\n"
    " * non-opt-in algorithms compile and execute byte-identically to pre-B1. */\n"
    "#ifndef SALT_BATCH\n"
    "#define SALT_BATCH 16\n"
    "#endif\n"
    "\n"
    "#ifdef GPU_TEMPLATE_HAS_LOCAL_BUFFER\n"
    "__kernel __attribute__((reqd_work_group_size(BCRYPT_WG_SIZE, 1, 1)))\n"
    "#else\n"
    "__kernel\n"
    "#endif\n"
    "void template_phase0(\n"
    "    __global uchar        *payload,         /* coalesced: params + hit_count + word_offset + packed */\n"
    "    __global const uchar  *rule_program,\n"
    "    __global const uint   *rule_offset,\n"
    "    __global const uint   *compact_fp,\n"
    "    __global const uint   *compact_idx,\n"
    "    __global const uchar  *hash_data_buf,\n"
    "    __global const ulong  *hash_data_off,\n"
    "    __global const ushort *unused_hash_data_len,\n"
    "    __global uint         *hits,\n"
    "    __global const ulong  *overflow_keys,\n"
    "    __global const uchar  *overflow_hashes,\n"
    "    __global const uint   *overflow_offsets,\n"
    "    __global const ushort *unused_overflow_lengths,\n"
    "    __global volatile uint *hashes_shown,\n"
    "    /* B7.1-B7.5: multi-position prepend+append mask charsets. Layout is\n"
    "     * row-major by position index, using the SLAB-PATH CONVENTION (see\n"
    "     * gpu_kernels.cl md5_mask_batch / gpu_mask_desc): positions\n"
    "     * [0..n_prepend) are prepend rows, positions [n_prepend..n_prepend+\n"
    "     * n_append) are append rows. Row i at offset i*256 holds the 256-byte\n"
    "     * charset table for that position; only the first mask_sizes[i] bytes\n"
    "     * of each row are valid. Total capacity is MASK_POS_CAP=32 rows\n"
    "     * (16 prepend + 16 append max), so the buffer is 32*256=8192 bytes.\n"
    "     *\n"
    "     * B7.1 was single-position append (only row 0 read). B7.2 extended to\n"
    "     * multi-position append (rows [0..n_append) for the n_prepend==0 case).\n"
    "     * B7.3 adds single-position prepend (row 0 holds the prepend charset\n"
    "     * when n_prepend==1; n_append==0). B7.4 extends to multi-position\n"
    "     * prepend (rows [0..n_prepend) for the n_append==0 case). B7.5 mixes\n"
    "     * both: rows [0..n_prepend) prepend, rows [n_prepend..n_prepend+\n"
    "     * n_append) append (matches slab convention exactly).\n"
    "     *\n"
    "     * For B7.2 backward-compat (n_prepend==0): row 0 still holds append\n"
    "     * position 0's charset — the layout reduces to the B7.2 packing.\n"
    "     * Byte-exact backward-compatible. */\n"
    "    __global const uchar  *mask_charsets,\n"
    "    /* B7.1-B7.5: per-position charset sizes. mask_sizes[i] gives the count\n"
    "     * of valid bytes in mask_charsets[i*256..i*256+256). Only the first\n"
    "     * (n_prepend + n_append) entries are read; the rest is sentinel of 1\n"
    "     * (so any stray divmod terminates safely). The kernel uses mask_sizes[]\n"
    "     * to decompose mask_idx into per-position indices via successive\n"
    "     * divmod (last position innermost in each section). */\n"
    "    __global const uint   *mask_sizes\n"
    "    /* B6 salt-axis (2026-05-06): three appended args, gated behind\n"
    "     * #ifdef GPU_TEMPLATE_HAS_SALT. Layout mirrors gpu_md5salt.cl slab path:\n"
    "     *   salt_buf  -- concatenated salt bytes for the WHOLE salt list (not\n"
    "     *                paged); salt N starts at salt_offsets[N], length is\n"
    "     *                salt_lens[N]. The host uploads the full list once via\n"
    "     *                gpu_opencl_set_salts() per batch.\n"
    "     *   salt_off  -- per-salt byte offset into salt_buf, uint32 array.\n"
    "     *   salt_len  -- per-salt byte length, uint16 (ushort) array\n"
    "     *                (matches gpu_md5salt.cl:3 + host uint16_t at\n"
    "     *                gpu_opencl.c:2580-2591 — see §13.3).\n"
    "     *\n"
    "     * The unsalted instantiation elides these args entirely; the kernel\n"
    "     * signature stays at 16 args for the 32 already-validated cores.\n"
    "     * Salted variant signature is 19 args. */\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    , __global const uchar  *salt_buf\n"
    "    , __global const uint   *salt_off\n"
    "    , __global const ushort *salt_lens\n"
    "#endif\n"
    "    )\n"
    "{\n"
    "    /* Decode payload header. params struct sits at offset 0; copy to\n"
    "     * private memory so subsequent field accesses stay in registers. */\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    /* B7.1-B7.5 mask geometry: third axis is mask_idx in [0, mask_size).\n"
    "     * When no mask is active mask_size == 1 and the kernel collapses to\n"
    "     * the pre-B7 (word, rule) behavior — one-iteration mask loop, no\n"
    "     * append, no prepend.\n"
    "     *\n"
    "     * mask_size is threaded through OCLParams.num_salts. The salts field\n"
    "     * is unused in the rules-engine / template dispatch path (the slab\n"
    "     * path's salted kernels have their own kern_packed_fam[] entries),\n"
    "     * so we repurpose it as mask_size — same convention as num_masks\n"
    "     * being repurposed as n_rules in this dispatch path. The host sets\n"
    "     * num_salts = product(mask_sizes[0..n_prepend+n_append)) when MaskCount\n"
    "     * is active and the (n_prepend, n_append) configuration is in scope\n"
    "     * (B7.5 scope: n_prepend in [0, MASK_POS_CAP], n_append in [0,\n"
    "     * MASK_POS_CAP], n_prepend + n_append >= 1, both bounded by\n"
    "     * MASK_POS_CAP=16); otherwise num_salts = 1.\n"
    "     *\n"
    "     * B7.1: n_append==1 only.\n"
    "     * B7.2: n_prepend==0, n_append in [1, MASK_POS_CAP].\n"
    "     * B7.3: n_prepend==1, n_append==0.\n"
    "     * B7.4: n_prepend in [1, MASK_POS_CAP], n_append==0.\n"
    "     * B7.5: n_prepend in [0, MASK_POS_CAP], n_append in [0, MASK_POS_CAP],\n"
    "     *       n_prepend + n_append >= 1.\n"
    "     * B7.6: same as B7.5; user-defined classes are charset-byte changes\n"
    "     *       in the upload, no kernel change.\n"
    "     * B7.8: cap lifted from 8 to 16 per side (32 total rows). Same\n"
    "     *       divmod loop, just larger bound. */\n"
    "    uint mask_active = ((params.n_prepend >= 1u) || (params.n_append >= 1u)) ? 1u : 0u;\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    /* B6 salt-axis (2026-05-06): num_salts is overloaded as\n"
    "     *   num_salts = mask_size * num_salts_per_page\n"
    "     * so the host can carry both axes in a single uint32 field without\n"
    "     * touching the OCLParams wire format. params.num_salts_per_page is\n"
    "     * the new uint64 slot at offset 112 (was reserved64[0]). When\n"
    "     * num_salts_per_page == 1 (no salt paging) and num_salts == mask_size\n"
    "     * the math collapses to the pre-B6 layout. */\n"
    "    uint num_salts_per_page = (uint)params.num_salts_per_page;\n"
    "    if (num_salts_per_page == 0u) num_salts_per_page = 1u;\n"
    "    uint mask_size = mask_active\n"
    "        ? (params.num_salts / num_salts_per_page)\n"
    "        : 1u;\n"
    "    if (mask_size == 0u) mask_size = 1u;\n"
    "#ifdef GPU_TEMPLATE_HAS_PRE_SALT\n"
    "    /* Lane-level salt batching (2026-05-09 experiment): salt axis is\n"
    "     * replaced by salt_chunk axis of size ceil(num_salts_per_page /\n"
    "     * SALT_BATCH). Each lane processes SALT_BATCH salts serially after\n"
    "     * a single template_pre_salt() call, amortising the inner-MD5+hex\n"
    "     * work across SALT_BATCH outer-MD5 evaluations. */\n"
    "    uint chunks_per_page = (num_salts_per_page + (uint)SALT_BATCH - 1u)\n"
    "                         / (uint)SALT_BATCH;\n"
    "    if (chunks_per_page == 0u) chunks_per_page = 1u;\n"
    "    uint total = n_words * n_rules * mask_size * chunks_per_page;\n"
    "#else\n"
    "    /* gid layout (innermost -> outermost): mask -> word -> rule -> salt.\n"
    "     * total = n_words * n_rules * mask_size * num_salts_per_page. */\n"
    "    uint total = n_words * n_rules * mask_size * num_salts_per_page;\n"
    "#endif\n"
    "#else\n"
    "    uint mask_size = mask_active ? params.num_salts : 1u;\n"
    "    if (mask_size == 0u) mask_size = 1u;\n"
    "    uint total = n_words * n_rules * mask_size;\n"
    "#endif\n"
    "\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    /* gid -> (mask_idx, word_idx, rule_idx[, salt_local]) with mask\n"
    "     * innermost so the existing (word, rule) lex-ordering is preserved\n"
    "     * at mask_size==1. mask innermost also keeps the cursor protocol's\n"
    "     * lex order (rule_idx, word_idx) monotonic across overflow re-issues. */\n"
    "    uint mask_idx_local = gid % mask_size;\n"
    "    uint gid_wr         = gid / mask_size;\n"
    "    uint word_idx       = gid_wr % n_words;\n"
    "    /* BF chunk-as-job (2026-05-10 Phase 1.5): kernel emits LOCAL mask_idx\n"
    "     * (within-chunk, fits uint32 since mspw < 4G) for hit emit; uses\n"
    "     * ABSOLUTE mask_idx (ulong) for hash compute. Host re-adds at hit-replay.\n"
    "     * Reverses Tranche 2's \"kernel emits absolute\" + Tranche 3's \"host\n"
    "     * doesn't re-add\" — those interlocked to truncate above 2^32 and the\n"
    "     * <=4G gate disabled mask decode entirely for >4G keyspaces.\n"
    "     *\n"
    "     * For non-BF (mask_start == 0, mask_offset_per_word == 0), abs == local.\n"
    "     * Cost: small ulong divmod overhead in charset decompose; MD5 compute\n"
    "     * remains the dominant kernel cost. Per project_bf_chunk_as_job.md Q1.\n"
    "     *\n"
    "     * BF Phase 1.8 inner_iter wrap REVERTED (2026-05-10): the runtime-bounded\n"
    "     * for-loop introduced a 2.19× Pascal regression measured in task #239\n"
    "     * (raw MD5 BF) and a parallel JOB_MD5SALT (e31) regression. Kernel is\n"
    "     * back to Phase 1.7's single-pass shape. Host-side machinery\n"
    "     * (params.inner_iter, adaptive_bf_chunk_size servo, jobg bf_inner_iter)\n"
    "     * is left as dead-but-harmless; cleanup can happen separately. */\n"
    "    ulong mask_idx_abs_base = params.mask_start\n"
    "                       + (ulong)word_idx * (ulong)params.mask_offset_per_word\n"
    "                       + (ulong)mask_idx_local;\n"
    "    uint gid_wrr  = gid_wr / n_words;\n"
    "    uint rule_idx = gid_wrr % n_rules;\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "#ifdef GPU_TEMPLATE_HAS_PRE_SALT\n"
    "    /* Pre-salt path: the salt axis is folded into a salt_chunk axis where\n"
    "     * each chunk covers SALT_BATCH consecutive salts. The actual salt_local\n"
    "     * (and salt_idx_global) are computed inside the per-salt loop below. */\n"
    "    uint salt_chunk = gid_wrr / n_rules;\n"
    "    uint salt_base  = salt_chunk * (uint)SALT_BATCH;\n"
    "#else\n"
    "    /* Salt is the outermost axis. salt_local indexes into the current\n"
    "     * dispatch's page; salt_idx_global = params.salt_start + salt_local\n"
    "     * indexes into the host's salt list (gpu_pack_salts → b_salt_data /\n"
    "     * b_salt_off / b_salt_lens). */\n"
    "    uint salt_local      = gid_wrr / n_rules;\n"
    "    uint salt_idx_global = (uint)params.salt_start + salt_local;\n"
    "#endif\n"
    "#endif\n"
    "\n"
    "    /* B3 cursor check (Memo B §2). On a re-issue dispatch following hit\n"
    "     * buffer overflow, lanes whose (rule, word, mask) lex-precedes the\n"
    "     * cursor early-return. cursor=0 == identical to pre-B3 behavior.\n"
    "     * B7.1: cursor compares only on (rule, word); within a (rule, word)\n"
    "     * pair, mask_idx is processed entirely before advance. The kernel's\n"
    "     * EMIT macro CAS-min's on lane gid, so on overflow the host sees the\n"
    "     * lex-first lane gid and re-derives (mask, word, rule) the same way. */\n"
    "    if (params.input_cursor_start > 0u || params.rule_cursor_start > 0u) {\n"
    "        if (rule_idx < params.rule_cursor_start) return;\n"
    "        if (rule_idx == params.rule_cursor_start &&\n"
    "            word_idx < params.input_cursor_start) return;\n"
    "    }\n"
    "\n"
    "    /* Deterministic sub-buffer pointers (B1 wire format). */\n"
    "    __global volatile uint *hit_count = (__global volatile uint *)(payload + 128);\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "\n"
    "    /* B3 overflow channel pointers. See gpu_common.cl §B3 protocol. */\n"
    "    __global volatile uint *ovr_set =\n"
    "        (__global volatile uint *)(payload + 100);\n"
    "    __global volatile uint *ovr_gid =\n"
    "        (__global volatile uint *)(payload + 104);\n"
    "\n"
    "    /* Single private buffer; same RULE_BUF_MAX as gpu_md5_rules.cl\n"
    "     * (the macro is defined there and visible to us via the shared\n"
    "     * compile unit). 16-byte aligned for any vectorized fast paths. */\n"
    "    __attribute__((aligned(16))) uchar buf[RULE_BUF_MAX];\n"
    "\n"
    "    /* Phase 6 BCRYPT (2026-05-08): workgroup-shared __local buffer for the\n"
    "     * Eksblowfish S-boxes (4 × 256 uint = 4 KB per lane × BCRYPT_WG_SIZE\n"
    "     * lanes = 32 KB per WG). Declared at kernel-function scope per\n"
    "     * OpenCL 1.2 §6.5.3 (which forbids __local in non-kernel functions);\n"
    "     * passed by pointer to template_finalize via the 8-arg signature\n"
    "     * below (gated on GPU_TEMPLATE_HAS_LOCAL_BUFFER). When the macro is\n"
    "     * UNDEFINED (every algo other than BCRYPT), the preprocessor strips\n"
    "     * this block entirely — non-BCRYPT instantiations are byte-identical\n"
    "     * to pre-Phase 6. Mirrors slab gpu_bcrypt.cl line 511. The §6.5.3\n"
    "     * spec compliance note: __local declarations after divergent control\n"
    "     * flow (the gid >= total early return at line 186) is empirically\n"
    "     * accepted by Pascal NVCC + AMD ROCm + Mali Rusticl per the slab's\n"
    "     * ship history; Phase 4 4-cell smoke validates each vendor. */\n"
    "#ifdef GPU_TEMPLATE_HAS_LOCAL_BUFFER\n"
    "    __local uint sbox_pool[BCRYPT_WG_SIZE * GPU_TEMPLATE_LOCAL_BUFFER_PER_LANE];\n"
    "#endif\n"
    "\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    int wlen = (int)words[wpos++];\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "    for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "    uint rpos = rule_offset[rule_idx];\n"
    "\n"
    "    /* Synthetic no-rule discriminator (preserves feedback_no_rule_pass.md\n"
    "     * semantics; mirrors gpu_md5_rules.cl rev 1.28). The first byte being\n"
    "     * NUL means k==0 at apply_rule entry == the synthetic \":\" pass. */\n"
    "    int is_no_rule = (rule_program[rpos] == 0);\n"
    "    int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "\n"
    "    /* Rejection sentinel: apply_rule fired a `_ < > ! / ( )` op. */\n"
    "    if (new_len < 0) return;\n"
    "\n"
    "    /* No-op detection: if at least one op was processed AND the post-\n"
    "     * rule buffer is bit-identical to the input, the synthetic \":\" pass\n"
    "     * already covered this candidate -- skip hash + probe. Per\n"
    "     * feedback_no_rule_pass.md: with masks active, BOTH the no-rule pass\n"
    "     * AND each rule iterate every mask, so the same (word, mask_idx)\n"
    "     * coordinate is already covered by the synthetic \":\" pass at this\n"
    "     * mask_idx — the skip remains correct. */\n"
    "    if (!is_no_rule && new_len == wlen) {\n"
    "        int changed = 0;\n"
    "        for (int i = 0; i < wlen; i++) {\n"
    "            if (buf[i] != words[wpos + i]) { changed = 1; break; }\n"
    "        }\n"
    "        if (!changed) return;\n"
    "    }\n"
    "\n"
    "    /* B7.1-B7.5 mask: decompose mask_idx into prepend+append per-position\n"
    "     * indices and modify buf in-place. Slab convention (matches\n"
    "     * gpu_kernels.cl md5_mask_batch and gpu_mask_desc layout):\n"
    "     *\n"
    "     *   mask_idx = prepend_idx * append_combos + append_idx\n"
    "     *   append_combos = product(mask_sizes[n_prepend..n_prepend+n_append))\n"
    "     *\n"
    "     * Within each section the LAST position (highest index) is innermost\n"
    "     * / cycles fastest, matching the slab path's per-position decomposition\n"
    "     * (`for i = n-1; i >= 0; i--` style).\n"
    "     *\n"
    "     * mask_charsets is row-major with the slab convention: rows\n"
    "     * [0..n_prepend) hold prepend charsets, rows [n_prepend..n_prepend+\n"
    "     * n_append) hold append charsets. Total kernel cap is MASK_POS_CAP=16\n"
    "     * per section so positions stay below 32 rows.\n"
    "     *\n"
    "     * Modification order:\n"
    "     *   1. (Optional) shift buf right by n_prepend bytes to make room.\n"
    "     *   2. Write prepend chars into buf[0..n_prepend).\n"
    "     *   3. Write append chars into buf[new_len..new_len+n_append).\n"
    "     *   4. new_len += n_prepend + n_append.\n"
    "     *\n"
    "     * Backward-compat with B7.1+B7.2 (n_prepend==0): step 1 is a no-op\n"
    "     * and step 2 is skipped; rows [0..n_append) are append rows — exact\n"
    "     * same kernel-side behavior as B7.2. mask_charsets[0*256+...] reads\n"
    "     * the same byte. Byte-exact backward-compatible.\n"
    "     *\n"
    "     * Bounds-checked against RULE_BUF_LIMIT for safety. */\n"
    "    uint npre = params.n_prepend;\n"
    "    uint napp = params.n_append;\n"
    "    if (npre > 16u) npre = 16u;\n"
    "    if (napp > 16u) napp = 16u;\n"
    "\n"
    "    /* BF Phase 1.8 inner_iter wrap REVERTED (2026-05-10): mask_idx_abs is\n"
    "     * the base value computed above; no per-iter shift. */\n"
    "    ulong mask_idx_abs = mask_idx_abs_base;\n"
    "\n"
    "    if (npre >= 1u || napp >= 1u) {\n"
    "        /* Compute append_combos for the prepend/append split.\n"
    "         * Phase 1.5 (2026-05-10): widened to ulong because the product can\n"
    "         * exceed 2^32 for >9-position masks of size 10+ (e.g., ?d^10 = 1e10).\n"
    "         * Pre-Phase-1.5 this was uint; mask_idx < 4G constrained the\n"
    "         * keyspace so append_combos truncation didn't bite. With mask_idx_abs\n"
    "         * now ulong and >4G keyspaces in scope, append_combos MUST be ulong\n"
    "         * or the divmod produces garbage past the uint32 wrap point. */\n"
    "        ulong append_combos = 1u;\n"
    "        for (uint j = 0u; j < napp; j++) {\n"
    "            uint sz = mask_sizes[npre + j];\n"
    "            if (sz == 0u) sz = 1u;\n"
    "            append_combos *= (ulong)sz;\n"
    "        }\n"
    "        if (append_combos == 0u) append_combos = 1u;\n"
    "        /* Phase 1.5 (2026-05-10): use ABSOLUTE mask_idx (ulong) for charset\n"
    "         * decompose so chunks past keyspace_offset 2^32 receive the correct\n"
    "         * per-position character indices. The divmod loop below truncates\n"
    "         * each per-position index to uint after `% psize` (psize <= 256),\n"
    "         * so prepend_idx / append_idx are kept as ulong here. */\n"
    "        ulong prepend_idx = mask_idx_abs / append_combos;\n"
    "        ulong append_idx  = mask_idx_abs % append_combos;\n"
    "\n"
    "        /* Step 1: shift buf right by npre bytes to make room at the front\n"
    "         * (only when npre > 0). Iterate from high to low to avoid clobber. */\n"
    "        if (npre > 0u) {\n"
    "            uint shift_dst_end = (uint)new_len + npre;\n"
    "            if (shift_dst_end > RULE_BUF_LIMIT) {\n"
    "                /* Truncate the shift to keep within bounds. */\n"
    "                if ((uint)new_len + npre > RULE_BUF_LIMIT) {\n"
    "                    /* Drop trailing bytes that would exceed the limit. */\n"
    "                    if (new_len > (int)(RULE_BUF_LIMIT - npre))\n"
    "                        new_len = (int)(RULE_BUF_LIMIT - npre);\n"
    "                }\n"
    "            }\n"
    "            for (int i = new_len - 1; i >= 0; i--) {\n"
    "                buf[i + (int)npre] = buf[i];\n"
    "            }\n"
    "        }\n"
    "\n"
    "        /* Step 2: write prepend chars at buf[0..npre).\n"
    "         * Decompose prepend_idx with last position innermost (i==npre-1\n"
    "         * cycles fastest). Each iteration: pidx = remaining % size_i;\n"
    "         * remaining /= size_i; buf[i] = mask_charsets[i*256 + pidx]. */\n"
    "        if (npre > 0u) {\n"
    "            /* Phase 1.5: remaining is ulong because prepend_idx is ulong;\n"
    "             * pidx fits uint (psize <= 256 enforced by host). */\n"
    "            ulong remaining = prepend_idx;\n"
    "            for (uint k = 0u; k < npre; k++) {\n"
    "                uint i = npre - 1u - k;\n"
    "                uint psize = mask_sizes[i];\n"
    "                if (psize == 0u) psize = 1u;\n"
    "                uint pidx = (uint)(remaining % (ulong)psize);\n"
    "                remaining /= (ulong)psize;\n"
    "                if (i < RULE_BUF_LIMIT) {\n"
    "                    buf[i] = mask_charsets[i * 256u + pidx];\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "\n"
    "        /* Step 3: write append chars at buf[new_len + npre .. new_len +\n"
    "         * npre + napp). Same decomposition order. mask_charsets row index\n"
    "         * for append position j is (npre + j). */\n"
    "        if (napp > 0u) {\n"
    "            uint append_base = (uint)new_len + npre;\n"
    "            /* Phase 1.5: remaining is ulong because append_idx is ulong;\n"
    "             * pidx fits uint (psize <= 256 enforced by host). */\n"
    "            ulong remaining = append_idx;\n"
    "            for (uint k = 0u; k < napp; k++) {\n"
    "                uint i = napp - 1u - k;\n"
    "                uint row = npre + i;\n"
    "                uint psize = mask_sizes[row];\n"
    "                if (psize == 0u) psize = 1u;\n"
    "                uint pidx = (uint)(remaining % (ulong)psize);\n"
    "                remaining /= (ulong)psize;\n"
    "                uint dst = append_base + i;\n"
    "                if (dst < RULE_BUF_LIMIT) {\n"
    "                    buf[dst] = mask_charsets[row * 256u + pidx];\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "\n"
    "        /* Step 4: advance new_len. Truncate at RULE_BUF_LIMIT. */\n"
    "        uint new_total = (uint)new_len + npre + napp;\n"
    "        if (new_total <= RULE_BUF_LIMIT) {\n"
    "            new_len = (int)new_total;\n"
    "        } else {\n"
    "            new_len = RULE_BUF_LIMIT;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* --- Algorithm-specific hash via template extension functions. --- */\n"
    "#ifdef GPU_TEMPLATE_HAS_PRE_SALT\n"
    "    /* Lane-level salt batching (2026-05-09 experiment): compute the\n"
    "     * password-only portion of the salted hash ONCE per (word, rule, mask,\n"
    "     * salt_chunk), then loop over up to SALT_BATCH salts serially. Each\n"
    "     * iteration reuses pre_state but re-initialises template_state for\n"
    "     * the per-salt outer-MD5. The algorithm core (gpu_md5salt_core.cl)\n"
    "     * defines template_pre_salt to populate pre_state from buf and\n"
    "     * template_finalize_post to consume pre_state + salt and produce the\n"
    "     * final per-salt digest in st. */\n"
    "    template_pre_salt_state pre_state;\n"
    "    template_pre_salt(buf, new_len, params.algo_mode, &pre_state);\n"
    "\n"
    "    for (uint i = 0u; i < (uint)SALT_BATCH; i++) {\n"
    "        uint salt_local = salt_base + i;\n"
    "        if (salt_local >= num_salts_per_page) break;\n"
    "        uint salt_idx_global = (uint)params.salt_start + salt_local;\n"
    "        uint  s_off = salt_off[salt_idx_global];\n"
    "        uint  s_len = (uint)salt_lens[salt_idx_global];\n"
    "\n"
    "        template_state st;\n"
    "        template_init(&st);\n"
    "        template_finalize_post(&st, &pre_state,\n"
    "                               buf, new_len,\n"
    "                               salt_buf + s_off, s_len,\n"
    "                               params.algo_mode);\n"
    "#else\n"
    "    template_state st;\n"
    "    template_init(&st);\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    /* B6 salt-axis: pass salt bytes + length to the core. The core\n"
    "     * computes its algorithm's salted hash inline (see gpu_md5salt_core.cl\n"
    "     * for the JOB_MD5SALT double-MD5 chain, gpu_md5saltpass_core.cl for\n"
    "     * the JOB_MD5SALTPASS prepend, etc.). salt_idx_global is the index\n"
    "     * into the host's full salt list (b_salt_data / b_salt_off /\n"
    "     * b_salt_lens uploaded once via gpu_opencl_set_salts). */\n"
    "    uint  s_off = salt_off[salt_idx_global];\n"
    "    uint  s_len = (uint)salt_lens[salt_idx_global];\n"
    "#ifdef GPU_TEMPLATE_HAS_LOCAL_BUFFER\n"
    "    /* Phase 6 BCRYPT (2026-05-08): 8-arg signature variant — passes the\n"
    "     * workgroup-shared __local sbox_pool + per-lane lid so the core's\n"
    "     * template_finalize can claim its 1024-uint partition (lid * 1024).\n"
    "     * Gated on GPU_TEMPLATE_HAS_LOCAL_BUFFER; only the BCRYPT carrier\n"
    "     * sets this define. */\n"
    "    template_finalize(&st, buf, new_len, salt_buf + s_off, s_len,\n"
    "                      params.algo_mode, sbox_pool, (uint)get_local_id(0));\n"
    "#else\n"
    "    template_finalize(&st, buf, new_len, salt_buf + s_off, s_len, params.algo_mode);\n"
    "#endif\n"
    "#else\n"
    "    template_finalize(&st, buf, new_len);\n"
    "#endif\n"
    "#endif /* GPU_TEMPLATE_HAS_PRE_SALT */\n"
    "\n"
    "    /* --- Iterated probe (algorithm-agnostic loop; per-iter step is\n"
    "     *      template_iterate, which is algorithm-specific). --- */\n"
    "    uint max_iter = params.max_iter;\n"
    "    if (max_iter < 1) max_iter = 1;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint matched_idx = 0u;\n"
    "        if (template_digest_compare(&st,\n"
    "                                    compact_fp, compact_idx,\n"
    "                                    params.compact_mask, params.max_probe,\n"
    "                                    params.hash_data_count,\n"
    "                                    hash_data_buf, hash_data_off,\n"
    "                                    overflow_keys, overflow_hashes,\n"
    "                                    overflow_offsets, params.overflow_count,\n"
    "                                    &matched_idx))\n"
    "        {\n"
    "            /* B3 dedup+overflow-aware emit (Memo B §2). The macro itself\n"
    "             * does the hashes_shown atomic_or; on overflow, it rolls back\n"
    "             * the dedup bit so re-issue lanes can re-emit. Without the\n"
    "             * rollback, dedup bits stay set across dispatches and silently\n"
    "             * drop cracks. See gpu_common.cl §B3 protocol.\n"
    "             *\n"
    "             * B7.1: pack mask_idx into the rule_idx slot of the hit entry.\n"
    "             * combined_ridx = rule_idx * mask_size + mask_idx so the host\n"
    "             * can decode rule_idx = combined / mask_size and mask_idx =\n"
    "             * combined % mask_size. Hit-stride is unchanged (slot[1] is\n"
    "             * the second word; was just rule_idx pre-B7). When mask_size\n"
    "             * == 1 (no mask), combined_ridx == rule_idx and the host\n"
    "             * decodes a 0 mask_idx — bit-identical to pre-B7 behavior.\n"
    "             *\n"
    "             * B6 (2026-05-06): for salted variants the kernel packs\n"
    "             *   combined_ridx = ((rule_idx * mask_size) + mask_idx)\n"
    "             *                   * num_salts_per_page + salt_local\n"
    "             * so host hit-replay can recover (salt_local, mask_idx,\n"
    "             * rule_idx) via three div/mod steps. The kernel ALSO emits\n"
    "             * salt_idx_global = params.salt_start + salt_local in slot[1]\n"
    "             * of the hit entry would require widening EMIT_HIT_N (rejected\n"
    "             * per §10 Q2 / Decision C.3). Instead the host dispatcher\n"
    "             * post-processes each page's hits after readback to convert\n"
    "             * salt_local -> salt_idx_global by adding salt_start. By the\n"
    "             * time hits reach gpujob_opencl.c hit-replay, slot[1] always\n"
    "             * encodes ((rule_idx * mask_size) + mask_idx) *\n"
    "             * num_salts_per_page + SALT_IDX_GLOBAL — i.e., a uniform\n"
    "             * format across all salt pages. When num_salts_per_page == 1\n"
    "             * (unsalted dispatch / salt-axis disabled) the layout\n"
    "             * collapses to the existing rule_idx*mask_size + mask_idx —\n"
    "             * bit-identical to pre-B6. */\n"
    "            /* Phase 1.5 (2026-05-10): hit emit uses LOCAL mask_idx (within-\n"
    "             * chunk; bounded by mask_size which equals bf_num_masks for BF\n"
    "             * chunks or gpu_mask_total for non-BF). Encoding fits uint32\n"
    "             * because rule_idx * mask_size * num_salts_per_page < 2^32 in\n"
    "             * all valid configurations. Host re-adds bf_mask_start +\n"
    "             * widx*offset at hit-replay to recover the absolute index. */\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "            /* Salted path encoding: pack rule, mask-local and salt-local into\n"
    "             * a single uint per the B6 layout. */\n"
    "            uint combined_ridx =\n"
    "                (rule_idx * mask_size + mask_idx_local) * num_salts_per_page +\n"
    "                salt_local;\n"
    "#else\n"
    "            /* Unsalted path (Phase 1.7 form, restored after Phase 1.8 revert):\n"
    "             * combined_ridx = rule_idx * mask_size + mask_idx_local. The\n"
    "             * Phase 1.8 inner-iter packing caused a 2.19× Pascal regression\n"
    "             * (task #239) and a parallel JOB_MD5SALT regression; reverted. */\n"
    "            uint combined_ridx =\n"
    "                rule_idx * mask_size + mask_idx_local;\n"
    "#endif\n"
    "            uint mask = 1u << (iter & 31);\n"
    "            template_emit_hit_or_overflow(hits, hit_count, params.max_hits,\n"
    "                              &st, word_idx, combined_ridx, iter,\n"
    "                              hashes_shown, matched_idx, mask,\n"
    "                              ovr_set, ovr_gid, gid);\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* B7.7a (2026-05-07): MD5UC algo_mode threading. Only\n"
    "             * gpu_md5_core.cl defines GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE\n"
    "             * (its template_iterate accepts an algo_mode arg to switch\n"
    "             * lowercase/uppercase hex). All other cores keep the\n"
    "             * legacy `(st)` signature. Mirrors the existing\n"
    "             * GPU_TEMPLATE_HAS_SALT pattern at template_finalize. */\n"
    "#ifdef GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE\n"
    "            template_iterate(&st, params.algo_mode);\n"
    "#else\n"
    "            template_iterate(&st);\n"
    "#endif\n"
    "        }\n"
    "    }\n"
    "#ifdef GPU_TEMPLATE_HAS_PRE_SALT\n"
    "    /* Close the SALT_BATCH inner salt loop opened above the iter loop. */\n"
    "    }\n"
    "#endif\n"
    "}\n"
    "\n"
    "/* template_phase0_test: byte-exact harness twin of template_phase0.\n"
    " * Mirrors md5_rules_phase0_test in gpu_md5_rules.cl: same\n"
    " * (word, rule) geometry, but emits the digest into digests_out[]\n"
    " * unconditionally instead of probing the compact table.\n"
    " *\n"
    " * Used by gpu_rules_test.c with --engine=template to validate that\n"
    " * the template path produces byte-identical digests to the legacy\n"
    " * path. Signature mirrors md5_rules_phase0_test exactly so the\n"
    " * harness can swap kernel name + recompile sources without touching\n"
    " * the dispatch wiring.\n"
    " *\n"
    " * B6 (2026-05-06): the harness only compiles for unsalted instantiations\n"
    " * — salted variants don't have a no-salt template_finalize signature,\n"
    " * and the test harness itself doesn't carry salt args. Salted byte-exact\n"
    " * validation goes through the real template_phase0 + a dedicated\n"
    " * fixture in gpu_rules_test.c (post-ship). */\n"
    "#ifndef GPU_TEMPLATE_HAS_SALT\n"
    "__kernel\n"
    "void template_phase0_test(\n"
    "    __global const uchar     *words,\n"
    "    __global const uint      *word_offset,\n"
    "    __global const uchar     *rule_program,\n"
    "    __global const uint      *rule_offset,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global uint            *digests_out)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    uint n_rules = params.num_masks;\n"
    "    uint total = n_words * n_rules;\n"
    "    uint gid = get_global_id(0);\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = gid / n_words;\n"
    "\n"
    "    __attribute__((aligned(16))) uchar buf[RULE_BUF_MAX];\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    int wlen = (int)words[wpos++];\n"
    "    if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "    for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "    uint rpos = rule_offset[rule_idx];\n"
    "    int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "\n"
    "    /* Rejection sentinel: emit zero digest. Same convention as\n"
    "     * md5_rules_phase0_test for diff-the-harness compatibility. */\n"
    "    if (new_len < 0) {\n"
    "        for (int i = 0; i < HASH_WORDS; i++) digests_out[gid * HASH_WORDS + i] = 0u;\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    template_state st;\n"
    "    template_init(&st);\n"
    "    template_finalize(&st, buf, new_len);\n"
    "\n"
    "    for (int i = 0; i < HASH_WORDS; i++) digests_out[gid * HASH_WORDS + i] = st.h[i];\n"
    "}\n"
    "#endif /* !GPU_TEMPLATE_HAS_SALT */\n"
;
