/* Auto-generated from gpu_md4_packed.cl -- do not edit */
static const char gpu_md4_packed_str[] =
    "/* gpu_md4_packed.cl — Packed password MD4 kernel\n"
    " *\n"
    " * Same as MD5 packed but uses md4_compress (inline, not in gpu_common.cl).\n"
    " * LE format, 4-word state, EMIT_HIT_4.\n"
    " * md5_to_hex_lc works for MD4 iteration (same LE 128-bit format).\n"
    " */\n"
    "\n"
    "/* MD4 compress — fully unrolled, 3 rounds × 16 steps */\n"
    "void md4_compress_p(uint *hx, uint *hy, uint *hz, uint *hw, uint *M) {\n"
    "    uint a = *hx, b = *hy, c = *hz, d = *hw;\n"
    "#define F4(x,y,z) (((x)&(y)) | ((~(x))&(z)))\n"
    "#define G4(x,y,z) (((x)&(y)) | ((x)&(z)) | ((y)&(z)))\n"
    "#define H4(x,y,z) ((x)^(y)^(z))\n"
    "#define R1(a,b,c,d,k,s) a = rotate(a + F4(b,c,d) + M[k], (uint)(s))\n"
    "#define R2(a,b,c,d,k,s) a = rotate(a + G4(b,c,d) + M[k] + 0x5A827999u, (uint)(s))\n"
    "#define R3(a,b,c,d,k,s) a = rotate(a + H4(b,c,d) + M[k] + 0x6ED9EBA1u, (uint)(s))\n"
    "    R1(a,b,c,d, 0, 3); R1(d,a,b,c, 1, 7); R1(c,d,a,b, 2,11); R1(b,c,d,a, 3,19);\n"
    "    R1(a,b,c,d, 4, 3); R1(d,a,b,c, 5, 7); R1(c,d,a,b, 6,11); R1(b,c,d,a, 7,19);\n"
    "    R1(a,b,c,d, 8, 3); R1(d,a,b,c, 9, 7); R1(c,d,a,b,10,11); R1(b,c,d,a,11,19);\n"
    "    R1(a,b,c,d,12, 3); R1(d,a,b,c,13, 7); R1(c,d,a,b,14,11); R1(b,c,d,a,15,19);\n"
    "    R2(a,b,c,d, 0, 3); R2(d,a,b,c, 4, 5); R2(c,d,a,b, 8, 9); R2(b,c,d,a,12,13);\n"
    "    R2(a,b,c,d, 1, 3); R2(d,a,b,c, 5, 5); R2(c,d,a,b, 9, 9); R2(b,c,d,a,13,13);\n"
    "    R2(a,b,c,d, 2, 3); R2(d,a,b,c, 6, 5); R2(c,d,a,b,10, 9); R2(b,c,d,a,14,13);\n"
    "    R2(a,b,c,d, 3, 3); R2(d,a,b,c, 7, 5); R2(c,d,a,b,11, 9); R2(b,c,d,a,15,13);\n"
    "    R3(a,b,c,d, 0, 3); R3(d,a,b,c, 8, 9); R3(c,d,a,b, 4,11); R3(b,c,d,a,12,15);\n"
    "    R3(a,b,c,d, 2, 3); R3(d,a,b,c,10, 9); R3(c,d,a,b, 6,11); R3(b,c,d,a,14,15);\n"
    "    R3(a,b,c,d, 1, 3); R3(d,a,b,c, 9, 9); R3(c,d,a,b, 5,11); R3(b,c,d,a,13,15);\n"
    "    R3(a,b,c,d, 3, 3); R3(d,a,b,c,11, 9); R3(c,d,a,b, 7,11); R3(b,c,d,a,15,15);\n"
    "#undef F4\n"
    "#undef G4\n"
    "#undef H4\n"
    "#undef R1\n"
    "#undef R2\n"
    "#undef R3\n"
    "    *hx = a + *hx; *hy = b + *hy; *hz = c + *hz; *hw = d + *hw;\n"
    "}\n"
    "\n"
    "__kernel void md4_packed_batch(\n"
    "    __global const uchar *packed_buf,\n"
    "    __global const uint *word_offset,\n"
    "    __global const uchar *unused_mask,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_start = params.reserved32[0];\n"
    "    uint word_idx = word_start + tid;\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint pos = word_offset[word_idx];\n"
    "    uint len = packed_buf[pos++];\n"
    "\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint i = 0;\n"
    "    for (; i + 3 < len; i += 4) {\n"
    "        M[i >> 2] = (uint)packed_buf[pos + i]\n"
    "                  | ((uint)packed_buf[pos + i + 1] << 8)\n"
    "                  | ((uint)packed_buf[pos + i + 2] << 16)\n"
    "                  | ((uint)packed_buf[pos + i + 3] << 24);\n"
    "    }\n"
    "    uint tail = 0;\n"
    "    uint shift = 0;\n"
    "    for (; i < len; i++) {\n"
    "        tail |= (uint)packed_buf[pos + i] << shift;\n"
    "        shift += 8;\n"
    "    }\n"
    "    tail |= (uint)0x80 << shift;\n"
    "    M[i >> 2] = tail;\n"
    "    M[14] = len * 8;\n"
    "\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u;\n"
    "    uint hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md4_compress_p(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe,\n"
    "                          params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes,\n"
    "                          overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_4(hits, hit_count, params.max_hits,\n"
    "                       word_idx, 0, iter, hx, hy, hz, hw)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u;\n"
    "            hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md4_compress_p(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
