/* Auto-generated from gpu_mysql3_core.cl -- do not edit */
static const char gpu_mysql3_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_mysql3_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_mysql3_core.cl — MYSQL3 (-m e456) algorithm extension functions\n"
    " * for the generic dispatch template (Memo B Phase B5 sub-batch 7).\n"
    " *\n"
    " * MYSQL3 = legacy MySQL OLD_PASSWORD() hash. 64-bit output. Per-byte\n"
    " * arithmetic accumulator loop:\n"
    " *\n"
    " *   nr = 1345345333; nr2 = 0x12345671; add = 7;\n"
    " *   for each input byte b in input:\n"
    " *     if b == ' ' or b == '\\t': continue;\n"
    " *     nr  ^= ((nr & 63) + add) * b + (nr << 8);\n"
    " *     nr2 += (nr2 << 8) ^ nr;\n"
    " *     add += b;\n"
    " *   final = (nr & 0x7fffffff, nr2 & 0x7fffffff)  -- 8 bytes total\n"
    " *\n"
    " * Iter step (CPU JOB_MYSQL3, mdxfind.c:25180-25186):\n"
    " *   for x = 1..Maxiter:\n"
    " *     mysql3(cur, len, linebuf);              -- linebuf = 16 ASCII hex chars\n"
    " *     get32(linebuf, curin.h, 16); checkhash(curin, 16, x, JOB_MYSQL3);\n"
    " *     cur = linebuf; len = 16;                -- next iter input is the hex\n"
    " *\n"
    " *   The hex string format is \"%08x%08x\" of nr & 0x7fffffff and nr2 & 0x7fffffff\n"
    " *   (lowercase). 16 ASCII hex chars total.\n"
    " *\n"
    " * Probe path (host zero-pad fix, mdxfind.c:36400-36412 rev 1.399+): the\n"
    " * compact-table HashDataBuf entries for sub-128-bit outputs are stored as\n"
    " * 16 bytes (real bytes followed by zero pad). For MYSQL3 (8-byte output),\n"
    " * the kernel emits hx = byteswap(nr), hy = byteswap(nr2), hz = hw = 0 ---\n"
    " * matches the slab kernel gpu_mysql3unsalted.cl:121-125, and matches the\n"
    " * \"16-hex\" CPU compact-table storage of \"AAAAAAAA00000000BBBBBBBB\" hex\n"
    " * patterns (where AAA = nr LE-bytes, BBB = nr2 LE-bytes; remaining 8\n"
    " * bytes zero per the host pad).\n"
    " *\n"
    " * State carried in template_state: HASH_WORDS=4 uint32. h[0]=hx, h[1]=hy,\n"
    " * h[2]=h[3]=0. We retain the byteswapped probe form so template_iterate\n"
    " * can recover nr/nr2 by reverse-byteswapping h[0]/h[1].\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=4,HASH_BLOCK_BYTES=64\". Distinct\n"
    " * cache entry guaranteed by source-text hash difference (the per-byte\n"
    " * MYSQL3 arithmetic is unique).\n"
    " *\n"
    " * R1 mitigation: single private buffer; no addrspace-cast helpers.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_mysql3_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* MYSQL3 has no MD-style block. The \"compress\" interface here is a stub\n"
    " * for symmetry; the per-byte loop runs entirely inside template_finalize. */\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    /* No work-state install needed before per-byte loop. We zero the probe\n"
    "     * state slots so template_finalize and template_iterate write them\n"
    "     * cleanly. */\n"
    "    st->h[0] = 0u;\n"
    "    st->h[1] = 0u;\n"
    "    st->h[2] = 0u;\n"
    "    st->h[3] = 0u;\n"
    "}\n"
    "\n"
    "/* Stub for interface symmetry (the shared template body in gpu_template.cl\n"
    " * never invokes this for MYSQL3; template_finalize handles the input\n"
    " * directly). */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    (void)st;\n"
    "    (void)block;\n"
    "}\n"
    "\n"
    "/* Inline MYSQL3 per-byte arithmetic loop. Consumes `len` input bytes from\n"
    " * `data` and produces the 8-byte digest as (nr_out, nr2_out). Skips spaces\n"
    " * and tabs (matching CPU mysql3() at mdxfind.c:3494-3513). */\n"
    "static inline void mysql3_compute(const uchar *data, int len,\n"
    "                                  uint *nr_out, uint *nr2_out)\n"
    "{\n"
    "    uint nr = 1345345333u;\n"
    "    uint nr2 = 0x12345671u;\n"
    "    uint add = 7u;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        uint c = (uint)data[i];\n"
    "        if (c == 0x20u || c == 0x09u) continue;\n"
    "        uint tmp = c;\n"
    "        nr ^= (((nr & 63u) + add) * tmp) + (nr << 8);\n"
    "        nr2 += (nr2 << 8) ^ nr;\n"
    "        add += tmp;\n"
    "    }\n"
    "    *nr_out = nr & 0x7fffffffu;\n"
    "    *nr2_out = nr2 & 0x7fffffffu;\n"
    "}\n"
    "\n"
    "/* template_finalize: runs the MYSQL3 per-byte loop on the input bytes and\n"
    " * stores the byteswapped (nr, nr2) into st->h[0..1]. h[2..3] stay zero. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint nr, nr2;\n"
    "    mysql3_compute(data, len, &nr, &nr2);\n"
    "    /* Probe form: byteswap nr/nr2 to match CPU compact-table LE storage of\n"
    "     * the 16-hex hash representation. Slab kernel does the same at\n"
    "     * gpu_mysql3unsalted.cl:121-125. */\n"
    "    uint hx = ((nr  >> 24) & 0xffu) | ((nr  >> 8) & 0xff00u) |\n"
    "              ((nr  << 8)  & 0xff0000u) | ((nr  << 24) & 0xff000000u);\n"
    "    uint hy = ((nr2 >> 24) & 0xffu) | ((nr2 >> 8) & 0xff00u) |\n"
    "              ((nr2 << 8)  & 0xff0000u) | ((nr2 << 24) & 0xff000000u);\n"
    "    st->h[0] = hx;\n"
    "    st->h[1] = hy;\n"
    "    st->h[2] = 0u;\n"
    "    st->h[3] = 0u;\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. CPU reference at mdxfind.c:25180-25186:\n"
    " *\n"
    " *   mysql3(cur, len, linebuf);   -- linebuf gets \"%08x%08x\" (16 hex chars)\n"
    " *   cur = linebuf; len = 16;     -- next iter consumes those 16 ASCII bytes\n"
    " *\n"
    " * Implementation:\n"
    " *   1. Recover nr, nr2 from the byteswapped st->h[0], st->h[1].\n"
    " *      (template_finalize stored byteswap(nr) and byteswap(nr2); reverse\n"
    " *      the byteswap to get the raw 31-bit-masked values.)\n"
    " *   2. Format 16 lowercase ASCII hex chars in a stack buffer (8 hex from nr,\n"
    " *      8 hex from nr2 -- both already & 0x7fffffff in template_finalize so\n"
    " *      \"%08x\" gives leading-zero-padded hex without further masking).\n"
    " *   3. Run mysql3_compute on those 16 bytes.\n"
    " *   4. Byteswap and store into st->h[0..1] (h[2..3] stay zero).\n"
    " */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    /* Step 1: reverse the byteswap st->h[0/1] back to nr, nr2. */\n"
    "    uint hx = st->h[0];\n"
    "    uint hy = st->h[1];\n"
    "    uint nr  = ((hx >> 24) & 0xffu) | ((hx >> 8) & 0xff00u) |\n"
    "               ((hx << 8)  & 0xff0000u) | ((hx << 24) & 0xff000000u);\n"
    "    uint nr2 = ((hy >> 24) & 0xffu) | ((hy >> 8) & 0xff00u) |\n"
    "               ((hy << 8)  & 0xff0000u) | ((hy << 24) & 0xff000000u);\n"
    "    /* nr and nr2 are already & 0x7fffffff (set by template_finalize). */\n"
    "\n"
    "    /* Step 2: emit 16 lowercase hex chars. Layout matches sprintf(\"%08x%08x\",\n"
    "     * nr, nr2): char[0..7] = nr (high nibble first), char[8..15] = nr2.\n"
    "     * \"%08x\" of nr writes nr's MSB byte (bits 24..31) as 2 hex chars first.\n"
    "     * For each byte b (high to low in nr), high-nibble first then low-nibble.\n"
    "     */\n"
    "    uchar hexbuf[16];\n"
    "    {\n"
    "        /* nr -> hexbuf[0..7] */\n"
    "        uint v = nr;\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            uint b = (v >> ((3 - i) * 8)) & 0xffu;\n"
    "            uint hi = (b >> 4) & 0xfu;\n"
    "            uint lo = b & 0xfu;\n"
    "            hexbuf[i*2]     = (uchar)(hi + ((hi < 10u) ? '0' : ('a' - 10)));\n"
    "            hexbuf[i*2 + 1] = (uchar)(lo + ((lo < 10u) ? '0' : ('a' - 10)));\n"
    "        }\n"
    "        /* nr2 -> hexbuf[8..15] */\n"
    "        v = nr2;\n"
    "        for (int i = 0; i < 4; i++) {\n"
    "            uint b = (v >> ((3 - i) * 8)) & 0xffu;\n"
    "            uint hi = (b >> 4) & 0xfu;\n"
    "            uint lo = b & 0xfu;\n"
    "            hexbuf[8 + i*2]     = (uchar)(hi + ((hi < 10u) ? '0' : ('a' - 10)));\n"
    "            hexbuf[8 + i*2 + 1] = (uchar)(lo + ((lo < 10u) ? '0' : ('a' - 10)));\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Step 3+4: rerun MYSQL3 on the 16 hex bytes; byteswap and store. */\n"
    "    uint nr_n, nr2_n;\n"
    "    mysql3_compute(hexbuf, 16, &nr_n, &nr2_n);\n"
    "    uint nhx = ((nr_n  >> 24) & 0xffu) | ((nr_n  >> 8) & 0xff00u) |\n"
    "               ((nr_n  << 8)  & 0xff0000u) | ((nr_n  << 24) & 0xff000000u);\n"
    "    uint nhy = ((nr2_n >> 24) & 0xffu) | ((nr2_n >> 8) & 0xff00u) |\n"
    "               ((nr2_n << 8)  & 0xff0000u) | ((nr2_n << 24) & 0xff000000u);\n"
    "    st->h[0] = nhx;\n"
    "    st->h[1] = nhy;\n"
    "    st->h[2] = 0u;\n"
    "    st->h[3] = 0u;\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
