/* Auto-generated from gpu_wrl_core.cl -- do not edit */
static const char gpu_wrl_core_str[] =
    "/*\n"
    " * $Revision: 1.3 $\n"
    " * $Log: gpu_wrl_core.cl,v $\n"
    " * Revision 1.3  2026/08/10 14:50:25  dlr\n"
    " * Remove duplicate WRL_RC, WRL_SBOX and WRL_OP definitions. gpu_common.cl rev 1.28 lifted the wrl_block primitive in from librhash for the WRLMD5PASS family helper and supplies all three; this file is only ever concatenated after gpu_common.cl in gpu_opencl_template_compile_wrl, so the second copy made every WRL template build fail with CL_BUILD_PROGRAM_FAILURE, redefinition of WRL_RC and WRL_SBOX. The effect was not merely loss of GPU acceleration: resolve_kernel returned NULL and the work was never re-routed to CPU, so WRL found zero hashes on any OpenCL device from 2026-05-27 onward while the run exited normally. Tables verified value-identical, 10 of 10 round constants and 2048 of 2048 S-box entries; the two WRL_OP bodies differ only in parenthesisation of the src argument, immaterial at the K[m] and state[m] call sites. Header note corrected: it reasoned only about gpu_wrlunsalted.cl being a separate cl_program and overlooked gpu_common.cl being in the same one. Validated on fpga GTX 1080 at iter 1 and iter 3, GPU and CPU byte-identical, 15 of 15.\n"
    " *\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_wrl_core.cl — Whirlpool (WRL, -m e5) algorithm extension functions\n"
    " * for the generic dispatch template (Memo B Phase B5 sub-batch 6.5).\n"
    " *\n"
    " * WRL = Whirlpool 512-bit hash. 64-byte digest. The compression function\n"
    " * is Miyaguchi-Preneel applied to a 64-byte BIG-ENDIAN block:\n"
    " *\n"
    " *   hash = old_hash ^ state ^ block\n"
    " *\n"
    " * where state = 10-round AES-like permutation of (block ^ old_hash) keyed\n"
    " * by old_hash + round constants. Single-block IV is all-zeros.\n"
    " *\n"
    " * Dual-purpose ship/diagnostic (ref: brief Path A 2026-05-05):\n"
    " *\n"
    " *   1. SHIP — first wired Whirlpool template; expands the unified template\n"
    " *      family from 29 to 30 algorithms.\n"
    " *   2. DIAGNOSTIC — Streebog (B5 sub-batch 5b, 2026-05-05) revealed RDNA4\n"
    " *      gfx1201 incompatibility with the rules-walker template path: 4/100\n"
    " *      lanes pass per wavefront (positions 1, 33, 65, 97 — wavefront-stride\n"
    " *      lane 0). The hypothesis is that the 16 KB __constant SBOB_SL64 table\n"
    " *      addressed via the SBOG_LPS uchar-from-ulong pattern triggers RDNA4\n"
    " *      codegen breakage. WRL has a 16 KB __constant WRL_SBOX of identical\n"
    " *      shape ([8][256] ulong) but a DIFFERENT access pattern — direct ulong\n"
    " *      indexing with shift-then-mask (`(src)[i] >> shift & 0xff`), no\n"
    " *      uchar-from-ulong reinterpret cast.\n"
    " *\n"
    " *      Decision tree:\n"
    " *        - WRL gfx1201 100/100 PASS → bug is SBOG_LPS-specific (uchar/ulong\n"
    " *          aliasing), NOT 16 KB __constant capacity.\n"
    " *        - WRL gfx1201 < 100/100, lanes 1/33/65/97 only → generic 16 KB\n"
    " *          __constant RDNA4 issue. Both algos need __global mitigation.\n"
    " *        - WRL gfx1201 different lane pattern → distinct bug class.\n"
    " *\n"
    " * Iter step (CPU JOB_WRL, mdxfind.c:28019-28024):\n"
    " *   for x = 1..Maxiter:\n"
    " *     WHIRLPOOL(cur, len, curin.h);              // 64-byte digest\n"
    " *     checkhash(curin, len, x, JOB_WRL);\n"
    " *     cur = prmd5(curin.h, mdbuf, 128);          // 128 lowercase hex chars\n"
    " *     len = 128;                                 // next iter consumes hex\n"
    " *\n"
    " *   Hex feedback: 64-byte digest -> 128 ASCII hex chars. Whirlpool then\n"
    " *   processes those 128 bytes via 2 full blocks + 1 padding-only block\n"
    " *   (128 + 1 (0x80) + 32 (256-bit length) > 128, so the length spills\n"
    " *   into a third block).\n"
    " *\n"
    " * State carried in template_state:\n"
    " *   ulong state[8]    — internal compression state (BIG-ENDIAN, ulong)\n"
    " *   uint  h[16]       — exposed digest words, LE-byteswapped uint32\n"
    " *   (probe path uses h[0..3] = leading 16 bytes LE; same convention as\n"
    " *   the slab kernel gpu_wrlunsalted.cl:765 and SHA-512 template.)\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=16,HASH_BLOCK_BYTES=64\".\n"
    " * Distinct cache entry guaranteed by source-text hash difference.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single private\n"
    " * buffer pattern. No __private uchar* helpers; no addrspace-cast\n"
    " * ternaries. ulong M[8] is private scratch only.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_wrl_core_str, gpu_template_str ]\n"
    " *\n"
    " * NOTE: WRL_SBOX, WRL_RC and WRL_OP are NOT defined here - they are\n"
    " * supplied by gpu_common_str, the first source in the list above. Only\n"
    " * whirlpool_compress* and the template_* specialisations are local to\n"
    " * this translation unit. The slab kernel gpu_wrlunsalted.cl carries its\n"
    " * own copies, but that is a separate cl_program, so it does not collide.\n"
    " *\n"
    " * The earlier version of this note reasoned only about gpu_wrlunsalted.cl\n"
    " * and overlooked gpu_common.cl, which is in the SAME program - that is\n"
    " * precisely how the 2026-05-27 redefinition regression went unnoticed.\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 16\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Whirlpool round constants, S-box and the WRL_OP macro are deliberately\n"
    " * NOT defined here. gpu_common.cl is sources[0] of the WRL template build\n"
    " * (gpu_opencl.c gpu_opencl_template_compile_wrl) and has supplied WRL_RC,\n"
    " * WRL_SBOX and WRL_OP since gpu_common.cl rev 1.28 (2026-05-27, sub-phase\n"
    " * 5b2a1 lifted wrl_block in from librhash for the WRLMD5PASS family\n"
    " * helper). Defining them a second time here made every WRL template build\n"
    " * fail with CL_BUILD_PROGRAM_FAILURE - redefinition of WRL_RC and\n"
    " * WRL_SBOX - which silently dropped WRL to CPU-only on every OpenCL\n"
    " * device from that date until this revision. The values are identical:\n"
    " * 10 of 10 round constants and 2048 of 2048 S-box entries match. The two\n"
    " * WRL_OP bodies differ only in parenthesisation of the src argument,\n"
    " * which is immaterial at the K[m] and state[m] call sites below. This\n"
    " * file is only ever concatenated after gpu_common.cl, so the shared\n"
    " * definitions are always in scope here. */\n"
    "\n"
    "/* Whirlpool compress with zero IV (single-block fast path).\n"
    " *   hash = Miyaguchi-Preneel(0, block) = state_final ^ block\n"
    " * Used by template_finalize for the first block when input fits in one\n"
    " * block (input_len <= 31 bytes; 0x80 padding + 32-byte BE length fits).\n"
    " *\n"
    " * Mirrors gpu_wrlunsalted.cl:571-608 byte-for-byte. */\n"
    "static inline void whirlpool_compress_zero_iv(ulong *hash, ulong *block) {\n"
    "    ulong K[2][8];\n"
    "    ulong state[2][8];\n"
    "    int m = 0;\n"
    "\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        K[0][i] = 0;\n"
    "        state[0][i] = block[i];\n"
    "    }\n"
    "\n"
    "    for (int r = 0; r < 10; r++) {\n"
    "        K[m^1][0] = WRL_OP(K[m], 0) ^ WRL_RC[r];\n"
    "        K[m^1][1] = WRL_OP(K[m], 1);\n"
    "        K[m^1][2] = WRL_OP(K[m], 2);\n"
    "        K[m^1][3] = WRL_OP(K[m], 3);\n"
    "        K[m^1][4] = WRL_OP(K[m], 4);\n"
    "        K[m^1][5] = WRL_OP(K[m], 5);\n"
    "        K[m^1][6] = WRL_OP(K[m], 6);\n"
    "        K[m^1][7] = WRL_OP(K[m], 7);\n"
    "\n"
    "        state[m^1][0] = WRL_OP(state[m], 0) ^ K[m^1][0];\n"
    "        state[m^1][1] = WRL_OP(state[m], 1) ^ K[m^1][1];\n"
    "        state[m^1][2] = WRL_OP(state[m], 2) ^ K[m^1][2];\n"
    "        state[m^1][3] = WRL_OP(state[m], 3) ^ K[m^1][3];\n"
    "        state[m^1][4] = WRL_OP(state[m], 4) ^ K[m^1][4];\n"
    "        state[m^1][5] = WRL_OP(state[m], 5) ^ K[m^1][5];\n"
    "        state[m^1][6] = WRL_OP(state[m], 6) ^ K[m^1][6];\n"
    "        state[m^1][7] = WRL_OP(state[m], 7) ^ K[m^1][7];\n"
    "\n"
    "        m ^= 1;\n"
    "    }\n"
    "\n"
    "    for (int i = 0; i < 8; i++)\n"
    "        hash[i] = state[0][i] ^ block[i];\n"
    "}\n"
    "\n"
    "/* General Whirlpool compress: hash = Miyaguchi-Preneel(cv, block) =\n"
    " *                                    cv ^ state_final ^ block.\n"
    " * Used for second-and-subsequent blocks. Mirrors gpu_wrlunsalted.cl:611-645. */\n"
    "static inline void whirlpool_compress_cv(ulong *hash, ulong *block, ulong *cv) {\n"
    "    ulong K[2][8];\n"
    "    ulong state[2][8];\n"
    "    int m = 0;\n"
    "\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        K[0][i] = cv[i];\n"
    "        state[0][i] = block[i] ^ cv[i];\n"
    "    }\n"
    "\n"
    "    for (int r = 0; r < 10; r++) {\n"
    "        K[m^1][0] = WRL_OP(K[m], 0) ^ WRL_RC[r];\n"
    "        K[m^1][1] = WRL_OP(K[m], 1);\n"
    "        K[m^1][2] = WRL_OP(K[m], 2);\n"
    "        K[m^1][3] = WRL_OP(K[m], 3);\n"
    "        K[m^1][4] = WRL_OP(K[m], 4);\n"
    "        K[m^1][5] = WRL_OP(K[m], 5);\n"
    "        K[m^1][6] = WRL_OP(K[m], 6);\n"
    "        K[m^1][7] = WRL_OP(K[m], 7);\n"
    "\n"
    "        state[m^1][0] = WRL_OP(state[m], 0) ^ K[m^1][0];\n"
    "        state[m^1][1] = WRL_OP(state[m], 1) ^ K[m^1][1];\n"
    "        state[m^1][2] = WRL_OP(state[m], 2) ^ K[m^1][2];\n"
    "        state[m^1][3] = WRL_OP(state[m], 3) ^ K[m^1][3];\n"
    "        state[m^1][4] = WRL_OP(state[m], 4) ^ K[m^1][4];\n"
    "        state[m^1][5] = WRL_OP(state[m], 5) ^ K[m^1][5];\n"
    "        state[m^1][6] = WRL_OP(state[m], 6) ^ K[m^1][6];\n"
    "        state[m^1][7] = WRL_OP(state[m], 7) ^ K[m^1][7];\n"
    "\n"
    "        m ^= 1;\n"
    "    }\n"
    "\n"
    "    for (int i = 0; i < 8; i++)\n"
    "        hash[i] = cv[i] ^ state[0][i] ^ block[i];\n"
    "}\n"
    "\n"
    "/* Per-lane state struct. WRL carries 8 × uint64 chaining BIG-ENDIAN\n"
    " * INTERNALLY (state[]). The template body needs uint32 access to the\n"
    " * digest for digests_out[] and EMIT_HIT_16 — provide that via h[16]\n"
    " * populated at the end of each compression (template_finalize /\n"
    " * template_iterate). h[0..15] mirrors state[0..7] in LE-byteswapped\n"
    " * uint32 pairs:\n"
    " *   h[2i]   = (uint)bswap64(state[i])\n"
    " *   h[2i+1] = (uint)(bswap64(state[i]) >> 32)\n"
    " *\n"
    " * This matches gpu_wrlunsalted.cl:754-759's split convention exactly. */\n"
    "typedef struct {\n"
    "    ulong state[8];   /* internal compression state, BIG-ENDIAN ulong */\n"
    "    uint  h[HASH_WORDS]; /* exposed digest words, LE-byteswapped uint32 */\n"
    "} template_state;\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    /* Whirlpool IV is all-zeros. */\n"
    "    for (int i = 0; i < 8; i++) st->state[i] = 0UL;\n"
    "    /* h[] is populated only after at least one compression in\n"
    "     * template_finalize / template_iterate. */\n"
    "}\n"
    "\n"
    "/* Internal helper: decompose state[8] (BE ulong) into h[16] (LE uint32).\n"
    " * Mirrors gpu_wrlunsalted.cl:754-759 exactly. */\n"
    "static inline void template_state_to_h(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = bswap64(st->state[i]);\n"
    "        st->h[i*2]   = (uint)s;\n"
    "        st->h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Stub for template interface symmetry; the shared template body invokes\n"
    " * template_finalize directly with the full input buffer. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    (void)st;\n"
    "    (void)block;\n"
    "}\n"
    "\n"
    "/* template_finalize: process the input bytes and write the final digest.\n"
    " *\n"
    " * Whirlpool padding spec:\n"
    " *   - block size = 64 bytes\n"
    " *   - 0x80 marker after the last input byte\n"
    " *   - 256-bit BIG-ENDIAN bit count in last 32 bytes of the FINAL block\n"
    " *\n"
    " * Single-block fits when (rem + 1 + 32 <= 64), i.e., rem <= 31.\n"
    " * Otherwise need an extra padding-only final block.\n"
    " *\n"
    " * For our chokepoint maxlen=27, all primary-input cases fit single-block.\n"
    " * The iterate path's 128-byte hex string requires multi-block (handled in\n"
    " * template_iterate). This finalize path supports general len, anchoring\n"
    " * compatibility for any future maxlen > 31 changes.\n"
    " *\n"
    " * Length encoding: bit count fits in low 64 bits of the 256-bit field\n"
    " * (M[7]); high 192 bits (M[4..6]) are zero. Matches the slab kernel's\n"
    " * `M64[6] = 0; M64[7] = bitlen;` pattern (gpu_wrlunsalted.cl:746-747).\n"
    " *\n"
    " * R1 mitigation: single private buffer (just ulong M[8] + ulong cv[8]\n"
    " * for multi-block + the input data pointer). No private uchar* helper\n"
    " * indirection. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    ulong M[8];\n"
    "    int pos = 0;\n"
    "    int first = 1;\n"
    "    ulong cv[8];\n"
    "\n"
    "    /* Process complete 64-byte blocks BIG-ENDIAN ulong load. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 8; j++) {\n"
    "            int b = pos + j * 8;\n"
    "            M[j] = ((ulong)data[b]     << 56)\n"
    "                 | ((ulong)data[b + 1] << 48)\n"
    "                 | ((ulong)data[b + 2] << 40)\n"
    "                 | ((ulong)data[b + 3] << 32)\n"
    "                 | ((ulong)data[b + 4] << 24)\n"
    "                 | ((ulong)data[b + 5] << 16)\n"
    "                 | ((ulong)data[b + 6] << 8)\n"
    "                 |  (ulong)data[b + 7];\n"
    "        }\n"
    "        if (first) {\n"
    "            whirlpool_compress_zero_iv(st->state, M);\n"
    "            first = 0;\n"
    "        } else {\n"
    "            for (int i = 0; i < 8; i++) cv[i] = st->state[i];\n"
    "            whirlpool_compress_cv(st->state, M, cv);\n"
    "        }\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Build final padded block(s). Zero scratch, copy remaining tail\n"
    "     * bytes BIG-ENDIAN, append 0x80 marker. */\n"
    "    for (int j = 0; j < 8; j++) M[j] = 0UL;\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 3;\n"
    "        int bi = 7 - (i & 7);\n"
    "        M[wi] |= ((ulong)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 3;\n"
    "        int bi = 7 - (rem & 7);\n"
    "        M[wi] |= ((ulong)0x80UL) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem <= 31) {\n"
    "        /* Length fits in this block. M[4..6] = 0; M[7] = total_bits.\n"
    "         * total_bits = (input_total_bytes * 8). For multi-block path\n"
    "         * (this branch is reached after len was split), total_bits is\n"
    "         * still len*8 (same input). */\n"
    "        M[4] = 0UL;\n"
    "        M[5] = 0UL;\n"
    "        M[6] = 0UL;\n"
    "        M[7] = (ulong)((ulong)len * 8UL);\n"
    "        if (first) {\n"
    "            whirlpool_compress_zero_iv(st->state, M);\n"
    "        } else {\n"
    "            for (int i = 0; i < 8; i++) cv[i] = st->state[i];\n"
    "            whirlpool_compress_cv(st->state, M, cv);\n"
    "        }\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length.\n"
    "         * Compress this partial block (with 0x80 but no length), then\n"
    "         * issue a length-only block. */\n"
    "        if (first) {\n"
    "            whirlpool_compress_zero_iv(st->state, M);\n"
    "            first = 0;\n"
    "        } else {\n"
    "            for (int i = 0; i < 8; i++) cv[i] = st->state[i];\n"
    "            whirlpool_compress_cv(st->state, M, cv);\n"
    "        }\n"
    "        for (int j = 0; j < 8; j++) M[j] = 0UL;\n"
    "        M[7] = (ulong)((ulong)len * 8UL);\n"
    "        for (int i = 0; i < 8; i++) cv[i] = st->state[i];\n"
    "        whirlpool_compress_cv(st->state, M, cv);\n"
    "    }\n"
    "\n"
    "    /* Decompose final state into h[16] LE uint32 for digest emit. */\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the digest as 128-byte\n"
    " * lowercase hex ASCII and rehash with a fresh zero IV. WRL hex output\n"
    " * is 128 chars = 2 full 64-byte blocks. Then add a padding-only block\n"
    " * (0x80 at byte 0 + 32-byte length 128*8=1024 in bits) for total of\n"
    " * 3 compressions.\n"
    " *\n"
    " * Mirrors gpu_wrlunsalted.cl:771-833 byte-for-byte semantically. The\n"
    " * slab uses the LE h[] pre-computation; here we emit hex bytes and feed\n"
    " * them BIG-ENDIAN-loaded into the compression. Both paths produce the\n"
    " * same digest because Whirlpool is byte-stream defined; the ulong load\n"
    " * order is just an implementation detail.\n"
    " *\n"
    " * R1 mitigation preserved: only ulong scratch (M[8], cv[8]) + small\n"
    " * private uchar hex_buf[128]. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    ulong M[8];\n"
    "    ulong cv[8];\n"
    "    uchar hex_buf[128];\n"
    "\n"
    "    /* Emit 128 lowercase hex chars from h[0..15] (LE uint32 digest).\n"
    "     * h[i] is one uint32 LE; bytes b0=lo, b1=mid-lo, b2=mid-hi, b3=hi. */\n"
    "    for (int i = 0; i < 16; i++) {\n"
    "        uint s = st->h[i];\n"
    "        uint b0 = s & 0xff, b1 = (s >> 8) & 0xff;\n"
    "        uint b2 = (s >> 16) & 0xff, b3 = (s >> 24) & 0xff;\n"
    "        uint hi0 = (b0 >> 4) & 0xf, lo0 = b0 & 0xf;\n"
    "        uint hi1 = (b1 >> 4) & 0xf, lo1 = b1 & 0xf;\n"
    "        uint hi2 = (b2 >> 4) & 0xf, lo2 = b2 & 0xf;\n"
    "        uint hi3 = (b3 >> 4) & 0xf, lo3 = b3 & 0xf;\n"
    "        hex_buf[i*8 + 0] = (uchar)(hi0 + ((hi0 < 10u) ? '0' : ('a' - 10)));\n"
    "        hex_buf[i*8 + 1] = (uchar)(lo0 + ((lo0 < 10u) ? '0' : ('a' - 10)));\n"
    "        hex_buf[i*8 + 2] = (uchar)(hi1 + ((hi1 < 10u) ? '0' : ('a' - 10)));\n"
    "        hex_buf[i*8 + 3] = (uchar)(lo1 + ((lo1 < 10u) ? '0' : ('a' - 10)));\n"
    "        hex_buf[i*8 + 4] = (uchar)(hi2 + ((hi2 < 10u) ? '0' : ('a' - 10)));\n"
    "        hex_buf[i*8 + 5] = (uchar)(lo2 + ((lo2 < 10u) ? '0' : ('a' - 10)));\n"
    "        hex_buf[i*8 + 6] = (uchar)(hi3 + ((hi3 < 10u) ? '0' : ('a' - 10)));\n"
    "        hex_buf[i*8 + 7] = (uchar)(lo3 + ((lo3 < 10u) ? '0' : ('a' - 10)));\n"
    "    }\n"
    "\n"
    "    /* Reset state to all-zeros IV. */\n"
    "    for (int i = 0; i < 8; i++) st->state[i] = 0UL;\n"
    "\n"
    "    /* Block 1: hex_buf[0..63] BE-loaded into M[0..7]. */\n"
    "    for (int j = 0; j < 8; j++) {\n"
    "        int off = j * 8;\n"
    "        M[j] = ((ulong)hex_buf[off]     << 56)\n"
    "             | ((ulong)hex_buf[off + 1] << 48)\n"
    "             | ((ulong)hex_buf[off + 2] << 40)\n"
    "             | ((ulong)hex_buf[off + 3] << 32)\n"
    "             | ((ulong)hex_buf[off + 4] << 24)\n"
    "             | ((ulong)hex_buf[off + 5] << 16)\n"
    "             | ((ulong)hex_buf[off + 6] <<  8)\n"
    "             |  (ulong)hex_buf[off + 7];\n"
    "    }\n"
    "    whirlpool_compress_zero_iv(st->state, M);\n"
    "\n"
    "    /* Block 2: hex_buf[64..127]. */\n"
    "    for (int j = 0; j < 8; j++) {\n"
    "        int off = 64 + j * 8;\n"
    "        M[j] = ((ulong)hex_buf[off]     << 56)\n"
    "             | ((ulong)hex_buf[off + 1] << 48)\n"
    "             | ((ulong)hex_buf[off + 2] << 40)\n"
    "             | ((ulong)hex_buf[off + 3] << 32)\n"
    "             | ((ulong)hex_buf[off + 4] << 24)\n"
    "             | ((ulong)hex_buf[off + 5] << 16)\n"
    "             | ((ulong)hex_buf[off + 6] <<  8)\n"
    "             |  (ulong)hex_buf[off + 7];\n"
    "    }\n"
    "    for (int i = 0; i < 8; i++) cv[i] = st->state[i];\n"
    "    whirlpool_compress_cv(st->state, M, cv);\n"
    "\n"
    "    /* Block 3: padding-only. 0x80 at byte 0 (M[0] high byte BE),\n"
    "     * zeros, 256-bit BE bit count = 128 * 8 = 1024 in low 64 bits (M[7]).\n"
    "     * Whirlpool stores 256-bit BE bit count in last 32 bytes (M[4..7]).\n"
    "     * For 128 bytes input total, bit count fits in M[7] = 1024. */\n"
    "    for (int j = 0; j < 8; j++) M[j] = 0UL;\n"
    "    M[0] = 0x8000000000000000UL;   /* 0x80 in first byte BE */\n"
    "    M[7] = 1024UL;                  /* bit count */\n"
    "    for (int i = 0; i < 8; i++) cv[i] = st->state[i];\n"
    "    whirlpool_compress_cv(st->state, M, cv);\n"
    "\n"
    "    /* Decompose updated state into h[16]. */\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the leading\n"
    " * 16 bytes of the final digest. h[0..3] holds the 4 LE uint32 leading\n"
    " * words (populated by template_state_to_h via finalize/iterate).\n"
    " *\n"
    " * Mirrors gpu_wrlunsalted.cl:765-769 exactly: probe with h[0], h[1],\n"
    " * h[2], h[3]. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. Wraps EMIT_HIT_16 (WRL = 16 uint32\n"
    " * digest words, populated LE-byteswapped in st->h by finalize/iterate).\n"
    " * Wire format matches gpu_wrlunsalted.cl emit. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_16((hits), (hit_count), (max_hits), \\\n"
    "                (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_16_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
