/* Auto-generated from gpu_kernel_a_rules.cl -- do not edit */
static const char gpu_kernel_a_rules_str[] =
    "/*\n"
    " * $Revision: $\n"
    " * $Log: $\n"
    " *\n"
    " */\n"
    "/* gpu_kernel_a_rules.cl -- Kernel A1 (rules-only) candidate producer.\n"
    " *\n"
    " * Production kernel A variant A1 per Phase 1a spec\n"
    " *   project_kernel_a_variants_phase1a_spec_2026-05-20.md.\n"
    " *\n"
    " * Produces packed candidates from input words x rule set via the\n"
    " * buffer-quadruple API (b_packed_buf, b_chunk_index, b_kernelA_state,\n"
    " * b_params). Output is consumable by any kernel B that obeys the\n"
    " * buffer-quadruple contract; in this codebase the existing kernel B\n"
    " * salt-axis dispatcher (gpu_opencl_kernelb_dispatch_proto) is the\n"
    " * primary consumer.\n"
    " *\n"
    " * Mechanical lineage: split from gpu_md5_rules.cl's md5_rules_phase0\n"
    " * production kernel. Identical apply_rule walker, identical opcode\n"
    " * contract, identical (word, rule) geometry, identical B3 cursor\n"
    " * semantics, identical no-op / rejection skip optimizations. The\n"
    " * MD5 + probe + EMIT_HIT tail is replaced by a write of [len][bytes]\n"
    " * into a packed candidate buffer with per-slot byte offset.\n"
    " *\n"
    " * Authoritative buffer contract:\n"
    " *   project_two_kernel_candidate_buffer_contract.md\n"
    " * Phase 1a A-variant spec:\n"
    " *   project_kernel_a_variants_phase1a_spec_2026-05-20.md\n"
    " *\n"
    " * Contract per buffer:\n"
    " *   b_packed_buf        - [len][bytes][len][bytes]... post-rule candidates.\n"
    " *                         len byte stored as uchar; bytes follow uncompressed.\n"
    " *                         Written at slot's reserved byte offset.\n"
    " *   b_chunk_index       - uint32 per slot. b_chunk_index[slot] = byte offset\n"
    " *                         into b_packed_buf where this candidate's len byte\n"
    " *                         lives. Pure physical byte offsets only.\n"
    " *   b_kernelA_state     - small counter buffer:\n"
    " *                           offset 0 : uint slot_counter   (atomic_inc)\n"
    " *                           offset 4 : uint byte_counter   (atomic_add for\n"
    " *                                                            variable-size\n"
    " *                                                            byte reservation)\n"
    " *                           offset 8 : uint overflow_flag  (set if either\n"
    " *                                                            counter exceeds\n"
    " *                                                            its capacity;\n"
    " *                                                            host re-issues\n"
    " *                                                            with larger\n"
    " *                                                            buffer or\n"
    " *                                                            smaller chunk)\n"
    " *\n"
    " * Walker behavior (mirrors md5_rules_phase0):\n"
    " *   1. Decode payload -> params, hit_count region (unused here but the same\n"
    " *      payload layout per the brief), word_offset, words.\n"
    " *   2. Decompose gid -> (word_idx, rule_idx) rule-major: same as the prod\n"
    " *      kernel.\n"
    " *   3. B3 cursor early-return for chunked overflow restart.\n"
    " *   4. Stage input word into private buf[].\n"
    " *   5. apply_rule(rule_program + rpos, buf, wlen) -> new_len.\n"
    " *   6. Rejection (new_len < 0): no slot reserved, no buffer write.\n"
    " *   7. No-op detection (!is_no_rule && new_len == wlen && buf == words):\n"
    " *      synthetic no-rule pass already covered this candidate; no slot.\n"
    " *      Foundational mdxfind behavior (feedback_no_rule_pass.md).\n"
    " *   8. Otherwise: reserve a slot, write [new_len][buf bytes] into\n"
    " *      b_packed_buf at the reserved byte offset, write byte offset into\n"
    " *      b_chunk_index[slot].\n"
    " *\n"
    " * Kernel B contract (consumer side, separate kernel):\n"
    " *   uint slot      = gid;\n"
    " *   uint wpos      = b_chunk_index[slot];\n"
    " *   if (wpos >= params.packed_size) return;  -- bounds guard per contract S5.2\n"
    " *   uint plen      = b_packed_buf[wpos];\n"
    " *   uchar *cand    = b_packed_buf + wpos + 1;\n"
    " *   uint widx      = params.base_word_idx + slot;\n"
    " *   -- kernel B then hashes cand[0..plen-1] and probes; EMIT_HIT_4 with\n"
    " *      widx + iter + digest. Per contract S7.1, no rule_idx sidecar is\n"
    " *      propagated; the plaintext IS the candidate and the host reads it\n"
    " *      from b_packed_buf[b_chunk_index[slot]].\n"
    " *\n"
    " * Geometry: same rule-major dispatch as md5_rules_phase0:\n"
    " *   global_size = n_words * n_rules\n"
    " *   word_idx    = gid % n_words\n"
    " *   rule_idx    = gid / n_words\n"
    " *\n"
    " * Reused primitives from gpu_common.cl: OCLParams struct only.\n"
    " *   - No md5_block / md5_buf / md5_to_hex_lc reference (kernel A pure).\n"
    " *   - No probe_compact_idx reference.\n"
    " *   - No EMIT_HIT_N reference.\n"
    " *\n"
    " * Salt-axis logic: not applicable. Salts are kernel B's concern. The\n"
    " * rules walker section of md5_rules_phase0 has no salt-axis fan-out\n"
    " * (verified by reading lines 1064-1153 of gpu_md5_rules.cl rev 1.30);\n"
    " * salts feed into the trailing MD5+probe block which kernel A omits.\n"
    " *\n"
    " * ====================================================================\n"
    " * KNOB G (2026-05-29) -- coalesced uint4 (16-byte) candidate writes.\n"
    " * --------------------------------------------------------------------\n"
    " * Build-gated by -DKNOBG_VEC_WRITE=1 (host env-flag MDXFIND_EXPERIMENT_-\n"
    " * RULES_CODEGEN_VEC_WRITE=1 + parent ..._MD5=1). When the macro is\n"
    " * defined, the per-byte write loop that emits [len][bytes] into\n"
    " * b_packed_buf is replaced by uint4 (16-byte) stores from a private\n"
    " * 16-aligned staging buffer. Each slot's atomic byte-claim is rounded\n"
    " * UP to a multiple of 16 (need_aligned = (need_bytes + 15) & ~15), so\n"
    " * every slot starts on a 16-byte boundary and consumes a 16-byte\n"
    " * multiple of bytes. Pad bytes inside each slot's padded tail are\n"
    " * undefined; the consumer reads only [len] bytes (plen) and never\n"
    " * accesses padding -- bit-perfect equivalence with the legacy path.\n"
    " *\n"
    " * Invariant (proof by induction): the candidate buffer base is\n"
    " * 16-byte aligned by OpenCL guarantee; first byte_off=0 (16-aligned);\n"
    " * every subsequent claim adds a multiple of 16 -> every byte_off is a\n"
    " * multiple of 16. Aligned uint4 stores into the slot region are legal.\n"
    " *\n"
    " * Capacity: cap_packed sizing (host: cap_slots * 256) is unchanged.\n"
    " * 256 is the max need_aligned (need_bytes max = 256 = 1+255). Knob G\n"
    " * shifts ACTUAL bytes consumed per slot from emit_len+1 to\n"
    " * 16*ceil((emit_len+1)/16) ~ +3.8 B/slot on rockyou-1m mean (still\n"
    " * well under the cap; bounded halve-K retry handles the impossible-\n"
    " * by-construction overflow case unchanged).\n"
    " *\n"
    " * Authoritative spec: project_rules_codegen_knob_g_spec_2026-05-29.md.\n"
    " * ====================================================================\n"
    " */\n"
    "\n"
    "/* ==== Opcode definitions (must match ruleproc.c RULE_OP_* exactly) ==== */\n"
    "#define RULE_OP_INSERT      0xfd\n"
    "#define RULE_OP_OVERWRITE   0xfc\n"
    "#define RULE_OP_TOGGLE_AT   0xfb\n"
    "#define RULE_OP_INC         0xfa\n"
    "#define RULE_OP_DEC         0xf9\n"
    "#define RULE_OP_TRUNC       0xf8\n"
    "#define RULE_OP_DROP_LAST   0xf7\n"
    "#define RULE_OP_SUB         0xf6\n"
    "#define RULE_OP_LOWER       0xf5\n"
    "#define RULE_OP_UPPER       0xf4\n"
    "#define RULE_OP_CAP         0xf3\n"
    "#define RULE_OP_CAP_INV     0xf2\n"
    "#define RULE_OP_REVERSE     0xf1\n"
    "#define RULE_OP_TOGGLE      0xf0\n"
    "#define RULE_OP_TITLE_SP    0xef\n"
    "#define RULE_OP_TITLE_SEP   0xee\n"
    "#define RULE_OP_DUP         0xed\n"
    "#define RULE_OP_REFLECT     0xec\n"
    "#define RULE_OP_DUP_EACH    0xeb\n"
    "#define RULE_OP_ROT_L       0xea\n"
    "#define RULE_OP_ROT_R       0xe9\n"
    "#define RULE_OP_SWAP_FRONT  0xe8\n"
    "#define RULE_OP_SWAP_BACK   0xe7\n"
    "#define RULE_OP_DROP_FIRST  0xe6\n"
    "#define RULE_OP_APPEND      0xe5\n"
    "#define RULE_OP_PREPEND     0xe4\n"
    "#define RULE_OP_DEL_AT      0xe3\n"
    "#define RULE_OP_BIT_SHL     0xe2\n"
    "#define RULE_OP_BIT_SHR     0xe1\n"
    "#define RULE_OP_REPL_NEXT   0xe0\n"
    "#define RULE_OP_REPL_PREV   0xdf\n"
    "#define RULE_OP_PURGE       0xde\n"
    "#define RULE_OP_DUP_LAST    0xdd\n"
    "#define RULE_OP_DUP_FIRST   0xdc\n"
    "#define RULE_OP_REPEAT      0xdb\n"
    "#define RULE_OP_DUP_PREFIX  0xda\n"
    "#define RULE_OP_DUP_SUFFIX  0xd9\n"
    "#define RULE_OP_SWAP_AT     0xd8\n"
    "#define RULE_OP_EXTRACT     0xd7\n"
    "#define RULE_OP_OMIT        0xd6\n"
    "#define RULE_OP_TOGGLE_SEP  0xd5\n"
    "#define RULE_OP_NOOP        0xd4\n"
    "#define RULE_OP_NOOP_SP     0xd3\n"
    "#define RULE_OP_NOOP_TAB    0xd2\n"
    "#define RULE_OP_MEM_STORE   0xd1\n"
    "#define RULE_OP_MEM_APP     0xd0\n"
    "#define RULE_OP_MEM_PRE     0xcf\n"
    "#define RULE_OP_MEM_REJ     0xce\n"
    "#define RULE_OP_MEM_INSERT  0xcd\n"
    "#define RULE_OP_REJ_LEN_NE  0xcc\n"
    "#define RULE_OP_REJ_LEN_GE  0xcb\n"
    "#define RULE_OP_REJ_LEN_LE  0xca\n"
    "#define RULE_OP_REJ_HAS     0xc9\n"
    "#define RULE_OP_REJ_NHAS    0xc8\n"
    "#define RULE_OP_REJ_FIRST   0xc7\n"
    "#define RULE_OP_REJ_LAST    0xc6\n"
    "#define RULE_OP_S_SPECIAL   0xc5\n"
    "#define RULE_OP_HASH_EXIT   0xc4\n"
    "#define RULE_OP_HEX_UPPER   0xc3\n"
    "#define RULE_OP_HEX_LOWER   0xc2\n"
    "#define RULE_OP_DIV_INSERT  0xc1\n"
    "\n"
    "#define RULE_BUF_MAX   40960\n"
    "#define RULE_BUF_LIMIT (RULE_BUF_MAX - 1)\n"
    "\n"
    "/* Kernel-A state buffer offsets. Single source of truth for host wiring\n"
    " * (Phase 4) to mirror via fixed-offset writes/reads. */\n"
    "#define KERNELA_STATE_SLOT_COUNTER   0u\n"
    "#define KERNELA_STATE_BYTE_COUNTER   4u\n"
    "#define KERNELA_STATE_OVERFLOW_FLAG  8u\n"
    "#define KERNELA_STATE_BYTES         12u\n"
    "\n"
    "/* ==== Branchless case-flip helper ====================================\n"
    " *\n"
    " * case_flip_mask(c) returns 0x20 if `c` is alphabetic (A-Z or a-z),\n"
    " * else 0. Verbatim from gpu_md5_rules.cl rev 1.30.\n"
    " */\n"
    "static inline uchar case_flip_mask(uchar c) {\n"
    "    uchar v = (uchar)((c | (uchar)0x20) - (uchar)'a');\n"
    "    return (uchar)((v < (uchar)26) ? 0x20 : 0);\n"
    "}\n"
    "\n"
    "/* ==== Unified single-buffer in-place rule walker =====================\n"
    " *\n"
    " * Verbatim copy of apply_rule from gpu_md5_rules.cl rev 1.30 (lines\n"
    " * 179-954). The walker is identical bytecode contract, identical\n"
    " * rejection semantics, identical bounds discipline. Future post-prototype\n"
    " * refactor may hoist this into a shared header consumed by both kernels.\n"
    " * For Phase 2 mechanical-split scope, verbatim duplication is correct.\n"
    " */\n"
    "static int apply_rule(__global const uchar *prog, uchar *buf, int len)\n"
    "{\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 3\n"
    "    /* V3 (PROFILE_VARIANT=3): stub apply_rule — return input length\n"
    "     * unchanged; suppress the huge opcode switch entirely. The walker\n"
    "     * still runs (word read into buf), the atomic claim still happens,\n"
    "     * the per-byte write still happens; only the apply_rule body is\n"
    "     * stubbed. Used to isolate the cost of the rule-walker switch.\n"
    "     * Compile-time: this `if`-true block is the entire function body. */\n"
    "    return len;\n"
    "#else\n"
    "    int k = 0;\n"
    "    int orig_len = len;\n"
    "\n"
    "    for (int n = 0; n < 256; n++) {\n"
    "        uchar op = prog[k];\n"
    "        if (op == 0) break;\n"
    "\n"
    "        switch (op) {\n"
    "\n"
    "            /* ---- Variable-length affix ops (0xff / 0xfe) ---- */\n"
    "            case 0xff: {\n"
    "                int N = (int)prog[k + 1];\n"
    "                int n_copy = N;\n"
    "                if (len + n_copy > RULE_BUF_LIMIT) n_copy = RULE_BUF_LIMIT - len;\n"
    "                if (n_copy < 0) n_copy = 0;\n"
    "                for (int j = 0; j < n_copy; j++) {\n"
    "                    buf[len + j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += n_copy;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "            case 0xfe: {\n"
    "                int N = (int)prog[k + 1];\n"
    "                int new_pre = N;\n"
    "                if (len + new_pre > RULE_BUF_LIMIT) new_pre = RULE_BUF_LIMIT - len;\n"
    "                if (new_pre < 0) new_pre = 0;\n"
    "                for (int j = len - 1; j >= 0; j--) {\n"
    "                    int dst = j + new_pre;\n"
    "                    if (dst <= RULE_BUF_LIMIT) buf[dst] = buf[j];\n"
    "                }\n"
    "                for (int j = 0; j < new_pre; j++) {\n"
    "                    buf[j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += new_pre;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Insert / overwrite / toggle ---- */\n"
    "            case RULE_OP_INSERT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                if (pos >= 0 && pos < len && len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > pos; j--) buf[j] = buf[j - 1];\n"
    "                    buf[pos] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OVERWRITE: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                if (pos >= 0 && pos < len) buf[pos] = ch;\n"
    "                if (pos == 0 && len == 0) { buf[0] = ch; len++; }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_AT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    buf[pos] ^= case_flip_mask(buf[pos]);\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position arithmetic (branchless) ---- */\n"
    "            case RULE_OP_INC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] + (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DEC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] - (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Length-shrink ---- */\n"
    "            case RULE_OP_TRUNC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                len = (pos < len) ? pos : len;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DROP_LAST: {\n"
    "                len -= (len > 0);\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Substitute ---- */\n"
    "            case RULE_OP_SUB: {\n"
    "                uchar c1 = prog[k + 1], c2 = prog[k + 2];\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                uchar16 v_c1 = (uchar16)c1;\n"
    "                uchar16 v_c2 = (uchar16)c2;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 eq = (v == v_c1);\n"
    "                    uchar16 eq_mask = as_uchar16(eq);\n"
    "                    uchar16 result = v ^ ((v ^ v_c2) & eq_mask);\n"
    "                    vstore16(result, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    if (buf[j] == c1) buf[j] = c2;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-string case ops ---- */\n"
    "            case RULE_OP_LOWER: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_upper = (v >= (uchar16)'A') & (v <= (uchar16)'Z');\n"
    "                    uchar16 mask = as_uchar16(is_upper) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_UPPER: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_lower = (v >= (uchar16)'a') & (v <= (uchar16)'z');\n"
    "                    uchar16 mask = as_uchar16(is_lower) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_upper = (v >= (uchar16)'A') & (v <= (uchar16)'Z');\n"
    "                    uchar16 mask = as_uchar16(is_upper) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                for (int q = 0; q < len; q++) {\n"
    "                    uchar c = buf[q];\n"
    "                    if (c >= 'a' && c <= 'z') {\n"
    "                        buf[q] = c ^ (uchar)0x20;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP_INV: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    char16 is_lower = (v >= (uchar16)'a') & (v <= (uchar16)'z');\n"
    "                    uchar16 mask = as_uchar16(is_lower) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                for (int q = 0; q < len; q++) {\n"
    "                    uchar c = buf[q];\n"
    "                    if (c >= 'A' && c <= 'Z') {\n"
    "                        buf[q] = c ^ (uchar)0x20;\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REVERSE: {\n"
    "                int i = 0, j = len - 1;\n"
    "                while (i < j) {\n"
    "                    uchar t = buf[i];\n"
    "                    buf[i] = buf[j];\n"
    "                    buf[j] = t;\n"
    "                    i++;\n"
    "                    j--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE: {\n"
    "                int j = 0;\n"
    "                int vbound = len & ~15;\n"
    "                for (; j < vbound; j += 16) {\n"
    "                    uchar16 v = vload16(0, buf + j);\n"
    "                    uchar16 v_or = v | (uchar16)0x20;\n"
    "                    uchar16 v_d  = v_or - (uchar16)'a';\n"
    "                    char16 is_alpha = (v_d < (uchar16)26);\n"
    "                    uchar16 mask = as_uchar16(is_alpha) & (uchar16)0x20;\n"
    "                    vstore16(v ^ mask, 0, buf + j);\n"
    "                }\n"
    "                for (; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                        buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Title-case ---- */\n"
    "            case RULE_OP_TITLE_SP: {\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == ' ') { z = 0; }\n"
    "                    else if (z == 0 && c >= 'a' && c <= 'z') { z = 1; buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else if (c >= 'A' && c <= 'Z') { buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_SEP: {\n"
    "                uchar delim = prog[k + 1];\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == delim) { z = 0; }\n"
    "                    else if (z == 0 && c >= 'a' && c <= 'z') { z = 1; buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else if (c >= 'A' && c <= 'Z') { buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-buffer length-grow ops ---- */\n"
    "            case RULE_OP_DUP: {\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    int j = 0;\n"
    "                    int vbound = tlen & ~15;\n"
    "                    for (; j < vbound; j += 16) {\n"
    "                        uchar16 v = vload16(0, buf + j);\n"
    "                        vstore16(v, 0, buf + len + j);\n"
    "                    }\n"
    "                    for (; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REFLECT: {\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = 0; j < tlen; j++)\n"
    "                        buf[len + tlen - 1 - j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_EACH: {\n"
    "                int tlen = len;\n"
    "                if (tlen * 2 <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = tlen - 1; j >= 0; j--) {\n"
    "                        uchar c = buf[j];\n"
    "                        buf[j * 2]     = c;\n"
    "                        buf[j * 2 + 1] = c;\n"
    "                    }\n"
    "                    len = tlen * 2;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Rotation / swap ---- */\n"
    "            case RULE_OP_ROT_L: {\n"
    "                if (len > 0) {\n"
    "                    uchar first = buf[0];\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    buf[len - 1] = first;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_ROT_R: {\n"
    "                if (len > 0) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = last;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_FRONT: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[0]; buf[0] = buf[1]; buf[1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_BACK: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[len - 2];\n"
    "                    buf[len - 2] = buf[len - 1];\n"
    "                    buf[len - 1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Drop first / append / prepend ---- */\n"
    "            case RULE_OP_DROP_FIRST: {\n"
    "                if (len > 0) {\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_APPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) buf[len++] = ch;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_PREPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            case RULE_OP_DEL_AT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    for (int j = pos; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position bit shifts / nearest-neighbor copy ---- */\n"
    "            case RULE_OP_BIT_SHL: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] << 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_BIT_SHR: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] >> 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_NEXT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    buf[pos] = (pos + 1 < len) ? buf[pos + 1] : (uchar)0;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_PREV: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos > 0 && pos < len) buf[pos] = buf[pos - 1];\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Purge ---- */\n"
    "            case RULE_OP_PURGE: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                int w = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] != ch) buf[w++] = buf[j];\n"
    "                }\n"
    "                len = w;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Last/first-char duplicators ---- */\n"
    "            case RULE_OP_DUP_LAST: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    int j = 0;\n"
    "                    int vbound = n2 & ~15;\n"
    "                    uchar16 v_last = (uchar16)last;\n"
    "                    for (; j < vbound; j += 16) {\n"
    "                        vstore16(v_last, 0, buf + len + j);\n"
    "                    }\n"
    "                    for (; j < n2; j++) buf[len + j] = last;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_FIRST: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar first = buf[0];\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j + n2] = buf[j];\n"
    "                    for (int j = 1; j <= n2; j++) buf[j] = first;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPEAT: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                int tlen = len;\n"
    "                if (tlen > 0 && n2 > 0) {\n"
    "                    for (int copy = 0; copy < n2; copy++) {\n"
    "                        if (len + tlen > RULE_BUF_LIMIT) break;\n"
    "                        for (int j = 0; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                        len += tlen;\n"
    "                    }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_PREFIX: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    for (int j = len - 1; j >= 0; j--) buf[j + n2] = buf[j];\n"
    "                    for (int j = 0; j < n2; j++) buf[j] = buf[j + n2];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_SUFFIX: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    for (int j = 0; j < n2; j++) buf[len + j] = buf[len - n2 + j];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Position-paired ops ---- */\n"
    "            case RULE_OP_SWAP_AT: {\n"
    "                int posA = (int)prog[k + 1] - 1;\n"
    "                int posB = (int)prog[k + 2] - 1;\n"
    "                if (posA >= 0 && posA < len && posB >= 0 && posB < len) {\n"
    "                    uchar t = buf[posA]; buf[posA] = buf[posB]; buf[posB] = t;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_EXTRACT: {\n"
    "                int start = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (start > 0 && start < len && count > 0) {\n"
    "                    int actual = 0;\n"
    "                    while (actual < count && (start + actual) < len) {\n"
    "                        buf[actual] = buf[start + actual];\n"
    "                        actual++;\n"
    "                    }\n"
    "                    len = actual;\n"
    "                } else if (start == 0 && start < len && count > 0) {\n"
    "                    int actual = 0;\n"
    "                    while (actual < count && actual < len) {\n"
    "                        actual++;\n"
    "                    }\n"
    "                    len = actual;\n"
    "                } else if (start >= len || start < 0) {\n"
    "                    /* applyrule: clen > y false branch, no change. */\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OMIT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (pos >= 0 && pos < len && count > 0 && pos + count <= len) {\n"
    "                    for (int j = pos; j + count < len; j++) buf[j] = buf[j + count];\n"
    "                    len -= count;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_SEP: {\n"
    "                int upos = (int)prog[k + 1] - 1;\n"
    "                uchar sep = prog[k + 2];\n"
    "                int toggle_next = 0;\n"
    "                int occurrence = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == sep) {\n"
    "                        if (occurrence == upos) toggle_next = 1;\n"
    "                        else occurrence++;\n"
    "                        continue;\n"
    "                    }\n"
    "                    if (toggle_next) {\n"
    "                        if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                            buf[j] = c ^ case_flip_mask(c);\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- No-ops ---- */\n"
    "            case RULE_OP_NOOP:\n"
    "            case RULE_OP_NOOP_SP:\n"
    "            case RULE_OP_NOOP_TAB:\n"
    "                k += 1;\n"
    "                break;\n"
    "\n"
    "            /* ---- Special ops (silent no-ops) ---- */\n"
    "            case RULE_OP_S_SPECIAL:  k += 1; break;\n"
    "            case RULE_OP_HASH_EXIT:  k += 1; break;\n"
    "            case RULE_OP_DIV_INSERT: k += 3; break;\n"
    "\n"
    "            /* ---- Rejection ops ---- */\n"
    "            case RULE_OP_REJ_LEN_NE: {\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (y != orig_len) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_GE: {\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len < y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_LE: {\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len > y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_HAS: {\n"
    "                uchar c = prog[k + 1];\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) return -1;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_NHAS: {\n"
    "                uchar c = prog[k + 1];\n"
    "                int found = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) { found = 1; break; }\n"
    "                }\n"
    "                if (!found) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_FIRST: {\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[0] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LAST: {\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[len - 1] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* H/h hex emit: split cases (ROCm comgr addrspace fix per\n"
    "             * gpu_md5_rules.cl rev 1.27). */\n"
    "            case RULE_OP_HEX_UPPER: {\n"
    "                const uchar uhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','A','B','C','D','E','F'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = uhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = uhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_HEX_LOWER: {\n"
    "                const uchar lhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','a','b','c','d','e','f'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = lhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = lhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            default:\n"
    "                return len;\n"
    "        }\n"
    "    }\n"
    "    return len;\n"
    "#endif  /* PROFILE_VARIANT == 3 stub guard */\n"
    "}\n"
    "\n"
    "/* ---- Kernel A1 (rules-only) production kernel --------------------\n"
    " *\n"
    " * Payload layout is identical to md5_rules_phase0 (Memo B B1\n"
    " * coalesced layout):\n"
    " *\n"
    " *   offset   0 : OCLParams params\n"
    " *   offset 128 : uint hit_count            (unused by kernel A; reserved\n"
    " *                                            for payload symmetry with\n"
    " *                                            md5_rules_phase0)\n"
    " *   offset 132 : uint word_offset[num_words]\n"
    " *   offset 132 + 4*num_words : uchar packed_words[]\n"
    " *\n"
    " * params.base_word_idx is read for hit-attribution propagation. Phase 1\n"
    " * rev 1.23 of gpu_common.cl renamed reserved32[0] -> base_word_idx with\n"
    " * this exact semantic. Kernel A does NOT write base_word_idx; the host\n"
    " * sets it before dispatch.\n"
    " *\n"
    " * params.packed_size is read as the kernel-A output buffer capacity (bytes\n"
    " * available in b_packed_buf). Overflow detection: any candidate that would\n"
    " * push byte_counter past packed_size sets overflow_flag and returns\n"
    " * without writing.\n"
    " *\n"
    " * Output buffer caps (capacity guards):\n"
    " *   b_packed_buf       capacity = params.packed_size bytes\n"
    " *   b_chunk_index      capacity = params.num_words * params.num_rules slots\n"
    " *                                  (worst case: every (word, rule) emits\n"
    " *                                   a slot, which is the rejection-free /\n"
    " *                                   no-op-free upper bound).\n"
    " *\n"
    " * On overflow the kernel signals via overflow_flag (state offset 8); host\n"
    " * retries with a smaller chunk or larger buffer. Mirrors the rules-engine\n"
    " * B3 cursor pattern.\n"
    " */\n"
    "\n"
    "__kernel\n"
    "void cand_rules_phase0(\n"
    "    __global uchar         *payload,\n"
    "    __global const uchar   *rule_program,\n"
    "    __global const uint    *rule_offset,\n"
    "    __global uchar         *b_packed_buf,\n"
    "    __global uint          *b_chunk_index,\n"
    "    __global volatile uint *b_kernelA_state\n"
    "    )\n"
    "{\n"
    "    __global const OCLParams *params_buf = (__global const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words = params.num_words;\n"
    "    /* RULE-AXIS CHUNKING (Option A, 2026-05-29): params.num_rules carries the\n"
    "     * per-chunk rule COUNT (rule_count) and params.rule_cursor_start carries\n"
    "     * the per-chunk rule BASE (rule_start) into rule_offset[]. The host loops\n"
    "     * disjoint rule sub-ranges [rule_start, rule_start+rule_count) so the\n"
    "     * candidate buffer for one dispatch is bounded to n_words*rule_count*256\n"
    "     * <= cap. When the whole ruleset fits one chunk (e347 / small rule count)\n"
    "     * the host sets rule_start=0 and rule_count=n_rules, making this decode\n"
    "     * BYTE-IDENTICAL to the pre-chunking geometry (rule_idx = gid / n_words).\n"
    "     * The legacy B3 overflow-cursor early-return is REMOVED from this A1 path:\n"
    "     * with chunking the per-chunk buffer cannot overflow by construction\n"
    "     * (host caps K), and overloading rule_cursor_start with two meanings\n"
    "     * (chunk base vs overflow-restart cursor) would corrupt the chunk decode.\n"
    "     * Overflow is now handled host-side by a bounded halve-K retry. */\n"
    "    uint rule_start = params.rule_cursor_start;  /* chunk base into rule_offset[] */\n"
    "    uint n_rules    = params.num_rules;           /* this chunk's rule_count */\n"
    "    uint total      = n_words * n_rules;\n"
    "\n"
    "    uint gid = get_global_id(0);\n"
    "\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    /* ==== PROFILE_VARIANT scaffolding (2026-05-29, perf decomposition) =====\n"
    "     * When the kernel is JIT-built with -DPROFILE_VARIANT=N (N in 1..5), the\n"
    "     * per-lane kernel body is progressively stubbed to attribute kernel_a_us\n"
    "     * to its components. V0 (default; macro undefined) = byte-identical to\n"
    "     * the production path. ALL variants leave b_kernelA_state untouched\n"
    "     * (slot_counter = 0, byte_counter = 0) so the host sees actual_slots=0\n"
    "     * and skips kernel B; kernel_a_us is captured by the existing CL\n"
    "     * profiling event before kernel B runs (host site\n"
    "     * gpu_opencl.c:13059 `if (actual_slots == 0) ... continue` already exists).\n"
    "     * Crack-parity is INTENTIONALLY NOT preserved for V1..V5; results are\n"
    "     * throwaway, this is timing-only profiling infrastructure.\n"
    "     *\n"
    "     *   V1 = no atomic claim (per-lane deterministic offset gid*256 instead\n"
    "     *        of atomic_add; per-byte write still happens; apply_rule still\n"
    "     *        runs). Measures: atomic_add cost share.\n"
    "     *   V2 = no candidate write (atomic_add still happens but per-byte\n"
    "     *        write loop is no-op'd; index store skipped). Measures: per-byte\n"
    "     *        write loop cost share (BUT note V2 lets atomic still fire so\n"
    "     *        slot_counter would advance; we force it back to 0 below via\n"
    "     *        an end-of-kernel reset by lane 0 to keep host-side\n"
    "     *        actual_slots=0 invariant).\n"
    "     *   V3 = stub apply_rule (returns wlen unchanged; rule walker walks\n"
    "     *        but switch body is gone). Measures: apply_rule switch cost.\n"
    "     *   V4 = walker only — read word into buf, then return. NO apply_rule,\n"
    "     *        NO atomic, NO write. Measures: word-read + apply_rule + write\n"
    "     *        in aggregate (delta from V5).\n"
    "     *   V5 = empty kernel — return immediately. Measures: dispatch overhead\n"
    "     *        + chunk-loop overhead + kernel launch latency.\n"
    "     *\n"
    "     * V5 must short-circuit BEFORE the word-read; place gate here. */\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 5\n"
    "    return;\n"
    "#endif\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint rule_idx = rule_start + (gid / n_words);  /* GLOBAL rule index */\n"
    "\n"
    "    /* Deterministic sub-buffer pointers from params.num_words (identical\n"
    "     * to md5_rules_phase0). The compiler hoists since they depend only on\n"
    "     * params (uniform across the dispatch). hit_count + ovr_set + ovr_gid\n"
    "     * regions exist for payload symmetry; kernel A does not read or write\n"
    "     * them. */\n"
    "    __global const uint   *word_offset = (__global const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    __global const uchar  *words = payload + pkt_off;\n"
    "\n"
    "    /* Private buffer (16-byte aligned, matches md5_rules_phase0). */\n"
    "    __attribute__((aligned(16))) uchar buf[RULE_BUF_MAX];\n"
    "\n"
    "    /* Per-lane emit state. Populated for in-range lanes only. */\n"
    "    int should_emit = 0;\n"
    "    uint emit_len = 0u;\n"
    "    uint need_bytes = 0u;\n"
    "    uint wpos = 0u;\n"
    "\n"
    "    /* Walk the rule. */\n"
    "    {\n"
    "        wpos = word_offset[word_idx];\n"
    "        int wlen = (int)words[wpos++];\n"
    "        if (wlen > RULE_BUF_LIMIT) wlen = RULE_BUF_LIMIT;\n"
    "        for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 4\n"
    "        /* V4 (walker only): stop here. word_read into buf is done; skip\n"
    "         * apply_rule, atomic claim, per-byte write, index store. The\n"
    "         * compiler must not dead-strip the buf write — `buf` is private\n"
    "         * stack; force a fence by reading it back into a sink. */\n"
    "        if (buf[0] == 0xffu) {\n"
    "            /* unreachable on real data (wlen>0 by construction); inserted\n"
    "             * to keep the buf write in the live range so the compiler does\n"
    "             * not strip the read into buf. */\n"
    "            atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 0u);\n"
    "        }\n"
    "        return;\n"
    "#endif\n"
    "\n"
    "        uint rpos = rule_offset[rule_idx];\n"
    "        int is_no_rule = (rule_program[rpos] == 0);\n"
    "        int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "\n"
    "        if (new_len >= 0) {\n"
    "            /* No-op detection: synthetic \":\" no-rule pass already covered\n"
    "             * this candidate; skip slot emission. Foundational mdxfind\n"
    "             * behavior (feedback_no_rule_pass.md). Matches md5_rules_phase0\n"
    "             * exactly. */\n"
    "            int suppress_noop = 0;\n"
    "            if (!is_no_rule && new_len == wlen) {\n"
    "                int changed = 0;\n"
    "                for (int i = 0; i < wlen; i++) {\n"
    "                    if (buf[i] != words[wpos + i]) { changed = 1; break; }\n"
    "                }\n"
    "                if (!changed) suppress_noop = 1;\n"
    "            }\n"
    "            if (!suppress_noop) {\n"
    "                /* Clamp new_len to fit in the [len] byte. RULE_BUF_LIMIT <\n"
    "                 * 65536 so caller-side capacity ensures it; defensive guard\n"
    "                 * for the uchar length-byte slot. */\n"
    "                uint elen = (uint)new_len;\n"
    "                if (elen > 255u) elen = 255u;\n"
    "                emit_len = elen;\n"
    "                need_bytes = 1u + elen;   /* [len][bytes] */\n"
    "                should_emit = 1;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* Per-lane global atomic_add slot/byte reservation. */\n"
    "    if (!should_emit) return;\n"
    "\n"
    "#if defined(PROFILE_VARIANT) && PROFILE_VARIANT == 1\n"
    "    /* V1 (no atomic claim): substitute deterministic per-lane offsets for\n"
    "     * the atomic_add slot/byte reservation. Per-byte write still happens\n"
    "     * (so V0 - V1 attributes the atomic_add cost). slot_counter +\n"
    "     * byte_counter stay at zero, so host sees actual_slots=0 and skips\n"
    "     * kernel B. The fake byte_off (gid * 256) keeps writes within the\n"
    "     * pre-allocated packed buffer for any gid covered by the host's K-cap\n"
    "     * (worst-case K*num_words slots, 256 B/slot = cap). */\n"
    "    uint byte_off = gid * 256u;\n"
    "    uint slot     = gid;\n"
    "    if (byte_off + need_bytes > params.packed_size) return;\n"
    "    if (slot >= total) return;\n"
    "    b_packed_buf[byte_off] = (uchar)emit_len;\n"
    "    for (uint i = 0; i < emit_len; i++) {\n"
    "        b_packed_buf[byte_off + 1u + i] = buf[i];\n"
    "    }\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "#elif defined(PROFILE_VARIANT) && PROFILE_VARIANT == 2\n"
    "    /* V2 (no candidate write): atomic claim still runs (so V0 - V2\n"
    "     * attributes the per-byte write loop). Per-byte memcpy + index store\n"
    "     * are removed. We INTENTIONALLY do not write slot_counter — we use a\n"
    "     * private read-write of the byte_counter to keep the atomic_add live\n"
    "     * (compiler must not fold; the result `byte_off` is unused). To prevent\n"
    "     * the host from running kernel B with non-zero actual_slots, we leave\n"
    "     * slot_counter alone (it stays 0). */\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes);\n"
    "    /* Keep byte_off live so the compiler doesn't drop the atomic; cheap\n"
    "     * side-effect via overflow flag (ored with 0 = no-op functionally). */\n"
    "    if (byte_off == 0xffffffffu) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 0u);\n"
    "    }\n"
    "    /* Slot-counter NOT incremented (intentional — host actual_slots=0 ->\n"
    "     * kernel B skipped). Per-byte write loop omitted (the measured target). */\n"
    "#elif defined(PROFILE_VARIANT) && PROFILE_VARIANT == 6\n"
    "    /* V6 (Knob G micro-benchmark; D4 in knob_g_spec): V0 baseline with\n"
    "     * the Knob G vectorized write loop FORCED ON, regardless of\n"
    "     * KNOBG_VEC_WRITE. Used to measure V0-vs-V6 kernel_a_us delta in\n"
    "     * the same harness that motivated Knob G -- closes the prediction-\n"
    "     * verification loop. Slot/byte claim semantics + crack output are\n"
    "     * IDENTICAL to V0 with KNOBG_VEC_WRITE=1; the only reason V6\n"
    "     * exists separately is so the operator can toggle just this leg\n"
    "     * of the cost share via MDXFIND_PROFILE_VARIANT=6 without setting\n"
    "     * MDXFIND_EXPERIMENT_RULES_CODEGEN_VEC_WRITE. */\n"
    "    {\n"
    "        uint need_aligned = (need_bytes + 15u) & ~15u;\n"
    "        uint byte_off = atomic_add(\n"
    "            &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "            need_aligned);\n"
    "        if (byte_off + need_aligned > params.packed_size) {\n"
    "            atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "            return;\n"
    "        }\n"
    "        uint slot = atomic_add(\n"
    "            &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u], 1u);\n"
    "        if (slot >= total) {\n"
    "            atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "            return;\n"
    "        }\n"
    "        __private uchar __attribute__((aligned(16))) stage[256];\n"
    "        stage[0] = (uchar)emit_len;\n"
    "        for (uint i = 0; i < emit_len; i++) stage[1u + i] = buf[i];\n"
    "        uint nvec = need_aligned / 16u;\n"
    "        __global uint4 *dst = (__global uint4 *)(b_packed_buf + byte_off);\n"
    "        __private uint4 *src = (__private uint4 *)stage;\n"
    "        for (uint v = 0; v < nvec; v++) dst[v] = src[v];\n"
    "        b_chunk_index[slot] = byte_off;\n"
    "    }\n"
    "#else\n"
    "    /* V0 (production baseline) — legacy path. KNOB G gated. */\n"
    "#ifdef KNOBG_VEC_WRITE\n"
    "    /* KNOB G ON: round need_bytes up to a 16-byte multiple. The atomic\n"
    "     * shape is unchanged (single atomic_add); only the value is rounded.\n"
    "     * Slot-start alignment proof: base ptr 16-aligned + each running sum\n"
    "     * adds a multiple of 16 -> every byte_off is 16-aligned. */\n"
    "    uint need_aligned = (need_bytes + 15u) & ~15u;\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_aligned);\n"
    "\n"
    "    /* Capacity guard: use the post-rounding byte count for the bound\n"
    "     * check (otherwise the tail uint4 stores could spill past packed). */\n"
    "    if (byte_off + need_aligned > params.packed_size) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "#else\n"
    "    uint byte_off = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes);\n"
    "\n"
    "    /* Capacity guard: did this lane's reservation push past packed_size?\n"
    "     * If so, flag overflow and return WITHOUT incrementing slot_counter\n"
    "     * (so the slot count reflects only successfully-emitted candidates). */\n"
    "    if (byte_off + need_bytes > params.packed_size) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "#endif\n"
    "\n"
    "    uint slot = atomic_add(\n"
    "        &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u], 1u);\n"
    "\n"
    "    /* Slot-index capacity: bounded by num_words * num_rules (host alloc\n"
    "     * size). If for some reason slot >= total (overflow paradox: lanes\n"
    "     * past 'total' early-returned at the top), flag and skip. */\n"
    "    if (slot >= total) {\n"
    "        atomic_or(&b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u], 1u);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    /* --- Write [len][bytes] into packed buf ----------------------- */\n"
    "#ifdef KNOBG_VEC_WRITE\n"
    "    /* KNOB G ON: stage [len][bytes] into a private 16-aligned buffer,\n"
    "     * then issue need_aligned/16 uint4 stores. emit_len in [0,255] ->\n"
    "     * need_aligned in [16,256] -> nvec in [1,16]. Pad bytes in\n"
    "     * stage[1+emit_len .. need_aligned) are undefined; consumer reads\n"
    "     * only plen bytes after the [len] header (see §3 spec). */\n"
    "    {\n"
    "        __private uchar __attribute__((aligned(16))) stage[256];\n"
    "        stage[0] = (uchar)emit_len;\n"
    "        for (uint i = 0; i < emit_len; i++) stage[1u + i] = buf[i];\n"
    "        uint nvec = need_aligned / 16u;\n"
    "        __global uint4 *dst = (__global uint4 *)(b_packed_buf + byte_off);\n"
    "        __private uint4 *src = (__private uint4 *)stage;\n"
    "        for (uint v = 0; v < nvec; v++) dst[v] = src[v];\n"
    "    }\n"
    "#else\n"
    "    b_packed_buf[byte_off] = (uchar)emit_len;\n"
    "    for (uint i = 0; i < emit_len; i++) {\n"
    "        b_packed_buf[byte_off + 1u + i] = buf[i];\n"
    "    }\n"
    "#endif\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "#endif  /* PROFILE_VARIANT 1/2/6/V0 selection */\n"
    "    /* Per-spec invariant 1: caller (Phase 4 host) relies on in-order\n"
    "     * single-queue FIFO to ensure these writes are visible to kernel B\n"
    "     * before kernel B dispatches. No explicit fence; the queue boundary\n"
    "     * provides the cross-kernel global-memory visibility. */\n"
    "}\n"
;
