/* Auto-generated from gpu_sha512raw_core.cl -- do not edit */
static const char gpu_sha512raw_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sha512raw_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha512raw_core.cl — SHA512RAW algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 5a, Tier 1).\n"
    " *\n"
    " * SHA512RAW differs from SHA512 ONLY in template_iterate:\n"
    " *   - SHA512  iter (gpu_sha512_core.cl): re-hash 128-byte hex_lc encoding\n"
    " *     of the digest. Bytes are ASCII '0'..'9','a'..'f'. Two blocks\n"
    " *     required (128 hex + 0x80 + 16 length = 145 > 128, so two-block).\n"
    " *   - SHA512RAW iter (this file):     re-hash the 64-byte BINARY digest\n"
    " *     directly. Single block (64 + 1 + 16 = 81 ≤ 128).\n"
    " *\n"
    " * CPU reference (mdxfind.c rev 1.394+ JOB_SHA512RAW at line 27579):\n"
    " *\n"
    " *   for (x = 1; x <= Maxiter; x++) {\n"
    " *     mysha512(...);\n"
    " *     cur = (char *)curin.h;\n"
    " *     len = 64;                         // BINARY 64 bytes\n"
    " *     memcpy(cur, md5buf.h, len);\n"
    " *     checkhash(&curin, 128, x, job);\n"
    " *   }\n"
    " *\n"
    " * Block layout for the iter step:\n"
    " *   M[0..7]  = 64 BE digest bytes from state[0..7] (each ulong holds 8\n"
    " *              bytes BE; matches the BE state ordering)\n"
    " *   M[8]     = 0x8000000000000000UL  (0x80 at byte 64 in BE position)\n"
    " *   M[9..13] = 0\n"
    " *   M[14]    = 0                 (high 64 bits of bit count)\n"
    " *   M[15]    = 64 * 8 = 512      (low 64 bits)\n"
    " *\n"
    " * All other extension functions (template_state, template_init,\n"
    " * template_transform, template_finalize, template_digest_compare,\n"
    " * template_emit_hit) are byte-identical to gpu_sha512_core.cl.\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=16,HASH_BLOCK_BYTES=128\" —\n"
    " * same as SHA512. Distinct cache entry guaranteed by source-text hash\n"
    " * difference (only template_iterate differs).\n"
    " *\n"
    " * R1 mitigation: single private buffer pattern; no addrspace-cast helpers.\n"
    " *\n"
    " * R2 (register pressure): same compression footprint as SHA512.\n"
    " * priv_mem_size on gfx1201 expected ~ 42.5 KB, comparable to SHA512.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha512raw_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 16\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 128\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    ulong state[8];   /* internal compression state, BIG-ENDIAN */\n"
    "    uint  h[HASH_WORDS]; /* exposed digest words, LE-byteswapped uint32 (16 = full 64-byte digest) */\n"
    "} template_state;\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->state[0] = 0x6a09e667f3bcc908UL;\n"
    "    st->state[1] = 0xbb67ae8584caa73bUL;\n"
    "    st->state[2] = 0x3c6ef372fe94f82bUL;\n"
    "    st->state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "    st->state[4] = 0x510e527fade682d1UL;\n"
    "    st->state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "    st->state[6] = 0x1f83d9abfb41bd6bUL;\n"
    "    st->state[7] = 0x5be0cd19137e2179UL;\n"
    "}\n"
    "\n"
    "static inline void template_state_to_h(template_state *st) {\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong s = bswap64(st->state[i]);\n"
    "        st->h[i*2]   = (uint)s;\n"
    "        st->h[i*2+1] = (uint)(s >> 32);\n"
    "    }\n"
    "}\n"
    "\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    ulong M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 8;\n"
    "        M[j] = ((ulong)block[b]     << 56)\n"
    "             | ((ulong)block[b + 1] << 48)\n"
    "             | ((ulong)block[b + 2] << 40)\n"
    "             | ((ulong)block[b + 3] << 32)\n"
    "             | ((ulong)block[b + 4] << 24)\n"
    "             | ((ulong)block[b + 5] << 16)\n"
    "             | ((ulong)block[b + 6] << 8)\n"
    "             |  (ulong)block[b + 7];\n"
    "    }\n"
    "    sha512_block(&st->state[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: byte-identical to gpu_sha512_core.cl. SHA512\n"
    " * compression + 128-bit length + full 16-uint32 digest. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    ulong M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 8;\n"
    "            M[j] = ((ulong)data[b]     << 56)\n"
    "                 | ((ulong)data[b + 1] << 48)\n"
    "                 | ((ulong)data[b + 2] << 40)\n"
    "                 | ((ulong)data[b + 3] << 32)\n"
    "                 | ((ulong)data[b + 4] << 24)\n"
    "                 | ((ulong)data[b + 5] << 16)\n"
    "                 | ((ulong)data[b + 6] << 8)\n"
    "                 |  (ulong)data[b + 7];\n"
    "        }\n"
    "        sha512_block(&st->state[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..127 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 3;\n"
    "        int bi = 7 - (i & 7);\n"
    "        M[wi] |= ((ulong)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 3;\n"
    "        int bi = 7 - (rem & 7);\n"
    "        M[wi] |= ((ulong)0x80UL) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 112) {\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    } else {\n"
    "        sha512_block(&st->state[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0UL;\n"
    "        M[14] = 0UL;\n"
    "        M[15] = (ulong)((ulong)len * 8UL);\n"
    "        sha512_block(&st->state[0], M);\n"
    "    }\n"
    "\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "/* template_iterate: SHA512RAW iter — re-feed the 64-byte BINARY digest\n"
    " * (not hex-encoded) into the compression. CPU reference at mdxfind.c\n"
    " * line 27579:\n"
    " *\n"
    " *   memcpy(cur, md5buf.h, 64);\n"
    " *   mysha512(cur, 64);\n"
    " *\n"
    " * Layout: 64 input bytes + 0x80 + zeros + 16 byte length = 81 bytes ≤ 128\n"
    " * (single block). state[0..7] hold the BE digest, mapping 1:1 onto\n"
    " * M[0..7] (sha512_block's M-load convention is BE). M[8] holds the 0x80\n"
    " * marker; M[14..15] holds the bit-count.\n"
    " */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    ulong M[16];\n"
    "    /* Copy the BE-packed digest directly into M[0..7]. state[i] is\n"
    "     * already the BE uint64 of digest bytes [i*8..i*8+7]. */\n"
    "    M[0] = st->state[0];\n"
    "    M[1] = st->state[1];\n"
    "    M[2] = st->state[2];\n"
    "    M[3] = st->state[3];\n"
    "    M[4] = st->state[4];\n"
    "    M[5] = st->state[5];\n"
    "    M[6] = st->state[6];\n"
    "    M[7] = st->state[7];\n"
    "    M[8] = 0x8000000000000000UL;   /* 0x80 BE at byte 64 */\n"
    "    for (int j = 9; j < 14; j++) M[j] = 0UL;\n"
    "    M[14] = 0UL;\n"
    "    M[15] = 64UL * 8UL;            /* 64 binary bytes = 512 bits */\n"
    "\n"
    "    /* Reset state to SHA512 IV; absorb the prepared block. */\n"
    "    st->state[0] = 0x6a09e667f3bcc908UL;\n"
    "    st->state[1] = 0xbb67ae8584caa73bUL;\n"
    "    st->state[2] = 0x3c6ef372fe94f82bUL;\n"
    "    st->state[3] = 0xa54ff53a5f1d36f1UL;\n"
    "    st->state[4] = 0x510e527fade682d1UL;\n"
    "    st->state[5] = 0x9b05688c2b3e6c1fUL;\n"
    "    st->state[6] = 0x1f83d9abfb41bd6bUL;\n"
    "    st->state[7] = 0x5be0cd19137e2179UL;\n"
    "    sha512_block(&st->state[0], M);\n"
    "\n"
    "    template_state_to_h(st);\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_16((hits), (hit_count), (max_hits), \\\n"
    "                (widx), (sidx), (iter), ((st)->h))\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_16_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), ((st)->h), \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
