/* Auto-generated from gpu_phpbb3_core.cl -- do not edit */
static const char gpu_phpbb3_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_phpbb3_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_phpbb3_core.cl -- PHPBB3 / phpass (e455) algorithm extension\n"
    " * functions for the generic dispatch template (Memo B Phase B6 PHPBB3\n"
    " * Path A hand-written sibling of the unsalted-template family).\n"
    " *\n"
    " * STATUS: PHPBB3 fan-out 2026-05-08 -- second iterated-crypt algorithm\n"
    " * after SHA1DRU on the unified template path. Single algo_mode (0); no\n"
    " * KPASS/KSALT siblings -- JOB_PHPBB3 (e455) is a single-mode algorithm.\n"
    " *\n"
    " * PHPBB3 / phpass semantics (mirrors mdxfind.c JOB_PHPBB3 at lines\n"
    " * 13415-13628 + slab oracle gpu_phpbb3.cl):\n"
    " *\n"
    " *   salt buffer (12 bytes total): \"$H$\" + cost_char + 8-byte salt\n"
    " *   cost_char decodes via phpitoa64 = \"./0123456789ABCDEF...xyz\"\n"
    " *   iter_count = 1 << itoa64_index(salt[3])  (typically 7..30 -> 128..2^30)\n"
    " *\n"
    " *   state = MD5(salt[4..11] || pass)        -- 8-byte salt + password\n"
    " *   for (i = 0; i < iter_count; i++):\n"
    " *     state = MD5(state[16] || pass)        -- 16-byte digest + password\n"
    " *\n"
    " *   probe state once at the end (matches CPU semantics at mdxfind.c:13620\n"
    " *   which calls checkhashbb(curin, 32, s1, job) AFTER the for-loop).\n"
    " *\n"
    " * DESIGN: iter loop INSIDE template_finalize, max_iter=1.\n"
    " * --------------------------------------------------------\n"
    " * Mirrors SHA1DRU pattern (B6.11 precedent):\n"
    " *   - the iter count is INTERNAL to the algorithm (decoded from salt\n"
    " *     byte 3), NOT user-controlled via -i;\n"
    " *   - only the FINAL state is probed (CPU semantics); putting the\n"
    " *     loop in template_iterate would either waste a probe per iter\n"
    " *     OR require max_iter = iter_count (which varies per salt!), which\n"
    " *     the host iter-budget infrastructure cannot express;\n"
    " *   - host forces params.max_iter = 1 at the rules-engine pack site\n"
    " *     so the kernel's outer iter loop runs exactly once and never\n"
    " *     calls template_iterate (which is a stub).\n"
    " *\n"
    " * Salt-axis carrier: this kernel routes through the salted-template\n"
    " * scaffolding (GPU_TEMPLATE_HAS_SALT=1, SALT_POSITION=PREPEND in\n"
    " * defines_str). The salt buffer carries the FULL 12-byte \"$H$<cost>\n"
    " * <8-byte salt>\" prefix (mdxfind.c:40572 stores 12 bytes via\n"
    " * store_typesalt(JOB_PHPBB3, line, 12)). gpu_pack_salts is called with\n"
    " * use_hashsalt=0 (no hashsalt synthesis), so salt_buf+salt_off[i] points\n"
    " * at the raw 12-byte salt prefix and salt_lens[i] is 12.\n"
    " *\n"
    " * Inside the kernel:\n"
    " *   - salt_bytes[3]    -> cost char (phpitoa64 lookup -> log2 iter count)\n"
    " *   - salt_bytes[4..11] -> 8-byte salt for step 1\n"
    " *   - salt_bytes[0..2]  -> \"$H$\" prefix (unused inside the kernel; the\n"
    " *                          host already validated the format at salt-load\n"
    " *                          time via mdxfind.c:40559).\n"
    " *\n"
    " * Validation oracle: gpu_phpbb3.cl phpbb3_batch (slab kernel; this file\n"
    " * is a port of that body into the template extension API). Differences:\n"
    " *   - reads pass from `data` (post-rule buf passed by template; PRIVATE\n"
    " *     uchar *) rather than from a packed wordbuf indexed by tid (slab's\n"
    " *     `__global const uchar *pass`);\n"
    " *   - reads salt from `salt_bytes` (the global salt buffer threaded by\n"
    " *     gpu_template.cl under GPU_TEMPLATE_HAS_SALT) rather than from\n"
    " *     the slab's own salts/salt_offsets/salt_lens trio.\n"
    " *\n"
    " * The slab oracle uses M_copy_bytes (gpu_common.cl:761) which takes a\n"
    " * __global pointer; data is __private here, so we use the inline\n"
    " * byte-pack pattern (M[i>>2] |= v << ((i & 3) * 8)) instead. This is\n"
    " * the same pattern md5salt_core / md5saltpass_core use for the private\n"
    " * `data` source. Correctness invariant: identical M[] state to the\n"
    " * slab kernel's M_copy_bytes(M, off, pass, plen) call -- byte-for-byte.\n"
    " *\n"
    " * Hit replay: host calls checkhashbb(curin, 32, salt_bytes, job) where\n"
    " * salt_bytes is the FULL 12-byte \"$H$<cost><8>\" prefix (matches CPU\n"
    " * semantics at mdxfind.c:13620 which passes saltsnap[si].salt = the\n"
    " * full 12-byte prefix).\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single private\n"
    " * buffer pattern. M[16] uint32 working block + 4-uint chaining state\n"
    " * are private; salt_bytes is __global (read byte-by-byte into M[] via\n"
    " * the same inline byte-pack pattern that md5salt_core uses for both\n"
    " * private and global sources -- no addrspace casts).\n"
    " *\n"
    " * R2 (register pressure): one M[16] scratch + 4-uint state + a small\n"
    " * integer for the iter count. Comparable to MD5SALT base body minus\n"
    " * the inner-MD5 hex staging -- expected priv_mem on Pascal in the\n"
    " * 41-43 KB band shared by all unified-template dispatches.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_phpbb3_core_str,\n"
    " *     gpu_template_str ]\n"
    " *\n"
    " * Cache key (R3): defines_str =\n"
    " *   \"HASH_WORDS=4,HASH_BLOCK_BYTES=64,HAS_SALT=1,SALT_POSITION=PREPEND,\n"
    " *    BASE_ALGO=phpbb3\"\n"
    " *\n"
    " * Cache-key disambiguation:\n"
    " *   - From MD5SALT family (HASH_WORDS=4 + HAS_SALT=1 + BASE_ALGO=md5)\n"
    " *     by BASE_ALGO=phpbb3 axis.\n"
    " *   - From every other salted/unsalted template via the unique\n"
    " *     BASE_ALGO=phpbb3 token.\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* phpitoa64 reverse-lookup table for decoding the cost character from\n"
    " * salt byte 3. Mirrors the slab kernel's phpitoa64_k constant\n"
    " * (gpu_phpbb3.cl:7). MD5-LE direct (no bswap32) -- matches the slab\n"
    " * kernel and CPU's mymd5() output convention. */\n"
    "__constant uchar phpbb3_phpitoa64[] =\n"
    "    \"./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\";\n"
    "\n"
    "/* Per-lane state struct: MD5 carries 4 uint32 chaining values (LE). */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install MD5 IV into state. Same IV as gpu_md5_core.cl. */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: stub for interface symmetry. PHPBB3's\n"
    " * template_finalize builds M[] in-place per block -- never routes\n"
    " * through this. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b])\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: full PHPBB3 chain.\n"
    " *\n"
    " * Step 1: state = MD5(salt8 || pass)\n"
    " *   - salt8 = salt_bytes[4..11] (8 bytes, packed into M[0..1])\n"
    " *   - pass  = data[0..plen-1]\n"
    " *   - total = 8 + plen\n"
    " *\n"
    " * Step 2: for each iter, state = MD5(state[16] || pass)\n"
    " *   - M[0..3] receive the previous state's 16 binary bytes (st->h[]).\n"
    " *   - M[4..] receive pass + 0x80 padding + length, computed ONCE outside\n"
    " *     the loop (pass + length doesn't change across iterations).\n"
    " *\n"
    " * Password length cap: matches the slab kernel's \"pass max 39 bytes\"\n"
    " * comment (gpu_phpbb3.cl:6). With plen <= 39, total = 16 + 39 = 55 bytes\n"
    " * fits in a single MD5 block (55 + 1 padding + 8 length = 64). The\n"
    " * chokepoint admit at mdxfind.c gates job->clen <= 39 so this path\n"
    " * is only entered for valid passwords. Defensive cap below clamps to\n"
    " * 39 on entry.\n"
    " *\n"
    " * algo_mode: PHPBB3 has only one mode. The arg is unused; kept for\n"
    " * interface symmetry with the salted-template signature. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "                                     , __global const uchar *salt_bytes\n"
    "                                     , uint salt_len\n"
    "                                     , uint algo_mode\n"
    "#endif\n"
    "                                     )\n"
    "{\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    (void)algo_mode;\n"
    "    (void)salt_len;\n"
    "\n"
    "    /* Defensive: PHPBB3 caps password length at 39 bytes (CPU at\n"
    "     * mdxfind.c:13450 gates job->clen <= 39 before GPU dispatch).\n"
    "     * Clamp here too so a malformed call doesn't produce out-of-bounds\n"
    "     * writes to M[]. */\n"
    "    int plen = len;\n"
    "    if (plen > 39) plen = 39;\n"
    "\n"
    "    /* Decode iter count from salt_bytes[3] via phpitoa64 reverse lookup.\n"
    "     * Mirrors slab kernel gpu_phpbb3.cl lines 31-34 byte-for-byte. */\n"
    "    uchar ic = salt_bytes[3];\n"
    "    int log2count = 0;\n"
    "    for (int k = 0; k < 64; k++) {\n"
    "        if (phpbb3_phpitoa64[k] == ic) { log2count = k; break; }\n"
    "    }\n"
    "    uint count = 1u << log2count;\n"
    "\n"
    "    /* Step 1: MD5(salt[4..11] || pass) -- single MD5 block (8 + 39 + 1\n"
    "     * padding + 8 length = 56 max, well under 64).\n"
    "     *\n"
    "     * Build M[16] in LE byte order via the inline pack pattern (matches\n"
    "     * md5salt_core's mode-0 inner-MD5 streaming loop). */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    /* Pack salt_bytes[4..11] (8 bytes) into M[0..1] little-endian. */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint v = (uint)salt_bytes[4 + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    /* Pack pass[0..plen-1] into M starting at byte offset 8. */\n"
    "    for (int i = 0; i < plen; i++) {\n"
    "        int pos = 8 + i;\n"
    "        uint v = (uint)data[i];\n"
    "        M[pos >> 2] |= v << ((pos & 3) * 8);\n"
    "    }\n"
    "    int total = 8 + plen;\n"
    "    /* MD5 padding marker. */\n"
    "    M[total >> 2] |= (uint)0x80u << ((total & 3) * 8);\n"
    "    /* Length in bits, little-endian uint32 at M[14] (low 32 bits suffice\n"
    "     * for total <= 55 bytes = 440 bits). */\n"
    "    M[14] = (uint)total * 8u;\n"
    "\n"
    "    /* Reset state to MD5 IV before absorbing block 1. */\n"
    "    uint hx = 0x67452301u;\n"
    "    uint hy = 0xEFCDAB89u;\n"
    "    uint hz = 0x98BADCFEu;\n"
    "    uint hw = 0x10325476u;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Step 2: N iterations of MD5(state[16] || pass).\n"
    "     *\n"
    "     * Pre-pack M[] with pass + padding + length. M[0..3] will be\n"
    "     * overwritten with the chaining state per iteration; M[4..] stays\n"
    "     * constant across iterations.\n"
    "     *\n"
    "     * total = 16 + plen (max 16 + 39 = 55 -- single MD5 block). */\n"
    "    total = 16 + plen;\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "    /* Pass starts at byte 16 (after the 16-byte digest slot). */\n"
    "    for (int i = 0; i < plen; i++) {\n"
    "        int pos = 16 + i;\n"
    "        uint v = (uint)data[i];\n"
    "        M[pos >> 2] |= v << ((pos & 3) * 8);\n"
    "    }\n"
    "    /* MD5 padding marker at byte (16 + plen). */\n"
    "    M[total >> 2] |= (uint)0x80u << ((total & 3) * 8);\n"
    "    /* Length in bits at M[14] (LE uint32). */\n"
    "    M[14] = (uint)total * 8u;\n"
    "\n"
    "    /* Iteration loop: only M[0..3] change per iter; the digest absorbs\n"
    "     * its own previous output. Mirrors slab kernel gpu_phpbb3.cl lines\n"
    "     * 55-59 byte-for-byte. */\n"
    "    for (uint ic2 = 0; ic2 < count; ic2++) {\n"
    "        M[0] = hx;\n"
    "        M[1] = hy;\n"
    "        M[2] = hz;\n"
    "        M[3] = hw;\n"
    "        /* Reset state to MD5 IV for each iter (the digest of the prior\n"
    "         * iter is already loaded into M[0..3] via the four lines above). */\n"
    "        hx = 0x67452301u;\n"
    "        hy = 0xEFCDAB89u;\n"
    "        hz = 0x98BADCFEu;\n"
    "        hw = 0x10325476u;\n"
    "        md5_block(&hx, &hy, &hz, &hw, M);\n"
    "    }\n"
    "\n"
    "    /* Install final state into template_state for digest compare + emit. */\n"
    "    st->h[0] = hx;\n"
    "    st->h[1] = hy;\n"
    "    st->h[2] = hz;\n"
    "    st->h[3] = hw;\n"
    "    return;\n"
    "#else\n"
    "    /* Defensive fall-through for the !HAS_SALT instantiation. PHPBB3 is\n"
    "     * always a salted op (the salt carries the iteration count); a no-\n"
    "     * salt build would have nothing to do. Compute MD5(data) so the\n"
    "     * extension interface stays well-formed. */\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "    while ((len - pos) >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b])\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "    int rem = len - pos;\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = (i & 3) * 8;\n"
    "        M[wi] |= ((uint)data[pos + i]) << bi;\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = (rem & 3) * 8;\n"
    "        M[wi] |= ((uint)0x80u) << bi;\n"
    "    }\n"
    "    if (rem < 56) {\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    } else {\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)((uint)len * 8u);\n"
    "        md5_block(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    }\n"
    "#endif\n"
    "}\n"
    "\n"
    "/* template_iterate: STUB. With max_iter = 1 (host-set for PHPBB3), the\n"
    " * outer iter loop in template_phase0 runs exactly once and never calls\n"
    " * template_iterate. Mirrors SHA1DRU pattern (gpu_sha1dru_core.cl\n"
    " * lines 313-317). */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    (void)st;\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the 4 MD5 LE\n"
    " * digest words. Identical to gpu_md5_core.cl's template_digest_compare\n"
    " * (PHPBB3's final state is in MD5 native LE byte order). */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit. PHPBB3 = 4 LE uint32 digest words\n"
    " * (same wire format as MD5). */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
