/* Auto-generated from gpu_md5_packed.cl -- do not edit */
static const char gpu_md5_packed_str[] =
    "/* gpu_md5_packed.cl — Packed password MD5 kernel for rule-generated candidates\n"
    " *\n"
    " * Input: packed buffer of [uint8 len][password bytes] entries, tightly packed.\n"
    " *        word_offset[] array of uint32 byte offsets, one per word.\n"
    " *\n"
    " * One thread per word. Each thread reads its offset, unpacks password,\n"
    " * computes MD5, probes compact table. Supports iteration (md5(md5(x))).\n"
    " *\n"
    " * params.num_words = total passwords in buffer\n"
    " * params.max_iter = iteration count (1 = single hash, >1 = iterated)\n"
    " * params.reserved32[0] = word_start (chunk offset)\n"
    " *\n"
    " * Primitives (md5_block, md5_to_hex_lc, probe_compact, EMIT_HIT_4)\n"
    " * provided by gpu_common.cl\n"
    " */\n"
    "\n"
    "__kernel void md5_packed_batch(\n"
    "    __global const uchar *packed_buf,     /* [len][data][len][data]... */\n"
    "    __global const uint *word_offset,     /* uint32 byte offset per word */\n"
    "    __global const uchar *unused_mask,    /* unused — matches kernel arg layout */\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_start = params.reserved32[0];\n"
    "    uint word_idx = word_start + tid;\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Read word position directly from offset array */\n"
    "    uint pos = word_offset[word_idx];\n"
    "    uint len = packed_buf[pos++];\n"
    "\n"
    "    /* Build M[16] from packed password */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    /* Copy password bytes into M[] in little-endian uint32 layout */\n"
    "    uint i = 0;\n"
    "    for (; i + 3 < len; i += 4) {\n"
    "        M[i >> 2] = (uint)packed_buf[pos + i]\n"
    "                  | ((uint)packed_buf[pos + i + 1] << 8)\n"
    "                  | ((uint)packed_buf[pos + i + 2] << 16)\n"
    "                  | ((uint)packed_buf[pos + i + 3] << 24);\n"
    "    }\n"
    "    /* Remaining bytes + 0x80 padding */\n"
    "    uint tail = 0;\n"
    "    uint shift = 0;\n"
    "    for (; i < len; i++) {\n"
    "        tail |= (uint)packed_buf[pos + i] << shift;\n"
    "        shift += 8;\n"
    "    }\n"
    "    tail |= (uint)0x80 << shift;\n"
    "    M[i >> 2] = tail;\n"
    "\n"
    "    /* Bit length in M[14] */\n"
    "    M[14] = len * 8;\n"
    "\n"
    "    /* MD5 compress */\n"
    "    uint hx = 0x67452301u, hy = 0xEFCDAB89u;\n"
    "    uint hz = 0x98BADCFEu, hw = 0x10325476u;\n"
    "    md5_block(&hx, &hy, &hz, &hw, M);\n"
    "\n"
    "    /* Iteration loop: probe at each iteration, hex-encode and re-hash */\n"
    "    uint max_iter = params.max_iter;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        if (probe_compact(hx, hy, hz, hw, compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe,\n"
    "                          params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes,\n"
    "                          overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_4(hits, hit_count, params.max_hits,\n"
    "                       word_idx, 0, iter, hx, hy, hz, hw)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode hash into M[0..7], set up 32-byte input padding */\n"
    "            md5_to_hex_lc(hx, hy, hz, hw, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;  /* 32 hex bytes = 256 bits */\n"
    "            hx = 0x67452301u; hy = 0xEFCDAB89u;\n"
    "            hz = 0x98BADCFEu; hw = 0x10325476u;\n"
    "            md5_block(&hx, &hy, &hz, &hw, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
