/* Auto-generated from gpu_sha1raw_core.cl -- do not edit */
static const char gpu_sha1raw_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_sha1raw_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha1raw_core.cl — SHA1RAW algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B5 sub-batch 6, Tier A).\n"
    " *\n"
    " * SHA1RAW differs from SHA1 ONLY in template_iterate:\n"
    " *   - SHA1    iter (gpu_sha1_core.cl): re-hash 40-byte hex_lc encoding.\n"
    " *   - SHA1RAW iter (this file):     re-hash the 20-byte BINARY digest\n"
    " *     directly. No hex re-encoding.\n"
    " *\n"
    " * CPU reference (mdxfind.c JOB_SHA1RAW at line 26321):\n"
    " *\n"
    " *   for (x = 1; x <= Maxiter; x++) {\n"
    " *     mysha1(cur, len, md5buf.h);\n"
    " *     cur = (char *)curin.h;\n"
    " *     len = 20;                     // BINARY 20 bytes\n"
    " *     memcpy(cur, md5buf.h, len);\n"
    " *     checkhash(md5buf, 40, x, job);\n"
    " *   }\n"
    " *\n"
    " * Block layout for the iter step (20-byte input, SHA1 BE):\n"
    " *   M[0..4] = 20 BE digest bytes from state[0..4]\n"
    " *             (st->h[i] is the BE uint32 from sha1_block; M-load reads\n"
    " *             bytes BE — these match identically.)\n"
    " *   M[5]    = 0x80000000u  (0x80 padding marker at byte 20, BE)\n"
    " *   M[6..13]= 0\n"
    " *   M[14]   = 0  (high 32 bits of bit count)\n"
    " *   M[15]   = 20 * 8 = 160\n"
    " *\n"
    " * 20 + 1 + 8 = 29 < 56 ⇒ single block.\n"
    " *\n"
    " * State width / byte order: SHA1 carries 5 BE uint32 chaining values.\n"
    " * Final digest h[0..4] (after template_finalize) is BIG-ENDIAN — matches\n"
    " * gpu_sha1_core.cl convention. template_digest_compare bswap32's the\n"
    " * leading 4 words to LE before probing (mirrors gpu_sha1_core.cl's\n"
    " * compare).\n"
    " *\n"
    " * All other extension functions are byte-identical to gpu_sha1_core.cl.\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=5,HASH_BLOCK_BYTES=64\" —\n"
    " * same as SHA1. Distinct cache entry guaranteed by source-text hash\n"
    " * difference (only template_iterate differs).\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha1raw_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 5\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "}\n"
    "\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* SHA1 reads message words big-endian. */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b]     << 24)\n"
    "             | ((uint)block[b + 1] << 16)\n"
    "             | ((uint)block[b + 2] << 8)\n"
    "             |  (uint)block[b + 3];\n"
    "    }\n"
    "    sha1_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: byte-identical to gpu_sha1_core.cl. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b]     << 24)\n"
    "                 | ((uint)data[b + 1] << 16)\n"
    "                 | ((uint)data[b + 2] << 8)\n"
    "                 |  (uint)data[b + 3];\n"
    "        }\n"
    "        sha1_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = 3 - (i & 3);\n"
    "        M[wi] |= ((uint)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = 3 - (rem & 3);\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    } else {\n"
    "        sha1_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha1_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: SHA1RAW iter — re-feed the 20-byte BINARY digest\n"
    " * (not hex-encoded) into the compression. State words are BE uint32\n"
    " * (sha1_block's natural form); M-load reads bytes BE — st->h[i]\n"
    " * directly maps to M[i] for i in 0..4.\n"
    " *\n"
    " * Layout:\n"
    " *   M[0..4]  = st->h[0..4] (20 BE digest bytes; native sha1 word order)\n"
    " *   M[5]     = 0x80000000u (0x80 BE at byte 20)\n"
    " *   M[6..13] = 0\n"
    " *   M[14]    = 0\n"
    " *   M[15]    = 20 * 8 = 160 (low 32 of bit count, BE)\n"
    " *\n"
    " * Single block (20 + 1 + 8 = 29 < 56). After absorption, h[] holds the\n"
    " * fresh digest in native SHA1 BE form.\n"
    " */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    M[0] = st->h[0];\n"
    "    M[1] = st->h[1];\n"
    "    M[2] = st->h[2];\n"
    "    M[3] = st->h[3];\n"
    "    M[4] = st->h[4];\n"
    "    M[5] = 0x80000000u;\n"
    "    for (int j = 6; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 0u;\n"
    "    M[15] = 20u * 8u;\n"
    "    /* Reset state to SHA1 IV; absorb the prepared block. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    st->h[4] = 0xC3D2E1F0u;\n"
    "    sha1_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    uint h0 = bswap32(st->h[0]);\n"
    "    uint h1 = bswap32(st->h[1]);\n"
    "    uint h2 = bswap32(st->h[2]);\n"
    "    uint h3 = bswap32(st->h[3]);\n"
    "    return probe_compact_idx(\n"
    "        h0, h1, h2, h3,\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[5]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        EMIT_HIT_5_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h, \\\n"
    "                   (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                   (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
;
