/* Auto-generated from gpu_blake2s256unsalted.cl -- do not edit */
static const char gpu_blake2s256unsalted_str[] =
    "/* gpu_blake2s256unsalted.cl — Pre-padded unsalted BLAKE2S-256 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted(): password bytes at offset n_prepend,\n"
    " *   total_len stored as uint16 at bytes [56..57] (after the password area).\n"
    " *   BLAKE2S uses its own padding (no 0x80/bitlen), so the packer just stores\n"
    " *   the password and length — the kernel handles BLAKE2S-specific finalization.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " *\n"
    " * Primitives (B2S_IV, B2S_SIGMA, b2s_compress) provided by gpu_common.cl\n"
    " */\n"
    "\n"
    "__kernel void blake2s256_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-packed block (16 uint32 = 64 bytes).\n"
    "     * Password bytes start at n_prepend. Total length at M[14] bits [7:0] and [15:8]. */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uchar buf[64];\n"
    "    for (int i = 0; i < 64; i++)\n"
    "        buf[i] = ((__global const uchar *)src)[i];\n"
    "\n"
    "    /* Fill mask positions */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    /* Read total_len from packed M[14] (stored as bitlen by packer, extract byte len) */\n"
    "    uint M14 = src[14];\n"
    "    int total_len = M14 >> 3;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                buf[i] = ch;\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    buf[app_start + i] = ch;\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                buf[app_start + i] = ch;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* BLAKE2S-256: single-block hash (password <= 55 bytes fits in one 64-byte block).\n"
    "     * Init: IV ^ parameter block (outlen=32, keylen=0, fanout=1, depth=1). */\n"
    "    uint h[8];\n"
    "    for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "    h[0] ^= 0x01010020u;\n"
    "\n"
    "    /* Zero bytes after password */\n"
    "    for (int i = total_len; i < 64; i++) buf[i] = 0;\n"
    "\n"
    "    /* Single compress with last=1, counter=total_len */\n"
    "    b2s_compress(h, buf, (ulong)total_len, 1);\n"
    "\n"
    "    /* BLAKE2S-256: 8 hash words, output is LE — no bswap */\n"
    "    uint max_iter = params.max_iter;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        if (probe_compact(h[0], h[1], h[2], h[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_8(hits, hit_count, params.max_hits, word_idx, mask_idx, iter, h)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode 8 LE hash words into buf[0..63] (64 hex chars) */\n"
    "            for (int i = 0; i < 8; i++) {\n"
    "                uint s = h[i];\n"
    "                uint b0 = s & 0xff, b1 = (s >> 8) & 0xff;\n"
    "                uint b2 = (s >> 16) & 0xff, b3 = (s >> 24) & 0xff;\n"
    "                uint hi0 = (b0 >> 4) & 0xf, lo0 = b0 & 0xf;\n"
    "                uint hi1 = (b1 >> 4) & 0xf, lo1 = b1 & 0xf;\n"
    "                uint hi2 = (b2 >> 4) & 0xf, lo2 = b2 & 0xf;\n"
    "                uint hi3 = (b3 >> 4) & 0xf, lo3 = b3 & 0xf;\n"
    "                buf[i*8+0] = hi0 + ((hi0 < 10) ? '0' : ('a'-10));\n"
    "                buf[i*8+1] = lo0 + ((lo0 < 10) ? '0' : ('a'-10));\n"
    "                buf[i*8+2] = hi1 + ((hi1 < 10) ? '0' : ('a'-10));\n"
    "                buf[i*8+3] = lo1 + ((lo1 < 10) ? '0' : ('a'-10));\n"
    "                buf[i*8+4] = hi2 + ((hi2 < 10) ? '0' : ('a'-10));\n"
    "                buf[i*8+5] = lo2 + ((lo2 < 10) ? '0' : ('a'-10));\n"
    "                buf[i*8+6] = hi3 + ((hi3 < 10) ? '0' : ('a'-10));\n"
    "                buf[i*8+7] = lo3 + ((lo3 < 10) ? '0' : ('a'-10));\n"
    "            }\n"
    "            /* Re-init BLAKE2S and compress 64-byte hex block */\n"
    "            for (int i = 0; i < 8; i++) h[i] = B2S_IV[i];\n"
    "            h[0] ^= 0x01010020u;\n"
    "            b2s_compress(h, buf, 64UL, 1);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
