/* Auto-generated from gpu_sha256_core.cl -- do not edit */
static const char gpu_sha256_core_str[] =
    "/*\n"
    " * $Revision: 1.3 $\n"
    " * $Log: gpu_sha256_core.cl,v $\n"
    " * Revision 1.3  2026/05/11 05:22:02  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_sha256_core.cl — SHA256 algorithm extension functions for the\n"
    " * generic dispatch template (Memo B Phase B4 fan-out).\n"
    " *\n"
    " * Mirrors gpu_sha1_core.cl rev 1.1 structure exactly. The template body\n"
    " * (gpu_template.cl) is algorithm-agnostic; this file provides the\n"
    " * SHA256-specific extension functions:\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (8 for SHA256)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64 — same Merkle-Damgård\n"
    " *                        block geometry as MD5/SHA1)\n"
    " *   template_state     — opaque per-lane state struct (8 uint32 chaining)\n"
    " *   template_init      — install SHA256 IV (8 standard values)\n"
    " *   template_transform — absorb one 64-byte block (BIG-ENDIAN word load)\n"
    " *   template_finalize  — pad and finalize (in-place M[16] pattern; see\n"
    " *                        the perf-fix lesson at the head of gpu_md5_core.cl)\n"
    " *   template_iterate   — re-hash digest as 64-byte hex_lc (-i loop)\n"
    " *   template_digest_compare — probe compact table with leading 16 bytes\n"
    " *                             (h[0..3], LE-byteswapped to match the\n"
    " *                             host-side compact table key encoding)\n"
    " *   template_emit_hit       — EMIT_HIT_8 wrapper (8 LE digest words)\n"
    " *\n"
    " * KEY POINTS vs gpu_sha1_core.cl:\n"
    " *\n"
    " * 1. State width. SHA256 carries 8 uint32 chaining values (vs SHA1's 5).\n"
    " *    The state struct is uint h[HASH_WORDS] = uint h[8].\n"
    " *\n"
    " * 2. Message schedule. SHA256 uses W[0..63] with the recurrence\n"
    " *    W[t] = SSIG1(W[t-2]) + W[t-7] + SSIG0(W[t-15]) + W[t-16];\n"
    " *    sha256_block (gpu_common.cl line 484) handles this.\n"
    " *\n"
    " * 3. BIG-ENDIAN identical to SHA1: message words BE-loaded, length\n"
    " *    encoded as 64-bit BE in M[14..15] (high 32 in M[14], low in M[15]).\n"
    " *    For our wordlist inputs len < 2^29 bytes always, so M[14] = 0 and\n"
    " *    M[15] = len * 8. Same convention as gpu_sha256_packed.cl line 76-78.\n"
    " *\n"
    " * 4. Iter loop. SHA256 hex output is 64 lowercase hex chars, which\n"
    " *    exactly fills one HASH_BLOCK_BYTES block. Pad lands in the SECOND\n"
    " *    block: M[0]=0x80000000 BE, M[1..14]=0, M[15]=64*8=512. Mirrors\n"
    " *    gpu_sha256_packed.cl rev 1's iter step (lines 100-112) byte-for-byte.\n"
    " *\n"
    " * 5. Compact table probe. Same leading-16-byte LE convention as MD5 and\n"
    " *    SHA1: bswap32 the leading 4 state words before probe_compact_idx.\n"
    " *    The remaining 4 words (h[4..7]) are NOT used by the probe — only\n"
    " *    by EMIT_HIT_8.\n"
    " *\n"
    " * 6. EMIT_HIT_8: 8-word emit; widx/sidx/iter triple prepend stays the same.\n"
    " *\n"
    " * Source order at compile time (mirrors SHA1 build):\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_sha256_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides sha256_block(), bswap32, EMIT_HIT_8, and\n"
    " * probe_compact_idx. gpu_md5_rules_str provides apply_rule (the rules\n"
    " * walker is algorithm-agnostic). gpu_sha256_core_str (this file) provides\n"
    " * the per-algorithm hooks. gpu_template_str ties them into template_phase0.\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final digest h[0..7] (after template_finalize) is BIG-ENDIAN —\n"
    " *     the same byte order sha256_block writes back into state[0..7].\n"
    " *     gpu_sha256_packed.cl matches this.\n"
    " *   - template_digest_compare byte-swaps the leading 4 words to LE\n"
    " *     before probing. Matches gpu_sha256_packed.cl line 90's\n"
    " *     `for j: h[j] = bswap32(state[j])` pattern.\n"
    " *   - template_emit_hit writes the LE-byteswapped digest into the hits\n"
    " *     buffer (same as gpu_sha256_packed.cl), so host hit-replay matches\n"
    " *     the legacy SHA256 packed kernel.\n"
    " *\n"
    " * R1 mitigation (AMD ROCm comgr addrspace fragility): single private\n"
    " * buffer pattern. No __private uchar* helpers; no addrspace-cast\n"
    " * ternaries. apply_rule + buf are unchanged from MD5; the algorithm\n"
    " * core only operates on the post-rule buf and emits LE digest words.\n"
    " *\n"
    " * R2 (register pressure): SHA256's W[64] schedule is built on-stack\n"
    " * inside sha256_block (gpu_common.cl line 485) — 64 uint32 = 256 bytes\n"
    " * private, plus 8-word state, plus 4-word transient probe_h. Per-lane\n"
    " * VGPR footprint is moderately larger than SHA1's W[80] (320 bytes)\n"
    " * but with simpler round constants. Expected priv_mem_size on gfx1201\n"
    " * comparable to SHA1's reading, well below the 240-byte risk threshold\n"
    " * (the ~41 KB measurements seen on SHA1/MD5 are dominated by the\n"
    " * RULE_BUF_MAX = 40960 byte buf[] array on the rules walker, not the\n"
    " * compression scratch). Watching this for SHA256 is a B5 prep for the\n"
    " * SHA512 family.\n"
    " *\n"
    " * PERF-FIX LESSON (from gpu_md5_core.cl rev 1.2, repeated for SHA1\n"
    " * rev 1.1, applied here):\n"
    " *\n"
    " * template_finalize MUST build M[16] DIRECTLY from input bytes via\n"
    " * shifts/OR-merge — NOT via a private uchar pad[64] tail-block buffer\n"
    " * that is then read BACK out as message words. This file applies the\n"
    " * same pattern: BE byte ordering of M[] words and 64-bit BE length\n"
    " * encoding in M[14..15].\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. The template uses these as structural\n"
    " * compile-time constants; the kernel-cache key (gpu_kernel_cache R3\n"
    " * fix) hashes the defines_str (\"HASH_WORDS=8,HASH_BLOCK_BYTES=64\")\n"
    " * alongside the source set so distinct instantiations get distinct\n"
    " * cache entries even though source text would otherwise be identical. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 8\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: SHA256 carries 8 uint32 chaining values. The\n"
    " * template only reads/writes the digest words via template_finalize's\n"
    " * output + template_digest_compare; it does not introspect the struct. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* template_init: install SHA256 IV into state.\n"
    " * Standard SHA256 initial hash values (FIPS 180-4 §5.3.3). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x6a09e667u;\n"
    "    st->h[1] = 0xbb67ae85u;\n"
    "    st->h[2] = 0x3c6ef372u;\n"
    "    st->h[3] = 0xa54ff53au;\n"
    "    st->h[4] = 0x510e527fu;\n"
    "    st->h[5] = 0x9b05688cu;\n"
    "    st->h[6] = 0x1f83d9abu;\n"
    "    st->h[7] = 0x5be0cd19u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (64) byte block.\n"
    " * `block` points into the working buffer at the absorb position;\n"
    " * the caller must guarantee >=64 bytes are readable. SHA256 reads\n"
    " * message words BIG-ENDIAN.\n"
    " *\n"
    " * Public extension API; the hot-path template_finalize bypasses this\n"
    " * via an in-place M[16] pattern (see perf-fix lesson at file head).\n"
    " * Kept symmetric with gpu_md5_core.cl/gpu_sha1_core.cl for cores that\n"
    " * prefer the function-style entry. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* SHA256 reads message words big-endian. */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = ((uint)block[b]     << 24)\n"
    "             | ((uint)block[b + 1] << 16)\n"
    "             | ((uint)block[b + 2] << 8)\n"
    "             |  (uint)block[b + 3];\n"
    "    }\n"
    "    sha256_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process the tail, append the 0x80 padding marker\n"
    " * + 64-bit BE length-in-bits, and absorb. Caller passes the full\n"
    " * buffer; we run complete blocks then build the final padded block(s)\n"
    " * here. After return, st->h[0..7] holds the final SHA256 digest words\n"
    " * in BIG-ENDIAN form (sha256_block's natural output).\n"
    " *\n"
    " * Mirrors gpu_sha1_core.cl rev 1.1's in-place M[16] pattern. The\n"
    " * difference vs SHA1 is 8 chaining words (vs 5) and the SHA256 round\n"
    " * constants/schedule (handled by sha256_block).\n"
    " *\n"
    " * R1 mitigation preserved: single private buffer (M[16] uints + the\n"
    " * input data pointer), no addrspace-cast helpers. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Process complete 64-byte blocks. Build M[] BIG-ENDIAN directly\n"
    "     * from bytes. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = ((uint)data[b]     << 24)\n"
    "                 | ((uint)data[b + 1] << 16)\n"
    "                 | ((uint)data[b + 2] << 8)\n"
    "                 |  (uint)data[b + 3];\n"
    "        }\n"
    "        sha256_block(&st->h[0], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    /* Build final block(s): tail bytes + 0x80 marker + zeros + 64-bit\n"
    "     * BE length. Direct-into-M[] approach — no intermediate uchar\n"
    "     * pad[]. */\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Copy remaining tail bytes into M[] big-endian. Each byte's\n"
    "     * position within its 32-bit word is determined by 3-(byte_idx & 3)\n"
    "     * shift (BE: byte 0 is high octet of word). */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int wi = i >> 2;\n"
    "        int bi = 3 - (i & 3);\n"
    "        M[wi] |= ((uint)data[pos + i]) << (bi * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker, BE byte position. */\n"
    "    {\n"
    "        int wi = rem >> 2;\n"
    "        int bi = 3 - (rem & 3);\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    if (rem < 56) {\n"
    "        /* Length fits in this block. SHA256 BE: M[14] = high 32 bits\n"
    "         * of bit count, M[15] = low 32 bits. For len < 2^29 bytes\n"
    "         * (always true for our wordlist inputs), high 32 bits = 0. */\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha256_block(&st->h[0], M);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        sha256_block(&st->h[0], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = 0;\n"
    "        M[15] = (uint)((uint)len * 8u);\n"
    "        sha256_block(&st->h[0], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. Re-encode the digest as 64-byte\n"
    " * lowercase hex ASCII and rehash. SHA256's hex output exactly fills\n"
    " * one 64-byte block, so the pad lands in a SECOND block.\n"
    " *\n"
    " * Mirrors gpu_sha256_packed.cl rev 1 lines 100-112 byte-for-byte:\n"
    " *   - 8 state words -> 16 BE-encoded hex M[] words (2 words per state\n"
    " *     word, 4 hex chars each — matches sha256_to_hex_lc_p)\n"
    " *   - state reset to SHA256 IV; sha256_block(M)\n"
    " *   - second block: M[0] = 0x80000000u BE, M[1..14] = 0, M[15] = 64*8 = 512\n"
    " *   - sha256_block(M) again. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* Inlined sha256_to_hex_lc_p body — keeps gpu_sha256_core\n"
    "     * self-contained. Per-byte BE hex encoding. */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint s = st->h[i];\n"
    "        uint b0 = (s >> 24) & 0xff;\n"
    "        uint b1 = (s >> 16) & 0xff;\n"
    "        uint b2 = (s >> 8)  & 0xff;\n"
    "        uint b3 = s & 0xff;\n"
    "        uint hi0 = (b0 >> 4) & 0xf, lo0 = b0 & 0xf;\n"
    "        uint hi1 = (b1 >> 4) & 0xf, lo1 = b1 & 0xf;\n"
    "        uint hi2 = (b2 >> 4) & 0xf, lo2 = b2 & 0xf;\n"
    "        uint hi3 = (b3 >> 4) & 0xf, lo3 = b3 & 0xf;\n"
    "        uint h0 = ((hi0 + ((hi0 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo0 + ((lo0 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h1 = ((hi1 + ((hi1 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo1 + ((lo1 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h2 = ((hi2 + ((hi2 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo2 + ((lo2 < 10) ? '0' : ('a' - 10)));\n"
    "        uint h3 = ((hi3 + ((hi3 < 10) ? '0' : ('a' - 10))) << 8)\n"
    "                |  (lo3 + ((lo3 < 10) ? '0' : ('a' - 10)));\n"
    "        M[i * 2]     = (h0 << 16) | h1;\n"
    "        M[i * 2 + 1] = (h2 << 16) | h3;\n"
    "    }\n"
    "    /* Reset state to SHA256 IV; absorb first hex block (full 64 bytes). */\n"
    "    st->h[0] = 0x6a09e667u; st->h[1] = 0xbb67ae85u;\n"
    "    st->h[2] = 0x3c6ef372u; st->h[3] = 0xa54ff53au;\n"
    "    st->h[4] = 0x510e527fu; st->h[5] = 0x9b05688cu;\n"
    "    st->h[6] = 0x1f83d9abu; st->h[7] = 0x5be0cd19u;\n"
    "    sha256_block(&st->h[0], M);\n"
    "\n"
    "    /* Second block: pad + length only. */\n"
    "    M[0] = 0x80000000u;\n"
    "    for (int j = 1; j < 15; j++) M[j] = 0u;\n"
    "    M[15] = 64u * 8u;       /* 64 hex chars = 512 bits */\n"
    "    /* M[14] left from the previous block — zero it explicitly to be safe. */\n"
    "    M[14] = 0u;\n"
    "    sha256_block(&st->h[0], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the final\n"
    " * digest. On a hit, *out_idx is set to the matched target's hash_data\n"
    " * index. Return 1 on hit, 0 on miss.\n"
    " *\n"
    " * SHA256 state is stored big-endian (sha256_block's natural form). The\n"
    " * compact table is keyed on the leading 16 BYTES of the digest in\n"
    " * little-endian uint32 form (host-side compact_table_register reads\n"
    " * the digest bytes as 4 LE uint32 to form the key). We byte-swap the\n"
    " * leading 4 words to LE before calling probe_compact_idx.\n"
    " *\n"
    " * Mirrors gpu_sha256_packed.cl line 90's `for j: h[j] = bswap32(state[j])`\n"
    " * pattern verbatim. The remaining state words (h[4..7]) are NOT used\n"
    " * by the compact-table probe — only by EMIT_HIT_8 below. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    uint h0 = bswap32(st->h[0]);\n"
    "    uint h1 = bswap32(st->h[1]);\n"
    "    uint h2 = bswap32(st->h[2]);\n"
    "    uint h3 = bswap32(st->h[3]);\n"
    "    return probe_compact_idx(\n"
    "        h0, h1, h2, h3,\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit into the global hits buffer. Wraps\n"
    " * EMIT_HIT_8 (SHA256 = 8 uint32 digest words). Hits buffer convention\n"
    " * matches gpu_sha256_packed.cl: 8 LE-byteswapped digest words after the\n"
    " * widx/sidx/iter triple.\n"
    " *\n"
    " * The macro builds a private uint h[8] of LE-byteswapped state, then\n"
    " * passes it to EMIT_HIT_8 (which expects an array, not 8 individual\n"
    " * args). Same wire format as gpu_sha256_packed.cl line 98 emit. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[8]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        _h[5] = bswap32((st)->h[5]); \\\n"
    "        _h[6] = bswap32((st)->h[6]); \\\n"
    "        _h[7] = bswap32((st)->h[7]); \\\n"
    "        EMIT_HIT_8((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. See gpu_md5_core.cl for protocol\n"
    " * notes. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[8]; \\\n"
    "        _h[0] = bswap32((st)->h[0]); \\\n"
    "        _h[1] = bswap32((st)->h[1]); \\\n"
    "        _h[2] = bswap32((st)->h[2]); \\\n"
    "        _h[3] = bswap32((st)->h[3]); \\\n"
    "        _h[4] = bswap32((st)->h[4]); \\\n"
    "        _h[5] = bswap32((st)->h[5]); \\\n"
    "        _h[6] = bswap32((st)->h[6]); \\\n"
    "        _h[7] = bswap32((st)->h[7]); \\\n"
    "        EMIT_HIT_8_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h, \\\n"
    "                   (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                   (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
;
