/* Auto-generated from gpu_md4_core.cl -- do not edit */
static const char gpu_md4_core_str[] =
    "/*\n"
    " * $Revision: 1.3 $\n"
    " * $Log: gpu_md4_core.cl,v $\n"
    " * Revision 1.3  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_md4_core.cl — MD4 algorithm extension functions for the generic\n"
    " * dispatch template (Memo B Phase B4 fan-out).\n"
    " *\n"
    " * Mirrors gpu_md5_core.cl rev 1.2 structure exactly. The template body\n"
    " * (gpu_template.cl) is algorithm-agnostic; this file provides the\n"
    " * MD4-specific extension functions:\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (4 for MD4 — same\n"
    " *                        as MD5)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64 — same as MD5)\n"
    " *   template_state     — opaque per-lane state struct (4 uint32 chaining)\n"
    " *   template_init      — install MD4 IV (same 4 standard values as MD5)\n"
    " *   template_transform — absorb one 64-byte block (LITTLE-ENDIAN word load)\n"
    " *   template_finalize  — pad and finalize (in-place M[16] pattern)\n"
    " *   template_iterate   — re-hash digest as 32-byte hex_lc (-i loop)\n"
    " *   template_digest_compare — probe compact table with leading 16 bytes\n"
    " *   template_emit_hit       — EMIT_HIT_4 wrapper (4 LE digest words)\n"
    " *\n"
    " * KEY DIFFERENCES FROM MD5:\n"
    " *\n"
    " * 1. Compression function. MD4 uses 3 rounds × 16 steps (vs MD5's 4 ×\n"
    " *    16). Round functions: F = (X & Y) | (~X & Z); G = (X & Y) | (X & Z) |\n"
    " *    (Y & Z); H = X ^ Y ^ Z. Round constants: 0, 0x5A827999, 0x6ED9EBA1.\n"
    " *    Inlined here as md4_compress (mirrors gpu_md4_packed.cl rev 1's\n"
    " *    md4_compress_p byte-for-byte; gpu_common.cl does NOT export an\n"
    " *    md4_block primitive).\n"
    " *\n"
    " * 2. Endianness same as MD5: LITTLE-ENDIAN message words and LE 64-bit\n"
    " *    length encoding (M[14] = low 32 bits of bit count, M[15] = high\n"
    " *    bits = 0).\n"
    " *\n"
    " * 3. IV same 4 values as MD5: 0x67452301, 0xEFCDAB89, 0x98BADCFE,\n"
    " *    0x10325476 (RFC 1320 §3.3 / RFC 1321 §3.3 — both algorithms share\n"
    " *    these). State is 4 uint32.\n"
    " *\n"
    " * 4. Hex iter loop same as MD5: 32 hex chars = 16 bytes = quarter of a\n"
    " *    block; pad + length fits in one 64-byte block. md5_to_hex_lc from\n"
    " *    gpu_common.cl is reusable (LE 4-word hex format is algorithm-\n"
    " *    independent — both MD4 and MD5 produce 4 LE uint32 digest words).\n"
    " *\n"
    " * 5. EMIT_HIT_4 same as MD5.\n"
    " *\n"
    " * Source order at compile time (mirrors MD5 build):\n"
    " *\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_md4_core_str, gpu_template_str ]\n"
    " *\n"
    " * gpu_common_str provides md5_to_hex_lc, EMIT_HIT_4, OCLParams, and\n"
    " * probe_compact_idx. gpu_md5_rules_str provides apply_rule (the rules\n"
    " * walker is algorithm-agnostic). gpu_md4_core_str (this file) provides\n"
    " * the per-algorithm hooks INCLUDING the inline md4_compress (since\n"
    " * gpu_common.cl does not export an md4_block primitive — gpu_md4_-\n"
    " * packed.cl carries its own).\n"
    " *\n"
    " * Bytecast invariants:\n"
    " *   - Final digest h[0..3] (after template_finalize) is in NATIVE\n"
    " *     order — for MD4 that's little-endian per word (md4_compress\n"
    " *     stores LE chaining values). gpu_md4_packed.cl matches this.\n"
    " *   - template_digest_compare reads st->h[0..3] directly — no bswap\n"
    " *     needed because MD4's natural state order is already LE.\n"
    " *     (Contrast with SHA1/SHA256 which store BE and bswap before probe.)\n"
    " *   - template_emit_hit writes the 4 LE state words directly (no\n"
    " *     bswap — same as MD5).\n"
    " *\n"
    " * R1 mitigation: single private buffer pattern. The inline\n"
    " * md4_compress takes uint pointers to chaining values + a uint M[16];\n"
    " * no __private uchar* helpers; no addrspace-cast ternaries.\n"
    " *\n"
    " * R2 (register pressure): MD4's M[16] schedule is just the 16 message\n"
    " * words (no W[80] expansion like SHA1, no W[64] like SHA256) — smaller\n"
    " * compression-time footprint than either SHA family. Same overall\n"
    " * priv_mem_size as MD5 expected (dominated by the RULE_BUF_MAX = 40960\n"
    " * byte buf[]).\n"
    " *\n"
    " * PERF-FIX LESSON (from gpu_md5_core.cl rev 1.2): template_finalize\n"
    " * builds M[16] DIRECTLY from input bytes via shifts/OR-merge — NOT via\n"
    " * a uchar pad[64] tail-block round-trip. Same pattern applied here.\n"
    " */\n"
    "\n"
    "/* Per-algorithm geometry. The kernel-cache key (R3 fix) hashes the\n"
    " * defines_str (\"HASH_WORDS=4,HASH_BLOCK_BYTES=64\") — note this is\n"
    " * IDENTICAL to MD5's defines_str. Distinct cache entries are guaranteed\n"
    " * because the SOURCE TEXT differs (this file vs gpu_md5_core.cl); the\n"
    " * kernel-cache hash includes the concatenated source text, not just\n"
    " * the defines. */\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* Per-lane state struct: MD4 carries 4 uint32 chaining values. */\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* MD4 compression — fully unrolled, 3 rounds × 16 steps. Mirrors\n"
    " * gpu_md4_packed.cl rev 1's md4_compress_p byte-for-byte. The macros\n"
    " * use rotate() (OpenCL builtin) for left rotation. State chaining is\n"
    " * little-endian per word (same as MD5). */\n"
    "static inline void md4_compress(uint *hx, uint *hy, uint *hz, uint *hw, uint *M) {\n"
    "    uint a = *hx, b = *hy, c = *hz, d = *hw;\n"
    "#define MD4_F(x,y,z) (((x)&(y)) | ((~(x))&(z)))\n"
    "#define MD4_G(x,y,z) (((x)&(y)) | ((x)&(z)) | ((y)&(z)))\n"
    "#define MD4_H(x,y,z) ((x)^(y)^(z))\n"
    "#define MD4_R1(a,b,c,d,k,s) a = rotate(a + MD4_F(b,c,d) + M[k], (uint)(s))\n"
    "#define MD4_R2(a,b,c,d,k,s) a = rotate(a + MD4_G(b,c,d) + M[k] + 0x5A827999u, (uint)(s))\n"
    "#define MD4_R3(a,b,c,d,k,s) a = rotate(a + MD4_H(b,c,d) + M[k] + 0x6ED9EBA1u, (uint)(s))\n"
    "    MD4_R1(a,b,c,d, 0, 3); MD4_R1(d,a,b,c, 1, 7); MD4_R1(c,d,a,b, 2,11); MD4_R1(b,c,d,a, 3,19);\n"
    "    MD4_R1(a,b,c,d, 4, 3); MD4_R1(d,a,b,c, 5, 7); MD4_R1(c,d,a,b, 6,11); MD4_R1(b,c,d,a, 7,19);\n"
    "    MD4_R1(a,b,c,d, 8, 3); MD4_R1(d,a,b,c, 9, 7); MD4_R1(c,d,a,b,10,11); MD4_R1(b,c,d,a,11,19);\n"
    "    MD4_R1(a,b,c,d,12, 3); MD4_R1(d,a,b,c,13, 7); MD4_R1(c,d,a,b,14,11); MD4_R1(b,c,d,a,15,19);\n"
    "    MD4_R2(a,b,c,d, 0, 3); MD4_R2(d,a,b,c, 4, 5); MD4_R2(c,d,a,b, 8, 9); MD4_R2(b,c,d,a,12,13);\n"
    "    MD4_R2(a,b,c,d, 1, 3); MD4_R2(d,a,b,c, 5, 5); MD4_R2(c,d,a,b, 9, 9); MD4_R2(b,c,d,a,13,13);\n"
    "    MD4_R2(a,b,c,d, 2, 3); MD4_R2(d,a,b,c, 6, 5); MD4_R2(c,d,a,b,10, 9); MD4_R2(b,c,d,a,14,13);\n"
    "    MD4_R2(a,b,c,d, 3, 3); MD4_R2(d,a,b,c, 7, 5); MD4_R2(c,d,a,b,11, 9); MD4_R2(b,c,d,a,15,13);\n"
    "    MD4_R3(a,b,c,d, 0, 3); MD4_R3(d,a,b,c, 8, 9); MD4_R3(c,d,a,b, 4,11); MD4_R3(b,c,d,a,12,15);\n"
    "    MD4_R3(a,b,c,d, 2, 3); MD4_R3(d,a,b,c,10, 9); MD4_R3(c,d,a,b, 6,11); MD4_R3(b,c,d,a,14,15);\n"
    "    MD4_R3(a,b,c,d, 1, 3); MD4_R3(d,a,b,c, 9, 9); MD4_R3(c,d,a,b, 5,11); MD4_R3(b,c,d,a,13,15);\n"
    "    MD4_R3(a,b,c,d, 3, 3); MD4_R3(d,a,b,c,11, 9); MD4_R3(c,d,a,b, 7,11); MD4_R3(b,c,d,a,15,15);\n"
    "#undef MD4_F\n"
    "#undef MD4_G\n"
    "#undef MD4_H\n"
    "#undef MD4_R1\n"
    "#undef MD4_R2\n"
    "#undef MD4_R3\n"
    "    *hx = a + *hx; *hy = b + *hy; *hz = c + *hz; *hw = d + *hw;\n"
    "}\n"
    "\n"
    "/* template_init: install MD4 IV into state.\n"
    " * Same 4 values as MD5 (RFC 1320 §3.3). */\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one HASH_BLOCK_BYTES (64) byte block.\n"
    " * MD4 reads message words LITTLE-ENDIAN (same as MD5).\n"
    " *\n"
    " * Public extension API; the hot-path template_finalize bypasses this\n"
    " * via an in-place M[16] pattern. */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    /* MD4 reads message words little-endian. */\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md4_compress(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process the tail, append the 0x80 padding marker\n"
    " * + 64-bit LE length-in-bits, and absorb. Mirrors gpu_md5_core.cl rev\n"
    " * 1.2's in-place M[16] pattern. The only difference vs MD5 is the\n"
    " * compression function call. */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Process complete 64-byte blocks. Build M[] LE directly from\n"
    "     * bytes (no intermediate pad[]). */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md4_compress(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Tail bytes LE. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    /* 0x80 padding marker. */\n"
    "    M[rem >> 2] |= (uint)0x80 << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        /* Length fits in this block. MD4 LE: M[14] = low 32 bits of\n"
    "         * bit count, M[15] = high bits = 0 for our inputs. */\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md4_compress(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    } else {\n"
    "        /* Need one extra padding-only block to hold the length. */\n"
    "        md4_compress(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0;\n"
    "        md4_compress(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step. MD4 hex output is 32 lowercase hex\n"
    " * chars (same as MD5 — both produce 16-byte digests with 4 LE uint32\n"
    " * words). md5_to_hex_lc from gpu_common.cl is reusable here because\n"
    " * the LE 4-word hex format is algorithm-independent.\n"
    " *\n"
    " * Mirrors gpu_md4_packed.cl rev 1 lines 96-103 byte-for-byte:\n"
    " *   - 4 state words -> 8 LE-encoded hex M[] words (md5_to_hex_lc)\n"
    " *   - M[8] = 0x80 (LE pad marker at byte position 32)\n"
    " *   - M[9..13] = 0\n"
    " *   - M[14] = 32 * 8 = 256, M[15] = 0\n"
    " *   - state reset to MD4 IV (same as MD5 IV); md4_compress. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    md5_to_hex_lc(st->h[0], st->h[1], st->h[2], st->h[3], M);\n"
    "    M[8] = 0x80u;\n"
    "    for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 32u * 8u;     /* 32 hex chars = 256 bits */\n"
    "    M[15] = 0u;\n"
    "    /* Reinitialize state to IV, then absorb the prepared M[]. */\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    md4_compress(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the final\n"
    " * digest. MD4 state words are stored LITTLE-ENDIAN (md4_compress's\n"
    " * natural form, same as MD5) so NO byte-swap is needed before probing —\n"
    " * the compact table is keyed on LE uint32 words. Mirror's MD5's\n"
    " * template_digest_compare exactly. */\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit a hit into the global hits buffer. Wraps\n"
    " * EMIT_HIT_4 (MD4 = 4 uint32 digest words). MD4 state is already LE so\n"
    " * no bswap; mirror MD5's pattern exactly. */\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "/* B3 dedup+overflow-aware variant. See gpu_md5_core.cl for protocol\n"
    " * notes. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
