/* Auto-generated from gpu_rmd160unsalted.cl -- do not edit */
static const char gpu_rmd160unsalted_str[] =
    "/* gpu_rmd160unsalted.cl — Pre-padded unsalted RIPEMD-160 with mask expansion\n"
    " *\n"
    " * Input: 4096 pre-padded 64-byte M[] blocks in passbuf (word_stride=64).\n"
    " *   Packed by gpu_try_pack_unsalted() in little-endian format:\n"
    " *   password at offset n_prepend, 0x80 padding, M[14]=bitlen (LE).\n"
    " *   RIPEMD-160 is native little-endian — no byte-swap needed.\n"
    " *\n"
    " * Dispatch: num_words × num_masks threads.\n"
    " *   word_idx = tid / num_masks, mask_idx = mask_start + (tid % num_masks)\n"
    " *\n"
    " * Hit stride: 6 (word_idx, mask_idx, h0, h1, h2, h3)\n"
    " *\n"
    " * Primitives (RMD macros, L1-L5, R1-R5, rmd160_block) provided by gpu_common.cl\n"
    " */\n"
    "\n"
    "__kernel void rmd160_unsalted_batch(\n"
    "    __global const uint *words,\n"
    "    __global const ushort *unused_lens,\n"
    "    __global const uchar *mask_desc,\n"
    "    __global const uint *unused1, __global const ushort *unused2,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    __global const OCLParams *params_buf,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ushort *hash_data_len,\n"
    "    __global uint *hits, __global volatile uint *hit_count,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, __global const ushort *overflow_lengths)\n"
    "{\n"
    "    OCLParams params = *params_buf;\n"
    "    uint tid = get_global_id(0);\n"
    "    uint word_idx = tid / params.num_masks;\n"
    "    ulong mask_idx = params.mask_start + (tid % params.num_masks);\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    /* Load pre-padded M[] block (16 uint32 = 64 bytes, LE from host) */\n"
    "    __global const uint *src = words + word_idx * 16;\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = src[i];\n"
    "\n"
    "    /* Fill mask positions into M[] — LE words */\n"
    "    uint n_pre = params.n_prepend;\n"
    "    uint n_app = params.n_append;\n"
    "\n"
    "    if (n_pre > 0 || n_app > 0) {\n"
    "        uint n_total_m = n_pre + n_app;\n"
    "\n"
    "        if (n_pre > 0) {\n"
    "            uint append_combos = 1;\n"
    "            for (uint i = 0; i < n_app; i++)\n"
    "                append_combos *= mask_desc[n_pre + i];\n"
    "            uint prepend_idx = (uint)(mask_idx / append_combos);\n"
    "            uint append_idx = (uint)(mask_idx % append_combos);\n"
    "\n"
    "            uint pidx = prepend_idx;\n"
    "            for (int i = (int)n_pre - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + (pidx % sz)];\n"
    "                pidx /= sz;\n"
    "                M[i >> 2] = (M[i >> 2] & ~(0xFFu << ((i & 3) << 3)))\n"
    "                           | ((uint)ch << ((i & 3) << 3));\n"
    "            }\n"
    "\n"
    "            if (n_app > 0) {\n"
    "                int total_len = M[14] >> 3;\n"
    "                int app_start = total_len - (int)n_app;\n"
    "                uint aidx = append_idx;\n"
    "                for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                    int pos_idx = n_pre + i;\n"
    "                    uint sz = mask_desc[pos_idx];\n"
    "                    uchar ch = mask_desc[n_total_m + pos_idx * 256 + (aidx % sz)];\n"
    "                    aidx /= sz;\n"
    "                    int pos = app_start + i;\n"
    "                    M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                                 | ((uint)ch << ((pos & 3) << 3));\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            /* Append-only (brute-force): host pre-decomposes mask_start into\n"
    "             * per-position base offsets. Kernel does fast uint32 local\n"
    "             * decomposition and adds to base with carry. */\n"
    "            int total_len = M[14] >> 3;\n"
    "            int app_start = total_len - (int)n_app;\n"
    "            uint local_idx = tid % params.num_masks;\n"
    "            uint aidx = local_idx;\n"
    "            uint carry = 0;\n"
    "            for (int i = (int)n_app - 1; i >= 0; i--) {\n"
    "                uint sz = mask_desc[i];\n"
    "                uint local_digit = aidx % sz;\n"
    "                aidx /= sz;\n"
    "                uint base_digit = (i < 8)\n"
    "                    ? (uint)((params.mask_base0 >> (i * 8)) & 0xFF)\n"
    "                    : (uint)((params.mask_base1 >> ((i - 8) * 8)) & 0xFF);\n"
    "                uint sum = base_digit + local_digit + carry;\n"
    "                carry = sum / sz;\n"
    "                uint final_digit = sum % sz;\n"
    "                uchar ch = mask_desc[n_total_m + i * 256 + final_digit];\n"
    "                int pos = app_start + i;\n"
    "                M[pos >> 2] = (M[pos >> 2] & ~(0xFFu << ((pos & 3) << 3)))\n"
    "                             | ((uint)ch << ((pos & 3) << 3));\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    /* RIPEMD-160 is native LE — M[] is already in correct byte order.\n"
    "     * Padding: 0x80 after message, bit-length at M[14] (LE) — same as MD5. */\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    rmd160_block(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* RMD160: 5 hash words, output is LE — no bswap needed */\n"
    "        if (probe_compact(state[0], state[1], state[2], state[3], compact_fp, compact_idx,\n"
    "                          params.compact_mask, params.max_probe, params.hash_data_count,\n"
    "                          hash_data_buf, hash_data_off,\n"
    "                          overflow_keys, overflow_hashes, overflow_offsets, params.overflow_count)) {\n"
    "            EMIT_HIT_5(hits, hit_count, params.max_hits, word_idx, mask_idx, iter, state)\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            /* Hex-encode 5 LE state words into M[0..9] (40 hex chars, LE packing) */\n"
    "            for (int i = 0; i < 5; i++) {\n"
    "                uint s = state[i];\n"
    "                uint b0 = s & 0xff, b1 = (s >> 8) & 0xff;\n"
    "                uint b2 = (s >> 16) & 0xff, b3 = (s >> 24) & 0xff;\n"
    "                M[i*2]   = hex_byte_lc(b0) | (hex_byte_lc(b1) << 16);\n"
    "                M[i*2+1] = hex_byte_lc(b2) | (hex_byte_lc(b3) << 16);\n"
    "            }\n"
    "            M[10] = 0x80;\n"
    "            for (int i = 11; i < 14; i++) M[i] = 0;\n"
    "            M[14] = 40 * 8; M[15] = 0;  /* 40 hex bytes = 320 bits */\n"
    "            state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "            state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "            rmd160_block(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
