/* Auto-generated from gpu_ntlmh_core.cl -- do not edit */
static const char gpu_ntlmh_core_str[] =
    "/*\n"
    " * $Revision: 1.2 $\n"
    " * $Log: gpu_ntlmh_core.cl,v $\n"
    " * Revision 1.2  2026/05/11 05:22:01  dlr\n"
    " * Backfill $Revision/$Log RCS keyword stanzas per feedback_rcs_keyword_stanzas.md. Passive 4-line comment block at top of file; no behavioral change. Hand-authored .cl file was missing required stanzas (per memory: all hand-authored .c/.h/.cl/.frag/.tmpl/.py/.sh files MUST contain $Revision/$Log keyword stanzas). Build green on .205 against the post-add files; OpenCL compile strips comments so no kernel behavior change.\n"
    " *\n"
    " */\n"
    "/* gpu_ntlmh_core.cl — NTLMH (NT password hash) algorithm extension\n"
    " * functions for the generic dispatch template (Memo B Phase B5\n"
    " * sub-batch 6, Tier B).\n"
    " *\n"
    " * NTLMH = MD4(UTF-16LE(password)). The hashcat-compatible variant uses\n"
    " * \"zero-extend\" UTF-16LE encoding: each input byte b -> two bytes b,0x00.\n"
    " * For ASCII inputs this is byte-identical to iconv(utf-8 -> UTF-16LE).\n"
    " * For non-ASCII (multi-byte UTF-8) inputs the zero-extend path computes\n"
    " * a different digest than the iconv path; mdxfind's CPU JOB_NTLMH tests\n"
    " * BOTH the iconv variant AND the zero-extend variant — the GPU template\n"
    " * path here implements ONLY the zero-extend variant (hashcat-compatible\n"
    " * by design), matching the existing slab kernel md4utf16_unsalted_batch\n"
    " * (gpu_md4unsalted.cl line 197+) which has the same semantic.\n"
    " *\n"
    " * The slab path's prior NTLMH validation note (mdxfind.c rev 1.394\n"
    " * commit comment): \"verified byte-identical GPU vs CPU on dev1 Metal\n"
    " * and fpga OpenCL across e369 (152/152), e786 primary (100/100),\n"
    " * e786 superset (expected 30-hit iconv gap on non-ASCII, hashcat-compat\n"
    " * by design)\". Same gap applies here.\n"
    " *\n"
    " * CPU reference (mdxfind.c JOB_NTLMH at line 15174):\n"
    " *\n"
    " *   if (Unicode) {\n"
    " *     MD4(cur, len, md5buf.h);            // input is already UTF-16\n"
    " *     checkhash(&md5buf, 32, 1, job);\n"
    " *   } else {\n"
    " *     // Variant 1: iconv utf-8 -> UTF-16LE -> MD4\n"
    " *     // Variant 2: zero-extend UTF-16LE -> MD4   <-- GPU implements this\n"
    " *     to_utf16le(cur, wline, len);\n"
    " *     MD4(wline, len*2, md5buf.h);\n"
    " *     checkhash(&md5buf, 32, 1, job);\n"
    " *   }\n"
    " *\n"
    " * NTLMH has NO iter loop in the CPU implementation — Maxiter is ignored.\n"
    " * For template_iterate (called only when iter < Maxiter), we provide a\n"
    " * standard MD4 hex re-feed as defensive fallback; in practice the\n"
    " * chokepoint and host pipe disable Maxiter > 1 for this algorithm.\n"
    " *\n"
    " * Block layout: per-byte LE expansion of input[i] to (input[i], 0x00).\n"
    " * For ASCII char c, MD4 word j (LE) covers UTF-16LE bytes\n"
    " * [4j..4j+3] = (input[2j], 0, input[2j+1], 0). Equivalent uint:\n"
    " *   M[j] = input[2j] | (input[2j+1] << 16)\n"
    " *\n"
    " * Length: 2 * len bytes UTF-16LE. Single MD4 block if 2*len <= 55 (so\n"
    " * len <= 27); two blocks if 2*len <= 119 (len <= 59). The chokepoint\n"
    " * limits len to a value within the rule-engine path's input bound.\n"
    " *\n"
    " * State width / byte order: MD4 carries 4 LE uint32 chaining values\n"
    " * (same as MD5; UNLIKE the SHA family).\n"
    " *\n"
    " * Cache key (R3): defines_str = \"HASH_WORDS=4,HASH_BLOCK_BYTES=64\" — same\n"
    " * as MD4 / MD5 / MD5RAW. Distinct cache entry guaranteed by source-text\n"
    " * hash difference.\n"
    " *\n"
    " * R1 mitigation: single private buffer; no addrspace-cast helpers.\n"
    " *\n"
    " * Source order at compile time:\n"
    " *   [ gpu_common_str, gpu_md5_rules_str, gpu_ntlmh_core_str, gpu_template_str ]\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "typedef struct {\n"
    "    uint h[HASH_WORDS];\n"
    "} template_state;\n"
    "\n"
    "/* MD4 compression — inlined here (renamed to md4_compress_ntlmh to avoid\n"
    " * symbol clash if gpu_md4_core_str is ever included in the same compile\n"
    " * unit). Mirrors gpu_md4_core.cl's md4_compress byte-for-byte. */\n"
    "static inline void md4_compress_ntlmh(uint *hx, uint *hy, uint *hz, uint *hw, uint *M) {\n"
    "    uint a = *hx, b = *hy, c = *hz, d = *hw;\n"
    "#define MD4_F(x,y,z) (((x)&(y)) | ((~(x))&(z)))\n"
    "#define MD4_G(x,y,z) (((x)&(y)) | ((x)&(z)) | ((y)&(z)))\n"
    "#define MD4_H(x,y,z) ((x)^(y)^(z))\n"
    "#define MD4_R1(a,b,c,d,k,s) a = rotate(a + MD4_F(b,c,d) + M[k], (uint)(s))\n"
    "#define MD4_R2(a,b,c,d,k,s) a = rotate(a + MD4_G(b,c,d) + M[k] + 0x5A827999u, (uint)(s))\n"
    "#define MD4_R3(a,b,c,d,k,s) a = rotate(a + MD4_H(b,c,d) + M[k] + 0x6ED9EBA1u, (uint)(s))\n"
    "    MD4_R1(a,b,c,d, 0, 3); MD4_R1(d,a,b,c, 1, 7); MD4_R1(c,d,a,b, 2,11); MD4_R1(b,c,d,a, 3,19);\n"
    "    MD4_R1(a,b,c,d, 4, 3); MD4_R1(d,a,b,c, 5, 7); MD4_R1(c,d,a,b, 6,11); MD4_R1(b,c,d,a, 7,19);\n"
    "    MD4_R1(a,b,c,d, 8, 3); MD4_R1(d,a,b,c, 9, 7); MD4_R1(c,d,a,b,10,11); MD4_R1(b,c,d,a,11,19);\n"
    "    MD4_R1(a,b,c,d,12, 3); MD4_R1(d,a,b,c,13, 7); MD4_R1(c,d,a,b,14,11); MD4_R1(b,c,d,a,15,19);\n"
    "    MD4_R2(a,b,c,d, 0, 3); MD4_R2(d,a,b,c, 4, 5); MD4_R2(c,d,a,b, 8, 9); MD4_R2(b,c,d,a,12,13);\n"
    "    MD4_R2(a,b,c,d, 1, 3); MD4_R2(d,a,b,c, 5, 5); MD4_R2(c,d,a,b, 9, 9); MD4_R2(b,c,d,a,13,13);\n"
    "    MD4_R2(a,b,c,d, 2, 3); MD4_R2(d,a,b,c, 6, 5); MD4_R2(c,d,a,b,10, 9); MD4_R2(b,c,d,a,14,13);\n"
    "    MD4_R2(a,b,c,d, 3, 3); MD4_R2(d,a,b,c, 7, 5); MD4_R2(c,d,a,b,11, 9); MD4_R2(b,c,d,a,15,13);\n"
    "    MD4_R3(a,b,c,d, 0, 3); MD4_R3(d,a,b,c, 8, 9); MD4_R3(c,d,a,b, 4,11); MD4_R3(b,c,d,a,12,15);\n"
    "    MD4_R3(a,b,c,d, 2, 3); MD4_R3(d,a,b,c,10, 9); MD4_R3(c,d,a,b, 6,11); MD4_R3(b,c,d,a,14,15);\n"
    "    MD4_R3(a,b,c,d, 1, 3); MD4_R3(d,a,b,c, 9, 9); MD4_R3(c,d,a,b, 5,11); MD4_R3(b,c,d,a,13,15);\n"
    "    MD4_R3(a,b,c,d, 3, 3); MD4_R3(d,a,b,c,11, 9); MD4_R3(c,d,a,b, 7,11); MD4_R3(b,c,d,a,15,15);\n"
    "#undef MD4_F\n"
    "#undef MD4_G\n"
    "#undef MD4_H\n"
    "#undef MD4_R1\n"
    "#undef MD4_R2\n"
    "#undef MD4_R3\n"
    "    *hx = a + *hx; *hy = b + *hy; *hz = c + *hz; *hw = d + *hw;\n"
    "}\n"
    "\n"
    "static inline void template_init(template_state *st) {\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: stub for interface symmetry. NTLMH finalize handles\n"
    " * its own block packing inline (UTF-16LE expansion is interleaved with\n"
    " * the M[] build). */\n"
    "static inline void template_transform(template_state *st,\n"
    "                                      const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md4_compress_ntlmh(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: NTLMH = MD4(UTF-16LE-zero-extend(input)). Build M[]\n"
    " * directly from the input bytes interleaved with zeros (the UTF-16LE\n"
    " * high-byte placeholder for ASCII chars).\n"
    " *\n"
    " * For each MD4 word j of UTF-16LE bytes:\n"
    " *   word covers UTF-16LE bytes [4j..4j+3]:\n"
    " *     UTF-16LE byte 2k   = input[k]      (low byte of UTF-16 char k)\n"
    " *     UTF-16LE byte 2k+1 = 0             (high byte = 0 for zero-extend)\n"
    " *   So byte 4j   = input[2j]\n"
    " *      byte 4j+1 = 0\n"
    " *      byte 4j+2 = input[2j+1]\n"
    " *      byte 4j+3 = 0\n"
    " * MD4 reads M LE: M[j] = byte[4j] | byte[4j+1]<<8 | byte[4j+2]<<16 | byte[4j+3]<<24\n"
    " *               = input[2j] | (input[2j+1] << 16)\n"
    " *\n"
    " * The 0x80 padding marker lands at UTF-16-byte position 2*len; if 2*len\n"
    " * is even (always true since 2*len is always even), the marker is at\n"
    " * the LOW byte of M[len/2] (when len is even) or M[(len/2)] high byte (?).\n"
    " * Actually 2*len is the count of UTF-16 bytes consumed. The pad goes at\n"
    " * byte index 2*len in the UTF-16LE stream. byte_idx = 2*len:\n"
    " *   M_word = byte_idx >> 2 = len >> 1\n"
    " *   byte_in_word = byte_idx & 3 = (2*len) & 3 = 2 * (len & 1)\n"
    " *   ⇒ byte_in_word = 0 if len even, 2 if len odd\n"
    " *\n"
    " * Bit count in UTF-16LE = 2 * len * 8 = 16 * len.\n"
    " */\n"
    "static inline void template_finalize(template_state *st,\n"
    "                                     const uchar *data, int len)\n"
    "{\n"
    "    /* Process complete UTF-16LE blocks. Each MD4 block (64 bytes) holds\n"
    "     * 32 UTF-16LE chars = 32 input bytes. */\n"
    "    uint M[16];\n"
    "    int input_pos = 0;\n"
    "\n"
    "    while (len - input_pos >= 32) {\n"
    "        /* 32 input bytes -> 64 UTF-16LE bytes -> 16 MD4 M[] words. */\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int k = input_pos + j * 2;\n"
    "            M[j] = (uint)data[k] | ((uint)data[k + 1] << 16);\n"
    "        }\n"
    "        md4_compress_ntlmh(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        input_pos += 32;\n"
    "    }\n"
    "\n"
    "    /* Tail: remaining input bytes (rem in [0..31]) -> 2*rem UTF-16LE bytes. */\n"
    "    int rem = len - input_pos;  /* 0..31 input bytes */\n"
    "    int rem_utf16 = rem * 2;     /* 0..62 UTF-16LE bytes */\n"
    "\n"
    "    /* Zero scratch. */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "\n"
    "    /* Pack input bytes into M[] LE positions, interleaved with zeros. */\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        int byte_idx = i * 2;            /* low byte of UTF-16 char */\n"
    "        int wi = byte_idx >> 2;\n"
    "        int bi = byte_idx & 3;\n"
    "        M[wi] |= ((uint)data[input_pos + i]) << (bi * 8);\n"
    "        /* High byte (byte_idx + 1) is zero; no write needed. */\n"
    "    }\n"
    "\n"
    "    /* 0x80 pad marker at UTF-16 byte position rem_utf16 = 2*rem. */\n"
    "    {\n"
    "        int wi = rem_utf16 >> 2;\n"
    "        int bi = rem_utf16 & 3;\n"
    "        M[wi] |= ((uint)0x80u) << (bi * 8);\n"
    "    }\n"
    "\n"
    "    /* MD4 LE bit-count encoding: M[14] = low 32 bits, M[15] = high 32 bits.\n"
    "     * Total UTF-16LE bytes = 2*len ⇒ bit count = 16 * len. */\n"
    "    if (rem_utf16 < 56) {\n"
    "        M[14] = (uint)((uint)len * 16u);\n"
    "        M[15] = 0;\n"
    "        md4_compress_ntlmh(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    } else {\n"
    "        md4_compress_ntlmh(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0;\n"
    "        M[14] = (uint)((uint)len * 16u);\n"
    "        M[15] = 0;\n"
    "        md4_compress_ntlmh(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: defensive fallback. NTLMH has no iter loop in CPU.\n"
    " * If the host ever passes Maxiter > 1 for NTLMH (it shouldn't), this\n"
    " * computes MD4(hex_lc(prev_hash)) — same shape as MD4 template_iterate.\n"
    " * Production path (Maxiter == 1) never calls this. */\n"
    "static inline void template_iterate(template_state *st)\n"
    "{\n"
    "    uint M[16];\n"
    "    md5_to_hex_lc(st->h[0], st->h[1], st->h[2], st->h[3], M);\n"
    "    M[8] = 0x80u;\n"
    "    for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 32u * 8u;\n"
    "    M[15] = 0u;\n"
    "    st->h[0] = 0x67452301u;\n"
    "    st->h[1] = 0xEFCDAB89u;\n"
    "    st->h[2] = 0x98BADCFEu;\n"
    "    st->h[3] = 0x10325476u;\n"
    "    md4_compress_ntlmh(&st->h[0], &st->h[1], &st->h[2], &st->h[3], M);\n"
    "}\n"
    "\n"
    "static inline int template_digest_compare(\n"
    "    const template_state *st,\n"
    "    __global const uint *compact_fp, __global const uint *compact_idx,\n"
    "    ulong compact_mask, uint max_probe, uint hash_data_count,\n"
    "    __global const uchar *hash_data_buf, __global const ulong *hash_data_off,\n"
    "    __global const ulong *overflow_keys, __global const uchar *overflow_hashes,\n"
    "    __global const uint *overflow_offsets, uint overflow_count,\n"
    "    uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st->h[0], st->h[1], st->h[2], st->h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    EMIT_HIT_4((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3])\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "               (widx), (sidx), (iter), \\\n"
    "               (st)->h[0], (st)->h[1], (st)->h[2], (st)->h[3], \\\n"
    "               (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "               (ovr_set), (ovr_gid), (lane_gid))\n"
;
