/* Auto-generated from metal_md5_packed.metal -- do not edit */
static const char metal_md5_packed_str[] =
    "/* metal_md5_packed.metal — Packed password MD5 kernel for rule-generated candidates\n"
    " *\n"
    " * Metal port of gpu_md5_packed.cl.\n"
    " *\n"
    " * Input: packed buffer of [uint8 len][password bytes] entries, tightly packed.\n"
    " *        word_offset[] array of uint32 byte offsets, one per word.\n"
    " *\n"
    " * One thread per word. Each thread reads its offset, unpacks password,\n"
    " * computes MD5, probes compact table. Supports iteration (md5(md5(x))).\n"
    " *\n"
    " * params.num_words = total passwords in buffer\n"
    " * params.max_iter = iteration count (1 = single hash, >1 = iterated)\n"
    " * params.reserved32[0] = word_start (chunk offset)\n"
    " *\n"
    " * Primitives (md5_block, md5_to_hex_lc, MetalParams, HIT_STRIDE) are\n"
    " * provided by metal_common.metal (concatenated at build time).\n"
    " * Emits a 4-word hash hit (stride 19: widx, sidx, iter, hx..hw, pad).\n"
    " */\n"
    "\n"
    "static void md5_compress_packed(thread uint4 &state, thread uint *M) {\n"
    "    uint a = state.x, b = state.y, c = state.z, d = state.w;\n"
    "    a += ((b&c)|(~b&d)) + M[ 0] + 0xd76aa478u; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[ 1] + 0xe8c7b756u; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[ 2] + 0x242070dbu; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[ 3] + 0xc1bdceeeu; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((b&c)|(~b&d)) + M[ 4] + 0xf57c0fafu; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[ 5] + 0x4787c62au; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[ 6] + 0xa8304613u; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[ 7] + 0xfd469501u; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((b&c)|(~b&d)) + M[ 8] + 0x698098d8u; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[ 9] + 0x8b44f7afu; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[10] + 0xffff5bb1u; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[11] + 0x895cd7beu; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((b&c)|(~b&d)) + M[12] + 0x6b901122u; a = b + ((a<< 7)|(a>>25));\n"
    "    d += ((a&b)|(~a&c)) + M[13] + 0xfd987193u; d = a + ((d<<12)|(d>>20));\n"
    "    c += ((d&a)|(~d&b)) + M[14] + 0xa679438eu; c = d + ((c<<17)|(c>>15));\n"
    "    b += ((c&d)|(~c&a)) + M[15] + 0x49b40821u; b = c + ((b<<22)|(b>>10));\n"
    "    a += ((d&b)|(~d&c)) + M[ 1] + 0xf61e2562u; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[ 6] + 0xc040b340u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[11] + 0x265e5a51u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[ 0] + 0xe9b6c7aau; b = c + ((b<<20)|(b>>12));\n"
    "    a += ((d&b)|(~d&c)) + M[ 5] + 0xd62f105du; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[10] + 0x02441453u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[15] + 0xd8a1e681u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[ 4] + 0xe7d3fbc8u; b = c + ((b<<20)|(b>>12));\n"
    "    a += ((d&b)|(~d&c)) + M[ 9] + 0x21e1cde6u; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[14] + 0xc33707d6u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[ 3] + 0xf4d50d87u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[ 8] + 0x455a14edu; b = c + ((b<<20)|(b>>12));\n"
    "    a += ((d&b)|(~d&c)) + M[13] + 0xa9e3e905u; a = b + ((a<< 5)|(a>>27));\n"
    "    d += ((c&a)|(~c&b)) + M[ 2] + 0xfcefa3f8u; d = a + ((d<< 9)|(d>>23));\n"
    "    c += ((b&d)|(~b&a)) + M[ 7] + 0x676f02d9u; c = d + ((c<<14)|(c>>18));\n"
    "    b += ((a&c)|(~a&d)) + M[12] + 0x8d2a4c8au; b = c + ((b<<20)|(b>>12));\n"
    "    a += (b^c^d) + M[ 5] + 0xfffa3942u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[ 8] + 0x8771f681u; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[11] + 0x6d9d6122u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[14] + 0xfde5380cu; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (b^c^d) + M[ 1] + 0xa4beea44u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[ 4] + 0x4bdecfa9u; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[ 7] + 0xf6bb4b60u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[10] + 0xbebfbc70u; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (b^c^d) + M[13] + 0x289b7ec6u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[ 0] + 0xeaa127fau; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[ 3] + 0xd4ef3085u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[ 6] + 0x04881d05u; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (b^c^d) + M[ 9] + 0xd9d4d039u; a = b + ((a<< 4)|(a>>28));\n"
    "    d += (a^b^c) + M[12] + 0xe6db99e5u; d = a + ((d<<11)|(d>>21));\n"
    "    c += (d^a^b) + M[15] + 0x1fa27cf8u; c = d + ((c<<16)|(c>>16));\n"
    "    b += (c^d^a) + M[ 2] + 0xc4ac5665u; b = c + ((b<<23)|(b>> 9));\n"
    "    a += (c^(~d|b)) + M[ 0] + 0xf4292244u; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[ 7] + 0x432aff97u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[14] + 0xab9423a7u; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[ 5] + 0xfc93a039u; b = c + ((b<<21)|(b>>11));\n"
    "    a += (c^(~d|b)) + M[12] + 0x655b59c3u; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[ 3] + 0x8f0ccc92u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[10] + 0xffeff47du; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[ 1] + 0x85845dd1u; b = c + ((b<<21)|(b>>11));\n"
    "    a += (c^(~d|b)) + M[ 8] + 0x6fa87e4fu; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[15] + 0xfe2ce6e0u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[ 6] + 0xa3014314u; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[13] + 0x4e0811a1u; b = c + ((b<<21)|(b>>11));\n"
    "    a += (c^(~d|b)) + M[ 4] + 0xf7537e82u; a = b + ((a<< 6)|(a>>26));\n"
    "    d += (b^(~c|a)) + M[11] + 0xbd3af235u; d = a + ((d<<10)|(d>>22));\n"
    "    c += (a^(~b|d)) + M[ 2] + 0x2ad7d2bbu; c = d + ((c<<15)|(c>>17));\n"
    "    b += (d^(~a|c)) + M[ 9] + 0xeb86d391u; b = c + ((b<<21)|(b>>11));\n"
    "    state += uint4(a, b, c, d);\n"
    "}\n"
    "\n"
    "kernel void md5_packed_batch(\n"
    "    device const uint8_t    *packed_buf  [[buffer(0)]],\n"
    "    device const uint       *word_offset [[buffer(1)]],\n"
    "    device const uint8_t    *unused_mask [[buffer(2)]],\n"
    "    device const uint       *unused1     [[buffer(3)]],\n"
    "    device const ushort     *unused2     [[buffer(4)]],\n"
    "    device const uint8_t    *unused3     [[buffer(5)]],  /* placeholder */\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys    [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes  [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_start = params.reserved32[0];\n"
    "    uint word_idx = word_start + tid;\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint pos = word_offset[word_idx];\n"
    "    uint len = packed_buf[pos++];\n"
    "\n"
    "    /* Build M[16] in little-endian */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint i = 0;\n"
    "    for (; i + 3 < len; i += 4) {\n"
    "        M[i >> 2] = (uint)packed_buf[pos + i]\n"
    "                  | ((uint)packed_buf[pos + i + 1] << 8)\n"
    "                  | ((uint)packed_buf[pos + i + 2] << 16)\n"
    "                  | ((uint)packed_buf[pos + i + 3] << 24);\n"
    "    }\n"
    "    uint tail = 0;\n"
    "    uint shift = 0;\n"
    "    for (; i < len; i++) {\n"
    "        tail |= (uint)packed_buf[pos + i] << shift;\n"
    "        shift += 8;\n"
    "    }\n"
    "    tail |= (uint)0x80 << shift;\n"
    "    M[i >> 2] = tail;\n"
    "    M[14] = len * 8;\n"
    "\n"
    "    uint4 state = uint4(0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u);\n"
    "    md5_compress_packed(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint4 h = state;\n"
    "        ulong key = (ulong(h.y) << 32) | h.x;\n"
    "        uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "        ulong ppos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "        bool found = false;\n"
    "        for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "            uint cfp = compact_fp[ppos]; if (cfp == 0) break;\n"
    "            if (cfp == fp) {\n"
    "                uint idx = compact_idx[ppos];\n"
    "                if (idx < params.hash_data_count) {\n"
    "                    ulong off = hash_data_off[idx];\n"
    "                    device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                    if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "            }\n"
    "            ppos = (ppos + 1) & params.compact_mask;\n"
    "        }\n"
    "        if (!found && params.overflow_count > 0) {\n"
    "            int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "            while (lo <= hi2 && !found) {\n"
    "                int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "                if (key < mkey) hi2 = mid - 1;\n"
    "                else if (key > mkey) lo = mid + 1;\n"
    "                else {\n"
    "                    for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    break;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (found) {\n"
    "            uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * HIT_STRIDE;\n"
    "                hits[base] = word_idx; hits[base+1] = 0; hits[base+2] = iter;\n"
    "                hits[base+3] = h.x; hits[base+4] = h.y;\n"
    "                hits[base+5] = h.z; hits[base+6] = h.w;\n"
    "                for (uint _z = 7; _z < HIT_STRIDE; _z++) hits[base+_z] = 0;\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            md5_to_hex_lc(state.x, state.y, state.z, state.w, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;\n"
    "            state = uint4(0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u);\n"
    "            md5_compress_packed(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
