/* GENERATED by gpu/gen_u32_walker.py -- DO NOT EDIT BY HAND.
 *
 * Backend: Metal
 * Sources: gpu_u32_tables.cl + gpu_u32_walker.inc
 *
 * Metal requires an explicit address space on every pointer, so
 * the two buffer spaces DIFFER: U32_BUF is `device` because
 * Apple Metal does not spill and 24 KB of `thread` arrays is
 * rejected at PSO create (task #250 hit exactly this with the
 * byte walker's buf), while U32_SCRATCH stays `thread`
 * because its callers pass a plain local array and Metal
 * type-checks address spaces.
 *
 * Edit gpu_u32_walker.inc and re-run the generator.  An edit made
 * here is silently reverted by the next run, which is the whole
 * point: the two backends cannot drift.
 */

#define CL_CONSTANT constant
#define U32_GLOBAL  device
#define U32_BUF     device
#define U32_SCRATCH thread
#define U32_SI      static inline

/* GENERATED by gpu/gen_u32_tables.py from ../combining.h and ../latin_case.h.
 * DO NOT EDIT BY HAND.  Regenerate after any change to either source header,
 * then regenerate gpu_u32_tables_str.h with cl2str.py and delete BOTH
 * mdxfind.o and gpu/gpu_opencl.o (the _str.h is included by gpu_opencl.c, not
 * by mdxfind.c, and the Makefile dependency does not notice).
 *
 * Flat arrays, not structs-of-arrays: a struct with a uint[3] member lays out
 * identically in OpenCL C and Metal only by accident, and the expansion table
 * is read by index arithmetic anyway.  Flattening removes the question.
 *
 * Address space is spelled CL_CONSTANT so one generated file serves OpenCL
 * (__constant) and Metal (constant).  The fallback below makes the file
 * compile STANDALONE as well as inlined -- gen_u32_walker.py defines the macro
 * before including this, so the guard makes the two uses agree instead of
 * making one of them depend on the other.  An earlier revision only PROMISED
 * this in the comment and did not emit it, and the JIT then failed with
 * `CL_CONSTANT uint u32_marks[580] = {` echoed back as a syntax error.
 */

#ifndef CL_CONSTANT
#  ifdef __METAL_VERSION__
#    define CL_CONSTANT constant
#  else
#    define CL_CONSTANT __constant
#  endif
#endif

/* Constant-memory footprint of THIS file: 4648 bytes (4.5 KB).
 *
 * The 26,048-byte case tables are deliberately absent -- they are a
 * __global kernel argument.  MEASURED on a GTX 1080: with them in
 * __constant the rules program was 78,532 bytes of constant data against
 * NVIDIA's 65,536 limit and ptxas refused the build outright
 * (`File uses too much global constant data (0x132c4 bytes, 0x10000 max)`),
 * because gpu_common.cl's algorithm tables already occupy ~47.8 KB of it.
 * What remains here is the mark ranges, the case range index and the
 * length-changing expansion table. */

#define U32_MARK_N   290
#define U32_MARK_LO  0x0300u
#define U32_MARK_HI  0xE01EFu

/* cp_marks[], flattened to (lo, hi) pairs.  Sorted, so lookup is a binary
 * search; the bounds test rejects every ASCII character in one compare. */
CL_CONSTANT uint u32_marks[580] = {
    0x00300u, 0x0036Fu, 0x00483u, 0x00489u, 0x00591u, 0x005BDu, 0x005BFu, 0x005BFu,
    0x005C1u, 0x005C2u, 0x005C4u, 0x005C5u, 0x005C7u, 0x005C7u, 0x00610u, 0x0061Au,
    0x0064Bu, 0x0065Fu, 0x00670u, 0x00670u, 0x006D6u, 0x006DCu, 0x006DFu, 0x006E4u,
    0x006E7u, 0x006E8u, 0x006EAu, 0x006EDu, 0x00711u, 0x00711u, 0x00730u, 0x0074Au,
    0x007A6u, 0x007B0u, 0x007EBu, 0x007F3u, 0x007FDu, 0x007FDu, 0x00816u, 0x00819u,
    0x0081Bu, 0x00823u, 0x00825u, 0x00827u, 0x00829u, 0x0082Du, 0x00859u, 0x0085Bu,
    0x008D3u, 0x008E1u, 0x008E3u, 0x00903u, 0x0093Au, 0x0093Cu, 0x0093Eu, 0x0094Fu,
    0x00951u, 0x00957u, 0x00962u, 0x00963u, 0x00981u, 0x00983u, 0x009BCu, 0x009BCu,
    0x009BEu, 0x009C4u, 0x009C7u, 0x009C8u, 0x009CBu, 0x009CDu, 0x009D7u, 0x009D7u,
    0x009E2u, 0x009E3u, 0x009FEu, 0x009FEu, 0x00A01u, 0x00A03u, 0x00A3Cu, 0x00A3Cu,
    0x00A3Eu, 0x00A42u, 0x00A47u, 0x00A48u, 0x00A4Bu, 0x00A4Du, 0x00A51u, 0x00A51u,
    0x00A70u, 0x00A71u, 0x00A75u, 0x00A75u, 0x00A81u, 0x00A83u, 0x00ABCu, 0x00ABCu,
    0x00ABEu, 0x00AC5u, 0x00AC7u, 0x00AC9u, 0x00ACBu, 0x00ACDu, 0x00AE2u, 0x00AE3u,
    0x00AFAu, 0x00AFFu, 0x00B01u, 0x00B03u, 0x00B3Cu, 0x00B3Cu, 0x00B3Eu, 0x00B44u,
    0x00B47u, 0x00B48u, 0x00B4Bu, 0x00B4Du, 0x00B55u, 0x00B57u, 0x00B62u, 0x00B63u,
    0x00B82u, 0x00B82u, 0x00BBEu, 0x00BC2u, 0x00BC6u, 0x00BC8u, 0x00BCAu, 0x00BCDu,
    0x00BD7u, 0x00BD7u, 0x00C00u, 0x00C04u, 0x00C3Eu, 0x00C44u, 0x00C46u, 0x00C48u,
    0x00C4Au, 0x00C4Du, 0x00C55u, 0x00C56u, 0x00C62u, 0x00C63u, 0x00C81u, 0x00C83u,
    0x00CBCu, 0x00CBCu, 0x00CBEu, 0x00CC4u, 0x00CC6u, 0x00CC8u, 0x00CCAu, 0x00CCDu,
    0x00CD5u, 0x00CD6u, 0x00CE2u, 0x00CE3u, 0x00D00u, 0x00D03u, 0x00D3Bu, 0x00D3Cu,
    0x00D3Eu, 0x00D44u, 0x00D46u, 0x00D48u, 0x00D4Au, 0x00D4Du, 0x00D57u, 0x00D57u,
    0x00D62u, 0x00D63u, 0x00D81u, 0x00D83u, 0x00DCAu, 0x00DCAu, 0x00DCFu, 0x00DD4u,
    0x00DD6u, 0x00DD6u, 0x00DD8u, 0x00DDFu, 0x00DF2u, 0x00DF3u, 0x00E31u, 0x00E31u,
    0x00E34u, 0x00E3Au, 0x00E47u, 0x00E4Eu, 0x00EB1u, 0x00EB1u, 0x00EB4u, 0x00EBCu,
    0x00EC8u, 0x00ECDu, 0x00F18u, 0x00F19u, 0x00F35u, 0x00F35u, 0x00F37u, 0x00F37u,
    0x00F39u, 0x00F39u, 0x00F3Eu, 0x00F3Fu, 0x00F71u, 0x00F84u, 0x00F86u, 0x00F87u,
    0x00F8Du, 0x00F97u, 0x00F99u, 0x00FBCu, 0x00FC6u, 0x00FC6u, 0x0102Bu, 0x0103Eu,
    0x01056u, 0x01059u, 0x0105Eu, 0x01060u, 0x01062u, 0x01064u, 0x01067u, 0x0106Du,
    0x01071u, 0x01074u, 0x01082u, 0x0108Du, 0x0108Fu, 0x0108Fu, 0x0109Au, 0x0109Du,
    0x0135Du, 0x0135Fu, 0x01712u, 0x01714u, 0x01732u, 0x01734u, 0x01752u, 0x01753u,
    0x01772u, 0x01773u, 0x017B4u, 0x017D3u, 0x017DDu, 0x017DDu, 0x0180Bu, 0x0180Du,
    0x01885u, 0x01886u, 0x018A9u, 0x018A9u, 0x01920u, 0x0192Bu, 0x01930u, 0x0193Bu,
    0x01A17u, 0x01A1Bu, 0x01A55u, 0x01A5Eu, 0x01A60u, 0x01A7Cu, 0x01A7Fu, 0x01A7Fu,
    0x01AB0u, 0x01AC0u, 0x01B00u, 0x01B04u, 0x01B34u, 0x01B44u, 0x01B6Bu, 0x01B73u,
    0x01B80u, 0x01B82u, 0x01BA1u, 0x01BADu, 0x01BE6u, 0x01BF3u, 0x01C24u, 0x01C37u,
    0x01CD0u, 0x01CD2u, 0x01CD4u, 0x01CE8u, 0x01CEDu, 0x01CEDu, 0x01CF4u, 0x01CF4u,
    0x01CF7u, 0x01CF9u, 0x01DC0u, 0x01DF9u, 0x01DFBu, 0x01DFFu, 0x020D0u, 0x020F0u,
    0x02CEFu, 0x02CF1u, 0x02D7Fu, 0x02D7Fu, 0x02DE0u, 0x02DFFu, 0x0302Au, 0x0302Fu,
    0x03099u, 0x0309Au, 0x0A66Fu, 0x0A672u, 0x0A674u, 0x0A67Du, 0x0A69Eu, 0x0A69Fu,
    0x0A6F0u, 0x0A6F1u, 0x0A802u, 0x0A802u, 0x0A806u, 0x0A806u, 0x0A80Bu, 0x0A80Bu,
    0x0A823u, 0x0A827u, 0x0A82Cu, 0x0A82Cu, 0x0A880u, 0x0A881u, 0x0A8B4u, 0x0A8C5u,
    0x0A8E0u, 0x0A8F1u, 0x0A8FFu, 0x0A8FFu, 0x0A926u, 0x0A92Du, 0x0A947u, 0x0A953u,
    0x0A980u, 0x0A983u, 0x0A9B3u, 0x0A9C0u, 0x0A9E5u, 0x0A9E5u, 0x0AA29u, 0x0AA36u,
    0x0AA43u, 0x0AA43u, 0x0AA4Cu, 0x0AA4Du, 0x0AA7Bu, 0x0AA7Du, 0x0AAB0u, 0x0AAB0u,
    0x0AAB2u, 0x0AAB4u, 0x0AAB7u, 0x0AAB8u, 0x0AABEu, 0x0AABFu, 0x0AAC1u, 0x0AAC1u,
    0x0AAEBu, 0x0AAEFu, 0x0AAF5u, 0x0AAF6u, 0x0ABE3u, 0x0ABEAu, 0x0ABECu, 0x0ABEDu,
    0x0FB1Eu, 0x0FB1Eu, 0x0FE00u, 0x0FE0Fu, 0x0FE20u, 0x0FE2Fu, 0x101FDu, 0x101FDu,
    0x102E0u, 0x102E0u, 0x10376u, 0x1037Au, 0x10A01u, 0x10A03u, 0x10A05u, 0x10A06u,
    0x10A0Cu, 0x10A0Fu, 0x10A38u, 0x10A3Au, 0x10A3Fu, 0x10A3Fu, 0x10AE5u, 0x10AE6u,
    0x10D24u, 0x10D27u, 0x10EABu, 0x10EACu, 0x10F46u, 0x10F50u, 0x11000u, 0x11002u,
    0x11038u, 0x11046u, 0x1107Fu, 0x11082u, 0x110B0u, 0x110BAu, 0x11100u, 0x11102u,
    0x11127u, 0x11134u, 0x11145u, 0x11146u, 0x11173u, 0x11173u, 0x11180u, 0x11182u,
    0x111B3u, 0x111C0u, 0x111C9u, 0x111CCu, 0x111CEu, 0x111CFu, 0x1122Cu, 0x11237u,
    0x1123Eu, 0x1123Eu, 0x112DFu, 0x112EAu, 0x11300u, 0x11303u, 0x1133Bu, 0x1133Cu,
    0x1133Eu, 0x11344u, 0x11347u, 0x11348u, 0x1134Bu, 0x1134Du, 0x11357u, 0x11357u,
    0x11362u, 0x11363u, 0x11366u, 0x1136Cu, 0x11370u, 0x11374u, 0x11435u, 0x11446u,
    0x1145Eu, 0x1145Eu, 0x114B0u, 0x114C3u, 0x115AFu, 0x115B5u, 0x115B8u, 0x115C0u,
    0x115DCu, 0x115DDu, 0x11630u, 0x11640u, 0x116ABu, 0x116B7u, 0x1171Du, 0x1172Bu,
    0x1182Cu, 0x1183Au, 0x11930u, 0x11935u, 0x11937u, 0x11938u, 0x1193Bu, 0x1193Eu,
    0x11940u, 0x11940u, 0x11942u, 0x11943u, 0x119D1u, 0x119D7u, 0x119DAu, 0x119E0u,
    0x119E4u, 0x119E4u, 0x11A01u, 0x11A0Au, 0x11A33u, 0x11A39u, 0x11A3Bu, 0x11A3Eu,
    0x11A47u, 0x11A47u, 0x11A51u, 0x11A5Bu, 0x11A8Au, 0x11A99u, 0x11C2Fu, 0x11C36u,
    0x11C38u, 0x11C3Fu, 0x11C92u, 0x11CA7u, 0x11CA9u, 0x11CB6u, 0x11D31u, 0x11D36u,
    0x11D3Au, 0x11D3Au, 0x11D3Cu, 0x11D3Du, 0x11D3Fu, 0x11D45u, 0x11D47u, 0x11D47u,
    0x11D8Au, 0x11D8Eu, 0x11D90u, 0x11D91u, 0x11D93u, 0x11D97u, 0x11EF3u, 0x11EF6u,
    0x16AF0u, 0x16AF4u, 0x16B30u, 0x16B36u, 0x16F4Fu, 0x16F4Fu, 0x16F51u, 0x16F87u,
    0x16F8Fu, 0x16F92u, 0x16FE4u, 0x16FE4u, 0x16FF0u, 0x16FF1u, 0x1BC9Du, 0x1BC9Eu,
    0x1D165u, 0x1D169u, 0x1D16Du, 0x1D172u, 0x1D17Bu, 0x1D182u, 0x1D185u, 0x1D18Bu,
    0x1D1AAu, 0x1D1ADu, 0x1D242u, 0x1D244u, 0x1DA00u, 0x1DA36u, 0x1DA3Bu, 0x1DA6Cu,
    0x1DA75u, 0x1DA75u, 0x1DA84u, 0x1DA84u, 0x1DA9Bu, 0x1DA9Fu, 0x1DAA1u, 0x1DAAFu,
    0x1E000u, 0x1E006u, 0x1E008u, 0x1E018u, 0x1E01Bu, 0x1E021u, 0x1E023u, 0x1E024u,
    0x1E026u, 0x1E02Au, 0x1E130u, 0x1E136u, 0x1E2ECu, 0x1E2EFu, 0x1E8D0u, 0x1E8D6u,
    0x1E944u, 0x1E94Au, 0xE0100u, 0xE01EFu,
};

#define U32_CASE_NRANGES 24
#define U32_CASE_N       3256

/* cp_case_ranges[], flattened to (lo, hi, off) triples. */
CL_CONSTANT uint u32_case_ranges[72] = {
    0x000A0u, 0x0017Fu, 0x00000u, 0x00180u, 0x002AFu, 0x000E0u,
    0x00370u, 0x003FFu, 0x00210u, 0x00400u, 0x0052Fu, 0x002A0u,
    0x00530u, 0x0058Fu, 0x003D0u, 0x010A0u, 0x010FFu, 0x00430u,
    0x013A0u, 0x013FDu, 0x00490u, 0x01C80u, 0x01CBFu, 0x004EEu,
    0x01E00u, 0x01EFFu, 0x0052Eu, 0x01F00u, 0x01FFFu, 0x0062Eu,
    0x02126u, 0x02184u, 0x0072Eu, 0x024B6u, 0x024E9u, 0x0078Du,
    0x02C00u, 0x02D2Fu, 0x007C1u, 0x0A640u, 0x0A69Fu, 0x008F1u,
    0x0A722u, 0x0A7F6u, 0x00951u, 0x0AB53u, 0x0ABBFu, 0x00A26u,
    0x0FB00u, 0x0FB17u, 0x00A93u, 0x0FF21u, 0x0FF5Au, 0x00AABu,
    0x10400u, 0x1044Fu, 0x00AE5u, 0x104B0u, 0x104FBu, 0x00B35u,
    0x10C80u, 0x10CF2u, 0x00B81u, 0x118A0u, 0x118DFu, 0x00BF4u,
    0x16E40u, 0x16E7Fu, 0x00C34u, 0x1E900u, 0x1E943u, 0x00C74u,
};

/* cp_case_up[] / cp_case_lo[] are NOT emitted here.
 *
 * 26,048 bytes of __constant put the rules program 13 KB past NVIDIA's
 * 65,536-byte constant bank -- MEASURED on a GTX 1080:
 *   ptxas error : File uses too much global constant data
 *                 (0x132c4 bytes, 0x10000 max)
 * so they travel as a __global kernel argument instead, CONCATENATED into
 * one buffer: up at [0 .. U32_CASE_N-1], lo at [U32_CASE_N .. 2N-1].
 * gen_u32_case_host.h below is the HOST's copy, which is what gets
 * uploaded; the walker reads it through the U32_CT_UP / U32_CT_LO macros.
 * See the long comment above u32_case_find in gpu_u32_walker.inc. */

#define U32_EXPAND_N   102
#define U32_EXPAND_MAX 3
#define U32_EXPAND_LO  0x00DFu
#define U32_EXPAND_HI  0xFB17u

/* cp_expand[]: the length-CHANGING uppercase mappings, eszett -> SS and
 * friends.  Flattened to 5 words per entry: cp, n, out[0..2].
 * Only the whole-string verbs (u, c, C) consult this; a position-indexed
 * verb keeps the 1:1 map, because growing a character underneath an index
 * would move every position the rest of the rule refers to
 * (ruleproc32.c, the comment above cp_upper_full). */
CL_CONSTANT uint u32_expand[510] = {
    0x000DFu, 0x00002u, 0x00053u, 0x00053u, 0x00000u,
    0x00149u, 0x00002u, 0x002BCu, 0x0004Eu, 0x00000u,
    0x001F0u, 0x00002u, 0x0004Au, 0x0030Cu, 0x00000u,
    0x00390u, 0x00003u, 0x00399u, 0x00308u, 0x00301u,
    0x003B0u, 0x00003u, 0x003A5u, 0x00308u, 0x00301u,
    0x00587u, 0x00002u, 0x00535u, 0x00552u, 0x00000u,
    0x01E96u, 0x00002u, 0x00048u, 0x00331u, 0x00000u,
    0x01E97u, 0x00002u, 0x00054u, 0x00308u, 0x00000u,
    0x01E98u, 0x00002u, 0x00057u, 0x0030Au, 0x00000u,
    0x01E99u, 0x00002u, 0x00059u, 0x0030Au, 0x00000u,
    0x01E9Au, 0x00002u, 0x00041u, 0x002BEu, 0x00000u,
    0x01F50u, 0x00002u, 0x003A5u, 0x00313u, 0x00000u,
    0x01F52u, 0x00003u, 0x003A5u, 0x00313u, 0x00300u,
    0x01F54u, 0x00003u, 0x003A5u, 0x00313u, 0x00301u,
    0x01F56u, 0x00003u, 0x003A5u, 0x00313u, 0x00342u,
    0x01F80u, 0x00002u, 0x01F08u, 0x00399u, 0x00000u,
    0x01F81u, 0x00002u, 0x01F09u, 0x00399u, 0x00000u,
    0x01F82u, 0x00002u, 0x01F0Au, 0x00399u, 0x00000u,
    0x01F83u, 0x00002u, 0x01F0Bu, 0x00399u, 0x00000u,
    0x01F84u, 0x00002u, 0x01F0Cu, 0x00399u, 0x00000u,
    0x01F85u, 0x00002u, 0x01F0Du, 0x00399u, 0x00000u,
    0x01F86u, 0x00002u, 0x01F0Eu, 0x00399u, 0x00000u,
    0x01F87u, 0x00002u, 0x01F0Fu, 0x00399u, 0x00000u,
    0x01F88u, 0x00002u, 0x01F08u, 0x00399u, 0x00000u,
    0x01F89u, 0x00002u, 0x01F09u, 0x00399u, 0x00000u,
    0x01F8Au, 0x00002u, 0x01F0Au, 0x00399u, 0x00000u,
    0x01F8Bu, 0x00002u, 0x01F0Bu, 0x00399u, 0x00000u,
    0x01F8Cu, 0x00002u, 0x01F0Cu, 0x00399u, 0x00000u,
    0x01F8Du, 0x00002u, 0x01F0Du, 0x00399u, 0x00000u,
    0x01F8Eu, 0x00002u, 0x01F0Eu, 0x00399u, 0x00000u,
    0x01F8Fu, 0x00002u, 0x01F0Fu, 0x00399u, 0x00000u,
    0x01F90u, 0x00002u, 0x01F28u, 0x00399u, 0x00000u,
    0x01F91u, 0x00002u, 0x01F29u, 0x00399u, 0x00000u,
    0x01F92u, 0x00002u, 0x01F2Au, 0x00399u, 0x00000u,
    0x01F93u, 0x00002u, 0x01F2Bu, 0x00399u, 0x00000u,
    0x01F94u, 0x00002u, 0x01F2Cu, 0x00399u, 0x00000u,
    0x01F95u, 0x00002u, 0x01F2Du, 0x00399u, 0x00000u,
    0x01F96u, 0x00002u, 0x01F2Eu, 0x00399u, 0x00000u,
    0x01F97u, 0x00002u, 0x01F2Fu, 0x00399u, 0x00000u,
    0x01F98u, 0x00002u, 0x01F28u, 0x00399u, 0x00000u,
    0x01F99u, 0x00002u, 0x01F29u, 0x00399u, 0x00000u,
    0x01F9Au, 0x00002u, 0x01F2Au, 0x00399u, 0x00000u,
    0x01F9Bu, 0x00002u, 0x01F2Bu, 0x00399u, 0x00000u,
    0x01F9Cu, 0x00002u, 0x01F2Cu, 0x00399u, 0x00000u,
    0x01F9Du, 0x00002u, 0x01F2Du, 0x00399u, 0x00000u,
    0x01F9Eu, 0x00002u, 0x01F2Eu, 0x00399u, 0x00000u,
    0x01F9Fu, 0x00002u, 0x01F2Fu, 0x00399u, 0x00000u,
    0x01FA0u, 0x00002u, 0x01F68u, 0x00399u, 0x00000u,
    0x01FA1u, 0x00002u, 0x01F69u, 0x00399u, 0x00000u,
    0x01FA2u, 0x00002u, 0x01F6Au, 0x00399u, 0x00000u,
    0x01FA3u, 0x00002u, 0x01F6Bu, 0x00399u, 0x00000u,
    0x01FA4u, 0x00002u, 0x01F6Cu, 0x00399u, 0x00000u,
    0x01FA5u, 0x00002u, 0x01F6Du, 0x00399u, 0x00000u,
    0x01FA6u, 0x00002u, 0x01F6Eu, 0x00399u, 0x00000u,
    0x01FA7u, 0x00002u, 0x01F6Fu, 0x00399u, 0x00000u,
    0x01FA8u, 0x00002u, 0x01F68u, 0x00399u, 0x00000u,
    0x01FA9u, 0x00002u, 0x01F69u, 0x00399u, 0x00000u,
    0x01FAAu, 0x00002u, 0x01F6Au, 0x00399u, 0x00000u,
    0x01FABu, 0x00002u, 0x01F6Bu, 0x00399u, 0x00000u,
    0x01FACu, 0x00002u, 0x01F6Cu, 0x00399u, 0x00000u,
    0x01FADu, 0x00002u, 0x01F6Du, 0x00399u, 0x00000u,
    0x01FAEu, 0x00002u, 0x01F6Eu, 0x00399u, 0x00000u,
    0x01FAFu, 0x00002u, 0x01F6Fu, 0x00399u, 0x00000u,
    0x01FB2u, 0x00002u, 0x01FBAu, 0x00399u, 0x00000u,
    0x01FB3u, 0x00002u, 0x00391u, 0x00399u, 0x00000u,
    0x01FB4u, 0x00002u, 0x00386u, 0x00399u, 0x00000u,
    0x01FB6u, 0x00002u, 0x00391u, 0x00342u, 0x00000u,
    0x01FB7u, 0x00003u, 0x00391u, 0x00342u, 0x00399u,
    0x01FBCu, 0x00002u, 0x00391u, 0x00399u, 0x00000u,
    0x01FC2u, 0x00002u, 0x01FCAu, 0x00399u, 0x00000u,
    0x01FC3u, 0x00002u, 0x00397u, 0x00399u, 0x00000u,
    0x01FC4u, 0x00002u, 0x00389u, 0x00399u, 0x00000u,
    0x01FC6u, 0x00002u, 0x00397u, 0x00342u, 0x00000u,
    0x01FC7u, 0x00003u, 0x00397u, 0x00342u, 0x00399u,
    0x01FCCu, 0x00002u, 0x00397u, 0x00399u, 0x00000u,
    0x01FD2u, 0x00003u, 0x00399u, 0x00308u, 0x00300u,
    0x01FD3u, 0x00003u, 0x00399u, 0x00308u, 0x00301u,
    0x01FD6u, 0x00002u, 0x00399u, 0x00342u, 0x00000u,
    0x01FD7u, 0x00003u, 0x00399u, 0x00308u, 0x00342u,
    0x01FE2u, 0x00003u, 0x003A5u, 0x00308u, 0x00300u,
    0x01FE3u, 0x00003u, 0x003A5u, 0x00308u, 0x00301u,
    0x01FE4u, 0x00002u, 0x003A1u, 0x00313u, 0x00000u,
    0x01FE6u, 0x00002u, 0x003A5u, 0x00342u, 0x00000u,
    0x01FE7u, 0x00003u, 0x003A5u, 0x00308u, 0x00342u,
    0x01FF2u, 0x00002u, 0x01FFAu, 0x00399u, 0x00000u,
    0x01FF3u, 0x00002u, 0x003A9u, 0x00399u, 0x00000u,
    0x01FF4u, 0x00002u, 0x0038Fu, 0x00399u, 0x00000u,
    0x01FF6u, 0x00002u, 0x003A9u, 0x00342u, 0x00000u,
    0x01FF7u, 0x00003u, 0x003A9u, 0x00342u, 0x00399u,
    0x01FFCu, 0x00002u, 0x003A9u, 0x00399u, 0x00000u,
    0x0FB00u, 0x00002u, 0x00046u, 0x00046u, 0x00000u,
    0x0FB01u, 0x00002u, 0x00046u, 0x00049u, 0x00000u,
    0x0FB02u, 0x00002u, 0x00046u, 0x0004Cu, 0x00000u,
    0x0FB03u, 0x00003u, 0x00046u, 0x00046u, 0x00049u,
    0x0FB04u, 0x00003u, 0x00046u, 0x00046u, 0x0004Cu,
    0x0FB05u, 0x00002u, 0x00053u, 0x00054u, 0x00000u,
    0x0FB06u, 0x00002u, 0x00053u, 0x00054u, 0x00000u,
    0x0FB13u, 0x00002u, 0x00544u, 0x00546u, 0x00000u,
    0x0FB14u, 0x00002u, 0x00544u, 0x00535u, 0x00000u,
    0x0FB15u, 0x00002u, 0x00544u, 0x0053Bu, 0x00000u,
    0x0FB16u, 0x00002u, 0x0054Eu, 0x00546u, 0x00000u,
    0x0FB17u, 0x00002u, 0x00544u, 0x0053Du, 0x00000u,
};


/*
 * $Revision: $
 * $Log: $
 *
 * CHECK THIS FILE IN WITH `-ko`.
 *
 * Not for the usual reason (a keyword inside a string literal -- the
 * generators defang those now).  This file's text is copied VERBATIM into
 * gpu_u32_walker.cl and metal_u32_walker.metal, and from there into the
 * _str.h that the JIT compiles.  An expanded $Log$ would therefore grow the
 * KERNEL SOURCE by the whole revision history on every check-in -- changing
 * the kernel-cache key each time and re-JITting for nothing.  The other .cl
 * files in this directory are -ko for the same reason: gpu_md5_rules.cl is at
 * revision 1.34 and its working copy still reads `$Log: $`.
 */
/* gpu_u32_walker.inc -- the UTF-32 rule walker, shared body.
 *
 * THIS FILE IS NOT COMPILED DIRECTLY.  gen_u32_walker.py emits
 * gpu_md5_rules32.cl (OpenCL) and metal_md5_rules32.metal (Metal) from it,
 * substituting only the address-space spellings.  That is deliberate: the
 * byte walker exists as two hand-maintained 1100-line twins
 * (gpu_md5_rules.cl / metal_md5_rules.metal) and keeping them in step is a
 * standing cost.  One source removes the question for this walker, and it is
 * the concrete answer to "keep OpenCL and Metal at feature parity".
 *
 * The CPU reference is applyrule32() in ../ruleproc32.c and it is the ONLY
 * authority.  Every arm below cites the behaviour it mirrors where that
 * behaviour is surprising; where it is not, the arm is a transliteration and
 * is deliberately unclever.
 *
 * ---- WHAT THIS WALKER IS NOT -------------------------------------------
 *
 * 1. It does NOT implement the twelve RULE32_OP_*_STR string-operand opcodes
 *    (0x1002..0x100C).  MEASURED reason, not a preference: across 338,310
 *    real rule lines (HashMob.100k.rule, all_gj.rule, game.rule) exactly FOUR
 *    use one.  They appear only in hand-authored UTF-32 rules.  Excluding
 *    them removes every variable-length operand from the device stream except
 *    the two collapsed affix runs, which keeps the operand skip a constant.
 *    A rule using one is marked "no UTF-32 form" host-side and its pairs are
 *    walked on the CPU, so correctness is preserved by construction.
 *
 * 2. It computes VARIANT 0 ONLY.  applyrule32 can have two right answers for
 *    one (word, rule) when a Turkish/Azeri dotted-i mapping is reached, but
 *    mdxfind's CPU -8 path calls applyrule_u32(..., variant 0, &nvar) and only
 *    COUNTS the cases where nvar > 1 (Variants_dropped).  Matching that is
 *    what makes GPU == CPU reachable at all; emitting both variants here
 *    would diverge from the oracle on every word containing i or I under
 *    l / u / c / C / t.
 *
 * 3. Buffer exhaustion is DEFINED behaviour, not an error, exactly as in the
 *    byte walker: the rule does what it can, stops, and whatever was
 *    generated becomes the candidate.  The CPU engine's bound is
 *    RULE32_MAXCP (200K codepoints) and this one's is U32_BUF_LIMIT, so GPU
 *    and CPU candidates diverge above U32_BUF_LIMIT.  `-G none` is the answer
 *    when CPU-exact output is required at that length.
 */

/* ---- THE TWO BUFFER ADDRESS SPACES, and why they are not one ----------
 *
 * U32_BUF     the WORKING buffers: the staged codepoints, the memory-verb
 *             scratch, and the encode target.  Two arrays of U32_BUF_ELEMS
 *             uints plus a byte buffer -- about 24 KB per lane.
 * U32_SCRATCH the 3-element array u32_upper_full writes an expanded uppercase
 *             into.  Twelve bytes, always lane-local.
 *
 * On OpenCL both expand to nothing: private is the default and drivers spill
 * to global transparently.  On METAL THEY MUST DIFFER, and the reason is on
 * the record in this tree rather than theoretical -- task #250 moved the byte
 * walker's `buf` out of `thread` because on an M2 Max the PSO-create gate
 * rejected it outright with "Compute function exceeds available temporary
 * registers".  Apple Metal does NOT spill.  24 KB of `thread` arrays would
 * fail the same way, so U32_BUF is `device` there and the host provides the
 * slice, exactly as buf_scratch_pool already does for the byte walker.
 *
 * U32_SCRATCH stays `thread` because its callers pass a plain local array, and
 * Metal type-checks address spaces: a `device`-qualified parameter cannot
 * accept a thread-local argument.  Collapsing the two into one macro compiles
 * on OpenCL and fails on Metal, which is exactly the kind of difference that
 * only shows up on the backend you were not testing. */

/* ==== sizing ==========================================================
 *
 * ELEMENTS, not bytes.  One element is a uint32_t codepoint here, where the
 * byte walker's element is a uchar -- so the same element count costs 4x the
 * memory.  That is the headline occupancy risk of this walker and the reason
 * U32_BUF_ELEMS is injectable separately from RULE_BUF_MAX: a 2026 attempt at
 * a second 40960-BYTE buffer already FATAL'd CL_OUT_OF_HOST_MEMORY on an
 * RTX 3080 (see gpu_md5_rules.cl, the apply_rule scratch comment), and this
 * walker needs two buffers of uint.
 *
 * U32_BUF_LIMIT is 15 below the allocation, matching the byte walker: it
 * covers the n+1 boundary reads in the per-op bounds checks.
 */
/* DEFAULT 2048 ELEMENTS, chosen for correctness parity with the byte walker,
 * not for memory.  The input-word gate is GPU_RULES_MAX_INPUT_LEN = 1024
 * BYTES (gpujob.h), a 1024-byte UTF-8 word is at most 1024 codepoints, and
 * the byte walker's RULE_BUF_MAX is 2 x its gate so that a `d` or `f` on a
 * full-length word still fits.  1024 elements here would stage the widest
 * allowed input with NO growth headroom and would turn every duplication verb
 * on a long word into a defined-behaviour divergence from the CPU.
 *
 * The cost is stated rather than hidden.  Per-thread private memory, MEASURED
 * from the declarations in gpu_md5_rules32.cl:
 *
 *   byte walker      buf 2048 uchar + mem 2048 uchar            =  4,096 B
 *   pure UTF-32      u32buf+u32mem 2048 uint + cand 8192 uchar  = 24,576 B  6.0x
 *   mixed            the above + bytebuf 2048 uchar             = 26,624 B  6.5x
 *
 * That is the headline occupancy risk of this walker and the reason the knob
 * exists: a 2026 attempt at a second 40960-BYTE buffer already FATAL'd
 * CL_OUT_OF_HOST_MEMORY on an RTX 3080.  Lowering it to 1024 halves the two
 * uint buffers and quarters `cand`, at the price of divergence above
 * U32_BUF_LIMIT -- which is DEFINED behaviour, not an error.  Both settings
 * are in the trial matrix. */
/* Presence marker.  Kernel sources compiled into the SAME translation unit as
 * this walker test `#ifdef GPU_U32_WALKER_PRESENT` to decide whether they have
 * a UTF-32 arm at all.  It exists so one kernel source (gpu_template.cl,
 * metal_template.metal, the kernel-A pair) serves both engines: the host
 * appends this walker to the source list only when `-8` is active, so a
 * byte-mode run compiles text that is byte-identical to the pre-UTF-32
 * program -- same cache key, same private-memory footprint, same PTX/AIR.
 * A `-DGPU_U32_RULES` build option would have done the same job, but it would
 * have had to be threaded through 57 separate per-algorithm compile helpers
 * and could drift out of step with the source list it describes; this cannot,
 * because it IS the source list. */
#define GPU_U32_WALKER_PRESENT 1

#ifndef U32_BUF_ELEMS
#define U32_BUF_ELEMS  2048
#endif
#ifndef U32_BUF_LIMIT
#define U32_BUF_LIMIT  (U32_BUF_ELEMS - 15)
#endif

/* Bytes of device-side working memory ONE lane needs, laid out as
 *   [0                 .. U32_BUF_ELEMS*4)    u32buf  codepoints
 *   [U32_BUF_ELEMS*4   .. U32_BUF_ELEMS*8)    u32mem  memory verbs
 *   [U32_BUF_ELEMS*8   .. + U32_OUT_BYTES)    the candidate bytes
 *
 * Defined HERE, in the shared body, because the HOST has to allocate exactly
 * this and the kernel has to carve exactly this -- two places that must agree
 * to the byte, so they read it from one constant.  A multiple of 16, so every
 * region is aligned for the uint casts on both backends.
 *
 * At U32_BUF_ELEMS = 2048 that is 24,576 bytes per lane, and the grid is one
 * lane per WORD, so ~402 MB at the 16,384-word peak.  Sized deliberately:
 * against the 40 KB-per-lane the pre-task-#250 byte walker wanted at the same
 * peak it is a fraction, and Apple Silicon has 8-24 GB of unified memory. */
#define U32_OUT_BYTES   (4 * U32_BUF_ELEMS)
#define U32_SLOT_BYTES  (U32_BUF_ELEMS * 8 + U32_OUT_BYTES)

/* Return codes, in applyrule32()'s numbering (ruleproc32.h).  NOT the byte
 * walker's: the two engines number their negatives INVERSELY and collapsing
 * them is a documented trap (mdxfind.c, the applyrule_u32 contract table).
 * The kernel bodies translate. */
#define U32_ERR_INVALID (-1)   /* input is not well-formed UTF-8: pair dies  */
#define U32_ERR_NOROOM  (-2)   /* buffer too small: caller sized it wrongly  */
#define U32_REJECTED    (-3)   /* a rejection rule fired: emit nothing       */

#define U32_END          0u    /* terminates a packed rule (RULE32_END)      */

/* Opcodes for the collapsed affix runs.  Values from ruleproc32.h; they sit
 * above the byte engine's 0xc0..0xfd range on purpose. */
#define RULE32_OP_APPEND_MULTI   0x1000u
#define RULE32_OP_PREPEND_MULTI  0x1001u

/* Named codepoints, from ruleproc32.c. */
#define U32_ZWJ          0x200Du
#define U32_ZWNJ         0x200Cu
#define U32_EMOJI_MOD_LO 0x1F3FBu
#define U32_EMOJI_MOD_HI 0x1F3FFu
#define U32_RI_LO        0x1F1E6u
#define U32_RI_HI        0x1F1FFu
#define U32_TAG_LO       0xE0020u
#define U32_TAG_HI       0xE007Fu
#define U32_HW_VOICED     0xFF9Eu
#define U32_HW_SEMIVOICED 0xFF9Fu
#define U32_SMALL_I       0x0069u
#define U32_CAPITAL_I     0x0049u
/* The Turkish/Azeri dotted-i family.  ruleproc32.c names these
 * CP_LATIN_CAPITAL_I_DOT / CP_LATIN_SMALL_DOTLESS; same values, and the
 * special cases in u32_upper/u32_lower below are its cp_upper/cp_lower
 * token for token. */
#define U32_CAPITAL_I_DOT 0x0130u
#define U32_SMALL_DOTLESS 0x0131u
#define U32_SMALL_SIGMA   0x03C3u
#define U32_FINAL_SIGMA   0x03C2u

/* `=NX` and `%NX` pack as their LITERAL ASCII bytes, a historical exception
 * to the high-bit opcode range.  gpu_common.cl already names them for the
 * byte walker; ../rule_ops.h does not, so the host twin test needs them from
 * here.  Guarded so whichever source arrives first wins. */
#ifndef RULE_OP_REJ_AT_CHR
#define RULE_OP_REJ_AT_CHR   0x3du
#endif
#ifndef RULE_OP_REJ_CNT_CHR
#define RULE_OP_REJ_CNT_CHR  0x25u
#endif

#define U32_ENCODABLE(cp) ((cp) <= 0x10FFFFu && ((cp) < 0xD800u || (cp) > 0xDFFFu))


/* ==== UTF-8 -> UTF-32, strict =========================================
 *
 * Mirrors utf8_to_utf32() (ruleproc32.c).  STRICT is the whole point: a
 * permissive decoder accepts overlongs and CESU-8 surrogates silently and the
 * failure then shows up much later as a candidate that never matches.
 * Rejected here, as there: overlong forms, surrogates encoded as three bytes,
 * scalars above U+10FFFF, lead bytes 0xC0/0xC1/0xF5..0xFF, truncated
 * sequences and stray continuation bytes.
 *
 * Returns the codepoint count, or U32_ERR_INVALID / U32_ERR_NOROOM.
 *
 * The ASCII fast path is first and is not an optimisation of the decoder so
 * much as of the DIVERGENCE: a warp of ASCII words takes the one-byte arm
 * uniformly and never enters the length dispatch below.
 */
U32_SI int u32_decode(U32_GLOBAL const uchar *in, int inlen,
                      U32_BUF uint *out, int outmax)
{
    int i = 0, n = 0;

    while (i < inlen) {
        uint b0 = (uint)in[i];
        uint cp;
        int need;

        if (n >= outmax) return U32_ERR_NOROOM;

        if (b0 < 0x80u) { out[n++] = b0; i++; continue; }

        if (b0 < 0xC2u) return U32_ERR_INVALID;   /* continuation, C0, C1 */
        else if (b0 < 0xE0u) { cp = b0 & 0x1Fu; need = 1; }
        else if (b0 < 0xF0u) { cp = b0 & 0x0Fu; need = 2; }
        else if (b0 < 0xF5u) { cp = b0 & 0x07u; need = 3; }
        else return U32_ERR_INVALID;              /* F5..FF never valid */

        /* The continuation bytes live at i+1 .. i+need, so the sequence is
         * truncated unless i+need is still inside the buffer. */
        if (i + need >= inlen) return U32_ERR_INVALID;
        for (int k = 1; k <= need; k++) {
            uint bc = (uint)in[i + k];
            if ((bc & 0xC0u) != 0x80u) return U32_ERR_INVALID;
            cp = (cp << 6) | (bc & 0x3Fu);
        }
        /* Overlong, surrogate and out-of-range checks, per length. */
        if (need == 1) { if (cp < 0x80u)    return U32_ERR_INVALID; }
        else if (need == 2) {
            if (cp < 0x800u)                return U32_ERR_INVALID;
            if (cp >= 0xD800u && cp <= 0xDFFFu) return U32_ERR_INVALID;
        } else {
            if (cp < 0x10000u || cp > 0x10FFFFu) return U32_ERR_INVALID;
        }
        out[n++] = cp;
        i += need + 1;
    }
    return n;
}

/* ==== UTF-32 -> UTF-8 =================================================
 *
 * Mirrors utf32_to_utf8() (ruleproc32.c), INCLUDING the drop rule: there is
 * no "invalid" outcome here.  An unencodable codepoint is DROPPED and the
 * rest of the line is emitted.  The only way to get one is a verb doing
 * arithmetic on a codepoint -- + - L R and s -- pushing it past U+10FFFF or
 * into the surrogate block.  Keeping that test in the ENCODER rather than in
 * those four arms is what keeps the walker free of range checks.
 *
 * Returns the byte count, or U32_ERR_NOROOM.
 */
U32_SI int u32_encode(U32_BUF const uint *in, int inlen,
                      U32_BUF uchar *out, int outmax)
{
    int i, n = 0;

    for (i = 0; i < inlen; i++) {
        uint cp = in[i];

        if (!U32_ENCODABLE(cp)) continue;         /* dropped, line survives */

        if (cp < 0x80u) {
            if (n + 1 > outmax) return U32_ERR_NOROOM;
            out[n++] = (uchar)cp;
        } else if (cp < 0x800u) {
            if (n + 2 > outmax) return U32_ERR_NOROOM;
            out[n++] = (uchar)(0xC0u | (cp >> 6));
            out[n++] = (uchar)(0x80u | (cp & 0x3Fu));
        } else if (cp < 0x10000u) {
            if (n + 3 > outmax) return U32_ERR_NOROOM;
            out[n++] = (uchar)(0xE0u | (cp >> 12));
            out[n++] = (uchar)(0x80u | ((cp >> 6) & 0x3Fu));
            out[n++] = (uchar)(0x80u | (cp & 0x3Fu));
        } else {
            if (n + 4 > outmax) return U32_ERR_NOROOM;
            out[n++] = (uchar)(0xF0u | (cp >> 18));
            out[n++] = (uchar)(0x80u | ((cp >> 12) & 0x3Fu));
            out[n++] = (uchar)(0x80u | ((cp >> 6) & 0x3Fu));
            out[n++] = (uchar)(0x80u | (cp & 0x3Fu));
        }
    }
    return n;
}

/* ==== cluster layer ===================================================
 *
 * Every position and length operand in this engine counts GRAPHEME CLUSTERS.
 * A rule that says "delete character 3" means the third thing a reader sees,
 * and on vocalised Arabic or pointed Hebrew the third codepoint is routinely
 * a vowel mark hanging off the second letter.
 *
 * MEASURED, and it decided the design: classifying every verb by whether its
 * applyrule32 arm calls cl_count / cl_start / cl_next shows that a
 * CLUSTER-FREE subset covers only 34.22% of HashMob.100k.rule, 25.69% of
 * HashMob.10k.rule, 26.40% of all_gj.rule and 4.22% of game.rule -- because
 * the excluded verbs are the COMMON ones (i 63619, o 26646, T 15685,
 * r 15293, ' 13399, ] 13039, * 8732, { 8708 occurrences in HashMob.100k).
 * So the cluster layer is implemented in full rather than avoided, and the
 * staging is by cl_all_plain instead, exactly as the CPU stages it.
 */

U32_SI int u32_is_mark(uint c)
{
    int lo = 0, hi = U32_MARK_N - 1;

    if (c < U32_MARK_LO || c > U32_MARK_HI) return 0;   /* all ASCII, 1 test */
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (c < u32_marks[2 * mid])      hi = mid - 1;
        else if (c > u32_marks[2 * mid + 1]) lo = mid + 1;
        else return 1;
    }
    return 0;
}

U32_SI int u32_is_ri(uint c) { return c >= U32_RI_LO && c <= U32_RI_HI; }

/* UAX #29 GB6-GB8.  A Korean syllable can be written as one precomposed
 * codepoint or as conjoining jamo; macOS stores filenames decomposed, so
 * harvested Korean arrives either way. */
U32_SI int u32_hangul_class(uint c)
{
    if (c >= 0x1100u && c <= 0x115Fu) return 1;   /* L */
    if (c >= 0x1160u && c <= 0x11A7u) return 2;   /* V */
    if (c >= 0x11A8u && c <= 0x11FFu) return 3;   /* T */
    if (c >= 0xA960u && c <= 0xA97Cu) return 1;
    if (c >= 0xD7B0u && c <= 0xD7C6u) return 2;
    if (c >= 0xD7CBu && c <= 0xD7FBu) return 3;
    if (c >= 0xAC00u && c <= 0xD7A3u)
        return ((c - 0xAC00u) % 28u) ? 5 : 4;     /* LVT : LV */
    return 0;
}

U32_SI int u32_hangul_join(int a, int b)
{
    if (a == 1) return b == 1 || b == 2 || b == 4 || b == 5;
    if (a == 4 || a == 2) return b == 2 || b == 3;
    if (a == 5 || a == 3) return b == 3;
    return 0;
}

U32_SI int u32_is_extend(uint c)
{
    if (c >= U32_EMOJI_MOD_LO && c <= U32_EMOJI_MOD_HI) return 1;
    if (c >= U32_TAG_LO && c <= U32_TAG_HI) return 1;
    if (c == U32_ZWNJ) return 1;
    if (c == U32_HW_VOICED || c == U32_HW_SEMIVOICED) return 1;
    return u32_is_mark(c);
}

/* GB9c.  The consonant test is approximated as "a letter of the same script",
 * which over-joins only where a virama is followed by an independent vowel --
 * rare, and far less wrong than a dangling halant. */
U32_SI int u32_indic_script(uint c)
{
    if (c >= 0x0900u && c <= 0x097Fu) return 1;
    if (c >= 0x0980u && c <= 0x09FFu) return 2;
    if (c >= 0x0A80u && c <= 0x0AFFu) return 3;
    if (c >= 0x0B00u && c <= 0x0B7Fu) return 4;
    if (c >= 0x0C00u && c <= 0x0C7Fu) return 5;
    if (c >= 0x0D00u && c <= 0x0D7Fu) return 6;
    if (c >= 0x1780u && c <= 0x17FFu) return 7;
    return 0;
}

U32_SI int u32_is_linker(uint c)
{
    return c == 0x094Du || c == 0x09CDu || c == 0x0ACDu ||
           c == 0x0B4Du || c == 0x0C4Du || c == 0x0D4Du ||
           c == 0x17D2u;
}

/* Advance from i past exactly ONE cluster.  Every other cluster routine is
 * written in terms of this, so the definition lives in one place. */
U32_SI int u32_cl_next(U32_BUF const uint *b, int n, int i)
{
    if (i >= n) return n;

    /* Fast path, and it carries almost all real traffic.  Nothing below the
     * lowest mark at U+0300 can continue a cluster and nothing below U+1F1E6
     * is a regional indicator, so a base under that with a successor under
     * the mark floor is a one-codepoint cluster, settled in two compares. */
    if (b[i] < U32_RI_LO && (i + 1 >= n || b[i + 1] < U32_MARK_LO)) return i + 1;

    if (u32_is_ri(b[i])) {
        i++;
        if (i < n && u32_is_ri(b[i])) i++;        /* the pair is one flag */
    } else {
        int h = u32_hangul_class(b[i]);
        i++;
        if (h) {
            while (i < n) {
                int h2 = u32_hangul_class(b[i]);
                if (!h2 || !u32_hangul_join(h, h2)) break;
                h = h2; i++;
            }
        }
    }
    for (;;) {
        int linker = 0;
        while (i < n && u32_is_extend(b[i])) {
            if (u32_is_linker(b[i])) linker = 1;
            i++;
        }
        if (linker && i < n && u32_indic_script(b[i])) { i++; continue; }
        if (i < n && b[i] == U32_ZWJ) {
            i++;
            if (i < n) i++;
            continue;
        }
        break;
    }
    return i;
}

/* True when nothing in the buffer can join or extend, so cluster index and
 * codepoint index are the same.  ONE comparison per codepoint answers it.
 *
 * This is the staging gate.  MEASURED hit rate: 100.00% of the decodable
 * lines of NONUTF8test1.txt, 89.60% of UTF8test1.txt (overstated -- $HEX[]
 * was not unwrapped by the measuring tool), and 24.97% of UTF8test2.txt,
 * which is the honest figure for genuinely multi-script input.  So it is a
 * real optimisation and NOT a way to avoid implementing the walk.
 *
 * DO NOT "TIGHTEN" THIS TEST.  It was tried, 2026-09-14, and it is a large
 * REGRESSION on the GPU.  The bare threshold is conservative: it sends every
 * codepoint above U+02FF down the cluster walk, and on UTF8test2.txt 66.34%
 * of those walks turn out to be unnecessary (the word holds a high codepoint
 * but nothing that clusters).  Replacing the one compare with the precise
 * question u32_cl_next() asks -- extend, ZWJ, regional indicator, conjoining
 * Hangul -- removes exactly those walks and was byte-exact on 164,540,744
 * (word, rule) pairs.  It still lost, on an fpga.local GTX 1080, both arms
 * built from one tree differing in this object alone:
 *
 *      cluster-sensitive rules (38,370)  45.84 -> 28.12 Mh/s   1.63x SLOWER
 *      cluster-free rules      (61,625) 112.85 -> 75.26 Mh/s   1.50x SLOWER
 *      byte mode (control)              349.73 -> 350.07 Mh/s  unchanged
 *
 * Two lessons, and the second is the useful one.  First, the precise test is
 * not cheap: u32_is_extend() reaches u32_is_mark(), a binary search over 290
 * ranges, so the gate costs a divergent branchy table probe per codepoint in
 * place of one compare -- to save a walk whose own fast path is two compares
 * per codepoint.  The gate can never save more than about one compare per
 * codepoint, so there is no version of this that pays.
 *
 * Second, and this is why the number to chase is elsewhere: the CLUSTER-FREE
 * half slowed down by the same factor.  Those rules do not call cl_start() or
 * cl_count() at all, so a per-call cost cannot explain it.  The regression is
 * global -- kernel size and occupancy -- which says the 2.5x cluster
 * multiplier does not live in this gate either way.
 *
 * It used to be a bare `>= U32_MARK_LO` threshold, which was CORRECT but
 * conservative: it sent every codepoint above U+02FF down the cluster walk,
 * and 69.7% of the words that took the walk on UTF8test2.txt contained
 * nothing that clusters at all.  The precise test below asks the question
 * cl_next actually asks, and keeps the one-comparison exit for ASCII.
 *
 * Marks alone would be WRONG here, not merely slower -- an emoji-ZWJ
 * sequence carries no combining mark and still clusters, as does a flag
 * pair and a Hangul syllable.  The predicate mirrors every branch of
 * u32_cl_next and must be changed with it. */
U32_SI int u32_cl_all_plain(U32_BUF const uint *b, int n)
{
    for (int i = 0; i < n; i++) if (b[i] >= U32_MARK_LO) return 0;
    return 1;
}

U32_SI int u32_cl_start(U32_BUF const uint *b, int n, int k)
{
    int i = 0;
    if (u32_cl_all_plain(b, n)) return k < n ? k : n;
    while (i < n && k > 0) { i = u32_cl_next(b, n, i); k--; }
    return i;
}

U32_SI int u32_cl_count(U32_BUF const uint *b, int n)
{
    int i = 0, c = 0;
    if (u32_cl_all_plain(b, n)) return n;
    while (i < n) { i = u32_cl_next(b, n, i); c++; }
    return c;
}

/* Reverse the half-open span [i,j).  Reversing two spans and then the whole
 * run swaps two clusters of DIFFERENT lengths without a scratch buffer. */
U32_SI void u32_rev_span(U32_BUF uint *b, int i, int j)
{
    for (j--; i < j; i++, j--) { uint t = b[i]; b[i] = b[j]; b[j] = t; }
}

U32_SI void u32_cl_swap(U32_BUF uint *b, int n, int k1, int k2)
{
    int a0 = u32_cl_start(b, n, k1), a1 = u32_cl_start(b, n, k1 + 1);
    int b0 = u32_cl_start(b, n, k2), b1 = u32_cl_start(b, n, k2 + 1);
    if (a1 > b0) return;
    u32_rev_span(b, a0, a1); u32_rev_span(b, a1, b0); u32_rev_span(b, b0, b1);
    u32_rev_span(b, a0, b1);
}

/* ==== case layer ======================================================
 *
 * Tables are GENERATED from the CPU engine's own headers by
 * gen_u32_tables.py and verified element-by-element against them, because
 * hand-transcribing 6,858 entries is the defect class that check exists to
 * remove.
 */
/* ---- WHY THE TWO CASE ARRAYS ARE A KERNEL ARGUMENT ------------------
 *
 * They used to be CL_CONSTANT like the rest.  MEASURED on a GTX 1080:
 *
 *     ptxas error : File uses too much global constant data
 *                   (0x132c4 bytes, 0x10000 max)
 *
 * 78,532 against NVIDIA's 65,536-byte constant bank.  The rules program
 * already carried ~47.8 KB of __constant before this walker was added -- the
 * algorithm tables in gpu_common.cl -- so the 30,696 bytes here pushed it
 * 13 KB over.  `u32_case_up` and `u32_case_lo` are 26,048 of those 30,696, so
 * moving just those two to __global brings this walker's constant use to
 * 4,648 and the program to ~52.5 KB: 13 KB of headroom rather than none.
 *
 * int16 DELTAS were measured first and REJECTED: the range is [-42319, 42319]
 * and **183 of 6,512 entries do not fit in int16** (the astral blocks --
 * Deseret, Osage, Adlam -- have large case offsets).  A delta table with an
 * escape list would also have saved only 13,024 bytes, landing at 65,508
 * against a 65,536 limit, which is 28 bytes of headroom and not a design.
 *
 * The two arrays arrive CONCATENATED in one buffer -- up at [0 .. N-1], lo at
 * [N .. 2N-1] -- so exactly one pointer threads through, rather than two or a
 * struct.  `ct` is that pointer and it is passed down from the kernel.
 *
 * The COST is that a case lookup now reads global memory instead of the
 * constant cache.  The tables are 26 KB and hot, so they should live in L1/L2,
 * but that is an expectation and not a measurement; it is named in the run
 * report as a thing to watch rather than claimed to be free.
 */
#define U32_CT_UP(ct, ix)  ((ct)[(ix)])
#define U32_CT_LO(ct, ix)  ((ct)[U32_CASE_N + (ix)])

U32_SI int u32_case_find(uint c)   /* index into the case tables, or -1 */
{
    int lo = 0, hi = U32_CASE_NRANGES - 1;

    /* Bounds first.  Without it every ASCII digit and punctuation character
     * paid a full binary search, and case-heavy rules over an alphanumeric
     * wordlist ran 19% slower on the CPU for exactly that reason. */
    if (c < u32_case_ranges[0] ||
        c > u32_case_ranges[3 * (U32_CASE_NRANGES - 1) + 1]) return -1;

    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (c < u32_case_ranges[3 * mid])          hi = mid - 1;
        else if (c > u32_case_ranges[3 * mid + 1]) lo = mid + 1;
        else return (int)(u32_case_ranges[3 * mid + 2] +
                          (c - u32_case_ranges[3 * mid]));
    }
    return -1;
}

/* turkish is ALWAYS 0 here -- variant 0 only, see the header.  It is kept as
 * a parameter so the arms read the same as the CPU's and a future variant
 * pass has somewhere to go. */
U32_SI uint u32_upper(uint c, int turkish, U32_GLOBAL const uint *ct)
{
    int ix;
    if (c == U32_SMALL_I) return turkish ? U32_CAPITAL_I_DOT : U32_CAPITAL_I;
    /* U+0131 -> I is UNAMBIGUOUS (both locales agree), so ruleproc32.c states
     * it as a special case.  Here the generated table already carries it --
     * up(U+0131) = U+0049, verified against latin_case.h -- so the branch
     * would be dead weight in a function this hot.  Said rather than left to
     * be rediscovered, because the two functions are meant to read as
     * translations of each other. */
    if (c >= 'a' && c <= 'z') return c - 32u;
    if (c < 0x80u) return c;
    ix = u32_case_find(c);
    if (ix < 0) return c;
    return U32_CT_UP(ct, ix) ? U32_CT_UP(ct, ix) : c;
}

U32_SI uint u32_lower(uint c, int turkish, U32_GLOBAL const uint *ct)
{
    int ix;
    if (c == U32_CAPITAL_I) return turkish ? U32_SMALL_DOTLESS : U32_SMALL_I;
    /* U+0130 lowercases to i + COMBINING DOT ABOVE in full Unicode, which is
     * length-changing and therefore EXCLUDED from the generated table -- so
     * the table answer is U+0130 unchanged and the lookup below cannot supply
     * this.  ruleproc32.c's cp_lower states the simple 1:1 answer, plain i,
     * and this is that line.
     *
     * Found by the host twin, not by inspection: 105 diffs in 49,985,000 pairs
     * over HashMob.10k x 5,000 UTF-8 words, every one of them a `c`/`l`/`E`
     * after a `+N`/`-N` had walked a codepoint onto U+0130.  A 1-in-476,000
     * divergence that no per-rule spot check would have shown, and the reason
     * the twin exists. */
    if (c == U32_CAPITAL_I_DOT) return U32_SMALL_I;
    if (c >= 'A' && c <= 'Z') return c + 32u;
    if (c < 0x80u) return c;
    ix = u32_case_find(c);
    if (ix < 0) return c;
    return U32_CT_LO(ct, ix) ? U32_CT_LO(ct, ix) : c;
}

/* Index into u32_expand of the entry for c, or -1. */
U32_SI int u32_expand_find(uint c)
{
    int lo = 0, hi = U32_EXPAND_N - 1;
    int stride = 2 + U32_EXPAND_MAX;

    if (c < U32_EXPAND_LO || c > U32_EXPAND_HI) return -1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (c < u32_expand[mid * stride])      hi = mid - 1;
        else if (c > u32_expand[mid * stride]) lo = mid + 1;
        else return mid;
    }
    return -1;
}

/* A ligature has no 1:1 mapping in EITHER direction -- its uppercase grows
 * and its lowercase is itself -- so asking u32_upper alone would call it
 * caseless and `c` would walk straight past one looking for a letter. */
U32_SI int u32_is_cased(uint c, int turkish, U32_GLOBAL const uint *ct)
{
    if (u32_expand_find(c) >= 0) return 1;
    return u32_upper(c, turkish, ct) != c || u32_lower(c, turkish, ct) != c;
}

/* Uppercase that is allowed to GROW: eszett -> SS is the one mapping in the
 * covered ranges that changes length, and no 1:1 table can hold it.  Writes 1
 * or 3 codepoints and returns the count.  Only the whole-string verbs use it;
 * a position-indexed verb keeps the 1:1 map, because growing a character
 * underneath an index would move every position the rest of the rule refers
 * to.  So `u` on a word with an eszett gives ...SS..., while a toggle AT a
 * position leaves the eszett alone. */
U32_SI int u32_upper_full(uint c, int turkish, U32_SCRATCH uint *out,
                          U32_GLOBAL const uint *ct)
{
    int e = u32_expand_find(c);
    int stride = 2 + U32_EXPAND_MAX;
    if (e >= 0) {
        int cnt = (int)u32_expand[e * stride + 1];
        for (int k = 0; k < cnt; k++) out[k] = u32_expand[e * stride + 2 + k];
        return cnt;
    }
    out[0] = u32_upper(c, turkish, ct);
    return 1;
}

/* Uppercase the whole buffer in place, growing where a mapping expands.  ONE
 * pass over the buffer, which is the whole point.  Returns the new length or
 * U32_ERR_NOROOM.
 *
 * MEASURED, fpga.local GTX 1080, 38,370 distinct rules x 55,000 UTF8test2
 * words: throughput on this kernel tracks the NUMBER OF PASSES over the
 * codepoint buffer and almost nothing else.  `l` and `t` traverse once and both
 * run 233.7 Mh/s; `u` traversed twice -- an expansion pre-scan, then the map --
 * and ran 123.9, a ratio of 1.886 against a predicted 2.  Deleting the pre-scan
 * took it to 262.8.
 *
 * And making that pass CHEAPER does nothing: a block bitmap derived from
 * u32_expand, which removed 91.7%% of the pre-scan's binary searches, measured
 * 1.00x on every verb.  It was reverted.  The binary search was never the cost;
 * the traversal was.  Count passes before proposing anything here.
 *
 * Expansion is handled inline instead.  u32_upper_full returns 1 for every
 * codepoint that does not grow -- all but 0.0127%% of a multi-script corpus --
 * and the shift runs only for the rest.  Growth cannot cascade, since no
 * expansion output is itself an expanding codepoint, so `i` skips what was just
 * written exactly as the backwards write did. */
U32_SI int u32_upper_all(U32_BUF uint *b, int n, int turkish,
                         U32_GLOBAL const uint *ct)
{
    uint tmp[U32_EXPAND_MAX];
    int i, j, k, len = n;

    for (i = 0; i < len; i++) {
        k = u32_upper_full(b[i], turkish, tmp, ct);
        if (k == 1) { b[i] = tmp[0]; continue; }
        if (len + k - 1 > U32_BUF_LIMIT) return U32_ERR_NOROOM;
        for (j = len - 1; j > i; j--) b[j + k - 1] = b[j];
        for (j = 0; j < k; j++)      b[i + j] = tmp[j];
        len += k - 1;
        i   += k - 1;
    }
    return len;
}

/* Greek sigma is the one case mapping that depends on WHERE the character
 * sits: a sigma ending a word is U+03C2, anywhere else U+03C3.  The table
 * cannot express that, so it maps capital sigma to the medial form and this
 * runs afterwards over a whole-word lowercase.  Only the whole-string verbs
 * call it; a single-position toggle has no word to be at the end of. */
U32_SI void u32_final_sigma(U32_BUF uint *b, int n, int turkish,
                            U32_GLOBAL const uint *ct)
{
    for (int i = 0; i < n; i++) {
        if (b[i] != U32_SMALL_SIGMA) continue;
        if (i + 1 == n || !u32_is_cased(b[i + 1], turkish, ct))
            b[i] = U32_FINAL_SIGMA;
    }
}

/* Character-class membership, over a CODEPOINT.  The 15x32 bitmap in the
 * common source is indexed by BYTE, so a codepoint above 0xff cannot be in
 * any class except ALL and HIGH.  Mirrors RULE_CLASS_MATCH_CP in
 * ../rule_ops.h, which is shared verbatim by the two CPU engines. */
U32_SI int u32_class_match(uchar cb, uint ch)
{
    if (ch > 0xffu) {
        uchar which = (uchar)(cb & 0x7f);
        int in = (which == 15 || which == 14) ? 1 : 0;   /* ALL, HIGH */
        return in ^ (int)((cb >> 7) & 1);
    }
    return rule_class_match(cb, (uchar)ch);
}


/* ==== the per-word class, and the engine predicate ===================
 *
 * These live in the SHARED body rather than in the kernel file so that
 * both backends AND both host tests get one copy.  pick_engine already
 * exists in three places -- mdxfind.c, procrule.c (token-for-token,
 * because procrule is the oracle) and gpu_u32_wire_hosttest.c (on purpose,
 * so the test asserts agreement rather than assuming it).  A fourth and
 * fifth copy, one per backend, is where a divergence would actually hide.
 */
#define U32_CLASS_A   0u   /* ASCII or empty -- decodable, not wide */
#define U32_CLASS_W   1u   /* HI|UTF8        -- decodable, wide     */
#define U32_CLASS_I   2u   /* HI alone       -- NOT decodable       */

/* mdxfind.c's pick_engine is:
 *
 *     wide     = ((wenc & U8C_WIDE) == U8C_WIDE);
 *     u32_must = (u32_can && !byte_can);
 *     if ((wide || u32_must) && u32_can && U8C_DECODABLE(wenc)) return 1;
 *     if (byte_can) return 0;
 *     return -1;
 *
 * The word axis collapses to the three classes above because classify_utf8
 * guarantees exactly one of ASCII / HI for n > 0 and UTF8 only in company
 * with HI: `wide` is class == W, and `decodable` is class != I.
 *
 * Returns 1 = UTF-32, 0 = byte, -1 = neither (the pair is skipped, which is
 * what the CPU counts in Unreachable). */
U32_SI int u32_pick_engine(uint wclass, int u32_can, int byte_can)
{
    int wide      = (wclass == U32_CLASS_W);
    int decodable = (wclass != U32_CLASS_I);
    int u32_must  = (u32_can && !byte_can);

    if ((wide || u32_must) && u32_can && decodable) return 1;
    if (byte_can) return 0;
    return -1;
}


/* Second half of rule_offset: capability bits over a 30-bit offset.
 * A rule program larger than 2^30 would collide with these; the host asserts
 * against it before it sets a bit. */
#define U32_R_HASFORM 0x80000000u   /* a UTF-32 form exists for this rule   */
#define U32_R_BYTEOK  0x40000000u   /* the byte compiler accepted this rule */
#define U32_R_OFFMASK 0x3fffffffu

/* Per-word class values live in gpu_u32_walker.inc beside u32_pick_engine,
 * which is the only thing that interprets them. */

#define U32_OFF_MASK  0x3fffffffu
#define U32_TAG_SHIFT 30

/* U32_OUT_BYTES (the encoder's worst case, 4 UTF-8 bytes per codepoint) and
 * U32_SLOT_BYTES are defined ONCE, at the top of this file beside
 * U32_BUF_ELEMS, because the Metal host derives its scratch-pool stride from
 * the same formula.  A second identical #define sat here for one revision;
 * it was legal and it was exactly the kind of thing that later drifts. */

/* ==== the shared per-lane body ========================================
 *
 * Staged input -> engine choice -> walk -> UTF-8 bytes out.  Returns the
 * candidate length in BYTES, or negative:
 *   -1  the pair is skipped (no engine, or a rejection op fired)
 *   -2  the walker ran out of buffer (DEFINED divergence above
 *       U32_BUF_LIMIT, not an error -- see gpu_u32_walker.inc)
 *
 * `out` receives the candidate bytes.  For the byte engine that is the walker
 * buffer itself and no copy happens; for the UTF-32 engine it is the encode
 * target.  Both are caller-owned so the register/private-memory cost is
 * visible at the call site instead of hidden here.
 */
/* ==== the walker ======================================================
 *
 * apply_rule32:
 *   prog: pointer to the packed uint32 stream, already offset by the caller;
 *         the first word is the first opcode.  Terminated by U32_END.
 *   buf:  U32_BUF_ELEMS uints, pre-staged with the input in buf[0..len-1].
 *   mem:  U32_BUF_ELEMS uints of scratch for the memory verbs.  Passed in
 *         rather than declared here so the CALLER picks the address space --
 *         Metal cannot afford 8 KB of `thread` for it on top of buf.
 *   len:  initial length in CODEPOINTS.
 *
 * Returns the new length in codepoints, or U32_REJECTED / U32_ERR_NOROOM.
 *
 * ROOM() mirrors applyrule32's macro and its purpose: every growth path goes
 * through one place, because a bound living in one file and the buffer in
 * another is how the byte engine once wrote 40 KB into a 20 KB buffer.
 *
 * The 256-op cap on the loop matches the byte walker's, not the CPU's -- the
 * CPU walks to the terminator.  A rule longer than 256 ops is not reachable
 * from packrule32's own limits in practice; the cap is there so a corrupt
 * stream cannot spin a lane forever.
 */
#define U32_ROOM(need) do { if ((need) > U32_BUF_LIMIT) return U32_ERR_NOROOM; } while (0)

U32_SI int apply_rule32(U32_GLOBAL const uint *prog,
                        U32_BUF uint *buf, U32_BUF uint *mem, int len,
                        U32_GLOBAL const uint *ct)
{
    int k = 0;
    int memlen = 0;         /* per-invocation, exactly as applyrule32 resets it */
    const int turkish = 0;  /* variant 0 only -- see the header */
    int i, j;

    for (int nop = 0; nop < 256; nop++) {
        uint op = prog[k++];
        if (op == U32_END) break;

        switch (op) {
            case RULE_OP_NOOP:
            case RULE_OP_NOOP_SP:
            case RULE_OP_NOOP_TAB:
            case RULE_OP_HASH_EXIT:
            case RULE_OP_S_SPECIAL:
                break;

            /* ---- collapsed affix runs -------------------------------
             * Appending is a straight copy to the tail.  Prepending must
             * reproduce what N separate prepends do, and each one pushes in
             * FRONT of the last, so `^1^2^3` yields 321 -- the operands land
             * in REVERSE rule order.  Getting that backwards is silent. */
            case RULE32_OP_APPEND_MULTI: {
                int cnt = (int)prog[k++];
                U32_ROOM(len + cnt);
                for (int m = 0; m < cnt; m++) buf[len + m] = prog[k + m];
                k += cnt; len += cnt;
                break;
            }
            case RULE32_OP_PREPEND_MULTI: {
                int cnt = (int)prog[k++];
                U32_ROOM(len + cnt);
                for (int m = len - 1; m >= 0; m--) buf[m + cnt] = buf[m];
                for (int m = 0; m < cnt; m++) buf[m] = prog[k + cnt - 1 - m];
                k += cnt; len += cnt;
                break;
            }
            case RULE_OP_APPEND: {
                uint cp = prog[k++];
                U32_ROOM(len + 1); buf[len++] = cp; break;
            }
            case RULE_OP_PREPEND: {
                uint cp = prog[k++];
                U32_ROOM(len + 1);
                for (i = len; i > 0; i--) buf[i] = buf[i - 1];
                buf[0] = cp; len++; break;
            }

            /* ---- arithmetic on a CODEPOINT, not a byte ---------------
             * This is the deliberate semantic change: + - L R operate on the
             * full codepoint, so L on U+0041 gives U+0082 where the byte
             * engine gave 0x82.  These verbs are also the ONLY way to produce
             * a codepoint UTF-8 cannot encode, and u32_encode drops exactly
             * those while emitting the rest of the line.
             *
             * Note the index is a CODEPOINT index, not a cluster index -- that
             * is applyrule32's behaviour, not an omission here. */
            case RULE_OP_INC:     { int y = (int)prog[k++]; if (y < len) buf[y]++; break; }
            case RULE_OP_DEC:     { int y = (int)prog[k++]; if (y < len) buf[y]--; break; }
            case RULE_OP_BIT_SHL: { int y = (int)prog[k++]; if (y < len) buf[y] <<= 1; break; }
            case RULE_OP_BIT_SHR: { int y = (int)prog[k++]; if (y < len) buf[y] >>= 1; break; }

            /* `.N` at the LAST position leaves the character alone.  The byte
             * engine reads its NUL terminator there and writes a NUL, which is
             * an artefact of a NUL-terminated buffer; applyrule32 deliberately
             * does not reproduce it, because the answer then depended on the
             * previous candidate in a reused static buffer. */
            case RULE_OP_REPL_NEXT: { int y = (int)prog[k++];
                if (y < len - 1) buf[y] = buf[y + 1]; break; }
            case RULE_OP_REPL_PREV: { int y = (int)prog[k++];
                if (y < len && y > 0) buf[y] = buf[y - 1]; break; }

            /* ---- memory ---------------------------------------------- */
            case RULE_OP_MEM_STORE:
                for (i = 0; i < len; i++) mem[i] = buf[i];
                memlen = len; break;
            case RULE_OP_MEM_APP:
                if (memlen > 0) { U32_ROOM(len + memlen);
                    for (i = 0; i < memlen; i++) buf[len + i] = mem[i];
                    len += memlen; }
                break;
            case RULE_OP_MEM_PRE:
                if (memlen > 0) { U32_ROOM(len + memlen);
                    for (i = len - 1; i >= 0; i--) buf[i + memlen] = buf[i];
                    for (i = 0; i < memlen; i++) buf[i] = mem[i];
                    len += memlen; }
                break;
            case RULE_OP_MEM_REJ:
                if (memlen == len) {
                    for (i = 0; i < len; i++) if (buf[i] != mem[i]) break;
                    if (i == len) return U32_REJECTED;
                }
                break;
            /* `X N M I`: insert M of memory from OFFSET N, at position I.
             * REJECTS on each of no-memory / zero-count / position past end /
             * offset past memory / range overruns memory; only the
             * result-too-long case clamps.  Clamping the others instead is a
             * measured divergence (MX042 on aB3 gave aBaB33 where the oracle
             * rejects).  Memory is counted in CODEPOINTS while the insert
             * position is a CLUSTER index, as in applyrule32. */
            case RULE_OP_MEM_INSERT: {
                int off = (int)prog[k++], cnt = (int)prog[k++], at = (int)prog[k++];
                int nc = u32_cl_count(buf, len), a;
                if (memlen < 1 || cnt < 1 || at > nc ||
                    off > memlen || (off + cnt) > memlen) return U32_REJECTED;
                if (len + cnt > U32_BUF_LIMIT) cnt = U32_BUF_LIMIT - len;
                if (cnt < 1) break;
                a = u32_cl_start(buf, len, at);
                for (i = len - 1; i >= a; i--) buf[i + cnt] = buf[i];
                for (i = 0; i < cnt; i++)      buf[a + i] = mem[off + i];
                len += cnt;
                break;
            }

            /* ---- rejection ------------------------------------------
             * Length is a count of CLUSTERS and of the CURRENT buffer, not
             * the original: `$a _5` on a 4-cluster word must survive.  And
             * `<N` / `>N` follow john -- reject unless LESS / GREATER than N
             * -- which is the opposite of what an earlier reading had. */
            case RULE_OP_REJ_LEN_NE: { int y = (int)prog[k++];
                if (y != u32_cl_count(buf, len)) return U32_REJECTED; break; }
            case RULE_OP_REJ_LEN_GE: { int y = (int)prog[k++];
                if (u32_cl_count(buf, len) >= y) return U32_REJECTED; break; }
            case RULE_OP_REJ_LEN_LE: { int y = (int)prog[k++];
                if (u32_cl_count(buf, len) <= y) return U32_REJECTED; break; }
            case RULE_OP_REJ_AT_CHR: { int y = (int)prog[k++]; uint cp = prog[k++];
                if (y >= len || buf[y] != cp) return U32_REJECTED; break; }
            case RULE_OP_REJ_CNT_CHR: { int y = (int)prog[k++]; uint cp = prog[k++];
                int cnt = 0;
                for (i = 0; i < len; i++) if (buf[i] == cp) cnt++;
                if (cnt < y) return U32_REJECTED; break; }
            case RULE_OP_REJ_HAS: { uint cp = prog[k++];
                for (i = 0; i < len; i++) if (buf[i] == cp) return U32_REJECTED;
                break; }
            case RULE_OP_REJ_NHAS: { uint cp = prog[k++];
                for (i = 0; i < len; i++) if (buf[i] == cp) break;
                if (i >= len) return U32_REJECTED; break; }
            case RULE_OP_REJ_FIRST: { uint cp = prog[k++];
                if (len > 0 && buf[0] != cp) return U32_REJECTED; break; }
            case RULE_OP_REJ_LAST: { uint cp = prog[k++];
                if (len > 0 && buf[len - 1] != cp) return U32_REJECTED; break; }

            /* ---- substitution and purge, codepoint-indexed ---------- */
            case RULE_OP_PURGE: { uint cp = prog[k++]; int d = 0;
                for (i = 0; i < len; i++) if (buf[i] != cp) buf[d++] = buf[i];
                len = d; break; }
            case RULE_OP_SUB: { uint from = prog[k++], to = prog[k++];
                for (i = 0; i < len; i++) if (buf[i] == from) buf[i] = to;
                break; }

            /* ---- whole-word case ------------------------------------
             * The sigma pass is skipped unless a medial sigma was actually
             * produced; folding the test into the mapping loop costs one
             * compare per character instead of a second walk. */
            case RULE_OP_LOWER: {
                int sigma = 0;
                for (i = 0; i < len; i++) {
                    buf[i] = u32_lower(buf[i], turkish, ct);
                    if (buf[i] == U32_SMALL_SIGMA) sigma = 1;
                }
                if (sigma) u32_final_sigma(buf, len, turkish, ct);
                break;
            }
            case RULE_OP_UPPER: {
                int nl = u32_upper_all(buf, len, turkish, ct);
                if (nl < 0) return U32_ERR_NOROOM;
                len = nl; break;
            }
            /* `c`: lowercase the word, then UPPERCASE the first CASED
             * codepoint, expanding if it is one of the growing forms.  Note
             * this is uppercase, not Unicode TITLE case: the fi ligature gives
             * FInd here, where title case would give Find. */
            /* The hunt for the first cased codepoint rides along with the
             * lowercase pass instead of walking the buffer a second time.  The
             * old second loop breaks at that codepoint, which sounds cheap and
             * is not: MEASURED on UTF8test2.txt, 63.20% of words carry NO cased
             * codepoint at all, so the break never fires and the scan runs the
             * whole word -- 33.8% of a full extra pass overall.  Traversals are
             * what cost here, so that was a third of a verb for the same number
             * of u32_is_cased calls.
             *
             * fc survives u32_final_sigma, which runs between the two: it maps
             * sigma to final sigma and both are cased, so it can neither move
             * nor create the first cased position.  buf[fc] is read AFTER that
             * pass, exactly as the old second loop saw it. */
            case RULE_OP_CAP: {
                int sigma = 0, fc = -1;
                for (i = 0; i < len; i++) {
                    buf[i] = u32_lower(buf[i], turkish, ct);
                    if (buf[i] == U32_SMALL_SIGMA) sigma = 1;
                    if (fc < 0 && u32_is_cased(buf[i], turkish, ct)) fc = i;
                }
                if (sigma) u32_final_sigma(buf, len, turkish, ct);
                if (fc >= 0) {
                    uint ex[U32_EXPAND_MAX];
                    int ec = u32_upper_full(buf[fc], turkish, ex, ct);
                    if (ec == 1) buf[fc] = ex[0];
                    else {
                        U32_ROOM(len + ec - 1);
                        for (j = len - 1; j > fc; j--) buf[j + ec - 1] = buf[j];
                        for (j = 0; j < ec; j++) buf[fc + j] = ex[j];
                        len += ec - 1;
                    }
                }
                break;
            }
            /* `C`: UPPERCASE the word, then lowercase the first cased one. */
            case RULE_OP_CAP_INV: {
                int nl = u32_upper_all(buf, len, turkish, ct);
                if (nl < 0) return U32_ERR_NOROOM;
                len = nl;
                for (i = 0; i < len; i++) {
                    if (!u32_is_cased(buf[i], turkish, ct)) continue;
                    buf[i] = u32_lower(buf[i], turkish, ct);
                    break;
                }
                break;
            }
            case RULE_OP_TOGGLE:
                for (i = 0; i < len; i++) {
                    uint u = u32_upper(buf[i], turkish, ct);
                    buf[i] = (u != buf[i]) ? u : u32_lower(buf[i], turkish, ct);
                }
                break;
            /* `TN` toggles the CLUSTER's BASE, not the Nth codepoint. */
            case RULE_OP_TOGGLE_AT: {
                int kk = (int)prog[k++];
                int p = u32_cl_start(buf, len, kk);
                if (kk < u32_cl_count(buf, len)) {
                    uint u = u32_upper(buf[p], turkish, ct);
                    buf[p] = (u != buf[p]) ? u : u32_lower(buf[p], turkish, ct);
                }
                break;
            }
            /* `E` / `eX` title case.  An already-uppercase letter at a word
             * start IS the capital: keep it and mark the word started.  The
             * earlier form lowercased it and left the flag clear, so the NEXT
             * lowercase letter was capitalised instead -- Hello1 became
             * hEllo1.  hashcat 6.2.5 and john both give Hello1. */
            case RULE_OP_TITLE_SP:
            case RULE_OP_TITLE_SEP: {
                uint sep = (op == RULE_OP_TITLE_SEP) ? prog[k++] : (uint)' ';
                int z = 0;
                for (i = 0; i < len; i++) {
                    uint ch = buf[i];
                    if (ch == sep) { z = 0; }
                    else if (u32_lower(ch, turkish, ct) != ch) {
                        if (z == 0) z = 1;              /* already capitalised */
                        else buf[i] = u32_lower(ch, turkish, ct);
                    } else if (u32_upper(ch, turkish, ct) != ch) {
                        if (z == 0) { z = 1; buf[i] = u32_upper(ch, turkish, ct); }
                    }
                    /* CASELESS characters -- digits, punctuation, `$`, `[` --
                     * fall through UNTOUCHED and leave z alone.  An earlier
                     * form of this arm set z on them and lowercased in the
                     * final else, which turned `$HEX[` into `$Hex[` under
                     * `E`: 9,516 divergences in 1,999,400 pairs, all from
                     * this one arm.  There is no final else on purpose. */
                }
                break;
            }

            /* ---- cluster-indexed structural verbs ------------------- */
            case RULE_OP_REVERSE: {
                /* Two in-place passes and no scratch buffer: reverse each
                 * cluster, then reverse the whole run.  Reversing by
                 * codepoint put an Arabic fatha on the wrong letter and
                 * turned a flag into a DIFFERENT flag. */
                for (i = 0; i < len; ) { int e = u32_cl_next(buf, len, i);
                    u32_rev_span(buf, i, e); i = e; }
                u32_rev_span(buf, 0, len);
                break;
            }
            case RULE_OP_DUP:
                U32_ROOM(len * 2);
                for (i = 0; i < len; i++) buf[len + i] = buf[i];
                len *= 2; break;
            case RULE_OP_REFLECT: {
                int e;
                U32_ROOM(len * 2);
                for (i = 0; i < len; i++) buf[len + i] = buf[i];
                for (i = len; i < len * 2; ) { e = u32_cl_next(buf, len * 2, i);
                    u32_rev_span(buf, i, e); i = e; }
                u32_rev_span(buf, len, len * 2);
                len *= 2; break;
            }
            /* `q` -- double every CLUSTER, so a pointed letter is doubled
             * with its points rather than the mark being doubled alone. */
            case RULE_OP_DUP_EACH: {
                int nc = u32_cl_count(buf, len), w, a, b2, c2;
                U32_ROOM(len * 2);
                w = len * 2;
                for (c2 = nc - 1; c2 >= 0; c2--) {
                    a = u32_cl_start(buf, len, c2); b2 = u32_cl_start(buf, len, c2 + 1);
                    for (j = 0; j < 2; j++) { int t2;
                        for (t2 = b2 - 1; t2 >= a; t2--) buf[--w] = buf[t2]; }
                }
                len *= 2; break;
            }
            case RULE_OP_ROT_L:
                if (u32_cl_count(buf, len) > 1) {
                    int c1 = u32_cl_start(buf, len, 1);
                    u32_rev_span(buf, 0, c1); u32_rev_span(buf, c1, len);
                    u32_rev_span(buf, 0, len);
                }
                break;
            case RULE_OP_ROT_R:
                if (u32_cl_count(buf, len) > 1) {
                    int a = u32_cl_start(buf, len, u32_cl_count(buf, len) - 1);
                    u32_rev_span(buf, 0, a); u32_rev_span(buf, a, len);
                    u32_rev_span(buf, 0, len);
                }
                break;
            case RULE_OP_DROP_FIRST: {
                int e;
                if (!len) break;
                e = u32_cl_next(buf, len, 0);
                for (i = 0; i + e < len; i++) buf[i] = buf[i + e];
                len -= e; break;
            }
            case RULE_OP_DROP_LAST: {
                int nc;
                if (!len) break;
                nc = u32_cl_count(buf, len);
                len = u32_cl_start(buf, len, nc - 1);
                break;
            }
            case RULE_OP_SWAP_FRONT:
                if (u32_cl_count(buf, len) > 1) u32_cl_swap(buf, len, 0, 1);
                break;
            case RULE_OP_SWAP_BACK: {
                int nc = u32_cl_count(buf, len);
                if (nc > 1) u32_cl_swap(buf, len, nc - 2, nc - 1);
                break;
            }
            case RULE_OP_SWAP_AT: {
                int p = (int)prog[k++], q = (int)prog[k++];
                int nc = u32_cl_count(buf, len);
                if (p < nc && q < nc && p != q)
                    u32_cl_swap(buf, len, p < q ? p : q, p < q ? q : p);
                break;
            }
            case RULE_OP_DEL_AT: {
                int kk = (int)prog[k++], a, b2, w;
                if (kk >= u32_cl_count(buf, len)) break;
                a = u32_cl_start(buf, len, kk);
                b2 = u32_cl_start(buf, len, kk + 1);
                for (w = a; w + (b2 - a) < len; w++) buf[w] = buf[w + (b2 - a)];
                len -= (b2 - a);
                break;
            }
            case RULE_OP_TRUNC: {
                int kk = (int)prog[k++];
                if (kk < u32_cl_count(buf, len)) len = u32_cl_start(buf, len, kk);
                break;
            }
            /* Insert tests position >= length, so inserting AT the length
             * appends rather than silently doing nothing. */
            case RULE_OP_INSERT: {
                int kk = (int)prog[k++]; uint cp = prog[k++];
                int p = u32_cl_start(buf, len, kk);
                if (u32_cl_count(buf, len) >= kk) { U32_ROOM(len + 1);
                    for (i = len; i > p; i--) buf[i] = buf[i - 1];
                    buf[p] = cp; len++; }
                break;
            }
            /* `oNX` replaces the whole CLUSTER at N with ONE codepoint, so it
             * can SHRINK the buffer when that cluster was multi-codepoint. */
            case RULE_OP_OVERWRITE: {
                int kk = (int)prog[k++]; uint cp = prog[k++];
                int p = kk, a, b2, w;
                if (kk < u32_cl_count(buf, len)) {
                    a = u32_cl_start(buf, len, kk);
                    b2 = u32_cl_start(buf, len, kk + 1);
                    buf[a] = cp;
                    for (w = a + 1; w + (b2 - a - 1) < len; w++)
                        buf[w] = buf[w + (b2 - a - 1)];
                    len -= (b2 - a - 1);
                }
                /* Special case carried over from ruleproc.c: overwriting
                 * position 0 of an EMPTY buffer APPENDS instead of doing
                 * nothing, so `o0X` on a candidate some earlier verb emptied
                 * still yields X.  Omitting it is what made every
                 * `[ [ ... o0q ...` and `] ] ... o0q ...` rule in
                 * HashMob.100k.rule diverge on short words -- 9 distinct
                 * rules, and each looked like a cluster bug rather than a
                 * missing two-line special case. */
                if (p == 0 && len == 0) { U32_ROOM(1); buf[0] = cp; len = 1; }
                break;
            }
            /* `yN` / `YN`.  The guard is `if (len)` -- NOT `nrep > 0`.  At
             * nrep == 0 the arms are a no-op by arithmetic anyway, so the two
             * spellings agree; kept as the oracle writes it so a future
             * reader diffing the two files sees no difference at all. */
            case RULE_OP_DUP_FIRST: {
                int nrep = (int)prog[k++];
                int c1 = u32_cl_start(buf, len, 1);   /* first cluster width */
                if (len) { U32_ROOM(len + nrep * c1);
                    for (i = len - 1; i >= 0; i--) buf[i + nrep * c1] = buf[i];
                    for (i = 0; i < nrep; i++)
                        for (j = 0; j < c1; j++) buf[i * c1 + j] = buf[nrep * c1 + j];
                    len += nrep * c1; }
                break;
            }
            case RULE_OP_DUP_LAST: {
                int nrep = (int)prog[k++];
                int a = u32_cl_start(buf, len, u32_cl_count(buf, len) - 1);
                int cw = len - a;
                if (len) { U32_ROOM(len + nrep * cw);
                    for (i = 0; i < nrep; i++)
                        for (j = 0; j < cw; j++) buf[len + i * cw + j] = buf[a + j];
                    len += nrep * cw; }
                break;
            }
            case RULE_OP_REPEAT: {
                int nrep = (int)prog[k++];
                if (nrep > 0) { U32_ROOM(len * (nrep + 1));
                    for (j = 1; j <= nrep; j++)
                        for (i = 0; i < len; i++) buf[j * len + i] = buf[i];
                    len *= (nrep + 1); }
                break;
            }
            case RULE_OP_DUP_PREFIX: {
                int nrep = (int)prog[k++];
                int cpn = u32_cl_start(buf, len, nrep);
                if (nrep > 0 && u32_cl_count(buf, len) >= nrep) {
                    U32_ROOM(len + cpn);
                    for (i = len - 1; i >= 0; i--) buf[i + cpn] = buf[i];
                    for (i = 0; i < cpn; i++) buf[i] = buf[cpn + i];
                    len += cpn; }
                break;
            }
            case RULE_OP_DUP_SUFFIX: {
                int nrep = (int)prog[k++];
                int nc = u32_cl_count(buf, len);
                int cpn = len - u32_cl_start(buf, len, nc - nrep);
                if (nrep > 0 && nc >= nrep) { U32_ROOM(len + cpn);
                    for (i = 0; i < cpn; i++) buf[len + i] = buf[len - cpn + i];
                    len += cpn; }
                break;
            }
            /* Clamping derived from ruleproc.c, not inferred: when the start
             * is past the end the word is left UNCHANGED -- not truncated and
             * not emptied.  Guessing this produced a word-destroying
             * difference on real rules. */
            /* `xNM`.  The guard is `nc > N && (N+M) <= nc` and there is NO
             * lower bound on M: `x20` on a word of 2+ clusters extracts ZERO
             * clusters and EMPTIES the candidate.  A `if (m < 1) break;`
             * looks like defensive hygiene and is a divergence -- game.rule
             * uses x20/x30/x40/x50/x60/x70 heavily and every one of them
             * differed. */
            case RULE_OP_EXTRACT: {
                int kk = (int)prog[k++], m = (int)prog[k++], x;
                int nc = u32_cl_count(buf, len);
                int a = u32_cl_start(buf, len, kk);
                int b2 = u32_cl_start(buf, len, kk + m);
                if (nc > kk && (kk + m) <= nc) {
                    for (x = 0; x < b2 - a; x++) buf[x] = buf[a + x];
                    len = x;
                }
                break;
            }
            /* `ONM`.  Same guard as extract -- the WHOLE range must fit, and
             * the word is left untouched otherwise rather than omitting as
             * much as it can.  The final length is where the shift loop
             * STOPPED, which is NOT len - (b-a) at the boundary. */
            case RULE_OP_OMIT: {
                int kk = (int)prog[k++], m = (int)prog[k++], x;
                int nc = u32_cl_count(buf, len);
                int a = u32_cl_start(buf, len, kk);
                int b2 = u32_cl_start(buf, len, kk + m);
                if (nc > kk && (kk + m) <= nc) {
                    for (x = a; x + (b2 - a) < len; x++) buf[x] = buf[x + (b2 - a)];
                    len = x;
                }
                break;
            }
            /* `*N` insert every N CLUSTERS -- but applyrule32 divides by
             * CODEPOINT count, so this arm is codepoint-based on purpose. */
            case RULE_OP_DIV_INSERT: {
                int x = (int)prog[k++]; uint c1 = prog[k++];
                int total, w;
                if (x <= 0) return U32_ERR_INVALID;
                if (len < x) break;
                total = len + len / x;
                U32_ROOM(total);
                w = total;
                for (i = len - 1; i >= 0; i--) {
                    if (((i + 1) % x) == 0) buf[--w] = c1;
                    buf[--w] = buf[i];
                }
                len = total;
                break;
            }
            /* `TNX` -- toggle the character after the Nth occurrence of X.
             * N is ALREADY 0-BASED out of packrule32, so `30d` packs as
             * (op, 0, 'd') and means "after the FIRST d".  An arm written as
             * `seen++; if (seen == nth)` therefore never fires at all, and the
             * separator must be skipped with `continue` so it cannot itself be
             * the character toggled.  Both were wrong in a first draft and
             * cost 13 divergences in 1,999,400 pairs -- the last 13. */
            case RULE_OP_TOGGLE_SEP: {
                int y = (int)prog[k++]; uint c1 = prog[k++];
                int toggle_next = 0, occurrence = 0;
                for (i = 0; i < len; i++) {
                    if (buf[i] == c1) {
                        if (occurrence == y) toggle_next = 1;
                        else occurrence++;
                        continue;
                    }
                    if (toggle_next) {
                        uint u = u32_upper(buf[i], turkish, ct);
                        buf[i] = (u != buf[i]) ? u : u32_lower(buf[i], turkish, ct);
                        break;
                    }
                }
                break;
            }
            /* `H` / `h`: replace the candidate with the hex of its UTF-8
             * ENCODING.  Encoding first is the only reading that agrees with
             * the byte engine on ASCII and is meaningful above it: hexing the
             * codepoint values would give a different string for the same
             * word depending on the engine. */
            case RULE_OP_HEX_LOWER:
            case RULE_OP_HEX_UPPER: {
                uchar tmp[U32_EXPAND_MAX * 4];
                int d = 0, nb;
                /* Encode in place into a rolling scratch, two hex digits per
                 * byte, working BACKWARDS so the growth is safe. */
                nb = 0;
                for (i = 0; i < len; i++) {
                    uint cp = buf[i];
                    if (!U32_ENCODABLE(cp)) continue;
                    nb += (cp < 0x80u) ? 1 : (cp < 0x800u) ? 2
                        : (cp < 0x10000u) ? 3 : 4;
                }
                U32_ROOM(nb * 2);
                /* Second pass: write hex digits forwards while reading the
                 * codepoints forwards.  Safe because 2 digits per byte is at
                 * least 2 output slots per input slot. */
                d = nb * 2;
                for (i = len - 1; i >= 0; i--) {
                    uint cp = buf[i];
                    int m, c;
                    if (!U32_ENCODABLE(cp)) continue;
                    if (cp < 0x80u) { tmp[0] = (uchar)cp; c = 1; }
                    else if (cp < 0x800u) { tmp[0] = (uchar)(0xC0u | (cp >> 6));
                        tmp[1] = (uchar)(0x80u | (cp & 0x3Fu)); c = 2; }
                    else if (cp < 0x10000u) { tmp[0] = (uchar)(0xE0u | (cp >> 12));
                        tmp[1] = (uchar)(0x80u | ((cp >> 6) & 0x3Fu));
                        tmp[2] = (uchar)(0x80u | (cp & 0x3Fu)); c = 3; }
                    else { tmp[0] = (uchar)(0xF0u | (cp >> 18));
                        tmp[1] = (uchar)(0x80u | ((cp >> 12) & 0x3Fu));
                        tmp[2] = (uchar)(0x80u | ((cp >> 6) & 0x3Fu));
                        tmp[3] = (uchar)(0x80u | (cp & 0x3Fu)); c = 4; }
                    for (m = c - 1; m >= 0; m--) {
                        uint hi = (uint)(tmp[m] >> 4), lo2 = (uint)(tmp[m] & 0xf);
                        uint base = (op == RULE_OP_HEX_UPPER) ? 'A' : 'a';
                        buf[--d] = (lo2 < 10u) ? ('0' + lo2) : (base + lo2 - 10u);
                        buf[--d] = (hi  < 10u) ? ('0' + hi)  : (base + hi  - 10u);
                    }
                }
                len = nb * 2;
                break;
            }

            /* ---- character classes ---------------------------------- */
            case RULE_OP_SUB_CLASS: {
                uchar cb = (uchar)prog[k++]; uint y = prog[k++];
                for (j = 0; j < len; j++)
                    if (u32_class_match(cb, buf[j])) buf[j] = y;
                break;
            }
            case RULE_OP_PURGE_CLASS: {
                uchar cb = (uchar)prog[k++]; int d = 0;
                for (j = 0; j < len; j++)
                    if (!u32_class_match(cb, buf[j])) buf[d++] = buf[j];
                len = d; break;
            }
            case RULE_OP_TITLE_CLASS: {
                uchar cb = (uchar)prog[k++]; int z = 0;
                for (j = 0; j < len; j++) {
                    uint ch = buf[j];
                    if (u32_class_match(cb, ch)) { z = 0; continue; }
                    if (u32_lower(ch, turkish, ct) != ch) { z = 1; continue; }
                    if (!z) { buf[j] = u32_upper(ch, turkish, ct); z = 1; }
                    else buf[j] = u32_lower(ch, turkish, ct);
                }
                break;
            }
            case RULE_OP_TITLE_CLASS_HC: {
                uchar cb = (uchar)prog[k++]; int z = 1;
                for (j = 0; j < len; j++) {
                    uint ch = buf[j];
                    if (z) buf[j] = u32_upper(ch, turkish, ct);
                    else   buf[j] = u32_lower(ch, turkish, ct);
                    z = u32_class_match(cb, ch) ? 1 : 0;
                }
                break;
            }
            case RULE_OP_REJ_HAS_CLASS: {
                uchar cb = (uchar)prog[k++];
                for (j = 0; j < len; j++)
                    if (u32_class_match(cb, buf[j])) return U32_REJECTED;
                break;
            }
            case RULE_OP_REJ_NHAS_CLASS: {
                uchar cb = (uchar)prog[k++];
                for (j = 0; j < len; j++) if (u32_class_match(cb, buf[j])) break;
                if (j >= len) return U32_REJECTED; break;
            }
            case RULE_OP_REJ_FIRST_CLASS: {
                uchar cb = (uchar)prog[k++];
                if (len > 0 && !u32_class_match(cb, buf[0])) return U32_REJECTED;
                break;
            }
            case RULE_OP_REJ_LAST_CLASS: {
                uchar cb = (uchar)prog[k++];
                if (len > 0) { int a = u32_cl_start(buf, len, u32_cl_count(buf, len) - 1);
                    if (!u32_class_match(cb, buf[a])) return U32_REJECTED; }
                break;
            }
            case RULE_OP_REJ_AT_CLASS: {
                int y = (int)prog[k++]; uchar cb = (uchar)prog[k++];
                if (y >= u32_cl_count(buf, len)) return U32_REJECTED;
                if (!u32_class_match(cb, buf[u32_cl_start(buf, len, y)]))
                    return U32_REJECTED;
                break;
            }
            case RULE_OP_REJ_CNT_CLASS: {
                int y = (int)prog[k++]; uchar cb = (uchar)prog[k++];
                int cnt = 0;
                for (j = 0; j < len; j++) if (u32_class_match(cb, buf[j])) cnt++;
                if (cnt < y) return U32_REJECTED; break;
            }

            /* An opcode this walker does not implement -- the string-operand
             * family, 0x1002..0x100C.  A rule containing one must never have
             * been routed here: it is marked "no UTF-32 form" host-side and
             * walked on the CPU.  Reaching this is a WIRING bug, not a data
             * condition, so it fails the pair loudly rather than emitting a
             * half-applied candidate. */
            default:
                return U32_ERR_INVALID;
        }
    }
    return len;
}

U32_SI int u32_run_pair(
    U32_GLOBAL const uchar *words, uint wpos, int wlen,
    U32_GLOBAL const uchar *rule_program,
    uint byte_roff, uint u32_roff,
    uint wclass,
    U32_BUF uchar *bytebuf,                  /* RULE_BUF_MAX uchars  */
    U32_BUF uint *u32buf, U32_BUF uint *u32mem,     /* U32_BUF_ELEMS uints each */
    U32_BUF uchar *out, int outmax,
    U32_GLOBAL const uint *case_tab,
    U32_SCRATCH int *engine_out)
{
    int u32_can  = (u32_roff & U32_R_HASFORM) != 0u;
    int byte_can = (u32_roff & U32_R_BYTEOK)  != 0u;
    int eng = u32_pick_engine(wclass, u32_can, byte_can);
    int n;

    *engine_out = eng;
    if (eng < 0) return -1;

    if (eng == 0) {
        /* ---- byte engine: unchanged semantics, unchanged walker ---- */
        for (int i = 0; i < wlen; i++) bytebuf[i] = words[wpos + i];
        n = apply_rule(rule_program + byte_roff, bytebuf, wlen);
        if (n < 0) return -1;
        for (int i = 0; i < n && i < outmax; i++) out[i] = bytebuf[i];
        return (n > outmax) ? outmax : n;
    }

    /* ---- UTF-32 engine ---------------------------------------------
     * Decode, walk, encode.  The decode is STRICT and its failure is a
     * property of the data: a class-A or class-W word decodes by
     * construction, so a failure here means the host class was wrong, and
     * skipping the pair is what the CPU does too (applyrule_u32 returns -3
     * and every caller skips a negative). */
    n = u32_decode(words + wpos, wlen, u32buf, U32_BUF_ELEMS);
    if (n < 0) return (n == U32_ERR_NOROOM) ? -2 : -1;

    n = apply_rule32((U32_GLOBAL const uint *)(rule_program + (u32_roff & U32_R_OFFMASK)),
                     u32buf, u32mem, n, case_tab);
    if (n == U32_ERR_NOROOM) return -2;
    if (n < 0) return -1;

    n = u32_encode(u32buf, n, out, outmax);
    if (n < 0) return -2;
    return n;
}
