/* Auto-generated from metal_md5salt_core.metal -- do not edit */
static const char metal_md5salt_core_str[] =
    "/*\n"
    " * $Revision: 1.1 $\n"
    " * $Log: metal_md5salt_core.metal,v $\n"
    " * Revision 1.1  2026/05/13 14:44:27  dlr\n"
    " * Initial check-in: Phase 2c-A MD5SALT Metal core.\n"
    " *\n"
    " */\n"
    "/* metal_md5salt_core.metal -- MD5SALT (JOB_MD5SALT, op e31, hashcat -m 10):\n"
    " * MD5(hex32(MD5(pass)) || salt) double-MD5 chain. Metal Phase 2c port of\n"
    " * gpu/gpu_md5salt_core.cl algo_mode 0 only.\n"
    " *\n"
    " * Mirrors gpu_md5salt_core.cl byte-for-byte for the e31 inner+outer chain\n"
    " * (template_init IV, template_finalize: inner MD5(pass) -> hex32 lowercase\n"
    " * -> outer MD5(hex32 || salt)). Address-space port:\n"
    " *   __global  -> device\n"
    " *   __private -> thread\n"
    " *\n"
    " * Phase 2c scope:\n"
    " *   - algo_mode 0 ONLY (e31 lowercase hex32 + raw salt append).\n"
    " *   - Drops modes 1-6 (UC/REV/SUB8_24/MD5_MD5SALTMD5PASS/HMAC) -- those\n"
    " *     are Phase 2d+ siblings.\n"
    " *   - Drops salt_pack_uint helper (the simpler byte-by-byte append loop is\n"
    " *     used inline; OpenCL twin's uint-pack micro-opt was for Pascal RMW\n"
    " *     pathology -- Apple Metal has no equivalent and the few-cycle\n"
    " *     difference is dominated by md5_block cost).\n"
    " *   - Reuses unsalted MD5 template_iterate convention (HEX_FEEDBACK\n"
    " *     matches CPU JOB_MD5SALT iter convention per\n"
    " *     gpu_md5salt_core.cl:749).\n"
    " *\n"
    " * Phase 2e additions (pre-salt hoist + SIMD lane batching):\n"
    " *   - template_pre_salt_state struct (port of gpu_md5salt_core.cl:91-94).\n"
    " *   - template_pre_salt: computes the password-only inner MD5+hex32 once\n"
    " *     per (word, rule, mask), stores into a `thread` carrier; sentinel\n"
    " *     for modes 1-6 (which fall through to legacy template_finalize).\n"
    " *   - template_finalize_post: consumes the carrier + salt, computes\n"
    " *     outer MD5(hex32 || salt). Mirrors gpu_md5salt_core.cl:682-747.\n"
    " *   - Gated behind GPU_TEMPLATE_HAS_PRE_SALT in metal_template.metal;\n"
    " *     the SALT_BATCH lane-batch loop iterates the carrier across up to\n"
    " *     SALT_BATCH salts per template_pre_salt evaluation. Mode 0 only;\n"
    " *     modes 1-6 retain per-salt full-finalize via the sentinel path.\n"
    " *\n"
    " * Source-order in the salted JIT TU:\n"
    " *   1. metal_common.metal         (MetalParams, md5_block, md5_to_hex_lc,\n"
    " *                                  probe_compact_idx, EMIT macros)\n"
    " *   2. metal_md5_rules.metal      (apply_rule walker; concatenated for\n"
    " *                                  GPU_TEMPLATE_HAS_RULES variants)\n"
    " *   3. metal_md5salt_core.metal   (THIS file -- replaces metal_md5_core.metal\n"
    " *                                  for salted TUs; provides the 6-arg\n"
    " *                                  template_finalize)\n"
    " *   4. metal_template.metal       (the template_phase0 kernel, with\n"
    " *                                  GPU_TEMPLATE_HAS_SALT defined)\n"
    " *\n"
    " * Critical: this file and metal_md5_core.metal define the same set of\n"
    " * symbols (template_state, template_init, template_iterate,\n"
    " * template_digest_compare, template_emit_hit_or_overflow, AND\n"
    " * template_finalize). Only ONE may be linked into any given MTLLibrary.\n"
    " * The unsalted libraries (none/R/M/RM) concat metal_md5_core.metal; the\n"
    " * salted libraries (S/RS/MS/RMS) concat metal_md5salt_core.metal. The\n"
    " * call-site dispatch lives at the #ifdef GPU_TEMPLATE_HAS_SALT block in\n"
    " * metal_template.metal -- it picks the 3-arg template_finalize when\n"
    " * HAS_SALT is undef, the 6-arg form when defined.\n"
    " *\n"
    " * Patterns 1/3 enforced (per metal_jit_harness.m):\n"
    " *   - Every pointer arg is address-space-qualified (device or thread).\n"
    " *   - Every function is static inline.\n"
    " *   - No threadgroup decls (Pattern 5).\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* template_state: per-lane MD5 chaining values. Mirrors\n"
    " * metal_md5_core.metal's struct + gpu_md5salt_core.cl line 43. */\n"
    "struct template_state {\n"
    "    uint h[HASH_WORDS];\n"
    "};\n"
    "\n"
    "/* template_pre_salt_state: carrier for the password-only portion of the\n"
    " * salted MD5 chain. Phase 2e pre-salt hoist (mirrors\n"
    " * gpu_md5salt_core.cl:91-94). Lifted OUT of the per-salt loop -- one\n"
    " * inner-MD5+hex32 evaluation amortises across SALT_BATCH outer-MD5\n"
    " * evaluations.\n"
    " *\n"
    " * Layout (Phase 2h-A, 2026-05-18): 52 bytes per lane (8+4+1 uints).\n"
    " * Down from Phase 2e's 68 bytes (16+1) — M[8..15] dropped because those\n"
    " * slots are always-zero in pre_salt; finalize_post writes them locally\n"
    " * from scratch + Phase 2h-B explicit-literal zeros for compiler folding.\n"
    " *\n"
    " * Phase 2h-A pre-roll: a8/b8/c8/d8 hold the outer MD5 state AFTER 8 FF\n"
    " * rounds (rounds 1-8 of the outer chain). These 8 rounds depend ONLY on\n"
    " * M[0..7] (the hex32) and are completely salt-independent — so we run\n"
    " * them ONCE per (word, rule, mask) here and skip them in finalize_post,\n"
    " * saving 8/64 = 12.5% of outer MD5 work per (word, salt). Mirrors\n"
    " * hashcat's \"salt-independent prefix hoist\" optimization for m10.\n"
    " *\n"
    " * Lives in `thread` storage; written once by template_pre_salt(), read\n"
    " * repeatedly by template_finalize_post() inside the inner salt loop.\n"
    " *\n"
    " * Sentinel: inner_len == 0xFFFFFFFFu means \"fall back to legacy\n"
    " * template_finalize\" (for algo_modes other than 0; Phase 2e only hoists\n"
    " * mode 0, modes 1-6 remain on the per-salt full-finalize path). */\n"
    "struct template_pre_salt_state {\n"
    "    uint M[8];          /* hex32 of inner MD5 (lowercase, M[0..7] in 16-uint addressing) */\n"
    "    uint a8, b8, c8, d8; /* Phase 2h-A: outer MD5 (a,b,c,d) state after FF rounds 1-8 */\n"
    "    uint inner_len;     /* 32 (mode 0) or TEMPLATE_PRE_SALT_SENTINEL */\n"
    "};\n"
    "\n"
    "#define TEMPLATE_PRE_SALT_SENTINEL 0xFFFFFFFFu\n"
    "\n"
    "/* template_init: install MD5 IV. */\n"
    "static inline void template_init(thread template_state &st)\n"
    "{\n"
    "    st.h[0] = 0x67452301u;\n"
    "    st.h[1] = 0xEFCDAB89u;\n"
    "    st.h[2] = 0x98BADCFEu;\n"
    "    st.h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: kept for API completeness -- never called on the\n"
    " * hot path. template_finalize streams M[] directly. */\n"
    "static inline void template_transform(thread template_state &st,\n"
    "                                      thread const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: e31 MD5SALT chain. Mirrors gpu_md5salt_core.cl\n"
    " * template_finalize algo_mode==0 path (lines 198-606). Drops modes 1-6\n"
    " * branches and the salt_pack_uint helper.\n"
    " *\n"
    " * Steps:\n"
    " *   1. Inner MD5(buf[0..len)) -> local h0/h1/h2/h3 (4 uints).\n"
    " *   2. md5_to_hex_lc into M[0..7] (32 lowercase hex chars, byte order\n"
    " *      matches CPU prmd5).\n"
    " *   3. Outer MD5(hex32 || salt) -> st.h[0..3]:\n"
    " *      - inner_len = 32 (hex32 spans M[0..7]).\n"
    " *      - Salt bytes appended at M[8..] (byte offset 32 onward).\n"
    " *      - 0x80 marker + length-bits padding per MD5 spec.\n"
    " *      - One md5_block call when total_len < 56; otherwise a second\n"
    " *        block with the length-bits trailing.\n"
    " *\n"
    " * Pattern 1: `data` is `device const uchar *` (per task #250 buf-pool\n"
    " * migration -- the per-lane slice in metal_template.metal lives in\n"
    " * device storage). `salt_buf` is also `device const uchar *` -- the\n"
    " * host's salt MTLBuffer is uploaded via gpu_metal_set_salt and\n"
    " * referenced by offset.\n"
    " *\n"
    " * The algo_mode parameter is read but only mode 0 is meaningful in\n"
    " * Phase 2c (modes 1-6 are out of scope per file header). Callers in\n"
    " * the Phase 2c HAS_SALT block always pass params.algo_mode==0 for\n"
    " * JOB_MD5SALT. The unused-arg pattern silences -Wunused without code\n"
    " * size cost; future Phase 2d may put mode-switch logic here. */\n"
    "static inline void template_finalize(thread template_state &st,\n"
    "                                     device const uchar *data, int len,\n"
    "                                     device const uchar *salt_buf,\n"
    "                                     uint slen,\n"
    "                                     uint algo_mode)\n"
    "{\n"
    "    (void)algo_mode;  /* Phase 2c: only mode 0; modes 1-6 deferred to 2d+ */\n"
    "\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "    uint h0 = 0x67452301u, h1 = 0xEFCDAB89u,\n"
    "         h2 = 0x98BADCFEu, h3 = 0x10325476u;\n"
    "\n"
    "    /* Step 1: inner MD5(data[0..len)). Streams complete 64-byte blocks,\n"
    "     * then the tail block(s) with 0x80 + length-bits padding. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(h0, h1, h2, h3, M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    M[rem >> 2] |= (uint)0x80u << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0u;\n"
    "        md5_block(h0, h1, h2, h3, M);\n"
    "    } else {\n"
    "        md5_block(h0, h1, h2, h3, M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0u;\n"
    "        md5_block(h0, h1, h2, h3, M);\n"
    "    }\n"
    "\n"
    "    /* Step 2: hex-encode digest1 into M[0..7] (32 lowercase chars =\n"
    "     * 32 bytes). Zero the trailing M[8..15] so the salt-append +\n"
    "     * 0x80 + length-bits land in clean memory. mirrors\n"
    "     * gpu_md5salt_core.cl line 491 + 550. */\n"
    "    for (int j = 8; j < 16; j++) M[j] = 0u;\n"
    "    md5_to_hex_lc(h0, h1, h2, h3, M);\n"
    "    uint inner_len = 32u;\n"
    "\n"
    "    /* Step 3: outer MD5(hex32 || salt). Salt bytes append at byte\n"
    "     * offset inner_len (==32) in M[]. For total_len < 56 one block\n"
    "     * suffices; otherwise two blocks. Byte-wise append via shift+OR\n"
    "     * mirrors the legacy `mbytes` loop in OpenCL (we drop\n"
    "     * salt_pack_uint -- the uint-pack micro-opt was for Pascal byte-\n"
    "     * RMW pathology; Apple Metal has no equivalent gain, and the\n"
    "     * cycle delta is dwarfed by the two md5_block calls). */\n"
    "    uint total_len = inner_len + slen;\n"
    "    if (total_len < 56u) {\n"
    "        /* Salt bytes + 0x80 marker fit in the first (and only) block. */\n"
    "        for (uint i = 0u; i < slen; i++) {\n"
    "            uint pos_byte = inner_len + i;\n"
    "            uint v = (uint)salt_buf[i];\n"
    "            M[pos_byte >> 2] |= v << ((pos_byte & 3) * 8);\n"
    "        }\n"
    "        {\n"
    "            uint eom_pos = inner_len + slen;\n"
    "            M[eom_pos >> 2] |= (uint)0x80u << ((eom_pos & 3) * 8);\n"
    "        }\n"
    "        M[14] = total_len * 8u;\n"
    "        M[15] = 0u;\n"
    "        st.h[0] = 0x67452301u;\n"
    "        st.h[1] = 0xEFCDAB89u;\n"
    "        st.h[2] = 0x98BADCFEu;\n"
    "        st.h[3] = 0x10325476u;\n"
    "        md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "    } else {\n"
    "        /* First block: salt bytes only (no 0x80 yet -- it lives in\n"
    "         * the second block UNLESS the salt fully fits in block 1 AND\n"
    "         * total_len < 64; see eom_in_first comment below for the\n"
    "         * salt-length-30 padding-bug fix, 2026-06-03). first_chunk =\n"
    "         * bytes of salt that fit in this block after inner_len. */\n"
    "        uint first_chunk = 64u - inner_len;\n"
    "        if (first_chunk > slen) first_chunk = slen;\n"
    "        for (uint i = 0u; i < first_chunk; i++) {\n"
    "            uint pos_byte = inner_len + i;\n"
    "            uint v = (uint)salt_buf[i];\n"
    "            M[pos_byte >> 2] |= v << ((pos_byte & 3) * 8);\n"
    "        }\n"
    "        /* MD5 padding correctness (2026-06-03 fix): when first_chunk\n"
    "         * == slen AND total_len ∈ [56..63], the 0x80 EOM marker MUST\n"
    "         * go into byte total_len of BLOCK 1 (not byte 0 of block 2).\n"
    "         * For total_len == 64 the legacy path's M[0] |= 0x80 in block\n"
    "         * 2 is correct. For total_len > 64, rem_salt > 0 also OK. */\n"
    "        uint rem_salt = slen - first_chunk;\n"
    "        uint eom_in_first = (rem_salt == 0u && total_len < 64u) ? 1u : 0u;\n"
    "        if (eom_in_first) {\n"
    "            uint eom_pos = inner_len + first_chunk;  /* total_len, in [56..63] */\n"
    "            M[eom_pos >> 2] |= (uint)0x80u << ((eom_pos & 3) * 8);\n"
    "        }\n"
    "        st.h[0] = 0x67452301u;\n"
    "        st.h[1] = 0xEFCDAB89u;\n"
    "        st.h[2] = 0x98BADCFEu;\n"
    "        st.h[3] = 0x10325476u;\n"
    "        md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "\n"
    "        /* Second block: remaining salt bytes + 0x80 (if not already\n"
    "         * in block 1) + length-bits. rem_salt < 64; if rem_salt < 56\n"
    "         * the length-bits land in this same block, otherwise one more\n"
    "         * block. */\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "        for (uint i = 0u; i < rem_salt; i++) {\n"
    "            uint v = (uint)salt_buf[first_chunk + i];\n"
    "            M[i >> 2] |= v << ((i & 3) * 8);\n"
    "        }\n"
    "        if (!eom_in_first) {\n"
    "            M[rem_salt >> 2] |= (uint)0x80u << ((rem_salt & 3) * 8);\n"
    "        }\n"
    "        if (rem_salt < 56u) {\n"
    "            M[14] = total_len * 8u;\n"
    "            M[15] = 0u;\n"
    "            md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "        } else {\n"
    "            md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "            for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "            M[14] = total_len * 8u;\n"
    "            M[15] = 0u;\n"
    "            md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_pre_salt: Phase 2e pre-salt hoist. Compute the password-only\n"
    " * portion of the salted MD5 chain ONCE per (word, rule, mask), then\n"
    " * amortise across the inner salt loop via template_finalize_post.\n"
    " *\n"
    " * Mirrors gpu_md5salt_core.cl:615-674 verbatim for algo_mode==0 (e31).\n"
    " * Mode 0 path:\n"
    " *   1. Streaming MD5 of `data[0..len)` -> 4-uint digest1.\n"
    " *   2. md5_to_hex_lc into pre.M[0..7] (32 lowercase hex chars).\n"
    " *   3. pre.M[8..15] zeroed (downstream salt-append + 0x80 + padding lands\n"
    " *      in clean memory).\n"
    " *   4. pre.inner_len = 32u.\n"
    " *\n"
    " * Modes 1-6: write sentinel and return. template_finalize_post falls\n"
    " * through to the legacy 6-arg template_finalize for those modes.\n"
    " *\n"
    " * Pattern 1: `data` is `device const uchar *` (per task #250 buf-pool\n"
    " * migration). `pre` is `thread` (per-lane register storage). */\n"
    "static inline void template_pre_salt(device const uchar *data, int len,\n"
    "                                     uint algo_mode,\n"
    "                                     thread template_pre_salt_state &pre)\n"
    "{\n"
    "    if (algo_mode != 0u) {\n"
    "        pre.inner_len = TEMPLATE_PRE_SALT_SENTINEL;\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    uint Mi[16];\n"
    "    int pos = 0;\n"
    "    uint h0 = 0x67452301u, h1 = 0xEFCDAB89u,\n"
    "         h2 = 0x98BADCFEu, h3 = 0x10325476u;\n"
    "\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            Mi[j] = (uint)data[b]\n"
    "                  | ((uint)data[b + 1] << 8)\n"
    "                  | ((uint)data[b + 2] << 16)\n"
    "                  | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(h0, h1, h2, h3, Mi);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    int rem = len - pos;\n"
    "    for (int j = 0; j < 16; j++) Mi[j] = 0u;\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        Mi[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    Mi[rem >> 2] |= (uint)0x80u << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        Mi[14] = (uint)(len * 8);\n"
    "        Mi[15] = 0u;\n"
    "        md5_block(h0, h1, h2, h3, Mi);\n"
    "    } else {\n"
    "        md5_block(h0, h1, h2, h3, Mi);\n"
    "        for (int j = 0; j < 16; j++) Mi[j] = 0u;\n"
    "        Mi[14] = (uint)(len * 8);\n"
    "        Mi[15] = 0u;\n"
    "        md5_block(h0, h1, h2, h3, Mi);\n"
    "    }\n"
    "\n"
    "    /* Hex-encode digest1 into pre.M[0..7] (Phase 2h-A: M[8..15] dropped\n"
    "     * from the carrier; finalize_post writes them from scratch). */\n"
    "    md5_to_hex_lc(h0, h1, h2, h3, pre.M);\n"
    "\n"
    "    /* Phase 2h-A pre-roll: run outer MD5's first 8 FF rounds (rounds\n"
    "     * 1-8). These ONLY depend on M[0..7] (the hex32) — salt-independent\n"
    "     * — so amortise once per (word, rule, mask) instead of per-salt.\n"
    "     * Saves 8/64 = 12.5% of outer MD5 work in finalize_post fast path. */\n"
    "    uint a = 0x67452301u, b = 0xEFCDAB89u,\n"
    "         c = 0x98BADCFEu, d = 0x10325476u;\n"
    "    MTL_MD5_FF(a,b,c,d,pre.M[0], 7,0xd76aa478u);\n"
    "    MTL_MD5_FF(d,a,b,c,pre.M[1],12,0xe8c7b756u);\n"
    "    MTL_MD5_FF(c,d,a,b,pre.M[2],17,0x242070dbu);\n"
    "    MTL_MD5_FF(b,c,d,a,pre.M[3],22,0xc1bdceeeu);\n"
    "    MTL_MD5_FF(a,b,c,d,pre.M[4], 7,0xf57c0fafu);\n"
    "    MTL_MD5_FF(d,a,b,c,pre.M[5],12,0x4787c62au);\n"
    "    MTL_MD5_FF(c,d,a,b,pre.M[6],17,0xa8304613u);\n"
    "    MTL_MD5_FF(b,c,d,a,pre.M[7],22,0xfd469501u);\n"
    "    pre.a8 = a;\n"
    "    pre.b8 = b;\n"
    "    pre.c8 = c;\n"
    "    pre.d8 = d;\n"
    "    pre.inner_len = 32u;\n"
    "}\n"
    "\n"
    "/* template_finalize_post: Phase 2e pre-salt hoist consumer. Runs ONCE\n"
    " * per salt under the lane-batch pattern. For algo_mode 0 (the only\n"
    " * hoisted mode) consumes pre.M (the 32-char hex of MD5(password)) and\n"
    " * computes the outer MD5(hex32 || salt). For sentinel pre_state (any\n"
    " * algo_mode != 0) dispatches to the legacy 6-arg template_finalize.\n"
    " *\n"
    " * Mirrors gpu_md5salt_core.cl:682-747 verbatim. Drops salt_pack_uint\n"
    " * (same rationale as legacy template_finalize -- Apple Metal lacks\n"
    " * Pascal byte-RMW pathology). */\n"
    "static inline void template_finalize_post(thread template_state &st,\n"
    "                                          thread const template_pre_salt_state &pre,\n"
    "                                          device const uchar *data, int len,\n"
    "                                          device const uchar *salt_buf,\n"
    "                                          uint slen,\n"
    "                                          uint algo_mode)\n"
    "{\n"
    "    if (pre.inner_len == TEMPLATE_PRE_SALT_SENTINEL) {\n"
    "        /* Fallback: legacy template_finalize handles modes 1-6 + the\n"
    "         * full inner computation. Pass through buf+len unchanged. */\n"
    "        template_finalize(st, data, len, salt_buf, slen, algo_mode);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    /* Mode 0 hoisted path: pre.M[0..7] holds the 32-char lowercase hex\n"
    "     * of the inner MD5. Compute outer MD5(hex32 || salt) into st.h.\n"
    "     *\n"
    "     * Phase 2h-B: M[8..15] written from scratch with explicit literals so\n"
    "     * the Metal compiler sees compile-time-known zeros at M[9..13],M[15]\n"
    "     * and can fold them out of MD5 round inputs (`+ M[k]` becomes `+ 0`\n"
    "     * → elided). M[0..7] still come from pre.M[] (computed once per word\n"
    "     * in template_pre_salt; consumed per-salt here). */\n"
    "    uint M[16];\n"
    "    M[0] = pre.M[0]; M[1] = pre.M[1]; M[2] = pre.M[2]; M[3] = pre.M[3];\n"
    "    M[4] = pre.M[4]; M[5] = pre.M[5]; M[6] = pre.M[6]; M[7] = pre.M[7];\n"
    "    M[8] = 0u; M[9]  = 0u; M[10] = 0u; M[11] = 0u;\n"
    "    M[12] = 0u; M[13] = 0u; M[14] = 0u; M[15] = 0u;\n"
    "    uint inner_len = pre.inner_len;  /* always 32 in mode 0 */\n"
    "\n"
    "    uint total_len = inner_len + slen;\n"
    "    if (total_len < 56u) {\n"
    "        /* Single-block fast path. Typical for short salts (e31 sm-saltfull\n"
    "         * uses 3/6 byte salts). Inline rounds 9-64 from pre-rolled state\n"
    "         * (a8,b8,c8,d8) — Phase 2h-A skips rounds 1-8 (salt-independent). */\n"
    "        for (uint i = 0u; i < slen; i++) {\n"
    "            uint pos_byte = inner_len + i;\n"
    "            uint v = (uint)salt_buf[i];\n"
    "            M[pos_byte >> 2] |= v << ((pos_byte & 3) * 8);\n"
    "        }\n"
    "        {\n"
    "            uint eom_pos = inner_len + slen;\n"
    "            M[eom_pos >> 2] |= (uint)0x80u << ((eom_pos & 3) * 8);\n"
    "        }\n"
    "        M[14] = total_len * 8u;\n"
    "        /* M[15] already 0u (literal init above) */\n"
    "\n"
    "        /* Phase 2h-A: start outer MD5 at round 9 from pre-rolled state.\n"
    "         * Rounds 1-8 (which would use M[0..7] = hex32, all known after\n"
    "         * pre_salt) were precomputed once per word in template_pre_salt\n"
    "         * and saved into pre.{a8,b8,c8,d8}. */\n"
    "        uint a = pre.a8, b = pre.b8, c = pre.c8, d = pre.d8;\n"
    "\n"
    "        /* Rounds 9-16 (FF, uses M[8..15] = salt + 0x80 + length-bits) */\n"
    "        MTL_MD5_FF(a,b,c,d,M[8], 7,0x698098d8u);\n"
    "        MTL_MD5_FF(d,a,b,c,M[9],12,0x8b44f7afu);\n"
    "        MTL_MD5_FF(c,d,a,b,M[10],17,0xffff5bb1u);\n"
    "        MTL_MD5_FF(b,c,d,a,M[11],22,0x895cd7beu);\n"
    "        MTL_MD5_FF(a,b,c,d,M[12], 7,0x6b901122u);\n"
    "        MTL_MD5_FF(d,a,b,c,M[13],12,0xfd987193u);\n"
    "        MTL_MD5_FF(c,d,a,b,M[14],17,0xa679438eu);\n"
    "        MTL_MD5_FF(b,c,d,a,M[15],22,0x49b40821u);\n"
    "        /* Rounds 17-32 (GG, mixed M[] indices spanning hex + salt halves) */\n"
    "        MTL_MD5_GG(a,b,c,d,M[1], 5,0xf61e2562u);  MTL_MD5_GG(d,a,b,c,M[6], 9,0xc040b340u);\n"
    "        MTL_MD5_GG(c,d,a,b,M[11],14,0x265e5a51u); MTL_MD5_GG(b,c,d,a,M[0],20,0xe9b6c7aau);\n"
    "        MTL_MD5_GG(a,b,c,d,M[5], 5,0xd62f105du);  MTL_MD5_GG(d,a,b,c,M[10], 9,0x02441453u);\n"
    "        MTL_MD5_GG(c,d,a,b,M[15],14,0xd8a1e681u); MTL_MD5_GG(b,c,d,a,M[4],20,0xe7d3fbc8u);\n"
    "        MTL_MD5_GG(a,b,c,d,M[9], 5,0x21e1cde6u);  MTL_MD5_GG(d,a,b,c,M[14], 9,0xc33707d6u);\n"
    "        MTL_MD5_GG(c,d,a,b,M[3],14,0xf4d50d87u);  MTL_MD5_GG(b,c,d,a,M[8],20,0x455a14edu);\n"
    "        MTL_MD5_GG(a,b,c,d,M[13], 5,0xa9e3e905u); MTL_MD5_GG(d,a,b,c,M[2], 9,0xfcefa3f8u);\n"
    "        MTL_MD5_GG(c,d,a,b,M[7],14,0x676f02d9u);  MTL_MD5_GG(b,c,d,a,M[12],20,0x8d2a4c8au);\n"
    "        /* Rounds 33-48 (HH) */\n"
    "        MTL_MD5_HH(a,b,c,d,M[5], 4,0xfffa3942u);  MTL_MD5_HH(d,a,b,c,M[8],11,0x8771f681u);\n"
    "        MTL_MD5_HH(c,d,a,b,M[11],16,0x6d9d6122u); MTL_MD5_HH(b,c,d,a,M[14],23,0xfde5380cu);\n"
    "        MTL_MD5_HH(a,b,c,d,M[1], 4,0xa4beea44u);  MTL_MD5_HH(d,a,b,c,M[4],11,0x4bdecfa9u);\n"
    "        MTL_MD5_HH(c,d,a,b,M[7],16,0xf6bb4b60u);  MTL_MD5_HH(b,c,d,a,M[10],23,0xbebfbc70u);\n"
    "        MTL_MD5_HH(a,b,c,d,M[13], 4,0x289b7ec6u); MTL_MD5_HH(d,a,b,c,M[0],11,0xeaa127fau);\n"
    "        MTL_MD5_HH(c,d,a,b,M[3],16,0xd4ef3085u);  MTL_MD5_HH(b,c,d,a,M[6],23,0x04881d05u);\n"
    "        MTL_MD5_HH(a,b,c,d,M[9], 4,0xd9d4d039u);  MTL_MD5_HH(d,a,b,c,M[12],11,0xe6db99e5u);\n"
    "        MTL_MD5_HH(c,d,a,b,M[15],16,0x1fa27cf8u); MTL_MD5_HH(b,c,d,a,M[2],23,0xc4ac5665u);\n"
    "        /* Rounds 49-64 (II) */\n"
    "        MTL_MD5_II(a,b,c,d,M[0], 6,0xf4292244u);  MTL_MD5_II(d,a,b,c,M[7],10,0x432aff97u);\n"
    "        MTL_MD5_II(c,d,a,b,M[14],15,0xab9423a7u); MTL_MD5_II(b,c,d,a,M[5],21,0xfc93a039u);\n"
    "        MTL_MD5_II(a,b,c,d,M[12], 6,0x655b59c3u); MTL_MD5_II(d,a,b,c,M[3],10,0x8f0ccc92u);\n"
    "        MTL_MD5_II(c,d,a,b,M[10],15,0xffeff47du); MTL_MD5_II(b,c,d,a,M[1],21,0x85845dd1u);\n"
    "        MTL_MD5_II(a,b,c,d,M[8], 6,0x6fa87e4fu);  MTL_MD5_II(d,a,b,c,M[15],10,0xfe2ce6e0u);\n"
    "        MTL_MD5_II(c,d,a,b,M[6],15,0xa3014314u);  MTL_MD5_II(b,c,d,a,M[13],21,0x4e0811a1u);\n"
    "        MTL_MD5_II(a,b,c,d,M[4], 6,0xf7537e82u);  MTL_MD5_II(d,a,b,c,M[11],10,0xbd3af235u);\n"
    "        MTL_MD5_II(c,d,a,b,M[2],15,0x2ad7d2bbu);  MTL_MD5_II(b,c,d,a,M[9],21,0xeb86d391u);\n"
    "\n"
    "        /* Add original IV (not pre-rolled state) to round-64 output to\n"
    "         * match md5_block epilogue semantics. */\n"
    "        st.h[0] = 0x67452301u + a;\n"
    "        st.h[1] = 0xEFCDAB89u + b;\n"
    "        st.h[2] = 0x98BADCFEu + c;\n"
    "        st.h[3] = 0x10325476u + d;\n"
    "    } else {\n"
    "        /* Two-block slow path (salt > 23 bytes). Phase 2h-A pre-roll\n"
    "         * skipped here for simplicity — slow path is rare for short-salt\n"
    "         * workloads (sm-saltfull benchmark never triggers it). Falls back\n"
    "         * to the standard md5_block helper for both blocks. */\n"
    "        uint first_chunk = 64u - inner_len;\n"
    "        if (first_chunk > slen) first_chunk = slen;\n"
    "        for (uint i = 0u; i < first_chunk; i++) {\n"
    "            uint pos_byte = inner_len + i;\n"
    "            uint v = (uint)salt_buf[i];\n"
    "            M[pos_byte >> 2] |= v << ((pos_byte & 3) * 8);\n"
    "        }\n"
    "        /* MD5 padding correctness (2026-06-03 fix): see template_finalize\n"
    "         * eom_in_first comment. When first_chunk == slen AND total_len\n"
    "         * ∈ [56..63] the 0x80 EOM marker MUST go into byte total_len of\n"
    "         * block 1 (not byte 0 of block 2). */\n"
    "        uint rem_salt = slen - first_chunk;\n"
    "        uint eom_in_first = (rem_salt == 0u && total_len < 64u) ? 1u : 0u;\n"
    "        if (eom_in_first) {\n"
    "            uint eom_pos = inner_len + first_chunk;\n"
    "            M[eom_pos >> 2] |= (uint)0x80u << ((eom_pos & 3) * 8);\n"
    "        }\n"
    "        st.h[0] = 0x67452301u;\n"
    "        st.h[1] = 0xEFCDAB89u;\n"
    "        st.h[2] = 0x98BADCFEu;\n"
    "        st.h[3] = 0x10325476u;\n"
    "        md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "        for (uint i = 0u; i < rem_salt; i++) {\n"
    "            uint v = (uint)salt_buf[first_chunk + i];\n"
    "            M[i >> 2] |= v << ((i & 3) * 8);\n"
    "        }\n"
    "        if (!eom_in_first) {\n"
    "            M[rem_salt >> 2] |= (uint)0x80u << ((rem_salt & 3) * 8);\n"
    "        }\n"
    "        if (rem_salt < 56u) {\n"
    "            M[14] = total_len * 8u;\n"
    "            md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "        } else {\n"
    "            md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "            for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "            M[14] = total_len * 8u;\n"
    "            md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step (re-hash digest-as-hex32).\n"
    " *\n"
    " * Mirrors metal_md5_core.metal template_iterate (lowercase hex) which\n"
    " * mirrors gpu_md5salt_core.cl line 750 -- HEX_FEEDBACK matches CPU\n"
    " * JOB_MD5SALT iter convention (mdxfind.c default `prmd5` at line 9706).\n"
    " * No per-iter salt re-application -- salt is consumed ONCE in\n"
    " * template_finalize step 3, then the iter loop re-hashes the digest as\n"
    " * hex32 the same way unsalted MD5 does. */\n"
    "static inline void template_iterate(thread template_state &st)\n"
    "{\n"
    "    uint M[16];\n"
    "    md5_to_hex_lc(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "    M[8] = 0x80u;\n"
    "    for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 32u * 8u;     /* 32 hex chars = 256 bits */\n"
    "    M[15] = 0u;\n"
    "    st.h[0] = 0x67452301u;\n"
    "    st.h[1] = 0xEFCDAB89u;\n"
    "    st.h[2] = 0x98BADCFEu;\n"
    "    st.h[3] = 0x10325476u;\n"
    "    md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with state's first\n"
    " * 4 digest words. Identical to metal_md5_core.metal's variant. */\n"
    "static inline int template_digest_compare(\n"
    "    thread const template_state &st,\n"
    "    device const uint  *compact_fp,\n"
    "    device const uint  *compact_idx,\n"
    "    ulong               compact_mask,\n"
    "    uint                max_probe,\n"
    "    uint                hash_data_count,\n"
    "    device const uchar *hash_data_buf,\n"
    "    device const ulong *hash_data_off,\n"
    "    device const ulong *overflow_keys,\n"
    "    device const uchar *overflow_hashes,\n"
    "    device const uint  *overflow_offsets,\n"
    "    uint                overflow_count,\n"
    "    thread uint        *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st.h[0], st.h[1], st.h[2], st.h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit_or_overflow: dedup+overflow-aware hit emit. Wraps\n"
    " * EMIT_HIT_4_DEDUP_OR_OVERFLOW (MD5 = 4 uint32 digest words). Identical\n"
    " * to metal_md5_core.metal's macro -- the hit-record format is the same\n"
    " * (4 digest words after widx + sidx + iter), regardless of whether the\n"
    " * digest came from raw MD5 or MD5SALT. */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits,                       \\\n"
    "                                      st_ref, widx, sidx, iter,                        \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask,           \\\n"
    "                                      ovr_set, ovr_gid, lane_gid)                      \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits),                      \\\n"
    "                                 (widx), (sidx), (iter),                               \\\n"
    "                                 (st_ref).h[0], (st_ref).h[1],                         \\\n"
    "                                 (st_ref).h[2], (st_ref).h[3],                         \\\n"
    "                                 (hashes_shown), (matched_idx), (dedup_mask),          \\\n"
    "                                 (ovr_set), (ovr_gid), (lane_gid))\n"
;
