/* Auto-generated from metal_md5_rules.metal -- do not edit */
static const char metal_md5_rules_str[] =
    "/*\n"
    " * $Revision: 1.1 $\n"
    " * $Log: metal_md5_rules.metal,v $\n"
    " * Revision 1.1  2026/05/12 16:40:56  dlr\n"
    " * Initial check-in: Phase 2a Metal port of the rules-engine walker. Ports apply_rule from gpu_md5_rules.cl (1385 LOC OpenCL twin) to Metal; KERNEL BODY is NOT ported (kernel bodies live in metal_template.metal; main session extends template_phase0 with a GPU_TEMPLATE_HAS_RULES block that calls apply_rule from this TU). All 48 RULE_OP_ opcodes covered (0xc1..0xff range plus variable-length 0xff/0xfe affix ops). Rejection semantics mirror OpenCL twin: ops underscore-LT-GT-bang-slash-paren-paren return -1 to signal lane skip. Pattern 1 (every kernel-arg buffer is device qualified; every lane-local pointer is thread qualified). Pattern 3 (all helpers static inline). Scalar-only port for Phase 2a; vector heads from OpenCL twin (LOWER, UPPER, CAP, CAP_INV, TOGGLE, SUB, DUP, DUP_LAST) deferred to Phase 2c after correctness-proven landing. case_flip_mask helper local to walker (Phase 2c+ may hoist if other family kernels need it). xcrun metal compile clean on iMac AMD Radeon Pro 580X; metal_jit_harness --check-patterns reports 0 violations across the 4-file family TU (metal_common + metal_md5_core + metal_md5_rules + metal_template). 804 LOC including header + helper.\n"
    " *\n"
    " *\n"
    " */\n"
    "/* metal_md5_rules.metal — Phase 2a Metal port of the rules-engine walker.\n"
    " *\n"
    " * Ports the apply_rule() function from gpu/gpu_md5_rules.cl (1385 LOC OpenCL\n"
    " * twin) to Metal. The KERNEL BODY is NOT ported here — kernel bodies live in\n"
    " * metal_template.metal (the unified template_phase0 kernel); main session\n"
    " * extends template_phase0 with a GPU_TEMPLATE_HAS_RULES block that calls\n"
    " * apply_rule() from this TU.\n"
    " *\n"
    " * Phase 2a scope (memo §3 row 2):\n"
    " *   - Single-buffer in-place per-op semantics. apply_rule(prog, buf, len)\n"
    " *     walks the bytecode and mutates buf in place.\n"
    " *   - All 48 RULE_OP_* opcodes from gpu_md5_rules.cl (0xc1..0xff range\n"
    " *     plus the variable-length 0xff/0xfe affix ops).\n"
    " *   - Rejection semantics: ops `_ < > ! / ( )` return -1 to signal lane\n"
    " *     skip (no MD5 + probe).\n"
    " *\n"
    " * Pattern enforcement (memo §12 + Phase 0.5):\n"
    " *   Pattern 1: `prog` is `device const uchar *`, `buf` is `device uchar *`\n"
    " *              (post task #250 scratch-pool migration — see file header §3),\n"
    " *              return value is plain int (lane-private).\n"
    " *   Pattern 3: function is `static inline`. The walker is large enough\n"
    " *              that the compiler may decline to inline; that is fine —\n"
    " *              the keyword still gives the linker a private symbol and\n"
    " *              keeps the kernel TU self-contained.\n"
    " *\n"
    " * Concatenation order (build_metallib.sh per-family):\n"
    " *   metal_common.metal  (MetalParams, md5_block, probe_compact_idx,\n"
    " *                        RULE_BUF_MAX / RULE_BUF_LIMIT, HIT_STRIDE)\n"
    " *   metal_md5_core.metal (template_state, template_init/_finalize/\n"
    " *                         _digest_compare/_emit_hit_or_overflow,\n"
    " *                         template_iterate stub)\n"
    " *   metal_md5_rules.metal (THIS FILE — apply_rule)\n"
    " *   metal_template.metal  (template_phase0 kernel; calls apply_rule\n"
    " *                         inside the GPU_TEMPLATE_HAS_RULES block —\n"
    " *                         extension is main-session scope per memo\n"
    " *                         §3 row 4)\n"
    " *\n"
    " * --- Byte-exactness contract ---\n"
    " *\n"
    " * apply_rule() in this file MUST produce identical output to applyrule()\n"
    " * in ruleproc.c (CPU reference) AND apply_rule() in gpu_md5_rules.cl\n"
    " * (OpenCL twin) for every bytecode sequence the host emits. The walker\n"
    " * is the single source of truth for CPU<->GPU parity on the rules axis.\n"
    " *\n"
    " * Per memo §6 validation gate 2a-1: byte-exact parity check is `-M e1\n"
    " * -r best64.rule rockyou-1k.txt against 1k-hash compact` — hit count +\n"
    " * sorted hit md5sum must be identical CPU/Metal.\n"
    " *\n"
    " * --- Differences from OpenCL twin ---\n"
    " *\n"
    " *   1. Address space: __global -> device, __private -> thread.\n"
    " *      Every `__global const uchar *prog` becomes `device const uchar *prog`;\n"
    " *      `uchar *buf` (implicit __private in OpenCL) becomes `device uchar *buf`\n"
    " *      since task #250 — see file header §3. The OpenCL twin keeps buf in\n"
    " *      __private because OpenCL drivers spill private memory to global\n"
    " *      transparently; Apple Metal does NOT spill — a 40 KB thread-local\n"
    " *      array consumes registers + temporary-register budget, and on M2\n"
    " *      Max blows the PSO-create register-allocator gate. Moving to\n"
    " *      `device uchar *buf` keeps RULE_BUF_MAX at 40 KB without truncation.\n"
    " *      The `len` parameter is plain int (pass-by-value).\n"
    " *\n"
    " *   2. Vector intrinsics: OpenCL uses uchar16 / vload16 / vstore16 / select\n"
    " *      for vectorized case ops (LOWER, UPPER, CAP, CAP_INV, TOGGLE, SUB,\n"
    " *      DUP, DUP_LAST). Metal has uchar16, vload, vstore equivalents but\n"
    " *      via different syntax. For Phase 2a we use the SCALAR fallback path\n"
    " *      from the OpenCL twin (each case op has a scalar inner loop after\n"
    " *      the vector head — Phase 2c may add vector fast-paths after JIT\n"
    " *      harness Pattern 1+3 selftest verifies them).\n"
    " *\n"
    " *      Rationale: byte-exact parity must land first. The scalar loops in\n"
    " *      the OpenCL twin are correctness-proven against ruleproc.c\n"
    " *      applyrule(); the vector heads are a perf optimization on top.\n"
    " *      Phase 2a takes correctness; Phase 2c+ adds the vector heads if\n"
    " *      profiling shows we need them.\n"
    " *\n"
    " *   3. select(): OpenCL's `select(a, b, c)` -> Metal's `(c ? b : a)` (or\n"
    " *      `select(a, b, c)` if Metal has the function — checked metal3.0;\n"
    " *      yes it does, same arg order as OpenCL). The retired Phase 0\n"
    " *      design used Metal's select() directly; Phase 2a keeps the\n"
    " *      explicit ternary form everywhere for clarity (the OpenCL twin\n"
    " *      already noted the select() MSB-predicate gotcha and uses ternaries\n"
    " *      for the same reason — we mirror that choice).\n"
    " *\n"
    " *   4. case_flip_mask: identical between OpenCL and Metal. Defined here\n"
    " *      (NOT in metal_common.metal) because the walker is the only caller\n"
    " *      Phase 2a — Phase 2c+ may hoist it if other family kernels start\n"
    " *      using it.\n"
    " */\n"
    "\n"
    "/* ==== Opcode definitions (must match ruleproc.c RULE_OP_* + gpu_md5_rules.cl) ==== */\n"
    "#define RULE_OP_INSERT      0xfd\n"
    "#define RULE_OP_OVERWRITE   0xfc\n"
    "#define RULE_OP_TOGGLE_AT   0xfb\n"
    "#define RULE_OP_INC         0xfa\n"
    "#define RULE_OP_DEC         0xf9\n"
    "#define RULE_OP_TRUNC       0xf8\n"
    "#define RULE_OP_DROP_LAST   0xf7\n"
    "#define RULE_OP_SUB         0xf6\n"
    "#define RULE_OP_LOWER       0xf5\n"
    "#define RULE_OP_UPPER       0xf4\n"
    "#define RULE_OP_CAP         0xf3\n"
    "#define RULE_OP_CAP_INV     0xf2\n"
    "#define RULE_OP_REVERSE     0xf1\n"
    "#define RULE_OP_TOGGLE      0xf0\n"
    "#define RULE_OP_TITLE_SP    0xef\n"
    "#define RULE_OP_TITLE_SEP   0xee\n"
    "#define RULE_OP_DUP         0xed\n"
    "#define RULE_OP_REFLECT     0xec\n"
    "#define RULE_OP_DUP_EACH    0xeb\n"
    "#define RULE_OP_ROT_L       0xea\n"
    "#define RULE_OP_ROT_R       0xe9\n"
    "#define RULE_OP_SWAP_FRONT  0xe8\n"
    "#define RULE_OP_SWAP_BACK   0xe7\n"
    "#define RULE_OP_DROP_FIRST  0xe6\n"
    "#define RULE_OP_APPEND      0xe5\n"
    "#define RULE_OP_PREPEND     0xe4\n"
    "#define RULE_OP_DEL_AT      0xe3\n"
    "#define RULE_OP_BIT_SHL     0xe2\n"
    "#define RULE_OP_BIT_SHR     0xe1\n"
    "#define RULE_OP_REPL_NEXT   0xe0\n"
    "#define RULE_OP_REPL_PREV   0xdf\n"
    "#define RULE_OP_PURGE       0xde\n"
    "#define RULE_OP_DUP_LAST    0xdd\n"
    "#define RULE_OP_DUP_FIRST   0xdc\n"
    "#define RULE_OP_REPEAT      0xdb\n"
    "#define RULE_OP_DUP_PREFIX  0xda\n"
    "#define RULE_OP_DUP_SUFFIX  0xd9\n"
    "#define RULE_OP_SWAP_AT     0xd8\n"
    "#define RULE_OP_EXTRACT     0xd7\n"
    "#define RULE_OP_OMIT        0xd6\n"
    "#define RULE_OP_TOGGLE_SEP  0xd5\n"
    "#define RULE_OP_NOOP        0xd4\n"
    "#define RULE_OP_NOOP_SP     0xd3\n"
    "#define RULE_OP_NOOP_TAB    0xd2\n"
    "#define RULE_OP_MEM_STORE   0xd1\n"
    "#define RULE_OP_MEM_APP     0xd0\n"
    "#define RULE_OP_MEM_PRE     0xcf\n"
    "#define RULE_OP_MEM_REJ     0xce\n"
    "#define RULE_OP_MEM_INSERT  0xcd\n"
    "#define RULE_OP_REJ_LEN_NE  0xcc\n"
    "#define RULE_OP_REJ_LEN_GE  0xcb\n"
    "#define RULE_OP_REJ_LEN_LE  0xca\n"
    "#define RULE_OP_REJ_HAS     0xc9\n"
    "#define RULE_OP_REJ_NHAS    0xc8\n"
    "#define RULE_OP_REJ_FIRST   0xc7\n"
    "#define RULE_OP_REJ_LAST    0xc6\n"
    "#define RULE_OP_S_SPECIAL   0xc5\n"
    "#define RULE_OP_HASH_EXIT   0xc4\n"
    "#define RULE_OP_HEX_UPPER   0xc3\n"
    "#define RULE_OP_HEX_LOWER   0xc2\n"
    "#define RULE_OP_DIV_INSERT  0xc1\n"
    "#define RULE_OP_CHR_ADD     0xc0\n"
    "\n"
    "/* RULE_BUF_MAX / RULE_BUF_LIMIT live in metal_common.metal (~line 92);\n"
    " * we reference, not redefine. Mirrors OpenCL gpu_md5_rules.cl which also\n"
    " * pulls these from gpu_common.cl. */\n"
    "\n"
    "/* ==== Branchless case-flip helper ====================================\n"
    " *\n"
    " * case_flip_mask(c) returns 0x20 if `c` is alphabetic (A-Z or a-z),\n"
    " * else 0. Uses the unsigned-subtract trick: `(c | 0x20) - 'a' < 26u`.\n"
    " * The OR lifts uppercase into lowercase territory (or leaves lowercase\n"
    " * unchanged); the unsigned compare is true only for 'a'..'z'.\n"
    " *\n"
    " * Robust across the entire 0x00..0xff input space (mirrors gpu_md5_-\n"
    " * rules.cl rev 1.30 helper at line 149).\n"
    " *\n"
    " * Cast the subtraction result back to uchar so the unsigned wrap kicks\n"
    " * in — Metal promotes uchar to int in expressions same as OpenCL.\n"
    " */\n"
    "static inline uchar case_flip_mask(uchar c) {\n"
    "    uchar v = (uchar)((c | (uchar)0x20) - (uchar)'a');\n"
    "    return (uchar)((v < (uchar)26) ? 0x20 : 0);\n"
    "}\n"
    "\n"
    "/* ==== Unified single-buffer in-place rule walker =====================\n"
    " *\n"
    " * apply_rule:\n"
    " *   - prog: device pointer to NUL-terminated bytecode (offset already\n"
    " *           applied by caller; first byte is the first opcode).\n"
    " *   - buf:  device uchar slice of size RULE_BUF_MAX (task #250 scratch\n"
    " *           pool — gpu_metal.m buf_scratch_pool, indexed by word_idx).\n"
    " *           Pre-staged with the input word in buf[0..len-1].\n"
    " *   - len:  initial length of the staged input.\n"
    " * Returns: post-rule length (>= 0) on success, -1 if a rejection op fires.\n"
    " *          The buffer is modified in place.\n"
    " *\n"
    " * Rejection semantics mirror the OpenCL twin (rev 1.30 line 167):\n"
    " * ops `_ < > ! / ( )` return -1; the caller (template_phase0 in\n"
    " * metal_template.metal) must skip MD5+probe.\n"
    " *\n"
    " * The `_` op tests length-not-equal against the ORIGINAL input length\n"
    " * (the `len` parameter at function entry), NOT the running len. We\n"
    " * capture orig_len at entry to match applyrule byte-exact.\n"
    " *\n"
    " * The outer loop bound `for (int n = 0; n < 256; ...)` mirrors the\n"
    " * OpenCL twin: matches the per-rule opcode cap that ruleproc.c emits.\n"
    " */\n"
    "static int apply_rule(device const uchar *prog, device uchar *buf, int len)\n"
    "{\n"
    "    int k = 0;\n"
    "    /* ---- memory family: M 4 6 Q X (GPU-enabled 2026-09-11) ------------\n"
    "     * Per-call scratch, matching ruleproc.c exactly: applyrule() sets\n"
    "     * memlen = 0 at the top of EVERY call, so memory state never crosses a\n"
    "     * (word, rule) boundary.  That is what makes these ops portable to a\n"
    "     * walker where each work-item is independent -- there is no cross-rule\n"
    "     * state to reproduce.\n"
    "     *\n"
    "     * A second RULE_BUF_MAX buffer used to be unaffordable: at 40960 bytes it\n"
    "     * doubled per-thread private memory and FATAL'd CL_OUT_OF_HOST_MEMORY on\n"
    "     * an RTX 3080 (mdxfind.c rev 1.24 attempt, reverted).  At 2048 it is 4 KB\n"
    "     * per thread for both buffers together, a tenth of what one buffer cost\n"
    "     * before, which is why the operator reopened this. */\n"
    "    thread uchar mem[RULE_BUF_MAX];\n"
    "    int          memlen = 0;\n"
    "    int orig_len = len;     /* preserved for the `_ N` length-equal test */\n"
    "\n"
    "    for (int n = 0; n < 256; n++) {\n"
    "        uchar op = prog[k];\n"
    "        if (op == 0) break;\n"
    "\n"
    "        /* Main switch — contiguous high-bit opcodes 0xc1..0xff.\n"
    "         * 0xff/0xfe are variable-length (op + N + N data bytes); the rest\n"
    "         * are fixed-size. Scalar-only port for Phase 2a; vector heads from\n"
    "         * the OpenCL twin (LOWER, UPPER, CAP, CAP_INV, TOGGLE, SUB, DUP,\n"
    "         * DUP_LAST) are deferred — see file header §3 (scalar paths are\n"
    "         * correctness-proven). */\n"
    "        switch (op) {\n"
    "\n"
    "            /* ---- Variable-length affix ops (0xff / 0xfe) ---- */\n"
    "            case 0xff: {\n"
    "                /* Multi-char append: 2 + N bytes, N data bytes follow N-byte. */\n"
    "                int N = (int)prog[k + 1];\n"
    "                int n_copy = N;\n"
    "                if (len + n_copy > RULE_BUF_LIMIT) n_copy = RULE_BUF_LIMIT - len;\n"
    "                if (n_copy < 0) n_copy = 0;\n"
    "                for (int j = 0; j < n_copy; j++) {\n"
    "                    buf[len + j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += n_copy;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "            case 0xfe: {\n"
    "                /* Multi-char prepend: shift right by N, then write N data\n"
    "                 * bytes at buf[0..N-1]. */\n"
    "                int N = (int)prog[k + 1];\n"
    "                int new_pre = N;\n"
    "                if (len + new_pre > RULE_BUF_LIMIT) new_pre = RULE_BUF_LIMIT - len;\n"
    "                if (new_pre < 0) new_pre = 0;\n"
    "                /* Shift right (work backward to avoid overwrite). */\n"
    "                for (int j = len - 1; j >= 0; j--) {\n"
    "                    int dst = j + new_pre;\n"
    "                    if (dst <= RULE_BUF_LIMIT) buf[dst] = buf[j];\n"
    "                }\n"
    "                for (int j = 0; j < new_pre; j++) {\n"
    "                    buf[j] = prog[k + 2 + j];\n"
    "                }\n"
    "                len += new_pre;\n"
    "                k += 2 + N;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Top-frequency: insert / overwrite / toggle ---- */\n"
    "            case RULE_OP_INSERT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                /* pos <= len: inserting at position == length is an APPEND,\n"
    "                 * which john and hashcat 6.2.5 both do. */\n"
    "                if (pos >= 0 && pos <= len && len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > pos; j--) buf[j] = buf[j - 1];\n"
    "                    buf[pos] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OVERWRITE: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar ch = prog[k + 2];\n"
    "                if (pos >= 0 && pos < len) buf[pos] = ch;\n"
    "                if (pos == 0 && len == 0) { buf[0] = ch; len++; }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_AT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    buf[pos] ^= case_flip_mask(buf[pos]);\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position arithmetic ---- */\n"
    "            /* hashcat `BNX`: add the byte value of X to the byte at\n"
    "             * position N, wrapping.  No-op out of range, matching\n"
    "             * hashcat's mangle_chr_add() and ruleproc.c.  Branchless,\n"
    "             * in the style of RULE_OP_INC below. */\n"
    "            case RULE_OP_CHR_ADD: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                uchar add = prog[k + 2];\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] + (valid ? add : (uchar)0));\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_INC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] + (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DEC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int valid = ((pos >= 0) & (pos < len));\n"
    "                int safe_pos = valid ? pos : 0;\n"
    "                buf[safe_pos] = (uchar)(buf[safe_pos] - (uchar)valid);\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Length-shrink ---- */\n"
    "            case RULE_OP_TRUNC: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                len = (pos < len) ? pos : len;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DROP_LAST: {\n"
    "                len -= (len > 0);\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Substitute (scalar; OpenCL twin has uchar16 head) ---- */\n"
    "            case RULE_OP_SUB: {\n"
    "                uchar c1 = prog[k + 1], c2 = prog[k + 2];\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c1) buf[j] = c2;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-string case ops (scalar) ---- */\n"
    "            case RULE_OP_LOWER: {\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_UPPER: {\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP: {\n"
    "                /* Capitalize: lowercase all, then upper-case the first\n"
    "                 * lowercase letter. Matches ruleproc.c. */\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                /* john and hashcat both act on POSITION 0, not on the\n"
    "                 * first alphabetic character: `c` on \"!bang\" gives \"!bang\"\n"
    "                 * in both, where the find-first form gave \"!Bang\".  Mirrors\n"
    "                 * ruleproc.c. */\n"
    "                if (len > 0) {\n"
    "                    uchar c = buf[0];\n"
    "                    if (c >= 'a' && c <= 'z') buf[0] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_CAP_INV: {\n"
    "                /* Anti-capitalize: uppercase all, then lower-case first\n"
    "                 * uppercase letter. */\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                /* john and hashcat both act on POSITION 0, not on the\n"
    "                 * first alphabetic character: `c` on \"!bang\" gives \"!bang\"\n"
    "                 * in both, where the find-first form gave \"!Bang\".  Mirrors\n"
    "                 * ruleproc.c. */\n"
    "                if (len > 0) {\n"
    "                    uchar c = buf[0];\n"
    "                    if (c >= 'A' && c <= 'Z') buf[0] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REVERSE: {\n"
    "                int i = 0, j = len - 1;\n"
    "                while (i < j) {\n"
    "                    uchar t = buf[i];\n"
    "                    buf[i] = buf[j];\n"
    "                    buf[j] = t;\n"
    "                    i++;\n"
    "                    j--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE: {\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                        buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Title-case ---- */\n"
    "            case RULE_OP_TITLE_SP: {\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    /* An already-uppercase letter at a word start IS the\n"
    "                     * capital: keep it and mark the word started.  The old\n"
    "                     * form left z at 0 so the NEXT lowercase letter was\n"
    "                     * capitalised -- Hello1 became hEllo1. */\n"
    "                    /* Word start is POSITIONAL: the first character after a\n"
    "                     * separator, or position 0, whether or not it is a letter.\n"
    "                     * The old form only consumed the word start when it SAW a\n"
    "                     * letter, so \"!bang\" gave \"!Bang\" where john and hashcat\n"
    "                     * both give \"!bang\".  Mirrors ruleproc.c. */\n"
    "                    if (c == ' ') { z = 0; continue; }\n"
    "                    if (z == 0) { z = 1; if (c >= 'a' && c <= 'z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else { if (c >= 'A' && c <= 'Z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_SEP: {\n"
    "                uchar delim = prog[k + 1];\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    /* Word start is POSITIONAL: the first character after a\n"
    "                     * separator, or position 0, whether or not it is a letter.\n"
    "                     * The old form only consumed the word start when it SAW a\n"
    "                     * letter, so \"!bang\" gave \"!Bang\" where john and hashcat\n"
    "                     * both give \"!bang\".  Mirrors ruleproc.c. */\n"
    "                    if (c == delim) { z = 0; continue; }\n"
    "                    if (z == 0) { z = 1; if (c >= 'a' && c <= 'z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                    else { if (c >= 'A' && c <= 'Z') buf[j] = c ^ case_flip_mask(c); }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Whole-buffer length-grow ops ---- */\n"
    "            case RULE_OP_DUP: {\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = 0; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REFLECT: {\n"
    "                int tlen = len;\n"
    "                if (len + tlen <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = 0; j < tlen; j++)\n"
    "                        buf[len + tlen - 1 - j] = buf[j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_EACH: {\n"
    "                /* \"abc\" -> \"aabbcc\"; length doubles. Work from the end so\n"
    "                 * we don't overwrite source bytes still being read. */\n"
    "                int tlen = len;\n"
    "                if (tlen * 2 <= RULE_BUF_LIMIT && tlen > 0) {\n"
    "                    for (int j = tlen - 1; j >= 0; j--) {\n"
    "                        uchar c = buf[j];\n"
    "                        buf[j * 2]     = c;\n"
    "                        buf[j * 2 + 1] = c;\n"
    "                    }\n"
    "                    len = tlen * 2;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Rotation / swap ---- */\n"
    "            case RULE_OP_ROT_L: {\n"
    "                if (len > 0) {\n"
    "                    uchar first = buf[0];\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    buf[len - 1] = first;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_ROT_R: {\n"
    "                if (len > 0) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = last;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_FRONT: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[0]; buf[0] = buf[1]; buf[1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_SWAP_BACK: {\n"
    "                if (len > 1) {\n"
    "                    uchar t = buf[len - 2];\n"
    "                    buf[len - 2] = buf[len - 1];\n"
    "                    buf[len - 1] = t;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Drop first / append / prepend ---- */\n"
    "            case RULE_OP_DROP_FIRST: {\n"
    "                if (len > 0) {\n"
    "                    for (int j = 0; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_APPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) buf[len++] = ch;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_PREPEND: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                if (len < RULE_BUF_LIMIT) {\n"
    "                    for (int j = len; j > 0; j--) buf[j] = buf[j - 1];\n"
    "                    buf[0] = ch;\n"
    "                    len++;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            case RULE_OP_DEL_AT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    for (int j = pos; j < len - 1; j++) buf[j] = buf[j + 1];\n"
    "                    len--;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Per-position bit shifts / nearest-neighbor copy ---- */\n"
    "            case RULE_OP_BIT_SHL: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] << 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_BIT_SHR: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) buf[pos] = buf[pos] >> 1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_NEXT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos >= 0 && pos < len) {\n"
    "                    /* NO-OP when pos+1 is out of range, matching hashcat and\n"
    "                     * ruleproc.c: `hashcat --stdout` on abcdefghij gives\n"
    "                     * abcdefghjj for `.8` and abcdefghij unchanged for `.9`.\n"
    "                     * This wrote (uchar)0 instead, embedding a NUL in the\n"
    "                     * candidate -- a third answer again, different from both\n"
    "                     * the CPU engine's one-past-the-end read and hashcat's\n"
    "                     * no-op, so CPU and GPU hit sets could disagree on any\n"
    "                     * rule using `.` at the last position. */\n"
    "                    if (pos + 1 < len) buf[pos] = buf[pos + 1];\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPL_PREV: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                if (pos > 0 && pos < len) buf[pos] = buf[pos - 1];\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Purge ---- */\n"
    "            case RULE_OP_PURGE: {\n"
    "                uchar ch = prog[k + 1];\n"
    "                int w = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] != ch) buf[w++] = buf[j];\n"
    "                }\n"
    "                len = w;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Last/first-char duplicators ---- */\n"
    "            case RULE_OP_DUP_LAST: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar last = buf[len - 1];\n"
    "                    for (int j = 0; j < n2; j++) buf[len + j] = last;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_FIRST: {\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    uchar first = buf[0];\n"
    "                    /* Shift right by n2 (mirror OpenCL twin's loop). */\n"
    "                    for (int j = len - 1; j > 0; j--) buf[j + n2] = buf[j];\n"
    "                    /* buf[0] preserved (it's the source we copy from);\n"
    "                     * fill buf[1..n2] with first. */\n"
    "                    for (int j = 1; j <= n2; j++) buf[j] = first;\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REPEAT: {\n"
    "                /* p N: append N copies of input to itself. */\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                int tlen = len;\n"
    "                if (tlen > 0 && n2 > 0) {\n"
    "                    for (int copy = 0; copy < n2; copy++) {\n"
    "                        if (len + tlen > RULE_BUF_LIMIT) break;\n"
    "                        for (int j = 0; j < tlen; j++) buf[len + j] = buf[j];\n"
    "                        len += tlen;\n"
    "                    }\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_PREFIX: {\n"
    "                /* y N: duplicate first N chars at the start. */\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    for (int j = len - 1; j >= 0; j--) buf[j + n2] = buf[j];\n"
    "                    for (int j = 0; j < n2; j++) buf[j] = buf[j + n2];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_DUP_SUFFIX: {\n"
    "                /* Y N: duplicate last N chars at the end. */\n"
    "                int n2 = (int)prog[k + 1] - 1;\n"
    "                if (len > 0 && n2 > 0 && n2 <= len && len + n2 <= RULE_BUF_LIMIT) {\n"
    "                    for (int j = 0; j < n2; j++) buf[len + j] = buf[len - n2 + j];\n"
    "                    len += n2;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- Position-paired ops ---- */\n"
    "            case RULE_OP_SWAP_AT: {\n"
    "                int posA = (int)prog[k + 1] - 1;\n"
    "                int posB = (int)prog[k + 2] - 1;\n"
    "                if (posA >= 0 && posA < len && posB >= 0 && posB < len) {\n"
    "                    uchar t = buf[posA]; buf[posA] = buf[posB]; buf[posB] = t;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- character classes (0x80-0x89) and =NX / %NX ----------\n"
    "             * Mirrors ruleproc.c's class arms exactly.  The 480-byte\n"
    "             * membership table and rule_class_match() live in the COMMON\n"
    "             * source, in the constant address space -- deliberately not a\n"
    "             * function-local array, which is what put the retired memory-op\n"
    "             * attempt over the per-thread private-memory budget.\n"
    "             *\n"
    "             * Promoting these off the CPU-only list is the point: every\n"
    "             * character-class rule used to force a mixed GPU/CPU partition,\n"
    "             * and a partitioned run has to union two result sets.\n"
    "             */\n"
    "            case RULE_OP_SUB_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                uchar y  = prog[k + 2];\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) buf[j] = y;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_PURGE_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                int d = 0;\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (!rule_class_match(cb, buf[j])) buf[d++] = buf[j];\n"
    "                len = d;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_CLASS: {\n"
    "                /* john's e?C: positional word start, separator untouched. */\n"
    "                uchar cb = prog[k + 1];\n"
    "                int z = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (rule_class_match(cb, c)) { z = 0; continue; }\n"
    "                    if (z == 0) {\n"
    "                        z = 1;\n"
    "                        if (c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                    } else {\n"
    "                        if (c >= 'A' && c <= 'Z') buf[j] = c ^ (uchar)0x20;\n"
    "                    }\n"
    "                }\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_TITLE_CLASS_HC: {\n"
    "                /* hashcat's ~e?C is a DIFFERENT algorithm from john's e?C\n"
    "                 * above: it lowercases every position, uppercases position 0\n"
    "                 * and every position whose PREDECESSOR was in the class, and\n"
    "                 * case-normalises the separator itself.  The class test reads\n"
    "                 * the pre-modification byte. */\n"
    "                uchar cb = prog[k + 1];\n"
    "                int up = 1;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    int this_up = up;\n"
    "                    up = rule_class_match(cb, c) ? 1 : 0;\n"
    "                    if (c >= 'A' && c <= 'Z') { c ^= (uchar)0x20; buf[j] = c; }\n"
    "                    if (this_up && c >= 'a' && c <= 'z') buf[j] = c ^ (uchar)0x20;\n"
    "                }\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_HAS_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_NHAS_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                int found = 0;\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) { found = 1; break; }\n"
    "                if (!found) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_FIRST_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                if (len > 0 && !rule_class_match(cb, buf[0])) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LAST_CLASS: {\n"
    "                uchar cb = prog[k + 1];\n"
    "                if (len > 0 && !rule_class_match(cb, buf[len - 1])) return -1;\n"
    "                k += 2; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_AT_CLASS: {\n"
    "                int   y  = (int)prog[k + 1] - 1;\n"
    "                uchar cb = prog[k + 2];\n"
    "                if (y >= len || !rule_class_match(cb, buf[y])) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_CNT_CLASS: {\n"
    "                int   y  = (int)prog[k + 1] - 1;\n"
    "                uchar cb = prog[k + 2];\n"
    "                int cnt = 0;\n"
    "                for (int j = 0; j < len; j++)\n"
    "                    if (rule_class_match(cb, buf[j])) cnt++;\n"
    "                if (cnt < y) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_AT_CHR: {\n"
    "                /* `=NX` reject unless the character at position N is X. */\n"
    "                int   y = (int)prog[k + 1] - 1;\n"
    "                uchar c = prog[k + 2];\n"
    "                if (y >= len || buf[y] != c) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "            case RULE_OP_REJ_CNT_CHR: {\n"
    "                /* `%NX` reject unless X occurs at least N times. */\n"
    "                int   y = (int)prog[k + 1] - 1;\n"
    "                uchar c = prog[k + 2];\n"
    "                int cnt = 0;\n"
    "                for (int j = 0; j < len; j++) if (buf[j] == c) cnt++;\n"
    "                if (cnt < y) return -1;\n"
    "                k += 3; break;\n"
    "            }\n"
    "\n"
    "            /* ---- memory family, mirroring ruleproc.c's SLOW path ---------\n"
    "             * The CPU fast path escapes to slowrule on overflow; the slow\n"
    "             * path CLAMPS (y = MAXLINE - clen) rather than skipping, and that\n"
    "             * is the behaviour with a real limit, so it is what we mirror at\n"
    "             * RULE_BUF_LIMIT.  `6` prepends by memmove-right-then-copy\n"
    "             * because a GPU buffer has no headroom before index 0, where the\n"
    "             * CPU walks cpass backwards into its 512-byte slack. */\n"
    "            case RULE_OP_MEM_STORE: {          /* M -- store candidate */\n"
    "                for (int j = 0; j < len; j++) mem[j] = buf[j];\n"
    "                memlen = len;\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_APP: {            /* 4 -- append memory */\n"
    "                int y = memlen;\n"
    "                if (len + y > RULE_BUF_LIMIT) y = RULE_BUF_LIMIT - len;\n"
    "                if (y < 0) y = 0;\n"
    "                if (y > 0) {\n"
    "                    for (int j = 0; j < y; j++) buf[len + j] = mem[j];\n"
    "                    len += y;\n"
    "                }\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_PRE: {            /* 6 -- prepend memory */\n"
    "                int y = memlen;\n"
    "                if (len + y > RULE_BUF_LIMIT) y = RULE_BUF_LIMIT - len;\n"
    "                if (y < 0) y = 0;\n"
    "                if (y > 0) {\n"
    "                    for (int j = len - 1; j >= 0; j--) buf[j + y] = buf[j];\n"
    "                    for (int j = 0; j < y; j++) buf[j] = mem[j];\n"
    "                    len += y;\n"
    "                }\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_REJ: {            /* Q -- reject if == memory */\n"
    "                if (memlen == len) {\n"
    "                    int same = 1;\n"
    "                    for (int j = 0; j < len; j++) {\n"
    "                        if (buf[j] != mem[j]) { same = 0; break; }\n"
    "                    }\n"
    "                    if (same) return -1;\n"
    "                }\n"
    "                k += 1; break;\n"
    "            }\n"
    "            case RULE_OP_MEM_INSERT: {         /* X N M I */\n"
    "                /* Insert M chars of memory from OFFSET N at position I.\n"
    "                 * Out-of-range REJECTS, following hashcat's\n"
    "                 * mangle_insert_multi -- operator ruling 2026-09-11, and\n"
    "                 * identical to the CPU arm. */\n"
    "                int y    = (int)prog[k + 1] - 1;   /* offset within memory */\n"
    "                int tlen = (int)prog[k + 2] - 1;   /* count              */\n"
    "                int z    = (int)prog[k + 3] - 1;   /* insert position    */\n"
    "                if (memlen < 1 || tlen < 1 || z > len ||\n"
    "                    y > memlen || (y + tlen) > memlen) return -1;\n"
    "                if (len + tlen > RULE_BUF_LIMIT) tlen = RULE_BUF_LIMIT - len;\n"
    "                if (tlen > 0) {\n"
    "                    for (int j = len; j >= z; j--) buf[j + tlen] = buf[j];\n"
    "                    for (int j = 0; j < tlen; j++) buf[z + j] = mem[y + j];\n"
    "                    len += tlen;\n"
    "                }\n"
    "                k += 4; break;\n"
    "            }\n"
    "            case RULE_OP_EXTRACT: {\n"
    "                /* xAB: extract B characters from position A.  Mirrors\n"
    "                 * ruleproc.c, which follows HASHCAT here (operator ruling\n"
    "                 * 2026-09-11, superseding an earlier ruling for john).\n"
    "                 * hashcat's mangle_extract() no-ops on BOTH out-of-range\n"
    "                 * conditions and never extracts a partial run:\n"
    "                 *     if (upos >= arr_len)         return arr_len;\n"
    "                 *     if ((upos + ulen) > arr_len) return arr_len;\n"
    "                 * On \"abc\": x22 and x23 are \"abc\" here and \"c\" in john;\n"
    "                 * x90 is \"abc\" here and a reject in john.  A zero count\n"
    "                 * with an in-range start yields an EMPTY candidate, which\n"
    "                 * is kept -- john's empty-word rejection was also ruled to\n"
    "                 * hashcat.  start==0 self-copies, as on the CPU. */\n"
    "                int start = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (start >= 0 && start < len && (start + count) <= len) {\n"
    "                    for (int q = 0; q < count; q++) {\n"
    "                        buf[q] = buf[start + q];\n"
    "                    }\n"
    "                    len = count;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_OMIT: {\n"
    "                int pos = (int)prog[k + 1] - 1;\n"
    "                int count = (int)prog[k + 2] - 1;\n"
    "                if (pos >= 0 && pos < len && count > 0 && pos + count <= len) {\n"
    "                    for (int j = pos; j + count < len; j++) buf[j] = buf[j + count];\n"
    "                    len -= count;\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_TOGGLE_SEP: {\n"
    "                int upos = (int)prog[k + 1] - 1;\n"
    "                uchar sep = prog[k + 2];\n"
    "                int toggle_next = 0;\n"
    "                int occurrence = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    uchar c = buf[j];\n"
    "                    if (c == sep) {\n"
    "                        if (occurrence == upos) toggle_next = 1;\n"
    "                        else occurrence++;\n"
    "                        continue;\n"
    "                    }\n"
    "                    if (toggle_next) {\n"
    "                        if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))\n"
    "                            buf[j] = c ^ case_flip_mask(c);\n"
    "                        break;\n"
    "                    }\n"
    "                }\n"
    "                k += 3;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- No-ops ---- */\n"
    "            case RULE_OP_NOOP:\n"
    "            case RULE_OP_NOOP_SP:\n"
    "            case RULE_OP_NOOP_TAB:\n"
    "                k += 1;\n"
    "                break;\n"
    "\n"
    "            /* ---- Special ops (silent no-ops) ---- */\n"
    "            case RULE_OP_S_SPECIAL:  k += 1; break;\n"
    "            case RULE_OP_HASH_EXIT:  k += 1; break;\n"
    "            case RULE_OP_DIV_INSERT: k += 3; break;\n"
    "\n"
    "            /* ---- Rejection ops ---- */\n"
    "            case RULE_OP_REJ_LEN_NE: {\n"
    "                /* `_ N`: reject if orig_len != (arg - 1). */\n"
    "                /* CURRENT length, not the original word's. */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (y != len) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_GE: {\n"
    "                /* `< N`: reject if len < (arg - 1). */\n"
    "                /* john: \"<N reject unless less than N chars\" -- reject when\n"
    "                 * len >= N.  This was the complement, matching ruleproc.c's\n"
    "                 * old behaviour; both fixed together so CPU and GPU agree. */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len >= y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LEN_LE: {\n"
    "                /* `> N`: reject if len > (arg - 1). */\n"
    "                /* john: \">N reject unless greater than N chars\". */\n"
    "                int y = (int)prog[k + 1] - 1;\n"
    "                if (len <= y) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_HAS: {\n"
    "                /* `! X`: reject if buf contains X. */\n"
    "                uchar c = prog[k + 1];\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) return -1;\n"
    "                }\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_NHAS: {\n"
    "                /* `/ X`: reject if buf does NOT contain X. */\n"
    "                uchar c = prog[k + 1];\n"
    "                int found = 0;\n"
    "                for (int j = 0; j < len; j++) {\n"
    "                    if (buf[j] == c) { found = 1; break; }\n"
    "                }\n"
    "                if (!found) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_FIRST: {\n"
    "                /* `( X`: reject if (len > 0 && buf[0] != X). */\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[0] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_REJ_LAST: {\n"
    "                /* `) X`: reject if (len > 0 && buf[len-1] != X). */\n"
    "                uchar c = prog[k + 1];\n"
    "                if (len > 0 && buf[len - 1] != c) return -1;\n"
    "                k += 2;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            /* ---- H/h hex emit ---- */\n"
    "            case RULE_OP_HEX_UPPER: {\n"
    "                /* Mirror OpenCL twin's per-case private table (rev 1.27;\n"
    "                 * AMD ROCm bitcode-linker issue is OpenCL-specific, but\n"
    "                 * we keep the same split-cases structure for parity). */\n"
    "                const uchar uhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','A','B','C','D','E','F'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = uhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = uhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "            case RULE_OP_HEX_LOWER: {\n"
    "                const uchar lhex[16] = {\n"
    "                    '0','1','2','3','4','5','6','7',\n"
    "                    '8','9','a','b','c','d','e','f'\n"
    "                };\n"
    "                int x = len;\n"
    "                if (x + len > RULE_BUF_LIMIT) x = RULE_BUF_LIMIT - len;\n"
    "                if (x < 0) x = 0;\n"
    "                int new_len = len + x;\n"
    "                for (int i = x - 1; i >= 0; i--) {\n"
    "                    uchar c = buf[i];\n"
    "                    buf[i * 2]     = lhex[(c >> 4) & 0xf];\n"
    "                    buf[i * 2 + 1] = lhex[c & 0xf];\n"
    "                }\n"
    "                len = new_len;\n"
    "                k += 1;\n"
    "                break;\n"
    "            }\n"
    "\n"
    "            default:\n"
    "                /* Unknown opcode — bail to avoid runaway walk. Mirrors\n"
    "                 * OpenCL twin: returns len (NOT -1; rejection is reserved\n"
    "                 * for known rejection-class opcodes). */\n"
    "                return len;\n"
    "        }\n"
    "    }\n"
    "    return len;\n"
    "}\n"
;
