/*
 * $Revision: $
 * $Log: $
 *
 * Auto-generated by gpu/codegen/cl2metal.py from
 *   gpu_md4utf16_core.cl (RCS rev 1.4).
 *
 * Do NOT edit this file directly -- edit the OpenCL twin and
 * re-run cl2metal.py. The translator is intentionally lossless on
 * mechanical transforms; hand-curated Apple-specific tweaks live
 * in gpu/codegen/cl2metal_overrides/<algo>.yaml.
 *
 * Mirrors the byte-exact OpenCL hash chain; address-space port:
 *   __global  -> device
 *   __private -> thread
 *   barrier   -> threadgroup_barrier
 *   typedef struct ... T;  ->  struct T { ... };
 *   T *st     -> thread T &st
 *
 * Patterns 1/3 enforced: every pointer arg is address-space
 * qualified; every helper is static inline.
 */

/* gpu_md4utf16_core.cl — MD4UTF16 (-m e496) algorithm extension functions
 * for the generic dispatch template (Memo B Phase B5 sub-batch 8).
 *
 * MD4UTF16 = MD4(UTF-16LE(input))  on iter == 1, where UTF-16LE is the
 *            STRICT UTF-8 -> UTF-16LE conversion and an ill-formed input
 *            produces NO DIGEST AT ALL
 *          = MD4(UTF-16LE-zero-extend(lowercase_hex(prev_digest)))  on iter > 1
 *            (the iter feed is 32 lowercase hex chars, so zero-extend and
 *            the strict conversion are the same thing there)
 *
 * 2026-10-05 CORRECTNESS FIX, and it is the SECOND one in this file -- read
 * the 2026-09-15 note below first, it fixed a different half of the same
 * problem.  mdxfind.c 1.616 retired iconv.  CPU JOB_MD4UTF16 is now
 *
 *     len = U8TO16LE(cur, len, wline, MAXLINE*2);
 *     if (len <= 0) break;                 <-- NO digest for this candidate
 *     MD4((char *) wline, len, md5buf.h);
 *
 * where U8TO16LE is utf8_to_utf16() in ruleproc32.c, which returns a
 * LENGTH or a negative RULE32_ERR_ and NEVER a partial result.  So the CPU
 * now REFUSES an ill-formed candidate outright, where iconv("...//IGNORE")
 * used to delete the offending bytes and hash whatever survived.  This
 * kernel used to reproduce the //IGNORE behaviour faithfully; against
 * 1.616 that made every ill-formed candidate a GPU-ONLY hit the CPU would
 * never produce -- and because the GPU claims the batch, the CPU never
 * redoes the work, so there was nothing to catch it.  Measured before the
 * fix on a 1.616 binary, on TWO fixtures, both filtered to <= 27 bytes
 * (this op's gpu_maxlen at the host chokepoint, so every candidate in them
 * reached the GPU):
 *
 *   fixture                                      GPU      CPU   GPU-only
 *   273,660-word slice of isw2012-md5.dic    273,317  155,942    117,375
 *     (a real dirty wordlist, 91.8% of its
 *      high-bit words are not valid UTF-8)
 *   3,908 synthetic branch-coverage cands      3,564      450      3,114
 *
 * Every GPU-only hit was the retired //IGNORE partial reading.  Identical
 * numbers on OpenCL (GTX 1080 / RTX 4070 Ti SUPER / GTX 960) and on Metal
 * (M1 / M2 Max).  After the fix, GPU == CPU on both fixtures and all five
 * devices.  Cite the fixture with the number: the 117,375 figure quoted in
 * gpu_ntlmh_core.cl is the wordlist row, not the synthetic one.
 *
 * THE FIX IS `live`, NOT A SENTINEL DIGEST.  md4_over_utf16le now reports
 * ill-formedness through a `dropped` out-parameter and template_finalize
 * folds it into the state's `live` flag, which template_digest_compare
 * already honours (`if (!st->live) return 0;`).  `live` was added in
 * 2026-09 for the empty-conversion case and means exactly "the CPU would
 * not have produced a digest at all for this candidate", which is exactly
 * what `if (len <= 0) break;` says -- and `len <= 0` covers BOTH the
 * ill-formed case and the empty one with one test, so the two reasons
 * share the one flag by right rather than by coincidence.  Nothing in
 * gpu_template.cl changed: a single-digest core has no second digest to
 * suppress, so refusal has to be a gate on the probe, and the gate was
 * already there.  A poisoned/unmatchable sentinel digest was rejected --
 * no 128-bit value is provably absent from an arbitrary user hash file,
 * and if one ever collided the kernel would emit it as a plaintext.
 *
 * Note nothing is LOST by refusing.  The //IGNORE reading existed as an
 * ease-of-use convenience for mixed, unclean dictionary files; a dirty
 * non-UTF-8 line is still recovered by e369 through its real CP1251 /
 * CP1252 tables and by e786 through zero-extend.  Verified: the CP1252
 * line $HEX[636166e9] yields the true Windows digest
 * b1db12409c00d1fc586fc48ecadc36a1 under e369 and e786 while e496
 * correctly yields nothing.  The convenience is served by reading the
 * bytes under a REAL encoding, not by deleting the ones that do not fit.
 *
 * NO ALT_DIGEST HOOK HERE, and that asymmetry with NTLMH is deliberate.
 * gpu_ntlmh_core.cl declares GPU_TEMPLATE_HAS_ALT_DIGEST because its CPU
 * reference tests BOTH an iconv arm and a zero-extend arm, so the GPU has
 * to compute and compare two digests or leave one arm unreachable.  The
 * MD4UTF16 CPU reference has NO zero-extend arm at all, so a second digest
 * would be one the CPU never computes -- this core computes the iconv form
 * ALONE, and that is the whole of it.
 *
 * This is a CLONE of gpu_ntlmh_core.cl's algorithm (zero-extend UTF-16LE
 * variant of MD4) with one structural difference: MD4UTF16 supports the
 * mdxfind -i / Maxiter loop, NTLMH does not. The CPU reference at
 * mdxfind.c:15040-15068 (JOB_MD4UTF16) emits one digest per iter, with
 * iter 2..Maxiter feeding back the lowercase-hex of the prior digest
 * (32 ASCII hex chars) zero-extended to UTF-16LE (64 bytes), then MD4'd.
 *
 * 2026-09-15 CORRECTNESS FIX.  This core used to zero-extend (input byte
 * b -> the two bytes b, 0x00), described here and at mdxfind.c:13248 as
 * a "documented hashcat-compat gap, same as NTLMH".  That description was
 * wrong: JOB_NTLMH tests an iconv arm AND a zero-extend arm, but
 * JOB_MD4UTF16 at mdxfind.c:19070-19097 tests ONLY the iconv arm.  So on
 * any input carrying a byte >= 0x80 the GPU computed a digest the CPU
 * never computes -- it could not match, and the CPU never redid the work,
 * so the run printed "None found, sorry!" and exited 0.  Measured on
 * fpga.local (GTX 1080): CPU recovered its known answer, GPU recovered
 * nothing.  template_finalize now performs the real conversion; see
 * md4_over_utf16le below for the equivalence proof.  ASCII inputs are
 * byte-identical to the old code, so nothing that worked stops working.
 *
 * On the iter > 1 feedback path the input is always lowercase hex chars
 * [0-9a-f] (pure ASCII) so zero-extend == iconv; template_iterate is
 * UNCHANGED by the 2026-09-15 fix and stays byte-exact vs CPU (the CPU
 * itself calls to_utf16le there, mdxfind.c:19093, not iconv).
 *
 * Block layout (template_finalize, iter == 1):
 *   UTF-16 code unit k occupies UTF-16LE bytes 2k and 2k+1, so it lands in
 *   MD4 word (k mod 32) >> 1 at shift 16 * (k & 1).  A block closes every
 *   32 code units.  Bit count = 16 * (number of code units), which for an
 *   ASCII input is 16*len exactly as before, and for a multi-byte input is
 *   SHORTER than the old 16*len -- one of the two ways the old code was
 *   wrong (the other being the byte values themselves).
 *
 * Block layout (template_iterate, iter > 1):
 *   Input is fixed 32 lowercase hex chars (digest of prior iter).
 *   UTF-16LE-zero-extend yields 64 bytes -> exactly one MD4 input block.
 *   The 0x80 pad marker + length field need a SECOND MD4 block.
 *   M[j] for first block = hex[2j] | (hex[2j+1] << 16) for j in 0..15.
 *   Second block: M[0] = 0x80, M[1..13] = 0, M[14] = 64*8 = 512, M[15] = 0.
 *
 * State width / byte order: MD4 carries 4 LE uint32 chaining values
 * (same as MD5; UNLIKE the SHA family).
 *
 * Cache key (R3): defines_str = "HASH_WORDS=4,HASH_BLOCK_BYTES=64" -- same
 * as MD4 / MD5 / MD5RAW / NTLMH. Distinct cache entry guaranteed by
 * source-text hash difference (the iter step diverges from NTLMH).
 *
 * R1 mitigation: single private buffer; no addrspace-cast helpers.
 *
 * Source order at compile time:
 *   [ gpu_common_str, gpu_md5_rules_str, gpu_md4utf16_core_str, gpu_template_str ]
 */

#ifndef HASH_WORDS
#define HASH_WORDS 4
#endif
#ifndef HASH_BLOCK_BYTES
#define HASH_BLOCK_BYTES 64
#endif

struct template_state {
    uint h[HASH_WORDS];
    /* 0 when the CPU would not have produced a digest at all for this
     * candidate -- see template_finalize.  template_digest_compare then
     * refuses to probe, which is how the kernel says "no hash here". */
    uint live;
};

/* MD4 compression -- inlined here (renamed to md4_compress_md4utf16 to avoid
 * symbol clash if gpu_md4_core_str / gpu_ntlmh_core_str is ever included in
 * the same compile unit). Mirrors gpu_md4_core.cl's md4_compress byte-for-
 * byte; same as md4_compress_ntlmh. */
static inline void md4_compress_md4utf16(thread uint &hx, thread uint &hy, thread uint &hz, thread uint &hw, thread uint *M)
{
    uint a = hx, b = hy, c = hz, d = hw;
#define MD4_F(x,y,z) (((x)&(y)) | ((~(x))&(z)))
#define MD4_G(x,y,z) (((x)&(y)) | ((x)&(z)) | ((y)&(z)))
#define MD4_H(x,y,z) ((x)^(y)^(z))
#define MD4_R1(a,b,c,d,k,s) a = rotate(a + MD4_F(b,c,d) + M[k], (uint)(s))
#define MD4_R2(a,b,c,d,k,s) a = rotate(a + MD4_G(b,c,d) + M[k] + 0x5A827999u, (uint)(s))
#define MD4_R3(a,b,c,d,k,s) a = rotate(a + MD4_H(b,c,d) + M[k] + 0x6ED9EBA1u, (uint)(s))
    MD4_R1(a,b,c,d, 0, 3); MD4_R1(d,a,b,c, 1, 7); MD4_R1(c,d,a,b, 2,11); MD4_R1(b,c,d,a, 3,19);
    MD4_R1(a,b,c,d, 4, 3); MD4_R1(d,a,b,c, 5, 7); MD4_R1(c,d,a,b, 6,11); MD4_R1(b,c,d,a, 7,19);
    MD4_R1(a,b,c,d, 8, 3); MD4_R1(d,a,b,c, 9, 7); MD4_R1(c,d,a,b,10,11); MD4_R1(b,c,d,a,11,19);
    MD4_R1(a,b,c,d,12, 3); MD4_R1(d,a,b,c,13, 7); MD4_R1(c,d,a,b,14,11); MD4_R1(b,c,d,a,15,19);
    MD4_R2(a,b,c,d, 0, 3); MD4_R2(d,a,b,c, 4, 5); MD4_R2(c,d,a,b, 8, 9); MD4_R2(b,c,d,a,12,13);
    MD4_R2(a,b,c,d, 1, 3); MD4_R2(d,a,b,c, 5, 5); MD4_R2(c,d,a,b, 9, 9); MD4_R2(b,c,d,a,13,13);
    MD4_R2(a,b,c,d, 2, 3); MD4_R2(d,a,b,c, 6, 5); MD4_R2(c,d,a,b,10, 9); MD4_R2(b,c,d,a,14,13);
    MD4_R2(a,b,c,d, 3, 3); MD4_R2(d,a,b,c, 7, 5); MD4_R2(c,d,a,b,11, 9); MD4_R2(b,c,d,a,15,13);
    MD4_R3(a,b,c,d, 0, 3); MD4_R3(d,a,b,c, 8, 9); MD4_R3(c,d,a,b, 4,11); MD4_R3(b,c,d,a,12,15);
    MD4_R3(a,b,c,d, 2, 3); MD4_R3(d,a,b,c,10, 9); MD4_R3(c,d,a,b, 6,11); MD4_R3(b,c,d,a,14,15);
    MD4_R3(a,b,c,d, 1, 3); MD4_R3(d,a,b,c, 9, 9); MD4_R3(c,d,a,b, 5,11); MD4_R3(b,c,d,a,13,15);
    MD4_R3(a,b,c,d, 3, 3); MD4_R3(d,a,b,c,11, 9); MD4_R3(c,d,a,b, 7,11); MD4_R3(b,c,d,a,15,15);
#undef MD4_F
#undef MD4_G
#undef MD4_H
#undef MD4_R1
#undef MD4_R2
#undef MD4_R3
    hx = a + hx; hy = b + hy; hz = c + hz; hw = d + hw;
}

static inline void template_init(thread template_state &st)
{
    st.h[0] = 0x67452301u;
    st.h[1] = 0xEFCDAB89u;
    st.h[2] = 0x98BADCFEu;
    st.h[3] = 0x10325476u;
    st.live = 1u;
}

/* template_transform: stub for interface symmetry (cloned from NTLMH).
 * The shared template body in gpu_template.cl never invokes this for
 * MD4UTF16; template_finalize handles its own block packing inline
 * (UTF-16LE expansion is interleaved with the M[] build). */
static inline void template_transform(thread template_state &st,
                                thread const uchar *block)
{
    uint M[16];
    for (int j = 0; j < 16; j++) {
        int b = j * 4;
        M[j] = (uint)block[b]
             | ((uint)block[b + 1] << 8)
             | ((uint)block[b + 2] << 16)
             | ((uint)block[b + 3] << 24);
    }
    md4_compress_md4utf16(st.h[0], st.h[1], st.h[2], st.h[3], M);
}

/* md4_over_utf16le: MD4 of the UTF-16LE form of a UTF-8 input, assembled
 * one 64-byte block at a time so no UTF-16 scratch buffer is needed.
 *
 * h4 must already hold the MD4 IV (template_init does that).
 *
 * ILL-FORMED INPUT IS REFUSED, NOT PATCHED UP (2026-10-05).  At the three
 * points where the decoder learns the input is not well-formed it sets
 * *dropped and RETURNS.  It does NOT skip one byte and resynchronise the
 * way glibc's "UTF-16LE//IGNORE" does, because CPU JOB_MD4UTF16 at
 * mdxfind.c 1.616 no longer does either -- see the file header.  The
 * partial state left in h4 by an early return is never padded, never
 * probed and never emitted: template_finalize turns *dropped into
 * live = 0, and template_digest_compare returns 0 without touching h4
 * when live is 0, at EVERY iteration of the template's iter loop.
 *
 * The acceptance predicate is utf8_to_utf32()'s, term for term
 * (ruleproc32.c:240): lead classes C2-DF / E0-EF / F0-F4 only, so
 * 0x80-0xBF, 0xC0/0xC1 and 0xF5-0xFF can never start a sequence; every
 * continuation byte must be 10xxxxxx; the overlong minimum per length;
 * no surrogate U+D800..U+DFFF; nothing above U+10FFFF; and a sequence
 * truncated by end of input is ill-formed rather than ignored.  Astral
 * codepoints become a correct surrogate PAIR.
 *
 * HISTORICAL, and still true where it still applies: this loop's
 * WELL-FORMED half was validated against glibc iconv on .205 over
 * 18,802,400 inputs (every 1-, 2- and 3-byte string exhaustively, a
 * structured 4-byte sweep, ASCII lengths 0..63, 2/3/4-byte characters at
 * every block alignment, and 1.5M pseudo-random strings) with ZERO
 * differences.  That study still holds for every input where no byte is
 * dropped.  On an ill-formed input this function deliberately no longer
 * computes glibc's //IGNORE output, because nothing consumes it.
 *
 * For an ALL-ASCII input this is byte-identical to the zero-extend form
 * it replaces, so every existing MD4UTF16 result on ASCII candidates is
 * unchanged (host mirror part C: 0 differences).  It differs only where
 * the old code was wrong, because CPU JOB_MD4UTF16 has NO zero-extend
 * arm -- unlike JOB_NTLMH, which tests both.  The pre-2026-09 comments
 * in this file, in gpu_opencl.c and at mdxfind.c:13248 describing the
 * divergence as a "documented hashcat-compat gap, same as NTLMH" were
 * wrong on that point: for e496 the GPU was computing a digest the CPU
 * never computes, at any input, so it could only ever miss.
 */
static inline uint md4_over_utf16le(thread uint *h4, device const uchar *data, int len, thread int &dropped)
{
    uint M[16];
    for (int j = 0; j < 16; j++) M[j] = 0u;

    uint nunits = 0u;   /* UTF-16 code units emitted so far */
    int  i = 0;
    dropped = 0;

    while (i < len) {
        uint c = (uint)data[i];
        uint cp;
        int  adv;

        if (c < 0x80u) {
            cp = c; adv = 1;
        } else if (c >= 0xC2u && c <= 0xDFu && i + 1 < len &&
                   (data[i + 1] & 0xC0u) == 0x80u) {
            cp  = ((c & 0x1Fu) << 6) | (uint)(data[i + 1] & 0x3Fu);
            adv = 2;
        } else if (c >= 0xE0u && c <= 0xEFu && i + 2 < len &&
                   (data[i + 1] & 0xC0u) == 0x80u &&
                   (data[i + 2] & 0xC0u) == 0x80u) {
            cp  = ((c & 0x0Fu) << 12) |
                  ((uint)(data[i + 1] & 0x3Fu) << 6) |
                   (uint)(data[i + 2] & 0x3Fu);
            adv = 3;
            /* overlong, or a lone surrogate */
            if (cp < 0x800u || (cp >= 0xD800u && cp <= 0xDFFFu)) { dropped = 1; return 0u; }
        } else if (c >= 0xF0u && c <= 0xF4u && i + 3 < len &&
                   (data[i + 1] & 0xC0u) == 0x80u &&
                   (data[i + 2] & 0xC0u) == 0x80u &&
                   (data[i + 3] & 0xC0u) == 0x80u) {
            cp  = ((c & 0x07u) << 18) |
                  ((uint)(data[i + 1] & 0x3Fu) << 12) |
                  ((uint)(data[i + 2] & 0x3Fu) << 6) |
                   (uint)(data[i + 3] & 0x3Fu);
            adv = 4;
            if (cp < 0x10000u || cp > 0x10FFFFu) { dropped = 1; return 0u; }
        } else {
            /* 0x80-0xBF (continuation with no lead), 0xC0/0xC1 (only ever
             * an overlong), 0xF5-0xFF (above U+10FFFF), a bad continuation
             * byte, or a sequence truncated by end of input. */
            dropped = 1; return 0u;
        }
        i += adv;

        /* One BMP code unit, or a surrogate pair for an astral codepoint. */
        uint u0, u1; int nu;
        if (cp < 0x10000u) {
            u0 = cp; u1 = 0u; nu = 1;
        } else {
            uint v = cp - 0x10000u;
            u0 = 0xD800u + (v >> 10);
            u1 = 0xDC00u + (v & 0x3FFu);
            nu = 2;
        }
        for (int e = 0; e < nu; e++) {
            uint u = (e == 0) ? u0 : u1;
            /* Code unit k occupies UTF-16LE bytes 2k, 2k+1; MD4 reads M
             * little-endian, so it lands in M[(k mod 32) >> 1] at shift
             * 16 * (k & 1). */
            M[(nunits & 31u) >> 1] |= u << ((nunits & 1u) * 16u);
            nunits++;
            if ((nunits & 31u) == 0u) {   /* 32 code units == one 64-byte block */
                md4_compress_md4utf16(h4[0], h4[1], h4[2], h4[3], M);
                for (int j = 0; j < 16; j++) M[j] = 0u;
            }
        }
    }

    /* Pad.  r code units sit in the partial block, so the 0x80 marker goes
     * at byte 2r of it, and the bit count is 16 * nunits. */
    uint r = nunits & 31u;
    M[r >> 1] |= 0x80u << ((r & 1u) * 16u);
    if (r * 2u < 56u) {
        M[14] = nunits << 4;
        M[15] = nunits >> 28;
        md4_compress_md4utf16(h4[0], h4[1], h4[2], h4[3], M);
    } else {
        md4_compress_md4utf16(h4[0], h4[1], h4[2], h4[3], M);
        for (int j = 0; j < 16; j++) M[j] = 0u;
        M[14] = nunits << 4;
        M[15] = nunits >> 28;
        md4_compress_md4utf16(h4[0], h4[1], h4[2], h4[3], M);
    }
    return nunits;
}

/* template_finalize: MD4UTF16 = MD4(iconv(UTF-8 -> UTF-16LE)(input)),
 * which is the ONLY variant CPU JOB_MD4UTF16 computes.
 *
 * THE NO-DIGEST CASES.  The CPU guard, mdxfind.c 1.616, is
 *
 *     len = U8TO16LE(cur, len, wline, MAXLINE*2);
 *     if (len <= 0)
 *       break;                       -- no digest AT ALL for this candidate
 *
 * and `len <= 0` is true for TWO reasons, both of which land on live = 0:
 * the conversion FAILED (utf8_to_utf16() returned a negative RULE32_ERR_
 * because the candidate is not well-formed UTF-8) or it produced NOTHING
 * (the candidate was empty).  Before 1.616 the guard was iconv's
 * `ic_outleft == MAXLINE*2`, which tested only the second; the shortened
 * //IGNORE reading of an ill-formed candidate WAS hashed and probed.
 *
 * Getting the empty case wrong is not a miss, it is a FALSE POSITIVE, and
 * a spectacularly likely one: it would otherwise hash to MD4 of the empty
 * string, 31d6cfe0d16ae931b73c59d7e0c089c0, which is the empty password
 * and is present in essentially every NTLM-family hash list.  The kernel
 * would have reported garbage bytes as the plaintext for it.  Getting the
 * ill-formed case wrong is a false positive too, just a less uniform one:
 * it reports the digest of a candidate with bytes deleted, labelled with
 * the plaintext that was NOT hashed.
 *
 * live is NOT re-armed by template_iterate: the CPU's break leaves the
 * whole case, so iterations 2..Maxiter produce nothing either.  Tested
 * directly at -i 3 (8 well-formed + 8 ill-formed candidates): CPU and GPU
 * both emit 24 digests, 8 candidates x 3 iterations, and the 12 ladder
 * digests reachable only from a //IGNORE partial are emitted by neither.
 * The ladder itself is untouched by the refusal change -- template_iterate
 * feeds 32 lowercase hex characters, which are ASCII, so there is nothing
 * for a UTF-8 validator to reject past iteration 1. */
static inline void template_finalize(thread template_state &st,
                                device const uchar *data,
                                int len)
{
    int dropped;
    uint nunits = md4_over_utf16le(st.h, data, len, dropped);
    st.live = (!dropped && nunits != 0u) ? 1u : 0u;
}

/* template_iterate: -i loop step. CPU reference at mdxfind.c:15059-15066:
 *
 *   prmd5(md5buf.h, mdbuf, 32);     // 32 lowercase hex chars in mdbuf
 *   to_utf16le(mdbuf, linebuf, 32); // 64 UTF-16LE bytes (each ASCII byte
 *                                   //   followed by 0x00)
 *   MD4(linebuf, 64, md5buf.h);     // MD4 over the 64-byte buffer
 *
 * Implementation:
 *   1. Pack lowercase hex of state into 8 LE uint32 words via md5_to_hex_lc
 *      (defined in gpu_common.cl). Result: M_hex[0..7] each holds 4 hex
 *      bytes in LE order.
 *   2. Build the FIRST MD4 block from those 32 hex bytes via UTF-16LE
 *      zero-extend pack: M_blk[j] = hex[2j] | (hex[2j+1] << 16) for j in
 *      0..15. Read hex bytes from M_hex via byte extraction.
 *      Reset state IV, MD4-compress this first block.
 *   3. Build the SECOND MD4 block: M[0] = 0x80 pad marker (UTF-16 byte
 *      position 64 = wi=0 of block 2), M[1..13] = 0, M[14] = 64*8 = 512
 *      (bit count for 64 UTF-16LE bytes), M[15] = 0. MD4-compress. */
static inline void template_iterate(thread template_state &st)
{
    uint M_hex[16];
    /* Step 1: lowercase-hex of current digest -> M_hex[0..7] (32 bytes).
     * md5_to_hex_lc writes M[0..7] LE-packed; M[8..15] are not touched
     * by md5_to_hex_lc but our local M_hex was uninitialized -- ok,
     * we only read indices [0..7] below. */
    md5_to_hex_lc(st.h[0], st.h[1], st.h[2], st.h[3], M_hex);

    /* Step 2: build first MD4 block over UTF-16LE-zero-extend of the 32
     * hex chars. Hex char k is at byte position k of the linear hex
     * stream, which is at M_hex[k>>2], byte (k&3) (LE order). */
    uint M_blk[16];
    for (int j = 0; j < 16; j++) {
        int k0 = j * 2;          /* hex char index for low half of M_blk[j] */
        int k1 = j * 2 + 1;      /* hex char index for high half of M_blk[j] */
        uint c0 = (M_hex[k0 >> 2] >> ((k0 & 3) * 8)) & 0xffu;
        uint c1 = (M_hex[k1 >> 2] >> ((k1 & 3) * 8)) & 0xffu;
        M_blk[j] = c0 | (c1 << 16);
    }
    /* Reset state to MD4 IV before consuming the new input. */
    st.h[0] = 0x67452301u;
    st.h[1] = 0xEFCDAB89u;
    st.h[2] = 0x98BADCFEu;
    st.h[3] = 0x10325476u;
    md4_compress_md4utf16(st.h[0], st.h[1], st.h[2], st.h[3], M_blk);

    /* Step 3: build second MD4 block (pad + length). UTF-16 byte 64 lands
     * at wi=0, bi=0 of block 2 -- so M[0] = 0x80 (low byte of word 0). */
    M_blk[0] = 0x80u;
    for (int j = 1; j < 14; j++) M_blk[j] = 0u;
    M_blk[14] = 64u * 8u;        /* 64 UTF-16LE bytes = 512 bits */
    M_blk[15] = 0u;
    md4_compress_md4utf16(st.h[0], st.h[1], st.h[2], st.h[3], M_blk);
}

static inline int template_digest_compare(thread const template_state &st,
                                device const uint *compact_fp,
                                device const uint *compact_idx,
                                ulong compact_mask,
                                uint max_probe,
                                uint hash_data_count,
                                device const uchar *hash_data_buf,
                                device const ulong *hash_data_off,
                                device const ulong *overflow_keys,
                                device const uchar *overflow_hashes,
                                device const uint *overflow_offsets,
                                uint overflow_count,
                                thread uint *out_idx)
{
    if (!st.live) return 0;
    return probe_compact_idx(
        st.h[0], st.h[1], st.h[2], st.h[3],
        compact_fp, compact_idx,
        compact_mask, max_probe, hash_data_count,
        hash_data_buf, hash_data_off,
        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,
        out_idx);
}


#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \
                                      hashes_shown, matched_idx, dedup_mask, \
                                      ovr_set, ovr_gid, lane_gid) \
    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \
               (widx), (sidx), (iter), \
               (st).h[0], (st).h[1], (st).h[2], (st).h[3], \
               (hashes_shown), (matched_idx), (dedup_mask), \
               (ovr_set), (ovr_gid), (lane_gid))
