/* Auto-generated from metal_template.metal -- do not edit */
static const char metal_template_str[] =
    "/*\n"
    " * $Revisio" "n: 1.3 $\n"
    " * $Lo" "g: metal_template.metal,v $\n"
    " * Revision 1.3  2026/05/13 03:39:11  dlr\n"
    " * Phase 2b row 1: add GPU_TEMPLATE_HAS_MASK axis to template_phase0. New gated buffer args mask_charsets (buffer 12) and mask_sizes (buffer 13). Under the macro the kernel gains a third gid axis (mask innermost: mask_idx_local = gid % mask_size; word_idx and rule_idx unchanged in lex order), then decomposes mask_idx into per-position prepend+append indices via divmod (mirror of gpu_template.cl lines 405-531) and modifies thread uchar buf[] in place AFTER the rules walker but BEFORE template_finalize. Mirrors slab convention: rows [0..n_prepend) are prepend rows, rows [n_prepend..n_prepend+n_append) are append. RULE_BUF_LIMIT bound enforced; append_combos widened to ulong (matches OpenCL Phase 1.5 widening for >4G keyspaces). Combined_ridx packing extends: HAS_MASK alone -> mask_idx_local; HAS_RULES alone -> rule_idx; both -> rule_idx*mask_size+mask_idx_local; neither -> 0. Coexists with HAS_RULES: M-alone signature has buffers 0..9,12,13 (gap at 10,11); RM dense 0..13. Apple Metal driver-verified to accept gap-numbered buffer indices via xcrun metal standalone compile + AIR inspection on iMac before this commit. axis_mask_size and axis_n_rules locals factor the gid divmod into a single shape so the four (none/R/M/RM) variants share the same arithmetic. Phase 2b non-goals: salt axis, iter loop, pre-salt hoist, BCRYPT local buffer, BF chunk-as-job (params.mask_start and params.mask_offset_per_word read 0 in 2b). Offline xcrun metal compile clean for all 4 variants on iMac AMD Radeon Pro 580X (no new warnings beyond pre-existing template_transform/template_iterate/apply_rule unused-function noise). Per Phase 2b memo rows 1+8.\n"
    " *\n"
    " * Revision 1.2  2026/05/12 17:14:30  dlr\n"
    " * Phase 2a row 4: add GPU_TEMPLATE_HAS_RULES axis to template_phase0. Under the macro the kernel gains two new buffer args (rule_program at 10, rule_offset at 11), decomposes gid into (word_idx, rule_idx) with rule innermost, invokes apply_rule from metal_md5_rules.metal (same family TU + same JIT concat), and packs combined_ridx = rule_idx for hit emit. Synthetic-no-rule discriminator + post-rule no-op skip preserve feedback_no_rule_pass.md semantics. Without the macro the kernel compiles to Phase 1 behavior byte-identical: gid -> word_idx direct, no walker. n_rules sourced from params.num_masks (mirrors OpenCL twin gpu_template.cl line 215). Offline xcrun metal compile clean for both variants on iMac (no-rules AIR 12.9KB, rules AIR 23.5KB). Per memo §3 rows 4-7 + Phase 0.5 patterns 1-6.\n"
    " *\n"
    " * Revision 1.2  2026/05/12 18:00:00  dlr\n"
    " * Phase 2a row 4: add GPU_TEMPLATE_HAS_RULES axis to template_phase0. New gated buffer args rule_program (buffer 10) and rule_offset (buffer 11); under the macro the kernel decomposes gid into (word_idx, rule_idx) with rule innermost, then invokes apply_rule from metal_md5_rules.metal (same family TU) — same shape as gpu/gpu_template.cl lines 374-403. Synthetic-no-rule discriminator (first byte NUL -> is_no_rule=1) and post-rule no-op skip preserve feedback_no_rule_pass.md byte semantics. Hit emit packs combined_ridx = rule_idx (mask_size==1 in 2a; mask axis lands in 2b). Without the macro the kernel compiles to Phase 1 behavior byte-identical: gid -> word_idx direct, no walker. n_rules sourced from params.num_masks (same overload as OpenCL twin). Per memo §3 rows 4-7 + Phase 0.5 patterns 1-6 enforced (every new arg device-qualified; no threadgroup decls added).\n"
    " *\n"
    " * Revision 1.1  2026/05/12 13:35:19  dlr\n"
    " * Initial check-in: Phase 1 Metal template kernel. Subset of gpu/gpu_template.cl: raw MD5 unsalted only, gid -> word_idx direct (no rules, no mask, no salt), single iter cycle (max_iter==1). Payload wire format byte-identical to OpenCL: MetalParams at offset 0-127, hit_count at 128, word_offset at 132, packed words after. Buffer indices 0..9 sequential. Pattern 1: every kernel arg device-or-thread-qualified. Pattern 5: no threadgroup decls (rule pre-stated for Phase 2).\n"
    " *\n"
    " */\n"
    "/* metal_template.metal — generic dispatch-template kernel for Metal.\n"
    " * Mirrors a SUBSET of gpu/gpu_template.cl.\n"
    " *\n"
    " * Compile-time axes (Phase 2a row 4 + Phase 2b row 1):\n"
    " *   GPU_TEMPLATE_HAS_RULES   undef -> Phase 1 no-rules path (gid -> word).\n"
    " *                            defined -> apply_rule walker invoked per lane;\n"
    " *                            kernel signature gains rule_program (buffer 10)\n"
    " *                            and rule_offset (buffer 11).\n"
    " *   GPU_TEMPLATE_HAS_MASK    undef -> no mask axis (mask_size==1).\n"
    " *                            defined -> per-lane mask_idx decompose + in-place\n"
    " *                            buf prepend/append; kernel signature gains\n"
    " *                            mask_charsets (buffer 12) and mask_sizes\n"
    " *                            (buffer 13). Independent of HAS_RULES — the\n"
    " *                            four (none/R/M/RM) variants compile from the\n"
    " *                            same source. Buffer indices are gap-tolerant:\n"
    " *                            M-alone uses 12/13 even though 10/11 are absent.\n"
    " *                            Mirrors gpu/gpu_template.cl lines 181-188,\n"
    " *                            216-275, 405-531 (less BF and salt — not in 2b).\n"
    " *\n"
    " * Phase 1 scope (memo §5 mapping table; memo §1 non-goals — applies when\n"
    " * GPU_TEMPLATE_HAS_RULES is undefined):\n"
    " *   - Raw MD5 unsalted, NO rules, NO mask, NO salt, NO iter, NO BF,\n"
    " *     NO HMAC, NO BCRYPT, NO PRE_SALT, NO threadgroup LOCAL_BUFFER.\n"
    " *   - One word per lane (gid -> word_idx directly).\n"
    " *   - max_iter is read but only the iter==1 case is exercised (no\n"
    " *     iter loop body).\n"
    " *   - Cursor protocol disabled (input_cursor_start/rule_cursor_start\n"
    " *     populated to 0 by the host; kernel reads but takes no action).\n"
    " *\n"
    " * Phase 2a row 4: GPU_TEMPLATE_HAS_RULES axis adds the rules-engine walker\n"
    " * invocation. Mirrors gpu_template.cl lines 374-403.\n"
    " * Phase 2b row 1 (this revision): GPU_TEMPLATE_HAS_MASK axis adds in-place\n"
    " * prepend/append into the per-lane buf, mirroring gpu_template.cl lines\n"
    " * 181-188 (arg decls), 216-275 (geometry + mask_idx decompose), 405-531\n"
    " * (modification). Coexists with HAS_RULES — RM variant binds buffers\n"
    " * 10, 11, 12, 13; M-alone binds 12, 13 (gap-OK; verified by xcrun metal\n"
    " * standalone compile on iMac before this commit).\n"
    " * Phase 2c+ re-adds: salt axis, iter loop, pre-salt hoist, BCRYPT local\n"
    " * buffer, BF chunk-as-job (Metal currently lacks BF; 2b's\n"
    " * mask_offset_per_word + mask_start kernel args read 0 from params).\n"
    " *\n"
    " * Phase 2e (pre-salt hoist + SIMD lane batching):\n"
    " *   GPU_TEMPLATE_HAS_PRE_SALT  undef -> per-salt template_finalize (Phase\n"
    " *                              2c shape; the inner-MD5+hex32 is recomputed\n"
    " *                              for every salt).\n"
    " *                              defined -> template_pre_salt() runs ONCE\n"
    " *                              per (word, rule, mask); inner salt loop\n"
    " *                              iterates SALT_BATCH salts at a time via\n"
    " *                              template_finalize_post(). REQUIRES\n"
    " *                              GPU_TEMPLATE_HAS_SALT.\n"
    " *   SALT_BATCH                 compile-time macro (default 16). Tile size\n"
    " *                              for the inner salt loop under HAS_PRE_SALT.\n"
    " *                              On Metal one-thread-per-word the tile is\n"
    " *                              an unroll hint for the compiler -- the\n"
    " *                              kernel still iterates the FULL salt list,\n"
    " *                              just in stride-SALT_BATCH chunks. Per-tier\n"
    " *                              selection lives in gpu_metal.m\n"
    " *                              metal_select_salt_batch().\n"
    " *   Mirrors gpu_template.cl HAS_PRE_SALT block (lines 534-585), adapted\n"
    " *   to Metal's one-thread-per-word grid (the OpenCL twin folds salt_chunk\n"
    " *   into the outer NDRange axis; Metal keeps it as an inner-loop tile).\n"
    " *\n"
    " * --- Pattern enforcement (from memo §12 + Phase 0.5) ---\n"
    " *\n"
    " *   Pattern 1: every kernel-arg buffer is `device` or `constant`;\n"
    " *              every lane-local pointer is `thread`.\n"
    " *   Pattern 2: kernel name is `template_phase0` (matches OpenCL).\n"
    " *   Pattern 5: NO threadgroup declarations in Phase 1 (rule pre-stated\n"
    " *              for Phase 2: threadgroup decl MUST be initialized before\n"
    " *              first read; pair with threadgroup_barrier(mem_threadgroup)).\n"
    " *\n"
    " * --- Payload wire format (matches gpujob_opencl.c layout) ---\n"
    " *\n"
    " *   offset 0..127     MetalParams params (mirrors OCLParams; 128 B)\n"
    " *   offset 128..131   uint hit_count (atomic, written by kernel)\n"
    " *   offset 132..132+4*n_words-1  uint word_offset[n_words]\n"
    " *                                   per-word byte offsets into packed\n"
    " *                                   words buffer (word_offset[i] points\n"
    " *                                   at the length-prefixed word i)\n"
    " *   offset 132+4*n_words..     packed words (length byte + bytes)\n"
    " *\n"
    " *   ovr_set lives at offset 100  (inside params: overflow_first_set)\n"
    " *   ovr_gid lives at offset 104  (inside params: overflow_first_word)\n"
    " *\n"
    " * The layout is byte-identical to the OpenCL kernel's payload reads.\n"
    " * Reuses gpujob_opencl.c's existing packer.\n"
    " *\n"
    " * --- Kernel signature mapping (memo §5) ---\n"
    " *\n"
    " *   OpenCL                                 Metal\n"
    " *   __global uchar *payload                device uchar *payload [[buffer(0)]]\n"
    " *   __global const T *                     device const T *      [[buffer(N)]]\n"
    " *   __global volatile uint *hashes_shown   device atomic_uint *hashes_shown [[buffer(N)]]\n"
    " *   __global uint *hits                    device uint *hits     [[buffer(N)]]\n"
    " *   get_global_id(0)                       uint gid [[thread_position_in_grid]]\n"
    " *\n"
    " * Phase 1 args (10 buffers; subset of OpenCL's 14-arg template_phase0):\n"
    " *   payload, compact_fp, compact_idx, hash_data_buf, hash_data_off,\n"
    " *   hits, overflow_keys, overflow_hashes, overflow_offsets, hashes_shown.\n"
    " *\n"
    " * Phase 2a HAS_RULES extension: 12 buffers (adds rule_program at 10,\n"
    " * rule_offset at 11). The host (gpu_metal.m) MUST bind in the same order\n"
    " * and MUST always bind buffers 10/11 when the rules variant PSO is in\n"
    " * use. The two PSO variants live in two distinct MTLLibrary objects\n"
    " * (no-rules from embedded metallib; rules JIT-compiled with the macro\n"
    " * defined).\n"
    " *\n"
    " * Phase 2b HAS_MASK extension: 12 buffers total in the M-alone variant\n"
    " * (0..9 + 12, 13 — buffers 10 and 11 are absent in the kernel signature\n"
    " * because the rules-block is preprocessor-stripped). 14 buffers total in\n"
    " * the RM variant (0..13 dense). Apple Metal's argument-buffer validator\n"
    " * accepts gap-numbered indices (10/11 absent in M-alone is fine — the\n"
    " * other lanes of the signature still bind dense 0..9, 12, 13).\n"
    " *\n"
    " * Buffer indices:\n"
    " *   - Phase 1 (none):     0..9 dense                 + 14 (buf_scratch_pool)\n"
    " *   - Phase 2a (R only):  0..11 dense                + 14\n"
    " *   - Phase 2b (M only):  0..9, 12, 13 (gap at 10..11) + 14\n"
    " *   - Phase 2b (RM):      0..13 dense                + 14\n"
    " *\n"
    " * Task #250 buffer 14 (buf_scratch_pool) is always bound for every\n"
    " * variant — the 40 KB per-lane scratch lives in device memory rather\n"
    " * than thread-local registers to fit M2 Max's register budget. Host\n"
    " * sizes it to num_words * RULE_BUF_MAX (640 MB at 16K-word peak),\n"
    " * allocated lazily on first dispatch. See gpu_metal.m\n"
    " * metal_ensure_buf_scratch_pool() / buf_scratch_pool static.\n"
    " */\n"
    "\n"
    "/* Phase 2e SALT_BATCH default. Tile size for the inner salt loop under\n"
    " * GPU_TEMPLATE_HAS_PRE_SALT. The host passes -DSALT_BATCH=N (per-tier\n"
    " * selection via metal_select_salt_batch in gpu_metal.m: 8 for M1, 16\n"
    " * for M2/M2 Max, 32 for M3+).  The device tier is the only input --\n"
    " * MDXFIND_METAL_SALT_BATCH used to override it and was removed 2026-09-16.\n"
    " * Default 16 (M2 Max sweet spot) when the macro is not set. */\n"
    "#ifndef SALT_BATCH\n"
    "#define SALT_BATCH 16\n"
    "#endif\n"
    "\n"
    "kernel void template_phase0(\n"
    "    device uchar          *payload          [[buffer(0)]],\n"
    "    device const uint     *compact_fp       [[buffer(1)]],\n"
    "    device const uint     *compact_idx      [[buffer(2)]],\n"
    "    device const uchar    *hash_data_buf    [[buffer(3)]],\n"
    "    device const ulong    *hash_data_off    [[buffer(4)]],\n"
    "    device uint           *hits             [[buffer(5)]],\n"
    "    device const ulong    *overflow_keys    [[buffer(6)]],\n"
    "    device const uchar    *overflow_hashes  [[buffer(7)]],\n"
    "    device const uint     *overflow_offsets [[buffer(8)]],\n"
    "    device atomic_uint    *hashes_shown     [[buffer(9)]],\n"
    "#ifdef GPU_TEMPLATE_HAS_RULES\n"
    "    device const uchar    *rule_program     [[buffer(10)]],\n"
    "    device const uint     *rule_offset      [[buffer(11)]],\n"
    "#endif\n"
    "#ifdef GPU_TEMPLATE_HAS_RULES32\n"
    "    /* UTF-32 rule path.  Buffer 18 and 19 -- 0-9 are dense, 10/11 rules,\n"
    "     * 12/13 mask, 14 the byte scratch pool, 15/16/17 salt.\n"
    "     *\n"
    "     *   u32_case_tab  the two 1:1 case tables CONCATENATED: up at\n"
    "     *                 [0 .. U32_CASE_N-1], lo above it.  `device`, not\n"
    "     *                 `constant`, and that is not a preference: on NVIDIA the\n"
    "     *                 same 26,048 bytes in the constant bank put the OpenCL\n"
    "     *                 rules program 13 KB past a hard 64 KB limit and ptxas\n"
    "     *                 refused the build outright.  Generated from\n"
    "     *                 ../latin_case.h so it cannot drift from the CPU engine.\n"
    "     *\n"
    "     *   u32_scratch_pool  per-word working memory for the UTF-32 walker,\n"
    "     *                 U32_SLOT_BYTES per word.  In `device` space for the\n"
    "     *                 same reason buf_scratch_pool is (task #250): the\n"
    "     *                 walker's two uint buffers are ~16 KB per lane, Apple\n"
    "     *                 Metal does NOT spill, and an M2 Max PSO-create rejects\n"
    "     *                 a `thread` array that size with \"Compute function\n"
    "     *                 exceeds available temporary registers\". */\n"
    "    device const uint     *u32_case_tab     [[buffer(18)]],\n"
    "    device uchar          *u32_scratch_pool [[buffer(19)]],\n"
    "#endif\n"
    "#ifdef GPU_TEMPLATE_HAS_MASK\n"
    "    /* Phase 2b row 1: mask charset table + per-position sizes. Layout mirrors\n"
    "     * gpu/gpu_opencl.c b_template_mask_charsets / b_template_mask_sizes\n"
    "     * exactly:\n"
    "     *   mask_charsets[i*256..i*256+256)   = 256-byte charset row for position i;\n"
    "     *                                       only the first mask_sizes[i] bytes\n"
    "     *                                       are valid.\n"
    "     *   mask_sizes[i]                     = uint32 modulus for position i.\n"
    "     * Positions [0..n_prepend) are prepend rows; positions [n_prepend..\n"
    "     * n_prepend+n_append) are append rows. MASK_POS_CAP = 16 per side\n"
    "     * (32 rows total = 8 KB charset buffer). The host (gpu_metal_set_mask\n"
    "     * in gpu_metal.m) allocates the full 32-row buffer and writes only the\n"
    "     * active rows; unused rows are zero-filled + mask_sizes[unused] = 1\n"
    "     * sentinel so any stray divmod terminates safely. */\n"
    "    device const uchar    *mask_charsets    [[buffer(12)]],\n"
    "    device const uint     *mask_sizes       [[buffer(13)]],\n"
    "#endif\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    /* Phase 2c salt axis. Mirrors gpu/gpu_template.cl lines 203-207:\n"
    "     *   salt_buf  -- concatenated salt bytes for the whole salt list (not\n"
    "     *                paged); salt N starts at salt_off[N], length is\n"
    "     *                salt_lens[N]. Host uploads the full list once via\n"
    "     *                gpu_metal_set_salt (mirrors gpu_opencl_set_salts).\n"
    "     *   salt_off  -- per-salt byte offset into salt_buf (uint32 array).\n"
    "     *   salt_lens -- per-salt length (uint16 array).\n"
    "     * Buffer indices 15/16/17 -- gap-tolerant; 14 is buf_scratch_pool,\n"
    "     * 12/13 mask, 10/11 rules. Apple Metal driver-validated to accept the\n"
    "     * gap layout when MS variant binds 12/13 + 15/16/17 without 10/11. */\n"
    "    device const uchar    *salt_buf         [[buffer(15)]],\n"
    "    device const uint     *salt_off         [[buffer(16)]],\n"
    "    device const ushort   *salt_lens        [[buffer(17)]],\n"
    "#endif\n"
    "    /* Task #250 scratch-pool migration. The per-lane 40 KB `buf` was previously\n"
    "     * `thread uchar buf[RULE_BUF_MAX]` — a lane-private register array. On\n"
    "     * M1 / Apple Silicon Phase 2a the compiler accepted this; on M2 Max\n"
    "     * (T6020, larger SIMD width / different register-allocator headroom)\n"
    "     * the PSO-create gate rejects it: \"Compute function exceeds available\n"
    "     * temporary registers\". RULE_BUF_MAX cannot be truncated without\n"
    "     * losing rule-output coverage (per memo §1; user load-bearing).\n"
    "     *\n"
    "     * Solution: move buf to device storage. Host allocates one MTLBuffer\n"
    "     * sized num_words * RULE_BUF_MAX (640 MB at the 16K-word peak — fits\n"
    "     * comfortably in M1 16 GB / M2 Max 96+ GB unified memory). Each lane\n"
    "     * owns the slice `buf_scratch_pool + word_idx * RULE_BUF_MAX`. The\n"
    "     * kernel restructure (this revision) makes the outer grid one-thread-\n"
    "     * per-word and folds the rule × mask axes into an inner double-loop\n"
    "     * — same shape as hashcat's canonical per-word inner-loop model.\n"
    "     *\n"
    "     * Always bound (all four PSO variants). The OpenCL twin keeps `buf`\n"
    "     * in __private because OpenCL drivers spill to global transparently;\n"
    "     * Apple Metal does NOT spill, so the move is required, not optional. */\n"
    "    device uchar          *buf_scratch_pool [[buffer(14)]],\n"
    "    uint                   gid              [[thread_position_in_grid]]\n"
    "#ifdef GPU_TEMPLATE_HAS_LOCAL_BUFFER\n"
    "    ,\n"
    "    /* Phase 2d.9b BCRYPT: per-lane index within the workgroup. Used to\n"
    "     * partition the threadgroup-shared sbox_pool into per-lane 1024-uint\n"
    "     * slots (sbox_pool + lid * 1024). Only added under HAS_LOCAL_BUFFER\n"
    "     * so non-BCRYPT instantiations keep their exact pre-2d.9b signature\n"
    "     * (byte-identity gate per TRAP 1 of the Phase 2d.9b brief). */\n"
    "    uint                   lid              [[thread_position_in_threadgroup]]\n"
    "#endif\n"
    "    )\n"
    "{\n"
    "    /* Decode payload header. Copy params to thread (lane-private) memory\n"
    "     * so subsequent field accesses stay in registers — same optimization\n"
    "     * as the OpenCL twin (`OCLParams params = *params_buf;`). */\n"
    "    device const MetalParams *params_buf =\n"
    "        (device const MetalParams *)payload;\n"
    "    MetalParams params = *params_buf;\n"
    "\n"
    "    uint n_words = params.num_words;\n"
    "#ifdef GPU_TEMPLATE_HAS_RULES\n"
    "    /* params.num_masks carries the per-dispatch rule COUNT (which may\n"
    "     * be smaller than the total rule program when host-side rule-axis\n"
    "     * sub-batching is in effect — task #250). The synthetic no-rule\n"
    "     * pass uploads n_rules==1 with a 1-byte program containing NUL.\n"
    "     *\n"
    "     * params.salt_start carries the per-dispatch rule BASE (offset into\n"
    "     * the rule_offset[] table). The kernel loops over rule_idx in\n"
    "     * [rule_base, rule_base + rule_count). combined_ridx packs the\n"
    "     * absolute rule_idx so hit-replay decoding sees a stable index\n"
    "     * across all sub-batches.\n"
    "     *\n"
    "     * Sub-batching exists to keep per-dispatch kernel runtime below\n"
    "     * Apple's `kIOGPUCommandBufferCallbackErrorImpactingInteractivity`\n"
    "     * watchdog (~2 second hard wall). On 100K-rule programs an unsplit\n"
    "     * dispatch would inner-loop 100K rules per word lane; chunked\n"
    "     * dispatches inner-loop a few hundred rules each. salt_start is\n"
    "     * unused in the non-salt MD5 path so we overload it cleanly. */\n"
    "    uint rule_count = params.num_masks;\n"
    "    if (rule_count == 0u) rule_count = 1u;\n"
    "    /* Phase 2c: read rule_base from params.rule_cursor_start (its real\n"
    "     * meaning -- offset into rule_offset[] for sub-batching). Previously\n"
    "     * (Phase 2b) we overloaded params.salt_start because HAS_SALT was undef\n"
    "     * and params.salt_start carried no other meaning. With the salt axis\n"
    "     * arriving in Phase 2c, params.salt_start returns to its OpenCL\n"
    "     * semantics (salt-page start). The OCLParams field rule_cursor_start\n"
    "     * at offset 92 has been claimed for real use (see\n"
    "     * feedback_rename_reserved_slots.md); gpu_metal.m writes it under the\n"
    "     * same name in lockstep. */\n"
    "    uint rule_base  = params.rule_cursor_start;\n"
    "#else\n"
    "    uint rule_count = 1u;\n"
    "    uint rule_base  = 0u;\n"
    "#endif\n"
    "\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    /* Phase 2c salt-axis geometry. num_salts is overloaded as\n"
    "     *   num_salts = mask_size * num_salts_per_page\n"
    "     * so mask_size below is derived via division (mirrors\n"
    "     * gpu_template.cl:251-256). For Phase 2c num_salts_per_page is 1\n"
    "     * (single dispatch per salt batch), so the math collapses to\n"
    "     * mask_size == num_salts and the unsalted Phase 2b layout is\n"
    "     * preserved bit-identically. */\n"
    "    uint num_salts_per_page = (uint)params.num_salts_per_page;\n"
    "    if (num_salts_per_page == 0u) num_salts_per_page = 1u;\n"
    "#endif\n"
    "\n"
    "#ifdef GPU_TEMPLATE_HAS_MASK\n"
    "    /* Phase 2b row 1 mask geometry. Mirrors gpu_template.cl lines 216-275.\n"
    "     * mask_size derivation depends on whether the salt axis is also active:\n"
    "     *   - HAS_SALT undef (2b): mask_size = num_salts.\n"
    "     *   - HAS_SALT defined (2c): mask_size = num_salts / num_salts_per_page\n"
    "     *     (mirrors gpu_template.cl:251-256 overload).\n"
    "     *\n"
    "     * mask_active is the gate: a mask is in scope only when n_prepend or\n"
    "     * n_append is >= 1. With no mask, the kernel collapses to the (word,\n"
    "     * rule) shape (mask_size==1). */\n"
    "    uint mask_active = ((params.n_prepend >= 1u) || (params.n_append >= 1u)) ? 1u : 0u;\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "    uint mask_size = mask_active\n"
    "        ? (params.num_salts / num_salts_per_page)\n"
    "        : 1u;\n"
    "#else\n"
    "    uint mask_size = mask_active ? params.num_salts : 1u;\n"
    "#endif\n"
    "    if (mask_size == 0u) mask_size = 1u;\n"
    "#else\n"
    "    uint mask_size = 1u;\n"
    "#endif\n"
    "\n"
    "    /* Task #250: kernel restructure — one thread per word; rule × mask\n"
    "     * axes fold into an inner double-loop. The OpenCL twin keeps all\n"
    "     * three axes on the outer grid (OpenCL drivers spill thread-private\n"
    "     * arrays transparently to global so the 40 KB per-lane buf cost is\n"
    "     * paid once per-PE not once per-lane). Apple Metal does NOT spill —\n"
    "     * the only way to keep RULE_BUF_MAX at 40 KB is one device-buf slice\n"
    "     * per lane, and the cheapest \"slice per lane\" indexing is to make\n"
    "     * each lane own ONE word for its entire run. The inner double-loop\n"
    "     * mirrors hashcat's canonical per-word inner-loop model.\n"
    "     *\n"
    "     * Implications:\n"
    "     *   - Outer grid = n_words (was n_words * n_rules * mask_size).\n"
    "     *   - Per-lane buf pool slot = buf_scratch_pool[gid * RULE_BUF_MAX].\n"
    "     *     Reused across the inner double-loop iterations; the original\n"
    "     *     word must be re-staged from `words[]` at the top of each rule\n"
    "     *     iteration since the previous rule mutated buf in place.\n"
    "     *   - combined_ridx packing is unchanged (rule_idx, mask_idx_local).\n"
    "     *   - Hit dedup / overflow semantics unchanged. Hit order may differ\n"
    "     *     from the prior grid layout (per-word clustering instead of\n"
    "     *     interleaved), but gpujob_metal.m's hit-replay does not depend\n"
    "     *     on order; CPU-side sort + dedup absorbs any reshuffling. */\n"
    "    if (gid >= n_words) return;\n"
    "    uint word_idx = gid;\n"
    "\n"
    "    /* B3 cursor protocol read-only in Phase 1/2a. The kernel reads the\n"
    "     * fields so the wire format stays the same; never advances past\n"
    "     * gid==word_idx 0..n_words-1. Phase 2b+ wires the mask half. */\n"
    "    /* (no-op: input_cursor_start / rule_cursor_start are populated 0). */\n"
    "\n"
    "    /* --- Payload sub-buffer pointers (wire format invariant) --- */\n"
    "    device atomic_uint *hit_count =\n"
    "        (device atomic_uint *)(payload + 128);\n"
    "    device const uint  *word_offset =\n"
    "        (device const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    device const uchar *words = payload + pkt_off;\n"
    "\n"
    "    /* Overflow channel pointers (offsets 100, 104 — inside params).\n"
    "     * Typed as atomic_uint per Pattern 1 + Metal atomics. */\n"
    "    device atomic_uint *ovr_set =\n"
    "        (device atomic_uint *)(payload + 100);\n"
    "    device atomic_uint *ovr_gid =\n"
    "        (device atomic_uint *)(payload + 104);\n"
    "\n"
    "    /* Per-lane work buffer slice. Lives in device memory now (task #250\n"
    "     * — see signature comment for buf_scratch_pool). Each lane owns\n"
    "     * RULE_BUF_MAX contiguous bytes starting at slot[word_idx]. */\n"
    "    device uchar *buf =\n"
    "        buf_scratch_pool + (ulong)word_idx * (ulong)RULE_BUF_MAX;\n"
    "\n"
    "#ifdef GPU_TEMPLATE_HAS_RULES32\n"
    "    /* The UTF-32 lane's three working regions, carved out of one slot so the\n"
    "     * host binds one buffer:\n"
    "     *\n"
    "     *   [0                        .. U32_BUF_ELEMS*4)   u32buf  (codepoints)\n"
    "     *   [U32_BUF_ELEMS*4          .. 2*U32_BUF_ELEMS*4) u32mem  (memory verbs)\n"
    "     *   [2*U32_BUF_ELEMS*4        .. + U32_OUT_BYTES)   the CANDIDATE bytes\n"
    "     *\n"
    "     * All three are 4-aligned by construction (U32_SLOT_BYTES is a multiple of\n"
    "     * 16 and an MTLBuffer base is at least 16-aligned), which the uint casts\n"
    "     * require -- MSL vector and scalar loads are undefined when misaligned.\n"
    "     *\n"
    "     * `buf` is REPOINTED at the candidate region, and that is deliberate\n"
    "     * rather than tidy: it is U32_OUT_BYTES (8192) where buf_scratch_pool's\n"
    "     * slot is RULE_BUF_MAX (2048), and the UTF-32 encode can produce up to 4\n"
    "     * bytes per codepoint.  Encoding into the 2048-byte slot would truncate\n"
    "     * where the OpenCL kernel does not, and the two backends would disagree\n"
    "     * on exactly the long-candidate cases hardest to notice.  The BYTE arm is\n"
    "     * unaffected: apply_rule bounds itself at RULE_BUF_LIMIT regardless. */\n"
    "    device uchar *u32slot =\n"
    "        u32_scratch_pool + (ulong)word_idx * (ulong)U32_SLOT_BYTES;\n"
    "    device uint  *u32buf  = (device uint *)(u32slot);\n"
    "    device uint  *u32mem  = (device uint *)(u32slot + (ulong)U32_BUF_ELEMS * 4u);\n"
    "    buf = u32slot + (ulong)U32_BUF_ELEMS * 8u;\n"
    "#endif\n"
    "\n"
    "    /* Phase 2d.9b BCRYPT (2026-05-16): workgroup-shared threadgroup buffer\n"
    "     * for the Eksblowfish S-boxes (4 x 256 uint = 4 KB per lane x\n"
    "     * BCRYPT_WG_SIZE lanes = 32 KB per workgroup). Declared at kernel-\n"
    "     * function scope (Metal requires threadgroup decls at function scope);\n"
    "     * passed by pointer to template_finalize via the 8-arg signature\n"
    "     * variant below (gated on GPU_TEMPLATE_HAS_LOCAL_BUFFER). When the\n"
    "     * macro is UNDEFINED (every algo other than BCRYPT), the preprocessor\n"
    "     * strips this block entirely -- non-BCRYPT instantiations are byte-\n"
    "     * identical to pre-Phase-2d.9b. Mirrors gpu_template.cl lines 370-372\n"
    "     * (the OpenCL twin's __local sbox_pool) byte-for-byte.\n"
    "     *\n"
    "     * Apple Silicon maxThreadgroupMemoryLength = 32 KB exactly matches\n"
    "     * BCRYPT_WG_SIZE=8 lanes x 1024 uint x 4 bytes/uint = 32 KB. The\n"
    "     * dispatch site in gpu_metal.m forces threadsPerThreadgroup = 8 for\n"
    "     * JOB_BCRYPT specifically (per TRAP 2 of the Phase 2d.9b brief); any\n"
    "     * larger workgroup would overflow Apple's per-workgroup threadgroup\n"
    "     * memory cap. */\n"
    "#ifdef GPU_TEMPLATE_HAS_LOCAL_BUFFER\n"
    "    threadgroup uint sbox_pool[BCRYPT_WG_SIZE * GPU_TEMPLATE_LOCAL_BUFFER_PER_LANE];\n"
    "#endif\n"
    "\n"
    "    /* Cache word origin (wpos, wlen) once outside the inner loop.\n"
    "     * Each rule iteration re-stages buf[0..wlen) from words[]. */\n"
    "    uint raw_woff = word_offset[word_idx];\n"
    "#ifdef GPU_TEMPLATE_HAS_RULES32\n"
    "    /* Bits 30-31 carry the per-word CLASS (0 = A ascii, 1 = W utf8-wide,\n"
    "     * 2 = I undecodable), written by the host at submit.  MASK THEM OFF before\n"
    "     * using the offset -- the byte-only variants do not, which is why the tag\n"
    "     * and the kernel that reads it must be decided by one predicate.  Failing\n"
    "     * to mask cost a `md5_rules ovr-state read err=-5` on OpenCL. */\n"
    "    uint wcls = raw_woff >> U32_TAG_SHIFT;\n"
    "    uint wpos = raw_woff & U32_OFF_MASK;\n"
    "#else\n"
    "    uint wpos = raw_woff;\n"
    "#endif\n"
    "    int wlen_orig = (int)words[wpos] | ((int)words[wpos + 1] << 8);\n"
    "    wpos += 2;   /* 2-byte little-endian length: see gpujob.h */\n"
    "    if (wlen_orig > RULE_BUF_LIMIT) wlen_orig = RULE_BUF_LIMIT;\n"
    "\n"
    "    /* Inner double-loop: rule_idx (outer) × mask_idx_local (inner). The\n"
    "     * structure is identical for all four PSO variants — collapsing axes\n"
    "     * (mask_size==1 or rule_count==1) just makes the loop body run once\n"
    "     * on that axis. The runtime gate macros isolate the per-axis side\n"
    "     * effects (rule walker, mask expansion, combined_ridx packing).\n"
    "     *\n"
    "     * rule_idx iterates [rule_base, rule_base + rule_count) — when host-\n"
    "     * side sub-batching is active, rule_base is non-zero and rule_count\n"
    "     * is smaller than the total program. The synthetic no-rule pass is\n"
    "     * processed inside the same range (host populates the program at\n"
    "     * absolute rule_idx==0; sub-batches that include rule_base==0 also\n"
    "     * include the synthetic pass). */\n"
    "    uint rule_end = rule_base + rule_count;\n"
    "    for (uint rule_idx = rule_base; rule_idx < rule_end; rule_idx++) {\n"
    "        (void)rule_idx;  /* silence -Wunused when neither axis defined */\n"
    "\n"
    "        for (uint mask_idx_local = 0u; mask_idx_local < mask_size; mask_idx_local++) {\n"
    "            (void)mask_idx_local;\n"
    "\n"
    "            /* Re-stage the input word into buf[0..wlen). Previous inner-\n"
    "             * loop iteration may have mutated buf via rules walker\n"
    "             * and/or mask expansion. Cost = wlen bytes per (rule, mask)\n"
    "             * tuple — typically 6-20 bytes (rockyou word length); the\n"
    "             * rule walker + MD5 finalize dwarf this. */\n"
    "            int wlen = wlen_orig;\n"
    "            for (int i = 0; i < wlen; i++) buf[i] = words[wpos + i];\n"
    "\n"
    "#ifdef GPU_TEMPLATE_HAS_RULES\n"
    "            /* Rules-engine walker (OpenCL twin gpu_template.cl lines 379-403).\n"
    "             * apply_rule() is declared in metal_md5_rules.metal — concatenated\n"
    "             * into the same family TU by build_metallib.sh, AND prepended to\n"
    "             * the JIT source by gpu_metal.m's rules-variant compile path.\n"
    "             * Note: apply_rule's `buf` is `device uchar *` post task #250. */\n"
    "            uint rpos = rule_offset[rule_idx];\n"
    "\n"
    "            /* Synthetic no-rule discriminator (preserves feedback_no_rule_pass.md\n"
    "             * semantics; mirrors gpu_md5_rules.cl rev 1.28). The first byte\n"
    "             * being NUL means k==0 at apply_rule entry == the synthetic no-\n"
    "             * rule pass. */\n"
    "            int is_no_rule = (rule_program[rpos] == 0);\n"
    "#ifdef GPU_TEMPLATE_HAS_RULES32\n"
    "            /* ---- PER-LANE ENGINE CHOICE ----------------------------------\n"
    "             *\n"
    "             * The Metal twin of md5_rules_mixed_phase0.  u32_run_pair() is the\n"
    "             * SHARED body out of gpu_u32_walker.inc -- the same function the\n"
    "             * OpenCL kernel calls, not a second copy -- because its signature\n"
    "             * was already expressible in the address-space macros the walker\n"
    "             * uses.  It reproduces pick_engine() exactly: class W or a\n"
    "             * u32-only rule goes to UTF-32, class I with no byte form is\n"
    "             * skipped, everything else takes the byte walker.\n"
    "             *\n"
    "             * The candidate lands in `buf`, which points at the slot's\n"
    "             * candidate region here, so everything downstream -- mask\n"
    "             * expansion, the no-op test, template_finalize -- is unchanged.\n"
    "             *\n"
    "             * `engine` is written but not read: the arm taken is already\n"
    "             * implied by the bytes, and the host replay re-derives it from the\n"
    "             * DEVICE's own capability bits rather than trusting a flag that\n"
    "             * would have to survive the hit buffer. */\n"
    "            /* The second half of rule_offset is indexed by the TOTAL device\n"
    "             * rule count, and on Metal that is NOT rule_count: this backend\n"
    "             * sub-batches the rule axis to stay under Apple's ~2 s command\n"
    "             * buffer watchdog, so params.num_masks carries the SUB-BATCH size.\n"
    "             * OpenCL does not sub-batch here and uses num_masks as the total,\n"
    "             * so the two backends genuinely read the total from different\n"
    "             * fields -- stated rather than left to be inferred.  gpu_metal.m\n"
    "             * writes params.num_rules (offset 108, documented as \"source rule\n"
    "             * count\") with the total in lockstep. */\n"
    "            uint u32_total_rules = params.num_rules;\n"
    "            if (u32_total_rules == 0u) u32_total_rules = rule_count;\n"
    "            int engine = 0;\n"
    "            int new_len = u32_run_pair(words, wpos, wlen, rule_program,\n"
    "                                       rpos, rule_offset[u32_total_rules + rule_idx],\n"
    "                                       wcls, buf, u32buf, u32mem,\n"
    "                                       buf, U32_OUT_BYTES,\n"
    "                                       u32_case_tab, &engine);\n"
    "#else\n"
    "            int new_len = apply_rule(rule_program + rpos, buf, wlen);\n"
    "#endif\n"
    "\n"
    "            /* Rejection sentinel: apply_rule fired a `_ < > ! / ( )` op. */\n"
    "            if (new_len < 0) continue;\n"
    "\n"
    "            /* No-op detection: if at least one op was processed AND the\n"
    "             * post-rule buffer is bit-identical to the input, the synthetic\n"
    "             * no-rule pass already covered this candidate -- skip hash +\n"
    "             * probe. Per feedback_no_rule_pass.md. */\n"
    "            if (!is_no_rule && new_len == wlen) {\n"
    "                int changed = 0;\n"
    "                for (int i = 0; i < wlen; i++) {\n"
    "                    if (buf[i] != words[wpos + i]) { changed = 1; break; }\n"
    "                }\n"
    "                if (!changed) continue;\n"
    "            }\n"
    "#else\n"
    "            int new_len = wlen;\n"
    "#endif\n"
    "\n"
    "#ifdef GPU_TEMPLATE_HAS_MASK\n"
    "            /* Phase 2b row 1 mask: decompose mask_idx into prepend+append\n"
    "             * per-position indices and modify buf in-place. Mirrors\n"
    "             * gpu_template.cl lines 405-531. Steps 1-4 identical to\n"
    "             * pre-task-#250 layout — only address space of `buf` changes. */\n"
    "            uint npre = params.n_prepend;\n"
    "            uint napp = params.n_append;\n"
    "            if (npre > 16u) npre = 16u;\n"
    "            if (napp > 16u) napp = 16u;\n"
    "\n"
    "            ulong mask_idx_abs = (ulong)params.mask_start\n"
    "                               + (ulong)word_idx * (ulong)params.mask_offset_per_word\n"
    "                               + (ulong)mask_idx_local;\n"
    "\n"
    "            if (npre >= 1u || napp >= 1u) {\n"
    "                ulong append_combos = 1u;\n"
    "                for (uint j = 0u; j < napp; j++) {\n"
    "                    uint sz = mask_sizes[npre + j];\n"
    "                    if (sz == 0u) sz = 1u;\n"
    "                    append_combos *= (ulong)sz;\n"
    "                }\n"
    "                if (append_combos == 0u) append_combos = 1u;\n"
    "                ulong prepend_idx = mask_idx_abs / append_combos;\n"
    "                ulong append_idx  = mask_idx_abs % append_combos;\n"
    "\n"
    "                /* Step 1: shift buf right by npre bytes, high to low to\n"
    "                 * avoid clobber. */\n"
    "                if (npre > 0u) {\n"
    "                    uint shift_dst_end = (uint)new_len + npre;\n"
    "                    if (shift_dst_end > RULE_BUF_LIMIT) {\n"
    "                        if ((uint)new_len + npre > RULE_BUF_LIMIT) {\n"
    "                            if (new_len > (int)(RULE_BUF_LIMIT - npre))\n"
    "                                new_len = (int)(RULE_BUF_LIMIT - npre);\n"
    "                        }\n"
    "                    }\n"
    "                    for (int i = new_len - 1; i >= 0; i--) {\n"
    "                        buf[i + (int)npre] = buf[i];\n"
    "                    }\n"
    "                }\n"
    "\n"
    "                /* Step 2: write prepend chars at buf[0..npre). */\n"
    "                if (npre > 0u) {\n"
    "                    ulong remaining = prepend_idx;\n"
    "                    for (uint k = 0u; k < npre; k++) {\n"
    "                        uint i = npre - 1u - k;\n"
    "                        uint psize = mask_sizes[i];\n"
    "                        if (psize == 0u) psize = 1u;\n"
    "                        uint pidx = (uint)(remaining % (ulong)psize);\n"
    "                        remaining /= (ulong)psize;\n"
    "                        if (i < RULE_BUF_LIMIT) {\n"
    "                            buf[i] = mask_charsets[i * 256u + pidx];\n"
    "                        }\n"
    "                    }\n"
    "                }\n"
    "\n"
    "                /* Step 3: write append chars. */\n"
    "                if (napp > 0u) {\n"
    "                    uint append_base = (uint)new_len + npre;\n"
    "                    ulong remaining = append_idx;\n"
    "                    for (uint k = 0u; k < napp; k++) {\n"
    "                        uint i = napp - 1u - k;\n"
    "                        uint row = npre + i;\n"
    "                        uint psize = mask_sizes[row];\n"
    "                        if (psize == 0u) psize = 1u;\n"
    "                        uint pidx = (uint)(remaining % (ulong)psize);\n"
    "                        remaining /= (ulong)psize;\n"
    "                        uint dst = append_base + i;\n"
    "                        if (dst < RULE_BUF_LIMIT) {\n"
    "                            buf[dst] = mask_charsets[row * 256u + pidx];\n"
    "                        }\n"
    "                    }\n"
    "                }\n"
    "\n"
    "                /* Step 4: advance new_len. Truncate at RULE_BUF_LIMIT. */\n"
    "                uint new_total = (uint)new_len + npre + napp;\n"
    "                if (new_total <= RULE_BUF_LIMIT) {\n"
    "                    new_len = (int)new_total;\n"
    "                } else {\n"
    "                    new_len = RULE_BUF_LIMIT;\n"
    "                }\n"
    "            }\n"
    "#endif\n"
    "\n"
    "            /* Phase 2c salt-inner loop. With HAS_SALT undef this loop\n"
    "             * collapses to a single iteration (salt_count==1, salt_local\n"
    "             * always 0) -- bit-identical to the Phase 2b layout. With\n"
    "             * HAS_SALT defined the loop iterates num_salts_per_page\n"
    "             * salts, each with its own template_finalize(salt) call;\n"
    "             * the digest_compare + emit body runs once per (rule, mask,\n"
    "             * salt) triple.\n"
    "             *\n"
    "             * Salt-inner (not salt-outer) keeps the post-task-#250 one-\n"
    "             * lane-per-word invariant unbroken -- the 40 KB scratch buf\n"
    "             * belongs to one word, and rebinding salt outside the lane\n"
    "             * would waste the scratch slot. For Phase 2c with\n"
    "             * num_salts_per_page=1 the loop runs once per lane (no perf\n"
    "             * cost vs salt-outer); Phase 2d/2e can refactor to salt-outer\n"
    "             * when num_salts_per_page > 1 becomes real. Mirrors\n"
    "             * gpu_template.cl:243-256 + 562-585 + 639-644.\n"
    "             *\n"
    "             * Phase 2e GPU_TEMPLATE_HAS_PRE_SALT: hoist the inner\n"
    "             * MD5(password) + hex32 encoding ONCE per (word, rule, mask)\n"
    "             * via template_pre_salt(), then iterate the salt list calling\n"
    "             * template_finalize_post() which consumes the carrier.\n"
    "             * SALT_BATCH controls the inner tile size -- when the salt\n"
    "             * loop body is small enough, the Metal compiler unrolls the\n"
    "             * SALT_BATCH-stride inner cycle, amortising rule/mask\n"
    "             * overhead across SALT_BATCH outer-MD5 evaluations. The\n"
    "             * iteration still covers the full num_salts_per_page;\n"
    "             * SALT_BATCH is an unroll knob, not a per-dispatch chunk\n"
    "             * boundary (host outer chunking via METAL_SALT_CHUNK_SIZE\n"
    "             * is orthogonal). Mirrors gpu_template.cl:534-585. */\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "            uint salt_count = num_salts_per_page;\n"
    "#else\n"
    "            uint salt_count = 1u;\n"
    "#endif\n"
    "#if defined(GPU_TEMPLATE_HAS_PRE_SALT) && defined(GPU_TEMPLATE_HAS_SALT)\n"
    "            /* Pre-salt hoist: compute password-only inner-MD5 + hex32\n"
    "             * once per (word, rule, mask). All SALT_BATCH-tiled salt\n"
    "             * iterations below reuse pre_state. */\n"
    "            template_pre_salt_state pre_state;\n"
    "            template_pre_salt(buf, new_len, params.algo_mode, pre_state);\n"
    "#endif\n"
    "            for (uint salt_base = 0u; salt_base < salt_count; salt_base += (uint)SALT_BATCH) {\n"
    "                uint tile_end = salt_base + (uint)SALT_BATCH;\n"
    "                if (tile_end > salt_count) tile_end = salt_count;\n"
    "                for (uint salt_local = salt_base; salt_local < tile_end; salt_local++) {\n"
    "                (void)salt_local;\n"
    "\n"
    "                /* MD5(buf[0..new_len-1]) or MD5SALT(buf, salt). buf is\n"
    "                 * `device const uchar *` (post task #250); the\n"
    "                 * template_finalize variant is selected at TU build time:\n"
    "                 *   - HAS_SALT undef: 3-arg form in metal_md5_core.metal.\n"
    "                 *   - HAS_SALT defined: 6-arg form in metal_md5salt_core.metal.\n"
    "                 * The two TUs are mutually exclusive within one MTLLibrary\n"
    "                 * (only one of metal_md5_core.metal / metal_md5salt_core.metal\n"
    "                 * is concatenated into each PSO variant's JIT source).\n"
    "                 *\n"
    "                 * Phase 2e HAS_PRE_SALT: template_finalize_post consumes\n"
    "                 * pre_state (the hoisted inner-MD5 + hex32) and computes\n"
    "                 * only the outer MD5(hex32 || salt). For algo_mode != 0\n"
    "                 * the carrier is sentinel and the function falls through\n"
    "                 * to the legacy 6-arg template_finalize. */\n"
    "                template_state st;\n"
    "                template_init(st);\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "                /* salt_idx_global = salt_start + salt_local; salt_start\n"
    "                 * is the per-dispatch page base (0 in Phase 2c since\n"
    "                 * num_salts_per_page=1 and we cover the whole salt list\n"
    "                 * in one dispatch). */\n"
    "                uint salt_idx_global = (uint)params.salt_start + salt_local;\n"
    "                uint  s_off = salt_off[salt_idx_global];\n"
    "                uint  s_len = (uint)salt_lens[salt_idx_global];\n"
    "#ifdef GPU_TEMPLATE_HAS_PRE_SALT\n"
    "                template_finalize_post(st, pre_state,\n"
    "                                       buf, new_len,\n"
    "                                       salt_buf + s_off, s_len,\n"
    "                                       params.algo_mode);\n"
    "#else\n"
    "#ifdef GPU_TEMPLATE_HAS_LOCAL_BUFFER\n"
    "                /* Phase 2d.9b BCRYPT (2026-05-16): 8-arg signature variant.\n"
    "                 * Mirrors gpu_template.cl line 577-578 byte-for-byte. The\n"
    "                 * threadgroup-shared sbox_pool + lid are passed so the\n"
    "                 * core's template_finalize claims its 1024-uint per-lane\n"
    "                 * partition (sbox_pool + lid * 1024). Gated on\n"
    "                 * GPU_TEMPLATE_HAS_LOCAL_BUFFER; only the BCRYPT carrier\n"
    "                 * compile sets this define via preprocessorMacros in the\n"
    "                 * Metal library loader. */\n"
    "                template_finalize(st, buf, new_len,\n"
    "                                  salt_buf + s_off, s_len,\n"
    "                                  params.algo_mode,\n"
    "                                  sbox_pool, lid);\n"
    "#else\n"
    "                template_finalize(st, buf, new_len,\n"
    "                                  salt_buf + s_off, s_len,\n"
    "                                  params.algo_mode);\n"
    "#endif\n"
    "#endif\n"
    "#else\n"
    "                template_finalize(st, buf, new_len);\n"
    "#endif\n"
    "\n"
    "                /* --- Iterated probe loop — Phase 1 fires it exactly once. --- */\n"
    "                uint max_iter = params.max_iter;\n"
    "                if (max_iter < 1u) max_iter = 1u;\n"
    "                for (uint iter = 1u; iter <= max_iter; iter++) {\n"
    "                    uint matched_idx = 0u;\n"
    "                    if (template_digest_compare(st,\n"
    "                                                compact_fp, compact_idx,\n"
    "                                                params.compact_mask, params.max_probe,\n"
    "                                                params.hash_data_count,\n"
    "                                                hash_data_buf, hash_data_off,\n"
    "                                                overflow_keys, overflow_hashes,\n"
    "                                                overflow_offsets, params.overflow_count,\n"
    "                                                &matched_idx))\n"
    "                    {\n"
    "                        /* combined_ridx packing -- extends Phase 2b with salt:\n"
    "                         *   HAS_SALT:  combined_ridx = ((rule * mask_size +\n"
    "                         *               mask_local) * num_salts_per_page) +\n"
    "                         *               salt_local\n"
    "                         *   no SALT:   Phase 2b packing (rule * mask_size +\n"
    "                         *               mask_local) etc.\n"
    "                         * Mirrors gpu_template.cl:639-651. Hit-replay\n"
    "                         * divmods by num_salts_per_page (salt-axis), then\n"
    "                         * mask_size (mask-axis), to recover all three\n"
    "                         * indices. Host post-processes the salt_local\n"
    "                         * field to salt_idx_global by adding params.salt_start\n"
    "                         * (no-op for num_salts_per_page=1 / salt_start=0). */\n"
    "#if defined(GPU_TEMPLATE_HAS_RULES) && defined(GPU_TEMPLATE_HAS_MASK) && defined(GPU_TEMPLATE_HAS_SALT)\n"
    "                        uint combined_ridx =\n"
    "                            (rule_idx * mask_size + mask_idx_local) * num_salts_per_page +\n"
    "                            salt_local;\n"
    "#elif defined(GPU_TEMPLATE_HAS_RULES) && defined(GPU_TEMPLATE_HAS_SALT)\n"
    "                        uint combined_ridx =\n"
    "                            rule_idx * num_salts_per_page + salt_local;\n"
    "#elif defined(GPU_TEMPLATE_HAS_MASK) && defined(GPU_TEMPLATE_HAS_SALT)\n"
    "                        uint combined_ridx =\n"
    "                            mask_idx_local * num_salts_per_page + salt_local;\n"
    "#elif defined(GPU_TEMPLATE_HAS_SALT)\n"
    "                        uint combined_ridx = salt_local;\n"
    "#elif defined(GPU_TEMPLATE_HAS_RULES) && defined(GPU_TEMPLATE_HAS_MASK)\n"
    "                        uint combined_ridx = rule_idx * mask_size + mask_idx_local;\n"
    "#elif defined(GPU_TEMPLATE_HAS_RULES)\n"
    "                        uint combined_ridx = rule_idx;\n"
    "#elif defined(GPU_TEMPLATE_HAS_MASK)\n"
    "                        uint combined_ridx = mask_idx_local;\n"
    "#else\n"
    "                        uint combined_ridx = 0u;\n"
    "#endif\n"
    "                        uint mask = 1u << (iter & 31u);\n"
    "                        template_emit_hit_or_overflow(hits, hit_count, params.max_hits,\n"
    "                                                      st, word_idx, combined_ridx, iter,\n"
    "                                                      hashes_shown, matched_idx, mask,\n"
    "                                                      ovr_set, ovr_gid, gid);\n"
    "                    }\n"
    "#ifdef GPU_TEMPLATE_HAS_ALT_DIGEST\n"
    "                    /* SECOND DIGEST VARIANT -- Metal twin of the block in\n"
    "                     * gpu_template.cl (added there 2026-09-15, ported here\n"
    "                     * 2026-09-16).  Its absence was one of the two real\n"
    "                     * OpenCL->Metal port gaps: gpu_template.cl had this hook\n"
    "                     * and metal_template.metal had no reference to it at all.\n"
    "                     *\n"
    "                     * Some CPU algorithms compute more than one digest per\n"
    "                     * candidate and count a match on ANY of them.  JOB_NTLMH\n"
    "                     * is the one that needs it: mdxfind.c hashes the candidate\n"
    "                     * BOTH through iconv to UTF-16LE and through a byte\n"
    "                     * zero-extend, and checkhash()es each.  A single-probe\n"
    "                     * kernel covers only one, and the arm it does not cover is\n"
    "                     * UNREACHABLE rather than merely slow, because the GPU\n"
    "                     * claims the batch and the CPU never redoes the work -- so\n"
    "                     * the run exits 0 saying \"None found, sorry!\".  On Metal\n"
    "                     * that is exactly what happened: the core computed both\n"
    "                     * digests and only the zero-extend one was ever compared,\n"
    "                     * so a non-ASCII password (whose correct answer is the\n"
    "                     * UTF-16LE digest) missed in byte mode as well as -8.\n"
    "                     *\n"
    "                     * Only a core defining GPU_TEMPLATE_HAS_ALT_DIGEST\n"
    "                     * compiles this; today that is metal_ntlmh_core.metal\n"
    "                     * alone, so every other program's text is unchanged.\n"
    "                     *\n"
    "                     * Mutually exclusive with the salt axis, same as the\n"
    "                     * OpenCL twin: a salted alt-digest carrier would need the\n"
    "                     * three-axis combined_ridx encoding and has no caller. */\n"
    "#ifdef GPU_TEMPLATE_HAS_SALT\n"
    "#error \"GPU_TEMPLATE_HAS_ALT_DIGEST is unsalted-only; no salted carrier exists\"\n"
    "#endif\n"
    "                    {\n"
    "                        uint matched_idx_alt = 0u;\n"
    "                        if (template_digest_compare_alt(st,\n"
    "                                        compact_fp, compact_idx,\n"
    "                                        params.compact_mask, params.max_probe,\n"
    "                                        params.hash_data_count,\n"
    "                                        hash_data_buf, hash_data_off,\n"
    "                                        overflow_keys, overflow_hashes,\n"
    "                                        overflow_offsets, params.overflow_count,\n"
    "                                        &matched_idx_alt))\n"
    "                        {\n"
    "                            uint combined_ridx_alt =\n"
    "                                rule_idx * mask_size + mask_idx_local;\n"
    "                            uint mask_alt = 1u << (iter & 31u);\n"
    "                            template_emit_hit_alt_or_overflow(hits, hit_count,\n"
    "                                              params.max_hits,\n"
    "                                              st, word_idx, combined_ridx_alt, iter,\n"
    "                                              hashes_shown, matched_idx_alt, mask_alt,\n"
    "                                              ovr_set, ovr_gid, gid);\n"
    "                        }\n"
    "                    }\n"
    "#endif /* GPU_TEMPLATE_HAS_ALT_DIGEST */\n"
    "                    /* Advance to the next -i iteration. Mirrors\n"
    "                     * gpu_template.cl lines 666-677 exactly: the step is\n"
    "                     * taken only BETWEEN probes, never after the last one.\n"
    "                     *\n"
    "                     * This call was stubbed out in Phase 1 (max_iter==1\n"
    "                     * only) and the \"Phase 2 re-adds it\" note was never\n"
    "                     * acted on, so every family served by this legacy\n"
    "                     * carrier probed the SAME digest max_iter times and\n"
    "                     * could only ever report x01. Codegen-eligible ops\n"
    "                     * hid the defect because gpu/codegen_auto_dispatch.c\n"
    "                     * routes (Metal, iter>1, rules>0) away from here.\n"
    "                     *\n"
    "                     * B7.7a algo_mode threading: only metal_md5_core.metal\n"
    "                     * defines GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE (uppercase\n"
    "                     * hex for JOB_MD5UC); every other core keeps the legacy\n"
    "                     * one-argument shape. */\n"
    "                    if (iter < max_iter) {\n"
    "#ifdef GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE\n"
    "                        template_iterate(st, params.algo_mode);\n"
    "#else\n"
    "                        template_iterate(st);\n"
    "#endif\n"
    "                    }\n"
    "                }\n"
    "                } /* salt_local (inner tile) */\n"
    "            } /* salt_base (SALT_BATCH-stride outer) */\n"
    "        } /* mask_idx_local */\n"
    "    } /* rule_idx */\n"
    "}\n"
;
