/*
 * $Revision: 1.1 $
 * $Log: metal_sha1passsalt_core.metal,v $
 * Revision 1.1  2026/05/16 01:45:13  dlr
 * Initial revision
 *
 *
 * Auto-generated by gpu/codegen/cl2metal.py from
 *   gpu_sha1passsalt_core.cl (RCS rev ?).
 *
 * Do NOT edit this file directly -- edit the OpenCL twin and
 * re-run cl2metal.py. The translator is intentionally lossless on
 * mechanical transforms; hand-curated Apple-specific tweaks live
 * in gpu/codegen/cl2metal_overrides/<algo>.yaml.
 *
 * Mirrors the byte-exact OpenCL hash chain; address-space port:
 *   __global  -> device
 *   __private -> thread
 *   barrier   -> threadgroup_barrier
 *   typedef struct ... T;  ->  struct T { ... };
 *   T *st     -> thread T &st
 *
 * Patterns 1/3 enforced: every pointer arg is address-space
 * qualified; every helper is static inline.
 */

/* Per-algorithm geometry. */
#ifndef HASH_WORDS
#define HASH_WORDS 5
#endif
#ifndef HASH_BLOCK_BYTES
#define HASH_BLOCK_BYTES 64
#endif

struct template_state {
    uint h[HASH_WORDS];
};

/* template_init: install SHA1 IV (RFC 3174 §6.1). */
static inline void template_init(thread template_state &st)
{
    st.h[0] = 0x67452301u;
    st.h[1] = 0xEFCDAB89u;
    st.h[2] = 0x98BADCFEu;
    st.h[3] = 0x10325476u;
    st.h[4] = 0xC3D2E1F0u;
}

/* template_transform: kept for API completeness — never called on the
 * hot path (template_finalize builds M[16] inline as in gpu_sha1_core.cl).
 * SHA1 reads message words BIG-ENDIAN. */
static inline void template_transform(thread template_state &st,
                                thread const uchar *block)
{
    uint M[16];
    for (int j = 0; j < 16; j++) {
        int b = j * 4;
        M[j] = ((uint)block[b]     << 24)
             | ((uint)block[b + 1] << 16)
             | ((uint)block[b + 2] << 8)
             |  (uint)block[b + 3];
    }
    sha1_block(&st.h[0], M);
}

/* template_finalize: compute sha1(pass || salt).
 *
 * BIG-ENDIAN variant for SHA-family algorithms (SHA1/SHA224/SHA256 —
 * SHA1 ships first as B6.5 SHA1PASSSALT; SHA256PASSSALT reuses this
 * fragment with HASH_WORDS / IV adjustments via the spec). SHA384/512
 * use a 64-bit-state sibling fragment (different block size / length
 * encoding) — out of scope for this fragment.
 *
 * Layout in M[]: password bytes first (offset 0..plen-1), salt bytes
 * second (offset plen..plen+slen-1), then 0x80 padding marker, then
 * zeros, then 64-bit BE length-in-bits in M[14..15] (M[14] = high 32
 * bits, M[15] = low 32 bits). This is the inverse of the BE PREPEND
 * fragment (finalize_prepend_be.cl.frag), which puts salt first; and
 * the BE counterpart of the LE APPEND fragment (finalize_append.cl.frag)
 * which uses the same pass-then-salt order but LE byte placement and
 * LE length encoding.
 *
 * Block boundary handled the same way as the BE PREPEND sibling: if
 * the tail (after 0x80) extends past byte 55 we run a second block
 * whose last 8 bytes hold the length.
 *
 * Each byte's position within its 32-bit word is determined by
 * 3-(byte_idx & 3) shift (BE: byte 0 is high octet of word). This
 * matches gpu_sha1_core.cl's BE M[] build for the unsalted
 * path — only the source of the bytes (pass|salt instead of just data)
 * and the ordering (pass-first vs salt-first) differ.
 *
 * First APPEND-shape SHA-family salted variant on the codegen path:
 * ships SHA1PASSSALT (B6.5 / hashcat -m 100). Future SHA256PASSSALT
 * (hashcat -m 1410's APPEND counterpart, hashcat -m 1420's PREPEND is
 * SHA256SALTPASS) reuses this fragment with no further authoring —
 * the spec drives HASH_WORDS / hash_block_bytes / IV constants.
 *
 * Per feedback_codegen_fragment_width_bugs.md: this fragment does NOT
 * carry a defensive state-IV reinstall. template_init() (in the per-
 * algorithm core, not in this fragment) is the canonical state
 * initializer; reinstalling here would shadow it with width-incorrect
 * constants for non-SHA1 SHA-family algos.
 */
static inline void template_finalize(thread template_state &st,
                                device const uchar *data,
                                int len,
                                device const uchar *salt_buf,
                                uint slen,
                                uint algo_mode)
{
    (void)algo_mode;  /* unused in this fragment; reserved for variant flags */
    uint M[16];
    int total_len = len + (int)slen;
    int pos = 0;

    /* IV install is the responsibility of template_init() — called by
     * template_phase0 BEFORE template_finalize. Per-algorithm IV constants
     * (SHA1 vs SHA256, 5 vs 8 words) live in the per-core file, not in
     * this fragment. (See feedback_codegen_fragment_width_bugs.md — a
     * defensive SHA1 IV reinstall in the BE PREPEND sibling silently
     * corrupted SHA256 state h[5..7] in B6.2 fan-out; this fragment
     * inherits the lesson and never reinstalls.) */

    /* Process complete 64-byte blocks. Build M[] BIG-ENDIAN directly
     * from bytes; password bytes for p < len, salt bytes for p >= len. */
    while (total_len - pos >= HASH_BLOCK_BYTES) {
        for (int j = 0; j < 16; j++) M[j] = 0;
        for (int i = 0; i < HASH_BLOCK_BYTES; i++) {
            int p = pos + i;
            uchar c;
            if (p < len) {
                c = data[p];
            } else {
                c = salt_buf[p - len];
            }
            M[i >> 2] |= ((uint)c) << ((3 - (i & 3)) * 8);
        }
        sha1_block(&st.h[0], M);
        pos += HASH_BLOCK_BYTES;
    }

    /* Build final block(s): tail bytes + 0x80 marker + zeros + 64-bit
     * BE length. */
    int rem = total_len - pos;  /* 0..63 */
    for (int j = 0; j < 16; j++) M[j] = 0;
    for (int i = 0; i < rem; i++) {
        int p = pos + i;
        uchar c;
        if (p < len) {
            c = data[p];
        } else {
            c = salt_buf[p - len];
        }
        M[i >> 2] |= ((uint)c) << ((3 - (i & 3)) * 8);
    }
    /* 0x80 padding marker, BE byte position. */
    M[rem >> 2] |= ((uint)0x80u) << ((3 - (rem & 3)) * 8);

    if (rem < 56) {
        /* Length fits in this block. SHA-family BE: M[14] = high 32
         * bits of bit count, M[15] = low 32 bits. For total_len < 2^29
         * bytes (always true for our wordlist+salt inputs), high 32
         * bits = 0. */
        M[14] = 0;
        M[15] = (uint)((uint)total_len * 8u);
        sha1_block(&st.h[0], M);
    } else {
        /* Need one extra padding-only block to hold the length. */
        sha1_block(&st.h[0], M);
        for (int j = 0; j < 16; j++) M[j] = 0;
        M[14] = 0;
        M[15] = (uint)((uint)total_len * 8u);
        sha1_block(&st.h[0], M);
    }
}

/* template_iterate: -i loop step. Re-encode the digest as 40-byte
 * lowercase hex ASCII and rehash with fresh IV. lowercase hex of prior 40-char digest re-SHA1'd with FRESH IV (no salt re-application). Lines 14262-14265: prmd5(curin.h, newbuf, 40); mysha1(newbuf, 40, ...). Identical iter shape to SHA1SALTPASS — only the salt POSITION differs at template_finalize time (APPEND vs PREPEND).
 *
 * Mirrors gpu_sha1_core.cl rev 1 lines 257-288 byte-for-byte:
 *   - 5 state words -> 10 BE-encoded hex M[] words (2 words per state
 *     word, 4 hex chars each)
 *   - M[10] = 0x80000000u   (BE 0x80 padding at byte offset 40)
 *   - M[11..14] = 0
 *   - M[15] = 40 * 8 = 320 (bit count)
 *   - state reset to SHA1 IV; sha1_block. */
static inline void template_iterate(thread template_state &st)
{
    uint M[16];
    /* Inlined sha1_to_hex_lc_p body — keeps this core self-contained
     * (gpu_sha1_packed.cl's hex_byte_be_p / sha1_to_hex_lc_p are not
     * exported through gpu_common.cl). Per-byte BE hex encoding. */
    for (int i = 0; i < 5; i++) {
        uint s = st.h[i];
        uint b0 = (s >> 24) & 0xff;
        uint b1 = (s >> 16) & 0xff;
        uint b2 = (s >> 8)  & 0xff;
        uint b3 = s & 0xff;
        uint hi0 = (b0 >> 4) & 0xf, lo0 = b0 & 0xf;
        uint hi1 = (b1 >> 4) & 0xf, lo1 = b1 & 0xf;
        uint hi2 = (b2 >> 4) & 0xf, lo2 = b2 & 0xf;
        uint hi3 = (b3 >> 4) & 0xf, lo3 = b3 & 0xf;
        uint h0 = ((hi0 + ((hi0 < 10) ? '0' : ('a' - 10))) << 8)
                |  (lo0 + ((lo0 < 10) ? '0' : ('a' - 10)));
        uint h1 = ((hi1 + ((hi1 < 10) ? '0' : ('a' - 10))) << 8)
                |  (lo1 + ((lo1 < 10) ? '0' : ('a' - 10)));
        uint h2 = ((hi2 + ((hi2 < 10) ? '0' : ('a' - 10))) << 8)
                |  (lo2 + ((lo2 < 10) ? '0' : ('a' - 10)));
        uint h3 = ((hi3 + ((hi3 < 10) ? '0' : ('a' - 10))) << 8)
                |  (lo3 + ((lo3 < 10) ? '0' : ('a' - 10)));
        M[i * 2]     = (h0 << 16) | h1;
        M[i * 2 + 1] = (h2 << 16) | h3;
    }
    M[10] = 0x80000000u;
    for (int j = 11; j < 15; j++) M[j] = 0u;
    M[15] = 40u * 8u;        /* 40 hex chars = 320 bits */
    /* Reinitialize state to SHA1 IV, then absorb the prepared M[]. */
    st.h[0] = 0x67452301u;
    st.h[1] = 0xEFCDAB89u;
    st.h[2] = 0x98BADCFEu;
    st.h[3] = 0x10325476u;
    st.h[4] = 0xC3D2E1F0u;
    sha1_block(&st.h[0], M);
}

/* template_digest_compare: probe the compact table with the final digest.
 * SHA1 state is BE; bswap leading 4 words to LE (host's compact_table key
 * encoding). The 5th state word is NOT used by the compact-table probe —
 * only by EMIT_HIT_5 below. */
static inline int template_digest_compare(thread const template_state &st,
                                device const uint *compact_fp,
                                device const uint *compact_idx,
                                ulong compact_mask,
                                uint max_probe,
                                uint hash_data_count,
                                device const uchar *hash_data_buf,
                                device const ulong *hash_data_off,
                                device const ulong *overflow_keys,
                                device const uchar *overflow_hashes,
                                device const uint *overflow_offsets,
                                uint overflow_count,
                                thread uint *out_idx)
{
    uint h0 = bswap32(st.h[0]);
    uint h1 = bswap32(st.h[1]);
    uint h2 = bswap32(st.h[2]);
    uint h3 = bswap32(st.h[3]);
    return probe_compact_idx(
        h0, h1, h2, h3,
        compact_fp, compact_idx,
        compact_mask, max_probe, hash_data_count,
        hash_data_buf, hash_data_off,
        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,
        out_idx);
}


/* B3 dedup+overflow-aware variant. See gpu_sha1_core.cl for protocol
 * notes. */
#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \
                                      hashes_shown, matched_idx, dedup_mask, \
                                      ovr_set, ovr_gid, lane_gid) \
    do { \
        uint _h[5]; \
        _h[0] = bswap32((st).h[0]); \
        _h[1] = bswap32((st).h[1]); \
        _h[2] = bswap32((st).h[2]); \
        _h[3] = bswap32((st).h[3]); \
        _h[4] = bswap32((st).h[4]); \
        EMIT_HIT_5_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \
                   (widx), (sidx), (iter), _h, \
                   (hashes_shown), (matched_idx), (dedup_mask), \
                   (ovr_set), (ovr_gid), (lane_gid)); \
    } while (0)
