/*
 * $Revision: 1.1 $
 * $Log: metal_sha3_512_core.metal,v $
 * Revision 1.1  2026/05/16 18:50:16  dlr
 * Initial revision
 *
 *
 * Auto-generated by gpu/codegen/cl2metal.py from
 *   gpu_sha3_512_core.cl (RCS rev 1.2).
 *
 * Do NOT edit this file directly -- edit the OpenCL twin and
 * re-run cl2metal.py. The translator is intentionally lossless on
 * mechanical transforms; hand-curated Apple-specific tweaks live
 * in gpu/codegen/cl2metal_overrides/<algo>.yaml.
 *
 * Mirrors the byte-exact OpenCL hash chain; address-space port:
 *   __global  -> device
 *   __private -> thread
 *   barrier   -> threadgroup_barrier
 *   typedef struct ... T;  ->  struct T { ... };
 *   T *st     -> thread T &st
 *
 * Patterns 1/3 enforced: every pointer arg is address-space
 * qualified; every helper is static inline.
 */

/* gpu_sha3_512_core.cl - SHA3-512 algorithm extension functions for the
 * generic dispatch template (Memo B Phase B5 sub-batch 4, 2026-05-03).
 *
 * Sponge construction with rate=72 bytes (= 9 ulong), output=64 bytes,
 * domain suffix=0x06 (NIST FIPS 202 SHA3 family). HASH_WORDS=16,
 * HASH_BLOCK_BYTES=72.
 *
 * Note on iter: hex_lc encoding produces 2*64 = 128 chars > rate=72, so
 * iter requires absorbing one full rate block (chars 0..71) followed by
 * pad-absorb of remainder (chars 72..127, 56 bytes partial). Shared
 * while-loop in template_iterate handles this automatically.
 *
 * Bytecast invariant: sp[0..7] LE byte image == rhash_sha3 output (mdxfind.c
 * JOB_SHA3_512 line 28829). gpu_hash_words(JOB_SHA3_512) returns 16.
 */

#ifndef HASH_WORDS
#define HASH_WORDS 16
#endif
#ifndef HASH_BLOCK_BYTES
#define HASH_BLOCK_BYTES 72
#endif

#define KECCAK_RATE        72
#define KECCAK_RATE_WORDS   9
#define KECCAK_OUT_BYTES   64
#define KECCAK_DOMAIN_PAD  0x06

struct template_state {
    ulong sp[25];
    uint  h[HASH_WORDS];
};

static inline void template_state_to_h_sha3_512(thread template_state &st)
{
    for (int i = 0; i < HASH_WORDS / 2; i++) {
        ulong v = st.sp[i];
        st.h[i * 2]     = (uint)v;
        st.h[i * 2 + 1] = (uint)(v >> 32);
    }
}

static inline void sha3_512_absorb_pad(thread ulong *sp, thread const uchar *data, int rem)
{
    uchar block[KECCAK_RATE];
    for (int i = 0; i < rem; i++) block[i] = data[i];
    for (int i = rem; i < KECCAK_RATE; i++) block[i] = 0;
    block[rem]            ^= (uchar)KECCAK_DOMAIN_PAD;
    block[KECCAK_RATE - 1] ^= (uchar)0x80;
    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {
        ulong w = 0;
        int b = i * 8;
        w |= (ulong)block[b];
        w |= (ulong)block[b + 1] << 8;
        w |= (ulong)block[b + 2] << 16;
        w |= (ulong)block[b + 3] << 24;
        w |= (ulong)block[b + 4] << 32;
        w |= (ulong)block[b + 5] << 40;
        w |= (ulong)block[b + 6] << 48;
        w |= (ulong)block[b + 7] << 56;
        sp[i] ^= w;
    }
    keccakf1600(sp);
}

/* Phase 2d.7b: device-const overload (mirror of thread-const above). Selected by Metal's overload resolution when called from template_finalize's hot path with a device-const slice of buf_scratch_pool. */


static inline void sha3_512_absorb_pad(thread ulong *sp, device const uchar *data, int rem)
{
    uchar block[KECCAK_RATE];
    for (int i = 0; i < rem; i++) block[i] = data[i];
    for (int i = rem; i < KECCAK_RATE; i++) block[i] = 0;
    block[rem]            ^= (uchar)KECCAK_DOMAIN_PAD;
    block[KECCAK_RATE - 1] ^= (uchar)0x80;
    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {
        ulong w = 0;
        int b = i * 8;
        w |= (ulong)block[b];
        w |= (ulong)block[b + 1] << 8;
        w |= (ulong)block[b + 2] << 16;
        w |= (ulong)block[b + 3] << 24;
        w |= (ulong)block[b + 4] << 32;
        w |= (ulong)block[b + 5] << 40;
        w |= (ulong)block[b + 6] << 48;
        w |= (ulong)block[b + 7] << 56;
        sp[i] ^= w;
    }
    keccakf1600(sp);
}

static inline void sha3_512_absorb_full(thread ulong *sp, thread const uchar *data)
{
    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {
        ulong w = 0;
        int b = i * 8;
        w |= (ulong)data[b];
        w |= (ulong)data[b + 1] << 8;
        w |= (ulong)data[b + 2] << 16;
        w |= (ulong)data[b + 3] << 24;
        w |= (ulong)data[b + 4] << 32;
        w |= (ulong)data[b + 5] << 40;
        w |= (ulong)data[b + 6] << 48;
        w |= (ulong)data[b + 7] << 56;
        sp[i] ^= w;
    }
    keccakf1600(sp);
}

/* Phase 2d.7b: device-const overload (mirror of thread-const above). Selected by Metal's overload resolution when called from template_finalize's hot path with a device-const slice of buf_scratch_pool. */


static inline void sha3_512_absorb_full(thread ulong *sp, device const uchar *data)
{
    for (int i = 0; i < KECCAK_RATE_WORDS; i++) {
        ulong w = 0;
        int b = i * 8;
        w |= (ulong)data[b];
        w |= (ulong)data[b + 1] << 8;
        w |= (ulong)data[b + 2] << 16;
        w |= (ulong)data[b + 3] << 24;
        w |= (ulong)data[b + 4] << 32;
        w |= (ulong)data[b + 5] << 40;
        w |= (ulong)data[b + 6] << 48;
        w |= (ulong)data[b + 7] << 56;
        sp[i] ^= w;
    }
    keccakf1600(sp);
}

static inline void template_init(thread template_state &st)
{
    for (int i = 0; i < 25; i++) st.sp[i] = 0UL;
}

static inline void template_transform(thread template_state &st, thread const uchar *block)
{
    sha3_512_absorb_full(&st.sp[0], block);
}

static inline void template_finalize(thread template_state &st,
                                device const uchar *data,
                                int len)
{
    int pos = 0;
    while ((len - pos) >= KECCAK_RATE) {
        sha3_512_absorb_full(&st.sp[0], data + pos);
        pos += KECCAK_RATE;
    }
    int rem = len - pos;
    sha3_512_absorb_pad(&st.sp[0], data + pos, rem);
    template_state_to_h_sha3_512(st);
}

static inline void template_iterate(thread template_state &st)
{
    uint snap[HASH_WORDS];
    for (int i = 0; i < HASH_WORDS; i++) snap[i] = st.h[i];

    int hex_chars = 2 * KECCAK_OUT_BYTES;
    uchar hex[2 * KECCAK_OUT_BYTES];
    for (int i = 0; i < HASH_WORDS; i++) {
        uint s = snap[i];
        for (int b = 0; b < 4; b++) {
            uchar by = (uchar)((s >> (b * 8)) & 0xFFu);
            uchar hi = by >> 4, lo = by & 0xFu;
            hex[i * 8 + b * 2 + 0] = (hi < 10) ? (uchar)('0' + hi) : (uchar)('a' + (hi - 10));
            hex[i * 8 + b * 2 + 1] = (lo < 10) ? (uchar)('0' + lo) : (uchar)('a' + (lo - 10));
        }
    }

    for (int i = 0; i < 25; i++) st.sp[i] = 0UL;
    int pos = 0;
    while ((hex_chars - pos) >= KECCAK_RATE) {
        sha3_512_absorb_full(&st.sp[0], hex + pos);
        pos += KECCAK_RATE;
    }
    int rem = hex_chars - pos;
    sha3_512_absorb_pad(&st.sp[0], hex + pos, rem);
    template_state_to_h_sha3_512(st);
}

static inline int template_digest_compare(thread const template_state &st,
                                device const uint *compact_fp,
                                device const uint *compact_idx,
                                ulong compact_mask,
                                uint max_probe,
                                uint hash_data_count,
                                device const uchar *hash_data_buf,
                                device const ulong *hash_data_off,
                                device const ulong *overflow_keys,
                                device const uchar *overflow_hashes,
                                device const uint *overflow_offsets,
                                uint overflow_count,
                                thread uint *out_idx)
{
    return probe_compact_idx(
        st.h[0], st.h[1], st.h[2], st.h[3],
        compact_fp, compact_idx,
        compact_mask, max_probe, hash_data_count,
        hash_data_buf, hash_data_off,
        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,
        out_idx);
}

#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, widx, sidx, iter, \
                                      hashes_shown, matched_idx, dedup_mask, \
                                      ovr_set, ovr_gid, lane_gid) \
    EMIT_HIT_16_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \
               (widx), (sidx), (iter), ((st).h), \
               (hashes_shown), (matched_idx), (dedup_mask), \
               (ovr_set), (ovr_gid), (lane_gid))
