/* Auto-generated from metal_shacrypt_core.metal -- do not edit */
static const char metal_shacrypt_core_str[] =
    "/*\n"
    " * $Revisio" "n: $\n"
    " * $Lo" "g: $\n"
    " *\n"
    " * Hand-edited (Steps A+C port) from gpu/codegen/cl2metal.py base generated\n"
    " * from gpu_shacrypt_core.cl (RCS rev 1.3). Steps A+C ported 2026-05-19:\n"
    " *   Step A: metal_common.metal sha512_block flat-unrolled (MTL_SHA512_STEP_S).\n"
    " *   Step C: STEP 5 inner loop wpc boolean-cube (#if HASH_WORDS==16 gate).\n"
    " * Mirrors gpu_shacrypt_core.cl rev 1.4 optimizations for SHA512CRYPT.\n"
    " * SHA256CRYPT (HASH_WORDS=8) keeps original sc_update path unchanged.\n"
    " *\n"
    " * Address-space port from OpenCL:\n"
    " *   __global  -> device\n"
    " *   __private -> thread\n"
    " *   barrier   -> threadgroup_barrier\n"
    " *   typedef struct ... T;  ->  struct T { ... };\n"
    " *   T *st     -> thread T &st\n"
    " *\n"
    " * Patterns 1/3 enforced: every pointer arg is address-space\n"
    " * qualified; every helper is static inline.\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 8\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* SHA-256 IV constants. */\n"
    "#define SC_IV0_32 0x6a09e667u\n"
    "#define SC_IV1_32 0xbb67ae85u\n"
    "#define SC_IV2_32 0x3c6ef372u\n"
    "#define SC_IV3_32 0xa54ff53au\n"
    "#define SC_IV4_32 0x510e527fu\n"
    "#define SC_IV5_32 0x9b05688cu\n"
    "#define SC_IV6_32 0x1f83d9abu\n"
    "#define SC_IV7_32 0x5be0cd19u\n"
    "\n"
    "/* SHA-512 IV constants (used only at HASH_WORDS=16 in Phases 3 / 4). */\n"
    "#define SC_IV0_64 0x6a09e667f3bcc908UL\n"
    "#define SC_IV1_64 0xbb67ae8584caa73bUL\n"
    "#define SC_IV2_64 0x3c6ef372fe94f82bUL\n"
    "#define SC_IV3_64 0xa54ff53a5f1d36f1UL\n"
    "#define SC_IV4_64 0x510e527fade682d1UL\n"
    "#define SC_IV5_64 0x9b05688c2b3e6c1fUL\n"
    "#define SC_IV6_64 0x1f83d9abfb41bd6bUL\n"
    "#define SC_IV7_64 0x5be0cd19137e2179UL\n"
    "\n"
    "/* Per-lane state struct. The HASH_WORDS gate is RUNTIME-evaluated, but\n"
    " * the struct must hold whichever digest width is active at compile time.\n"
    " *\n"
    " * For SHA-256 path (HASH_WORDS=8): use uint state[8], uint buf[16],\n"
    " *   uint counter (each compiled instance picks the right width via the\n"
    " *   #ifdef inside the helpers below — but ONLY at the storage layer; the\n"
    " *   logic gates are runtime).\n"
    " *\n"
    " * For SHA-512 path (HASH_WORDS=16): use ulong state[8], ulong buf[16],\n"
    " *   ulong counter.\n"
    " *\n"
    " * Storage IS gated by `#ifdef` here (NOT `#if HASH_WORDS == N`) -- this is\n"
    " * a STORAGE choice (which TYPE compiles), not an EXECUTION branch (which\n"
    " * BODY runs). The lesson from feedback_runtime_gate_for_template_branches.md\n"
    " * is about EXECUTION branches in shared multi-width fragments. Storage-\n"
    " * only #ifdef on the TYPE is fine and standard practice (see e.g.\n"
    " * gpu_sha256crypt.cl + gpu_sha512crypt.cl which use this pattern). */\n"
    "#if HASH_WORDS == 16\n"
    "/* SHA-512 storage path */\n"
    "typedef ulong sc_word_t;\n"
    "typedef ulong sc_counter_t;\n"
    "#define SC_BLOCK_BYTES 128\n"
    "#define SC_DIGEST_BYTES 64\n"
    "#define SC_PAD_LEN_OFF  112      /* pos at which 16-byte length begins */\n"
    "#define SC_LEN_HI_IDX   14\n"
    "#define SC_LEN_LO_IDX   15\n"
    "#else\n"
    "/* SHA-256 storage path (default; HASH_WORDS=8) */\n"
    "typedef uint sc_word_t;\n"
    "typedef uint sc_counter_t;\n"
    "#define SC_BLOCK_BYTES 64\n"
    "#define SC_DIGEST_BYTES 32\n"
    "#define SC_PAD_LEN_OFF  56       /* pos at which 8-byte length begins */\n"
    "#define SC_LEN_HI_IDX   14\n"
    "#define SC_LEN_LO_IDX   15\n"
    "#endif\n"
    "\n"
    "struct template_state {\n"
    "    sc_word_t h[HASH_WORDS];\n"
    "};\n"
    "\n"
    "/* template_init: install IV. The IV constants are TYPE-dependent so we\n"
    " * use `#if` here (same discipline as the typedefs above). */\n"
    "static inline void template_init(thread template_state &st)\n"
    "{\n"
    "#if HASH_WORDS == 16\n"
    "    st.h[0] = SC_IV0_64; st.h[1] = SC_IV1_64;\n"
    "    st.h[2] = SC_IV2_64; st.h[3] = SC_IV3_64;\n"
    "    st.h[4] = SC_IV4_64; st.h[5] = SC_IV5_64;\n"
    "    st.h[6] = SC_IV6_64; st.h[7] = SC_IV7_64;\n"
    "    /* st.h[8..15] used as scratch for the final BE-extracted digest\n"
    "     * words / LE-packed output (see template_finalize tail). */\n"
    "    for (int i = 8; i < 16; i++) st.h[i] = 0;\n"
    "#else\n"
    "    st.h[0] = SC_IV0_32; st.h[1] = SC_IV1_32;\n"
    "    st.h[2] = SC_IV2_32; st.h[3] = SC_IV3_32;\n"
    "    st.h[4] = SC_IV4_32; st.h[5] = SC_IV5_32;\n"
    "    st.h[6] = SC_IV6_32; st.h[7] = SC_IV7_32;\n"
    "#endif\n"
    "}\n"
    "\n"
    "/* template_transform: stub. SHACRYPT manages multi-block absorption inline\n"
    " * via the buffered streaming helpers below; never routes through this. */\n"
    "static inline void template_transform(thread template_state &st, thread const uchar *block)\n"
    "{\n"
    "    (void)st; (void)block;\n"
    "}\n"
    "\n"
    "/* ---- Buffered streaming helpers ----------------------------------------\n"
    " *\n"
    " * sc_init / sc_update / sc_update_g / sc_final mirror the slab oracles'\n"
    " * accumulator pattern (gpu_sha256crypt.cl + gpu_sha512crypt.cl).\n"
    " *\n"
    " * Per the discipline note above:\n"
    " *   - Width-specific TYPES (sc_word_t / sc_counter_t) and constants\n"
    " *     (SC_BLOCK_BYTES, SC_PAD_LEN_OFF, IV literals) are gated by `#if\n"
    " *     HASH_WORDS == 16`.\n"
    " *   - The COMPRESSION call site is gated by `#if HASH_WORDS == 16`\n"
    " *     because sha256_block (uint*) vs sha512_block (ulong*) have\n"
    " *     incompatible signatures; a runtime gate would require ill-typed\n"
    " *     dead code.\n"
    " *   - Pure-uint control flow / final-pack loops use runtime\n"
    " *     `if (HASH_WORDS == N)` since both branches type-check.\n"
    " */\n"
    "\n"
    "static inline void sc_buf_set_byte(thread sc_word_t *buf, int pos, uchar val)\n"
    "{\n"
    "#if HASH_WORDS == 16\n"
    "    int wi = pos >> 3;\n"
    "    int bi = (7 - (pos & 7)) << 3;\n"
    "    buf[wi] = (buf[wi] & ~((sc_word_t)0xffUL << bi))\n"
    "              | ((sc_word_t)val << bi);\n"
    "#else\n"
    "    int wi = pos >> 2;\n"
    "    int bi = (3 - (pos & 3)) << 3;\n"
    "    buf[wi] = (buf[wi] & ~((sc_word_t)0xffu << bi))\n"
    "              | ((sc_word_t)val << bi);\n"
    "#endif\n"
    "}\n"
    "\n"
    "static inline void sc_init(thread sc_word_t *state)\n"
    "{\n"
    "#if HASH_WORDS == 16\n"
    "    state[0] = SC_IV0_64; state[1] = SC_IV1_64;\n"
    "    state[2] = SC_IV2_64; state[3] = SC_IV3_64;\n"
    "    state[4] = SC_IV4_64; state[5] = SC_IV5_64;\n"
    "    state[6] = SC_IV6_64; state[7] = SC_IV7_64;\n"
    "#else\n"
    "    state[0] = SC_IV0_32; state[1] = SC_IV1_32;\n"
    "    state[2] = SC_IV2_32; state[3] = SC_IV3_32;\n"
    "    state[4] = SC_IV4_32; state[5] = SC_IV5_32;\n"
    "    state[6] = SC_IV6_32; state[7] = SC_IV7_32;\n"
    "#endif\n"
    "}\n"
    "\n"
    "/* Accumulate `len` bytes from PRIVATE memory into the streaming buffer.\n"
    " * On block-boundary, compress + zero buf.\n"
    " *\n"
    " * The compression call site uses `#if HASH_WORDS == 16` because the two\n"
    " * primitives (sha256_block / sha512_block) take INCOMPATIBLE pointer\n"
    " * types (uint* / ulong*); a runtime gate would require ill-typed dead\n"
    " * code. Discipline: type-mismatched branches use `#if`; same-type\n"
    " * arithmetic / control flow uses runtime `if (HASH_WORDS == N)`. */\n"
    "static inline void sc_update(thread sc_word_t *state, thread sc_word_t *buf, thread int &bufpos, thread sc_counter_t &counter, thread const uchar *data, int len)\n"
    "{\n"
    "    counter += (sc_counter_t)len;\n"
    "    int bp = bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]);\n"
    "        bp++;\n"
    "        if (bp == SC_BLOCK_BYTES) {\n"
    "#if HASH_WORDS == 16\n"
    "            sha512_block(state, buf);\n"
    "#else\n"
    "            sha256_block(state, buf);\n"
    "#endif\n"
    "            for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "            bp = 0;\n"
    "        }\n"
    "    }\n"
    "    bufpos = bp;\n"
    "}\n"
    "\n"
    "/* Accumulate from GLOBAL memory. Identical to sc_update but data ptr is\n"
    " * __global. Used for salt_bytes (which lives in __global salt_buf). */\n"
    "static inline void sc_update_g(thread sc_word_t *state, thread sc_word_t *buf, thread int &bufpos, thread sc_counter_t &counter, device const uchar *data, int len)\n"
    "{\n"
    "    counter += (sc_counter_t)len;\n"
    "    int bp = bufpos;\n"
    "    for (int i = 0; i < len; i++) {\n"
    "        sc_buf_set_byte(buf, bp, data[i]);\n"
    "        bp++;\n"
    "        if (bp == SC_BLOCK_BYTES) {\n"
    "#if HASH_WORDS == 16\n"
    "            sha512_block(state, buf);\n"
    "#else\n"
    "            sha256_block(state, buf);\n"
    "#endif\n"
    "            for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "            bp = 0;\n"
    "        }\n"
    "    }\n"
    "    bufpos = bp;\n"
    "}\n"
    "\n"
    "/* Pad + length-encode + final compress; extract digest as raw bytes\n"
    " * (BE state words). out[] receives SC_DIGEST_BYTES bytes. */\n"
    "static inline void sc_final(thread sc_word_t *state,\n"
    "                                thread sc_word_t *buf,\n"
    "                                int bufpos,\n"
    "                                sc_counter_t counter,\n"
    "                                thread uchar *out)\n"
    "{\n"
    "    sc_buf_set_byte(buf, bufpos, 0x80);\n"
    "    bufpos++;\n"
    "\n"
    "    if (bufpos > SC_PAD_LEN_OFF) {\n"
    "        for (int i = bufpos; i < SC_BLOCK_BYTES; i++)\n"
    "            sc_buf_set_byte(buf, i, 0);\n"
    "#if HASH_WORDS == 16\n"
    "        sha512_block(state, buf);\n"
    "#else\n"
    "        sha256_block(state, buf);\n"
    "#endif\n"
    "        for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "        bufpos = 0;\n"
    "    }\n"
    "\n"
    "    /* Zero between bufpos and the length field. */\n"
    "    for (int i = bufpos; i < SC_PAD_LEN_OFF; i++)\n"
    "        sc_buf_set_byte(buf, i, 0);\n"
    "\n"
    "    /* Length in bits (BE). High word = 0 for our message sizes (well\n"
    "     * under 2^32 bytes for SHA-256, well under 2^64 bytes for SHA-512). */\n"
    "    buf[SC_LEN_HI_IDX] = 0;\n"
    "    buf[SC_LEN_LO_IDX] = (sc_word_t)counter * (sc_word_t)8;\n"
    "\n"
    "#if HASH_WORDS == 16\n"
    "    sha512_block(state, buf);\n"
    "    /* Extract 64 bytes BE from state[0..7] (ulong). */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        ulong w = state[i];\n"
    "        out[i*8 + 0] = (uchar)(w >> 56);\n"
    "        out[i*8 + 1] = (uchar)(w >> 48);\n"
    "        out[i*8 + 2] = (uchar)(w >> 40);\n"
    "        out[i*8 + 3] = (uchar)(w >> 32);\n"
    "        out[i*8 + 4] = (uchar)(w >> 24);\n"
    "        out[i*8 + 5] = (uchar)(w >> 16);\n"
    "        out[i*8 + 6] = (uchar)(w >> 8);\n"
    "        out[i*8 + 7] = (uchar)(w);\n"
    "    }\n"
    "#else\n"
    "    sha256_block(state, buf);\n"
    "    /* Extract 32 bytes BE from state[0..7] (uint). */\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint w = state[i];\n"
    "        out[i*4 + 0] = (uchar)(w >> 24);\n"
    "        out[i*4 + 1] = (uchar)(w >> 16);\n"
    "        out[i*4 + 2] = (uchar)(w >> 8);\n"
    "        out[i*4 + 3] = (uchar)(w);\n"
    "    }\n"
    "#endif\n"
    "}\n"
    "\n"
    "/* One-shot wrapper: compute HASH(data, len) -> out[SC_DIGEST_BYTES] */\n"
    "static inline void sc_oneshot(thread const uchar *data, int len, thread uchar *out)\n"
    "{\n"
    "    sc_word_t state[8];\n"
    "    sc_word_t buf[16];\n"
    "    int bp = 0;\n"
    "    sc_counter_t counter = 0;\n"
    "    sc_init(state);\n"
    "    for (int j = 0; j < 16; j++) buf[j] = 0;\n"
    "    sc_update(state, buf, bp, counter, data, len);\n"
    "    sc_final(state, buf, bp, counter, out);\n"
    "}\n"
    "\n"
    "/* template_finalize: full SHACRYPT chain (5 steps + rounds-iter loop).\n"
    " *\n"
    " * algo_mode dispatch (Phase 4 will use this):\n"
    " *   0 = SHA256CRYPT / SHA512CRYPT — straight chain on `data` as the password\n"
    " *   1 = SHA512CRYPTMD5 (Phase 4)  — first MD5(data) -> hex32, THEN feed\n"
    " *                                    that hex into the SHA-512 chain\n"
    " *   In Phase 2 ship, only mode 0 is used.\n"
    " *\n"
    " * SALT prefix parsing:\n"
    " *   salt_bytes points at \"$5$[rounds=N$]<salt>$\" or\n"
    " *                       \"$6$[rounds=N$]<salt>$\"\n"
    " *   - skip the 3-byte \"$5$\" / \"$6$\" prefix\n"
    " *   - if \"rounds=\" follows, parse decimal up to '$' (clamp 1000..999999999)\n"
    " *   - then read raw_salt up to '$' or end (cap 16 bytes)\n"
    " *\n"
    " * Final state in st->h[0..HASH_WORDS-1] (BE-extracted digest as\n"
    " * BIG-ENDIAN uint32 words for SHA-256; for SHA-512, the digest is 8\n"
    " * ulongs but template_digest_compare needs UINT32 LE for the compact\n"
    " * probe; we pack curin[0..3] LE-from-BE into the state words to mirror\n"
    " * the slab oracle behavior).\n"
    " */\n"
    "static inline void template_finalize(thread template_state &st,\n"
    "                                device const uchar *data,\n"
    "                                int len,\n"
    "                                device const uchar *salt_bytes,\n"
    "                                uint salt_len,\n"
    "                                uint algo_mode)\n"
    "{\n"
    "    /* Defensive: clamp plen to a reasonable upper bound. mdxfind default\n"
    "     * passwords <= 39 bytes; HASH_BLOCK_BYTES = 64 (SHA-256) or 128\n"
    "     * (SHA-512). Working buffer inside the bit loop / step 1 grows with\n"
    "     * plen; keep buf[256] for the worst-case temp construction. */\n"
    "    int plen = len;\n"
    "    if (plen > 64) plen = 64;  /* cap; won't happen in practice */\n"
    "\n"
    "    /* Copy password into private memory (data is post-rule buffer). */\n"
    "    uchar pw[64];\n"
    "    for (int i = 0; i < plen; i++) pw[i] = data[i];\n"
    "\n"
    "    /* SHA512CRYPTMD5 carrier (2026-05-08): algo_mode == 1u selects MD5-\n"
    "     * preprocess of the password (data[0..plen]) BEFORE the SHA-crypt\n"
    "     * chain runs. CPU semantics at mdxfind.c:12199-12212 substitutes\n"
    "     * the password with the 32-char ASCII-hex representation of MD5\n"
    "     * (original_password) -- the rest of crypt_round (which is the\n"
    "     * cryptlen=64 / SHA-512 branch) runs on this 32-byte string.\n"
    "     *\n"
    "     * Mirror that exactly here, INSIDE template_finalize so rules-engine\n"
    "     * post-rule plaintexts get the substitution AFTER rule application\n"
    "     * (matches CPU semantics: rules apply to the original word, MD5 of\n"
    "     * the post-rule word feeds the SHA-crypt chain).\n"
    "     *\n"
    "     * Using runtime `if` per feedback_runtime_gate_for_template_branches\n"
    "     * .md (NEVER `#if`; rev 1.7 Pascal NVIDIA ABORT lesson). The branch\n"
    "     * compiles unconditionally; on non-mode-1 paths NVCC's DCE strips\n"
    "     * it. SHA256CRYPT instantiation (HASH_WORDS=8, BASE_ALGO=sha256-\n"
    "     * crypt) hits a different cache key and never executes this branch\n"
    "     * (host sets algo_mode=0u for it).\n"
    "     *\n"
    "     * MD5-of-pw (≤ 64 bytes input): 1 block if plen ≤ 55; 2 blocks if\n"
    "     * 56 ≤ plen ≤ 64 (since MD5 padding requires 9 trailing bytes:\n"
    "     * 0x80 + 8-byte length). md5_block from gpu_common takes the\n"
    "     * h0..h3 state + M[16] message buffer. Output: 32-byte ASCII hex\n"
    "     * written back into pw[]; plen reset to 32. */\n"
    "    if (algo_mode == 1u) {\n"
    "        /* Build MD5 message buffer with standard padding. msg_len = plen.\n"
    "         * Use uchar mb[128] = 2 blocks, zero-init via local-scope var.\n"
    "         * Single block path (plen <= 55):\n"
    "         *   mb[plen] = 0x80; mb[56..63] = bit-length LE (uint64).\n"
    "         * Two block path (56 <= plen <= 64):\n"
    "         *   mb[plen] = 0x80 (could land in block 0 or block 1);\n"
    "         *   mb[120..127] = bit-length LE (uint64).\n"
    "         */\n"
    "        uchar mb[128];\n"
    "        for (int i = 0; i < 128; i++) mb[i] = 0;\n"
    "        for (int i = 0; i < plen; i++) mb[i] = pw[i];\n"
    "        mb[plen] = 0x80;\n"
    "        ulong bitlen = (ulong)plen * 8u;\n"
    "        int n_blocks = (plen <= 55) ? 1 : 2;\n"
    "        int len_off = (n_blocks == 1) ? 56 : 120;\n"
    "        mb[len_off + 0] = (uchar)(bitlen & 0xff);\n"
    "        mb[len_off + 1] = (uchar)((bitlen >>  8) & 0xff);\n"
    "        mb[len_off + 2] = (uchar)((bitlen >> 16) & 0xff);\n"
    "        mb[len_off + 3] = (uchar)((bitlen >> 24) & 0xff);\n"
    "        mb[len_off + 4] = (uchar)((bitlen >> 32) & 0xff);\n"
    "        mb[len_off + 5] = (uchar)((bitlen >> 40) & 0xff);\n"
    "        mb[len_off + 6] = (uchar)((bitlen >> 48) & 0xff);\n"
    "        mb[len_off + 7] = (uchar)((bitlen >> 56) & 0xff);\n"
    "\n"
    "        /* MD5 IV */\n"
    "        uint h0 = 0x67452301u;\n"
    "        uint h1 = 0xefcdab89u;\n"
    "        uint h2 = 0x98badcfeu;\n"
    "        uint h3 = 0x10325476u;\n"
    "\n"
    "        /* Pack first block as 16 LE uint32 from mb[0..63]. */\n"
    "        uint M[16];\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int k = j * 4;\n"
    "            M[j] = (uint)mb[k]\n"
    "                 | ((uint)mb[k+1] << 8)\n"
    "                 | ((uint)mb[k+2] << 16)\n"
    "                 | ((uint)mb[k+3] << 24);\n"
    "        }\n"
    "        md5_block(h0, h1, h2, h3, M);\n"
    "        if (n_blocks == 2) {\n"
    "            for (int j = 0; j < 16; j++) {\n"
    "                int k = 64 + j * 4;\n"
    "                M[j] = (uint)mb[k]\n"
    "                     | ((uint)mb[k+1] << 8)\n"
    "                     | ((uint)mb[k+2] << 16)\n"
    "                     | ((uint)mb[k+3] << 24);\n"
    "            }\n"
    "            md5_block(h0, h1, h2, h3, M);\n"
    "        }\n"
    "\n"
    "        /* Render MD5 digest as 32-char lowercase hex into pw[0..31]. The\n"
    "         * digest in (h0,h1,h2,h3) is stored LE byte-per-byte; CPU\n"
    "         * semantics (mymd5 + prmd5 in mdxfind.c) emits it as 32 lower-\n"
    "         * case ASCII hex chars in the natural byte order h0[0..3] then\n"
    "         * h1[0..3] then h2[0..3] then h3[0..3]. */\n"
    "        const char hex_digits[] = \"0123456789abcdef\";\n"
    "        uint hh[4]; hh[0] = h0; hh[1] = h1; hh[2] = h2; hh[3] = h3;\n"
    "        for (int j = 0; j < 4; j++) {\n"
    "            for (int k = 0; k < 4; k++) {\n"
    "                uchar by = (uchar)((hh[j] >> (k * 8)) & 0xff);\n"
    "                pw[j * 8 + k * 2 + 0] = (uchar)hex_digits[(by >> 4) & 0x0f];\n"
    "                pw[j * 8 + k * 2 + 1] = (uchar)hex_digits[by & 0x0f];\n"
    "            }\n"
    "        }\n"
    "        plen = 32;\n"
    "    }\n"
    "\n"
    "    /* ---- Salt prefix parsing ---- */\n"
    "    int slen_full = (int)salt_len;\n"
    "    int spos = 3;       /* skip \"$5$\" or \"$6$\" */\n"
    "    int rounds = 5000;\n"
    "\n"
    "    /* Detect \"rounds=\" (10 bytes of \"rounds=N$\") */\n"
    "    if (slen_full > 10\n"
    "        && salt_bytes[3] == 'r' && salt_bytes[4] == 'o'\n"
    "        && salt_bytes[5] == 'u' && salt_bytes[6] == 'n'\n"
    "        && salt_bytes[7] == 'd' && salt_bytes[8] == 's'\n"
    "        && salt_bytes[9] == '=')\n"
    "    {\n"
    "        rounds = 0;\n"
    "        spos = 10;\n"
    "        while (spos < slen_full\n"
    "               && salt_bytes[spos] >= '0' && salt_bytes[spos] <= '9')\n"
    "        {\n"
    "            rounds = rounds * 10 + (salt_bytes[spos] - '0');\n"
    "            spos++;\n"
    "        }\n"
    "        if (rounds < 1000) rounds = 1000;\n"
    "        if (rounds > 999999999) rounds = 999999999;\n"
    "        if (spos < slen_full && salt_bytes[spos] == '$') spos++;\n"
    "    }\n"
    "\n"
    "    /* Extract raw_salt up to 16 chars (terminated by '$' or end). */\n"
    "    uchar raw_salt[16];\n"
    "    int saltlen = 0;\n"
    "    for (int i = spos; i < slen_full && saltlen < 16; i++) {\n"
    "        uchar c = salt_bytes[i];\n"
    "        if (c == 0 || c == '$') break;\n"
    "        raw_salt[saltlen++] = c;\n"
    "    }\n"
    "    if (saltlen == 0) {\n"
    "        /* Defensive: zero state and return — saltlen 0 is invalid. */\n"
    "        for (int i = 0; i < HASH_WORDS; i++) st.h[i] = 0;\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    /* ---- Working buffers ---- */\n"
    "    sc_word_t state[8];\n"
    "    sc_word_t ctx_buf[16];\n"
    "    int ctx_bufpos;\n"
    "    sc_counter_t ctx_counter;\n"
    "    uchar tmp[256];                    /* scratch for building messages */\n"
    "    uchar digest_a[64];                /* alt_result (cryptlen <= 64) */\n"
    "    uchar digest_b[64];                /* temporary (P-prep / S-prep) */\n"
    "    uchar curin[64];                   /* main loop running digest */\n"
    "\n"
    "    int cryptlen = SC_DIGEST_BYTES;    /* compile-time const per width */\n"
    "\n"
    "    /* ---- STEP 1: digest_a = HASH(pass || raw_salt || pass) ---- */\n"
    "    {\n"
    "        int tlen = 0;\n"
    "        for (int i = 0; i < plen; i++)    tmp[tlen++] = pw[i];\n"
    "        for (int i = 0; i < saltlen; i++) tmp[tlen++] = raw_salt[i];\n"
    "        for (int i = 0; i < plen; i++)    tmp[tlen++] = pw[i];\n"
    "        sc_oneshot(tmp, tlen, digest_a);\n"
    "    }\n"
    "\n"
    "    /* ---- STEP 2: build curin ---- */\n"
    "    sc_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "\n"
    "    /* update(pass + salt) */\n"
    "    sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, pw, plen);\n"
    "    sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, raw_salt, saltlen);\n"
    "\n"
    "    /* For plen bytes, append digest_a in cryptlen-byte chunks. */\n"
    "    {\n"
    "        int x = plen;\n"
    "        while (x > cryptlen) {\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, digest_a, cryptlen);\n"
    "            x -= cryptlen;\n"
    "        }\n"
    "        sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, digest_a, x);\n"
    "    }\n"
    "\n"
    "    /* Bit loop: for each bit of plen (LSB to MSB) */\n"
    "    for (int x = plen; x != 0; x >>= 1) {\n"
    "        if (x & 1)\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, digest_a, cryptlen);\n"
    "        else\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, pw, plen);\n"
    "    }\n"
    "\n"
    "    sc_final(state, ctx_buf, ctx_bufpos, ctx_counter, curin);\n"
    "\n"
    "    /* ---- STEP 3 (P-prep): digest_p = HASH(pass repeated plen times) ---- */\n"
    "    sc_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "    for (int x = 0; x < plen; x++)\n"
    "        sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, pw, plen);\n"
    "    sc_final(state, ctx_buf, ctx_bufpos, ctx_counter, digest_b);\n"
    "\n"
    "    /* P-bytes: digest_b replicated to fill plen bytes. */\n"
    "    uchar p_bytes[64];\n"
    "    for (int i = 0; i < plen; i++)\n"
    "        p_bytes[i] = digest_b[i % cryptlen];\n"
    "\n"
    "    /* ---- STEP 4 (S-prep): digest_s = HASH(salt repeated 16+curin[0]\n"
    "     *                                      times) ---- */\n"
    "    sc_init(state);\n"
    "    for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "    ctx_bufpos = 0; ctx_counter = 0;\n"
    "    int s_repeats = 16 + (int)(uint)curin[0];\n"
    "    for (int x = 0; x < s_repeats; x++)\n"
    "        sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, raw_salt, saltlen);\n"
    "    sc_final(state, ctx_buf, ctx_bufpos, ctx_counter, digest_b);\n"
    "\n"
    "    /* S-bytes: first saltlen bytes of digest_b. */\n"
    "    uchar s_bytes[16];\n"
    "    for (int i = 0; i < saltlen; i++)\n"
    "        s_bytes[i] = digest_b[i];\n"
    "\n"
    "    /* ---- STEP 5: rounds main loop ----\n"
    "     *\n"
    "     * Optimized inner loop for SHA512CRYPT (HASH_WORDS == 16):\n"
    "     * Replaces per-iter sc_init/sc_update/sc_final (byte-RMW + state-\n"
    "     * machine overhead) with a direct block-construction approach.\n"
    "     * Mirrors hashcat m01800 wpc[8][16] pattern extended for plen > 15.\n"
    "     * Metal port of gpu_shacrypt_core.cl rev 1.4 Step C boolean-cube.\n"
    "     *\n"
    "     * Metal translation notes vs OpenCL:\n"
    "     *   - ulong blk[16] / bl2[16] / cu[8] / pu[8] / ns[8] are\n"
    "     *     function-local (thread private stack); no qualifier needed.\n"
    "     *   - sha512_block(ns, blk) passes thread ulong* implicitly (both\n"
    "     *     arrays are local); no addr-space cast required.\n"
    "     *   - Metal compiler inlines sha512_block (OPPOSITE of Pascal\n"
    "     *     noinline -- per feedback_md5_block_noinline_pascal.md).\n"
    "     *\n"
    "     * SHA256CRYPT (HASH_WORDS == 8) keeps the original sc_update path.\n"
    "     * The 2-block boundary logic differs (64B block vs 128B); no wpc. */\n"
    "#if HASH_WORDS == 16\n"
    "    {\n"
    "        /* Pre-pack p_bytes[plen] into pu[8] BE ulong (zeros beyond plen). */\n"
    "        ulong pu[8];\n"
    "        for (int i = 0; i < 8; i++) pu[i] = 0UL;\n"
    "        for (int i = 0; i < plen; i++) {\n"
    "            int wi = i >> 3, bi = (7 - (i & 7)) << 3;\n"
    "            pu[wi] |= (ulong)(uchar)p_bytes[i] << bi;\n"
    "        }\n"
    "\n"
    "        /* Pack initial curin[64] into cu[8] BE ulong. */\n"
    "        ulong cu[8];\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            int b = i * 8;\n"
    "            cu[i] = ((ulong)curin[b+0] << 56) | ((ulong)curin[b+1] << 48)\n"
    "                  | ((ulong)curin[b+2] << 40) | ((ulong)curin[b+3] << 32)\n"
    "                  | ((ulong)curin[b+4] << 24) | ((ulong)curin[b+5] << 16)\n"
    "                  | ((ulong)curin[b+6] <<  8) | ((ulong)curin[b+7]);\n"
    "        }\n"
    "\n"
    "        for (int r = 0; r < rounds; r++) {\n"
    "            int pc = (r & 1) + ((r % 3) ? 2 : 0) + ((r % 7) ? 4 : 0);\n"
    "\n"
    "            ulong blk[16];\n"
    "            ulong bl2[16];\n"
    "            for (int i = 0; i < 16; i++) { blk[i] = 0UL; bl2[i] = 0UL; }\n"
    "\n"
    "            int pos = 0;\n"
    "\n"
    "/* Helper: append N bytes from uchar src[] at byte offset pos in blk/bl2. */\n"
    "#define SC5_APPEND(src, len) \\\n"
    "            for (int _i = 0; _i < (len); _i++, pos++) { \\\n"
    "                int _wi = pos >> 3, _bi = (7 - (pos & 7)) << 3; \\\n"
    "                ulong _v = (ulong)(uchar)(src)[_i] << _bi; \\\n"
    "                if (_wi < 16) blk[_wi] |= _v; else bl2[_wi - 16] |= _v; \\\n"
    "            }\n"
    "\n"
    "/* Helper: append cu[8] ulong BE array (64 bytes) at current pos. */\n"
    "#define SC5_APPEND_CU() \\\n"
    "            if (pos == 0) { \\\n"
    "                for (int _i = 0; _i < 8; _i++) blk[_i] = cu[_i]; \\\n"
    "                pos = 64; \\\n"
    "            } else if ((pos & 7) == 0) { \\\n"
    "                int _bw = pos >> 3; \\\n"
    "                for (int _i = 0; _i < 8; _i++) { \\\n"
    "                    int _idx = _bw + _i; \\\n"
    "                    if (_idx < 16) blk[_idx] |= cu[_i]; \\\n"
    "                    else bl2[_idx - 16] |= cu[_i]; \\\n"
    "                } \\\n"
    "                pos += 64; \\\n"
    "            } else { \\\n"
    "                for (int _i = 0; _i < 64; _i++, pos++) { \\\n"
    "                    int _wi = pos >> 3, _bi = (7 - (pos & 7)) << 3; \\\n"
    "                    int _ci = _i >> 3, _cbi = (7 - (_i & 7)) * 8; \\\n"
    "                    ulong _v = ((cu[_ci] >> _cbi) & 0xffUL) << _bi; \\\n"
    "                    if (_wi < 16) blk[_wi] |= _v; else bl2[_wi-16] |= _v; \\\n"
    "                } \\\n"
    "            }\n"
    "\n"
    "/* Helper: append pu[8] ulong BE array (plen bytes). */\n"
    "#define SC5_APPEND_PU() \\\n"
    "            if ((pos & 7) == 0 && (plen & 7) == 0) { \\\n"
    "                int _bw = pos >> 3, _nw = plen >> 3; \\\n"
    "                for (int _i = 0; _i < _nw; _i++) { \\\n"
    "                    int _idx = _bw + _i; \\\n"
    "                    if (_idx < 16) blk[_idx] |= pu[_i]; \\\n"
    "                    else bl2[_idx - 16] |= pu[_i]; \\\n"
    "                } \\\n"
    "                pos += plen; \\\n"
    "            } else { SC5_APPEND(p_bytes, plen) }\n"
    "\n"
    "            /* Build message segments according to pc index. */\n"
    "            if (pc & 1) { SC5_APPEND_PU() } else { SC5_APPEND_CU() }\n"
    "            if (pc & 2) { SC5_APPEND(s_bytes, saltlen) }\n"
    "            if (pc & 4) { SC5_APPEND_PU() }\n"
    "            if (pc & 1) { SC5_APPEND_CU() } else { SC5_APPEND_PU() }\n"
    "\n"
    "#undef SC5_APPEND\n"
    "#undef SC5_APPEND_CU\n"
    "#undef SC5_APPEND_PU\n"
    "\n"
    "            /* Insert SHA-512 Merkle-Damgard padding (128B block):\n"
    "             * 0x80 at pos, zeros until length field, 128-bit BE length\n"
    "             * at blk[14..15] (single block, pos <= 111) or\n"
    "             * bl2[14..15] (two blocks, pos >= 112). */\n"
    "            int totbytes = pos;\n"
    "            {\n"
    "                int _wi = pos >> 3, _bi = (7 - (pos & 7)) << 3;\n"
    "                ulong _v = 0x80UL << _bi;\n"
    "                if (_wi < 16) blk[_wi] |= _v; else bl2[_wi - 16] |= _v;\n"
    "            }\n"
    "            ulong bitlen = (ulong)totbytes * 8UL;\n"
    "\n"
    "            ulong ns[8];\n"
    "            ns[0] = SC_IV0_64; ns[1] = SC_IV1_64;\n"
    "            ns[2] = SC_IV2_64; ns[3] = SC_IV3_64;\n"
    "            ns[4] = SC_IV4_64; ns[5] = SC_IV5_64;\n"
    "            ns[6] = SC_IV6_64; ns[7] = SC_IV7_64;\n"
    "\n"
    "            if (totbytes < 112) {\n"
    "                blk[15] = bitlen;\n"
    "                sha512_block(ns, blk);\n"
    "            } else {\n"
    "                bl2[15] = bitlen;\n"
    "                sha512_block(ns, blk);\n"
    "                sha512_block(ns, bl2);\n"
    "            }\n"
    "\n"
    "            /* Update cu[] = new curin (already in ulong BE form). */\n"
    "            for (int i = 0; i < 8; i++) cu[i] = ns[i];\n"
    "        }\n"
    "\n"
    "        /* Extract final curin from cu[8] back into curin[64] for pack step. */\n"
    "        for (int i = 0; i < 8; i++) {\n"
    "            ulong w = cu[i];\n"
    "            int b = i * 8;\n"
    "            curin[b+0] = (uchar)(w >> 56); curin[b+1] = (uchar)(w >> 48);\n"
    "            curin[b+2] = (uchar)(w >> 40); curin[b+3] = (uchar)(w >> 32);\n"
    "            curin[b+4] = (uchar)(w >> 24); curin[b+5] = (uchar)(w >> 16);\n"
    "            curin[b+6] = (uchar)(w >>  8); curin[b+7] = (uchar)(w);\n"
    "        }\n"
    "    }\n"
    "#else\n"
    "    /* SHA256CRYPT (HASH_WORDS == 8): keep original sc_update path. */\n"
    "    for (int r = 0; r < rounds; r++) {\n"
    "        sc_init(state);\n"
    "        for (int j = 0; j < 16; j++) ctx_buf[j] = 0;\n"
    "        ctx_bufpos = 0; ctx_counter = 0;\n"
    "\n"
    "        if (r & 1)\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, p_bytes, plen);\n"
    "        else\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, curin, cryptlen);\n"
    "\n"
    "        if (r % 3)\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, s_bytes, saltlen);\n"
    "\n"
    "        if (r % 7)\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, p_bytes, plen);\n"
    "\n"
    "        if (r & 1)\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, curin, cryptlen);\n"
    "        else\n"
    "            sc_update(state, ctx_buf, ctx_bufpos, ctx_counter, p_bytes, plen);\n"
    "\n"
    "        sc_final(state, ctx_buf, ctx_bufpos, ctx_counter, curin);\n"
    "    }\n"
    "#endif\n"
    "\n"
    "    /* ---- Pack final digest into st.h for compare/emit ----\n"
    "     *\n"
    "     * The compact-table probe + EMIT_HIT_8 (SHA-256) / EMIT_HIT_16\n"
    "     * (SHA-512) read st.h[i] as LE uint32 words. The slab oracle packs\n"
    "     * the first 4 uint32 words via LE-byte-read of curin[0..15]. We\n"
    "     * mirror exactly: pack curin[i*4 .. i*4+3] LE -> st.h[i].\n"
    "     *\n"
    "     * Loop bound + st.h[] write is width-dependent (8 vs 16 iterations).\n"
    "     * st.h has HASH_WORDS slots. A runtime gate would have a dead-branch\n"
    "     * OOB write at HASH_WORDS=8 (st.h[15] doesn't exist). Use #if for\n"
    "     * the same reason as the compression call site (TYPE/STORAGE\n"
    "     * discipline). */\n"
    "#if HASH_WORDS == 16\n"
    "    for (int i = 0; i < 16; i++) {\n"
    "        uint w = ((uint)curin[i*4 + 0])\n"
    "               | ((uint)curin[i*4 + 1] << 8)\n"
    "               | ((uint)curin[i*4 + 2] << 16)\n"
    "               | ((uint)curin[i*4 + 3] << 24);\n"
    "        /* Phase 3's EMIT_HIT_16 will re-extract 16 LE uint32 words via\n"
    "         * (uint)st.h[i] (lower 32 bits of each ulong). */\n"
    "        st.h[i] = (sc_word_t)w;\n"
    "    }\n"
    "#else\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        uint w = ((uint)curin[i*4 + 0])\n"
    "               | ((uint)curin[i*4 + 1] << 8)\n"
    "               | ((uint)curin[i*4 + 2] << 16)\n"
    "               | ((uint)curin[i*4 + 3] << 24);\n"
    "        st.h[i] = (sc_word_t)w;\n"
    "    }\n"
    "#endif\n"
    "    return;\n"
    "}\n"
    "\n"
    "/* template_iterate: STUB. max_iter=1 forced host-side for SHACRYPT, so\n"
    " * the kernel's outer iter loop runs exactly once and never calls this.\n"
    " * Mirror PHPBB3 / SHA1DRU / MD5CRYPT pattern. */\n"
    "static inline void template_iterate(thread template_state &st)\n"
    "{\n"
    "    (void)st;\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with the first 4 LE\n"
    " * uint32 words of the digest. Identical to the slab oracle's probe. */\n"
    "static inline int template_digest_compare(thread const template_state &st,\n"
    "                                device const uint *compact_fp,\n"
    "                                device const uint *compact_idx,\n"
    "                                ulong compact_mask,\n"
    "                                uint max_probe,\n"
    "                                uint hash_data_count,\n"
    "                                device const uchar *hash_data_buf,\n"
    "                                device const ulong *hash_data_off,\n"
    "                                device const ulong *overflow_keys,\n"
    "                                device const uchar *overflow_hashes,\n"
    "                                device const uint *overflow_offsets,\n"
    "                                uint overflow_count,\n"
    "                                thread uint *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        (uint)st.h[0], (uint)st.h[1], (uint)st.h[2], (uint)st.h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit: emit the digest words as a hit.\n"
    " *\n"
    " * EMIT_HIT_N macros in gpu_common.cl take `h` as an array argument (not\n"
    " * individual word args; cf. gpu_sha256saltpass_core.cl rev 1.x style).\n"
    " * We construct a local uint[HASH_WORDS] array from st->h[i] (already\n"
    " * LE-packed from curin in template_finalize) and pass it. NO bswap32:\n"
    " * st->h[i] is already LE uint32; the slab oracle does the same.\n"
    " *\n"
    " * Width-conditional via #if (CONSTANT macros, not execution branches —\n"
    " * the runtime-gate rule applies to BODIES, not preprocessor selection of\n"
    " * which #define line is active per compile target). */\n"
    "#if HASH_WORDS == 16\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[16]; \\\n"
    "        for (int _w = 0; _w < 16; _w++) _h[_w] = (uint)(st).h[_w]; \\\n"
    "        EMIT_HIT_16((hits), (hit_count), (max_hits), \\\n"
    "                    (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, \\\n"
    "                                      widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[16]; \\\n"
    "        for (int _w = 0; _w < 16; _w++) _h[_w] = (uint)(st).h[_w]; \\\n"
    "        EMIT_HIT_16_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                    (widx), (sidx), (iter), _h, \\\n"
    "                    (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                    (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
    "#else\n"
    "#define template_emit_hit(hits, hit_count, max_hits, st, widx, sidx, iter) \\\n"
    "    do { \\\n"
    "        uint _h[8]; \\\n"
    "        for (int _w = 0; _w < 8; _w++) _h[_w] = (uint)(st).h[_w]; \\\n"
    "        EMIT_HIT_8((hits), (hit_count), (max_hits), \\\n"
    "                   (widx), (sidx), (iter), _h) \\\n"
    "    } while (0)\n"
    "\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits, st, \\\n"
    "                                      widx, sidx, iter, \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask, \\\n"
    "                                      ovr_set, ovr_gid, lane_gid) \\\n"
    "    do { \\\n"
    "        uint _h[8]; \\\n"
    "        for (int _w = 0; _w < 8; _w++) _h[_w] = (uint)(st).h[_w]; \\\n"
    "        EMIT_HIT_8_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits), \\\n"
    "                    (widx), (sidx), (iter), _h, \\\n"
    "                    (hashes_shown), (matched_idx), (dedup_mask), \\\n"
    "                    (ovr_set), (ovr_gid), (lane_gid)); \\\n"
    "    } while (0)\n"
    "#endif\n"
;
