/* Auto-generated from metal_kernel_a_masks.metal -- do not edit */
static const char metal_kernel_a_masks_str[] =
    "/*\n"
    " * $Revision: $\n"
    " * $Log: $\n"
    " *\n"
    " * Hand-ported from gpu_kernel_a_masks.cl (post 2026-05-30 long-mask\n"
    " * amendment). Walker rewrite is non-trivial (per-thread var table +\n"
    " * 2-pass design) so we maintain this as a hand-written port rather\n"
    " * than depending on cl2metal.py for translation. Source stays in\n"
    " * lockstep with the OpenCL twin via review discipline; structural\n"
    " * changes to one MUST land in the other in the same commit per\n"
    " * feedback_opencl_metal_parity.\n"
    " */\n"
    "\n"
    "/* gpu_kernel_a_masks.cl -- Kernel A2 (masks-only) candidate producer\n"
    " * (Metal twin). See gpu_kernel_a_masks.cl for the full design memo.\n"
    " *\n"
    " * Post-amendment Metal-side notes:\n"
    " *   - __global -> device\n"
    " *   - __private (implicit on per-thread arrays) -> thread\n"
    " *   - atomic_uint with atomic_fetch_add_explicit / atomic_fetch_or_explicit\n"
    " *   - kernel entry uses [[thread_position_in_grid]]\n"
    " *\n"
    " * 8-arg signature is BYTE-IDENTICAL to OpenCL twin (post-amendment).\n"
    " */\n"
    "\n"
    "/* Wire-format tags (must match mdxfind.c host packer). */\n"
    "#define GPU_MASK_DESC_TAG_LIT   0x00u\n"
    "#define GPU_MASK_DESC_TAG_VAR   0x01u\n"
    "#define GPU_MASK_DESC_TAG_END   0xFFu\n"
    "\n"
    "/* Per-side caps (must match mdxfind.c host defines). */\n"
    "#define GPU_MASK_VAR_CAP        16\n"
    "#define GPU_MASK_LIT_BYTES_CAP  224\n"
    "#define GPU_MASK_DESC_BYTES_CAP 320\n"
    "\n"
    "/* Per-thread expanded-mask scratch capacity. */\n"
    "#define GPU_MASK_SIDE_EXPANDED_CAP (GPU_MASK_LIT_BYTES_CAP + GPU_MASK_VAR_CAP)\n"
    "\n"
    "/* Final candidate length cap (uchar len byte). */\n"
    "#define MASK_FINAL_LEN_LIMIT   255u\n"
    "\n"
    "/* Kernel-A state buffer offsets. */\n"
    "#define KERNELA_STATE_SLOT_COUNTER   0u\n"
    "#define KERNELA_STATE_BYTE_COUNTER   4u\n"
    "#define KERNELA_STATE_OVERFLOW_FLAG  8u\n"
    "#define KERNELA_STATE_BYTES         12u\n"
    "\n"
    "/* Charset table flat-array stride. */\n"
    "#define MASK_CHARSET_STRIDE          256u\n"
    "\n"
    "/* ==== Mask expander helper (2-pass; HIGH-TO-LOW variable expand) ==== */\n"
    "static int mask_expand_run_into_gpu(ulong idx,\n"
    "                                    device const uchar *desc,\n"
    "                                    uint desc_bytes,\n"
    "                                    device const uchar *mask_charsets,\n"
    "                                    device const uint  *mask_class_counts,\n"
    "                                    thread uchar *outbuf)\n"
    "{\n"
    "    uchar var_classids[GPU_MASK_VAR_CAP];\n"
    "    uint  var_outpos[GPU_MASK_VAR_CAP];\n"
    "    int   n_vars  = 0;\n"
    "    int   out_len = 0;\n"
    "    uint  p       = 0;\n"
    "\n"
    "    while (p < desc_bytes) {\n"
    "        uchar tag = desc[p++];\n"
    "        if (tag == GPU_MASK_DESC_TAG_END) break;\n"
    "        if (tag == GPU_MASK_DESC_TAG_LIT) {\n"
    "            if (p + 2u > desc_bytes) break;\n"
    "            uint lit_len = (uint)desc[p] | ((uint)desc[p + 1u] << 8);\n"
    "            p += 2u;\n"
    "            if (p + lit_len > desc_bytes) break;\n"
    "            for (uint i = 0; i < lit_len; i++) {\n"
    "                outbuf[out_len + (int)i] = desc[p + i];\n"
    "            }\n"
    "            out_len += (int)lit_len;\n"
    "            p += lit_len;\n"
    "        } else if (tag == GPU_MASK_DESC_TAG_VAR) {\n"
    "            if (p + 1u > desc_bytes) break;\n"
    "            uchar cid = desc[p++];\n"
    "            if (n_vars >= GPU_MASK_VAR_CAP) break;\n"
    "            var_classids[n_vars] = cid;\n"
    "            var_outpos[n_vars]   = (uint)out_len;\n"
    "            outbuf[out_len] = 0;\n"
    "            out_len += 1;\n"
    "            n_vars  += 1;\n"
    "        } else {\n"
    "            break;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    for (int i = n_vars - 1; i >= 0; i--) {\n"
    "        uint cid = (uint)var_classids[i];\n"
    "        uint cc  = mask_class_counts[cid];\n"
    "        if (cc == 0u) cc = 1u;\n"
    "        outbuf[var_outpos[i]] = mask_charsets[cid * MASK_CHARSET_STRIDE\n"
    "                                              + (uint)(idx % (ulong)cc)];\n"
    "        idx /= (ulong)cc;\n"
    "    }\n"
    "\n"
    "    return out_len;\n"
    "}\n"
    "\n"
    "/* ==== Per-side cardinality helper ==================================== */\n"
    "static ulong mask_pattern_total_run(device const uchar *desc,\n"
    "                                    uint desc_bytes,\n"
    "                                    device const uint  *mask_class_counts)\n"
    "{\n"
    "    ulong total = 1ul;\n"
    "    uint  p     = 0;\n"
    "    while (p < desc_bytes) {\n"
    "        uchar tag = desc[p++];\n"
    "        if (tag == GPU_MASK_DESC_TAG_END) break;\n"
    "        if (tag == GPU_MASK_DESC_TAG_LIT) {\n"
    "            if (p + 2u > desc_bytes) break;\n"
    "            uint lit_len = (uint)desc[p] | ((uint)desc[p + 1u] << 8);\n"
    "            p += 2u + lit_len;\n"
    "        } else if (tag == GPU_MASK_DESC_TAG_VAR) {\n"
    "            if (p + 1u > desc_bytes) break;\n"
    "            uchar cid = desc[p++];\n"
    "            uint cc = mask_class_counts[(uint)cid];\n"
    "            if (cc > 0u) total *= (ulong)cc;\n"
    "        } else {\n"
    "            break;\n"
    "        }\n"
    "    }\n"
    "    return total;\n"
    "}\n"
    "\n"
    "/* ---- Kernel A2 (masks-only) production kernel (Metal) ------------- */\n"
    "kernel\n"
    "void cand_masks_phase0(device uchar         *payload                    [[buffer(0)]],\n"
    "                       device const uchar   *mask_pattern_prepend       [[buffer(1)]],\n"
    "                       device const uchar   *mask_pattern_append        [[buffer(2)]],\n"
    "                       device const uchar   *mask_charsets              [[buffer(3)]],\n"
    "                       device const uint    *mask_class_counts          [[buffer(4)]],\n"
    "                       device uchar         *b_packed_buf               [[buffer(5)]],\n"
    "                       device uint          *b_chunk_index              [[buffer(6)]],\n"
    "                       device atomic_uint   *b_kernelA_state            [[buffer(7)]],\n"
    "                       uint                  gid                        [[thread_position_in_grid]])\n"
    "{\n"
    "    device const OCLParams *params_buf = (device const OCLParams *)payload;\n"
    "    OCLParams params = *params_buf;\n"
    "    uint n_words     = params.num_words;\n"
    "    uint n_masks     = params.num_masks;\n"
    "    uint prep_dbytes = params.n_prepend;\n"
    "    uint app_dbytes  = params.n_append;\n"
    "    uint total       = n_words * n_masks;\n"
    "\n"
    "    if (gid >= total) return;\n"
    "\n"
    "    uint word_idx = gid % n_words;\n"
    "    uint mask_idx = gid / n_words;\n"
    "\n"
    "    ulong append_total = mask_pattern_total_run(mask_pattern_append,\n"
    "                                                app_dbytes,\n"
    "                                                mask_class_counts);\n"
    "\n"
    "    ulong append_idx;\n"
    "    ulong prepend_idx;\n"
    "    if (append_total > 0ul) {\n"
    "        append_idx  = (ulong)mask_idx % append_total;\n"
    "        prepend_idx = (ulong)mask_idx / append_total;\n"
    "    } else {\n"
    "        append_idx  = 0ul;\n"
    "        prepend_idx = (ulong)mask_idx;\n"
    "    }\n"
    "\n"
    "    uchar prebuf[GPU_MASK_SIDE_EXPANDED_CAP];\n"
    "    uchar appbuf[GPU_MASK_SIDE_EXPANDED_CAP];\n"
    "\n"
    "    int prelen = mask_expand_run_into_gpu(prepend_idx,\n"
    "                                          mask_pattern_prepend, prep_dbytes,\n"
    "                                          mask_charsets, mask_class_counts,\n"
    "                                          prebuf);\n"
    "    int applen = mask_expand_run_into_gpu(append_idx,\n"
    "                                          mask_pattern_append,  app_dbytes,\n"
    "                                          mask_charsets, mask_class_counts,\n"
    "                                          appbuf);\n"
    "\n"
    "    device const uint   *word_offset = (device const uint *)(payload + 132);\n"
    "    uint pkt_off = 132u + (n_words * 4u);\n"
    "    device const uchar  *words = payload + pkt_off;\n"
    "\n"
    "    uint wpos = word_offset[word_idx];\n"
    "    uint wlen = (uint)words[wpos++];\n"
    "\n"
    "    uint final_len = (uint)prelen + wlen + (uint)applen;\n"
    "    if (final_len > MASK_FINAL_LEN_LIMIT) return;\n"
    "\n"
    "    uint need_bytes = 1u + final_len;\n"
    "    uint byte_off = atomic_fetch_add_explicit(\n"
    "        &b_kernelA_state[KERNELA_STATE_BYTE_COUNTER / 4u],\n"
    "        need_bytes, memory_order_relaxed);\n"
    "\n"
    "    if (byte_off + need_bytes > params.packed_size) {\n"
    "        atomic_fetch_or_explicit(\n"
    "            &b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u],\n"
    "            1u, memory_order_relaxed);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    uint slot = atomic_fetch_add_explicit(\n"
    "        &b_kernelA_state[KERNELA_STATE_SLOT_COUNTER / 4u],\n"
    "        1u, memory_order_relaxed);\n"
    "\n"
    "    if (slot >= total) {\n"
    "        atomic_fetch_or_explicit(\n"
    "            &b_kernelA_state[KERNELA_STATE_OVERFLOW_FLAG / 4u],\n"
    "            1u, memory_order_relaxed);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    b_packed_buf[byte_off] = (uchar)final_len;\n"
    "    uint p = byte_off + 1u;\n"
    "    for (int i = 0; i < prelen; i++) b_packed_buf[p++] = prebuf[i];\n"
    "    for (uint i = 0; i < wlen;   i++) b_packed_buf[p++] = words[wpos + i];\n"
    "    for (int i = 0; i < applen; i++) b_packed_buf[p++] = appbuf[i];\n"
    "\n"
    "    b_chunk_index[slot] = byte_off;\n"
    "}\n"
;
