/* Auto-generated from metal_md4_packed.metal -- do not edit */
static const char metal_md4_packed_str[] =
    "/* metal_md4_packed.metal — Packed password MD4 kernel\n"
    " *\n"
    " * Metal port of gpu_md4_packed.cl.\n"
    " *\n"
    " * Same structure as metal_md5_packed but uses MD4 compress (fully unrolled,\n"
    " * 3 rounds x 16 steps). md5_to_hex_lc works for MD4 iteration (same LE\n"
    " * 128-bit format).\n"
    " *\n"
    " * Primitives (md5_to_hex_lc, MetalParams, HIT_STRIDE) provided by\n"
    " * metal_common.metal (concatenated at build time).\n"
    " */\n"
    "\n"
    "/* MD4 compress — fully unrolled */\n"
    "static void md4_compress_p(thread uint4 &state, thread uint *M) {\n"
    "    uint a = state.x, b = state.y, c = state.z, d = state.w;\n"
    "#define MD4P_F(x,y,z) (((x)&(y)) | ((~(x))&(z)))\n"
    "#define MD4P_G(x,y,z) (((x)&(y)) | ((x)&(z)) | ((y)&(z)))\n"
    "#define MD4P_H(x,y,z) ((x)^(y)^(z))\n"
    "#define MD4P_ROTL(v,s) (((v)<<(s))|((v)>>(32-(s))))\n"
    "#define MD4P_R1(a,b,c,d,k,s) a = MD4P_ROTL(a + MD4P_F(b,c,d) + M[k], (s))\n"
    "#define MD4P_R2(a,b,c,d,k,s) a = MD4P_ROTL(a + MD4P_G(b,c,d) + M[k] + 0x5A827999u, (s))\n"
    "#define MD4P_R3(a,b,c,d,k,s) a = MD4P_ROTL(a + MD4P_H(b,c,d) + M[k] + 0x6ED9EBA1u, (s))\n"
    "    MD4P_R1(a,b,c,d, 0, 3); MD4P_R1(d,a,b,c, 1, 7); MD4P_R1(c,d,a,b, 2,11); MD4P_R1(b,c,d,a, 3,19);\n"
    "    MD4P_R1(a,b,c,d, 4, 3); MD4P_R1(d,a,b,c, 5, 7); MD4P_R1(c,d,a,b, 6,11); MD4P_R1(b,c,d,a, 7,19);\n"
    "    MD4P_R1(a,b,c,d, 8, 3); MD4P_R1(d,a,b,c, 9, 7); MD4P_R1(c,d,a,b,10,11); MD4P_R1(b,c,d,a,11,19);\n"
    "    MD4P_R1(a,b,c,d,12, 3); MD4P_R1(d,a,b,c,13, 7); MD4P_R1(c,d,a,b,14,11); MD4P_R1(b,c,d,a,15,19);\n"
    "    MD4P_R2(a,b,c,d, 0, 3); MD4P_R2(d,a,b,c, 4, 5); MD4P_R2(c,d,a,b, 8, 9); MD4P_R2(b,c,d,a,12,13);\n"
    "    MD4P_R2(a,b,c,d, 1, 3); MD4P_R2(d,a,b,c, 5, 5); MD4P_R2(c,d,a,b, 9, 9); MD4P_R2(b,c,d,a,13,13);\n"
    "    MD4P_R2(a,b,c,d, 2, 3); MD4P_R2(d,a,b,c, 6, 5); MD4P_R2(c,d,a,b,10, 9); MD4P_R2(b,c,d,a,14,13);\n"
    "    MD4P_R2(a,b,c,d, 3, 3); MD4P_R2(d,a,b,c, 7, 5); MD4P_R2(c,d,a,b,11, 9); MD4P_R2(b,c,d,a,15,13);\n"
    "    MD4P_R3(a,b,c,d, 0, 3); MD4P_R3(d,a,b,c, 8, 9); MD4P_R3(c,d,a,b, 4,11); MD4P_R3(b,c,d,a,12,15);\n"
    "    MD4P_R3(a,b,c,d, 2, 3); MD4P_R3(d,a,b,c,10, 9); MD4P_R3(c,d,a,b, 6,11); MD4P_R3(b,c,d,a,14,15);\n"
    "    MD4P_R3(a,b,c,d, 1, 3); MD4P_R3(d,a,b,c, 9, 9); MD4P_R3(c,d,a,b, 5,11); MD4P_R3(b,c,d,a,13,15);\n"
    "    MD4P_R3(a,b,c,d, 3, 3); MD4P_R3(d,a,b,c,11, 9); MD4P_R3(c,d,a,b, 7,11); MD4P_R3(b,c,d,a,15,15);\n"
    "#undef MD4P_F\n"
    "#undef MD4P_G\n"
    "#undef MD4P_H\n"
    "#undef MD4P_ROTL\n"
    "#undef MD4P_R1\n"
    "#undef MD4P_R2\n"
    "#undef MD4P_R3\n"
    "    state += uint4(a, b, c, d);\n"
    "}\n"
    "\n"
    "kernel void md4_packed_batch(\n"
    "    device const uint8_t    *packed_buf  [[buffer(0)]],\n"
    "    device const uint       *word_offset [[buffer(1)]],\n"
    "    device const uint8_t    *unused_mask [[buffer(2)]],\n"
    "    device const uint       *unused1     [[buffer(3)]],\n"
    "    device const ushort     *unused2     [[buffer(4)]],\n"
    "    device const uint8_t    *unused3     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys    [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes  [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_start = params.reserved32[0];\n"
    "    uint word_idx = word_start + tid;\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint pos = word_offset[word_idx];\n"
    "    uint len = packed_buf[pos++];\n"
    "\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint i = 0;\n"
    "    for (; i + 3 < len; i += 4) {\n"
    "        M[i >> 2] = (uint)packed_buf[pos + i]\n"
    "                  | ((uint)packed_buf[pos + i + 1] << 8)\n"
    "                  | ((uint)packed_buf[pos + i + 2] << 16)\n"
    "                  | ((uint)packed_buf[pos + i + 3] << 24);\n"
    "    }\n"
    "    uint tail = 0;\n"
    "    uint shift = 0;\n"
    "    for (; i < len; i++) {\n"
    "        tail |= (uint)packed_buf[pos + i] << shift;\n"
    "        shift += 8;\n"
    "    }\n"
    "    tail |= (uint)0x80 << shift;\n"
    "    M[i >> 2] = tail;\n"
    "    M[14] = len * 8;\n"
    "\n"
    "    uint4 state = uint4(0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u);\n"
    "    md4_compress_p(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        uint4 h = state;\n"
    "        ulong key = (ulong(h.y) << 32) | h.x;\n"
    "        uint fp = uint(key >> 32); if (fp == 0) fp = 1;\n"
    "        ulong ppos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "        bool found = false;\n"
    "        for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "            uint cfp = compact_fp[ppos]; if (cfp == 0) break;\n"
    "            if (cfp == fp) {\n"
    "                uint idx = compact_idx[ppos];\n"
    "                if (idx < params.hash_data_count) {\n"
    "                    ulong off = hash_data_off[idx];\n"
    "                    device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                    if (h.x == ref[0] && h.y == ref[1] && h.z == ref[2] && h.w == ref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "            }\n"
    "            ppos = (ppos + 1) & params.compact_mask;\n"
    "        }\n"
    "        if (!found && params.overflow_count > 0) {\n"
    "            int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "            while (lo <= hi2 && !found) {\n"
    "                int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "                if (key < mkey) hi2 = mid - 1;\n"
    "                else if (key > mkey) lo = mid + 1;\n"
    "                else {\n"
    "                    for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h.x == oref[0] && h.y == oref[1] && h.z == oref[2] && h.w == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    break;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (found) {\n"
    "            uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * HIT_STRIDE;\n"
    "                hits[base] = word_idx; hits[base+1] = 0; hits[base+2] = iter;\n"
    "                hits[base+3] = h.x; hits[base+4] = h.y;\n"
    "                hits[base+5] = h.z; hits[base+6] = h.w;\n"
    "                for (uint _z = 7; _z < HIT_STRIDE; _z++) hits[base+_z] = 0;\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            md5_to_hex_lc(state.x, state.y, state.z, state.w, M);\n"
    "            M[8] = 0x80;\n"
    "            for (int j = 9; j < 14; j++) M[j] = 0;\n"
    "            M[14] = 32 * 8; M[15] = 0;\n"
    "            state = uint4(0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u);\n"
    "            md4_compress_p(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
