/* Auto-generated from metal_md5_core.metal -- do not edit */
static const char metal_md5_core_str[] =
    "/*\n"
    " * $Revision: 1.1 $\n"
    " * $Log: metal_md5_core.metal,v $\n"
    " * Revision 1.1  2026/05/12 13:35:11  dlr\n"
    " * Initial check-in: Phase 1 Metal MD5 core. Mirrors gpu/gpu_md5_core.cl line-by-line for the byte-exact MD5 hash chain (template_init IV, template_finalize pad+compress with in-place M[] OR-merge to preserve the 12.3% wall regression fix from Memo B Phase B2). template_iterate pre-declared for Phase 2 -i loop port (Phase 1 max_iter==1 only). Pattern 3 enforced: every helper is static inline. Pattern 1 enforced: every pointer arg is thread-qualified or device-qualified.\n"
    " *\n"
    " */\n"
    "/* metal_md5_core.metal — MD5 algorithm extension for the generic\n"
    " * Metal dispatch template (Phase 1).\n"
    " *\n"
    " * Mirrors gpu/gpu_md5_core.cl (which is the OpenCL twin). Provides the\n"
    " * per-algorithm hooks that template_phase0 (in metal_template.metal)\n"
    " * calls into:\n"
    " *\n"
    " *   HASH_WORDS         — digest size in 32-bit words (4 for MD5)\n"
    " *   HASH_BLOCK_BYTES   — compress-block size (64 for MD5)\n"
    " *   template_state     — opaque per-lane state struct\n"
    " *   template_init      — initialize state to algorithm IV\n"
    " *   template_transform — absorb one HASH_BLOCK_BYTES block\n"
    " *   template_finalize  — pad and finalize a buffer; produces final state\n"
    " *   template_digest_compare — probe compact table from final state\n"
    " *   template_iterate   — re-hash digest as 32-byte hex_lc (-i loop)\n"
    " *   template_emit_hit_or_overflow — emit a hit (HASH_WORDS-aware)\n"
    " *\n"
    " * Phase 1 scope: raw MD5 only (no rules, no salt, no iter). Most\n"
    " * functions here ARE consumed by metal_template.metal even in Phase 1\n"
    " * (template_init/_finalize/_digest_compare/_emit_hit), but\n"
    " * template_iterate is unused in Phase 1 (max_iter==1 is the only\n"
    " * supported value). The fn is pre-declared anyway so Phase 2's iter\n"
    " * loop port is mechanical.\n"
    " *\n"
    " * Source-order at metallib build time (build_metallib.sh):\n"
    " *   1. metal_common.metal     — MetalParams, md5_block, probe_*, hex helpers, EMIT\n"
    " *   2. metal_md5_core.metal   — this file (per-algo hooks)\n"
    " *   3. metal_template.metal   — template_phase0 kernel\n"
    " *\n"
    " * Patterns 1/3 enforced: every fn is static inline (pattern 3); every\n"
    " * pointer arg is address-space-qualified (pattern 1).\n"
    " */\n"
    "\n"
    "#ifndef HASH_WORDS\n"
    "#define HASH_WORDS 4\n"
    "#endif\n"
    "#ifndef HASH_BLOCK_BYTES\n"
    "#define HASH_BLOCK_BYTES 64\n"
    "#endif\n"
    "\n"
    "/* template_state: per-lane MD5 chaining values. Mirrors gpu_md5_core.cl\n"
    " * line 71. SHA1 will carry 5; SHA256 8; SHA384/512 8 ulong. The template\n"
    " * does NOT introspect the struct; it only reads digest words through\n"
    " * template_finalize's effect + template_digest_compare. */\n"
    "struct template_state {\n"
    "    uint h[HASH_WORDS];\n"
    "};\n"
    "\n"
    "/* template_init: install MD5 IV. */\n"
    "static inline void template_init(thread template_state &st)\n"
    "{\n"
    "    st.h[0] = 0x67452301u;\n"
    "    st.h[1] = 0xEFCDAB89u;\n"
    "    st.h[2] = 0x98BADCFEu;\n"
    "    st.h[3] = 0x10325476u;\n"
    "}\n"
    "\n"
    "/* template_transform: absorb one 64-byte block. The block lives in the\n"
    " * lane's thread-buffer (template_phase0 builds it in `thread uchar buf[]`)\n"
    " * so `block` is `thread const uchar *`. Mirrors gpu_md5_core.cl line 86. */\n"
    "static inline void template_transform(thread template_state &st,\n"
    "                                      thread const uchar *block)\n"
    "{\n"
    "    uint M[16];\n"
    "    for (int j = 0; j < 16; j++) {\n"
    "        int b = j * 4;\n"
    "        M[j] = (uint)block[b]\n"
    "             | ((uint)block[b + 1] << 8)\n"
    "             | ((uint)block[b + 2] << 16)\n"
    "             | ((uint)block[b + 3] << 24);\n"
    "    }\n"
    "    md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "}\n"
    "\n"
    "/* template_finalize: process tail, append 0x80 + length-in-bits, absorb.\n"
    " *\n"
    " * Mirrors gpu_md5_core.cl::template_finalize byte-for-byte (line 131).\n"
    " * Critical: do NOT route through template_transform — instead build\n"
    " * M[16] directly via in-place OR-merge of input bytes (same as md5_buf\n"
    " * in gpu_md5_rules.cl). The byte-stores -> byte-loads round-trip in the\n"
    " * transform-wrapper version was a 12.3% wall regression on ioblade\n"
    " * (Memo B Phase B2 perf-fix). Metal Phase 1 inherits this shape so we\n"
    " * stay byte-exact AND perf-parity with the OpenCL twin.\n"
    " *\n"
    " * Pattern 1: `data` is `device const uchar *` — task #250 (Metal scratch\n"
    " * pool migration) moved per-lane buf out of thread-private storage into\n"
    " * a device-side pool to fix the M2 Max PSO failure\n"
    " * (Compute function exceeds available temporary registers). Reads from\n"
    " * the device buf are higher-latency than thread, but Metal's caches on\n"
    " * Apple Silicon hide this well in practice — and the move is the only\n"
    " * way to keep RULE_BUF_MAX at 40 KB without truncating rule outputs. */\n"
    "static inline void template_finalize(thread template_state &st,\n"
    "                                     device const uchar *data, int len)\n"
    "{\n"
    "    uint M[16];\n"
    "    int pos = 0;\n"
    "\n"
    "    /* Complete 64-byte blocks. */\n"
    "    while (len - pos >= HASH_BLOCK_BYTES) {\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int b = pos + j * 4;\n"
    "            M[j] = (uint)data[b]\n"
    "                 | ((uint)data[b + 1] << 8)\n"
    "                 | ((uint)data[b + 2] << 16)\n"
    "                 | ((uint)data[b + 3] << 24);\n"
    "        }\n"
    "        md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "        pos += HASH_BLOCK_BYTES;\n"
    "    }\n"
    "\n"
    "    /* Final block(s): tail bytes + 0x80 marker + zeros + length. */\n"
    "    int rem = len - pos;  /* 0..63 */\n"
    "\n"
    "    for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "\n"
    "    for (int i = 0; i < rem; i++) {\n"
    "        uint v = (uint)data[pos + i];\n"
    "        M[i >> 2] |= v << ((i & 3) * 8);\n"
    "    }\n"
    "    M[rem >> 2] |= (uint)0x80u << ((rem & 3) * 8);\n"
    "\n"
    "    if (rem < 56) {\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0u;\n"
    "        md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "    } else {\n"
    "        md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "        for (int j = 0; j < 16; j++) M[j] = 0u;\n"
    "        M[14] = (uint)(len * 8);\n"
    "        M[15] = 0u;\n"
    "        md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "    }\n"
    "}\n"
    "\n"
    "/* template_iterate: -i loop step (re-hash digest-as-hex32).\n"
    " *\n"
    " * Mirrors gpu_md5_core.cl::template_iterate (line 201). Phase 1 does\n"
    " * NOT use this (max_iter==1 only); pre-declared for Phase 2.\n"
    " *\n"
    " * algo_mode == 0 (JOB_MD5): lowercase hex.\n"
    " * algo_mode == 1 (JOB_MD5UC): uppercase hex (B7.7a 2026-05-07).\n"
    " *\n"
    " * GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE mirrors gpu_md5_core.cl line 200 and\n"
    " * is set ONLY in this core; metal_template.metal #ifdefs on it at the call\n"
    " * site so every other core keeps the legacy one-argument shape. */\n"
    "#define GPU_TEMPLATE_ITERATE_HAS_ALGO_MODE 1\n"
    "static inline void template_iterate(thread template_state &st, uint algo_mode)\n"
    "{\n"
    "    uint M[16];\n"
    "    if (algo_mode == 1u) {\n"
    "        md5_to_hex_uc(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "    } else {\n"
    "        md5_to_hex_lc(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "    }\n"
    "    M[8] = 0x80u;\n"
    "    for (int j = 9; j < 14; j++) M[j] = 0u;\n"
    "    M[14] = 32u * 8u;     /* 32 hex chars = 256 bits */\n"
    "    M[15] = 0u;\n"
    "    /* Reinitialize state to IV, then absorb. */\n"
    "    st.h[0] = 0x67452301u;\n"
    "    st.h[1] = 0xEFCDAB89u;\n"
    "    st.h[2] = 0x98BADCFEu;\n"
    "    st.h[3] = 0x10325476u;\n"
    "    md5_block(st.h[0], st.h[1], st.h[2], st.h[3], M);\n"
    "}\n"
    "\n"
    "/* template_digest_compare: probe the compact table with state's first 4\n"
    " * digest words. Wrapper around probe_compact_idx.\n"
    " *\n"
    " * Pattern 1: all global tables `device const`; out_idx `thread`. */\n"
    "static inline int template_digest_compare(\n"
    "    thread const template_state &st,\n"
    "    device const uint  *compact_fp,\n"
    "    device const uint  *compact_idx,\n"
    "    ulong               compact_mask,\n"
    "    uint                max_probe,\n"
    "    uint                hash_data_count,\n"
    "    device const uchar *hash_data_buf,\n"
    "    device const ulong *hash_data_off,\n"
    "    device const ulong *overflow_keys,\n"
    "    device const uchar *overflow_hashes,\n"
    "    device const uint  *overflow_offsets,\n"
    "    uint                overflow_count,\n"
    "    thread uint        *out_idx)\n"
    "{\n"
    "    return probe_compact_idx(\n"
    "        st.h[0], st.h[1], st.h[2], st.h[3],\n"
    "        compact_fp, compact_idx,\n"
    "        compact_mask, max_probe, hash_data_count,\n"
    "        hash_data_buf, hash_data_off,\n"
    "        overflow_keys, overflow_hashes, overflow_offsets, overflow_count,\n"
    "        out_idx);\n"
    "}\n"
    "\n"
    "/* template_emit_hit_or_overflow: dedup+overflow-aware hit emit. Wraps\n"
    " * EMIT_HIT_4_DEDUP_OR_OVERFLOW (MD5 = 4 uint32 digest words). Mirrors\n"
    " * gpu_md5_core.cl line 266.\n"
    " *\n"
    " * Macro form (not inline fn) because the underlying EMIT macro takes\n"
    " * the hits/hit_count/etc. as device-atomic pointers; threading those\n"
    " * through an inline wrapper requires Metal's overloaded address-space\n"
    " * deduction which is fragile at JIT time. Keep it a macro to mirror\n"
    " * the OpenCL twin's macro form 1:1.  */\n"
    "#define template_emit_hit_or_overflow(hits, hit_count, max_hits,                       \\\n"
    "                                      st_ref, widx, sidx, iter,                        \\\n"
    "                                      hashes_shown, matched_idx, dedup_mask,           \\\n"
    "                                      ovr_set, ovr_gid, lane_gid)                      \\\n"
    "    EMIT_HIT_4_DEDUP_OR_OVERFLOW((hits), (hit_count), (max_hits),                      \\\n"
    "                                 (widx), (sidx), (iter),                               \\\n"
    "                                 (st_ref).h[0], (st_ref).h[1],                         \\\n"
    "                                 (st_ref).h[2], (st_ref).h[3],                         \\\n"
    "                                 (hashes_shown), (matched_idx), (dedup_mask),          \\\n"
    "                                 (ovr_set), (ovr_gid), (lane_gid))\n"
;
