/* Auto-generated from metal_sha1_packed.metal -- do not edit */
static const char metal_sha1_packed_str[] =
    "/* metal_sha1_packed.metal — Packed password SHA1 kernel\n"
    " *\n"
    " * Metal port of gpu_sha1_packed.cl.\n"
    " *\n"
    " * Same structure as metal_md5_packed but with SHA1:\n"
    " *   - Big-endian byte swap on M[] before compress\n"
    " *   - 5-word state, bit count at M[15] (BE)\n"
    " *\n"
    " * Primitives (bswap32, sha1_compress, sha1_to_hex_lc, MetalParams, HIT_STRIDE)\n"
    " * provided by metal_common.metal.\n"
    " */\n"
    "\n"
    "kernel void sha1_packed_batch(\n"
    "    device const uint8_t    *packed_buf  [[buffer(0)]],\n"
    "    device const uint       *word_offset [[buffer(1)]],\n"
    "    device const uint8_t    *unused_mask [[buffer(2)]],\n"
    "    device const uint       *unused1     [[buffer(3)]],\n"
    "    device const ushort     *unused2     [[buffer(4)]],\n"
    "    device const uint8_t    *unused3     [[buffer(5)]],\n"
    "    device const uint       *compact_fp  [[buffer(6)]],\n"
    "    device const uint       *compact_idx [[buffer(7)]],\n"
    "    constant MetalParams    &params      [[buffer(8)]],\n"
    "    device const uint8_t    *hash_data_buf [[buffer(9)]],\n"
    "    device const uint64_t   *hash_data_off [[buffer(10)]],\n"
    "    device const ushort     *hash_data_len [[buffer(11)]],\n"
    "    device uint             *hits         [[buffer(12)]],\n"
    "    device atomic_uint      *hit_count    [[buffer(13)]],\n"
    "    device const uint64_t   *overflow_keys    [[buffer(14)]],\n"
    "    device const uint8_t    *overflow_hashes  [[buffer(15)]],\n"
    "    device const uint       *overflow_offsets [[buffer(16)]],\n"
    "    device const ushort     *overflow_lengths [[buffer(17)]],\n"
    "    uint                     tid          [[thread_position_in_grid]],\n"
    "    uint                     lid          [[thread_position_in_threadgroup]],\n"
    "    uint                     tgsize       [[threads_per_threadgroup]])\n"
    "{\n"
    "    uint word_start = params.reserved32[0];\n"
    "    uint word_idx = word_start + tid;\n"
    "    if (word_idx >= params.num_words) return;\n"
    "\n"
    "    uint pos = word_offset[word_idx];\n"
    "    uint len = packed_buf[pos++];\n"
    "\n"
    "    /* Build M[16] in little-endian first (like MD5) */\n"
    "    uint M[16];\n"
    "    for (int i = 0; i < 16; i++) M[i] = 0;\n"
    "\n"
    "    uint i = 0;\n"
    "    for (; i + 3 < len; i += 4) {\n"
    "        M[i >> 2] = (uint)packed_buf[pos + i]\n"
    "                  | ((uint)packed_buf[pos + i + 1] << 8)\n"
    "                  | ((uint)packed_buf[pos + i + 2] << 16)\n"
    "                  | ((uint)packed_buf[pos + i + 3] << 24);\n"
    "    }\n"
    "    uint tail = 0;\n"
    "    uint shift = 0;\n"
    "    for (; i < len; i++) {\n"
    "        tail |= (uint)packed_buf[pos + i] << shift;\n"
    "        shift += 8;\n"
    "    }\n"
    "    tail |= (uint)0x80 << shift;\n"
    "    M[i >> 2] = tail;\n"
    "    M[14] = len * 8;  /* temp: LE bitlen for swap */\n"
    "\n"
    "    /* Byte-swap to big-endian for SHA1 */\n"
    "    uint bitlen = M[14];\n"
    "    for (int j = 0; j < 16; j++) M[j] = bswap32(M[j]);\n"
    "    M[14] = 0;\n"
    "    M[15] = bitlen;\n"
    "\n"
    "    /* SHA1 compress */\n"
    "    uint state[5] = { 0x67452301u, 0xEFCDAB89u, 0x98BADCFEu, 0x10325476u, 0xC3D2E1F0u };\n"
    "    sha1_compress(state, M);\n"
    "\n"
    "    uint max_iter = params.max_iter;\n"
    "    for (uint iter = 1; iter <= max_iter; iter++) {\n"
    "        /* Byte-swap state to LE for compact table probe */\n"
    "        uint h[5];\n"
    "        for (int j = 0; j < 5; j++) h[j] = bswap32(state[j]);\n"
    "\n"
    "        ulong key = (ulong(h[1]) << 32) | h[0];\n"
    "        uint fp = h[1]; if (fp == 0) fp = 1;\n"
    "        ulong ppos = (key ^ (key >> 32)) & params.compact_mask;\n"
    "        bool found = false;\n"
    "        for (uint p = 0; p < params.max_probe && !found; p++) {\n"
    "            uint cfp = compact_fp[ppos]; if (cfp == 0) break;\n"
    "            if (cfp == fp) {\n"
    "                uint idx = compact_idx[ppos];\n"
    "                if (idx < params.hash_data_count) {\n"
    "                    ulong off = hash_data_off[idx];\n"
    "                    device const uint *ref = (device const uint *)(hash_data_buf + off);\n"
    "                    if (h[0] == ref[0] && h[1] == ref[1] && h[2] == ref[2] && h[3] == ref[3])\n"
    "                        found = true;\n"
    "                }\n"
    "            }\n"
    "            ppos = (ppos + 1) & params.compact_mask;\n"
    "        }\n"
    "        if (!found && params.overflow_count > 0) {\n"
    "            int lo = 0, hi2 = int(params.overflow_count) - 1;\n"
    "            while (lo <= hi2 && !found) {\n"
    "                int mid = (lo + hi2) / 2; ulong mkey = overflow_keys[mid];\n"
    "                if (key < mkey) hi2 = mid - 1;\n"
    "                else if (key > mkey) lo = mid + 1;\n"
    "                else {\n"
    "                    for (int d = mid; d >= 0 && overflow_keys[d] == key && !found; d--) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    for (int d = mid+1; d < int(params.overflow_count) && overflow_keys[d] == key && !found; d++) {\n"
    "                        device const uint *oref = (device const uint *)(overflow_hashes + overflow_offsets[d]);\n"
    "                        if (h[0] == oref[0] && h[1] == oref[1] && h[2] == oref[2] && h[3] == oref[3])\n"
    "                            found = true;\n"
    "                    }\n"
    "                    break;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        if (found) {\n"
    "            uint slot = atomic_fetch_add_explicit(hit_count, 1, memory_order_relaxed);\n"
    "            if (slot < params.max_hits) {\n"
    "                uint base = slot * HIT_STRIDE;\n"
    "                hits[base] = word_idx; hits[base+1] = 0; hits[base+2] = iter;\n"
    "                for (int ii = 0; ii < 5; ii++) hits[base+3+ii] = h[ii];\n"
    "                for (uint _z = 8; _z < HIT_STRIDE; _z++) hits[base+_z] = 0;\n"
    "            }\n"
    "        }\n"
    "        if (iter < max_iter) {\n"
    "            sha1_to_hex_lc(state, M);\n"
    "            M[10] = 0x80000000u;\n"
    "            for (int j = 11; j < 15; j++) M[j] = 0;\n"
    "            M[15] = 40 * 8;\n"
    "            state[0] = 0x67452301u; state[1] = 0xEFCDAB89u;\n"
    "            state[2] = 0x98BADCFEu; state[3] = 0x10325476u; state[4] = 0xC3D2E1F0u;\n"
    "            sha1_compress(state, M);\n"
    "        }\n"
    "    }\n"
    "}\n"
;
