/*
 * hx8_to_c.c -- build-time tool that converts the hx.8 algorithm
 *               catalog into codegen/hx_specs_data.c, a C-literal
 *               serialization of pre-compiled hx_program structs.
 *
 * Per spec D12.2.c REVISED-AGAIN (Path A) from
 * ~/.claude/projects/-Users-dlr-src-mdfind/memory/
 *   project_hx_codegen_phase2_3_spec_2026-05-21.md:
 *
 *   1. Open hx.8 (path via argv[1]); skip troff header before first eN row.
 *   2. For each `eN<TAB>NAME<TAB>EXPRESSION_OR_MARKUP` row:
 *      - detect outlier (\fI italics, T{ table block, \(em see Note)
 *      - non-outlier: strip remaining troff escapes, call hx_compile_expr
 *      - on success: serialize resulting hx_program to C literal
 *      - on compile failure: warn to stderr, mark compile_failed=1
 *   3. Emit codegen/hx_specs_data.c with:
 *      - banner: AUTO-GENERATED by tools/hx8_to_c -- DO NOT EDIT
 *      - per-entry static const initializers (code[], strings[], etc.)
 *      - top-level const struct hx_spec_entry hx_specs_data[] array
 *      - per-entry comment block with original expression + hx.8 line
 *   4. Summary report to stderr.
 *   5. exit(0) on success (any non-fatal soft-failures), nonzero only
 *      on truly fatal errors (hx.8 missing, output write failure).
 *
 * The tool links against the existing hx library ($(HX_OBJS)) plus
 * hashpipe.o (for hx_register_hashpipe_types(), which registers the
 * full 994-primitive function table before hx_compile_expr is invoked).
 *
 * mdxfind itself contains NO hx parser; only the compiled-in
 * hx_specs_data[] array. The tool runs at make time on the build host.
 *
 * Sub-phase 5a.1 (2026-05-22): each emitted hx_spec_entry initializer
 * now also includes a .call_names pointer at the per-program
 * _hx_callnames_NNN[] sidecar (already emitted earlier in the same
 * file). NULL for outliers / compile-fails. Enables codegen emitters
 * to resolve per-call-site function names via hx_callname_for_entry.
 *
 * hx_dedup_check Tier 2 (2026-05-28), Features 1 + 5: after the main
 * emission loop, run a build-time INTRA-CATALOG DUPLICATE WARNING pass.
 * For every pair of compiled entries with byte-identical (Layer 1 +
 * role-canon + Layer 2 commutative) bytecode, emit ONE informational
 * WARNING to stderr (never to stdout -- the C source channel). These
 * warnings DO NOT fail the build: the catalog's ~55 known duplicate
 * groups are INTENTIONAL historical aliases per
 * feedback_catalog_aliases_are_historical_dont_alter.md. The pass is
 * purely so the dedup truth surfaces on EVERY regenerate, not only when
 * an operator runs `tools/hx_dedup_check --scan`.
 *
 * Feature 5: a `# DEDUP_OK` annotation suppresses the warning for an
 * entry the operator has reviewed and intentionally kept. Two equivalent
 * forms are accepted (no hx.8 troff-table contamination either way):
 *   - SIDECAR FILE  tools/dedup_ok.txt : lines of `eN [eM ...] : reason`
 *     (and `#`-prefixed file comments). Read at tool startup.
 *   - TROFF COMMENT in hx.8 : a `.\" DEDUP_OK eN [eM ...]: reason` line
 *     (invisible in the rendered manual; skipped by parse_row). Picked
 *     up during the line walk.
 * An entry whose eN is annotated DEDUP_OK is excluded from BOTH sides of
 * a warning pair. We do NOT auto-annotate the known dupes -- the operator
 * decides; this only builds the mechanism.
 *
 * 1.1
 * hx8_to_c.c,v
 * Revision 1.1  2026/05/21 23:22:54  dlr
 * sub-phase 2a.2: build-time tool that reads hx.8 and emits codegen/hx_specs_data.c. Per spec D12.2.c Path A: links existing hx library via -DHX_STANDALONE -DHX_NO_MAIN; pre-scans expressions to stub-register unknown function names so hx_compile_expr never hits its exit-1 path; serializes resulting hx_program to C literal. 994 entries total: 781 non-outlier success, 210 outlier, 3 compile-fail (NTLM and another with bracket footnote, e522 with extra closing paren).
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <ctype.h>
#include <errno.h>

#include "../hx_vm.h"
#include "hx_program_cmp.h"   /* shared programs_equal() + Layer 2 canon */

/*
 * WARN(...) -- stream-ordering hygiene macro for all stderr writes.
 *
 * Belt-and-suspenders fix for the 2026-05-26 corruption incident where
 * an ad-hoc regen used `tools/hx8_to_c hx.8 > out.c 2>&1`, merging
 * stderr diagnostics into the C source output and breaking the v1.503
 * release build deep inside struct initializers (compiled cleanly to
 * grep, FAILED at cc).
 *
 * The discipline (NEVER 2>&1) is documented in operator memo
 * feedback_hx8_to_c_no_stderr_merge.md. This macro adds source-side
 * protection: every stderr write flushes stdout's in-flight buffer
 * BEFORE writing, and flushes stderr immediately after. Even if an
 * operator accidentally uses 2>&1, the merged output should at least
 * be deterministic and not interleaved mid-line with in-flight stdout
 * struct-initializer bytes.
 *
 * Use WARN(fmt, ...) in place of every fprintf(stderr, fmt, ...).
 */
#define WARN(...) do { \
    fflush(stdout); \
    fprintf(stderr, __VA_ARGS__); \
    fflush(stderr); \
} while (0)

/* Forward declarations of hx library entry points we link against. */
extern hx_program *hx_compile_expr(const char *expr, const char *script_file);

/*
 * Stub hashfn used for placeholder registry entries -- we never RUN
 * the compiled program in this tool, only serialize its bytecode, so
 * a no-op body is fine. The function pointer is part of hx_func_entry's
 * required surface; lookup against name is all we need.
 */
static void stub_hashfn(hx_func_entry *self, hx_val *args, int nargs,
                        hx_val *result, hx_arena *arena, uint8_t role)
{
    (void)self; (void)args; (void)nargs;
    (void)result; (void)arena; (void)role;
}

/*
 * Pre-scan an expression string for identifier(...) call sites and
 * register a stub entry under each name not already in the registry.
 * Strips any output-role suffix (`_bin`, `_hex`, `_b64`, `_mcf`) so the
 * base name resolves cleanly.
 *
 * This dodges hx_compile.c's `exit(1)` on unknown function -- every
 * function the parser sees will be resolvable. The downside is we
 * cannot detect typos in hx.8 at tool-build time; the tradeoff is
 * acceptable because hx.8 is checked + lint-driven on its own.
 */
static void prescan_register_stubs(const char *expr)
{
    const char *p = expr;
    while (*p) {
        /* find an identifier */
        if (isalpha((unsigned char)*p) || *p == '_') {
            const char *start = p;
            while (*p && (isalnum((unsigned char)*p) || *p == '_'))
                p++;
            /* did this identifier immediately precede a '(' (or whitespace
             * then '(')? if so, it's a function call. */
            const char *q = p;
            while (*q == ' ' || *q == '\t') q++;
            if (*q == '(') {
                size_t n = (size_t)(p - start);
                if (n > 0 && n < 64) {
                    char name[64];
                    memcpy(name, start, n);
                    name[n] = '\0';

                    /* strip role suffix */
                    if (n > 4 && name[n - 4] == '_') {
                        const char *s = name + n - 3;
                        if (memcmp(s, "bin", 3) == 0 ||
                            memcmp(s, "hex", 3) == 0 ||
                            memcmp(s, "b64", 3) == 0 ||
                            memcmp(s, "mcf", 3) == 0)
                            name[n - 4] = '\0';
                    }

                    /* register only if not already in registry */
                    if (!hx_func_lookup(name)) {
                        hx_func_register(name, stub_hashfn, 64,
                                          NULL, 0,
                                          ROLE_CAP_BIN | ROLE_CAP_HEX |
                                          ROLE_CAP_B64,
                                          ROLE_HEX);
                    }
                }
            }
        } else {
            p++;
        }
    }
}

/*
 * hashpipe registers its compute_* table into the hx function registry.
 * The bridge is in hashpipe.c; we link against it. Calling once at
 * tool startup makes all 994 algorithms resolvable by hx_compile_expr.
 *
 * The function is `static` inside hashpipe.c so we can't call it directly
 * from outside. Instead we register a minimal subset of the algorithms
 * the codegen will actually emit kernels for in Phase 2-3 (md5, sha1,
 * sha256, sha512, md4 etc.) plus the always-available algorithms that
 * hx already registers without hashpipe. The non-resolvable algorithms
 * will compile-fail and route to override -- exactly the same fate as
 * outliers, no information loss.
 *
 * Per Path A, full hashpipe integration is desirable but `static` on
 * hx_register_hashpipe_types is a real-world C linkage barrier. The
 * fallback (compile-fail = soft outlier) gives identical downstream
 * behavior for the 994-primitive long tail; Phase 5 expansion can lift
 * the `static` qualifier and link properly.
 */

/* ---------- DEDUP_OK suppression set (Feature 5) ---------- */

/*
 * Set of eN (job_enum) values for which the build-time intra-catalog
 * duplicate WARNING (Feature 1) is suppressed. Populated from:
 *   1. tools/dedup_ok.txt sidecar (if present), and
 *   2. `.\" DEDUP_OK eN [eM ...]: reason` troff-comment lines in hx.8.
 * Both forms are optional and additive. An eN here is excluded from BOTH
 * sides of any warning pair.
 */
static int  *g_dedup_ok = NULL;
static int   g_dedup_ok_n = 0;
static int   g_dedup_ok_cap = 0;

static void dedup_ok_add(int en)
{
    for (int i = 0; i < g_dedup_ok_n; i++)
        if (g_dedup_ok[i] == en) return;        /* already present */
    if (g_dedup_ok_n >= g_dedup_ok_cap) {
        g_dedup_ok_cap = g_dedup_ok_cap ? g_dedup_ok_cap * 2 : 16;
        g_dedup_ok = (int *)realloc(g_dedup_ok,
                                    (size_t)g_dedup_ok_cap * sizeof(int));
        if (!g_dedup_ok) { WARN("FATAL: hx8_to_c: OOM dedup_ok\n"); exit(2); }
    }
    g_dedup_ok[g_dedup_ok_n++] = en;
}

static int dedup_ok_has(int en)
{
    for (int i = 0; i < g_dedup_ok_n; i++)
        if (g_dedup_ok[i] == en) return 1;
    return 0;
}

/*
 * Parse a DEDUP_OK payload: a run of `eNNN` tokens up to an optional
 * ':' (after which is free-text reason). Adds each eNNN to the set.
 * `p` points just past the "DEDUP_OK" keyword. Tolerant of leading
 * spaces, commas, and 'e' prefixes (e288, 288, e288,e539 all work).
 */
static void dedup_ok_parse_payload(const char *p)
{
    while (*p && *p != ':' && *p != '\n' && *p != '\r') {
        while (*p == ' ' || *p == '\t' || *p == ',') p++;
        if (*p == 'e' || *p == 'E') p++;
        if (isdigit((unsigned char)*p)) {
            int en = 0;
            while (isdigit((unsigned char)*p)) {
                en = en * 10 + (*p - '0');
                p++;
            }
            dedup_ok_add(en);
        } else if (*p == ':' || *p == '\0' || *p == '\n' || *p == '\r') {
            break;
        } else {
            /* unexpected token before ':'; stop to avoid misreading the
             * reason text as eN values. */
            break;
        }
    }
}

/*
 * Load tools/dedup_ok.txt if present. Format: one or more whitespace/
 * comma-separated eN values, optional `:` then a free-text reason, per
 * line. `#`-prefixed lines and blank lines are ignored. Missing file is
 * NOT an error (the mechanism is opt-in). Path is relative to CWD (make
 * runs from the project root, same as hx8_to_c's other relative paths).
 */
static void dedup_ok_load_sidecar(const char *path)
{
    FILE *fp = fopen(path, "r");
    if (!fp) return;                            /* opt-in: absent is fine */
    char buf[512];
    int added_before = g_dedup_ok_n;
    while (fgets(buf, sizeof(buf), fp)) {
        char *p = buf;
        while (*p == ' ' || *p == '\t') p++;
        if (*p == '#' || *p == '\0' || *p == '\n' || *p == '\r') continue;
        dedup_ok_parse_payload(p);
    }
    fclose(fp);
    WARN("hx8_to_c: DEDUP_OK sidecar %s: %d eN suppressed\n",
         path, g_dedup_ok_n - added_before);
}

/*
 * Recognize a `.\" DEDUP_OK ...` troff-comment line during the hx.8
 * walk. Returns 1 if the line was a DEDUP_OK directive (and consumed),
 * 0 otherwise. The leading `.\"` is the troff comment marker; we accept
 * optional whitespace before the DEDUP_OK keyword.
 */
static int dedup_ok_try_line(const char *line)
{
    const char *p = line;
    while (*p == ' ' || *p == '\t') p++;
    /* troff comment marker: .\" (a dot, backslash, double-quote). In the
     * file this is the three chars '.', '\\', '"'. */
    if (p[0] != '.' || p[1] != '\\' || p[2] != '"') return 0;
    p += 3;
    while (*p == ' ' || *p == '\t') p++;
    if (strncmp(p, "DEDUP_OK", 8) != 0) return 0;
    p += 8;
    dedup_ok_parse_payload(p);
    return 1;
}

/* ---------- input buffer ---------- */

static char *slurp(const char *path, size_t *out_len)
{
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        WARN("FATAL: hx8_to_c: cannot open %s: %s\n",
             path, strerror(errno));
        exit(2);
    }
    if (fseek(fp, 0, SEEK_END) != 0) { fclose(fp); return NULL; }
    long n = ftell(fp);
    if (n < 0) { fclose(fp); return NULL; }
    rewind(fp);
    char *buf = (char *)malloc((size_t)n + 1);
    if (!buf) { fclose(fp); return NULL; }
    size_t got = fread(buf, 1, (size_t)n, fp);
    fclose(fp);
    buf[got] = '\0';
    if (out_len) *out_len = got;
    return buf;
}

/* ---------- troff stripping ---------- */

/*
 * Detect whether an expression-column field is markup-style rather than
 * a real hx expression. Triggers:
 *   - \fI ... \fP italics around prose (e.g. "(complex: iterates ...)")
 *   - "see Note [N]" reference
 *   - T{ ... T} block (multi-line table cell -- expression spread
 *     across lines, generally too irregular for the parser path)
 *   - \(em-only or other free-form markup without function calls
 *
 * Returns 1 if the field is an outlier.
 */
static int is_markup_outlier(const char *s)
{
    if (!s || !*s) return 1;
    if (strstr(s, "\\fI") != NULL) return 1;   /* italics start */
    if (strstr(s, "T{")   != NULL) return 1;   /* table-cell block */
    if (strstr(s, "see Note") != NULL) return 1;
    if (strstr(s, "\\(em") != NULL && strstr(s, "(") == NULL) return 1;
    /* Heuristic: if the field contains no '(' at all, it's almost
     * certainly markup, not an hx expression (every algorithm has at
     * least one function call). The exceptions are pure literals like
     * '"00000000" . cut(...)' which DO contain '('. */
    if (strchr(s, '(') == NULL) return 1;
    return 0;
}

/*
 * Sub-phase 5c.1 (2026-05-27): extract the Note reference number N from a
 * trailing "(see Note [N])" annotation. Returns N (>0) if present, else 0.
 *
 * hx.8 marks multi-emit and other special-handling algorithms with a
 * trailing "(see Note [N])" after the otherwise-real hx expression. For
 * the multi-emit colon class (Note [24]) the leading text is a genuine
 * 6-op FAMILY_MD5PASS expression (e.g. "md5(md5(pass).pass)"); the
 * annotation is what trips is_markup_outlier()'s "see Note" check. This
 * helper lets the generator recover N so it can record note_ref and (for
 * the activated e123 case) strip the suffix and compile the real program.
 */
static int extract_note_ref(const char *s)
{
    if (!s) return 0;
    const char *p = strstr(s, "see Note");
    if (!p) return 0;
    /* Advance to the '[' after "see Note". */
    const char *lb = strchr(p, '[');
    if (!lb) return 0;
    int n = 0;
    const char *d = lb + 1;
    if (!isdigit((unsigned char)*d)) return 0;
    while (isdigit((unsigned char)*d)) {
        n = n * 10 + (*d - '0');
        d++;
    }
    return n;
}

/*
 * Sub-phase 5c.1 (2026-05-27): return a newly malloc'd copy of s with any
 * trailing "(see Note [N])" annotation (and the whitespace before it)
 * removed. Caller frees. If no annotation is present, returns a plain
 * copy. The leading expression text (before the annotation) is preserved
 * verbatim so strip_troff_escapes + hx_compile_expr see the real
 * expression.
 */
static char *strip_note_markup(const char *s)
{
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 1);
    if (!out) return NULL;
    memcpy(out, s, n + 1);
    /* Find "(see Note" -- the annotation always opens with '(' then the
     * literal "see Note". Cut at the '(' and trim trailing whitespace. */
    char *paren = strstr(out, "(see Note");
    if (paren) {
        char *cut = paren;
        while (cut > out && (cut[-1] == ' ' || cut[-1] == '\t'))
            cut--;
        *cut = '\0';
    }
    return out;
}

/*
 * Strip a small set of recognized troff escapes from an expression
 * string. The hx parser does not understand troff; the build tool
 * cleans before calling hx_compile_expr.
 *
 * Conservative -- only strips what is known to appear in hx.8 expression
 * cells: \fB...\fP (bold), \fR (roman), \s-2 ... \s+2 (size shift),
 * \\ (backslash literal: collapse \\xNN to \xNN since troff doubles).
 *
 * Returns a newly malloc'd cleaned string. Caller frees.
 */
static char *strip_troff_escapes(const char *s)
{
    size_t n = strlen(s);
    char *out = (char *)malloc(n + 1);
    if (!out) return NULL;
    size_t i = 0, j = 0;
    while (i < n) {
        if (s[i] == '\\' && i + 1 < n) {
            /* \fB, \fI, \fP, \fR : font switches, 3 chars total */
            if (s[i+1] == 'f' && i + 2 < n) {
                i += 3; continue;
            }
            /* \s-2, \s+2, \s0 : size shift, 4 chars (or 3 for \s0) */
            if (s[i+1] == 's' && i + 2 < n) {
                if (s[i+2] == '-' || s[i+2] == '+') { i += 4; continue; }
                else { i += 3; continue; }
            }
            /* \\ : doubled backslash -- preserve as single backslash so
             *      the hx parser sees \xNN etc. as we want. */
            if (s[i+1] == '\\') {
                out[j++] = '\\';
                i += 2;
                continue;
            }
            /* \(em : em-dash; drop it */
            if (s[i+1] == '(' && i + 3 < n) {
                i += 4; continue;
            }
        }
        out[j++] = s[i++];
    }
    out[j] = '\0';
    /* trim trailing whitespace */
    while (j > 0 && (out[j-1] == ' ' || out[j-1] == '\t' ||
                     out[j-1] == '\n' || out[j-1] == '\r'))
        out[--j] = '\0';
    return out;
}

/* ---------- C-literal serialization ---------- */

/*
 * Emit a C string literal that round-trips arbitrary bytes -- escapes
 * backslash, double-quote, control chars; passes printable ASCII through.
 */
static void emit_cstr(FILE *fp, const char *s, int len)
{
    fputc('"', fp);
    for (int i = 0; i < len; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '\\') fputs("\\\\", fp);
        else if (c == '"') fputs("\\\"", fp);
        else if (c == '\n') fputs("\\n", fp);
        else if (c == '\r') fputs("\\r", fp);
        else if (c == '\t') fputs("\\t", fp);
        else if (c < 0x20 || c >= 0x7f) fprintf(fp, "\\x%02x", c);
        else fputc(c, fp);
    }
    fputc('"', fp);
}

/* Emit a single instruction as a designated initializer line. */
static void emit_inst(FILE *fp, const hx_inst *ip, int idx,
                      const hx_program *prog)
{
    fprintf(fp, "    [%d] = { .op = %u", idx, (unsigned)ip->op);
    switch (ip->op) {
    case OP_PUSH_VAR:
    case OP_STORE:
    case OP_INC:
        fprintf(fp, ", .u.slot = %d", ip->u.slot);
        break;
    case OP_PUSH_STR:
        fprintf(fp, ", .u.stridx = %d", ip->u.stridx);
        break;
    case OP_PUSH_INT:
        fprintf(fp, ", .u.ival = (int64_t)%lld",
                (long long)ip->u.ival);
        break;
    case OP_JUMP:
    case OP_JUMP_LE: case OP_JUMP_LT:
    case OP_JUMP_GT: case OP_JUMP_GE:
    case OP_JUMP_EQ: case OP_JUMP_NE:
        fprintf(fp, ", .u.addr = %d", ip->u.addr);
        break;
    case OP_CALL:
        /*
         * .u.call.entry is a runtime pointer -- we cannot serialize a
         * cross-process pointer. Encode the function NAME as a sidecar
         * string; the runtime walker resolves entry via hx_func_lookup
         * lazily (or, more efficiently, at first program use).
         *
         * For 2a.2 we emit the name in a comment + leave entry=NULL;
         * the walker's emit_call_opencl uses an alongside name table
         * (hxcalls_*[]) keyed by program index. See generated code.
         */
        fprintf(fp, ", .u.call = { .entry = NULL, .nargs = %d, .role = %u } "
                    "/* fn=\"%s\" */",
                ip->u.call.nargs, (unsigned)ip->u.call.role,
                ip->u.call.entry ? ip->u.call.entry->name : "?");
        break;
    case OP_CONCAT:
    case OP_HALT:
    case OP_DUP:
    case OP_POP:
    default:
        break;
    }
    fprintf(fp, " },\n");
    (void)prog;
}

/*
 * Emit one entry's hx_program initializer (struct literal). Per-entry
 * code/strings/varnames statics are emitted inline at the call site.
 */
static void emit_entry_program(FILE *fp, int eidx, const hx_program *prog)
{
    fprintf(fp,
        "static const hx_program _hx_program_%d = {\n"
        "    .code      = (hx_inst *)_hx_code_%d,\n"
        "    .ncode     = %d,\n",
        eidx, eidx, prog->ncode);
    if (prog->nstrings > 0) {
        fprintf(fp,
            "    .strings   = (char **)_hx_strings_%d,\n"
            "    .strlens   = (int *)_hx_strlens_%d,\n"
            "    .nstrings  = %d,\n",
            eidx, eidx, prog->nstrings);
    } else {
        fprintf(fp,
            "    .strings   = NULL,\n"
            "    .strlens   = NULL,\n"
            "    .nstrings  = 0,\n");
    }
    fprintf(fp,
        "    .varnames  = (char **)_hx_varnames_%d,\n"
        "    .nvars     = %d,\n"
        "    .max_stack = %d,\n"
        "    .has_emit  = %d,\n"
        "};\n",
        eidx, prog->nvars, prog->max_stack, prog->has_emit);
}

/* ---------- row parsing ---------- */

/*
 * Try to parse a row of the form `eN<TAB>NAME<TAB>EXPR`. Returns 1
 * on success and fills *out_type, *out_name, *out_expr (all malloc'd).
 * Returns 0 if the line is not a row (header, comment, blank).
 */
static int parse_row(const char *line,
                     int *out_type,
                     char **out_name,
                     char **out_expr)
{
    if (line[0] != 'e' || !isdigit((unsigned char)line[1])) return 0;
    const char *p = line + 1;
    while (*p && isdigit((unsigned char)*p)) p++;
    if (*p != '\t') return 0;
    int type = atoi(line + 1);

    const char *name_start = p + 1;
    const char *name_end = strchr(name_start, '\t');
    if (!name_end) return 0;
    int name_len = (int)(name_end - name_start);
    if (name_len <= 0 || name_len > 128) return 0;

    const char *expr_start = name_end + 1;
    /* strip trailing newline from expression */
    const char *expr_end = expr_start + strlen(expr_start);
    while (expr_end > expr_start &&
           (expr_end[-1] == '\n' || expr_end[-1] == '\r'))
        expr_end--;
    int expr_len = (int)(expr_end - expr_start);

    *out_type = type;
    *out_name = (char *)malloc((size_t)name_len + 1);
    *out_expr = (char *)malloc((size_t)expr_len + 1);
    if (!*out_name || !*out_expr) {
        free(*out_name); free(*out_expr);
        *out_name = *out_expr = NULL;
        return 0;
    }
    memcpy(*out_name, name_start, name_len);
    (*out_name)[name_len] = '\0';
    memcpy(*out_expr, expr_start, expr_len);
    (*out_expr)[expr_len] = '\0';
    return 1;
}

/* ---------- main ---------- */

int main(int argc, char **argv)
{
    if (argc != 2) {
        WARN("usage: %s path/to/hx.8 > codegen/hx_specs_data.c\n",
             argv[0]);
        return 2;
    }

    size_t inlen = 0;
    char *input = slurp(argv[1], &inlen);
    if (!input) {
        WARN("FATAL: hx8_to_c: read failed\n");
        return 2;
    }

    /* Output to stdout. */
    FILE *out = stdout;

    fprintf(out,
"/*\n"
" * codegen/hx_specs_data.c -- AUTO-GENERATED by tools/hx8_to_c from hx.8\n"
" *                            -- DO NOT EDIT BY HAND --\n"
" *\n"
" * Each entry pairs an hx.8 algorithm row (eN, NAME, EXPRESSION) with\n"
" * the hx_program produced by hx_compile_expr() at build time. Outlier\n"
" * entries (troff markup in the EXPRESSION column, not a real hx\n"
" * expression) carry .is_outlier=1 and .program=NULL. Compile-failed\n"
" * entries (hx parser rejected the expression) carry .compile_failed=1\n"
" * and .program=NULL. The codegen walker only consumes .program when\n"
" * both flags are zero.\n"
" *\n"
" * Per project_hx_codegen_phase2_3_spec_2026-05-21.md sub-phase 2a.2.\n"
" * Do NOT check this file into RCS; it is regenerated on every make.\n"
" */\n"
"\n"
"#include <stddef.h>\n"
"#include <stdint.h>\n"
"#include \"../hx_vm.h\"\n"
"#include \"hx_spec_entry.h\"\n"
"\n");

    /* Walk lines. */
    char *line = input;
    int total = 0, non_outlier = 0, outlier_n = 0, compile_failed = 0;
    int emitted_eidx = 0;

    /* First pass: parse + emit per-entry statics. Track per-entry
     * (eidx, type, name, line, is_outlier, compile_failed) for the
     * final array emit. We dynamically grow a small in-memory table. */
    struct entry_meta {
        int  eidx;            /* dense codegen index */
        int  type;            /* eN */
        char *name;
        int  hx8_line;
        int  is_outlier;
        int  compile_failed;
        char *expr_cleaned;   /* malloc'd; kept for emitting in entry comment */
        int  emit_class;      /* 5c.1: enum hx_emit_class (0 SINGLE) */
        int  note_ref;        /* 5c.1: hx.8 Note [N] ref; 0 = none */
        hx_program *prog;     /* Tier 2 F1: retained for intra-catalog
                               * duplicate-warning pass; NULL for
                               * outlier/compile-fail. Freed after the pass. */
    } *meta = NULL;
    int meta_cap = 0, meta_n = 0;

    /* Feature 5: load the optional DEDUP_OK sidecar before the walk so a
     * `.\" DEDUP_OK` troff line in hx.8 and the sidecar both feed the same
     * suppression set. */
    dedup_ok_load_sidecar("tools/dedup_ok.txt");

    int lineno = 0;
    while (line && *line) {
        char *nl = strchr(line, '\n');
        int linelen = nl ? (int)(nl - line) : (int)strlen(line);
        char saved = line[linelen];
        line[linelen] = '\0';
        lineno++;

        /* Feature 5: a `.\" DEDUP_OK eN [...]: reason` troff-comment line
         * adds eN(s) to the suppression set. Recognized before row parse;
         * such lines are not rows (parse_row would reject them anyway). */
        if (dedup_ok_try_line(line)) {
            line[linelen] = saved;
            if (!nl) break;
            line = nl + 1;
            continue;
        }

        int type;
        char *name = NULL, *expr = NULL;
        if (parse_row(line, &type, &name, &expr)) {
            total++;
            /* Sub-phase 5c.1 (2026-05-27): multi-emit annotation.
             *
             * Record the hx.8 "(see Note [N])" reference (if any) for
             * EVERY row so the entry carries note_ref. For the ACTIVATED
             * multi-emit member e123 MD5MD5PASS (Note [24]) ONLY, strip
             * the annotation so the leading "md5(md5(pass).pass)" compiles
             * to a real 6-op FAMILY_MD5PASS program and flag emit_class =
             * HX_EMIT_MULTI (=1). All other Note-[N] entries (e687 sha1(),
             * e663 T{...}, and the other 22 Note-[24] members) STAY
             * outliers/override exactly as before -- only their note_ref
             * is recorded; emit_class defaults SINGLE. Gating on type==123
             * keeps the change minimal (R4) and is the single member we
             * prove the multi-emit pattern on this sub-phase. */
            int emit_class = 0;            /* HX_EMIT_SINGLE */
            int note_ref   = extract_note_ref(expr);
            int activate_multi = (type == 123 && note_ref == 24);
            int is_out;
            char *clean;
            if (activate_multi) {
                /* e123's leading text is a real 6-op FAMILY_MD5PASS
                 * expression; the "(see Note [24])" is wrapped in troff
                 * italics (\fI ... \fP) in hx.8. Strip troff FIRST, then
                 * the Note annotation, leaving the bare expression to
                 * compile. Re-check is_markup_outlier on the fully-cleaned
                 * text (it should now be a non-outlier real expression).
                 * Other Note-[N] members do NOT take this path -- they
                 * keep their existing outlier/override routing. */
                char *troff_clean = strip_troff_escapes(expr);
                clean = strip_note_markup(troff_clean);
                free(troff_clean);
                /* Trim any trailing whitespace left after the cut. */
                size_t cl = strlen(clean);
                while (cl > 0 && (clean[cl-1] == ' ' || clean[cl-1] == '\t'))
                    clean[--cl] = '\0';
                is_out = is_markup_outlier(clean);
                emit_class = 1;            /* HX_EMIT_MULTI */
            } else {
                is_out = is_markup_outlier(expr);
                clean  = strip_troff_escapes(expr);
            }
            /* Strip any troff escapes from the NAME column too -- the
             * \s-2 ... \s+2 size markers used on long names slip through
             * parse_row as literal backslash chars, which the C compiler
             * later flags as unknown-escape-sequence in the .name = "..."
             * literal. Replace in-place: stripped string is no longer than
             * input. */
            char *name_clean = strip_troff_escapes(name);
            free(name);
            name = name_clean;
            int cf = 0;
            hx_program *prog = NULL;

            if (!is_out) {
                /* Pre-register every identifier-followed-by-paren as a
                 * stub function so hx_compile_expr never hits its
                 * exit(1) path for "unknown function". The standalone
                 * build only includes md5/sha/etc.; the long tail of
                 * hashpipe-only crypts are absent from the registry. */
                prescan_register_stubs(clean);
                prog = hx_compile_expr(clean, NULL);
                if (!prog) {
                    cf = 1;
                    compile_failed++;
                    WARN("hx8_to_c: line %d e%d %s: compile failed for `%s`\n",
                         lineno, type, name, clean);
                }
            }
            if (is_out) outlier_n++;
            if (!is_out && !cf) non_outlier++;

            /* growth */
            if (meta_n >= meta_cap) {
                meta_cap = meta_cap ? meta_cap * 2 : 64;
                meta = (struct entry_meta *)realloc(meta,
                          (size_t)meta_cap * sizeof(*meta));
            }
            meta[meta_n].eidx           = emitted_eidx;
            meta[meta_n].type           = type;
            meta[meta_n].name           = name;
            meta[meta_n].hx8_line       = lineno;
            meta[meta_n].is_outlier     = is_out;
            meta[meta_n].compile_failed = cf;
            meta[meta_n].expr_cleaned   = clean;
            meta[meta_n].emit_class     = emit_class;  /* 5c.1 */
            meta[meta_n].note_ref       = note_ref;    /* 5c.1 */
            meta[meta_n].prog           = prog;        /* Tier 2 F1: retain */
            meta_n++;

            if (prog) {
                /* per-entry header comment */
                fprintf(out, "/* eidx=%d e%d %s : `%s` (hx.8 line %d) */\n",
                        emitted_eidx, type, name, clean, lineno);
                /* code + sidecar + program */
                /* sidecar call-names */
                fprintf(out, "static const char *_hx_callnames_%d[] = {\n",
                        emitted_eidx);
                for (int i = 0; i < prog->ncode; i++) {
                    if (prog->code[i].op == OP_CALL &&
                        prog->code[i].u.call.entry)
                        fprintf(out, "    [%d] = \"%s\",\n", i,
                                prog->code[i].u.call.entry->name);
                    else
                        fprintf(out, "    [%d] = NULL,\n", i);
                }
                fprintf(out, "};\n");

                /* code[] */
                fprintf(out, "static const hx_inst _hx_code_%d[%d] = {\n",
                        emitted_eidx, prog->ncode);
                for (int i = 0; i < prog->ncode; i++)
                    emit_inst(out, &prog->code[i], i, prog);
                fprintf(out, "};\n");

                /* strings[] + strlens[] */
                if (prog->nstrings > 0) {
                    fprintf(out,
                        "static const char *_hx_strings_%d[%d] = {\n",
                        emitted_eidx, prog->nstrings);
                    for (int i = 0; i < prog->nstrings; i++) {
                        fprintf(out, "    [%d] = ", i);
                        emit_cstr(out, prog->strings[i], prog->strlens[i]);
                        fprintf(out, ",\n");
                    }
                    fprintf(out, "};\n");
                    fprintf(out, "static const int _hx_strlens_%d[%d] = {",
                            emitted_eidx, prog->nstrings);
                    for (int i = 0; i < prog->nstrings; i++)
                        fprintf(out, " %d,", prog->strlens[i]);
                    fprintf(out, " };\n");
                }

                /* varnames[] */
                fprintf(out,
                    "static const char *_hx_varnames_%d[%d] = {\n",
                    emitted_eidx, prog->nvars);
                for (int i = 0; i < prog->nvars; i++)
                    fprintf(out, "    [%d] = \"%s\",\n", i,
                            prog->varnames[i] ? prog->varnames[i] : "");
                fprintf(out, "};\n");

                /* program */
                emit_entry_program(out, emitted_eidx, prog);
                fprintf(out, "\n");

                /* Tier 2 F1: do NOT free prog here -- retained in
                 * meta[].prog for the intra-catalog duplicate-warning
                 * pass, then freed in the cleanup loop. */
            } else {
                fprintf(out, "/* eidx=%d e%d %s : %s (hx.8 line %d) */\n",
                        emitted_eidx, type, name,
                        is_out ? "OUTLIER" : "COMPILE_FAILED", lineno);
            }
            emitted_eidx++;
            /* note: name/clean kept alive in meta for final array emit */
        } else {
            /* not a row */
        }

        line[linelen] = saved;
        if (!nl) break;
        line = nl + 1;
    }

    /* Final array. */
    fprintf(out,
"const struct hx_spec_entry hx_specs_data[] = {\n");
    for (int i = 0; i < meta_n; i++) {
        struct entry_meta *m = &meta[i];
        fprintf(out, "    { .job_enum = %d, .name = \"%s\", .expression = ",
                m->type, m->name);
        if (m->expr_cleaned)
            emit_cstr(out, m->expr_cleaned, (int)strlen(m->expr_cleaned));
        else
            fprintf(out, "NULL");
        fprintf(out, ", .hx8_line = %d, .is_outlier = %d, .compile_failed = %d, ",
                m->hx8_line, m->is_outlier, m->compile_failed);
        /* Sub-phase 5a.1 (2026-05-22): emit .program AND .call_names.
         * Both NULL for outliers/compile-fails; both populated otherwise.
         * .call_names points at the per-program _hx_callnames_NNN[]
         * static sidecar emitted earlier in this file.
         *
         * Sub-phase 5c.1 (2026-05-27): also emit .emit_class + .note_ref.
         * emit_class is HX_EMIT_MULTI (=1) only for the activated e123
         * multi-emit member; SINGLE (=0) for everyone else. note_ref
         * carries the hx.8 "(see Note [N])" reference number (0 = none).*/
        if (m->is_outlier || m->compile_failed)
            fprintf(out, ".program = NULL, .call_names = NULL, "
                         ".emit_class = %d, .note_ref = %d },\n",
                    m->emit_class, m->note_ref);
        else
            fprintf(out, ".program = &_hx_program_%d, "
                         ".call_names = _hx_callnames_%d, "
                         ".emit_class = %d, .note_ref = %d },\n",
                    m->eidx, m->eidx, m->emit_class, m->note_ref);
    }
    fprintf(out, "};\n"
                 "const int hx_specs_count = %d;\n\n", meta_n);

    /* Lookup helper. */
    fprintf(out,
"const struct hx_spec_entry *hx_specs_lookup(int job_enum) {\n"
"    for (int i = 0; i < hx_specs_count; i++)\n"
"        if (hx_specs_data[i].job_enum == job_enum)\n"
"            return &hx_specs_data[i];\n"
"    return NULL;\n"
"}\n");

    /* ---------- Tier 2 Feature 1: build-time intra-catalog warning ----------
     *
     * O(N^2) pairwise comparison over the COMPILED entries (those with a
     * retained prog). Each bytecode-identical pair (under the SHARED
     * programs_equal() -- Layer 1 + role-canon + Layer 2 commutative)
     * emits ONE informational WARNING to stderr. Entries whose eN is in
     * the DEDUP_OK suppression set (Feature 5) are excluded from BOTH
     * sides of every pair.
     *
     * CRITICAL: these are WARNINGS, NOT errors. The build MUST still
     * succeed -- the ~55 known duplicate groups are INTENTIONAL historical
     * aliases (feedback_catalog_aliases_are_historical_dont_alter.md). We
     * never alter, never fail. The pass only surfaces the dedup truth on
     * every regenerate. Return value stays 0 regardless of warning count.
     *
     * The live programs carry resolved .u.call.entry pointers, so the
     * comparator resolves call names directly (NULL call_names sidecar is
     * fine -- programs_equal falls back to entry->name). Comparison reads
     * only; absorbed[] collapses an N-way group into one warning block.
     */
    {
        unsigned char *absorbed = (unsigned char *)calloc((size_t)meta_n, 1);
        int n_pairs = 0, n_groups = 0, n_suppressed = 0;
        if (!absorbed) {
            WARN("hx8_to_c: WARN: OOM in dedup pass; skipping\n");
        } else {
            for (int i = 0; i < meta_n; i++) {
                if (absorbed[i]) continue;
                if (!meta[i].prog) continue;
                if (dedup_ok_has(meta[i].type)) continue;

                int group_started = 0;
                for (int j = i + 1; j < meta_n; j++) {
                    if (absorbed[j]) continue;
                    if (!meta[j].prog) continue;
                    if (dedup_ok_has(meta[j].type)) continue;
                    if (!programs_equal(meta[i].prog, NULL,
                                        meta[j].prog, NULL))
                        continue;
                    if (!group_started) {
                        n_groups++;
                        group_started = 1;
                        WARN("hx8_to_c: WARNING: intra-catalog duplicate: "
                             "e%d %s (hx.8 line %d) has bytecode-identical "
                             "signature to:\n",
                             meta[i].type, meta[i].name, meta[i].hx8_line);
                    }
                    WARN("hx8_to_c: WARNING:   == e%d %s (hx.8 line %d)\n",
                         meta[j].type, meta[j].name, meta[j].hx8_line);
                    absorbed[j] = 1;
                    n_pairs++;
                }
                if (group_started) absorbed[i] = 1;
            }
            /* Count suppressed entries for the summary. */
            for (int i = 0; i < meta_n; i++)
                if (meta[i].prog && dedup_ok_has(meta[i].type)) n_suppressed++;
            free(absorbed);
        }
        if (n_groups > 0)
            WARN("hx8_to_c: NOTE: %d intra-catalog duplicate group(s), "
                 "%d alias pairing(s). These are INTENTIONAL historical "
                 "aliases unless newly introduced -- the build is NOT "
                 "affected. Annotate reviewed entries via tools/dedup_ok.txt "
                 "or a `.\\\" DEDUP_OK eN: reason` line in hx.8 to silence. "
                 "(%d entr%s currently DEDUP_OK-suppressed.)\n",
                 n_groups, n_pairs, n_suppressed,
                 n_suppressed == 1 ? "y" : "ies");
    }

    /* Cleanup. */
    for (int i = 0; i < meta_n; i++) {
        free(meta[i].name);
        free(meta[i].expr_cleaned);
        if (meta[i].prog) hx_program_free(meta[i].prog);
    }
    free(meta);
    free(input);
    free(g_dedup_ok);

    WARN("hx8_to_c: total=%d non_outlier=%d outlier=%d compile_failed=%d\n",
         total, non_outlier, outlier_n, compile_failed);
    return 0;
}
